### ISSUE TITLE
Uncaught Error: Class "Tqdev\PhpCrudApi\Config"  not found in api.php:12741

### ISSUE THREAD

**Issue by rafaelgimenes** [mevdschee/php-crud-api#1007]
Hi, 
I'm getting error its happen on php -S and also in nginx.
Sqlite3  its a simple database in sqlite3, I also used the same on another computer instalation (php 7.3) with no errors,

![image](https://github.com/mevdschee/php-crud-api/assets/9700683/e4d17929-89c6-4e55-a9ef-3257c9070603)

anyone can help-me?  I Just download the api.php, set my sqlite3 config at bottom
`/ file: src/index.php
namespace Tqdev\PhpCrudApi {

    use Tqdev\PhpCrudApi\Api;
    use Tqdev\PhpCrudApi\Config;
    use Tqdev\PhpCrudApi\RequestFactory;
    use Tqdev\PhpCrudApi\ResponseUtils;

    $config = new Config([
         'driver' => 'sqlite',
        'address' => '../db/mt.db',
        'username' => '',
        'password' => '',
        'database' => 'mt.db',
         'debug' => true
    ]);
    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    ResponseUtils::output($response);
}`

**PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies**

**php -m**
 [PHP Modules], calendar, Core, ctype, curl, date, dom, exif, FFI, fileinfo, filter, ftp, gd, gettext, hash, iconv, json, libxml, mbstring, odbc, openssl, pcntl, pcre, PDO, PDO_ODBC, pdo_sqlite, Phar, posix, random, readline, Reflection, session, shmop, SimpleXML, sockets, sodium, SPL, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, Zend OPcache, zip, zlib, , [Zend Modules], Zend OPcache

any tip and concern  about that?

**Comment by apps-caraga** [comment]
Can you update *use Tqdev\PhpCrudApi\Config;* 
to 
*use Tqdev\PhpCrudApi\Config\Config;*

**Comment by rafaelgimenes** [comment]
thank you its fixed my issue.
