### ISSUE TITLE
Update with "where"

### ISSUE THREAD

**Issue by focussing** [mevdschee/php-crud-api#1012]
Hi Maurits,

I am developing a CMS for editing content for multiple languages.
Basically I want to store for one element let's say 4 languages of that styled content in my database so I could easily retrieve that using filters like "filter=page_id,eq,4 &filter=rank,eq,16 &filter=language,eq,NL"

Right now I am thinking about storing this like
UPDATE <table> WHERE language='NL' and page_id=4 and rank=16
UPDATE <table> WHERE language='DE' and page_id=4 and rank=16
etc.

Is this possible using the php-crud-api?
If not do you have a suggestion how to deal with this?

Looking forward to hearing from you
Best regards,
Raymond

**Comment by mevdschee** [comment]
Hi Raymond,

To answer your specific questions:

>Is this possible using the php-crud-api?

No, it is not.

>If not do you have a suggestion how to deal with this?

Do multiple http requests. 

Kind regards, Maurits

**Comment by focussing** [comment]
Hi Maurits,

Thank you for your suggestions. During the last 2 weeks I have implemented the whole system, and soon it will arrive online.

Reading is easy of course.
The update function needs already to be done via separate api calls one at a time using the already known record id.

Creating and deleting records I did via an "await-loop" which worked fine.
Just this morning I came across the Batch operations, and I already implemented the delete colums-rows-pages already using that very efficient functionality!

One question remains, about creating records in batch. How should I provice the IDs in the url? The IDs are normally not given when creating a record as these are generated in the database itself.

Kind regards,
Raymond

**Comment by mevdschee** [comment]
Hi Raymond,

I hope you are aware of the "Batch Operations" section in the manual. You can find various useful examples there including batch creation of records.

see: https://github.com/mevdschee/php-crud-api?tab=readme-ov-file#batch-operations

Kind regards,

Maurits

**Comment by focussing** [comment]
I am aware, this morning I came across that part in the docs. However I don't see a CREATE batch example...

**Comment by focussing** [comment]
The solution is simple, just post the objects and do not use a key :)
Thanks @mevdschee for this beautiful single file api 👍

**Comment by mevdschee** [comment]
Thank you for your kind words. I updated the README to include this information, see: https://github.com/mevdschee/php-crud-api/commit/c38083fc593d67842b65be01701a957150082427

**Comment by focussing** [comment]
Topper!
