### ISSUE TITLE
Synchronization between local IndexedDB and MySQL Database.

### ISSUE THREAD

**Issue by scriptPilot** [mevdschee/php-crud-api#1017]
Based on this API and Dexie.js, I have created a synchronization feature between local IndexedDB and a MySQL database.
You maybe want to add it to the link list :-)

https://github.com/scriptPilot/dexie-mysql-sync

**Comment by scriptPilot** [comment]
PS: Just working on a version 2 where hooks are used and the implementation will work with two lines of code only and no specific wrapper functions :-)

**Comment by scriptPilot** [comment]
Now the implementation is very easy and does not require any special wrappers 🥳

https://github.com/scriptPilot/dexie-mysql-sync

**Comment by mevdschee** [comment]
Added to the README
