### ISSUE TITLE
Question: Add property on create

### ISSUE THREAD

**Issue by scriptPilot** [mevdschee/php-crud-api#1019]
On creation of a new record, I would like to add another property `owner = $_SESSION['user']['id']` - is there any middleware I can use to archive this?

**Comment by apps-caraga** [comment]
You can use the multiTenancy middleware to automatically insert  (and also filter) the current user's ID to a related table. Anyway, check https://github.com/mevdschee/php-crud-api/issues/754 if you got similar use case. If not, you can provide more data on your specific requirement

**Comment by mevdschee** [comment]
I agree, please let us know if you need more information or guidance.

**Comment by scriptPilot** [comment]
Perfect - thanks both of you!
