### ISSUE TITLE
check if field is blank without being NULL

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#102]
how would i go about seeing if a field is blank, meaning no data. it's not a NULL field.

**Comment by ubergeekzone** [comment]
Got it figured out it just goes like this filter[]=addr_one,ne,&filter[]=addr_two,ne,&transform=1 you just leave the last parameter in the filter after your operator blank.

**Comment by bigteejay** [comment]
I tried `https://www.somedomain.com/api/index.php/my_table/?order=time_stamp,asc&columns=my_column&filter=my_column,ne,&transform=1` and all I am getting are the fields that **arent** blank.

Better to discuss here, or create a new issue?

**Comment by mevdschee** [comment]
Here is fine: NE means Not Equal, EQ means equals. Change NE into EQ and the query should behave as expected.

**Comment by bigteejay** [comment]
Thanks for the quick reply!  I'm still not having any success.  I even tried reducing the number of variables/factors involved and used `/api/index.php/my_table/?filter=my_column,eq` off the base API, which returned no rows :-(

Even though there are blanks...
![image](https://user-images.githubusercontent.com/14826513/40591535-bfeae084-61c7-11e8-9169-9d0e124b9766.png)

**Comment by mevdschee** [comment]
Maybe the blanks are nulls? Try using IS instead of EQ.

**Comment by mevdschee** [comment]
Maybe the blanks are nulls? Try using IS instead of EQ.

**Comment by bigteejay** [comment]
No luck with IS either.  I even just went into the underlying MySQL (MariaDB, but I can't imagine that matters?) table and...
````
update my_table
set my_column = ''
where id = 3;  /* random id i know exists/usable , but only one blank then*/
````
...just so I **knew** that there was a blank/`''` value to find, and nothing but a list of columns was returned (and an empty `records:[]` object/array).

**Comment by bigteejay** [comment]
Ah, success!  My apologies if I missed this previously, but it was a trailing comma that did it!

**Comment by bigteejay** [comment]
`/api/index.php/my_table/?filter=my_column,eq,`

With the "eq**.**" being what had escaped me.
