### ISSUE TITLE
PUT using curl comes back successful but the record is not actually updated

### ISSUE THREAD

**Issue by pottertech** [mevdschee/php-crud-api#1022]
Here is the code I am using to attempt a PUT/UPDATE record and I hope you can tell me why this does not update the record.

`
              $values['host'] = trim($_POST['arguments'][0]); // private IP
              $user_id = trim($_POST['arguments'][1]); // user id
              $record_id = trim($_POST['arguments'][2]); // record id
              $exchange = strtoupper(trim($_POST['arguments'][3])); // exchange
              $symbol = strtoupper(trim($_POST['arguments'][4])); // exchange
           	   
               $ch = curl_init();
               $json_data = json_encode(array(
    		       "track_action" => "OWNMAINTUI"
               ));           	   
               
               // Set cURL options
               $url = "http://10.8.3.44/DCTAPI.php/records/DCT_positions/" . $record_id;
               curl_setopt($curl, CURLOPT_URL, $url);
               curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PUT");
               curl_setopt($curl, CURLOPT_POSTFIELDS, $json_data);
               curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
               curl_setopt($curl, CURLOPT_HTTPHEADER, array( 
                               'Content-Type: application/json', 
                               'Content-Length: ' . strlen($json_data)) 
               );

               // Execute cURL request and get the response
               $response = curl_exec($curl);
               // Check for errors
               if ($response === false) {
                   $aResult['result'] = "ERROR: (" . $record_id . ") " . $symbol . " position was not updated.";
               } else {
                   // Output the response
                   $aResult['result'] = "SUCCESS: (" . $record_id . ") " . $symbol . " position was updated.";
               }

               // Close cURL session
               curl_close($curl);
`

**Comment by pottertech** [comment]
Never mind, I found my mistake. The first line  $ch = curl_init(); should be  $curl = curl_init();

Too much late-night programming!

**Comment by mevdschee** [comment]
Thank you for reporting your success! Kind regards, Maurits
