### ISSUE TITLE
"Route '' not found"

### ISSUE THREAD

**Issue by ykhaled** [mevdschee/php-crud-api#1025]
I had api.php first version working fine for many years now. I decided to give version 2 ago. I placed the new api.php in new folder and I configured the database connection with the same settings from version 1 but I can not get v2 to work. I keep getting the error message "Route '' not found". I tested exactly the same request.

Request: https://someSite.com/api.php/TableName?transform=1&filter=FieldName,eq,20027747

There are no logs - so I'm not sure what I did incorrectly. 

I'm running:
mysql  Ver 14.14
PHP 7.2.24-0ubuntu0.18.04.17 (cli) (built: Feb 23 2023 13:29:25) ( NTS )

Any advice is appreciated.

**Comment by mevdschee** [comment]
You should add '/records/' between api.php and TableName.

**Comment by ykhaled** [comment]
That worked! thanks!. BTW, is there an ORM mapping based on C#?

**Comment by mevdschee** [comment]
No there is not
