### ISSUE TITLE
Direct usage of PHP CRUD API functions in external PHP Files

### ISSUE THREAD

**Issue by prof5alil** [mevdschee/php-crud-api#1027]
Hello,

I'm currently exploring the PHP CRUD API, and I'm excited about the possibility of using its features directly in other PHP files without relying on URL requests. I'm not very experienced in PHP coding, particularly with Object-Oriented Programming. I'd like to be able to pass a simple string, such as ("get", "records/users/1?exclude,password"), to a function and receive the response in JSON format. Could you please explain how to handle connection and closing the database connection, as well as how to perform CRUD operations in external PHP files?

I'm unsure if I'm using the right tool here, or if there are better alternatives available. At the moment, I'm considering using api.php because I'm already familiar with the PHP CRUD API (passing queries through URLs) and I'm thinking of utilizing api.php in this manner to reduce the amount of code in my project.

A big thanks for creating such a fantastic tool.

Cheers,

**Comment by apps-caraga** [comment]
PHP-CRUD-API needs to be run in a server to work, so you definitely can't do away with URL requests. Anyway, since you'll be running your external php on a server, you'll still be working with URL requests, so why don't you want to deal with such?

**Comment by prof5alil** [comment]
I understand that in certain frontend scenarios, it's common to use HTTP URL requests for all operations. However, in backend cases, where we need to manage databases without exposing operations to frontend users (who might see the HTTP requests in network inspection tools), a different approach is needed.

For instance, when developing a backend admin panel, it's often more effective to handle database operations directly within PHP files. This brings me to my question: having separate files and functions in the same project that manage the same database could lead to unnecessary redundancy and complexity. Instead, it might be more practical to utilize the internal functions of the PHP CRUD API to manage database operations directly within other PHP files.

**Comment by buckybytes** [comment]
> For instance, when developing a backend admin panel, it's often more effective to handle database operations directly 

It is definitely more efficient to handle database operations with one-liners, rather than parse them through an API.


>having separate files and functions in the same project that manage the same database could lead to unnecessary redundancy and complexity. Instead, it might be more practical to utilize the internal functions of the PHP CRUD API to manage database operations directly within other PHP files.

If you carefully design your program, you can avoid unnecessary redundancy in your database logic.  If you are going to use the API, use the API for everything and you wouldn't have redundancy either.  

As far as your concerns about exposing operations to users- as long as you are making the requests from the backend, and not through the front end with AJAX, your users will not see them in their browser's developer console, because those requests never make it to the browser.

**Comment by apps-caraga** [comment]
> For instance, when developing a backend admin panel, it's often more effective to handle database operations directly within PHP files.

Even if it is a backend admin panel, if you're using PHP it still have to access it via user interface which is most likely a front-end UI that is accessed via URL

**Comment by prof5alil** [comment]
@buckybytes, I understand your point, but it's worth noting that when we talk about "users" in this context, we're not just referring to frontend users. In systems like an LMS (Learning Management System), there are various types of users with different roles and permissions. These users include administrators, teachers, and even students who may need access to certain backend interfaces depending on their assigned roles. So, when we discuss concerns about exposing operations to users, it's not limited to frontend users.

@apps-caraga, Sending requests to the browser, only to resend them to the server for data processing, can introduce unnecessary delays in the code execution process. Instead, using PHP CRUD API directly could be a more professional and streamlined solution. It would be akin to frameworks like RedBeanPHP or Eloquent for Laravel, or the Doctrine ORM. This feature would greatly enhance the usability and efficiency of the PHP CRUD API.

In my opinion, this feature is already available in the PHP CRUD API, with the only missing piece being proper documentation. Once documented, it would greatly simplify the development process and make the PHP CRUD API even more powerful and user-friendly.

**Comment by mevdschee** [comment]
>Could you please explain how to handle connection and closing the database connection, as well as how to perform CRUD operations in external PHP files?

As @apps-caraga expained PHP-CRUD-API is not an ORM (Object Relational Mapper). And even if it was usable as such, there are far better ORMs out there. I especially fond of: https://redbeanphp.com

Warnings aside, I did what you are asking for in PHP-CRUD-ADMIN and use a LocalCaller class to circumvent Curl calls. 

see: https://github.com/mevdschee/php-crud-admin/blob/main/src/Tqdev/PhpCrudAdmin/Client/LocalCaller.php

**Comment by prof5alil** [comment]
hello Maurits and thank you for so much for your replay,

> And even if it was usable as such, there are far better ORMs out there. I especially fond of: https://redbeanphp.com/
I'am in love with PHP CRUD API, and I intend to continue using it as API and as well ORM for whole my life ^_^

> I did what you are asking for in PHP-CRUD-UI and use a LocalCaller class to circumvent Curl calls. That project can either run on a local PHP-CRUD-API or one over Curl calls.
> see: https://github.com/mevdschee/php-crud-ui/blob/main/src/Tqdev/PhpCrudUi/Client/LocalCaller.php

Yes this is exactly what I am asking for !! As I mentioned :
> I'm not very experienced in PHP coding, particularly with Object-Oriented Programming

Could you please do me a favor and explain where to place the file LocalCaller.php ? (Should it be in the same folder as api.php?) Also, could you please clarify how to use it? For example, if I have an index.php file in the root directory and the api.php is located in the /api folder, how would I execute a call like this:

```
require_once 'api/api.php';
require_once 'api/LocalCaller.php';

$username=call('GET', '/records/' . rawurlencode("users"), $_SESSION['user']);
echo "hello ".$username;
```

 I apologize for my lack of expertise in PHP and OOP.

**Comment by mevdschee** [comment]
I didn't test it, but something like this:

    $caller = new \Tqdev\PhpCrudUi\Client\LocalCaller($config)
    $user = $caller->call('GET', '/records/users');
    echo $user['username'];

I hope this helps.
