### ISSUE TITLE
Found this PDOException occurred (enable debug mode) in message

### ISSUE THREAD

**Issue by Hakkey** [mevdschee/php-crud-api#1030]
![Screenshot (118)](https://github.com/mevdschee/php-crud-api/assets/66235760/6715b930-eeae-4e63-828c-2221ae5fdd08)

i got this error when i tried to fetch the "users" table from my db of mysql

what is the possible error for this? thanks!

**Comment by mevdschee** [comment]
Hi. Something went wrong in the PDO driver. Please enable debug in the config and check the (HTTP) response headers in the network tab of the developer tools. Kind regards, Maurits

**Comment by Hakkey** [comment]
![Screenshot (120)](https://github.com/mevdschee/php-crud-api/assets/66235760/97ec0bee-2adc-47c1-a793-e8cb59fb0ef8)

is it this one?

**Comment by mevdschee** [comment]
There is a config setting named "debug" and the "Headers" tab is two tabs to the left on the screenshot.

**Comment by Hakkey** [comment]
i have found the error which why the connection is refused, so in my case the database is from another host let's say "10.9.0.0.1". Is there a way to pass the db host to the config model?

**Comment by mevdschee** [comment]
Yes, you can set the "address", as per README:

> "address": Hostname (or filename) of the database server (localhost)

from: https://github.com/mevdschee/php-crud-api?tab=readme-ov-file#configuration

**Comment by Hakkey** [comment]
Okay got it, thanks! 

Cool project anyway keep it up
