### ISSUE TITLE
Route Not Found Error Upon Deployment to Online Server

### ISSUE THREAD

**Issue by khalilghenimi** [mevdschee/php-crud-api#1031]
Hello,

The API work fine on my local machine, but upon deployment to an online server, it returns the error {"code":1000,"message":"Route '/sub/api/records/table' not found"}. I have tested it on two different domains, one using Cloudflare and the other on OVH servers.

Any insights or guidance on debugging this discrepancy would be greatly appreciated.

**Comment by mevdschee** [comment]
Hi, I guess the server config is not correct, check out this (new) part of the readme:

https://github.com/mevdschee/php-crud-api?tab=readme-ov-file#pretty-url

**Comment by khalilghenimi** [comment]
Thank you for your reply, Maurits. Yes, I have the same .htaccess configuration, and it's still not working.

**Comment by mevdschee** [comment]
It doesn't seem like you have a problem with this software. I'm closing the issue for now.

**Comment by khalilghenimi** [comment]
I have multiple WordPress and Joomla CMS installations on the same server, and all are functioning well. Also, I have tested the database connection parameters and executed several SQL queries, all of the have been successful replies. The error is likely stemming from the .htaccess configuration or mod_rewrite.c because when I make the .htaccess file as follows:
```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ api.php [QSA,L]
</IfModule>
```
the error is : 
`File not found.`

I have asked ChatGPT for the solution it gave me this code : 
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ api.php [QSA,L]
```
And it successfully reads the api.php file, even when I include some echo statements in the api.php file, it displays the expected content. However, the error is :
`{"code":1000,"message":"Route '\/api\/records\/menus' not found"}`

If you want to know more about the server configuration : 

PHP Version : 8.2.10
Build System : Linux d73abf0b4d30 5.10.0-25-cloud-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
Server API : FPM/FastCGI
Virtual Directory Support : disabled
Apache 2.0 Handler : Ian Holsman, Justin Erenkrantz (based on Apache 2.0 Filter code)
CGI / FastCGI : Rasmus Lerdorf, Stig Bakken, Shane Caraveo, Dmitry Stogov

If you require additional information about the server, I am happy to provide it.

Thank you so much.
