### ISSUE TITLE
How to use UUID as primary key and return it

### ISSUE THREAD

**Issue by chattago2002** [mevdschee/php-crud-api#1036]
Hi everyone.

I'm trying to use UUIDv4 as "id" field (primary key). I set it as CHAR(36) and tha value is created via MySQL trigger "before insert". The value is set in the right way but it's not returned.

I read other issues here about this case but solutions seems not to work.

P.S. I would prefer to create UUIDv4 server-side and not client-side as written in some of the above mentioned issues.

**Comment by mevdschee** [comment]
>The value is set in the right way but it's not returned.

Only auto increment values are returned.

>I would prefer to create UUIDv4 server-side

Why, there is no technical reason to do so.

**Comment by mevdschee** [comment]
See also https://github.com/mevdschee/php-crud-api/issues/932 and https://github.com/mevdschee/php-crud-api/issues/586
