### ISSUE TITLE
multi tenancy

### ISSUE THREAD

**Issue by wongdh** [mevdschee/php-crud-api#1041]
Hi need help with multi-tenancy. i have a situation where the system should switch databases based on parameters passed in. Can advise how to set up the middleware? and how it works. thanks

**Comment by mevdschee** [comment]
Hi and thank you for creating this issue. Please tell us what you tried an what problems you ran into and what you were sending, getting back, what you expected to get back and/or what error messages you received (copy all of these verbatim into the issue). Also state what versions you of Linux, database and PHP you are running. I'm closing this issue for now, but feel free to respond with more information and I'll consider re-opening. Kindest regards, Maurits
