### ISSUE TITLE
multiple API on same server

### ISSUE THREAD

**Issue by clysss** [mevdschee/php-crud-api#1044]
Hello,
I've 4 API xxApi.php on same server, each using a different controler.
In each, I use :
include api.include.php
everything go well until I made from :
aaApi an curl call to bbAPI
in this case there is a mismatch on the routes :
[25-Sep-2024 08:34:05 UTC] {routeList: [[{},"_list"],[{},"create"],[{},"read"],[{},"update"],[{},"delete"],[{},"increment"],[{},"_list"],[{},"read"],[{},"openapi"],[{},"ping"],[{},"createVendor"],[{},"getItem"],[{},"setItem"]],
 routeId: 12,
 routeInUse: [{},"setItem"]}
[25-Sep-2024 08:34:09 UTC] PHP Warning:  Undefined array key 12 in ..........\phpCrudApi\go\api.include.php on line 8038
[25-Sep-2024 08:34:09 UTC] {routeList: [[{},"_list"],[{},"create"],[{},"read"],[{},"update"],[{},"delete"],[{},"increment"],[{},"_list"],[{},"read"],[{},"openapi"],[{},"ping"],[{},"setItem"]],
 routeId: 12,
 routeInUse: null}

if I add a debug breakpoint and wait few seconds, the reply is OK 
[25-Sep-2024 08:34:20 UTC] {routeList: [[{},"_list"],[{},"create"],[{},"read"],[{},"update"],[{},"delete"],[{},"increment"],[{},"_list"],[{},"read"],[{},"openapi"],[{},"ping"],[{},"createVendor"],[{},"getItem"],[{},"setItem"]],
 routeId: 12,
 routeInUse: [{},"setItem"]}
[25-Sep-2024 08:34:31 UTC] {routeList: [[{},"_list"],[{},"create"],[{},"read"],[{},"update"],[{},"delete"],[{},"increment"],[{},"_list"],[{},"read"],[{},"openapi"],[{},"ping"],[{},"setItem"]],
 routeId: 10,
 routeInUse: [{},"setItem"]}

Finaly, I found a solution that seems really weird to me :
I made a copy of api.include.php to XXapi.include.php and each XXapi.php now include "his"  XXapi.include.php
with this, everything is OK. Do you have an idea why the routelist  seems shared from a 2 different API call ?
(i've test on 2 different PHP server, one on windows, one on Linux/prod environnemnt OVH)

**Comment by clysss** [comment]
in the previous msg rootId is [$routeNumbers[0]]

perhaps i've an idea where it comes from...
in line 8034 of api.include 
8034 : 
            $routeNumbers = $this->**getRouteNumbers($request);**
            if (count($routeNumbers) == 0) {
                return $this->responder->error(ErrorCode::ROUTE_NOT_FOUND, $request->getUri()->getPath());
            }
            try {
                $response = call_user_func($this->routeHandlers[$routeNumbers[0]], $request);

and in :
7998 : 
        private function getRouteNumbers(ServerRequestInterface $request): array
        {
            $method = strtoupper($request->getMethod());
            $path = array();
            $segment = $method;
            for ($i = 1; strlen($segment) > 0; $i++) {
                array_push($path, $segment);
                $segment = RequestUtils::getPathSegment($request, $i);
            }
            **return $this->routes->match($path);**
        }

so the issue seems to come from this->routes 
in 
class SimpleRouter implements Router
    {
  [...]
        public function __construct(string $basePath, Responder $responder, Cache $cache, int $ttl)
        {
7933 :            $this->routes = $this->loadPathTree();

and in 
7956 :      private function loadPathTree(): PathTree
        {
            $data = $this->cache->get('PathTree');

so when we make several call of different API, as the PathTree is cached, we don't have the last version of it
it seems the cache is updated soon after.. but not enough quicly

**Comment by clysss** [comment]
finaly SimpleRouter is called in :    class Api implements RequestHandlerInterface
        public function __construct(Config $config)

12289 :
           $cache = CacheFactory::create($config->getCacheType(), $prefix, $config->getCachePath());
            $reflection = new ReflectionService($db, $cache, $config->getCacheTime());
            $responder = new JsonResponder($config->getJsonOptions(), $config->getDebug());
            $router = new SimpleRouter($config->getBasePath(), $responder, $cache, $config->getCacheTime());


so : 
Question 1 : why routes are cached ? probably for perf issues ?..
Question 2 : when not defined, cache seems to be "nocache" type so basecache : 
Why basecache seems share as "Global" (in PHP sense) ?

An idea what I shoud do ?...

**Comment by mevdschee** [comment]
> So, if it's the same included api.include.php for all different xApi.php, the prefix is the same... and it bugs !

That is something I overlooked.

>Please give me your opinion that I can make a proposal :)

I'm not sure which one is the best. I think the "add a CachePrefix in the config file" is the best.

**Comment by clysss** [comment]
just one question before trying to update it :
what is the interest using FILE instead of $_SERVER["PHP_SELF"] ?
cf https://www.php.net/manual/en/reserved.variables.server.php
is it for executing not on a php web server ?

**Comment by clysss** [comment]
ah yes, PHP_SELF is crap because of easy injection 
so, why not $_SERVER['SCRIPT_NAME']  ? (as perhaps  $_SERVER['REQUEST_URI'] is not perfect because of rewritings?)

**Comment by mevdschee** [comment]
>so, why not $_SERVER['SCRIPT_NAME'] ?

There are many fcgi implementations. I'm not sure they all set that variable.

**Comment by clysss** [comment]
after rereading all the code, the easiest option seems to change only src/Tqdev/PhpCrudApi/Api.php

```
if (isset($_SERVER['SCRIPT_NAME'])) 
        $prefix = sprintf('phpcrudapi-%s-', substr(md5($_SERVER['SCRIPT_NAME']), 0, 8));
else
        $prefix = sprintf('phpcrudapi-%s-', substr(md5(__FILE__), 0, 8));

```

the adventage of option with cachePrefix is that we can reread more easily cachedata (as knowing wich MD5 is the good one is not easy)... but who needs ?! do you see other advantages ?
The disadvantages are that  it needs to make more modifications in src/Tqdev/PhpCrudApi/Config/Config.php and needs also not to forget to define it in each api call (in my case, I've at least 6 api running in //)

**Comment by mevdschee** [comment]
Lets think of other things that your 6 implementations differ in.. how about md5 of the entire json encoded config as a cache key?

**Comment by clysss** [comment]
Hmmm  very very clever:) you're a genius!

**Comment by clysss** [comment]
[pull request ](https://github.com/mevdschee/php-crud-api/pull/1046)

**Comment by mevdschee** [comment]
I merged and released. Your PR contained a syntax error: a closing bracket after `$config->getUID()`. I corrected that.
