### ISSUE TITLE
PATCH increments numerical value with the new value

### ISSUE THREAD

**Issue by apps-caraga** [mevdschee/php-crud-api#1048]
Assuming we have the following table,

```
+----------+-------------+------+-----+---------+----------------+
| Field    | Type        | Null | Key | Default | Extra          |
+----------+-------------+------+-----+---------+----------------+
| id       | int         | NO   | PRI | NULL    | auto_increment |
| testname | varchar(15) | NO   |     | NULL    |                |
| testdata | int         | YES  |     | NULL    |                |
+----------+-------------+------+-----+---------+----------------+
```

A **PATCH** operation will add the new `testdata `value to the existing one. So for example, if you have the value 10 in the `testdata`, a **PATCH** operation with the value 2 will result to the new value of 12 and so on. Is this by design? I was expecting that the value of the `testdata` will be replaced instead of incremented by the new value since a PATCH operation is supposed to do **partial** resource modification. By this, it means that it updates only the fields that is specified in the request body.

Another quirk is that when I PATCH just the non-numerical field, i.e., `testname`, it fails with code 9999, _Invalid parameter number: number of bound variables does not match number of tokens_

![image](https://github.com/user-attachments/assets/81341b91-ef53-4f3e-96e7-e7cb5f0258e7)

**Comment by mevdschee** [comment]
> A PATCH operation will add the new testdata value to the existing one. [...] Is this by design? 

Yes, it is. PUT already accepts partial updates. Atomic increments need their own verb, hence PATCH was (ab)used.

**Comment by apps-caraga** [comment]
Thanks for the response. Another thing to note, which may be already obvious to some, is that the field to be PATCHed should have an initial numerical value such as 0 instead of a NULL because any arithmetic operation with NULL (addition,subtraction etc.) results to NULL.
