### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by nenas04** [mevdschee/php-crud-api#106]
That api is amazing, nice work!
I have an issue with permissions, I want that the user has the permission to almost all tables unless one or two tables. How can I construct the function table_authorizer for that? Thank you!

**Comment by mevdschee** [comment]
```
'table_authorizer'=>function($cmd,$db,$tab) { return !in_array($tab,array('table_one','table_two'); },
```

**Comment by nenas04** [comment]
Inside the "$api = new PHP_CRUD_API(array(", right?
The api doens't show anything after that...
My code:
` $api = new PHP_CRUD_API(array(
 	'dbengine'=>'MySQL',
 	'hostname'=>'localhost',
	'username'=>'root',
	'password'=>'',
	'database'=>'database_slat',
 	'charset'=>'utf8',
	'table_authorizer'=>function($cmd,$db,$tab) { 
	  return !in_array($tab,array('tbl_slat','tbl_utilizador');
	},
 )));`

Help me please! Thank you!
