### ISSUE TITLE
Correct data type 

### ISSUE THREAD

**Issue by ManniManfred** [mevdschee/php-crud-api#11]
Is there a way to get the correct data type?
If the data type in mysql is INT(11), the type in php and then in json is always string.
I found a way with PDO to get the correct type in php by setting PDO::ATTR_EMULATE_PREPARES => false

Should I try to Implement support for PDO? Or is there a simpler way to achive the correct types?

**Comment by mevdschee** [comment]
There is an easier way (than PDO), you can for instance see how I did this for binary data. But first, let's analyze the problem:

- string, number, object, array, true, false, null are supported by JSON.
- array, object, true, false are not supported by MySQL.
- string, number, null are supported by both.
- nulls and strings are handled "correctly".
- PHP implicitly converts strings to numbers when needed.

I'm not saying there can not be a benefit. I think there could be two theoretical benefits in receiving floats from mysql as floats:

- Avoiding imprecision of string conversion
- Performance (no conversion, higher speed)

But do we actually achieve that when we would be receiving floats and ints from PDO? I wonder.

**Comment by mevdschee** [comment]
Maybe we should bypass PHP and output the MySQL string to javascript (JSON) directly. Still I'm worried about javascript's handling of MySQL types.

**Comment by mevdschee** [comment]
I see no solution for longs and decimals, but a conservative change would be to output small to normal sized integer types without quotes.

**Comment by ManniManfred** [comment]
In my case it would be ok, because I currently need it only for integers.

Am 02.01.2016 um 00:52 schrieb Maurits van der Schee:

**Comment by mevdschee** [comment]
As you can read [here](http://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin) only 53 bits of a 64 bit int are supported. So only 32 bit integers (or smaller) could go without quotes without losing precision.

**Comment by mevdschee** [comment]
Fixed in 8616b6795b3776f8bc88d54f7100212e6b6ef28b, but may cause issues on 8 byte integers (>53 bit) as they cannot be represented in JavaScript.
