### ISSUE TITLE
PUT Update +1

### ISSUE THREAD

**Issue by Silikowski** [mevdschee/php-crud-api#114]
Hi,

is there any way to add "+X" to a value of a table without doing a GET before and add the +1 to the actual value to PUT the final value?

It would be nice if the application could just send a PUT {"value":"+1"} to add +1 to the value in the database.

**Comment by mevdschee** [comment]
Can't you simply add a record for the increment and use a sum to find the counter value? In which case would this be very helpful? And would that case be limited to increment? Or also decrement, string append/prepend, add/subtract time ranges, etc..

**Comment by mevdschee** [comment]
Would you be helped by #53 so that you can prove your increment is done consistently?

**Comment by mevdschee** [comment]
I think this needs to be implemented using http://jsonpatch.com

**Comment by mevdschee** [comment]
After lot of thinking I implemented this as PATCH. It seems to be the closest match. Enjoy the feature!
