### ISSUE TITLE
auth.php usage

### ISSUE THREAD

**Issue by albmunmu** [mevdschee/php-crud-api#117]
Hello,

I downloaded your latest auth.php and after adding the code I am getting a login window with my browser requests, $_SERVER['PHP_AUTH_USER'] is supposedly sent in this requests or not? Should I set it in a post call? 

Which is the way to use this new auth.php, I'm not getting it clearly,

**Comment by mevdschee** [comment]
Simplest is to post "username" and "password" to "api.php" and uncomment the corresponding lines to include "auth.php" (that you need to download from [PHP-API-AUTH](https://github.com/mevdschee/php-api-auth)).

**Comment by albmunmu** [comment]
I've done as you asked and uncommented 

`
require 'auth.php'; // from the PHP-API-AUTH project, see: https://github.com/mevdschee/php-api-auth
`
And also added the file to the folder, I am now getting a blank page with no functionality. Is there something else I should do besides commenting that line out and adding the auth.php file to the same folder? I am using your latest uploaded api.php from php-crud-api and your latest auth.php from  PHP-API-AUTH.

**Comment by mevdschee** [comment]
Please also uncomment the 8 lines below:

    // uncomment the lines below for form+session based authentication (see "login.html"):

And use "login.html" to test the functionality.

**Comment by albmunmu** [comment]
And where would the DB connection info go? Should I still user the code below that is below "// uncomment the lines below when running in stand-alone mode:
"??

**Comment by mevdschee** [comment]
Yes indeed!

**Comment by albmunmu** [comment]
I am still getting a white page, even when showing errors with 

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

I did this with fresh, just downloaded files, I only added my DB connection info and that was working before as intended without tokens, could you help me out with this?

**Comment by albmunmu** [comment]
I am getting this header after my login.html post

Request URL:http://mysite.com/admin/api/api.php
Request Method:POST
Status Code:401 Unauthorized
Remote Address:37.59.139.134:80

**Comment by mevdschee** [comment]
username/password = admin/admin

Did you try that?

**Comment by albmunmu** [comment]
yes I did... also username/password but no good :(

**Comment by mevdschee** [comment]
Copy the following from PHP-API-AUTH:

- login.html
- auth.php

Uncomment the following:

    require 'auth.php'; // from the PHP-API-AUTH project, see: https://github.com/mevdschee/php-api-auth

    // uncomment the lines below for form+session based authentication (see "login.html"):

    $auth = new PHP_API_AUTH(array(
        'authenticator'=>function($user,$pass){ $_SESSION['user']=($user=='admin' && $pass=='admin'); }
    ));
    $auth->executeCommand();
    if (empty($_SESSION['user'])) {
        header('HTTP/1.0 401 Unauthorized');
        exit(0);
    }

    // uncomment the lines below when running in stand-alone mode:

    $api = new PHP_CRUD_API(array(
        'dbengine'=>'MySQL',
        'hostname'=>'localhost',
        'username'=>'maurits',
        'password'=>'',
        'database'=>'php-crud-api',
        'charset'=>'utf8'
    ));
    $api->executeCommand();

Run PHP by executing:

    php -S localhost:8000

Now go to:

    http://localhost/login.html

And press the "Ok" button to log in.

**Comment by albmunmu** [comment]
This is my api.php

`
 require 'auth.php'; // from the PHP-API-AUTH project, see: https://github.com/mevdschee/php-api-auth

// uncomment the lines below for token+session based authentication (see "login_token.html" + "login_token.php"):

// $auth = new PHP_API_AUTH(array(
//  'secret'=>'someVeryLongPassPhraseChangeMe',
// ));
// $auth->executeCommand();
// if (empty($_SESSION['user'])) {
//  header('HTTP/1.0 401 Unauthorized');
//  exit(0);
// }

// uncomment the lines below for form+session based authentication (see "login.html"):

 $auth = new PHP_API_AUTH(array(
  'authenticator'=>function($user,$pass){ $_SESSION['user']=($user=='admin' && $pass=='admin'); }
 ));
 $auth->executeCommand();
 if (empty($_SESSION['user'])) {
  header('HTTP/1.0 401 Unauthorized');
  exit(0);
 }

// uncomment the lines below when running in stand-alone mode:

$api = new PHP_CRUD_API(array(
 'dbengine'=>'MySQL',
  'hostname'=>'mysite',
 'username'=>'myuser',
 'password'=>'',
 'database'=>'mydb',
 'charset'=>'utf8' 
));
$api->executeCommand();`

I've just downloaded the latest login.html and auth.php from PHP-API-AUTH

When I go to api.php, I am getting 401 response.

After logging with admin/admin in login.html I am getting a redirect to api.php still getting a 401 response as you can see in the following screenshot http://4.1m.yt/DMySe4r.png

Do you have any idea what may be causing this ?

**Comment by mevdschee** [comment]
Are you running PHP on the command line or behind Apache or Nginx?

**Comment by albmunmu** [comment]
I am running it on apache, without the authentication your api is working fine, we are currently using a workaround checking if a session variable is set at the of the api but this is not the optimal solution I think...

**Comment by mevdschee** [comment]
at the **beginning**? of the api? Just as the script shows you should? If you feel that that is not optional you should probably argue why...

**Comment by albmunmu** [comment]
Yes at the beginning sorry. Where does your script shows this? I added a check for my session variable then do a session die as such:

```
if (isset($_SESSION['auth'])) {
	
}else{ 
    die("");
}
```

Still... This is not working by token as was recommended by you.

**Comment by albmunmu** [comment]
Because this allows full access to the api for a person that has logged to the system, I want the api to only be visible by post calls with a username and password.

**Comment by mevdschee** [comment]
The 'authenticator' sets the session variable 'user' and the script checks whether or not this is empty 3 lines lower.

**Comment by albmunmu** [comment]
As I mentioned, using the auth.php is giving me 401 after login, so I'm stuck with the basic api.php file, I am trying to implement a more secure way than the current one and I was hoping you could guide me, but the current steps are not working for me.

**Comment by mevdschee** [comment]
I wrote step-by-step instructions that work for me. You report they don't work for you. I've asked you to report something and you don't answer my question. What do you want me to do next?

**Comment by albmunmu** [comment]
Sorry man hadn't seen that part of the post.

I get this before login.
```
Notice: Undefined index: PATH_INFO in /home/devadv/public_html/admin/api/auth.php on line 2
string(3) "GET" NULL
```

And this after login as output


```
Notice: Undefined index: PATH_INFO in /home/devadv/public_html/admin/api/auth.php on line 2
string(4) "POST" NULL
```

**Comment by mevdschee** [comment]
Okay, that seems correct! Can you now put the line

    var_dump($_SESSION['user']);

before the line:

    if (empty($_SESSION['user'])) {

And replace the line:

    'authenticator'=>function($user,$pass){ $_SESSION['user']=($user=='admin' && $pass=='admin'); }

with:

    'authenticator'=>function($user,$pass){ $_SESSION['user']=($user=='admin' && $pass=='admin'); var_dump($user=='admin' && $pass=='admin'); }

and post the output?

**Comment by albmunmu** [comment]
That gives me the following


```
Notice: Undefined index: user in /home/devadv/public_html/admin/api/api.php on line 2081
NULL 
Warning: Cannot modify header information - headers already sent by (output started at /home/devadv/public_html/admin/api/api.php:2081) in /home/devadv/public_html/admin/api/api.php on line 2083
```

**Comment by mevdschee** [comment]
It seems the authenticator function does not get called, does it?

**Comment by mevdschee** [comment]
In the function executeCommand in auth.php you may add

    var_dump('req: '.$request);

just before:

    if ($method==$verb && trim($path,'/')==$request) {

and post the output.

**Comment by albmunmu** [comment]
I get the following output, this means it IS being run right?

```
string(22) "req: admin/api/api.php" 
Warning: Cannot modify header information - headers already sent by (output started at /home/devadv/public_html/admin/api/auth.php:136) in /home/devadv/public_html/admin/api/api.php on line 2082
```

**Comment by mevdschee** [comment]
Ah.. that is clearly incorrect (should be empty). Can you do a:

    var_dump($_SERVER['ORIG_PATH_INFO']);

at the beginning of 'api.php' and post the output?

**Comment by mevdschee** [comment]
I think I've found your problem:

see: 078e7ce80b71edef81b3289fdf431a8f3f584094

I hope that works for you!

**Comment by mevdschee** [comment]
Sorry for the inconvenience.. thank you for having patience.

**Comment by albmunmu** [comment]
Thank you mevdschee that worked with the login!

Now, my second question to you would be, is there a way of making it possible for people not to be able to access the data from browser calls?

**Comment by mevdschee** [comment]
Please update your other files as well, per:

https://github.com/mevdschee/php-api-auth/commit/ab72cc58bdab479b34ee467bb0cc72d75bb6b14a

Second question: I'm not entirely sure what you mean, but if you mean to protect the API to be restricted to only allowed calls, then you can use the 'table_authorizer' callback.

**Comment by mevdschee** [comment]
Please open a new issue for any further questions.
