### ISSUE TITLE
MySQLi -> PDO

### ISSUE THREAD

**Issue by abmmhasan** [mevdschee/php-crud-api#118]
This should be converted to PDO for better and simpler class implementation. Also PDO provides better security and Multiple DB type support on single command!

**Comment by mevdschee** [comment]
These are some very bold claims to make without argumentation.

**Comment by mevdschee** [comment]
There are many reasons this is a bad idea, but one is that the core of the implementation would then rely on EXPERIMENTAL PDO functionality.

See: http://php.net/manual/en/pdostatement.getcolumnmeta.php

**Comment by abmmhasan** [comment]
Interesting feedback! I'll think twice before I contribute here or not at all!

**Comment by pottertech** [comment]
PDO is a wrapping library for multiple database drivers, including mysqli. So when you are using PDO you are using mysqli and so the security vulnerabilities are basically the same.

**Comment by mevdschee** [comment]
Good news on this issue. The upcoming version 2 uses information_schema for it's metadata and is based on PDO.

It's not ready, but you can see the progress on: https://github.com/mevdschee/php-crud-api2
