### ISSUE TITLE
Insert multiple values

### ISSUE THREAD

**Issue by alanlimateles** [mevdschee/php-crud-api#120]
I read the documentation but I can`t find if is it possible to insert multiple values with a json. Can I do this?

**Comment by mevdschee** [comment]
No it is not supported (yet) as you can read in the README:

>Batch operations for insert, update and delete are not supported

This is also discussed in #24 and #3

**Comment by alanlimateles** [comment]
Tnx a lot!

**Comment by mevdschee** [comment]
You are welcome, thank you for reaching out!

**Comment by mevdschee** [comment]
I added the feature as many people have requested it. It uses a transaction. I hope you like it.

**Comment by alanlimateles** [comment]
Tnx, I will use it!
