### ISSUE TITLE
Nginx Config

### ISSUE THREAD

**Issue by trajche** [mevdschee/php-crud-api#121]
The default php config of Nginx that comes with Ubuntu 16.04 (nginx 1.10.0)
 `location ~ \.php$ { ... }` will not work with after .php therefore it must be updated to:
`location ~ [^/]\.php(/|$) { ... }`

Just a tip if anyone else is trying to get it to work. Time to test this now. Thanks!

**Comment by mevdschee** [comment]
Any reason you closed this?

**Comment by mevdschee** [comment]
Good documentation on this is found here:

https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/

**Comment by trajche** [comment]
Thought I'd close it since it's solved, just for people Googling for the solution...

**Comment by mevdschee** [comment]
ok.. maybe you can describe the commands you did in 16.04 and then we add it to the README? I would really like to help people get this stuff running the best possible way.

**Comment by trajche** [comment]
Sure, you could add a section 'Nginx Config Example', replace example.com with your domain:

`server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.php index.html index.htm index.nginx-debian.html;

    server_name server_domain_or_IP;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        try_files $fastcgi_script_name =404;
        set $path_info $fastcgi_path_info;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_index index.php;
        include fastcgi.conf;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }
}`

P.S. If I end up doing friendly URL's like you have in Apache example I will add it here too for an update, or open a new issue for the README update.

**Comment by mevdschee** [comment]
Thank you!

**Comment by fedemotta** [comment]
This should be added to the readme file!

**Comment by fedemotta** [comment]
Added #133 pull request

**Comment by larsbo** [comment]
thank you for the nginx example @trajche 
Can you give a nginx configuration example to use the api like this:
`/api/categories`?
I think urls without the .php inside would be more common in production.

**Comment by mevdschee** [comment]
change the line:

    location ~ [^/]\.php(/|$) {

to: 

    location ~ /api(/|$) {

**Comment by mevdschee** [comment]
For Nginx you may want to add something like this:

```
location /api {
    rewrite ^/api(.*)$ /api.php$1 last;
}
```

This should be added to your Nginx config, before or after the `location ~ [^/]\.php(/|$)` section.
