### ISSUE TITLE
BLOB causes LIST method not to work.

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#123]
BLOB causes LIST method not to work, Please inspect.

**Comment by mevdschee** [comment]
can you provide the schema, the url you are trying, the output and the expected output?

**Comment by ubergeekzone** [comment]
URL: http://localhost/api.php/locations?transform=1
Output: {"locations":[]}

I am simply just listing all the data within the locations table and i have a BLOB set on a column, if i remove the BLOB data type the output returns the data as it should, If it is a BLOB no data is returned as above.

**Comment by ubergeekzone** [comment]
I believe the issue to be in the function "convertOutputs" within the "isBinaryType" function.

**Comment by mevdschee** [comment]
Which blob type are you using? Just "blob"? Can you uncomment:

https://github.com/mevdschee/php-crud-api/blob/master/api.php#L178

And report back what you see?

**Comment by ubergeekzone** [comment]
just BLOB
![screen shot 2016-11-08 at 2 56 29 pm](https://cloud.githubusercontent.com/assets/6809045/20114781/a27c48f6-a5c3-11e6-806d-13fb14f6e8a4.png)

{"locations":{id: 3 (49667)
location_name: 253 (4097)
location_quick_ref: 253 (4097)
location_contact: 253 (4097)
location_address1: 253 (4097)
location_address2: 253 (4097)
location_city: 253 (4097)
location_state: 253 (4097)
location_zipcode: 3 (36865)
location_website: 253 (4097)
location_email: 253 (4097)
location_wired: 3 (32769)
location_prize_1: 252 (4113)
location_prize_2: 252 (4113)
location_prize_3: 252 (4113)
location_other_prize: 252 (4113)
location_print_requirements: 252 (4113)
location_capacity: 3 (32769)
location_notes: 252 (4113)
location_drinking_age_only: 3 (32769)
location_sales_rep: 3 (36865)
location_rep_expires: 12 (4225)
location_region_id: 3 (36865)
location_active: 3 (32769)
location_logo: 252 (4241)
}}

**Comment by mevdschee** [comment]
Can you put the following at the start of the api.php and see if errors are reported?

```
error_reporting(E_ALL);
ini_set('display_errors', 1);
```

This functionality seems to be covered by unit tests and the reported type seems to match.

**Comment by ubergeekzone** [comment]
shows no errors.

**Comment by mevdschee** [comment]
I suppose there are records in the 'locations' table? Just checking ;-) Does this test succeed?

**Comment by ubergeekzone** [comment]
they are indeed records in the locations table.

**Comment by mevdschee** [comment]
I tested for handling of empty values (0 bytes) in blob column, but that seems to go fine.

**Comment by mevdschee** [comment]
could it be related to a certain record? Does it also happen when you add a filter, for instance:

```
&filter=id,lt,10
```

Could you try that?

**Comment by ubergeekzone** [comment]
Just tried that a few different ways, no luck. i have had zero bytes to bytes and no luck.

**Comment by ubergeekzone** [comment]
Check this out 

```sql
--
-- Table structure for table `test`
--

CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `file` blob NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `test`
--

INSERT INTO `test` (`id`, `name`, `file`) VALUES
(1, 'test', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `test`
--
ALTER TABLE `test`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `test`
--
ALTER TABLE `test`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
```

**Comment by mevdschee** [comment]
For me it does this:

```
http://localhost:8000/blog.php/test?transform=1
{"test":[{"id":"1","name":"test","file":""}]}
```

What do you get?

**Comment by ubergeekzone** [comment]
i get {"test":[]}

**Comment by mevdschee** [comment]
I wonder if it could have to do with the mysql version.

**Comment by ubergeekzone** [comment]
![screen shot 2016-11-08 at 3 26 13 pm](https://cloud.githubusercontent.com/assets/6809045/20115809/b6b43672-a5c7-11e6-9a41-68b85b7815c1.png)

**Comment by mevdschee** [comment]
ah.. to_base64 was added in 5.6.1, see:

https://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_to-base64

**Comment by ubergeekzone** [comment]
Great! I feel stupid for not realizing that, i should of known. lol! Will update now and keep you updated on the status.

**Comment by ubergeekzone** [comment]
It's Alive, It's Alive! Thanks.

**Comment by mevdschee** [comment]
You shouldn't. Before I refactored a lot of code (to support spatial) I was doing this part in PHP. This new way is much more efficient, but requires a higher version of MySQL. I understand the confusion. 

I'm happy we were able to find it quickly, thank you for your time.
