### ISSUE TITLE
Updating File for File upload

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#124]
How would you go about updating a file for a certain record? 

My idea is to Make a file storage table using key, value with foreign keys to link to record and then delete them by file id.

But.. I am curios if a record has a blob column, How would you go about updating that?

**Comment by mevdschee** [comment]
Maybe you could add a new one every time, also when editing, and set 'on cascade delete' on the foreign key that points to the file records?

**Comment by mevdschee** [comment]
Or you could allow modifying the method through a get parameter and simply post with the method set to put.

**Comment by mevdschee** [comment]
See also #67

**Comment by ubergeekzone** [comment]
#67 worked great, i like how i can POST and then set a method param override and do an update. that's genius. ty

**Comment by mevdschee** [comment]
Thank you for reporting your success!
