### ISSUE TITLE
API Access without Authentication

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#125]
Ok, Let's discuss API Authentication for a moment, I am very curios about something. 

If you have an app like an admin backend, that would require a login of course. But let's say you need to use the API on a website that people will use that requires no login, Can we setup a token to be passed so the API can be accessed without requiring a login?

This means one API for both backend and frontend, which should be the useage case.

**Comment by mevdschee** [comment]
Hi, thank you for your question. You could allow access to certain tables based on whether or not a user is stored in the session using the 'table_authorizer' callback and looking at ```$_SESSION['user']```. You may also restrict access to a specific origin domain using the 'allow_origin' setting. Is one of these what you are after?

**Comment by ubergeekzone** [comment]
yes, that sums it up for me, thanks!

**Comment by ubergeekzone** [comment]
Re-hashing on this matter, So i have API Auth enabled and it works wonderful. I need to allow my locations table to be accessed without the need of a csrf token/login. I have tried the code below but not sure i am doing this right, because now my locations no longer return at all when logged in and i still get a 401 unauthorized error.

```php
'table_authorizer' => function($cmd,$db,$tab) { return $tab=='locations'?false:true; }
```

**Comment by mevdschee** [comment]
I think having two end-points would be more logical, but if you must combine them, this will do.

**Comment by ubergeekzone** [comment]
Do you mean two end-points having two API's, one for admin area and one for user area? That seems kind of redundant to me.

**Comment by mevdschee** [comment]
Yes, one that is public and one that requires login. Both pointing to the same database.

**Comment by ubergeekzone** [comment]
That is a good idea, but seems redundant to me. Thanks for all your help.

**Comment by mevdschee** [comment]
You are welcome.
