### ISSUE TITLE
Batch update (using a filter)

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#127]
instead of passing the primary key to be the selector for the update, is there a way i could pass a filter? like location_id,eq,89 so it would update the records that have a id of 89 or even just pass it back into json body like i do on create.

**Comment by mevdschee** [comment]
Thank you for your question. Batch update is currently not supported.

**Comment by ubergeekzone** [comment]
any plans to support it?

**Comment by mevdschee** [comment]
For instance we could allow a 'put' on ```/categories``` like we allow this for 'get', but I am afraid that people intend to do a 'put' on ```/categories/1``` and accidentally leave out the '1' and update all records in the table. That is why I have not build it yet and doubt whether or not I should. Do you think it is more useful than risky?

**Comment by ubergeekzone** [comment]
@mevdschee here is my suggested advice for that issue.

we check what the primary key is in "categories" which should be "id", if "id" is in the json body for a PUT it will batch update, if it's not throw a "must pass id, for non batch updates", if "id" is in URL string then do single update.

**Comment by mevdschee** [comment]
A batch update is typically something like "I want to set 'available' to false for all items that have 'stock_amount' equal to 0". This would be represented by:

```
PUT http://localhost/api.php/items?filter=stock_amount,eq,0
{"available":0}
```

I do not see what role the primary key would play.

**Comment by mevdschee** [comment]
What I think you mean is:

```
PUT http://localhost/api.php/items
[{"id":1,"available":false},{"id":2,"available":false},{"id":3,"available":false}]
```

I see how this would work and that it is not likely to fail. In that case the body must be a JSON array containing objects that hold a primary key.

**Comment by ubergeekzone** [comment]
correct, now in a dynamic method this would require a read statement but that is ok, but only one update call would need to be made. 

Your above example is exactly what i mean.

**Comment by mevdschee** [comment]
Hi, I implemented the feature as you requested.
