### ISSUE TITLE
UPDATE error checking

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#128]
I do believe right now that when an update is done it returns 0 if no data was modified, 1 if data was modified, Could we make it return a 404 (error) if there was an error inserting data or even return the error code from database server?

**Comment by mevdschee** [comment]
Thank you for your question. Currently the number of affected rows is returned. A successful update can have 0 affected rows (values where not adjusted). I think returning an error would be unexpected.
