### ISSUE TITLE
File Upload Discussion

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#131]
I have a few questions about the file upload feature.

1. When trying to submit a form if no file is picked to upload, the insert fails. How should this be handled?

2. Did you intend for the file upload feature to be used solo or when creating data for a record or both? 

3. Do you have any jquery or javascript lib you recommend for use with the file upload feature? I am looking for something with a preview and progress bar feature.

**Comment by mevdschee** [comment]
Thank you for your questions. I'll address each of the points:

1. I didn't know about this, it should be filed as a bug
2. I would prefer both (but have not tested extensively)
3. No, I have no such recommendation.
