### ISSUE TITLE
File Upload Bug (no file, insert fails)

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#132]
When trying to submit a form if no file is picked to upload, the insert fails.

**Comment by mevdschee** [comment]
I tried to reproduce your report, but did not succeed (insert succeeds). I did found the following warning that I fixed:

```
PHP Warning:  file_get_contents(): Filename cannot be empty in /home/maurits/projects/php-crud-api/api.php on line 1749
```

Can you help me to reproduce the problem?

**Comment by ubergeekzone** [comment]
I will update you on this shortly

**Comment by mevdschee** [comment]
Any update on this?

**Comment by ubergeekzone** [comment]
yes, i am ruling it as a JavaScript side error and not a php error.

**Comment by mevdschee** [comment]
Okay, thank you! I'll be closing the issue then.
