### ISSUE TITLE
DELETE (foreign key error/status codes)

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#134]
When trying to delete data that has a foreign key relationship, it seems as if it has succeeded because it returns the id of the record you were trying to delete. I think it should return status/error codes for a DELETE method. Example Below

## Fails
```json
{
   "code": 409, 
   "message": "record could not be deleted"
}
```

## Succeeds
```json
{
   "code": 200, 
   "message": [120,50,60,80]
}
```
It could be up to the developer to handle how to show where the data is that is causing the fail or we could list the foreign key constraints in a array along with the message like the linking column and linking table.

That would look something like this 

```json
{ 
   "code": 409, 
   "message": "record could not be deleted",
   "failed_constraints": {
      "locations": "locations_id"
      }
}
```

We show them the table as a they object key and then the linking column as a value, Which this would be a more intuitive solution to the matter. We can get the failed constraints form the mysqli error output.

I mean sure we could ON DELETE CASCADE but this is not a good way of handling data.

**Comment by mevdschee** [comment]
duplicate, see #14
