### ISSUE TITLE
Adding HTTP Status Codes to Outputs

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#135]
How do you feel about adding HTTP Status Codes to Outputs? Check out he list of them here http://www.restapitutorial.com/httpstatuscodes.html

# Example 

```json
{
   "code": 200,  
   "message": [120,50,40]
}
```

We can set it up to work with the old style outputs and new style outputs, see #134 on why this would be do able. 

We could just pass a override_output into the class constructor 0 for old style, 1 for new style. This way we have a fallback for people already using the API.

**Comment by mevdschee** [comment]
duplicate, see #14
