### ISSUE TITLE
Exclude Parameter 

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#136]
I see a column exculde parameter being useful for exculding data and relationship data. 

# Example

api.php/books?exclude=bookName,authors.name

**Comment by mevdschee** [comment]
This feels like a logical feature to provide and is not hard at all to implement.

**Comment by ubergeekzone** [comment]
any update on getting this added in?

**Comment by ubergeekzone** [comment]
any updates?

**Comment by mevdschee** [comment]
Implemented in #185
