### ISSUE TITLE
Large file upload issue

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#139]
I get this error when trying to upload a file that is 13.2MB in size

```php
<br />
<b>Warning</b>:  Error while sending QUERY packet. PID=81460 in <b>/Users/****/*****/Projects/****/api/index.php</b> on line <b>192</b><br />
```
asterisk signs were used to mask dir paths.

**Comment by mevdschee** [comment]
Change you MySQL configuration in `my.ini` under the `[mysqld]` section put:

    max_allowed_packet=500M

see: http://stackoverflow.com/questions/8062496/how-to-change-max-allowed-packet-size#8062538

**Comment by ubergeekzone** [comment]
ah yes, will do. thank you!
