### ISSUE TITLE
Would more response codes work?

### ISSUE THREAD

**Issue by resident0** [mevdschee/php-crud-api#14]
When submitting new resources to tables with a non-auto-increment primary key the API succeeds silently and returns NULL if the key is duplicate. Would it make sense to add 2 more exit functions? One would be 201 with a location header pointing to the primary key and the other would be 409 with a header entry indicating that the sql query threw a duplicate key error.

**Comment by mevdschee** [comment]
There is no standard for exchanging duplicate key information so it seems the error messages of the database need to be parsed. There are some obvious drawbacks to this approach. We can also add a header with the error message in case of a "null". What do you think?

**Comment by resident0** [comment]
That's a good point. Adding an error message to the 'null' case makes the most sense.

**Comment by ubergeekzone** [comment]
Another thing i have noticed if a database is blank or mysql can't connect, We don't throw an error message, It just displays the error message in a not intuitive way. I feel we should be throwing an error code along with the message. I feel a big part of an API is status codes and error handling., I could help integrate this feature,

Do you have a way currently we could override into a function? sorry if that makes no sense its nearly 2:00 AM here.

**Comment by mevdschee** [comment]
This is fixed in v2 (beta).
