### ISSUE TITLE
curl_init() does not work when use auth

### ISSUE THREAD

**Issue by hibinojack** [mevdschee/php-crud-api#140]
Hello,

I'm using php-crud-api and it worked good, thank you.
But when I wanted to read API file with PHP_API_AUTH, look like I cannot get in to it.
and stuck with the permission somewhere.

for example code I use: 

```
    function readAPIFile($url) {
        if($url) {
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, 'http://localhost/rest/api.php/users?transform=1&csrf=3117667488301580288');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            $output = curl_exec($ch);

            // convert response
            $output = json_decode($output);
       }
return $output
}
```

$output it was empty when I require 'auth.php' on api.php
but when I commented it. I can get $output value

PS: if going straight to with $url on the browser I can get data fine.

Sorry for my bad English.

**Comment by mevdschee** [comment]
see: https://github.com/mevdschee/php-api-auth/issues/7

**Comment by hibinojack** [comment]
Thank you for your quick response.

I tried to following the link you give already. 
and I found that, $output result on the first $ch CURL is something like:

`"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0ODAwODk1MjEsImV4cCI6MTQ4MDA4OTU1MX0.j8t917RilnhJ8z3Aq2MamUjvGSJW52intw0n56zVxzo"`

Which I think it shouldn't correct $csrf token key.
So after pass $output thought CURL2, it unable to get data on the $ch2

**Comment by mevdschee** [comment]
that is the sessionid .. the csrf token is all numeric

**Comment by hibinojack** [comment]
Just got that key all the time, impossible to get return $csrf token back.

By the way.. I thought It probably be problem on my authorize at the first time too.
because my login form will pass through the $_POST data via $.ajax,
so I pass that parameters to api.php too

Like this:

```
            check username password  blah blah ....
            ..
            ..
            }).done(function (data) {

                    var username = $("#username").val();
                    var password = $("#passwd").val();

                    var authenticator = {};
                    authenticator['user'] = $("#username").val();
                    authenticator['pass'] = $("#passwd").val();

        $.ajax({
            type: "POST",
            url: base_url + "rest/api.php/",
            data: {"username": username, "password": password, "authenticator": authenticator}
        }).done(function (res) {
            //console.log(res);
        });
```

So I don't know how figure it out?

**Comment by mevdschee** [comment]
Sorry, wrong button. You should first try the simple example without the token as described in the comments in `api.php`.

**Comment by hibinojack** [comment]
Ok., I tried many way but seem stuck with it, but no problem.
I coding an small auth coding script my self to figure out.

So thank you for your kind assist @mevdschee

**Comment by mevdschee** [comment]
You are welcome. Glad you got it working! Enjoy.
