### ISSUE TITLE
Using postgres maintenance database

### ISSUE THREAD

**Issue by beakman** [mevdschee/php-crud-api#142]
I'm trying to query the maintenance database "postgres" to obtain the database list from "pg_database" table.

When I use the php built-in web server: `php -S localhost:8000` it works fine:

`GET http://localhost:8000/api.php/postgres/pg_database`

RESULT:

> {"pg_database":{"columns":["datname","datdba","encoding","datcollate","datctype","datistemplate","datallowconn","datconnlimit","datlastsysoid","datfrozenxid","datminmxid","dattablespace","datacl"],"records":[["template1","10","6","en_US.UTF-8","en_US.UTF-8","t","t","-1","12030","673","1","1663","{=c\/postgres,postgres=CTc\/postgres}"],["template0","10","6","en_US.UTF-8","en_US.UTF-8","t","f","-1","12030","673","1","1663","{=c\/postgres,postgres=CTc\/postgres}"],["postgres","10","6","en_US.UTF-8","en_US.UTF-8","f","t","-1","12030","673","1","1663",null],["omldb","10","6","en_US.UTF-8","en_US.UTF-8","f","t","-1","12030","673","1","1663",null],["experiments_registry","16385","6","en_US.UTF-8","en_US.UTF-8","f","t","-1","12030","673","1","1663",null],["nc_18.11.201616.35.57.204","16385","6","en_US.UTF-8","en_US.UTF-8","f","t","-1","12030","673","1","1663",null]]}}

But when I upload the 'api.php' to production server I always get an 404 Not found (entity) error.

I found that the query: `$result = $this->db->query($this->db->getSql('reflect_table'),array($table,$database))` returns nothing in production server.

Any clues on why this is happening?

Thank you all.

**Comment by mevdschee** [comment]
I thought the reflection database was called `pg_catalog`?

**Comment by mevdschee** [comment]
Closed due to inactivity.
