### ISSUE TITLE
Bad json response format - inserting one row

### ISSUE THREAD

**Issue by komesta** [mevdschee/php-crud-api#143]
If you are inserting one rowto table, API returns the last insert id witch is not converted to json. This is due to this line 
`else echo json_encode(insertId)`
If you are inserting multiple values then insertId is an array and output is ok. But inserting one value leads to insertId is an integer and json_encode(3) is 3 and not [3].
My suggestion is this:  json_encode(array(insertId))

**Comment by mevdschee** [comment]
Hi, thank you for reaching out. You say:

>Bad json response format

When you update a single item, then you don't get an array back. When you update multiple, then you do. This is clearly stated in the readme. What is wrong about that?

Most people single single items and get a single value back. Batch inserting (sending an array) is supported with will also result in an array as the response. It seems consistent to me.

**Comment by komesta** [comment]
There is a problem because the content-type header in response is applicaion/json. With angular or other mvc framework the response is wrong cause it is not json. Even in firefox development utils it states cannot parse response.

**Comment by mevdschee** [comment]
IMHO a number it is a valid JSON value. 

see: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf
