### ISSUE TITLE
inserting to MySQL text field

### ISSUE THREAD

**Issue by komesta** [mevdschee/php-crud-api#144]
With mysql iam not able to insert to text column type. The cause is this: 
http://php.net/manual/en/mysqli-result.fetch-field-direct.php
```
<?php
$mysql_data_type_hash = array(
    1=>'tinyint',
    2=>'smallint',
    3=>'int',
    4=>'float',
    5=>'double',
    7=>'timestamp',
    8=>'bigint',
    9=>'mediumint',
    10=>'date',
    11=>'time',
    12=>'datetime',
    13=>'year',
    16=>'bit',
    //252 is currently mapped to all text and blob types (MySQL 5.0.51a)
    253=>'varchar',
    254=>'char',
    246=>'decimal'
);
?>
```
So the type 252 is for blob and text. If i`am trying to POST a field to database column witch has TEXT format, then the api asumes that this is binary data field and converts my text. The insertion then fails because of x in beggining of VALUE(x'asdasd').
I`m glad that your are working on this project. It is very helpfull and nice api. Thank you very much.

**Comment by mevdschee** [comment]
Do you have a binary collation on the field? Like `utf8_bin` while you should have `utf8_general_ci`?

**Comment by mevdschee** [comment]
I am not able to reproduce this bug.
