### ISSUE TITLE
PHP-API-AUTH problem

### ISSUE THREAD

**Issue by tufanayd** [mevdschee/php-crud-api#145]
Hello,

First of all thank you for this extremely helpful api.

I am trying to use it with auth however it is not working at all (I am doing something wrong I guess).

Here is my code:

`	require "api/php_crud_api_transform.php";
	
	$db_table = $_GET['t1'];
	
	function call($method, $url, $data = false) {
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
		curl_setopt($ch, CURLOPT_URL, $url);
		if ($data) {
			curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
			$headers = array();
			$headers[] = 'Content-Type: application/json';
			$headers[] = 'Content-Length: ' . strlen($data);
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		}
		curl_setopt($ch, CURLOPT_COOKIEJAR, "/tmp/cookieFileName");
		curl_setopt($ch, CURLOPT_COOKIEFILE, "/tmp/cookieFileName");
	
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		return curl_exec($ch);
	}
	
	$auth = call('POST','http://www.localhost.com/login_token.php','username=admin&password=admin');
	$response = call('GET','http://www.localhost.com/api.php/'.$db_table.'?csrf='.$auth,'');
	
	$jsonObject = json_decode($response,true);
	$jsonObject = php_crud_api_transform($jsonObject);
	
	$output = json_encode($jsonObject,JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
	echo $output;`

The output is 
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\api\php_crud_api_transform.php on line 29
[]

**Comment by mevdschee** [comment]
Hi, thank you for reaching out. Can you var dump the result of the call function? I think that may contain a hint.

**Comment by tufanayd** [comment]
Hi again,

```
var_dump($auth)

string(150) ""eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE0ODA2NjgwMTQsImV4cCI6MTQ4MDY2ODA0NH0.FPvIk6WLjKcQqQmsMf9SvAnfQw3Vue97PllBNDsv6eM""
```

```
var_dump($response)

string(0) ""
```

**Comment by mevdschee** [comment]
1. You are referring to a file named "/tmp/cookieFileName". Does that currently exist? 
2. Maybe try changing it into "C:\\Windows\\Temp\\cookies.txt"? 
3. Also there is new Curl object initialized for every request. That may also not be needed.

**Comment by tufanayd** [comment]
The file exists and the content of the file is as below:

```
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_www.localhost.com	FALSE	/	FALSE	0	PHPSESSID	r5jmn339j8vlpv47dk8ln6i443

```

**Comment by mevdschee** [comment]
Replace:

    $auth = call('POST','http://www.localhost.com/login_token.php','username=admin&password=admin');

With 

    $auth = call('POST','http://www.localhost.com/api.php','username=admin&password=admin');

That will fix it!
