### ISSUE TITLE
CORS Error from HTTPS Using POST

### ISSUE THREAD

**Issue by greenfm** [mevdschee/php-crud-api#147]
Hi, so I love this and am trying to expand my knowledge, but I have no PHP knowledge.

I've left the default settings, and I'm getting the CORS error:

XMLHttpRequest cannot load https://example.com/api.php/get_directions. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.example2.com' is therefore not allowed access.

Where do I specific allow_origin *?

Thank you!

**Comment by greenfm** [comment]
Well, turns out that I just swapped out the current version of PHP CRUD API with an older one I downloaded, and now it works?  I'm using a MySQL Database and getting this error after I adjusted my HTACCESS file:

<br />
<b>Warning</b>:  mysqli_options() expects parameter 2 to be long, string given in <b>/home2/public_html/api.php</b> on line <b>107</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Error setting int and float native. ' in /home2/public_html/api.php:108
Stack trace:
#0 /home2/public_html/api.php(1834): MySQL-&gt;connect('localhost', 'cars', 'xxxxxx...', 'cars', NULL, NULL, 'utf8')
#1 /home2/public_html/api.php(2260): PHP_CRUD_API-&gt;__construct(Array)
#2 {main}
  thrown in <b>/home2/public_html/api.php</b> on line <b>108</b><br />

**Comment by mevdschee** [comment]
Hi, can you tell me the version of PHP you are using? And the version of the mysqlnd extension (if you happen to know)? It seems the constant is not defined. You may comment out lines 107-109 and then it should work.

**Comment by mevdschee** [comment]
I'm pretty sure this is version related, but I may be mistaken. Please reach out if you encounter this error (again) on a supported PHP version.

**Comment by greenfm** [comment]
Hey, thanks, I got sidetracked but the php version 5.4.45 and I couldn't find the mysqlnd extension in the phpinfo...is there another name for it?

**Comment by mevdschee** [comment]
@greenfm Can you try to run the following:

```
$ php -a
Interactive mode enabled

php > var_dump(MYSQLI_OPT_INT_AND_FLOAT_NATIVE);
int(201)
php > 
```

And see whether or not you get the same output?
