### ISSUE TITLE
Swagger info showing up

### ISSUE THREAD

**Issue by PallyRogers** [mevdschee/php-crud-api#148]
Hi there,

When I load http://localhost/api.php the swagger info like this shows up:

{"swagger":"2.0","info":{"title": .... etc...

How do I prevent that info from loading. I would like to replace it with a friendlier message or at least not show the database and schema details.

Thank you.

**Comment by mevdschee** [comment]
Replace the call to swagger with something else.. like `echo "hello world"` in:

https://github.com/mevdschee/php-crud-api/blob/master/api.php#L2212

**Comment by PallyRogers** [comment]
Wow thank you. Your support is exceptional.
