### ISSUE TITLE
Support for sqlite

### ISSUE THREAD

**Issue by dicoy** [mevdschee/php-crud-api#15]
Would it be possible to not use a db at all and instead connect to a sqlite file?

**Comment by mevdschee** [comment]
I currently see no reason that would prevent this from being implemented as foreign key reflection seems to be present in SQLite.

**Comment by mevdschee** [comment]
I'm sorry, but I have absolutely no experience with SQLite. I am willing to work together on this. Any chance you can share what you have so far?

**Comment by TwanoO67** [comment]
I would be glad to cowork on that :)

Still in progress, but you can a first try here:
https://github.com/TwanoO67/php-crud-api

I have created a Sqlite3 file using the last Adminer, and configured an api instance using the filename in the 'hostname' parameter.

**Comment by mevdschee** [comment]
@TwanoO67 It's done! There is still a small problem with the binary columns, but that requires some serious refactoring. I will fix that soon.

**Comment by TwanoO67** [comment]
Great job! I will test that over the weekend :) Thanks a lot!

**Comment by mevdschee** [comment]
Thank you for your good input and nice start of the implementation. I found a work-around for being able to use "pragma" in a query. Check it out! ;-)
