### ISSUE TITLE
Inserted ID is returned in string (instead of JSON)

### ISSUE THREAD

**Issue by rrjanbiah** [mevdschee/php-crud-api#150]
Only in creating object, inserted ID is not returned in JSON

**Comment by mevdschee** [comment]
Can you be more specific? What is the output you receive? What is the output you expect? Is the `Content-Type` header missing/incorrect?

**Comment by rrjanbiah** [comment]
@mevdschee I'm sorry. It is correct. I misunderstood other developer's note.

Issue is that it doesn't have proper JSON format to handle error. Will open another ticket. Closing this now.
