### ISSUE TITLE
Automagic created_at and updated_at

### ISSUE THREAD

**Issue by rrjanbiah** [mevdschee/php-crud-api#151]
Provide support for automagic as in Rails

These are calculated/automatic added fields:

-  `created_at` auto insert
-  `updated_at` auto update

If these are already possible using callbacks, please provide some hints.

If you provide some guideline/hints, I'll try to provide PR.

**Comment by mevdschee** [comment]
Maybe we can have a callback that allows you to add calculated fields? Would that work for you?

**Comment by rrjanbiah** [comment]
@mevdschee Yes, callback should work.

**Comment by mevdschee** [comment]
@rrjanbiah Can you verify that this works for you?
