### ISSUE TITLE
Automagic required and maxlength validation

### ISSUE THREAD

**Issue by rrjanbiah** [mevdschee/php-crud-api#152]
Automatic validation constraints:

-  `required` validation using `not null`
-  `maxlength` validation using column length

(These have to be fetched from table schema and have to be cached)

**Comment by rrjanbiah** [comment]
> Maybe you should open separate tickets for required and maxlength, as they are different features and require a whole different approach. How would you expect the API to behave?

Probably similar to what current validation callback does?

**Comment by mevdschee** [comment]
What if you have `not null` with a default value? What do behavior do you expect? A validation error?

Shouldn't `maxlength` validation be done client side? What is the point of server side validation for that field? Databases either ignore (truncate) or fail the query, which is configurable. Not sure what would be expected.

**Comment by rrjanbiah** [comment]
> What if you have not null with a default value? What do behavior do you expect? A validation error?

`DEFAULT` value will be inserted in the absence of that field. But, if the filed is present, but empty, should throw error.

> Shouldn't maxlength validation be done client side? What is the point of server side validation for that field? Databases either ignore (truncate) or fail the query, which is configurable. Not sure what would be expected.

I think, instead of silent fail, validation is essential. Should throw error.

**Comment by mevdschee** [comment]
> But, if the filed is present, but empty, should throw error.

How can you determine whether or not the user wants to save an empty string?

>I think, instead of silent fail, validation is essential. Should throw error.

I agree, this should never reach the server as it should be validated on the client.
