### ISSUE TITLE
PUT Update Where

### ISSUE THREAD

**Issue by capnhancuoi** [mevdschee/php-crud-api#154]
Hello mevdschee :)

Why do you not make api update edit "WHERE" another row name?
I need update record.

records: categories
ID.          NAME.           CODE
1            Blue              ACB123.         => Make change SUK456
2           Black           CDF876
3           White           DVB234

http://yoursite.com/crudapi/api.php/categories/name/Blue?code=SUK456 <= may be look like or whatever you want ...

Thank's

**Comment by mevdschee** [comment]
Hi, thank you for your request. I will not add this as it is very easy to make an error with. You can retrieve the primary keys and then do a batch update. This only requires two calls and should satisfy your needs.

**Comment by mevdschee** [comment]
For reference, also read the discussion in #127

**Comment by capnhancuoi** [comment]
Thank for reply 👍 

But i think to do you can put to config, lock or open and note comment this a very dangerous.

// This is Dangerous 
$Update_Where = "Lock"; // For Default you can Open.

**Comment by mevdschee** [comment]
Are you sure you cannot retrieve the primary keys and batch update? It only requires two calls in total for all records to be updated.
