### ISSUE TITLE
Composite Keys Hack

### ISSUE THREAD

**Issue by massimilianogalanti** [mevdschee/php-crud-api#155]
Hello all,

since I need to support DELETE on a table with composite keys I have slightly modified the code to accept SELECTS and DELETES following this convention:

table/ckey0|ckey1|...|ckeyn

I understand this is maybe addressing just a specific case, what do you think about it?

**Comment by mevdschee** [comment]
To be honest I'm not a big fan of composite keys, nor do I believe that non-technical PK's are are good idea. And if a PK is a technical key, then is does need to be composite. 

Nevertheless these PK's do exist in some (legacy) databases. Don't expect support for this any time soon, but feel free to fork or branch if this is important to you.
