### ISSUE TITLE
Can't delete multiple values. Only single 

### ISSUE THREAD

**Issue by Denis-Evseev** [mevdschee/php-crud-api#156]
I have a list of answers which I want to delete. Here you can try any id which are presented below
`http://school528.spb.ru/api/index.php/answers/644,645,646,647,648,649,650,665,651,652,653,654,655,656,657,658,659,660,661,662,663,664,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,695,683,684,685,686,687,688,689,690,691,692,693,702,694,696,697,703,698,699`

If I call: http://school528.spb.ru/api/index.php/answers/645 It works
If I call: http://school528.spb.ru/api/index.php/answers/645,656 it returns 500 Error.

**Comment by Denis-Evseev** [comment]
You can get available ids here: 
http://school528.spb.ru/api/index.php/answers

It will be very inefficient if I use removing by single id

**Comment by mevdschee** [comment]
Thank you for reaching out. Are you using the latest version? This use case is in the tests:

https://github.com/mevdschee/php-crud-api/blob/master/tests/tests.php#L675

Can you run the tests and report the outcome?

**Comment by Denis-Evseev** [comment]
Yes I downloaded the api few days ago.
I have not deployed your api localy.

How to laugh your tests on my host ?

**Comment by mevdschee** [comment]
You need to setup the config file in tests folder and point it to a NEW database that can SAFELY BE DESTROYED (sorry for the caps, but this is important). Then you should download `phpunit.phar` from https://phpunit.de/ and then execute the tests from the command line:

```
php phpunit.phar tests/tests.php
```

And post the results here. You contribution is highly appreciated!

**Comment by mevdschee** [comment]
Maybe report the type of the table (should be InnoDB) and the version of MySQL (should be 5.6 or up)

**Comment by Denis-Evseev** [comment]
> SHOW CREATE TABLE answers;
```
`CREATE TABLE `answers` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `value` varchar(100) CHARACTER SET utf8 NOT NULL,
 `questionId` int(10) NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`),
 KEY `fk_question_id` (`questionId`),
 CONSTRAINT `fk_question_id` FOREIGN KEY (`questionId`) REFERENCES `questions` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=704 DEFAULT CHARSET=latin1`
```

> SELECT VERSION();

`5.6.33-79.0-log`

**Comment by mevdschee** [comment]
That looks the way it should.

**Comment by Denis-Evseev** [comment]
Honestly, I have never worked with PHP before only C# and NodeJS. 
Currently, I am trying to deploy my app locally and launch the command:

> php phpunit.phar tests/tests.php

**Comment by mevdschee** [comment]
Can you try to replace the "," (comma character) in the url with "%2C" (urlencoded)? Maybe it is the webserver that does not like the comma.

**Comment by mevdschee** [comment]
It is not very likely that it is in the code.. as the tests cover this case.

**Comment by Denis-Evseev** [comment]
Unfortunately,
> http://school528.spb.ru/api/index.php/answers/699%2C698

does not work.

**Comment by Denis-Evseev** [comment]
Any idea?

Do you have a tutorial how to deploy my app locally and run tests?
I can not install phpunit.phar

**Comment by mevdschee** [comment]
Do you have access to the error log? It is typically in `/var/log/nginx/error.log` for nginx. Every 500 should report something there.

You may want to `tail` the file to retrieve the last lines:

```
tail /var/log/nginx/error.log
```

please post the results here if they are not immediately clear.

**Comment by mevdschee** [comment]
The steps to follow are:

- download and install LAMP/WAMP/XAMP
- create database for api
- put api.php in the "www" folder
- edit configuration in api.php to point to database
- edit configuration in tests/config.php to point to ANOTHER database
- download phpunit.phar
- run `php phpunit.phar tests/tests.php` from the command line.

I'm not sure this is the fastest way to resolve your issue.

**Comment by mevdschee** [comment]
Do you have access to the error log? That would be the easiest path to resolve this issue.

**Comment by mevdschee** [comment]
I noticed you are running on Gentoo with PHP v5.3.29, I've created a VM with a similar setup. Hopefully I will run into the same issue.

**Comment by mevdschee** [comment]
Wow.. PHP 5.3 has lots of issues.. It is a miracle it even does something. I am very sorry, but I am afraid I can't support anything below PHP 5.5. 

I've updated the README to reflect this, see: 1a4b1ba850941f7eb2da8e391d6449d333b16832

**Comment by mevdschee** [comment]
Anyway I understand that is not much use for you, so I did some fixes that should help you, see: 026f2a12b957463f72d9fc77d016bac06ab579cf

**Comment by mevdschee** [comment]
Test report:

```
maurits@ubuntu:/var/www/php-crud-api$ php phpunit.phar tests/tests.php 
PHPUnit 4.8.31 by Sebastian Bergmann and contributors.

..............................................................

Time: 1.71 seconds, Memory: 23.25MB

OK (62 tests, 93 assertions)
maurits@ubuntu:/var/www/php-crud-api$ php -v
PHP 5.3.10-1ubuntu3.25 with Suhosin-Patch (cli) (built: Oct  3 2016 17:02:21) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
maurits@ubuntu:/var/www/php-crud-api$ mysql -uroot -p 
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 426
Server version: 5.6.32-1+deb.sury.org~precise+0.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

Seems to work now on PHP 5.3 + MySQL 5.6! Enjoy..

**Comment by Denis-Evseev** [comment]
school528.spb.ru [Sun Dec 18 07:17:31 2016] [error] [client 188.220.113.221] PHP Fatal error:  Call to undefined function mysqli_begin_transaction() in /home/s/school528s/public_html/api/index.php on line 209

**Comment by mevdschee** [comment]
Yes, I had found that error as well in my test environment I have setup for this bug. The latest version does not have that call anymore.

**Comment by Denis-Evseev** [comment]
Yes it works! Thank you very much!

**Comment by mevdschee** [comment]
Thank you for reporting this bug and helping me to find the cause.
