### ISSUE TITLE
Pluggable API class

### ISSUE THREAD

**Issue by rrjanbiah** [mevdschee/php-crud-api#157]
My suggestion is to make it pluggable API class to be used with any other libraries (Slim, Lumen, etc.. something like middleware or so). I think, independent library may not have heavy usecases.

This may probably need refactoring, as it directly `echo`s JSON. That would also make it `batch` API compliant

**Comment by mevdschee** [comment]
Thank you for your idea. I'm not sure I understand your "feature" request.

>I think, independent library may not have heavy usecases.

And why do you think that?

>This may probably need refactoring, as it directly `echo`s JSON.

Do you think these frameworks don't output the data? How do you stream data in such a case? Can't you just capture it using an output buffer (`ob_start`)?

>That would also make it `batch` API compliant

It already supports batch operations, what feature are you looking for?

NB: In general it feels to me that you are thinking about theoretical improvements to the software without having a real problem to solve. What are you using it for?

**Comment by rrjanbiah** [comment]
Yes, you are right.

Batch means batch of endpoints. It is about handling non database endpoints.

**Comment by mevdschee** [comment]
>Batch means batch of endpoints.

IMHO these can be handled by different front controllers (e.g. from the preferred framework) or - if you must - you can load this script behind the router of such a framework. This may have a negative performance impact though.
