### ISSUE TITLE
Integer ID's returning as strings

### ISSUE THREAD

**Issue by jasonbhuang** [mevdschee/php-crud-api#159]
Hi there,

I've been using the api with typescript and got a warning in run time that the ID's defined as numbers are coming back as strings.  On further inspection, everything is coming back as strings in a GET request.  In the readme, they are clearly shown as integers which is why I'm confused.  I checked and it seems MySQL returns strings by default.  I've used the blog database to test and it's returning a string for id whereas the readme shows an integer too.

Is there a setting I'm missing to fix this, I had a skim through the api.php file to look for "(int)" parsing code and it seems it's only ever used during the insert (which btw does come back as real integer values).

**Comment by mevdschee** [comment]
Can you verify this behavior in the latest version?

**Comment by mevdschee** [comment]
Please provide some reproduction steps.

**Comment by jasonbhuang** [comment]
Hi can confirm its now fixed in new version.  Sorry for not checking that first, only just started using it over a week ago =)

**Comment by mevdschee** [comment]
Thank you for reporting back! Enjoy the software.
