### ISSUE TITLE
Data type BIT always returning value 0

### ISSUE THREAD

**Issue by jasonbhuang** [mevdschee/php-crud-api#160]
Hi again,

So this is one I just found in the new version, I am saving boolean values with a database type of BIT(1), I've matched the data against the table and regardless if the value is 1 or 0, it always returns 0 from the API.

I did a further test and changed the type to INT and its working properly.

Thanks again.

**Comment by jasonbhuang** [comment]
Hm, it seems its a known mysql bug.  I will just set the types to INT(1) since it requires being parsed to int to fix.

http://bugs.mysql.com/bug.php?id=43670

**Comment by mevdschee** [comment]
It is caused by:

```
mysqli_options($db,MYSQLI_OPT_INT_AND_FLOAT_NATIVE,true);
```

apparently that option is not compatible with the "BIT" field type.

See: https://bugs.php.net/bug.php?id=67983

**Comment by jasonbhuang** [comment]
Thanks again for the quick response, and also the very handy software!
