### ISSUE TITLE
$_SERVER[...]: relates #40 & #58

### ISSUE THREAD

**Issue by randycasburn** [mevdschee/php-crud-api#163]
Relates: #40 & #58 

Looks interesting. Would like to investigate, BUT...

Running Nginx that does not support `'path_info'` or `'orig_path_info'`.

What is the possibility of using (the much more reliable) `'request_uri'`, which has all the info you need in one place?

Would require some rewiring, but would virtually eliminate the `$_SERVER[..]` related issues that may creep up in the future.

Thanks for your consideration.

**Comment by mevdschee** [comment]
Thank you for reaching out. I'll try to help you. What are you running? FPM?

**Comment by randycasburn** [comment]
Thanks for the quick reply...

Yes, FPM with `cgi.fix_pathinfo=1` enabled/verified in php.ini

if I add `fastcgi_param PATH_INFO  $path_info;` to the fastcgi_params collection (file), then Nginx crashes.

So what do you have in mind?

Thanks,

Randy

**Comment by mevdschee** [comment]
Please follow the official documentation from nginx on the link that I have sent. 

The command takes `$fastcgi_path_info` not `$path_info`, please follow the docs carefully!

**Comment by randycasburn** [comment]
Thanks. Still not there. But thanks for your help. Was not my intent to ask you to TS my server config.

All the best.

**Comment by randycasburn** [comment]
FYI: it was the location regex that was incorrect, not the split. But thanks again for leading me in the general direction.

**Comment by mevdschee** [comment]
You are welcome, glad I could help!
