### ISSUE TITLE
How to list records of a table as objects only

### ISSUE THREAD

**Issue by thimma11** [mevdschee/php-crud-api#164]
When trying to list the records as object using transform, the result still contains the table name at the beginning. Thus i can't convert the result to a list of objects in my angular-application because its format is wrong. Is there a way  to remove that additional information and just return the objects?

**Comment by mevdschee** [comment]
Maybe this post can help you:

https://fdietz.github.io/recipes-with-angular-js/consuming-external-services/consuming-restful-apis.html

```
$scope.posts = data.posts;
```

Let me know whether that helps.

**Comment by mevdschee** [comment]
Closed due to inactivity.
