### ISSUE TITLE
Filter by column other than id

### ISSUE THREAD

**Issue by braedeno** [mevdschee/php-crud-api#165]
Hi,
I was just wondering if there was a way to get data by columns other than ID? At the moment I can get the right row using an ID number like: `localhost/api.php/users/1` -> Returns all information in the first users row. But what I would like to do is have something like: `localhost/api.php/users/Joe Doe`

Is there a way to do this using the current code?

**Comment by mevdschee** [comment]
Yes, with a list call you can.

```
localhost/api.php/users/?filter=name,eq,Joe Doe
```

Hope that helps, read the README for more information.

**Comment by braedeno** [comment]
Thank you very much, I must have missed that in the README. Thanks for the code, it's working like a charm.
