### ISSUE TITLE
Check if have the key and value.

### ISSUE THREAD

**Issue by andykenobi** [mevdschee/php-crud-api#166]
When i call a POST... I set a JSON like this:
{
   "value": "test"
}

But i want to check if the JSON have a "user_id" key, if not, i want to set a value to "user_id" key or get an error.

Can i do this?

**Comment by mevdschee** [comment]
I guess you want to execute an update with a filter (condition), is that right? The equivalent in SQL of:

    "update `some_table` set `value`="test" where `id`=23 and `user_id` is not null"

You could add a filter to your update statement. That should work.

**Comment by andykenobi** [comment]
No no.
I want to insert a data. But I don't know if the user is passing the json with the user_id. If how do I check? And so, how do I add to the Json the user_id property?

**Comment by mevdschee** [comment]
Can you explain where the user_id is coming from if it isn't from the database nor the json?

**Comment by andykenobi** [comment]
Ok, let's me explain:

Fontend
- Send a request like this:
POST: http://phpserver/[table]
JSON: {"content": "contents..."}

Backend
RECEIVE: get the content and insert into the data base.
WHAT I WANT: i need to "auto add" to the JSON from the Frontend => "user_id" = $_SESSION["user_id"], to add into the database with that property.

Got it?

**Comment by GrahamCobb** [comment]
I do exactly this. I use a tenancy_function to do it - see https://github.com/GrahamCobb/report-status/blob/master/logapi.php

I found that I needed to use a table_authorizer to make sure that creates require that a username has been provided.

**Comment by mevdschee** [comment]
Sounds very good!

**Comment by mevdschee** [comment]
@GrahamCobb Does it not automatically add the session's user_id if it is omitted?

**Comment by GrahamCobb** [comment]
The issue is that I allow access for some operations (get, list) without any user ID being provided to Apache.  However, I need to make sure that when create operations are being done, the user has specified a valid username and password (not null). Maybe I could do that in the .htaccess, but I choose to do it in a table_authorizer.

**Comment by mevdschee** [comment]
@GrahamCobb Thank you for your explanation. Nevertheless I feel that on create this is actually taken care of by the 'applyInputTenancy' function (simplified it does):

    if (isset($input->$key) || $action=='create') $input->$key = $v;

Kind regards, Maurits

**Comment by mevdschee** [comment]
@andykenobi Did this solution work for you?

**Comment by mevdschee** [comment]
Closed due to inactivity
