### ISSUE TITLE
JSON entry into database

### ISSUE THREAD

**Issue by anushaath** [mevdschee/php-crud-api#168]
Hi,
   I'm building an Android app for which i'm using this API. Since I'm a beginner, i have some basic questions. I'm sending the data in the form of JSON object from the app into the API. How do I know that the API has received the data? (A request=success, maybe?) And how is this data being added into the database?(Which Function?)  I'm working with MySQL. 

Thanks.

**Comment by anushaath** [comment]
Should I use your PHP-SP-API to create an API endpoint? If so, how do I use that "api.php" file with this "api.php" file?

**Comment by mevdschee** [comment]
I suggest that you install "adminer.php" a single file PHPMyAdmin alternative that allows you to inspect the database (and fill it). Then you can upload and configure "api.php" and use a tool like "postman" to see that the API is working.

see: https://www.adminer.org/
see: https://www.getpostman.com/

**Comment by anushaath** [comment]
Thanks! The API is working as intended.
