### ISSUE TITLE
How to list records of a table as objects only

### ISSUE THREAD

**Issue by thimma11** [mevdschee/php-crud-api#169]
When trying to list the records as objects using transform, the result still contains the table name at the beginning. Thus i can't convert the result to a list of objects in my Angular2-/Ionic2-application because its format is wrong. Is there a way to remove that additional information and just return the objects?

I want to list all records of the table 'note'. I tried it with the following request:
"http://localhost/plotnote/api_crud.php/note?transform=1"

So how could i display the results like this:
[{"id":"7","text":"this is the first note of thimma","date":"2016-12-21","user":"thimma"},{"id":"8","text":"this is the first note of testuser","date":"2016-12-22","user":"testuser"}]

instead of this:
{"note":[{"id":"7","text":"this is the first note of thimma","date":"2016-12-21","user":"thimma"},{"id":"8","text":"this is the first note of testuser","date":"2016-12-22","user":"testuser"}]}

I'm getting a lot of those errors:
EXCEPTION: Error in ./HomePage class HomePage - inline template:13:14 caused by: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.

**Comment by mevdschee** [comment]
Did you see line 12 of the angular 2 example? It shows how to use "NgFor", see:

https://github.com/mevdschee/php-crud-api/blob/master/examples/client_angular2.html#L12

**Comment by thimma11** [comment]
Thank you it seems to work this way! :)
I'm gonna close the issue soon if i don't run into any problems.

**Comment by mevdschee** [comment]
Feel free to open a new issue if new problems arise.
