### ISSUE TITLE
Not found (entity)

### ISSUE THREAD

**Issue by JehBee** [mevdschee/php-crud-api#17]
I'm running mySQL and using phpMyAdmin.  I've got a static IP and using SSL.
I've uploaded the api.php to my public_html folder, and I've changed the settings to connect to my database within the: 
 $api = new MySQL_CRUD_API(array(
 	'hostname'=>'localhost',
	'username'=>'USER',
	'password'=>'PASS',
	'database'=>'USERDB',
 	'charset'=>'utf8'
 ));
 $api->executeCommand();

But, I keep getting "Not found (entity)" everytime I try to view the http://site/api.php

Any help would be greatly appreciated.
Thanks in advance ~ iJenn

**Comment by JehBee** [comment]
I've commented out line 72 and 237, now I get:
SELECT "TABLE_NAME" FROM "INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_NAME" LIKE AND "TABLE_SCHEMA" = Not found (entity)
~ iJenn

**Comment by mevdschee** [comment]
Hi, try to access http://site/api.php/tablename to list the records. Does that work?

**Comment by JehBee** [comment]
No, same issue.

**Comment by mevdschee** [comment]
You have to fill an actual table name.. the name of an existing table.

**Comment by mevdschee** [comment]
closed due to inactivity
