### ISSUE TITLE
Support using "now()" in the data

### ISSUE THREAD

**Issue by CyberDracula** [mevdschee/php-crud-api#170]
How do i map a column with SYSDATE()?

**Comment by mevdschee** [comment]
I believe that in MySQL sysdate is stored a datetime field. You may use datetime(3) to be more specific (milliseconds). In the tests directory you find some SQL files that show datetime usage. I hope this answers the question.

**Comment by CyberDracula** [comment]
Actually what i wanted to find out is if I can call api.php with now() in a datetime column:
api.php/inputdata?name=test&createDate=now()

**Comment by mevdschee** [comment]
No.. but you could send the date

    api.php/inputdata?name=test&createDate=2017-01-24%2021:43:00

or use the following JS function on the client:

    var nowStr = (new Date()).toISOString().substring(0, 19).replace('T', ' ');

I hope that helps.

**Comment by jr3cermak** [comment]
If you are adding new records, MySQL and PostgreSQL allow setting of default values for columns.   I would suggest pushing the effort back to the db.

MySQL: [http://stackoverflow.com/questions/168736/how-do-you-set-a-default-value-for-a-mysql-datetime-column](http://stackoverflow.com/questions/168736/how-do-you-set-a-default-value-for-a-mysql-datetime-column)
PostgreSQL:[http://stackoverflow.com/questions/910763/how-to-set-a-postgresql-default-value-datestamp-like-yyyymm](http://stackoverflow.com/questions/910763/how-to-set-a-postgresql-default-value-datestamp-like-yyyymm)

**Comment by mevdschee** [comment]
This can now be implemented using the newly added 'before' handler.
