### ISSUE TITLE
How to restrict the number of returning values 

### ISSUE THREAD

**Issue by Denis-Evseev** [mevdschee/php-crud-api#172]
If I call php api and just specify a name of table, I will obtain all rows in my table.
It is a vulnerability, a hacker can download all my data. 

How to solve this problem ?

**Comment by mevdschee** [comment]
> It is a vulnerability, 

No it is not. Please be careful in your wording.

>a hacker can download all my data. 

Yes, this is the functionality by design. 

>How to solve this problem ?

If you don't want to allow list functionality you can restrict that using the table_authorizer in the config:

````
'table_authorizer'=>function($cmd,$db,$tab) { return $cmd!='list'; },
```

I hope that helps.

**Comment by Denis-Evseev** [comment]
> No it is not. Please be careful in your wording.
I was referring to a vulnerability in my system. It is evident that _php-crud-api_ is a core that interacts with DB that must be secured

> 'table_authorizer'=>function($cmd,$db,$tab) { return $cmd!='list'; },
Okey, I will try to use it

you added `help wanted` label. What did you mean ? How I can help?

**Comment by mevdschee** [comment]
> It is evident that php-crud-api is a core that interacts with DB that must be secured

Okay, that is indeed as I understood it, but other may see such a remark as a warning against using this code.

>You added help wanted label. What did you mean ? How I can help?

Why would you think that you could help yourself?

**Comment by Denis-Evseev** [comment]
Actually, I am C# + AngularJS developer and don't know how php well. 
But I am really appreciate your work and try to help.

**Comment by mevdschee** [comment]
Thank you for your kind words. Enjoy the software!
