### ISSUE TITLE
Limit the request globally

### ISSUE THREAD

**Issue by atmoner** [mevdschee/php-crud-api#174]
Welcome! Already, thank you for sharing your script, it is really useful to me.
Here is my question: Is it possible to limit the request for output of the API (globally)
Let me explain, I understood that it was possible to limit the "pagination" like this:
`/files?order=id,desc&page=1,10`  

But without the limitation of the pagination, the script returns the totaliter of the table (and with more than 10 000 to enter in bdd it is complicated to manage)

So is it possible to globally limit the number of requests to the page call?

**Comment by mevdschee** [comment]
Thank you for posting a question and I am glad to hear the script is useful. Fortunately somebody else asked a similar question: #172

I hope that helps, if not, please let me know.

**Comment by atmoner** [comment]
Done for me :+1:
At top of api.php:
```
if (isset($_GET['paginate'])) {
	$_GET['page']=$_GET['paginate'].',10';
	$_GET['order']='id,desc';
} else {
	$_GET['page']='1,10';
	$_GET['order']='id,desc'; 
}
```
Small apache coding for url:
`RewriteRule ^files/(.*)$ api.php/files?paginate=$1 [L,QSA]`

And now i can get my website:

> http://api.website.com/files/1
> http://api.website.com/files/2

I get 10 row on each page :muscle:
Thank you for having oriented me! 

Edit: I will probably write a htaccess, I will leave my examples (it will be useful to other users)

**Comment by mevdschee** [comment]
Good thinking, glad I could help!

**Comment by Denis-Evseev** [comment]
If you do not specify order=id  the script will return all. Amended code provided above

`$_GET['page']  =  isset($_GET['paginate'])  ? $_GET['paginate'].',10' : '1,10';
 $_GET['order'] =  isset($_GET['order']) 	? $_GET['order'] : 'id';`
