### ISSUE TITLE
Can't obtain values

### ISSUE THREAD

**Issue by Denis-Evseev** [mevdschee/php-crud-api#178]
This query returns empty array and shows that there are 4366 rows in the table
http://chalkdesk.ru/ajax/api/index.php/mvuzes?order=id&page=1,5&transform=1

where this query
http://chalkdesk.ru/ajax/api/index.php/evuzes?order=id&page=1,5&transform=1
works perfect

No errors in logs, tables the same... can not figure out why it does not work...

**Comment by mevdschee** [comment]
Could this be related to the table_authorizer, column_authorizer or record_filter? Can you post the "create table" scripts for both tables?

**Comment by Denis-Evseev** [comment]
```
CREATE TABLE `mvuzes` (
 `Id` varchar(36) NOT NULL DEFAULT '',
 `Number` int(4) DEFAULT NULL,
 `Name` varchar(422) DEFAULT NULL,
 `Region` varchar(126) DEFAULT NULL,
 `City` varchar(51) DEFAULT NULL,
 `IsState` int(1) DEFAULT NULL,
 `IsMain` int(1) DEFAULT NULL,
 `Licence` varchar(5) DEFAULT NULL,
 `LicenceReleased` varchar(23) DEFAULT NULL,
 `IsBanned` int(1) DEFAULT NULL,
 `Address` varchar(100) DEFAULT NULL,
 `Boss` varchar(76) DEFAULT NULL,
 `Phone` varchar(79) DEFAULT NULL,
 `Fax` varchar(10) DEFAULT NULL,
 `Email` varchar(75) DEFAULT NULL,
 `Site` varchar(100) DEFAULT NULL,
 `Dorm` int(1) DEFAULT NULL,
 `MilitaryDapartment` int(1) DEFAULT NULL,
 `MainImage` varchar(37) DEFAULT NULL,
 `Students` int(5) DEFAULT NULL,
 `Сoefficient` int(1) DEFAULT NULL,
 `Ege` varchar(5) DEFAULT NULL,
 PRIMARY KEY (`Id`),
 UNIQUE KEY `Id` (`Id`),
 KEY `Id_2` (`Id`),
 KEY `Id_3` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by Denis-Evseev** [comment]
I checked mvuzes with evuzes. The difference in KEY `Id_2` (`Id`)

**Comment by mevdschee** [comment]
I'm on it.. please give me a few minutes

**Comment by mevdschee** [comment]
You letter C in "Сoefficient" is not ASCII-7bit

**Comment by Denis-Evseev** [comment]
Thank you, mevdschee!
 I'm so ashamed(

**Comment by mevdschee** [comment]
No worries, glad I could help. Enjoy the software!
