### ISSUE TITLE
Store JSONObject in String type on POST

### ISSUE THREAD

**Issue by saad-siddiqui** [mevdschee/php-crud-api#179]
Hi Maurits, can you please let me know how would I post nested json objects, example:

I have a simple table where in one column i am storing timings for a restaurant and planned to store timings in a serialized json string but when try and do a post on restaurant with an object like so 
```
{
    "restaurant_name" :"JSON Ville",
    ...
    "timings": {
        "Monday":"10AM-10PM",
        ... 
    }
}
```

this request it fails because the type of timings column in MySQL db is VARCHAR, and hence the api script interpreted it as string now if i have to send this data i'll have to escape the whole object before sending it and un-escape before finally using is in my android app.

can we have an option to explicitly allow some columns to be treated as object instead of strings.

**Comment by GrahamCobb** [comment]
Mutter, mutter... Codd's only been dead for 15 years ... What was NoSQL invented for? ...mutter... What about when the app wants to query which restaurants are open at 17:30 tomorrow? ... mutter...

Sorry for adding nothing of value -- seem to be in Grumpy Old Man mode today.

**Comment by saad-siddiqui** [comment]
Unless you are an angle investor, I am not looking towards NoSQL as an alternative to MySQL at this point, well... jokes apart, when Grumpy Old Man mode goes off, I could really do with some help here.
Thanks

**Comment by mevdschee** [comment]
@saad-siddiqui and @GrahamCobb thank you for your question and reply. It seems this case would be most helped by #176 (if you are able to run such a new version of MySQL/MariaDB). 

If you nevertheless insist on storing JSON in VARCHAR types you should escape it properly by using double json encode and the client should double json decode it.

I'm not sure I'm actually helping here, but please give a thumbs up to #176 if that is what you want.

**Comment by mevdschee** [comment]
Closing this one as it seems to be a duplicate.

**Comment by saad-siddiqui** [comment]
Thanks Maurits  @mevdschee  for your suggestion, unfortunately I have MySQL Community v5.5.52, so I will continue to use escaped strings for the time being till I write another api with SLIM

Further I would really like more control over the swagger output.

I'll continue to follow the developments here and hopefully comeback again and again in future as this one of the most helpful scripts out there, Great Job.

**Comment by mevdschee** [comment]
Thank you for your kind words. Ultimately many people will customize an API to their exact needs, as you are going to do with Slim, good choice and good luck!
