### ISSUE TITLE
Feature for Request Limit?

### ISSUE THREAD

**Issue by theBear** [mevdschee/php-crud-api#18]
Hello, I'm glad I could find such an easy tool to start an own rest api. I've just one question, before I will test it in my production: Is it possible to support a request limit (like Facebook or Twitter have)? Let me say 100 requests per day by one ip address. If there are more, the output will give an error. Beneath that I don't need any Authentication, just an ip limit to prevent spam and some bots.

**Comment by mevdschee** [comment]
You need something like this (add the code at the top of "api.php"):

https://www.leaseweb.com/labs/2015/06/limit-concurrent-php-requests-using-memcache/

Although this does not limit on number of requests (just on concurrency). It is quite easy to adjust that script to behave the way you want.

You do need memcache to keep track of request counts.

Let me know whether that helps.
