### ISSUE TITLE
List + Filter NE (Not Equals) ?

### ISSUE THREAD

**Issue by VyseExhale** [mevdschee/php-crud-api#182]
Is it possible to implement a not equals operator for filters?
I want to do something like this:
`GET http://localhost/api.php/categories?filter=name,ne,Internet`
The expected result should return me all categories except results where name equals "Internet"

In SQL this would be done:
`SELECT * FROM categories WHERE name <> "Internet"`

**Comment by mevdschee** [comment]
Yes, totally possible, you can use "neq" as described here:

https://github.com/mevdschee/php-crud-api/blame/master/README.md#L168

**Comment by mevdschee** [comment]
Thank you for your contribution Barry, much appreciated! Maybe you were using an old version? Anyway, please open a new issue if there is anything I can help you with. Kind regards, Maurits.
