### ISSUE TITLE
Error : Not found (entity)

### ISSUE THREAD

**Issue by siddhesh15** [mevdschee/php-crud-api#186]
It gives me error as **Not found (entity)**, when tried path - `api.php?path=/posts?transform=1&order=id,desc&page=1,10`

But it gives data for path  - `api.php?path=/posts` and for path - `api.php`

I am using it on Nginx server 1.10.0 and PHP 7 on Ubuntu.
I have tried it to run on one host but it won't help. Using Curl call alway gives null value as output.
Please suggest some solution.

**Comment by dhruwal** [comment]
Not sure if you are doing it write, there cant be two question marks as it represents part of query string.
Maybe try like this:
(Assuming posts is the table name.)
api.php/posts/?transform=1&order=id,desc&page=1,10

**Comment by mevdschee** [comment]
Thank you for your question and even more for the good reply. Please read the readme on using nginx.

**Comment by siddhesh15** [comment]
@dhruwal Thanks for reply.
I have tried it already but it gives 404 error in Codeigniter and if I used it as `localhost/api.php/posts/?transform=1&order=id,desc&page=1,10` it gives Nginx 404 error.

**Comment by mevdschee** [comment]
Are you using FPM? What is you nginx configuration?

**Comment by siddhesh15** [comment]
@mevdschee Thanks for pointing this out using readme.

I have added below code to my conf file -

_location ~ [^/]\.php(/|$) {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    try_files $fastcgi_script_name =404;
    set $path_info $fastcgi_path_info;
    fastcgi_param PATH_INFO $path_info;
    fastcgi_index index.php;
    include fastcgi.conf;
    fastcgi_pass unix:/run/php/php7.0-fpm.sock;
}_

_location ~ /\.ht {
    deny all;
}_

and it works.
Thank you very much.

**Comment by mevdschee** [comment]
You are welcome. That config looks good. I'm glad you got it working. Enjoy the software!
