### ISSUE TITLE
Implement auth

### ISSUE THREAD

**Issue by FigueiredoStable** [mevdschee/php-crud-api#187]
Hi, i am newb in PHP, so i have a doubt...

My site have a form to make a authentication user by checking previously on database (with bcrypt), if registered its ok login successfully.  

I use api.php from the examples and works perfectly, but, how i can use use my users database to authenticate the api?

**Comment by mevdschee** [comment]
Use the [php-api-auth](https://github.com/mevdschee/php-api-auth) (auth.php) and implement a database username/password check in the 'authenticator' callback.

**Comment by FigueiredoStable** [comment]
Thanks  Maurits, the explanation is not there... where i can found it?

When you say to implement in 'authenticator' callback is here:

-------->
if ($method==$verb && trim($path,'/')==$request) {
			$input = $this->retrieveInput($post);
			if ($authenticator && isset($input->$username) && isset($input->$password)) {
				$authenticator($input->$username,$input->$password);
				if ($no_session) {
					echo json_encode($this->generateToken($_SESSION,$time,$ttl,$algorithm,$secret));
				} else {
					session_regenerate_id();
					setcookie('XSRF-TOKEN',$_SESSION['csrf'],0,'/');
					echo json_encode($_SESSION['csrf']);
				}
----->

You can indicate how i can do this?

**Comment by mevdschee** [comment]
>You may use the [php-api-auth](https://github.com/mevdschee/php-api-auth) (auth.php) and implement a database username/password check in the 'authenticator' callback.

see: https://github.com/mevdschee/php-crud-api/blob/master/api.php#L2411

>In the comments at the bottom of the api.php file you can read briefly what to do.

see: https://github.com/mevdschee/php-crud-api/blob/master/api.php#L2395
and: https://github.com/mevdschee/php-crud-api/blob/master/api.php#L2408

**Comment by FigueiredoStable** [comment]
Thanks, i will make this.

**Comment by mevdschee** [comment]
You are welcome!
