### ISSUE TITLE
Composer / Packagist integration with versioning

### ISSUE THREAD

**Issue by nahuelhds** [mevdschee/php-crud-api#188]
Hi it'be nice to be able to install this package from Composer or Packagist. I assume you'd only would have to add a namespace for it.

That way we could get everyt advance in the project any time.

Thanks

**Comment by mevdschee** [comment]
Hi, thank you for reaching out. Composer or Packagist integration would indeed be helpful, which would also require some versioning standard I guess.

>That way we could get everyt advance in the project any time.

Sorry, I don't understand. Please elaborate.

**Comment by nahuelhds** [comment]
If you use composer, and an least register the master branch, every time
you commit anything there I can get it by doing "composer update".

I could create a pull request with the composer file if you want. It's not
something difficult to do at all. Let me know. I would be glad to help.

Regards


Nahuel Sotelo | Desarrollo de soluciones
Acevedo 83, Piso 5, Of. 1 (B1828BPA)
Lomas de Zamora, Buenos Aires, Argentina
(+5411) 5263-0144 | www.cristalmedia.net
<http://www.twitter.com/CristalMedia>
<http://www.linkedin.com/company/cristalmedia>
<http://www.facebook.com/CristalMedia>
<http://plus.google.com/+CristalmediaNet>

2017-02-22 16:24 GMT-03:00 Maurits van der Schee <notifications@github.com>:

**Comment by karllhughes** [comment]
Yes, this would be very helpful. I'd recommend adding a Changelog and adopting [semver](http://semver.org/).

@nahuelhds if I can help I'm happy to. Just let me know!

**Comment by mevdschee** [comment]
@karllhughes yes.. I agree, the project is ready to be properly versioned! :-)

**Comment by mevdschee** [comment]
v1.0.0 has just been released!

**Comment by nahuelhds** [comment]
Nice

**Comment by nahuelhds** [comment]
Just in case anyone want to add it with Composer in the meantime you can do:

```
{
    "repositories": [{
        "type": "package",
        "package": {
            "name": "mevdschee/php-crud-api",
            "version": "master",
            "source": {
                "url": "https://github.com/mevdschee/php-crud-api.git",
                "type": "git",
                "reference": "master"
            }
        }
    }],
    "require": {
        "mevdschee/php-crud-api": "@dev"
    }
}
```

As it's not using namespaces or anything like that **you have to manually add the api file as the autoloader won't map the classes from the project**

Personally, I've created a class to extend the PHP_CRUD_API one. So I did it like this:

```
<?php

namespace MyNameSpace;

// Docs: https://github.com/mevdschee/php-crud-api#usage
include './vendor/mevdschee/php-crud-api/api.php';

class Api extends \PHP_CRUD_API
{
```

Hope this help!

**Comment by mevdschee** [comment]
Yes.. I think I can apply this. Let me give it a shot and I'll let you know.

**Comment by nahuelhds** [comment]
I'll try a PR tonight after work!

**Comment by karllhughes** [comment]
@nahuelhds just curious, have you had time to put this out on Composer yet? If not, I'll try your workaround, just wanted to check in on this.

Thanks!

**Comment by nahuelhds** [comment]
Hi Karl. Not really. So go on. If you need anything let me know.


Nahuel Sotelo | Desarrollo de soluciones
Acevedo 83, Piso 5, Of. 1 (B1828BPA)
Lomas de Zamora, Buenos Aires, Argentina
(+5411) 5263-0144 | www.cristalmedia.net
<http://www.twitter.com/CristalMedia>
<http://www.linkedin.com/company/cristalmedia>
<http://www.facebook.com/CristalMedia>
<http://plus.google.com/+CristalmediaNet>

2017-03-19 19:14 GMT-03:00 Karl L. Hughes <notifications@github.com>:

**Comment by mevdschee** [comment]
Me neither, mainly because other interesting stuff came along. But it is still a good idea.

**Comment by mevdschee** [comment]
Wow! thank you very much and feel free to open a new issue for further improvements.
