### ISSUE TITLE
Two FK => same table

### ISSUE THREAD

**Issue by nahuelhds** [mevdschee/php-crud-api#189]
Hi again, I have the following usecase:
Primary Table with two relations that points to the same table

Example:
The main table is: TABLE MyTable, FIELDS: id, user_id, creator_id
The fields user_id and creator_id are FKs to the table User: TABLE User, FIELDS: id, username

The FKs are defined like this
```
ALTER TABLE `MyTable`
ADD CONSTRAINT `user`
  FOREIGN KEY (`user_id`)
  REFERENCES `User` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `Table`
ADD CONSTRAINT `creator`
  FOREIGN KEY (`creator_id`)
  REFERENCES `User` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
```

The problem is that when I do: 
```
GET http://127.0.0.1/api.php/MyTable?include=user,creator&filter=id,eq,1
```` 

The result only brings me the first relation, not both. I think it's because both FKs points to the same table. I'm doing this right? If not, what I'm doing wrong?

Thanks in advance

**Comment by nahuelhds** [comment]
This is the result
```
{
  "MyTable": [
    {
      "id": 1,
      "user_id": 1,
      "user": [
        {
          "id": 1,
          "username": "test"
        }
      ],
      "creator_id": 2
    }
  ]
}
```

**Comment by nahuelhds** [comment]
I changed the following

```
ALTER TABLE `MyTable`
ADD CONSTRAINT `user`
  FOREIGN KEY (`user_id`)
  REFERENCES `User` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
```

to

```
ALTER TABLE `MyTable`
ADD CONSTRAINT `tester`
  FOREIGN KEY (`user_id`)
  REFERENCES `User` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
```` 

Now then I do 

```
GET http://127.0.0.1/arm/assessrisk/api.php/MyTable?include=tester,creator&filter=id,eq,1
```

I don't get any relation, so I assume that the relation is restricted to the field with name equally to the table name... Even weirder is that doing

```
GET http://127.0.0.1/arm/assessrisk/api.php/MyTable?include=user&filter=id,eq,1
```

I get the relation in tester (which is the field named user_id.

So I think it'd nice if we could bring the relations based on the CONSTRAINT name, wouldn't it?

**Comment by mevdschee** [comment]
>So I think it'd nice if we could bring the relations based on the CONSTRAINT name, wouldn't it?

Are you sure that is more appropriate than on foreign key field name?

**Comment by nahuelhds** [comment]
I'll try what you say and I'll let you know. Sorry if I bring an issue based on my misunderstanding of your tool -which is excellent!

**Comment by mevdschee** [comment]
WARNING: Two foreign keys to one table is not supported at the moment!

>I'll try what you say and I'll let you know.

You can't.. I'm philosophizing about a feature that does not exist yet..

>Sorry if I bring an issue based on my misunderstanding of your tool -which is excellent!

Don't be.. I love it that people help out to improve the software! Thank you for your kind words.

**Comment by nahuelhds** [comment]
Oh I understand now what you meant with 
> include=creator_id.User,user_id.User

I think that using the Constraint name would be cleaner as you don't start messing with combinations and instead you use SQL standards for the FK. That's my thought

**Comment by mevdschee** [comment]
>Primary Table with two relations that points to the same table

Did you analyze the non-transformed output? Does it contain the proper records?

**Comment by nahuelhds** [comment]
Yeah, it doesn't contain them

**Comment by mevdschee** [comment]
Could you give me a minimal example in a SQL dump and the HTTP request you are doing on it?

**Comment by nahuelhds** [comment]
This is the sql for the schema creation

```
CREATE TABLE `my_table` (
  `id` int(11) NOT NULL,
  `id_user` int(11) DEFAULT NULL,
  `id_creator` int(11) DEFAULT NULL,
  `name` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `my_table` (`id`, `id_user`, `id_creator`, `name`) VALUES
(1, 1, 1, '1st rel'),
(2, 2, 1, '2nd rel'),
(3, 3, 1, '3rd rel');

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `name` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `user` (`id`, `name`) VALUES
(1, 'Nahuel'),
(2, 'Nicolas'),
(3, 'Michael');

ALTER TABLE `my_table`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_idx` (`id_user`),
  ADD KEY `creator_idx` (`id_creator`);

ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `my_table`
  ADD CONSTRAINT `creator` FOREIGN KEY (`id_creator`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `user` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
```

**Comment by nahuelhds** [comment]
The request is
```
curl -X GET "http://127.0.0.1/arm/assessrisk/api.php/my_table?include=user%2Ccreator"
```

The result without transform is:
```
{
  "my_table": {
    "columns": [
      "id",
      "id_user",
      "id_creator",
      "name"
    ],
    "records": [
      [
        1,
        1,
        1,
        "1st rel"
      ],
      [
        2,
        2,
        1,
        "2nd rel"
      ],
      [
        3,
        3,
        1,
        "3rd rel"
      ]
    ]
  },
  "user": {
    "relations": {
      "id": "my_table.id_user"
    },
    "columns": [
      "id",
      "name"
    ],
    "records": [
      [
        1,
        "Nahuel"
      ],
      [
        2,
        "Nicolas"
      ],
      [
        3,
        "Michael"
      ]
    ]
  }
}
```

And the result JSON formatted is:

```
{
  "my_table": [
    {
      "id": 1,
      "id_user": 1,
      "user": [
        {
          "id": 1,
          "name": "Nahuel"
        }
      ],
      "id_creator": 1,
      "name": "1st rel"
    },
    {
      "id": 2,
      "id_user": 2,
      "user": [
        {
          "id": 2,
          "name": "Nicolas"
        }
      ],
      "id_creator": 1,
      "name": "2nd rel"
    },
    {
      "id": 3,
      "id_user": 3,
      "user": [
        {
          "id": 3,
          "name": "Michael"
        }
      ],
      "id_creator": 1,
      "name": "3rd rel"
    }
  ]
}
```

**Comment by mevdschee** [comment]
This is fixed in v2 (beta). Does it meet your needs?
