### ISSUE TITLE
Authentication for api

### ISSUE THREAD

**Issue by cloud111** [mevdschee/php-crud-api#19]
How can I authentic a user accessing the api??

**Comment by mevdschee** [comment]
Authentication is not part of the code (as the readme states). If you want to add authentication, then add something like basic authentication. It is explained here:

http://www.phpgang.com/using-http-basic-auth-in-php-the-easy-way_2974.html

The code should be added at the top of the "api.php" file. After authentication you may base your authorization decisions on the logged in user.

Hope that helps, good luck!

**Comment by cloud111** [comment]
Yeah! Thanks
