### ISSUE TITLE
Support `json` data type in Postgres

### ISSUE THREAD

**Issue by karllhughes** [mevdschee/php-crud-api#190]
I noticed that in the `isJsonType` method in the PostgreSQL class, only `jsonb` is translated as JSON data:

```
public function isJsonType($field) {
    return $field->type == 'jsonb';
}
```

Is there any downside to making this work the same way that SQLite does so that `json` data types are supported as well? Something like:

```
public function isJsonType($field) {
    return in_array($field->type, array('json','jsonb'));;
}
```

If you think it's a good idea, I'll make a PR. Thanks!

**Comment by mevdschee** [comment]
Do you think that would be valuable? Please do the PR.. I'll merge it. Thank you very much!

**Comment by mevdschee** [comment]
Maybe support xml as well?

**Comment by karllhughes** [comment]
Ok, I'll make the PR for supporting JSON in Postgres.

I don't have a good way to test out the SQL Server XML as I'm on a Mac, but maybe I can set up a VM to look into it.

How do you test this out with multiple databases? Do you have some vagrant boxes set up on your machine?

**Comment by mevdschee** [comment]
@karllhughes I meant.. maybe add JSON stored in JSON/JSONB/XML fields in PostgreSQL. Storing JSON in XML is what we do in SQL Server (because the XML support is better than the JSON support).

See: https://github.com/mevdschee/json2xml.php/blob/master/json2xml.php

**Comment by mevdschee** [comment]
It seems that the XML data type could be supported in PostgreSQL. I have found the following document:

https://www.postgresql.org/docs/9.2/static/datatype-xml.html

**Comment by mevdschee** [comment]
Although it is tempting, let's leave XML support out for now.
