### ISSUE TITLE
Swagger output not working in "Swagger Editor"

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#193]
Some errors:

✖ Swagger Error

Not a valid parameter definition
Jump to line 128
Details
Object
code: "ONE_OF_MISSING"
params: Array [0]
message: "Not a valid parameter definition"
path: Array [5]
0: "paths"
1: "/categories"
2: "post"
3: "parameters"
4: "0"
schemaId: "http://swagger.io/v2/schema.json#"
inner: Array [2]
0: Object
code: "ONE_OF_MISSING"
params: Array [0]
message: "Data does not match any schemas from 'oneOf'"
path: Array [5]
inner: Array [2]
1: Object
code: "OBJECT_MISSING_REQUIRED_PROPERTY"
params: Array [1]
message: "Missing required property: $ref"
path: Array [5]
level: 900
type: "Swagger Error"
description: "Not a valid parameter definition"
lineNumber: 128

✖ Swagger Error

Not a valid response definition
Jump to line 98
Details
Object
code: "ONE_OF_MISSING"
params: Array [0]
message: "Not a valid response definition"
path: Array [5]
0: "paths"
1: "/categories"
2: "get"
3: "responses"
4: "200"
schemaId: "http://swagger.io/v2/schema.json#"
inner: Array [2]
0: Object
code: "ONE_OF_MISSING"
params: Array [0]
message: "Data does not match any schemas from 'oneOf'"
path: Array [6]
inner: Array [2]
1: Object
code: "OBJECT_MISSING_REQUIRED_PROPERTY"
params: Array [1]
message: "Missing required property: $ref"
path: Array [5]
level: 900
type: "Swagger Error"
description: "Not a valid response definition"
lineNumber: 98

See: http://editor.swagger.io/

**Comment by jr3cermak** [comment]
Which database driver is causing this?

**Comment by mevdschee** [comment]
MySQL.. latest master.. maybe I broke it, but I don't understand these messages.

**Comment by jr3cermak** [comment]
Here is one error.   I stumbled on it earlier.   "required" can't be used in the Parameter section.   Change that to: allowEmptyValue: {true,false}.   Unfortunately, it is the reverse of required.

**Comment by jr3cermak** [comment]
So... parameters: can use allowEmptyValue.  This can not be used in the response: section.  In the parameters: section change required -> allowEmptyValue.   In the response: section, it may be good to show this as a feature of the field.   Change to x-required:.

**Comment by mevdschee** [comment]
I believe "allowEmptyValue" does something else. I introduced "x-nullable" for the "response" section and ensures the "default" values have the right type.

**Comment by mevdschee** [comment]
I now use required as an array on the object level in the response, that seems valid.

**Comment by mevdschee** [comment]
I still get "Object is missing the required property 'undefined'" when using the "try out" functionality and creating a record with non-required fields. Is this a bug in Swagger editor?

**Comment by mevdschee** [comment]
I guess it was a glitch in the matrix, because I can't reproduce that problem anymore.

**Comment by jimaan** [comment]
Hi,

I'm also getting the same error when using the Swagger Editor. I tried to copy the full error message(expanding the crappy tree interface). If required I can post/pm the output Swagger Spec.

Editor error:
Error
 Object
code: "ONE_OF_MISSING"
 params: Array [0]
message: "Not a valid parameter definition"
 path: Array [5]
0: "paths"
1: "/clients/{id}"
2: "patch"
3: "parameters"
4: "1"
schemaId: "http://swagger.io/v2/schema.json#"
 inner: Array [2]
 0: Object
code: "ONE_OF_MISSING"
 params: Array [0]
message: "Data does not match any schemas from 'oneOf'"
 path: Array [5]
0: "paths"
1: "/clients/{id}"
2: "patch"
3: "parameters"
4: "1"
 inner: Array [2]
 0: Object
code: "INVALID_TYPE"
 params: Array [2]
0: "integer"
1: "string"
message: "Expected type integer but found type string"
 path: Array [4]
0: "schema"
1: "properties"
2: "LastCMD"
3: "maxLength"
 1: Object
code: "OBJECT_MISSING_REQUIRED_PROPERTY"
 params: Array [1]
0: "type"
message: "Missing required property: type"
 path: Array [0]
 1: Object
code: "OBJECT_MISSING_REQUIRED_PROPERTY"
 params: Array [1]
0: "$ref"
message: "Missing required property: $ref"
 path: Array [5]
0: "paths"
1: "/clients/{id}"
2: "patch"
3: "parameters"
4: "1"

Added the screenshot for error clarification. 
![editor-error-api](https://cloud.githubusercontent.com/assets/6625922/23360030/6abc4060-fce9-11e6-82cd-af5639bc42cf.PNG)

Yesterday I merged the changes from the last three weeks or so. Before the merging the output Spec is validated correctly by the Editor. Although the generated (C#) client did not function properly. But hey that could be on my hand.

So I guess the matrix is repeating itself? Miiieuw.... :) I hope you can give me a push in the right direction.

**Comment by mevdschee** [comment]
I guess the matrix is fine, maybe you can try to clear your cache.. pull latest changes.. and try again :-)

Hopefully that helps for you too..

**Comment by mevdschee** [comment]
@jimaan Can you see whether the issue still exists with the latest version?

**Comment by jimaan** [comment]
@mevdschee The latest commit fixed the issue for me. Thanks for putting in your effort!
