### ISSUE TITLE
Feature detection for test suite

### ISSUE THREAD

**Issue by karllhughes** [mevdschee/php-crud-api#194]
While working on #190 I realized that the tests require [PostGIS](http://www.postgis.net/). While this is not an uncommon extension, it's not a default one either.

I don't necessarily think it should be removed as a requirement, but I do think that we should list the database extensions required to run the tests. It would help future devs get up and running faster.

What do you think?

**Comment by karllhughes** [comment]
I should have read more carefully 😞 

https://github.com/mevdschee/php-crud-api/blob/master/README.md#requirements

**Comment by mevdschee** [comment]
@karllhughes I totally agree. It would be very helpful if there was some form of feature detection in the test suite, so that devs could get up to speed much faster with any version.

**Comment by karllhughes** [comment]
One option would be to include vagrant or Docker files in the repo. This way, new devs could use those to ensure they have the same environment as others when running tests.

When I was testing, I set up a Docker container with Linux, Apache, PHP, and Postgres/Postgis. I'll look into what it might take to get all the tests running in Docker containers.

**Comment by mevdschee** [comment]
another way would be to just detect the version of the database and adjust the test suite accordingly.. skipping tests for not supported functionality.. that does not rule out the use of docker.. but it is more light weight..

**Comment by karllhughes** [comment]
That's a good point. It also still doesn't help if the developer is using a database without all the correct extensions, but it would be lighter weight.

In an ideal world the test suite would be able to test _all_ different database connections during its run, but I don't know exactly how you'd go about doing that.

**Comment by mevdschee** [comment]
Yes, but I would rather make it easy for anyone to run the test (successfully) and report relevant test failures, than that it becomes harder to run them. Although it would still be good to easily run the full suite on multiple platforms. It is just that you are aiming much higher than I am when I when simply skipping non-supported functionality to avoid false-negatives in the tests. Also running the test suite may inform the user of the non-supported functionality, which would be useful in many cases.

**Comment by karllhughes** [comment]
I did some work on Phinx this week and their test suite has similar feature detection. I'm going to look into making this update and will send a PR sometime next week.

**Comment by karllhughes** [comment]
I've been doing a lot of looking into these tests. So far, they all run successfully on:

- PHP 5.3 through PHP 7.1, although there are some deprecation notices
- MySQL 5.7+
- Postgres 5.4+
- SQLite 3

So, now my plan is to:

- Adjust the test suite to test for versions of MySQL and Postgres
- If an older version is detected, it will skip the tests that can't be run

Eventually, I'd like to automate all these combinations with Travis, but for now I'm going to focus on locally running everything with all the various versions.

**Comment by mevdschee** [comment]
@karllhughes check out this issue and my comments/research:

https://github.com/mevdschee/php-crud-api/issues/176#issuecomment-278112391

Here you see some analysis of versions and feature support.

**Comment by karllhughes** [comment]
Awesome, thanks @mevdschee. I'll let you know if I have any further questions, but your list there should make this pretty straight forward.

**Comment by mevdschee** [comment]
>Postgres 5.4+

That is a typo, right?

**Comment by karllhughes** [comment]
@mevdschee I was saying that the tests do run successfully for me on Postgres 5.4 and greater.

With the latest update, they now run on older versions down to 9.1. I think this comment was just old.

**Comment by mevdschee** [comment]
Okay, I finished testing on all VM's and I got the feeling that this feature works! Centos 6.9 has PostgreSQL 8.4 and MySQL 5.1 and is thus not usable out-of-the-box. Other machines all report successful tests.
