### ISSUE TITLE
Multiple parameter sorting doesn't work on a View with Unions

### ISSUE THREAD

**Issue by thoughtgap** [mevdschee/php-crud-api#196]
Hi, first of all thank you for the nice API.

I have a view `view_balances` in my MySQL-Database like this:

```
SELECT account_id, zeit as timestamp, balance FROM balances
UNION ALL
SELECT id as account_id, cast('1980-01-01 00:00:00' as datetime) as timestamp, 0 as balance FROM accounts
UNION ALL
SELECT id as account_id, cast('2020-12-31 00:00:00' as datetime) as timestamp, 99999 as balance FROM accounts
```

In this example we'll have two accounts and one balance of 500 in 2013 for the first account.

If I query this view by `api.php/view_balances?order=timestamp` it displays the entries in the correct order, sorted by timestamp:

account_id | timestamp | balance
--- | --- | ---
1 | 1980-01-01 00:00:00 | 0
2 | 1980-01-01 00:00:00 | 0
1 | 2013-01-01 00:00:00 | 500
1 | 2020-12-31 00:00:00 | 99999
2 | 2020-12-31 00:00:00 | 99999

But if I try to multi-sort like this: `api.php/view_balances?order[]=account_id&order[]=timestamp` the entries are not sorted anymore, but displayed as they come out of the unsorted view:

account_id | timestamp | balance
--- | --- | ---
1 | 2013-01-01 00:00:00 | 500
1 | 1980-01-01 00:00:00 | 0
2 | 1980-01-01 00:00:00 | 0
1 | 2020-12-31 00:00:00 | 99999
2 | 2020-12-31 00:00:00 | 99999

I'd expect:

account_id | timestamp | balance
--- | --- | ---
1 | 1980-01-01 00:00:00 | 0
1 | 2013-01-01 00:00:00 | 500
1 | 2020-12-31 00:00:00 | 99999
2 | 1980-01-01 00:00:00 | 0
2 | 2020-12-31 00:00:00 | 99999

What am I doing wrong? The multi-sort works on a single table that is not a view.
`SELECT * FROM view_balances ORDER BY account_id, timestamp` does also work the expected way.

Is there any way I can debug this and get the query from the api.php-Script?

Thanks a lot in advance.

**Comment by jr3cermak** [comment]
I am having a devil of a time reproducing this issue.   Do you have a small sql setup script I can import into a test database?    Looks like there are two tables and one view? Thanks!

```
mysql> create view testme AS SELECT account_id, zeit as timestamp, balance FROM balances
    -> UNION ALL
    -> SELECT id as account_id, cast('1980-01-01 00:00:00' as datetime) as timestamp, 0 as balance FROM accounts
    -> UNION ALL
    -> SELECT id as account_id, cast('2020-12-31 00:00:00' as datetime) as timestamp, 99999 as balance FROM accounts;
ERROR 1054 (42S22): Unknown column 'zeit' in 'field list'
```

**Comment by mevdschee** [comment]
There is a line you can uncomment to debug sql statements:

https://github.com/mevdschee/php-crud-api/blob/master/api.php#L154

Maybe that helps you analyze the problem.

**Comment by thoughtgap** [comment]
Thanks for your input. After the line mentioned by @mevdschee's was not Line 154 for me, I updated the api.php script (my old version was from 21.12.2016) and now it seems to work fine. I'm very sorry to have wasted your time. I will do extensive testing tonight and then report back.

Here's the full commands for reproduction though:

```
CREATE TABLE test_accounts ( id INT NOT NULL ) ENGINE = InnoDB;
CREATE TABLE test_balances ( account_id INT NOT NULL , timestamp DATETIME NOT NULL , balance INT NOT NULL ) ENGINE = InnoDB;
INSERT INTO test_accounts (id) VALUES ('1');
INSERT INTO test_accounts (id) VALUES ('2');
INSERT INTO test_balances (account_id, timestamp, balance) VALUES ('1', '2017-02-28 10:00:00', '500');
INSERT INTO test_balances (account_id, timestamp, balance) VALUES ('1', '2017-02-01 10:00:00', '300');

CREATE
 ALGORITHM = UNDEFINED
 VIEW test_allbalances
 AS SELECT account_id, timestamp, balance FROM test_balances
UNION ALL
SELECT id as account_id, cast('1980-01-01 00:00:00' as datetime) as timestamp, 0 as balance FROM test_accounts
UNION ALL
SELECT id as account_id, cast('2020-12-31 00:00:00' as datetime) as timestamp, 99999 as balance FROM test_accounts
```

`api.php/test_allbalances?order[]=account_id&order[]=timestamp` is outputting

```
{test_allbalances: {
columns: ["account_id","timestamp","balance"],
records: [
	[1,"1980-01-01 00:00:00",0],
	[1,"2017-02-01 10:00:00",300],
	[1,"2017-02-28 10:00:00",500],
	[1,"2020-12-31 00:00:00",99999],
	[2,"1980-01-01 00:00:00",0],
	[2,"2020-12-31 00:00:00",99999]]}}
```

now, like it should.

Old version returned:

```
{test_allbalances: {
columns: ["account_id","timestamp","balance"],
records: [
[1,"2017-02-28 10:00:00",500],
[1,"2017-02-01 10:00:00",300],
[1,"1980-01-01 00:00:00",0],
[2,"1980-01-01 00:00:00",0],
[1,"2020-12-31 00:00:00",99999],
[2,"2020-12-31 00:00:00",99999]]}}
```

Sorry again!
