### ISSUE TITLE
Adding apikey authentication to swagger definition

### ISSUE THREAD

**Issue by jr3cermak** [mevdschee/php-crud-api#197]
This enhancement cuts across two projects.  To enable the apikey to work via swagger, a swagger definition has to be added in the json reply.   The minimal json that enables use of the apikey for authentication is:

```
securityDefinitions:
  UserSecurity:
    type: apiKey
    in: query
    name: apikey
security:
  - UserSecurity: [] 
```

What this does is attach the apikey= argument to the URL.   What would be the best was to signal the code that this authentication method is in use?   Would it be something like?

```
// $api = new PHP_CRUD_API(array(
//      'dbengine'=>'MySQL',
//      'hostname'=>'localhost',
//      'username'=>'',
//      'password'=>'',
//      'database'=>'',
//      'charset'=>'utf8',
//      'security'=>'apikey/query'
//
// ));
// $api->executeCommand();
```

If we pass PHP_CRUD_API the whole Auth object, we can just operate on it.  Say:

```
// Auth is always checked before the CRUD_API
$auth = new PHP_API_AUTH(....);

// $api = new PHP_CRUD_API(array(
//      'dbengine'=>'MySQL',
//      'hostname'=>'localhost',
//      'username'=>'',
//      'password'=>'',
//      'database'=>'',
//      'charset'=>'utf8',
//      'security'=> $auth,
//
// ));
// $api->executeCommand();
```

I think I like the latter method.    This is ok for setting global access at the top level.   How to press security down into the individual sections is a bit more difficult.   For example, require security for read/write on this or that table.

For now, I am in the need for a global (api) wide security layer instead of fine grained.

**Comment by mevdschee** [comment]
Let's collect some background information, so that we can make a good implementation. Here is the link to the security specification of swagger:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-definitions-object

My first question is how we should model our jwt+session security in this specification. It is not clear to me yet.

**Comment by mevdschee** [comment]
We could allow specifying the session identifier as an apikey, but I'm afraid all that does is weaken the security model. An area in which I'm not keen to compromise. Session cookies can be set to "HttpOnly" which makes them secure. An apikey is less secure as JavaScript can read it and it can thus be stolen using an XSS vulenerability.

**Comment by jr3cermak** [comment]
Is there a specific danger to transmitting the key in a query or header if https is used?   I can certainly understand that the basic and apiKey authentication under http is not recommended.   For testing, sure, but never in production.

Our specific use case is to use this API software as a notification (hook) for events say after someone has made a credit card payment via Authorize.Net or PayPal.    The web hook does not necessarily allow for a two step process auth+token; to authorize first and then use a session/cookie token to proceed.  At best, you can give it a url and maybe some other credentials to pass along with the call.

At least with PayPay, a webhook cannot be created using http, they enforce https.  http://paypal.github.io/PayPal-PHP-SDK/sample/doc/notifications/CreateWebhook.html
In their particular example, the uniqid= is the apikey.   The name of the key is arbitrary.

Going back to your question "My first question is how we should model our jwt+session security in this specification. It is not clear to me yet.".   The specification and use is not very clear.   The only other model to work with is "oauth2".   The scope definitions are baffling as well.   It isn't clear how those are applied.    It will be a bit of fun to poke around with "oauth2" and see if it can be adapted to what you have going on in the code.

**Comment by mevdschee** [comment]
I would strongly recommend that you do NOT use a shared secret without expiration when implementing a payment solution.

If you nevertheless need to protect your script with such a key I would suggest adding the following on the top of your file:

    if (!isset($_GET['uniqid']) || $_GET['uniqid']!='sharedsecret') die('Access denied');

I guess that should do it. Unfortunately it does not help our discussion on how to support secure communications much.

**Comment by jr3cermak** [comment]
No problem.   I am happy to store this in my fork for now.

**Comment by mevdschee** [comment]
Thank you for understanding. Note that I am still open to discussion.
