### ISSUE TITLE
Hosting company does not support PATH_INFO

### ISSUE THREAD

**Issue by marekpridal** [mevdschee/php-crud-api#198]
Hi,

I have a strange problem. I setup API on localhost and everything works. So I put it on server and it gets just table info but not data inside. So I can access on api.php but when I want to go to api.php/<table_name> it gives me error _File not found._. I use MySQL, PHP 7 and server should run on Linux. I also tried to set up PHP-CRUD-UI but same problem there. It gets table names but when I try to open in it gets me _File not found._. Do you have any suggestions how to fix it?

**Comment by mevdschee** [comment]
There are two things to do to analyze your hosting environment:

- Can you uncomment the first line of the "api.php" file and post the output when you go to "api.php/<table_name>"? It will tell me something about the hosting environment. 

- Can you also upload a file with "<?php phpinfo();" in it and post the output here? It will tell me even more about your environment.

Thank you.

**Comment by mevdschee** [comment]
It may be that your hosting environment has nginx and is misconfigured:

>There are many guide about configuring NGINX with PHP FPM, but many of them are incomplete (don’t handle PATH_INFO correctly) or contain security issues (don’t check whether the script is indeed php file).

see: https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/

**Comment by marekpridal** [comment]
- I did that but I still get error File not found without any other info (api.php/<table_name>). When I do it on api.php it gets me _string(3) "GET" NULL_ 

- [phpinfo().pdf](https://github.com/mevdschee/php-crud-api/files/818603/phpinfo.pdf)

**Comment by mevdschee** [comment]
I need to run.. I'll get back to you later.. it is caused by the path_info not set correctly.

**Comment by mevdschee** [comment]
Okay. You seem to be running Nginx with PHP-FPM and it is misconfigured as explained in the link from the nginx site (as I expected). If you have professional hosting, then contact their support and send them the link and if you have setup your own nginx with fpm, then follow the instructions on the link.

**Comment by marekpridal** [comment]
Okay. Thanks a lot! I try to contact a support and hope they help me.

**Comment by marekpridal** [comment]
They have answered me they're using Apache not nginx.

**Comment by mevdschee** [comment]
It does not change that they mis-configured their server. Anyway let me try to help you:

https://github.com/mevdschee/php-crud-api/blob/master/api.php#L2144

Change `$_SERVER['PATH_INFO']` to `$_GET['path']` and use the url like this:

    api.php?path=<table_name>

That should work for you.

**Comment by mevdschee** [comment]
In your configuration add the following:

    'request' => isset($_GET['path'])?$_GET['path']:'',

No instead of calling:

    api.php/<table_name>

You should call:

    api.php?path=<table_name>

and also things like:

    api.php?path=<table_name>/<primary_key>

That should work for you.

**Comment by marekpridal** [comment]
Great!! Now it's working. BTW is there a way how to fix it in UI.php, too?

**Comment by mevdschee** [comment]
Maybe in the following line, do:

https://github.com/mevdschee/php-crud-ui/blob/master/ui.php#L10

replace the `$url` variable the function `call` with:

    $url => preg_replace('|.php/|','.php?path=',$url);

I hope that helps!

**Comment by marekpridal** [comment]
Sadly it doesn't.

```php
    function call($method, $url, $data = false) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
        curl_setopt($ch, CURLOPT_URL, preg_replace('|.php/|','.php?path=',$url));
        if ($data) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
            $headers = array();
            $headers[] = 'Content-Type: application/json';
            $headers[] = 'Content-Length: ' . strlen($data);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        }
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $response = curl_exec($ch);
        curl_close($ch);
        return json_decode($response, true);
    }
```

**Comment by mevdschee** [comment]
Can you try this?

    curl_setopt($ch, CURLOPT_URL, preg_replace('|\.php/([^?]*)\?|','.php?path=\1&',$url));

It should work.

**Comment by marekpridal** [comment]
Still doesn't 😞 
```php
    function call($method, $url, $data = false) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
        curl_setopt($ch, CURLOPT_URL, preg_replace('|\.php/([^?]*)\?|','.php?path=\1&',$url));
        if ($data) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
            $headers = array();
            $headers[] = 'Content-Type: application/json';
            $headers[] = 'Content-Length: ' . strlen($data);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        }
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $response = curl_exec($ch);
        curl_close($ch);
        return json_decode($response, true);
    }
```

**Comment by mevdschee** [comment]
works on my machine ;-)

**Comment by mevdschee** [comment]
Ah.. I guess you also want the ui.php to run on that environment?

**Comment by ksartnl** [comment]
If I do `?path=users/1` I get a JSON result, but with `?path=users` only I get "Not found (entity)". What can I do, I added: `'request' => isset($_GET['path'])?$_GET['path']:''` in the config array.
