### ISSUE TITLE
I cant use transform with filter

### ISSUE THREAD

**Issue by algoritmauzmani** [mevdschee/php-crud-api#199]
I request to Api with my python code. I need to request specisific record. 

GET http://mysite.com/api.php/students?filter=Number, eq, 12345

But i cant use this in python. I need to transforn this. How can i use "?transform = 1" in this case?

my python code like 
r = requests.get("http://mysite.com/api.php/students?filter=Number, eq, 12345")
d = json.loads(r.text)

i want to use **print d['name']** but it fails whe i transform ( http://mysite.com/api.php/students?transform=1) , it works but in json, it includes all records

**Comment by jr3cermak** [comment]
try:
`r = requests.get("http://mysite.com/api.php/students?filter=Number,eq,12345&transform=1")`

The order of the arguments is arbitrary.   This should also work.

`r = requests.get("http://mysite.com/api.php/students?transform=1&filter=Number,eq,12345")`

Be careful with spacing around arguments.

**Comment by algoritmauzmani** [comment]
it works! Thank you...
