### ISSUE TITLE
small test error with daylight savings

### ISSUE THREAD

**Issue by jr3cermak** [mevdschee/php-crud-api#203]
Just before daylight savings time, the tests passed.   But the integer seconds passed is now an hour off.

`                                'before' => function (&$action,&$database,&$table,&$id,&$inputs) { if ($action=='create') foreach ($inputs as $input) if ($input) $input->created_at = date('Y-m-d H:i:s',1386752948); },`

```
1) PHP_CRUD_API_Test::testAddProducts
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'{"id":2,"name":"Laptop","price":"1299.99","properties":{},"created_at":"2013-12-11 10:09:08"}'
+'{"id":2,"name":"Laptop","price":"1299.99","properties":{},"created_at":"2013-12-11 09:09:08"}'
```

Will need to fix that up somehow.   Don't want to change the strings each time we switch between standard/daylight.

**Comment by mevdschee** [comment]
Maybe this helps:

0da7a623fae31d313adc3e260757c59f7078e32f

**Comment by mevdschee** [comment]
Thank you for finding this bug and making it easy to fix.
