### ISSUE TITLE
Fetch ID based on attribute before inserting data into a new row.

### ISSUE THREAD

**Issue by topcat5665** [mevdschee/php-crud-api#204]
I'd like to be able to fetch an ID from a table, based on some attribute sent in a post request, and then use this ID during the creation of a new row in another table.

Let's say I have two tables, "users" and "scores". One of the fields in the "scores" table is user_id (a foreign key pointing to the users table). Naturally, I need a value for user_id in order to insert a new row into the table.

The issue I have here is that I don't want to send the user_id in the post request; I only want to send the username. So, I essentially I need a way of fetching the user_id based on the username I've sent in the post request, and I then storing that ID in the user_id field.

Naturally, I could implement this by adding some special code to make some specific queries. But I was wondering if there was any easier way of doing this using the API?

Thanks.

**Comment by VyseExhale** [comment]
since yesterday there is a "before" method available:

 'before'=>function(&$cmd,&$db,&$tab,&$id,&$in) { /* adjust array $in */ },

Maybe that would help?

**Comment by topcat5665** [comment]
That callback has made my life a lot easier. Modifying the input to the database was very easy to do, all I needed to add was a bit of custom SQL to fetch the user_id.

Thanks again!
