### ISSUE TITLE
I just found this project and am quite interested. 

### ISSUE THREAD

**Issue by timlitw** [mevdschee/php-crud-api#205]
I am working on a project with instruction from a course on udemy,  The app is in ionic2 and the service the instructor created was a local service for the purpose of the course - my only problem is I haven't learned enough of javascript/angular2/ionic2 to know how to read 
{
  "jobs": [
    {
      "id": "1",
      "date": "2017-03-09",
      "farmername": "John Doe",
      "fieldname": "South 1/2 South 80",
      "acres": "35",
      "swathed": 35,
      "baled": 160,
      "loaded": 160,
      "hauled": 0,
      "distance": "0",
      "note": "",
      "latitude": "38.361676",
      "longitude": "-97.126971"
    }
  ]
}

that is output by this project instead of 

{
      "id": "1",
      "date": "2017-03-09",
      "farmername": "John Doe",
      "fieldname": "South 1/2 South 80",
      "acres": "35",
      "swathed": 35,
      "baled": 160,
      "loaded": 160,
      "hauled": 0,
      "distance": "0",
      "note": "",
      "latitude": "38.361676",
      "longitude": "-97.126971"
    }
that his example server served.  Could there be an option that doesn't serve the Json with the table name wrapped around it?  I already know the table name.   Or if someone would be kind enought to help me with the javascript code to parse it properly I would greatly appreciate it.

Thanks

**Comment by mevdschee** [comment]
Have you seen the angular2 example in the folder 'examples'? Can you post the code where you consume the API?

**Comment by timlitw** [comment]
I have looked at it - like i said I am just learning javascript - there is to much difference between what I have and what I see here.

in my job.service.ts I have

` getJobs(): Promise<Job[]> {
    return this.http.get('https://myurl/jobs?transform=1')
      .toPromise()
      .then(response => response.json());
  }`
in jobs.ts page I have
`  ionViewWillEnter() {
    this.jobService.getJobs()
      .then(jobs => this.jobs = jobs);
  }`

then in the html template, I iterate thru the jobs to create a list of buttons to click to choose the job and then go to the job detail page.
`<ion-content padding>
    <ion-list>
      <button ion-item *ngFor="let job of jobs"
        (click)="onJobClick(job)">
        <h2>{{job.date | date}}</h2>
       <div> {{ job.farmername }} - {{job.fieldname}}</div>
        <ion-note item-right>{{job.acres}} A</ion-note>
       <p>
         Acres Swathed: <b ion-text color="danger">{{job.swathed}}</b>, 
         Bales Baled: <b ion-text color="danger">{{job.baled}}</b> 
      </p>
       <p>
         Loaded: <b ion-text color="danger">{{job.loaded}}</b>, 
         Hauled: <b ion-text color="danger">{{job.hauled}}</b> - 
         <b ion-text color="danger">{{job.distance}}</b> miles
      </p>
      </button>
    </ion-list>
  </ion-content>
`

**Comment by mevdschee** [comment]
Maybe you should change `then(response => response.json())` to `then(response => response.json().jobs)`

**Comment by timlitw** [comment]
the error then changes to: Error in ./Jobs class Jobs - inline template:11:23 caused by: Cannot read property 'jobs' of undefined which is the line after this.jobs=jobs
 `  ionViewWillEnter() {
    this.jobService.getJobs()
      .then(jobs => {
        this.jobs = jobs
      });
  }`

**Comment by timlitw** [comment]
Thank you! I think I tried adding .job everywhere but there.
