### ISSUE TITLE
2 steps relations?

### ISSUE THREAD

**Issue by henninghall** [mevdschee/php-crud-api#21]
I am trying to attach relation data which works great except when it is "relations relation". In the example it should be possible to use mysql_crud_api_tranform() to achieve this. 

I want to achieve this: 

`{
    "posts": [
        {
            "id": "1",
            "post_tags": [
                {
                    "id": "1",
                    "post_id": "1",
                    "tag_id": "1",
                    "tags": [
                        {
                            "id": "1",
                            "name": "funny"
                        }
                    ]
                },
                {
                    "id": "2",
                    "post_id": "1",
                    "tag_id": "2",
                    "tags": [
                        {
                            "id": "2",
                            "name": "important"
                        }
                    ]
                }
            ],
            "comments": [
                {
                    "id": "1",
                    "post_id": "1",
                    "message": "great"
                },
                {
                    "id": "2",
                    "post_id": "1",
                    "message": "fantastic"
                }
            ],
            "user_id": "1",
            "category_id": "1",
            "categories": [
                {
                    "id": "1",
                    "name": "anouncement"
                }
            ],
            "content": "blog started"
        }
    ]
}`

But the result is : 

`{
    "posts": [
        {
            "id": "1",
            "post_tags": [
                {
                    "id": "1",
                    "post_id": "1",
                    "tag_id": "1",
                },
                {
                    "id": "2",
                    "post_id": "1",
                    "tag_id": "2",
                    "tags": [
                        {
                            "id": "2",
                            "name": "important"
                        }
                    ]
                }
            ],
            "comments": [
                {
                    "id": "1",
                    "post_id": "1",
                    "message": "great"
                },
                {
                    "id": "2",
                    "post_id": "1",
                    "message": "fantastic"
                }
            ],
            "user_id": "1",
            "category_id": "1",
            "categories": [
                {
                    "id": "1",
                    "name": "anouncement"
                }
            ],
            "content": "blog started"
        }
    ]
    "tags": [
                        {
                            "id": "1",
                            "name": "funny"
                        }
                    ]
}`

Do you know why or how i can fix this? If anyone is achieving the expected result, please provide an example of how you use mysql_crud_api_tranform(). Thanks for a great api!

**Comment by mevdschee** [comment]
Is that really the result? That is worrying as it is not even valid JSON. Can you confirm this?

**Comment by Disane87** [comment]
Yep I have the same issue. I have a db as this model:
![bildschirmfoto 2016-02-09 um 12 19 41](https://cloud.githubusercontent.com/assets/956158/12914902/715388b6-cf27-11e5-89e8-3bbcbe59b7f1.png)

If I want to read one row of "RezeptMischungen", I have this structure by your api:
`{
    "RezepteMischungen": [
        {
            "ID": "1",
            "Rezept_ID": "1",
            "Aroma_ID": "1"
        }
    ],
    "rezeptemischungen": [
        {
            "ID": "1",
            "Rezept_ID": "1",
            "Rezepte": [
                {
                    "ID": "1",
                    "Name": "Erdbeer",
                    "Datum": "2016-02-09 12:00:42",
                    "User_ID": "1",
                    "Base_ID": "1",
                    "Bewertung_ID": "2",
                    "Reifezeit": "7"
                }
            ],
            "Aroma_ID": "1",
            "Aromen": [
                {
                    "ID": "1",
                    "Name": "Erdbeer",
                    "Datum": "2016-02-09 12:01:29",
                    "Hersteller_ID": "1",
                    "Bewertung_ID": "1"
                }
            ]
        }
    ],
    "Basen": [
        {
            "ID": "1",
            "Name": "VPG",
            "Datum": "2016-02-09 11:43:19",
            "Hersteller_ID": "1",
            "Bewertung_ID": "2"
        },
        {
            "ID": "2",
            "Name": "Traditional",
            "Datum": "2016-02-09 12:14:20",
            "Hersteller_ID": "1",
            "Bewertung_ID": "1"
        }
    ]
}`

My call of your api:
`api.php/RezepteMischungen,Aromen,Rezepte,Basen?filter=rezept_id,eq1&callback=callback`

Which is generally ok, but the table "Rezepte" has a relation to "Basen" which isn't applicated.
I hope you know what I mean. If not, feel free to ask me anything.

**Comment by mevdschee** [comment]
Thank you very much! I will look into this and report back after reproducing your findings.

**Comment by mevdschee** [comment]
Does this help?

**Comment by Disane87** [comment]
I really don't know why. Could be a collation problem I guess. I will cross check that and your solution tomorrow. Thanks for you effort! :)

**Comment by mevdschee** [comment]
Okay, much appreciated. You are probably running MySQL on Windows, right?

**Comment by Disane87** [comment]
Oh no. Im running mysql within XAMPP under OSX El Capitan. I can check that with my external Apache with MySQL. But I created that DB with Navicat not PHPmyadmin.

**Comment by mevdschee** [comment]
Thank you for your cooperation on this second bug.

Please post the returned JSON on your machine and please also post the output of:

```
SELECT 1 as `N`,`TABLE_NAME` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` LIKE 'RezepteMischungen' UNION
SELECT 2,`TABLE_NAME` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` = 'RezepteMischungen' UNION
SELECT 3,`TABLE_NAME` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` COLLATE 'utf8_bin' LIKE 'RezepteMischungen'  UNION
SELECT 4,`TABLE_NAME` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` LIKE 'rezeptemischungen';
```

because:

> Suppose that a query searches the SCHEMATA.SCHEMA_NAME column for the test database. On Linux, file systems are case sensitive, so comparisons of SCHEMATA.SCHEMA_NAME with 'test' match, but comparisons with 'TEST' do not: 
> ...
> On Windows or OS X where file systems are not case sensitive, comparisons match both 'test' and 'TEST': 

see: https://dev.mysql.com/doc/refman/5.1/en/charset-collation-information-schema.html

Your help is very valuable!

**Comment by henninghall** [comment]
Sorry my example wasn't the exact result. @Disane87 explains the same issue perfectly. I am using MySQL with XAMPP on Windows.

**Comment by mevdschee** [comment]
@henninghall You can update your "api.php" with the latest version as I applied a fix. Please let me know whether or not it works for you (it should).

**Comment by henninghall** [comment]
@mevdschee It works brilliantly! Thanks a lot for keeping this api so great!

**Comment by mevdschee** [comment]
@Disane87 Can you still help me to identify the other bug (with the casing) by sending the returned JSON and executing the SQL queries on your machine?

**Comment by Disane87** [comment]
My result of your script:
```
N	TABLE_NAME
1	RezepteMischungen
2	rezeptemischungen
3	RezepteMischungen
4	RezepteMischungen
```

Returned JSON with your updated api.php:

```
{
    "RezepteMischungen": [
        {
            "ID": "1",
            "Rezept_ID": "1",
            "Rezepte": [
                {
                    "ID": "1",
                    "Name": "Erdbeer",
                    "Datum": "2016-02-09 12:00:42",
                    "User_ID": "1",
                    "Base_ID": "1",
                    "Bewertung_ID": "2",
                    "Reifezeit": "7"
                }
            ],
            "Aroma_ID": "1"
        }
    ],
    "rezepte": [
        {
            "ID": "1",
            "Name": "Erdbeer",
            "Datum": "2016-02-09 12:00:42",
            "User_ID": "1",
            "Base_ID": "1",
            "Basen": [
                {
                    "ID": "1",
                    "Name": "VPG",
                    "Datum": "2016-02-09 11:43:19",
                    "Hersteller_ID": "1",
                    "Bewertung_ID": "2"
                }
            ],
            "Bewertung_ID": "2",
            "Reifezeit": "7"
        }
    ],
    "rezeptemischungen": [
        {
            "ID": "1",
            "Rezept_ID": "1",
            "Aroma_ID": "1",
            "Aromen": [
                {
                    "ID": "1",
                    "Name": "Erdbeer",
                    "Datum": "2016-02-09 12:01:29",
                    "Hersteller_ID": "1",
                    "Bewertung_ID": "1"
                }
            ]
        }
    ]
} 
```

**Comment by mevdschee** [comment]
Ah.. thank you very much! Very unexpected to me!

```
SELECT `TABLE_NAME` FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` COLLATE 'utf8_bin' = 'RezepteMischungen';
```
Can you post the output of this SQL query as well?

**Comment by Disane87** [comment]
Sure :)

```
TABLE_NAME
RezepteMischungen
```

**Comment by mevdschee** [comment]
Thank you, I will prepare a new version tonight that should fix the bug.

**Comment by Disane87** [comment]
Thank you! :) 
I will use your API for a bigger project, so I guess we'll stay in contact. But very great work! Really appreciate it!

**Comment by mevdschee** [comment]
The case sensitivity issue should also be fixed now. See: 7bd9919591ea49e4a3afe0781d962bb34d5aa8a3

**Comment by Disane87** [comment]
Thanks, works now!
