### ISSUE TITLE
Unsure why code is not working?

### ISSUE THREAD

**Issue by thadocta** [mevdschee/php-crud-api#211]
Hi

I am using this API successfully for a number of uses.  One of them I cannot get to work using curl in PHP.  I'm not a software engineer by training and do this part time as a hobby.  Below is a description of the problem.  Any pointers would be greatly appreciated!

From the command line the following works perfectly:

$ curl -H "Content-Type: application/json" -X POST -d '{"claim_number":"12345","policy_number":"98765"}' http://localhost:8888/api_claim.php/claim

Using Postman I also successfully add to the database.

When I use a basic html form to trigger the code below (code modified from that generated by Postman for me):

```php
<?php

$member_name = $_POST['member_name'];
$member_surname=$_POST['member_surname'];
$policy_number=$_POST['policy_number'];
$claim_number=$_POST['claim_number'];
$date_entered=$_POST['date_entered'];
$client_id=$_POST['client_id'];

$curl = curl_init();

curl_setopt_array($curl, array(
    CURLOPT_PORT => "8888",
    CURLOPT_URL => "http://localhost:8888/api_claim.php/claim",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
//    CURLOPT_POSTFIELDS => "{\"policy_number\":\"12345\",\"icd10\":\"J45.1\",\"date_entered\":null}",
    CURLOPT_POSTFIELDS => "{\"policy_number\":$policy_number,\"member_name\":$member_name,\"date_entered\":$date_entered,\"member_surname\":$member_surname,\"claim_number\":$claim_number,\"client_id\":$client_id}",
    CURLOPT_HTTPHEADER => array(
        "cache-control: no-cache",
        "content-type: application/json"
    ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);
//echo $policy_number;

if ($err) {
    echo "cURL Error #:" . $err;
} else {
    echo $response;
}
```

I get the following response:

"Not found (input)"

**Comment by mevdschee** [comment]
Do you submit using ajax? Can you post the form tags you use?

**Comment by mevdschee** [comment]
Try this:

```php
CURLOPT_POSTFIELDS => json_encode($_POST),
```

I think that helps.

**Comment by thadocta** [comment]
That worked 100% - thank you!  And it has made my life much easier into the future (and my code much tidier) :)

**Comment by mevdschee** [comment]
See: https://github.com/mevdschee/php-crud-api/blob/master/examples/client.php
