### ISSUE TITLE
Make 404 response valid JSON

### ISSUE THREAD

**Issue by grandgeorg** [mevdschee/php-crud-api#214]
Hi,

may I suggest to alter the exitWith404 function to be something like:

```
protected function exitWith404($type) {
    if (isset($_SERVER['REQUEST_METHOD'])) {
        header('Content-Type: application/json; charset=utf-8', true, 404);
        die('{
            "errors": [
            {
                "status": 404,
                "code": "not-found",
                "title": "Resource Not Found",
                "detail": "This ' . $type . ' is not available on this server."
            }
            ]
        }');
    } else {
        throw new \Exception("Not found ($type)");
    }
}
```
otherwise API would drop out of JSON, which could be a bad idea.

**Comment by jr3cermak** [comment]
Issue #14 is related.

Response definitions: http://swagger.io/specification/#responses-object-example-57
Example error model with composition: http://swagger.io/specification/#models-with-composition-90

By having an error template, we can tighten up the json currently being generated.

The one error that needs to be defined on the server side is 500.   If your PHP code throws a server error, it won't be PHP that generates the json.   On some systems where you cannot control the response from the server, clients will still have to check the 500 error code returned from the server.

**Comment by mevdschee** [comment]
>otherwise API would drop out of JSON, which could be a bad idea.

As @jr3cermak explains you can't prevent that. Also I wonder why you want to parse the error when you can simply look at the status code (not 200). Even if you could parse the error I don't understand what it is that you would want to do with that error.

**Comment by jr3cermak** [comment]
```
                echo '"consumes":["application/json"],';
                echo '"produces":["application/json"],';
```

At this point and time, the /produces path states that the (api) server only emits application/json.   I can see your point that the only responses that are defined are 200 and they always emit application/json.   But, we do emit text responses for non-200 errors, fuzzy area...

**Comment by grandgeorg** [comment]
From a simple practical point of view there are also some use cases e.g.

On one hand an API client can call a wrong URL for the API (e.g. one without hitting api.php at all, because of renaming files and paths), so a HTTP server will emit a 404 on its own obviously without JSON response.

On the other hand one could have e.g. defined a ```record_filter``` in the API for a table where only records with a state of ‘published’ should be displayed. As this data within the DB may change over time, an API call for a specific data set could then also emit a 404. For that case it would be good to have a JSON response, so that the client could figure out, that the call (i.e. the URL) was valid but just the requested data (an object of a table row) is not available for the time being.

(Also then one could start to think of solutions for read multiple objects calls where some objects are available and some not. At this time calling multiple objects with one being not available results in a 404 for the complete request.)

**Comment by bubach** [comment]
You can handle any error with PHP, see https://stackoverflow.com/a/8851820

**Comment by grandgeorg** [comment]
@bubach sure, so what?

**Comment by bubach** [comment]
sorry if i missunderstood, looked like jr3cermak & mevdschee talked about not being able to handle 500 for example.

**Comment by grandgeorg** [comment]
That could be true if something else is causing the 500 e.g. a misconfigured .htacess file. Then the server will stop processing the request before hitting any php.

**Comment by mevdschee** [comment]
In v2 this is fixed. What do you think about it?
