### ISSUE TITLE
Update Image using "put" method type not working

### ISSUE THREAD

**Issue by ckatarpawar** [mevdschee/php-crud-api#215]
Hi,
I use this plugin to do CRUD operation from my HTML pages. While working with I got stuck in 1 place where I need to update the image. so as per documentation of plugin I submit my form with "put" as method type, updated image file, and other form data. But my request is not processed, I got a response as null. when I check in database it shows me old image file. I tested this with HTML page and REST client extension of google chrome, but found same response.

Any help in above issue will be very thankful.

please find below request which I am using
URL: localhost/my-app/api.php/catalogue_tbl/1
Parameters:
catalogue_name:fff
catalogue_for:xxx
cover_image: jellyfish.png (new image file)

please find attached image of "PUT" REST request.

`<form enctype="multipart/form-data" action="/my-ap/api.php/catalogue_tbl/1" method="post">`
`<div class="box-body">`
`<div class="row">`
`<div class="form-group col-md-12">`
`<label for="exampleInputEmail1" class="required">Catalogue Name</label>`
`<input type="text" class="form-control" name="catlogue_name" placeholder="Enter catalogue name" />`
`<input type="hidden" id="catalogueId" />`
`</div>`
`</div>`
`<div class="row">`
`<div class="form-group col-md-12">`
`<label for="exampleInputPassword1" class="required">Catalogue For</label>`
`<select class="form-control" name="catogue_for" required>`
`<option value="cricket" selected="selected">CRICKET</option>`
`<option value="fashion">FASHION</option>`
`</select>`
`</div>`
`</div>`
`<div class="row">`
`<div class="form-group col-md-4">`
`<label for="exampleInputFile">Catalogue Cover Image</label>`
`<input type="file" name="cover_image" class="updt-catalogue-cover-img">`											  
`</div>`
`</div>`
`<div class="row">`
`<div class="form-group col-md-12">`
`<llabel for="exampleInputFile">Preview</label>`
`<p><img class="updatecataloguepreviewimg" src="dist/img/no-pattern.png" alt="preview" class="preview" style="width:360px; height:240px;" /></p>`
`</div>`
`</div>`
`</div>`
`<div class="box-footer">`
`<button type="submit" class="btn btn-primary">Submit</button>`
`</div>`
`</form>`

![put - restlet client](https://cloud.githubusercontent.com/assets/12656304/24073093/a708ac10-0c17-11e7-9221-2c306ebb72e5.png)

**Comment by mevdschee** [comment]
File upload and PUT requests don't mix, for a workaround see #67

**Comment by ckatarpawar** [comment]
Thank you for your help. issue is fixed with the solution mentioned in ticket #67.
