### ISSUE TITLE
execute a stored procedure

### ISSUE THREAD

**Issue by alexiskhoury** [mevdschee/php-crud-api#22]
Hi,

First thanks for this useful api. I have 2 requests if possible:

1- Sqlite connectivity, I think this was requested by one of the users
2- Is it possible to execute a stored procedure on the database and get the result in json?

I understand that your api can do simple crud operation like selecting and filtering records, but in my queries am using sql functions like sum(), count(), etc. The aim of my second request is to have all this logic stored into a procedure on server side and use your REST api to call and retrieve the results.

Regards;
Alexis

**Comment by mevdschee** [comment]
Thank you for your request, both requests are both valid and doable. I was also thinking about how to reflect stored procedures, but I haven't completely figured it out. I also think that if I will add it, this have to be done in another (unrelated) project.

**Comment by alexiskhoury** [comment]
Hi,

This will be a great feature. the procedure could be called by something similar to:

GET http://localhost/api.php/procedure_name?param1=x&param2=y

Is this feasible?

Regards;
A.

**Comment by mevdschee** [comment]
Not production ready yet... but one should "release early" right?

Enjoy: https://github.com/mevdschee/php-sp-api
