### ISSUE TITLE
All requests returning the Swagger API specs

### ISSUE THREAD

**Issue by guillochon** [mevdschee/php-crud-api#221]
Hi,

Installed the API and attached a read-only MySQL user. While the main API page (http://voxcharta.org/api.php) loads the Swagger API, no request for a specific table actually returns anything different, the Swagger API is returned every single time. Any idea what might be going on or how I could debug the issue?

**Comment by guillochon** [comment]
Figured it out: PATH_INFO was not enabled in my nginx configuration, now that it's enabled things work great.

**Comment by jayhawkins** [comment]
guillochon, how did you enable it in nginx?

**Comment by mevdschee** [comment]
See: https://github.com/mevdschee/php-crud-api#nginx-config-example

Pay special attention to the "fastcgi_split_path_info" directive.

**Comment by jayhawkins** [comment]
Still not working. I can get it to work if I set PATH_INFO to request_uri and then parse out the 'api/' in my script, but obviously not a great work-around.

Here is my conf file setup:

location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
                #try_files $uri $uri/ /index.php?$query_string;
        }

location ~ [^/]\.php(/|$) {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                try_files $fastcgi_script_name =404;
                set $path_info $fastcgi_path_info;
                fastcgi_param PATH_INFO $path_info;
                fastcgi_index index.php;
                include fastcgi.conf;
                fastcgi_pass 127.0.0.1:9000;
        }

        location /api {
                rewrite ^/api(.*)$ /api.php?$1 last;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        location ~ /\.ht {
                deny all;
        }

**Comment by mevdschee** [comment]
What OS are you running and what is in "fastcgi.conf" that you include?
