### ISSUE TITLE
DELETE Request with filter not working

### ISSUE THREAD

**Issue by thimma11** [mevdschee/php-crud-api#222]
I'm trying to make a Delete-Request with filters to my server but it's not working. Deleting Rows by Primary Key works fine though.

Request:
http://localhost/dev/api.php/user_group?filter[]=group_id,eq,35&filter[]=user_id,eq,1&satisfy=all

The table user_group has two columns (user_id and group_id).

I also tested the request with a Rest-Client in VS-Code and got the following response:
The requested method DELETE is not allowed for the URL /dev/api_new/user_group.

I hope you can help me :)

**Comment by mevdschee** [comment]
Hi thank you for creating this issue. Unfortunaltely delete on the list end-point is not supported. You can do a multi-delete (batch), but you will have to specify all primary-keys in the url. This is for preventing accidental clearing of the database.

**Comment by thimma11** [comment]
@mevdschee Thanks but how would such a multi-delete look like? Never heard of it.

**Comment by mevdschee** [comment]
see: https://github.com/mevdschee/php-crud-api#delete-multiple

**Comment by thimma11** [comment]
@mevdschee is there a way to specify composite primary keys in the delete request? Because that's what i need to do xD

**Comment by mevdschee** [comment]
I'm sorry, but as the readme states:

https://github.com/mevdschee/php-crud-api/blob/master/README.md#limitations

composite keys are not supported.

**Comment by 27maximilian** [comment]
> 
> 
> see: https://github.com/mevdschee/php-crud-api#delete-multiple

Hi,
was this section moved? I can't find it under the link.

I am looking for a good way to remove multiple entries in a mapping table (as an alternative to delete with filter).

**Comment by mevdschee** [comment]
> was this section moved? I can't find it under the link.

No, it was removed. The software in 2017 (v1 early stage) is not comparable to the software now.

>I am looking for a good way to remove multiple entries in a mapping table (as an alternative to delete with filter).

You can remove the entries by using a batch operation by primary keys, after doing a list with filter.

**Comment by mevdschee** [comment]
As for an example, the following request:

    DELETE /api.php/records/posts/1,2,3

Would remove posts with id 1,2 and 3.

**Comment by 27maximilian** [comment]
Ok, perfect.

Thank you!
