### ISSUE TITLE
Help using filters 

### ISSUE THREAD

**Issue by Kavan72** [mevdschee/php-crud-api#223]
Watch this example "https://github.com/typicode/json-server"
on this that project run on node.js and your project run on php but on your project complex filters not working pls add on this project

**Comment by mevdschee** [comment]
Thank you for creating an issue. Have you read about filter support in the README?

see: https://github.com/mevdschee/php-crud-api#list--filter

What is it that you want to do that is not supported?

**Comment by Kavan72** [comment]
Watch this http://localhost/2/api.php/bollywood?filter=cat,eq,bollywood&?page=1,1
That not work on this api but on  this "https://github.com/typicode/json-server" example that work like that
http://localhost:3000/movies?title=Bollywood?_page=1&_limit=5
OK Sir First thank you for your response. i think you use slim framwork for convert mysql to json and after work complex filter

**Comment by mevdschee** [comment]
What you are trying seems possible to me. Instead of:

    http://localhost/2/api.php/bollywood?filter=cat,eq,bollywood&?page=1,1

Try:

    http://localhost/2/api.php/movies?filter=cat,eq,bollywood&page=1,5

That should help.

**Comment by Kavan72** [comment]
Sir Not works all of this

**Comment by mevdschee** [comment]
Without detailed and constructive feedback I can't help you
