### ISSUE TITLE
Running the tests on multiple databases in one run

### ISSUE THREAD

**Issue by karllhughes** [mevdschee/php-crud-api#225]
What do you think about refactoring the tests so that we can run them across multiple databases in one run?

I'm thinking we loop through all the configurations and repeat the test suite for each? I may have to play around with the code to try it out, but I wanted to run it by @mevdschee just to make sure you think it's worthwhile.

I think it would help make testing easier.

**Comment by mevdschee** [comment]
Yes, good improvement!

**Comment by mevdschee** [comment]
Thank you @karllhughes, great contribution!

**Comment by karllhughes** [comment]
Thank you for putting this together, and I'm happy to help.
