### ISSUE TITLE
Adding travis-ci to automatically run tests

### ISSUE THREAD

**Issue by karllhughes** [mevdschee/php-crud-api#226]
After accidentally discovering some failing tests (hence [this PR](https://github.com/mevdschee/php-crud-api/pull/224)) I think adding [Travis CI](https://travis-ci.org/) to this project would help ensure that tests are passing at all times.

It's free, and it will tell us that tests are passing without us having to pull down the code and run it locally.

I'm happy to do the grunt work of getting it set up, just wanted to run it by you @mevdschee. Thanks!

**Comment by mevdschee** [comment]
I would love this!
