### ISSUE TITLE
Java class

### ISSUE THREAD

**Issue by reubenwalkerau** [mevdschee/php-crud-api#231]
Just checking, has anyone written a java class to connect to this API via asyncTask?

**Comment by mevdschee** [comment]
No, not that I am aware of.

**Comment by Kavan72** [comment]
Yes it's working with asyncTask, and also for retrofit2 lib

**Comment by mevdschee** [comment]
@Kavan72 please share a link to your code.

**Comment by Kavan72** [comment]
AsyncTask<Integer,Void,Void> task = new AsyncTask<Integer, Void, Void>() {
            @Override
            protected Void doInBackground(Integer... integers) {

                OkHttpClient client = new OkHttpClient();
                Request request = new Request.Builder()
                        .url("http://localhost/2/api.php/bollywood?order=id&page=1,2&filter=cat,eq,bollywood&transform=1")
                        .build();
                try {
                    Response response = client.newCall(request).execute();

                    JSONArray jsonArray =  new  JSONArray(response.body().string());

                    if(jsonArray.length()==0){
                        Handler h = new Handler(Looper.getMainLooper());
                        h.post(new Runnable() {
                            public void run() {
                                Toast.makeText(getApplicationContext(), "No More Movies Available", Toast.LENGTH_LONG).show();
                            }
                        });
                    }else {
                        for (int j = 0; j < jsonArray.length(); j++) {
                            JSONObject obj1 = jsonArray.getJSONObject(j);
                            SingleItemModel Si = new SingleItemModel(obj1.getString("Title")
                                    ,obj1.getString("Year")
                                    ,obj1.getString("Released")
                                    ,obj1.getString("Runtime")
                                    ,obj1.getString("Genre")
                                    ,obj1.getString("Director")
                                    ,obj1.getString("Actors")
                                    ,obj1.getString("Plot")
                                    ,obj1.getString("Poster")
                                    ,obj1.getString("imdbRating")
                                    ,obj1.getString("imdbVotes"));
                            SingleItemModels.add(Si);
                        }
                    }

                }  catch (JSONException e) {
                    e.printStackTrace();

                }  catch (IOException e) {
                    System.out.println("No More Data");

                }
                return null;
            }

            @Override
            protected void onPostExecute(Void aVoid) {
                adapter.notifyDataSetChanged();
            }
        };

**Comment by Kavan72** [comment]
AsyncTask<Integer,Void,Void> task = new AsyncTask<Integer, Void, Void>() {
            protected Void doInBackground(Integer... integers) {

                OkHttpClient client = new OkHttpClient();
                Request request = new Request.Builder()
                        .url("http://localhost/2/api.php/bollywood?order=id&page=1,2&filter=cat,eq,bollywood&transform=1")
                        .build();
                try {
                    Response response = client.newCall(request).execute();

                    JSONArray jsonArray =  new  JSONArray(response.body().string());

                    if(jsonArray.length()==0){
                        Handler h = new Handler(Looper.getMainLooper());
                        h.post(new Runnable() {
                            public void run() {
                                Toast.makeText(getApplicationContext(), "No More Movies Available", Toast.LENGTH_LONG).show();
                            }
                        });
                    }else {
                        for (int j = 0; j < jsonArray.length(); j++) {
                            JSONObject obj1 = jsonArray.getJSONObject(j);
                            SingleItemModel Si = new SingleItemModel(obj1.getString("Title")
                                    ,obj1.getString("Year")
                                    ,obj1.getString("Released")
                                    ,obj1.getString("Runtime")
                                    ,obj1.getString("Genre")
                                    ,obj1.getString("Director")
                                    ,obj1.getString("Actors")
                                    ,obj1.getString("Plot")
                                    ,obj1.getString("Poster")
                                    ,obj1.getString("imdbRating")
                                    ,obj1.getString("imdbVotes"));
                            SingleItemModels.add(Si);
                        }
                    }

                }  catch (JSONException e) {
                    e.printStackTrace();

                }  catch (IOException e) {
                    System.out.println("No More Data");

                }
                return null;
            }

            @Override
            protected void onPostExecute(Void aVoid) {
                adapter.notifyDataSetChanged();
            }
        };
