### ISSUE TITLE
How to obtain rows from A table searching in an included B table?

### ISSUE THREAD

**Issue by Denis-Evseev** [mevdschee/php-crud-api#232]
Hi mevdschee,
Thank you for your effort and constant improving the soft!

Let me just describe relations in my tables and what I want to reach:
I have 2 tables:
1) Unis (columns: id, name)
2) Specs (columns: id, uid, groupName, name)
All rows in Specs table have connections to Unis table. 

I need to find all Unis rows, which contain filtered rows from Specs;
I'm trying: 
> api.php/vuzes?include=specs&filter[]=GroupName,cs,Сервис%20и%20туризм&transform=1

It, unfortunately, doesn't work;

Whereas this request works:
> api.php/specs?filter[]=GroupName,cs,Сервис%20и%20туризм&transform=1%27

Do you have any ideas?

Many thanks in advance!

**Comment by mevdschee** [comment]
Simplest is to do 2 queries: one to get the id's of the Specs and then one to query the Unis that have those Specs.

**Comment by mevdschee** [comment]
@Denis-Evseev did my suggestions help you? Do you have follow-up questions?

**Comment by mevdschee** [comment]
http://chalkdesk.ru/ajax/api/index.php/specs?filter[]=GroupName,eq,%D0%A1%D0%B5%D1%80%D0%B2%D0%B8%D1%81%20%D0%B8%20%D1%82%D1%83%D1%80%D0%B8%D0%B7%D0%BC&columns=vuzes.*&include=vuzes

**Comment by Denis-Evseev** [comment]
Not quite what I wanted. I wanted something like this 

`http://chalkdesk.ru/ajax/api/index.php/vuzes/fv7GhFf,umZcMsr ...` 
+  filter[]=Adress,cs,Москва

or you request 
http://chalkdesk.ru/ajax/api/index.php/specs?filter[]=GroupName,eq,Сервис%20и%20туризм&columns=vuzes.*&include=vuzes
+  filter[]=Adress,cs,Москва

Your requests + filter seems to work but it doesn't filter Address 

I also have some troubles with auth... emailed you yesterday

**Comment by mevdschee** [comment]
>Not quite what I wanted

Why not? Where did the address filter requirement suddenly come from? I guess this is what you want:

http://chalkdesk.ru/ajax/api/index.php/specs?filter[]=GroupName,eq,Сервис%20и%20туризм&columns=vuzes.*&include=vuzes&filter[]=vuzes.Adress,cs,Москва

>I also have some troubles with auth... emailed you yesterday

Thank you for your email. I replied.

**Comment by Denis-Evseev** [comment]
Wow this is the tricky trick 👍 . I had to add `vuzes.` I didn't know about it.
I'm very very grateful to you that you constantly provide support. 

Can you please erase domain name for security reasons?

**Comment by mevdschee** [comment]
> I'm very very grateful to you that you constantly provide support.

You are welcome. Glad I could help.

> Can you please erase domain name for security reasons?

Done
