### ISSUE TITLE
How to add Authentication on delete,put and post but not on get ?

### ISSUE THREAD

**Issue by Kavan72** [mevdschee/php-crud-api#234]
only admin can delete,put and post request how to do that ?
normal user not delete ,put or post 

how to do that ?

**Comment by mevdschee** [comment]
You have to implement this in the 'table_authorizer' callback. There you should return true for admins for those commands and false for normal users.

**Comment by Kavan72** [comment]
Sorry i don't understand  
Any example

**Comment by mevdschee** [comment]
Make your users authenticate using the https://github.com/mevdschee/php-api-auth project and then differentiate between normal users (that login with a common username/password) and admins (that login with their own username/password. For normal users you can use a user "user" with password "pass" and then in the callback return false when the $_SESSION['user'] is set to the normal user.

Check for instance #177

**Comment by Gialdeb** [comment]
Hi I have generated the token and set my cookies, but if I try to invare postman with a request I always returns not authorized, what can I do to riolvere? Thank you for a possible answer

**Comment by mevdschee** [comment]
@Gialdeb Can you share the script you try? Did you look at the examples? Especially this one:

**Comment by Gialdeb** [comment]
Thanks for your reply as soon as I try and let you know, thanks anyway for the great code :-)

**Comment by Gialdeb** [comment]
Thanks I was able to manage the token header I was wrong because I passed only XSRF-TOKEN :-). One last thing you can not set the token without having to pass the username and password to api.php?
Thank you for a possible answer.

**Comment by mevdschee** [comment]
>you can not set the token without having to pass the username and password to api.php?

You can, but then you have to send a JWT. And to acquire the JWT you have to pass username and password. The advantage is that the JWT maybe issued by another server on another domain.

**Comment by Gialdeb** [comment]
@mevdschee thanks for your support, I have another problem. I can delete, read and create the DB, but I can not update the row using the PUT method, it will return "404 Not Found"

**Comment by mevdschee** [comment]
Many people have this problem. It is most likely due to your hosting environment, not allowing those verbs. Can you share some more details?

**Comment by Gialdeb** [comment]
@mevdschee local work on the problem and I use server.

I use the Apache PHP module on ISS 8

This is what comes back to me from the request using postman:

X-XSRF-Token: ..........
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 9ec65b84-b2f9-46b1-5b74-00d5eab32365
Status: 404

**Comment by Kavan72** [comment]
I am making android app with this api project.When first time open android app then generate token and that token to access this api . how to do that on this project ?

**Comment by Kavan72** [comment]
On this project on click login_token.php ok button the token pass on api/ body part but i need the pressed ok then open api/csrf='token' how to do that

**Comment by mevdschee** [comment]
@Gialdeb I think it has to do with verbs, see the following tickets:

- https://forums.iis.net/t/1166025.aspx
- http://stackoverflow.com/questions/6739124/iis-7-5-enable-put-and-delete-for-restful-service-extensionless

Please read them and enable those verbs and disable webdav if it is enabled.
