### ISSUE TITLE
Support for MySQL 5.6 or JSON support?

### ISSUE THREAD

**Issue by karllhughes** [mevdschee/php-crud-api#236]
Currently our MySQL test suite uses a `JSON` column type. Support for this column type only [appeared in MySQL 5.7](https://dev.mysql.com/doc/refman/5.7/en/json.html), so users of MySQL 5.6 will not be able to run our test suite (or use JSON columns effectively).

I see three options to address this issue:

1. Remove the JSON support for MySQL. This means we'll have to drop that column type from the tests and alert users in the Docs that JSON isn't supported for MySQL
2. Explicitly require MySQL 5.7+, which will allow us to support JSON column types
3. Offer a "hybrid" approach where users of MySQL 5.7+ would be able to use JSON columns, but users of older versions would not. We would need to update the test and seeder to run selectively based on the version of MySQL being used.

What do you think @mevdschee? Option 2 is the easiest for us as devs, but it offers the least flexibility to users who might be stuck with older versions of MySQL.

**Comment by mevdschee** [comment]
I actually want to support even older versions of MySQL, as most people also don't use the Spatial features of 5.6 either. We should adjust the tests in a way that these are optional and feature support is detected based on the version.

**Comment by karllhughes** [comment]
Ok, sounds good.

I'm guessing the same applies to Postgres? I think Postgres 9.4 was the first to support JSON, so older versions won't run the complete test suite either.

You can close this as it's really an extension of https://github.com/mevdschee/php-crud-api/issues/194

Thanks!

**Comment by mevdschee** [comment]
>I'm guessing the same applies to Postgres?

Yes, absolutely.
