### ISSUE TITLE
Travis CI improvements

### ISSUE THREAD

**Issue by karllhughes** [mevdschee/php-crud-api#238]
While we have a [basic Travis CI implementation](https://github.com/mevdschee/php-crud-api/issues/226), there are some ways we could improve it:

- [ ] Add MySQL 5.6 support (see #194)
- [ ] Run tests with multiple versions of Postgres and MySQL
- [ ] Run tests with/without Postgis support
- [ ] Add SQLServer support
- [ ] Add PHP 5.3 support

**Comment by karllhughes** [comment]
I run the tests locally on multiple versions by using Docker, so that might be the best solution for Travis as well: https://docs.travis-ci.com/user/docker/

It doesn't look like they're going to support multiple travis files: https://github.com/travis-ci/travis-ci/issues/3540

**Comment by mevdschee** [comment]
@karllhughes I got MySQL running, but there is a message in the log:

    $ sudo service mysql start
    start: Job failed to start

I don't know why, but this seems wrong to me.

**Comment by karllhughes** [comment]
@mevdschee looking into this now.

**Comment by mevdschee** [comment]
Thank you very much. The Travis CI tests look good now!

**Comment by mevdschee** [comment]
The Travis tests have been superseded by the docker tests that have all of these features.
