### ISSUE TITLE
Auth public Token for GET Method

### ISSUE THREAD

**Issue by Gialdeb** [mevdschee/php-crud-api#240]
I managed to set a token passing through the form usename and password but it's not clear how to handle the front end the only GET requests and have an public token.
I also want to figure out how to stop the reading of some of db tables.
Thanks as always for your support possible.

**Comment by mevdschee** [comment]
Thank you for your request. I think you may have not searched the closed issues yet. Take a look at this one:

#213

I think it will help you.

**Comment by Gialdeb** [comment]
@mevdschee I looked but with little attention, sorry :-). 
My problem, however, and I make log in and back, and I can use the CRUD method, however, I do not understand how to have a token for those who do not make a login.

**Comment by mevdschee** [comment]
@Gialdeb How about hardcoding a public username/password into your application calling the API? Then differentiate permissions based on the username.

**Comment by Gialdeb** [comment]
@mevdschee forgive me, but I did not understand :-( . 
For the front-end I do not have the form where to enter username and password, how do I default to having only a token for reading certain tables?
Thanks as always for your amazing support.

**Comment by mevdschee** [comment]
Check out the auth examples where you see how the username/password is hardcoded:

https://github.com/mevdschee/php-crud-api/tree/master/examples

I'm sure this will get you started.
