### ISSUE TITLE
Download PDF after Add or Edit

### ISSUE THREAD

**Issue by anushaath** [mevdschee/php-crud-api#241]
I'm using Dompdf to convert my invoice to pdf. While testing it, if i just run the php file, the PDF will be automatically downloaded.

Now If I add or edit a bill, it should automatically download the PDF. 
So, in the createObject and updateObject functions, I've made a function call to run the dompdf after including the file. 
The object is created but the PDF is not downloaded.

Any possible reasons?

**Comment by anushaath** [comment]
Is it better to create a download button in front of each record in the UI, instead of going through the api?

**Comment by mevdschee** [comment]
>Is it better to create a download button in front of each record in the UI, instead of going through the api?

I think it is better to make a separate 'invoice_pdf.php' file that does exactly one thing: generate the pdf for a given invoice identifier. You can make that php file use the api, see for an example here:

https://github.com/mevdschee/php-crud-api/blob/master/examples/client.php

Or if you use auth:

https://github.com/mevdschee/php-crud-api/blob/master/examples/client_auth.php

Let me know whether or not you have further questions.

**Comment by anushaath** [comment]
Yes. I'm building a 'invoice_pdf.php' file. If I click on a invoice button for a record, how can I send the 'id' of that record to the invoice_pdf.php? So that I can then use the API to get the info for that id.

**Comment by mevdschee** [comment]
@anushaath sorry, I can't help you with such generic and basic PHP programming questions.

**Comment by mevdschee** [comment]
Thank you for understanding. Feel free to open a new issue, when you run into API specific problems.

**Comment by anushaath** [comment]
Thank you!
