### ISSUE TITLE
Make tests isolated in test suite

### ISSUE THREAD

**Issue by karllhughes** [mevdschee/php-crud-api#242]
While going through #194 I realized that some of our tests rely on previous tests' results to pass. The order of the tests matters.

For example, if you run the `testListProducts` test after the `testAddProducts` test, it will fail.

When we were running just one class for all the tests this was okay, but now I'm extending the base test class for each database provider, so if I overwrite a parent method, PHPUnit runs it first. This ordering issue starts to cause problems as our test suite gets more complicated.

The obvious solution would be to re-seed the database before each test is run. The problem there is that the test suite will take a really long time to run (plus it will need to be refactored).

For now I'm just going to make a semi-hacky workaround to ensure that tests pass, but I think eventually we'll want to address this issue.

**Comment by mevdschee** [comment]
>The order of the tests matters.

Yes it does.

>This ordering issue starts to cause problems as our test suite gets more complicated.

This is true if the different paths in the test suite have different states as result.

>The obvious solution would be to re-seed the database before each test is run.

I agree that fast tests are desirable, so indeed, that may be not the best plan.

**Comment by mevdschee** [comment]
Since #194 is now implemented, I will close this issue.
