### ISSUE TITLE
How to implement rights management

### ISSUE THREAD

**Issue by MastaBaba** [mevdschee/php-crud-api#245]
I want different users to have different access rights. Correct me if I'm wrong, but I think I can achieve this through the use of a combination of the authenticator, table_authorizer and tenancy_function. Or?

In your example on multi-tenancy, the tenancy function has access to $_SESSION['customer_id']. Does this imply that, in form+session based authentication, this session variable is set in the authenticator function?

If so, the authenticator would need to become something like

```
function($user,$pass){ 
  //Access a users table and find the record with the matching $user and $pass
  if ($userExists) {
    //Set rights in $_SESSION, based on the user. For example $_SESSION["permissions"]["somePermission"] = true;
    $_SESSION["user"] = true;
    $_SESSION["userId"] = $theUserIdFromTheUserTable;
  }
  else {
    $_SESSION["permission"]["somePermission"] = false;
    $_SESSION["user"] = false;
  }
}
```

Then, if I have a permission that equates to being able to manipulate all users, the table_authorizer could be something like 
 
```
function($cmd,$db,$tab) {
  if (!$_SESSION["permissions"]["manipulateUsers"]) {
    if ($tab == "users") {
      return false;
    }
  }
  return true;
},
```

Finally, if I have a table with user-submitted data, where I want users to only be able to edit their own data, unless the current user has the right permission, assuming that that table includes a column identifying the user, the tenancy function could be something like 

```
function($cmd,$db,$tab,$col) {
  if ($tab == "tableWithUserSubmittedData") {
    if ($_SESSION["permissions"]["manipulateAllData"]) {
      return null;
    }
    else {
      if ($col == 'userId') {
        return $_SESSION["userId"];
      }
      else {
        return null;
      }
    }
  }
  else {
    return null;
 }
}
```

All of this depends on being able to fill the session with the right permissions and userId. This would happen in the authenticator, I presume. But, how to access the user table in the authenticator, as it seems to me the database is, at that point, not yet available. Or?

**Comment by mevdschee** [comment]
Good question, thank you for asking it.

>I think I can achieve this through the use of a combination of the authenticator, table_authorizer and tenancy_function. Or?

Yes, that is the idea.

> This would happen in the authenticator, I presume.

Yes

> how to access the user table in the authenticator, as it seems to me the database is, at that point, not yet available. Or?

I don't know where and how you store your users, it could be in LDAP or in a users table in some database. There is nothing in this script that will help you with that.

I can imagine that you would like to get a reference to the (already established) database connection in the authenticator. Am I right?

**Comment by MastaBaba** [comment]
Thanks for the quick response.

You are correct; it would be ideal to access the current database from within the Authenticator, assuming I don't have to establish a separate connection.

**Comment by mevdschee** [comment]
>I don't have to establish a separate connection.

Well, you could. Calling `mysqli_connect()` does not even have to start a separate connection as PHP can use connection pooling.

**Comment by MastaBaba** [comment]
Right. Indeed.

I'm now doing something like that, where user creation happens outside of this API. Then, the authenticator checks an external file to confirm the user's credentials when logging in.

Thanks!
