### ISSUE TITLE
laravel integration

### ISSUE THREAD

**Issue by williansmartins** [mevdschee/php-crud-api#246]
Man, I love this project, I'm using around 6 month.
Now I'm trying to integrate with laravel 5, is possible? I try like this: http://laraveldaily.com/how-to-use-external-classes-and-php-files-in-laravel-controller/ but not result yet.

**Comment by williansmartins** [comment]
Got it! using: http://guzzle.readthedocs.io/en/latest/quickstart.html

I dont know if is a safe way, but I can do a request to api.php

I think the api.php is unsafe for others(malicious) requests..., can I have protect it?

**Comment by mevdschee** [comment]
@williansmartins Yes, please add protection. Simplest is to add something like:

    if ($_SERVER['REMOTE_ADDR']!='127.0.0.1') die('not allowed');

as the first line of the script. This will deny any request not coming from the same machine. or:

    if ($_GET['password']!='SomeVeryRandomPassword123') die('not allowed');

This will require you to add '&password=SomeVeryRandomPassword123' to all requests.

You can also do more sophisticated authentication/authorization using [php-api-auth](https://github.com/mevdschee/php-api-auth).

**Comment by williansmartins** [comment]
thanks a lot
