### ISSUE TITLE
change table name with a alias

### ISSUE THREAD

**Issue by dgiaffreda** [mevdschee/php-crud-api#250]
I'm using this interesting plugin but I cannot realize how to create table alias.
Example: I have a table called "pia_0alert" and i'd like to expose to the user just "alert" so it's more intuitive.
I tried with a view built as "SELECT * from pia_0alert"  but the problem id that does not work read command like GET .../alert/1 in order to read just a record.
thanks
best regards
daniele

**Comment by mevdschee** [comment]
Thank you for creating this issue. Currently there is no support for name mapping and also no support for crud operations on views.

You could simply rename the table to whatever name you want to expose or you could live with a less than optimal table name.

If you explain a little more about your needs and constraints we might be able to turn this into a feature request for a name mapping feature as there already is one for crud operations on views, see #29.

**Comment by GrahamCobb** [comment]
If I understand the request correctly, I do this using a rewrite rule in my .htaccess so the "simple" name exposed to the user is replaced with the actual table name before the API is called.

Or did I misunderstand what is being asked?

**Comment by mevdschee** [comment]
Although that will work for most of the requests, the list response will not reflect the new name(s).

**Comment by dgiaffreda** [comment]
Thank you very much for your contribute.
My wish is to create a separated logical o physical layer in order to publish resources (tables) with standard name.
So in this way I could also change database table names without impact API and all system that uses it.

**Comment by mevdschee** [comment]
This indirection (or separation as you call it) does not seem advantageous to a software system to me. It makes fixing bugs harder as you have to look up the mapping before you can find the data in the database.

Nevertheless, I can see how such a system would be beneficial if you have a legacy system that uses prefixes (think in the lines of WordPress and 'wp_posts'). Or when you want to have an API to expose the data of off-the-shelf software (SAP?), where naming may be horrible and not adjustable.

**Comment by YisusCristH4K3r** [comment]
You could go to the function getParameters($settings) and write a switch under 
$table     = $this->parseRequestParameter($request, 'a-zA-Z0-9\-_');
like 
switch ($table) {
	case 'alias':
		$table = 'real_table_name';
		break;
	case 'alias2':
		$table = 'real_table2_name';
		break;
}

**Comment by mevdschee** [comment]
There is a mapper branch that may be merged into the next minor release.
