### ISSUE TITLE
API is printing all JSON output 2 times which breaks it

### ISSUE THREAD

**Issue by jasondavis** [mevdschee/php-crud-api#252]
First of all thanks for the library I am really happy to have discovered it.  I thought it was just some run of the mill PHP JSON API lib at first glance of the title but then I looked at the readme and it really is amazing for its flexability and auto detection and the Swagger API doc generation is amazing!

Then you add the plugins too and its just a great little package!

---

## Issue

On to my issue now.  I installed with Composer to create a new project so I have a `api.php` file with this:

	<?php

	/// PHP-Crud-API - https://github.com/mevdschee/php-crud-api
	/// PHP-API-AUTH - https://github.com/mevdschee/php-api-auth
	/// PHP-CRUD-UI - https://github.com/mevdschee/php-crud-ui

	include './vendor/autoload.php';

	// set user ID for multi-tenancy user below
	$user_id = 1;

	$api = new PHP_CRUD_API(array(
		'dbengine'=>'MySQL',
		'hostname'=>'localhost',
		'username'=>'root',
		'password'=>'',
		'database'=>'bookmark_lists',
		'charset'=>'utf8',
		'before'=>function(&$cmd, &$db, &$tab, &$id, &$in) {
			// soft delete instead of a hard delete
			if ($cmd == 'delete') {
				$cmd = 'update'; // change command to update
				$in = (object)array('deleted' => date('Y-m-d H:i:s', time()));
			}
		},
		'after'=>function($cmd,$db,$tab,$id,$in,$out) {
			/* do something */
		},
		'table_authorizer'=>function($cmd,$db,$tab) {
			return true;
		},
		'column_authorizer'=>function($cmd, $db ,$tab, $col) { 
			return ( ! in_array($col, array('deleted')));
		},
		'record_filter'=>function($cmd,$db,$tab) { 
			return array('deleted,is,null');
		},
		'tenancy_function'=>function($cmd,$db,$tab,$col) { 
			return $col=='customer_id'?$user_id:null;
		},
		'allow_origin'=>'*',
		'auto_include'=>true,
	));
	$api->executeCommand();

---

## MySQL SQL Schema

	--
	-- Database: `bookmark_lists`
	-- Table structure for table `lists`
	--

	CREATE TABLE `lists` (
	  `id` int(20) NOT NULL,
	  `name` varchar(50) DEFAULT NULL,
	  `description` text,
	  `owner_id` int(10) DEFAULT NULL,
	  `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  `modified_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  `sort_order` int(3) NOT NULL DEFAULT '1',
	  `deleted` varchar(100) DEFAULT NULL,
	  `active` int(1) NOT NULL DEFAULT '1'
	) ENGINE=InnoDB DEFAULT CHARSET=latin1;

	INSERT INTO `lists` (`id`, `name`, `description`, `owner_id`, `created_on`, `modified_on`, `sort_order`, `deleted`, `active`) VALUES
	(1, 'Test List 1', 'Test List 1', 1, '2017-05-02 00:00:00', '2017-05-02 00:00:00', 1, NULL, 1),
	(2, 'Test List 2', 'Test List 2', 1, '2017-05-02 00:00:00', '2017-05-02 00:00:00', 1, NULL, 1);

	--
	-- Indexes for table `lists`
	--
	ALTER TABLE `lists`
	  ADD PRIMARY KEY (`id`);

	--
	-- AUTO_INCREMENT for table `lists`
	--
	ALTER TABLE `lists`
	  MODIFY `id` int(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

---

## The API Error

Now when I access the file on my Dev server URL `http://localhost/labs/php_crud_api/api.php` it prints out the JSON data for the Swagger docs.

The problem is that it prints it 2 times.  So when the 2nd one prints it shows warning from PHP that headers already sent and then shows the exact same JSON data again a 2nd time.

My test DB/API has 1 DB and 1 table named `lists`.

So when I access the API URL `http://localhost/labs/php_crud_api/api.php/lists`

It prints the JSON data for the DB table lists:

(NOTICE that it prints the API data here 2 times as well!)

    // http://localhost/labs/php_crud_api/api.php/lists
	{
	    "lists": {
	        "columns": ["id", "name", "description", "owner_id", "created_on", "modified_on", "sort_order", "active"],
	        "records": [
	            [1, "Test List 1", "Test List 1", 1, "2017-05-02 00:00:00", "2017-05-02 00:00:00", 1, 1],
	            [2, "Test List 2", "Test List 2", 1, "2017-05-02 00:00:00", "2017-05-02 00:00:00", 1, 1]
	        ]
	    }
	} {
	    "lists": {
	        "columns": ["id", "name", "description", "owner_id", "created_on", "modified_on", "sort_order", "active"],
	        "records": [
	            [1, "Test List 1", "Test List 1", 1, "2017-05-02 00:00:00", "2017-05-02 00:00:00", 1, 1],
	            [2, "Test List 2", "Test List 2", 1, "2017-05-02 00:00:00", "2017-05-02 00:00:00", 1, 1]
	        ]
	    }
	}

---

## PHP Warning

This is the PHP warning which shows the line numbers from the `api.php` file

    Warning: Cannot modify header information - headers already sent by 
    (output started at E:\Dev_Server\htdocs\labs\php_crud_api\vendor\mevdschee\php-crud-api\api.php:2588)
    in
    E:\Dev_Server\htdocs\labs\php_crud_api\vendor\mevdschee\php-crud-api\api.php on line 2325

---

Any ideas what could be causing this issue?  Ideas on a fix greatly appreciate any help thank you

 I am running on PHP v7 with MySQL on Windows for this dev server test

**Comment by mevdschee** [comment]
Hi.. thank you for your kind words. Could it be that you invoke `$api->executeCommand();` two times?

**Comment by jasondavis** [comment]
Thanks for the reply.  Unfortunately I only have the 1 call to `$api->executeCommand();` and when I disable it I get no output.  I'm not sure what could be causing the double call

**Comment by jasondavis** [comment]
@mevdschee Do you have any other ideas for a source of problem?

I am loading the library with Composer.  I am going to test:

- using the single file without composer
- s different DB table

**Comment by mevdschee** [comment]
I have no idea how you are using the file, but maybe testing without composer will lead you to the source of the problem. Using a different DB table seems unlikely to me to be solving your issue.

**Comment by jasondavis** [comment]
I have an update....

I went ahead and tried the single file version as I was using Composer which install a bunch of other files.  I also created a new test DB for the new single file API test and the result is it worked as it is supposed to which is great!

I then went back to my Composer version and ran it and strange enough the issue seems to have vanished!

I am thinking maybe it was a weird cache issue somewhere with my Dev server software or something but either way everything seems to be correct now =)

Thanks for your help on the matter you can close this issue if you like.

**Comment by mevdschee** [comment]
Thank you for reporting your success!
