### ISSUE TITLE
multiple filters question

### ISSUE THREAD

**Issue by kopsinnovaties** [mevdschee/php-crud-api#258]
first of all: great api!
My question:
i am querying a database table that looks something like:

table: mytable
| id | username | role | address | country |

I want all the address and country of all usernames starting with (sw) 'someting' and having role 'admin'

can this be done?

...../api.php/mytable?columns=address,country?filter[]username,sw,something&filter[]role,eq,admin&satisfy=all

But that doesnt work..

**Comment by mevdschee** [comment]
It seems like you forgot the '=', so like this:

...../api.php/mytable?columns=address,country?filter[]=username,sw,something&filter[]=role,eq,admin&satisfy=all

Does that work?

**Comment by kopsinnovaties** [comment]
Nope...just a typo in my question (too bad)
my full query (the real one):
../api.php/?columns=bonnummer,adres,deelnemer,gereed?filter[]=gereed,eq,NEE&filter[]=deelnemer,sw,Kops&satisfy=all
my databasetable:
cid || bonnummer || adres || plaats || deelnemer || email || gereed || and so on...
it does give resultset but only the ones where "gereed" = "NEE" (the "deelnemer" starts with "Kops" is ignored. It also doesnt just give the columns "bonnummer", "adres", "deelnemer", "gereed", it gives all columns.
Any idea?
Btw thanks alot for the quick response... and again: great api
Regards

**Comment by kopsinnovaties** [comment]
Btw...i use jquery ajax to post to a php (that requires a login header (my own) and the php_crud_api_transform.php) and then makes the GET to the api.
strange thing is...it does give a result..just not the complete (filtered) one

**Comment by mevdschee** [comment]
You can only use one question mark in the URL, the second question mark should be replaced with an ampersand.

**Comment by mevdschee** [comment]
closed due to inactivity
