### ISSUE TITLE
Question about result with Relations

### ISSUE THREAD

**Issue by IOPSL** [mevdschee/php-crud-api#259]
Take book.sql as example.

GET /api.php/posts?include=categories,tags,comments&filter=id,eq,1 gets right output.

GET /api.php/posts?include=categories,tags,comments&filter=id,eq,3 prints all records for the included tables.

However, when there is no post whose id=3, should the output be expected to be empty for all included tables?

**Comment by mevdschee** [comment]
Thank you for reporting this issue. I will look into it ASAP.

**Comment by KAsiri** [comment]
Thank you for the great work, @mevdschee 
I face the same problem
Is there any solution for it?

**Comment by mevdschee** [comment]
Can you test the latest master and see whether or not that fixes it for you?

**Comment by KAsiri** [comment]
Yes it's Solved, Thank you @mevdschee
