### ISSUE TITLE
PUT Method with long MySql column name

### ISSUE THREAD

**Issue by Gottihh** [mevdschee/php-crud-api#260]
Hello,
i need to make an update with put. It seems that the column name can't be longer than 20 chars. Is that possible?

This PHP cURL Request dosen't work:

Don't work:
```
 $aUpdate = array(
            'FORT_EmpfaengerIdSearch'           => $iNumber
        );
```

Work!!!:
```
 $aUpdate = array(
            'FORT_EmpfaengerIdSea'           => $iNumber
        );
```

```
$ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, PREFIX.DOMAIN."/api/api.php/".$sTableName."/".(int)$iPrimaryKey);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
            curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($aUpdate ));
            $output = curl_exec($ch);
```

Any idea what is the Problem with this?

Thanks for your help 
Markus

**Comment by mevdschee** [comment]
For future reference:

>It seems that the column name can't be longer than 20 chars. Is that possible?

No, column name CAN be longer than 20 chars.
