### ISSUE TITLE
Javascript question: working with array output from the API

### ISSUE THREAD

**Issue by thadocta** [mevdschee/php-crud-api#261]
Hi

When I use the following code:

    <script>
        function validateClaimNo() {
            alert ("");
            var x = document.getElementById("claim_number").value;
            var y = "api_claim.php/claim?filter=claim_number%2Ceq%2C";
            var url = y + x;
            var settings = {
                "async": true,
                "crossDomain": true,
                "url": url,
                "method": "GET",
                "headers": {
                    "content-type": "application/json",
                    "cache-control": "no-cache"
                }
            };
            alert (url);
            var z = $.ajax(settings).done(function(response) {
                console.log(response);
                });
    //           var obj = new Array(JSON.parse(z));
                if (z[0][4] == x) {
                    alert("This Claim Number is already in the database, please try another case to enter")
                } else alert(z[0][4]);

        }
    </script>
`
Using jquery-3.2.1.min.js
I get the following error:
Uncaught TypeError: Cannot read property '4' of undefined

When I use this code:

    <script>
        function validateClaimNo() {
            alert ("");
            var x = document.getElementById("claim_number").value;
            var y = "api_claim.php/claim?filter=claim_number%2Ceq%2C";
            var url = y + x;
            var settings = {
                "async": true,
                "crossDomain": true,
                "url": url,
                "method": "GET",
                "headers": {
                    "content-type": "application/json",
                    "cache-control": "no-cache"
                }
            };
            alert (url);
            var z = new Array($.ajax(settings).done(function(response) {
                console.log(response);
                }));
    //            var obj = new Array(JSON.parse(z));
                if (z[0][4] == x) {
                    alert("This Claim Number is already in the database, please try another case to enter")
                } else alert(z[0][4]);

        }
    </script>`

The script runs through to the "else" alert at the end and the alert reads "undefined".

I know this isn't really a question regarding the php-crud-api directly ....

**Comment by Denis-Evseev** [comment]
I think you need to use
` obj[0][4]`
instead of 
` z[0][4]`

Otherwise, what is the purpose of using 
`var obj = new Array(JSON.parse(z));`

**Comment by mycaravam** [comment]
I know its late, but if somebody run across this:
```
function validateClaimNo() {
	var x = 12; // Just a Test Value
	var y = "api_claim.php/claim?transform=1&filter=id%2Ceq%2C";
	var url = y + x;

	$.get( url, function(response) {
			data = $.parseJSON(JSON.stringify(response));
			// This will log the id
			console.log(data.claim[0].id);
		});
}
validateClaimNo();
```
Note: Use JSON Parse and stringify and use the transform option with the api.
