### ISSUE TITLE
How to prevent updating a particular field/column

### ISSUE THREAD

**Issue by MastaBaba** [mevdschee/php-crud-api#263]
I'm not clear on how to prevent particular columns in particular tables from being updated.

Using the input_sanitizer, I can manipulate submitted fields, but I don't see how I can 'cancel' the update of a particular field.

The tenancy function doesn't seem to be the right place to make this happen. Or?

How to prevent particular columns in particular tables from being updated?

**Comment by VyseExhale** [comment]
Using the column_authorizer

example below is used for "canceling" the update of column "bar" in the "foo" table.
```php
   'column_authorizer'=>function($cmd, $db ,$tab, $col) { 
      if ($cmd == 'update' && $tabl == "foo" && $col == "bar") {
         return false;
      }
      return true;
   }
```

**Comment by MastaBaba** [comment]
Thanks a bunch.
