### ISSUE TITLE
Different satisfy with filters

### ISSUE THREAD

**Issue by Denis-Evseev** [mevdschee/php-crud-api#266]
I am trying to create a function which obtaining a city and subway stations will return a list of organisations near these stations in the city.

Something like this: 
http://localhost/api.php/vuzes&filter[]=vuzes.region,eq,London&filter[]=vuzes.metro,cs,Old Street&filter[]=vuzes.metro,cs,Angel

The problem is when I am using 
1) satisfy=all - returns all organisations which have both Old Street and Angel stations
2) satisfy=any - eventually it returns all organisations in London

Whereas I need to return all organisations which have separately Old Street and Angel stations in the city. Obviously, I can invoke 2 requests 
http://localhost/api.php/vuzes&filter[]=vuzes.region,eq,London&filter[]=vuzes.metro,cs,Old Street
http://localhost/api.php/vuzes&filter[]=vuzes.region,eq,London&filter[]=vuzes.metro,cs,Angel

But I have much more complicated requests and also use pagination.
This problem doesn't allow me to move further with my project.

Please help

**Comment by Denis-Evseev** [comment]
Probably, I will need to create an intermediate php script which will implement intermediate calculations and mapping... I think it is the most efficient way to do it

**Comment by mevdschee** [comment]
These more complex filters are planned to be supported in v2.

**Comment by Denis-Evseev** [comment]
Hi,
Thank you for the new version, lots of new features!

How can we implement satisfy in v2?

**Comment by mevdschee** [comment]
This feature has landed in v2 and it is almost ready! Please try out the beta and let me know what you think about it.
