### ISSUE TITLE
How to change api.php to "V1" or something similar?

### ISSUE THREAD

**Issue by leossmith** [mevdschee/php-crud-api#267]
So i want to remove the api.php from my url and make it look something like exampledomain.com/v1/offers/ 

i think i should use .htaccess but i am not sure.

Can you help me?

ps. I love your api :)

**Comment by mevdschee** [comment]
Hi, thank you for your kind words. Yes, you should use the htaccess as described in the readme here: 

https://github.com/mevdschee/php-crud-api/blob/master/README.md#apache

**Comment by leossmith** [comment]
So i have added that in my htaccess and when i try to access the url exampledomain.com/api/offers/ or exampledomain.com/offers/ i get the following error:

No input file specified.

api.php/offers/ still works.

**Comment by mevdschee** [comment]
Did you uncomment line 2 and see what happens? It should show you the path info. This thread shows some common reasons why you would see that message:

http://my.instant-update.com/t/url-rewrites-are-not-working-with-fastcgi-no-input-file-specified/102

I hope that helps

**Comment by mevdschee** [comment]
Did you figure it out? Any updates?

**Comment by mevdschee** [comment]
closed due to inactivity

**Comment by leossmith** [comment]
I haven't managed to make it work unfortunately. It is either No input file specified or blank page whatever I try. It could be my server though.

**Comment by x29a** [comment]
@leossmith can you try the suggestion from [here](https://stackoverflow.com/a/1568937/875020)?
