### ISSUE TITLE
Api.php seems to be altering output of strings

### ISSUE THREAD

**Issue by dpskipper** [mevdschee/php-crud-api#268]
Hi,
I'm storing bycrypt hashes in the database, and when I view the output of the hash, in some of the hashes there is an extra `\` or `/` added into the string.

For example:
Hash in the database:
`$2y$12$K/jNNnJqz6b61rEHsheSgeuXBsdeH5sdewESCdhew`

Output in API.PHP:
`$2y$12$K\/jNNnJqz6b61rEHsheSgeuXBsdeH5sdewESCdhew`

**Comment by mevdschee** [comment]
This is correct behavior and according to spec, see:

https://tools.ietf.org/html/rfc7159#section
