### ISSUE TITLE
Get tables with '%' at first character in column name

### ISSUE THREAD

**Issue by Romerski** [mevdschee/php-crud-api#269]
Hi, I've this library working with sql server 2012. But I have a problem in some tables which they come empty. I've been testing and I think the problem is on tables with column's names start with '%', for example: '%Comision'.

I know is not the correct form to name columns but it's not my database and I cant modify anything.

Any ideas on how to fix it or escape '%' or something?

**Comment by mevdschee** [comment]
This currently is not supported as column names are filtered from special characters for security purposes. Searching and replacing "A-Z" with"%A-Z" in api.php will probably do the job.

**Comment by mevdschee** [comment]
I would recommend to work around this issue as special characters in column names are uncommon and not supported in all engines. Letters, numbers and underscores are safe to use.

**Comment by Romerski** [comment]
@mevdschee Thanks! Working like a charm. 

I know columns shuldn't be called like this but as I said I can't modify anything from database. Im developing a web interface for an ERP running on SQL Server 2012 and it's not mine. About security, will be a private API for app and I think it would be fine with authentication.

Thanks again for your time and for this great job!

**Comment by mevdschee** [comment]
Great. Thank you for your question and enjoy the software!
