### ISSUE TITLE
Underscore in id doesn't work

### ISSUE THREAD

**Issue by henninghall** [mevdschee/php-crud-api#27]
I am trying to get an row by "api.php/tablename/id" but it doesn't work when my string id contains a underscore(_). When I use "api.php/tablename" all rows are shown, including those which contains underscore. Am I doing something wrong? Thanks again for a brilliant API.

**Comment by mevdschee** [comment]
Fixed in 49c73db, although this is not needed for uuid or numeric id (recommended use)

**Comment by mevdschee** [comment]
Can you confirm this resolves the issue for you?

**Comment by mevdschee** [comment]
Closed due to inactivity
