### ISSUE TITLE
Update Fail with URL Parameters Specified

### ISSUE THREAD

**Issue by excel-vba-course** [mevdschee/php-crud-api#270]
Hi - thanks for the code - very useful :-)

I need to perform an update operation with URL parameters specified (because after the update I need to return a field value from the record being updated - plan to include an auxiliary READ after the update (equiv of PostgreSQL's UPDATE.....RETURNING) but notice that when specifying columns=foo in the URL and not having foo=bar in the body ($input) that the input value is unset (a comparison is being performed against columns GET var and input fields) by the below:

filterInputByFields

Can you please let me know the purpose of this function ?

Thanks,
Steve

**Comment by mevdschee** [comment]
I guess my idea ​was that you may specify which columns need to be written using a get parameter.

**Comment by excel-vba-course** [comment]
Thanks but isn't that the job of the input vars ? In any case, I feel it is useful in order to check that the fields being specified for update or insert actually exist. So I left the check in but included the array of all fields in the table and used that as the basis of comparison rather than those that may have been specified in the URL.
