### ISSUE TITLE
Composite Primary Keys

### ISSUE THREAD

**Issue by jsmith1717** [mevdschee/php-crud-api#271]
First, thank you very much for writing this great API. I read all your code months ago, and it was very easy to understand. One question:

Documentation says "**Composite primary** or foreign keys are not supported."

You normally can't count on composite fields being unique, and have to concatenate a sequential field that increments. But MySQL + InnoDB do not support composite indexes that auto-increment. I understand that your APIs don't support the syntax required to implement the normal work-around for this: 

`
BEGIN;
SELECT @id := IFNULL(MAX(id), 0) + 1 FROM tbl WHERE other = 123 FOR UPDATE;
  INSERT INTO tbl
     (other, id, ...)
     VALUES
     (123, @id, ...);
COMMIT;
`

However, it is possible to declare a table with an auto-incrementing composite key, if you declare a redundant index:

`
key1 SMALINT UNSIGNED,
key2 INT UNSIGNED AUTO_INCREMENT,
PRIMARY KEY(key1, key2),
INDEX(key2)
`

How is it that your APIs don't support this primary key? Can't we just use filters?

`GET http://url/api.php/table?filter[]=key1,eq,5&filter[]=key2,gt,3&satisfy=all`

Is there some API limitation on composite primary keys that I'm missing?

**Comment by mevdschee** [comment]
If you want to read/update/delete a specific record you need to send something like:

    DELETE http://url/api.php/table/123

The value 123 is a single value matched against what is specified to be the primary key.

I hope my explanation clears things up.

**Comment by jsmith1717** [comment]
Got it, thank you. Our App really needs composite indexes and logarithmic search times on SELECT. 

I'll modify our local copy to use the filters.
