### ISSUE TITLE
Escaped JSON Issue

### ISSUE THREAD

**Issue by excel-vba-course** [mevdschee/php-crud-api#276]
Hi,

This may be a naive question but I am getting issues when trying to update a record that contains the apostrophe: ' character. I am forming a JSON payload and it is already escaped when I PUT it to the server but the api escapes using mysqli_real_escape_string. Does this mean the character is escaped twice, and looks simply like the escaping of \ character ?

BTW I did try the payload without any escaping but that also did not work sadly :-(

Thanks in advance for any pointers etc.

Steve

**Comment by excel-vba-course** [comment]
Here is the string being PUT to the server:

[
{"localid":"34","ID":"7","createduser":"64","notename":"sdsdsadsa d'n","noredetail":"asdsdasdsas
","created":"2017-6-25 5:30:40 AM","modified":"2017-6-25 5:30:54 AM","modifieduser":"0","ts":"4270","deleted":"False","dirty":"True"}
]

Notice the apostrophe in field notename ? I get this error: Not found (subject)

Here is the same string with escaping:

[
{"localid":"34","ID":"7","createduser":"64","notename":"sdsdsadsa d\'n","noredetail":"asdsdasdsas\r\n","created":"2017-6-25 5:30:40 AM","modified":"2017-6-25 5:30:54 AM","modifieduser":"0","ts":"4270","deleted":"False","dirty":"True"}
]

I get the same error. When I remove the apostrophe, all is good ! Can someone please enlighten me ?

Thanks,
Steve

**Comment by mevdschee** [comment]
Thank you for reporting this issue. Can you please review my test case and run it locally?

**Comment by mevdschee** [comment]
I can't reproduce this issue.
