### ISSUE TITLE
Exclude specific column on server-side

### ISSUE THREAD

**Issue by AlexeyYar** [mevdschee/php-crud-api#277]
Hi, mevdschee! Please explain, what is the best practice to deal with security aspect.
For example, I've got password_hash in "users" table. So when I retrieve data from this resource I get all columns of it including "password_hash" and "email" which I don't want to be accessable for everyone.

Adding "columns" or "exclude" parameters doesn't seem to me secure enough. Or it's ok?
May be I have to implement some server-side logic to handle it properly? Please, give some advice on it.

**Comment by ksartnl** [comment]
I also want to know how to exclude certain columns of a table. I think it needs column_authorizer.

**Comment by mevdschee** [comment]
>I think it needs column_authorizer.

Indeed it does:

            'column_authorizer'=>function ($action, $database, $table, $column) {
                return !($column=='password'&&$table=='users');
            },

Is that a good enough example?

**Comment by AlexeyYar** [comment]
Oh, thanks! Will it work for included tables as well? For example, if I fetch data from "pages" table where user_id refers to included "users" table.

**Comment by alexandruaron** [comment]
how would you apply this to multiple tables and multiple columns?

**Comment by mevdschee** [comment]
@AlexeyYar: yes! 

@alexandruaron: using in_array:

    'column_authorizer'=>function ($action, $database, $table, $column) {
        return !($column=='password'&&in_array($table,array('users','posts')));
    },

see: http://php.net/manual/en/function.in-array.php

**Comment by alexandruaron** [comment]
Thanks for the quick reply. I did manage to do this. My question was how would you apply this for ex:

table 'users' for columns 'password,mobile_number,email' and table 'posts' for columns 'date,ip'

**Comment by mevdschee** [comment]
With a more complex expression you can .. use '||' for 'or' and '&&' for 'and'.

    'column_authorizer'=>function ($action, $database, $table, $column) {
        return !(
            ($table=='users' && in_array($column,array('password','mobile_number','email'))) ||
            ($table=='posts' && in_array($column,array('date','ip')))
        );
    },

I hope this helps.

**Comment by alexandruaron** [comment]
Thanks!
