### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by ManniManfred** [mevdschee/php-crud-api#28]
Hi,

can i filter something like "(col1,eq,2 or col2,eq,2) and col3,eq,7"?
My current workaround is creating a view with a column that combines col1 and col2.

**Comment by mevdschee** [comment]
No, this is not supported. Your workaround sounds fine to me. IMHO the real solution would be to support #22.

**Comment by mevdschee** [comment]
Updated readme to make this more clear. See: c93095154310a3ef054423e50fa1eb1242950e72

**Comment by mevdschee** [comment]
Improved wording. See: fd6a6ba92f2e60a9f4c4e935850e0c4f55f5001e @mevdschee mevdschee committed just now
