### ISSUE TITLE
Angular 1.6.4 no show data in ng-repeat

### ISSUE THREAD

**Issue by zubzero** [mevdschee/php-crud-api#283]
Good morning, Mr. Maurits: I currently use php_crud_api, I had used it before, without problems, but I am currently trying to use it without success. I am using AngularJS 1.4.3 or 1.6.4 to bring me the data from: viveenunclick.com/api.php/clientes_categories

With the angular code: 
app.controller("CategoriaCtl", function($scope, $http) {
          var url = 'http://viveenunclick.com/api.php/clientes_categorias';
          $http.get(url).success(function(response) {
            $scope.clientes_categorias = php_crud_api_transform(response);
            console.log($scope.clientes_categorias);
          });
        });

And HTML: 
          <ul ng-controller="CategoriaCtl">
                <li ng-repeat="x in posts">{{ x.nombre }}</li>
            </ul>
But I can not visualize the data. Could you please orient me if I am doing things wrong or how can I see the data?
Thanks in advance, from Mexico.

**Comment by mnicic** [comment]
Does php_crud_api_transform() replaces transform=1 in the URL? What is your response?

**Comment by ezetojo** [comment]
@zubzero php-crud-api is working perfect. I added the transform in the url. Check your angular code.
https://codepen.io/ezetojo/pen/KXqKPW

**Comment by mevdschee** [comment]
I'll close this now, due to inactivity.
