### ISSUE TITLE
Filter AND / OR

### ISSUE THREAD

**Issue by wwwjohntech** [mevdschee/php-crud-api#284]
Hi,

First of all, thank you for the good job!

Question, I'm trying to figure out how to make a request like for example:

from_id_user=123 OR to_id_user=123

The thing is the user can be a receiver or a sender.

Thank you

John

**Comment by mevdschee** [comment]
Thank you for your kind words. Try to add the following to your URL:

&filter[]=from_id_user,eq,123&filter[]=to_id_user,eq,123&satisfy=any

See also: https://github.com/mevdschee/php-crud-api#list--filter--satisfy

**Comment by wwwjohntech** [comment]
Hey,

The problem is that I have another condition.

My first condition is id_conversation and I need it after that I need from_id_user OR to_id_user

This is my major problem right now.

Thank you

John

Envoyé de mon iPad

**Comment by mevdschee** [comment]
I believe satisfy can be set per table, but I suggest to do two api calls, much easier!

**Comment by wwwjohntech** [comment]
OK the thing is it's in the same table that's why and for me it's easier to do:

messages?filter[]=id_conversation,eq,123
messages?filter[]=from_id_user,eq,345
OR
messages?filter[]=to_id_user,eq,345

**Comment by mevdschee** [comment]
Unfortunately complex queries are not supported (as stated in the documentation). Does the workaround of multiple queries work for you?

**Comment by mevdschee** [comment]
closed due to inactivity
