### ISSUE TITLE
Have question about structure and display of JSON data

### ISSUE THREAD

**Issue by laural4705** [mevdschee/php-crud-api#287]
I am new to web services and found your api file extremely helpful and easy to use.  I was able to hook up to my MSSQL server and retrieve information without problem, so thank you for that!  I would now like to take the data that I am pulling and present it in an html page.  I am not sure how to do this and have been doing a lot of reading to try and figure it out.  I am noticing that the structure of my JSON data does not look like the other sites that I have seen, so I was hoping you could tell me if this looked correct, and if not, how I could fix it...  thanks :)

{
  "content_data": {
    "columns": [
      "id",
      "title"
    ],
    "records": [
      [
        41901,
        "Resources for Educational Excellence"
      ],
      [
        44230,
        "The Khan Academy"
      ],
      [
        145925,
        "Educating Your Child at Home"
      ],
      [
        147803,
        "Organisations and Resources for Primary Schools"
      ]
    ]
  }
}

**Comment by mevdschee** [comment]
Hi, thank you for reaching out. You probably already found this, but for completeness and future reference: 

You need to add "&transform=1" to the request URL to get what you expect, or you could transform the json client side using the library provided in the "lib" directory.
