### ISSUE TITLE
Support for CRUD on views

### ISSUE THREAD

**Issue by ErikV88** [mevdschee/php-crud-api#29]
404 when using guid as id for update

Not found (1pk)
0

**Comment by mevdschee** [comment]
@ErikV88 tested this on MySQL and it works, could it be that you forgot to add:

```ALTER` TABLE `posts` ADD PRIMARY KEY `id` (`id`);```

Kind regards, Maurits

**Comment by mevdschee** [comment]
Please let me know whether or not this solves the issue.

**Comment by mevdschee** [comment]
closed due to inactivity

**Comment by ErikV88** [comment]
Sorry, It fail when calling a view . We need a uniq table

**Comment by mevdschee** [comment]
Please post your table definition, so I can help you. Use:

```show table `posts````

Where 'posts' is the table you are using.

**Comment by ErikV88** [comment]
CREATE TABLE IF NOT EXISTS `BasketProducts` (
  `BasketID` int(11) NOT NULL,
  `ProductID` int(11) NOT NULL,
  `NummerOfProducts` int(11) NOT NULL DEFAULT '1',
  `PrimKey` varchar(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`PrimKey`),
  KEY `atbl_WebShop_BasketProductsProductID` (`ProductID`,`BasketID`),
  KEY `IX_ProductBasket` (`BasketID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TRIGGER IF EXISTS `IXBasketProducts`;
DELIMITER //
CREATE TRIGGER `IXBasketProducts` BEFORE INSERT ON `BasketProducts`
 FOR EACH ROW SET NEW.PrimKey=UUID()
//
DELIMITER ;

ALTER ALGORITHM=UNDEFINED DEFINER=`myUser`@`localhost` SQL SECURITY DEFINER VIEW `aviw_BasketProducts` AS 
	SELECT `P`.`ID` AS `ID`,`P`.`Name` AS `Name`,`P`.`Price` AS `Price`,`P`.`Description` AS `Description`,`BP`.`NummerOfProducts` AS `NummerOfProducts`,`BP`.`PrimKey` 	AS `PrimKey`,(`P`.`Price` * `BP`.`NummerOfProducts`) AS 	`TotalPrice` 
    FROM (`BasketProducts` `BP` 	
      INNER JOIN WebShop_Products` `P` on((`P`.`ID` = `BP`.	`ProductID`))) 
      GROUP BY `BP`.`BasketID`,`BP`.`ProductID`

**Comment by mevdschee** [comment]
I think the Primary Key reference gets lost when you join two tables in a view.

**Comment by mevdschee** [comment]
Tried to simulate your case and even without join there are no primary keys defined for views (probably by definition). This means that in order to expose full crud on a view we need another method to find the primary key. Fallback to the name "id" comes to mind as a possible solution.

**Comment by ErikV88** [comment]
I find a solution to it ... in ny js lib , my object now the uniqtable of the view... Then i can call the view if update and delete or update . but if select then the view :+1:

**Comment by mevdschee** [comment]
>Fallback to the name "id" comes to mind as a possible solution or to default to the first column of the view.

This is now implemented
