### ISSUE TITLE
Using a View instead of a Table name

### ISSUE THREAD

**Issue by laural4705** [mevdschee/php-crud-api#291]
Is there a way to use a View instead of a Table name?  When I use the name of the view in my URL I don't get anything returned....  thanks :)
Also, how do I get the total number of records returned for pagination? Thank you!

**Comment by mevdschee** [comment]
>Is there a way to use a View instead of a Table name?

Views are only supported on list calls.

>how do I get the total number of records returned for pagination?

This is returned in a variable named "results", see: 
https://github.com/mevdschee/php-crud-api#list--order--pagination

**Comment by laural4705** [comment]
This is perfect, the pagination works great.  Thank you for the information!

**Comment by laural4705** [comment]
You mentioned that views were only supported on list calls.  I just wanted to check with you about something.  I am able to return all of my data in perfect JSON, in the browser, using this url: 

http://www.mywebserver.com/rest/api.php/ws_nfy?transform=1&filter=content_languages_list,cs,001

Where ws_nfy is a view I created on mssql server.  When I put this in the browser it works great.  When I try to access it via php (file_get_content) or as a callback within my Jquery, I get nothing...  If it works in the browser, then shouldn't it work other places, too?  Thanks for the information :)

**Comment by mevdschee** [comment]
> If it works in the browser, then shouldn't it work other places, too?

yes

**Comment by claudesign** [comment]
Hello Maurits,
First things first: your API is great, and it's the reason I am rewriting one of my websites according to the _API-first_ architecture.

I am having a problem similar to laural4705's: list calls do not return my views. Is it because of the **TABLE_TYPE** in getTablesSQL() ?

`case 'mysql':return 'SELECT "TABLE_NAME" FROM "INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_TYPE" IN (\'BASE TABLE\') AND "TABLE_SCHEMA" = ? ORDER BY BINARY "TABLE_NAME"';`

Further info: 
- Error: {"code":1001,"message":"Table 'vwforumlatest' not found"}
- MySQL version: 5.5.5-10.1.36-MariaDB

Am I missing something?

Thank you
Claudio

**Comment by mevdschee** [comment]
Hi Claudio,

Yes, if you adjust the "IN" to read "IN (\'BASE TABLE\', \'VIEW\')" you also get views returned.

Note that you can only do list operations on those (as there is no PK reflected).

KInd regards, 

Maurits

**Comment by mevdschee** [comment]
>Note that you can only do list operations on those (as there is no PK reflected).

Did you try list operation and are you on the latest master?

**Comment by claudesign** [comment]
> Did you try the 'list' operation
Yes, I am using GET /records/<my view>

> and are you on the latest master?
And here was the problem... I downloaded the master as a .zip file on 29/09/2018. Just re-downloaded it, amended getTablesSQL() as you suggested above, and now my views are visible. Thanks!

I imagine this (the amount of changes you applied in the last three days) could also fix something else I encountered: when joining two tables, the presence of an ENUM or MEDIUMINT column **anywhere** in the database (therefore **not** in the tables being joined) caused an error. I resolved that by replacing these data types with CHAR, VARCHAR or INT. But this is definitely off-topic and unrelated to views.

Once again, thanks for the API and for the support, Maurits.
Claudio

**Comment by mevdschee** [comment]
Thank you for reporting these issues. Enjoy the software!

**Comment by mevdschee** [comment]
Please follow the progress on #409

**Comment by mevdschee** [comment]
@claudesign latest master should now support what you want without modification.
