### ISSUE TITLE
Record filter

### ISSUE THREAD

**Issue by pinheiroweb** [mevdschee/php-crud-api#295]
Hello Friends,

How can I apply a forced filter?

Example:
The Api can only return the "**Cities**" if the "**state**" is sent.

GET http://localhost/api.php/cities?filter=state,eq,Florida

Thank you very much!

**Comment by mevdschee** [comment]
There are ways to implement this using the available handlers, but there is no such thing as a built-in "forced filter". Wouldn't it be better to simply limit the number of results? You can limit the number of results to 50 by adding the following to the top of the file:

    $_GET['page']='1,50';

I hope this helps.
