### ISSUE TITLE
getting a 404 upon reuqest

### ISSUE THREAD

**Issue by dicoy** [mevdschee/php-crud-api#298]
I started with a fresh lemp instalation and just copied api.php into the html directory and edited the access info.

Then I created a table like so:
CREATE TABLE test (
    ->   ID int(11) NOT NULL AUTO_INCREMENT,
    ->   text varchar(255) NOT NULL,
    ->   optional varchar(255) DEFAULT NULL,
    ->   number int(11) DEFAULT NULL,
    ->   PRIMARY KEY (ID)
    -> ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
Query OK, 0 rows affected (0,33 sec)

mysql> INSERT INTO test VALUES (1,'zero','first actually',1);
Query OK, 1 row affected (0,05 sec)

http://localhost/api.php shows me the swagger example with the table I created:
`paths: {
/test: {
get: {
tags: [
"test"
],
summary: "List",
parameters: [...`

but for some reason I get a 404 from:
http://localhost/api.php/test

Any ideas?

**Comment by 331164885** [comment]
https://github.com/mevdschee/php-crud-api#nginx-config-example   Hope to help you

**Comment by mevdschee** [comment]
Thank you @331164885! See also #121

**Comment by dicoy** [comment]
That was exactly it. Thankyou both
