### ISSUE TITLE
Support inserting mutiple records (json array)

### ISSUE THREAD

**Issue by maacaron** [mevdschee/php-crud-api#3]
Hi,
I'm trying to insert several rows to table by passing a json array with some elements but I get a 404 error:

```
[{
    "id" : "1",
    "name" : "Internet"
},{
    "id" : "2",
    "name" : "Internet 2"
}]
```

When I put single item into json everything works fine. I know that's not a bug but this would be a nice feature to that api - do you have plans to add this? Some kind of bulk insert.

Best regards,
macaron

**Comment by mevdschee** [comment]
@ maacaron: Great idea. I don't know why I did not build this yet. Will add this ASAP.

**Comment by mevdschee** [comment]
@maacaron Added in 7db137f, hope you like it.

**Comment by mevdschee** [comment]
Reverted the change, due to added complexity and hardly any performance gain.

**Comment by mevdschee** [comment]
See also: 2cd2597

**Comment by mevdschee** [comment]
(Re)added due to popular demand.
