### ISSUE TITLE
Support column name containing space character

### ISSUE THREAD

**Issue by peterphen** [mevdschee/php-crud-api#30]
Hi Mevdschee, 

First of all, thanks for this awesome API.

How to handle column name with two or more words?

...api.php?columns=First Name 

i'm using PHP5.2, MSSQL2012.

**Comment by mevdschee** [comment]
Search "a-zA-Z0-9" and replace with "a-zA-Z0-9 " in "api.php" and let me know whether or not that works for you.

**Comment by peterphen** [comment]
Noted, I'll report my finding soon. Tq

**Comment by peterphen** [comment]
Sorry,

Search "a-zA-Z0-9" and replace with "a-zA-Z0-9 " ? :D

**Comment by mevdschee** [comment]
note the space :-)

**Comment by peterphen** [comment]
Awesome, it works now.

**Comment by mevdschee** [comment]
Okay, glad it does. I will consider it as a change for master.

**Comment by mevdschee** [comment]
I believe this is fixed now.
