### ISSUE TITLE
ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by mateomattmatt** [mevdschee/php-crud-api#304]
I'm getting this error when using PUT method OPTIONS "URL" net::ERR_SPDY_PROTOCOL_ERROR
This is my code from ionic 3

		let toPut = {
			data : "Hello World"
		};
		let loader = this.loading.create({
		  content: 'Please wait...',
		});
		console.log(toPut);
		let headers = new Headers();
		headers.append('Content-Type', 'application/json');
  		let options = new RequestOptions({ headers: headers });
		loader.present().then(() => {
	        this.http.put(url, toPut, options) .map(res => res.json()).subscribe(data => {
	    	        console.log(data);
			loader.dismiss();
			let toast = this.toastCtrl.create({
		             message: 'Data : ' + toPut.data,
		             duration: 2000,
		             position: 'top'
		        });
	                toast.present(toast);
	         }, err => {
	  		loader.dismiss();
	  		// show alert
			let toast = this.toastCtrl.create({
		            message: 'Internal Server Error! ' + err,
		            duration: 3000,
		        });
	                toast.present(toast);
		  	});
	    });

**Comment by mevdschee** [comment]
Hi, thank you for reaching out. It seems to me that there is no point in trying to support SPDY, now that HTTP2 is here. Turn it off on your server.

see: https://stackoverflow.com/questions/38986585/put-request-generates-spdy-protocol-errors-only-in-chrome-or-opera

**Comment by mateomattmatt** [comment]
Thanks :D
