### ISSUE TITLE
Generated API doesn't work properly when imported into swagger.

### ISSUE THREAD

**Issue by xhorntail** [mevdschee/php-crud-api#306]
I have a database that looks like this:

![screenshot_1](https://user-images.githubusercontent.com/20708358/31264710-185ff158-aa28-11e7-981d-859a085e290a.png)

It imports into Swagger as this:

    responses:
        '200':
          description: An array of user_agents
          schema:
            type: array
            items:
              type: object
              properties:
                user_agent_id:
                  type: integer
                  x-dbtype: int
                  x-nullable: false
                  x-primary-key: true
                string:
                  type: string
                  x-dbtype: varchar
                  x-nullable: true
                  maxLength: 255`

Where, I believe, it should be something more like this (when using transform, and far different still when not using transform:

    responses:
        '200':
          description: An array of user_agents
          schema:
            type: object
            properties:
              user_agents:
                type: array
                items:
                  type: object
                  properties:
                    user_agent_id:
                      type: integer
                      x-dbtype: int
                      x-nullable: false
                      x-primary-key: true
                    user_agent_string:
                      type: string
                      x-dbtype: varchar
                      x-nullable: true
                      maxLength: 255`

The problem being, any client generated with Swagger doesn't work, as it's expecting a different model. I think. I'm new to all this, so be patient if I'm way off base here.

EDIT: Sorry that code looks ugly, I promise it's not like that in editing. haha.

**Comment by taktechOne** [comment]
Can confirm, the currently generated API output doesn't work with the client generator on Swagger.

**Comment by mevdschee** [comment]
Good find! Thank you

**Comment by xhorntail** [comment]
Submitted possible fix as PR #308 
Swagger generated API clients still return complex objects, it would likely be better to remove the table object from the output in the transform instead. This band-aids the current issue however.

**Comment by mevdschee** [comment]
New version has been released
