### ISSUE TITLE
POST or PUT for Batch Update (URI too long for PUT method)

### ISSUE THREAD

**Issue by pdm19882004** [mevdschee/php-crud-api#307]
Hello,
I have an App in UWP, where I have to send bulk Update queries (containing 5000+ products details per batch). Is there a way to use POST method to update?
My URI string is too long for PUT method.
Unfortunately I cannot code in PHP, my expertise is in .Net.

Thank you.

**Comment by mevdschee** [comment]
There is no limit for the URI string other than the one configured in your webserver, which is configurable. Just add in web.config 

    <httpRuntime maxRequestLength="2048576"/>

see: https://stackoverflow.com/questions/16609059/the-uri-string-is-too-long-for-the-input-parameter-of-my-post-method

**Comment by mevdschee** [comment]
closed due to inactivity
