### ISSUE TITLE
A addition to your examples.

### ISSUE THREAD

**Issue by resident0** [mevdschee/php-crud-api#31]
I had a similar situation to issue #30 when querying time stamps. The space between the date and time was breaking my URI. I wrote this function to correct the problem. Perhaps it could be added to the extras directory.

`function buildURI($endPoint, $resources, $filters, $satisfy='all') {
  /***
  *** $resources = array('res1', 'res2', 'res3' ...)
  *** $filters = array (array('Resource'=>'resName', 'Filter'=>'filter', 'Value'=>'val'))
  ***/

  $baseURI = 'https://path/to/api.php';

  $query = $baseURI . preg_replace('/(\s)/','%20',$endPoint);

  if (!empty($resources)) {
    for($i=0;$i<count($resources);$i++){
      $query .= ($i>0?',':'?columns=') . $resources[$i];
    }
  }
  if (!empty($filters[0])) {
    for($i=0;$i<count($filters);$i++){
      $query .= ($i>0?'&':(empty($resources)?'?':'&')) . (count($filters)>1?'filter[]=':'filter=') . $filters[$i]['Resource'] . ',' . $filters[$i]['Filter'] . ',' . preg_replace('/(\s)/','%20',$filters[$i]['Value']) . ($i===count($filters)-1?'&satisfy='.$satisfy:'');
    }
  }
  return $query;
}`

**Comment by mevdschee** [comment]
Thank you for your suggestion. Although this might work (for some cases), it can be made much easier more correct by conforming to the RFC standards. Simply use the PHP's ```http_build_query`` function.

See: http://php.net/manual/en/function.http-build-query.php
