### ISSUE TITLE
Please add capability to return GeoJSON Feature Sets...

### ISSUE THREAD

**Issue by pottertech** [mevdschee/php-crud-api#312]
Now that spatial queries is supported it would complete the spatial ability for the api to return GeoJSON Feature Sets.  This could be done by adding "&transform=2" to have the api return something like below as an example:

    {   "type": "FeatureCollection",
        "features": [
            {   "type": "Feature",
                "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
                "properties": {"prop0": "value0"}
            },
            {   "type": "Feature",
                "geometry": {
                    "type": "LineString",
                    "coordinates": [
                        [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
                    ]
                },
                "properties": {
                    "prop0": "value0",
                    "prop1": 0.0
                }
            },
            {   "type": "Feature",
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                        [   [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
                            [100.0, 1.0], [100.0, 0.0] 
                        ]
                    ]
                },
                "properties": {
                    "prop0": "value0",
                    "prop1": {"this": "that"}
                }
            }
        ]
    }

**Comment by mevdschee** [comment]
It seems this is a solved problem for PHP and JavaScript:

PHP: https://github.com/phayes/geoPHP

JavaScript: https://github.com/mapbox/wellknown

Would you be helped with a geometry column filter?

**Comment by pottertech** [comment]
I current use geoPHP for other things and it can be of help.  I would like your API to do all the work so that the Javascript developers have to do nothing.
I am including a sample snippet to give you the idea of how it might work:

<?php

date_default_timezone_set("GMT");

# Include required geoPHP library and define wkb_to_json function

include_once('geoPHP/geoPHP.inc');

function wkb_to_json($wkb) {
   $geom = geoPHP::load($wkb,'wkb');
   return $geom->out('json');
}

# Connect to MySQL database
$conn = new PDO('mysql:host=localhost;dbname=earth','user','password',array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));

# Build SQL SELECT statement 
$WKT = "POINT(48.7471065435931 31.3431585560757)";"
$sql = $SELECT * FROM Airports WHERE ST_Intersect(geometry,' . $WKT .')";

   # Try query or error
   $rs = $conn->query($q);
   if (!$rs) {
       echo 'An SQL error occured.\n';
       exit;
   }
# Build GeoJSON feature collection array
$geojson = array(
  'type'      => 'FeatureCollection',
  'features'  => array()
);

# Loop through rows to build feature arrays
while ($row = $rs->fetch(PDO::FETCH_ASSOC)) {
   $properties = $row;
   # Remove wkb and geometry fields from properties
   unset($properties['geometry']);
   $feature = array(
        'type' => 'Feature',
        'geometry' => json_decode($geom),
        'properties' => $properties
   );
   # Add feature arrays to feature collection array
   array_push($geojson['features'], $feature);
}

header('Content-type: application/json');
echo json_encode($geojson, JSON_NUMERIC_CHECK | JSON_UNESCAPED_UNICODE);
$conn = NULL;
?>


—Skip

**Comment by pottertech** [comment]
The properties are the “other” columns of the record but excluding geometry since geometry is already part of the record as the geojson “geometry field” after “type”: “Feature”.

—Skip

**Comment by pottertech** [comment]
The tools like:
PHP: https://github.com/phayes/geoPHP
JavaScript: https://github.com/mapbox/wellknown

only convert the WKT coordinates to GeoJSON and do not provide the ability to include the "properties" along with the GeoJSON object so that you have a whole feature.

**Comment by mevdschee** [comment]
FYI, this has been implemented in the latest version.

**Comment by pottertech** [comment]
Thank you very much!  You continue to be one of the best.

**Comment by mevdschee** [comment]
Thank you for your kind words.
