### ISSUE TITLE
Getting count and joins. 

### ISSUE THREAD

**Issue by abantecart** [mevdschee/php-crud-api#314]
Hello Guys,

Great library, thank you. 

I was not able to find an ability to get count(*) as total and do custom joins. 

Are you interested in pull request if I develop that?

**Comment by mevdschee** [comment]
I think the count and distinct have been requested before. Those are not very controversial nor hard to build. Custom joins on the other hand .. ;-) What is your idea there?

**Comment by abantecart** [comment]
For our need, we do not have relational database. Some of selects will reqiure join between 2+ tables. 
I am still researching on best approach

**Comment by mevdschee** [comment]
>we do not have a relational database

What do you have?

**Comment by abantecart** [comment]
Mysql / MyISAM with programatic relationships (not on database side)

**Comment by mevdschee** [comment]
do you join on the primary key and a foreign key?

**Comment by mevdschee** [comment]
Are there naming conventions

**Comment by abantecart** [comment]
Mostly join on primary keys.

**Comment by mevdschee** [comment]
I was thinking of a fallback for primary keys based on name ("id") and foreign keys based on table name and column name.. "posts_id" for instance.. would that help you?

**Comment by mevdschee** [comment]
Or would you want to define the relationships manually using a configuration parameter?

**Comment by abantecart** [comment]
I would prefer configuration parameters. Thank you. I can help with that if you want. I might have time tomorrow.

**Comment by mevdschee** [comment]
Count is now supported through pagination with a small page size and joins based on naming conventions will not be supported (there will not be MyISAM support).

**Comment by claudesign** [comment]
> Count is now (in v2) supported through pagination with a small page size

Could you give us an example of how to use count in php-crud-api? /records/table1?... 
Thank in advance.

**Comment by mevdschee** [comment]
Sure:

    GET /records/posts?order=id&page=1,0

See also: 

https://github.com/mevdschee/php-crud-api/blob/master/tests/functional/001_records/022_list_with_zero_page_size.log

**Comment by claudesign** [comment]
Maurits,
I am thinking of the aggregate function count(), so my problem might be more similar to #60. Specifically, I have two tables:

minisites_tags
- tag_id
- tag_value

minisites_tags_join
- id 
- tag_id
- item_id

So far (pre- php-crud-api) (thanks again for it!), I have been querying my tables with a simple
```
SELECT tag_value, count(*) AS counter
FROM minisites_tags mt
	JOIN minisites_tags_join mtj ON mtj.tag_id = mt.tag_id
GROUP BY tag_value
ORDER BY counter DESC;
```

which produces something like 

```
tag_value | counter
-------------------
Nirvana   | 271
Beatles   | 421
Bach      | 123
```

Using ```GET /records/posts?order=id&page=1,0``` would return the total number of records, instead of the count for each tag...

Any ideas? I have been trawling through code and issues (open and closed) without finding a solution.

Thanks
Claudio

**Comment by claudesign** [comment]
Well, there was an easy solution: use the above query to create a view. Problem solved.
