### ISSUE TITLE
Having a weird issue trying to POST a record through PHP using cUrl

### ISSUE THREAD

**Issue by rmawani** [mevdschee/php-crud-api#315]
Hi,

Been using your awesome solution for a number of months now and it's all working very smoothly.

This past could of days, I've been struggling with a pretty simple piece of code in which I send some info to the script from my interface and then let the script handle POSTing the info to the API after gathering some additional data.

The first 3 API calls work whereas the 4th does not. You'll see that the first 3 calls are being done through a function call that basically uses the same cUrl flow and options as the 4th API call (which I built and called cUrl inline).

    $json = file_get_contents('php://input');
    $jsonData = json_decode($json);
    $appID = $_GET['APPID'];
    $userID = $jsonData->UserID;
    $message = $jsonData->Message;
    $actionType = $jsonData->ActionType;
    if (isset($jsonData->SupportTicketNumber))
        $supportTicketNumber = $jsonData->SupportTicketNumber;
    else
        $supportTicketNumber = "";
    $oneSignalAppId = "";
    $oneSignalApiKey = "";

    if (session_id() == '')
        session_start();

    switch ($appID) {
        case "TSG31072017":
            require_once("../tsg/lib/func.global.php");
            $oneSignalAppId = "hiddenappid";
            $oneSignalApiKey = "hiddenapikey";
            break;
        case "SAM31072017":
            require_once("../sam/lib/func.global.php");
            $oneSignalAppId = "hiddenappid";
            $oneSignalApiKey = "hiddenapikey";
            break;
        case "KOR31072017":
            require_once("../kor/lib/func.global.php");
            $oneSignalAppId = "hiddenappid";
            $oneSignalApiKey = "hiddenapikey";
            break;
    }

    $cookieFile = fopen('php://temp', 'r+');

    // Authenticate Admin and receive JWT
    $Url = 'locahost/api/get_token.php';
    $postData = 'username=username&password=passowrd&APPID=' . $appID;
    $jwt = RESTRequest('POST', $Url, $cookieFile, true, $postData);

    // Authenticate JWT and receive CSRF for Admin user
    $Url = 'localhost/api/';
    $postData = 'token=' . $jwt . '&APPID=' . $appID;
    $csrf = RESTRequest('POST', $Url, $cookieFile, true, $postData, 'UrlEncoded');

    // GET PushID for ID from Users Table
    $Url = 'locahost/api/Users/' . $userID . '?transform=1&csrf=' . $csrf . '&APPID=' . $appID;
    $output = RESTRequest('GET', $Url, $cookieFile);

    $pushID = $output['PushID'];
    $systemMessageNumber = strtoupper(createSystemMessageNumber());
    $action = $actionType == "CloseSupportRequest" ? $actionType . ":" . $supportTicketNumber : $actionType;
    $subject = "System Message";

    //
    // Use Admin CSRF to perform HTTP REST Requests
    //

    // POST record to SystemMessages Table
    $Url = 'localhost/api/SystemMessages?APPID=' . $appID . '&csrf=' . $csrf;
    $postDataArray =
    [
        'To' => $pushID,
        'SystemMessageNumber' => $systemMessageNumber,
        'Subject' => $subject,
        'Message' => $message,
        'RelatedUserID' => $userID,
        'Action' => $action
    ];
    $postDataJson = json_encode($postDataArray);
    //$addSystemMessageResponse = RESTRequest('POST', $Url, $cookieFile, true, $postDataJson, 'Json');

    //
    // Above function call not working so try to build the cUrl call inline here instead
    //
    
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $Url);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        "Content-Type: application/json; charset=utf-8",
    ]);
    curl_setopt ($ch, CURLOPT_COOKIEJAR, $cookieFile);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $postDataJson);

    $resp = curl_exec($ch);

    if(!$resp) {
        die('Error: "' . curl_error($ch) . '" - Code: ' . curl_errno($ch));
    } else {
        echo "Response HTTP Status Code : " . curl_getinfo($ch, CURLINFO_HTTP_CODE);
        echo "\nResponse HTTP Body : " . $resp;
    }

    // Close request and unlink the cookieFile to clear up some resources
    curl_close($ch);
    unlink($cookieFile);

Really not sure what I'm doing wrong in the above code as the problematic POST request in question works perfectly if I send the same through PostMan or Paw. Not to mention the other 3 API calls that work as expected in the same script beforehand.

Any help would be greatly appreciated!

Thanks in advance and hoping you can point me in the right direction...

**Comment by mevdschee** [comment]
I don't immediately see the issue. Can you post the output and if possible run Charles on both postman and this script to detect what the difference is?

**Comment by rmawani** [comment]
Below is the output I receive after inserting a var_dump before the 4th API request fails:

string(78) "localhost/api/SystemMessages?APPID=KOR31072017&csrf=6360357089428111360"
string(181) "{"To":"c35ca3f3-dac2-4f5a-8745-05873245d9b0","SystemMessageNumber":"8D52E501F7E6500","Subject":"System Message","RelatedUserID":"532","Action":"CloseSupportRequest:8D52E501F7E6500"}"
Error: "" - Code: 0

Now, the reason I know the first 3 API requests work is that I would not have a valid CSRF nor would I have had a value in the 'To' field.

I also took your advice and ran both scripts through CharlesProxy and saw no differences that would cause this type of issue.

After some further digging, I then tried to replace that 4th POST request with a very simple PUT request on another table and that didn't work through this script either whereas it works fine in Paw.

Utterly baffled...

**Comment by rmawani** [comment]
Just wanted to let you know that I managed to fix the issue. 

It was of course from my end as I had not handled Cookie interaction properly resulting in a 401 -
Unauthorized error on the PUT request. I was trying to Save a cookie to the CookieJar instead of using the CookieFile that was already created by the first 2 POST requests.

Thanks so much for taking the time to look at the issue from your end as your advice to use Charles Proxy really helped me to pinpoint the problem!

**Comment by mevdschee** [comment]
Well done. Thank you for not giving up! Enjoy.
