### ISSUE TITLE
File Upload $_FILES example file manipulation

### ISSUE THREAD

**Issue by Mindex404** [mevdschee/php-crud-api#316]
Hi!
How do I access the $_FILES variable from the API?
I need to manipulate the uploaded file, does someone have an example of file upload? 
How do I move the file to another folder? Thanks for your help.

**Comment by mevdschee** [comment]
Can you read issue #215 and see whether or not it helps you?

**Comment by Mindex404** [comment]
yes, I read it Maurits but #215 is is trying to update an image. I just need to upload it (POST) and manipulate the file as I did before, for example:

```
<input type="file" name="image"/>

$tmp_name = $_FILES['image']['tmp_name'];
$name = $_FILES['image']['name'];
$folder = '../folder/'
move_uploaded_file($tmp_name, $folder.$name)

$sql = "
INSERT INTO za_article_image (
img
)
VALUES(
'$name'
)
";
```
