### ISSUE TITLE
Dont know how to update database with Ajax

### ISSUE THREAD

**Issue by shenglong209** [mevdschee/php-crud-api#32]
my code

```
jQuery('#update').click(function(){
    jQuery.ajax({
      type: 'PUT',
      url: 'http://localhost/api/api.php/users/2',
      dataType: "json",
      data:{'username':'abcxyz'},
      success: function(data){
        alert(data);
      }
    });

  });
```

i dont understand exactly this request is mean? what mean of the number '2' in url, what is the data will be updating after this request.

and i just run this request, it returned zero.
Please help me !

**Comment by mevdschee** [comment]
This means that you set the field 'username' for the record with primary key 2 in the 'users' table to 'abcxyz'. The return value is the rows affected.

**Comment by shenglong209** [comment]
if i have tables 'users' with 2 fileds: id, usernames(primary key)
i want update the record where username="abc" then what i have to do ?
thank you !

**Comment by mevdschee** [comment]
First you need to find the id (which should be primary key, the username should be a unique key) for the user with that username:

    http://localhost/api/api.php/users?filter[]=username,eq,abc

Let's say that the id field for that record is '2', then you have to update that record with the code you posted before.

**Comment by shenglong209** [comment]
thanks you for your response, and i have a lastest question: how to update if my tables have a foreign key, because i just test, and it return -1

**Comment by mevdschee** [comment]
If the 'posts' table has a field 'user_id' for the author, pointing to the 'id' field in the 'users' table then you can simply set the field 'user_id' to an *existing* primary key value from the 'users' table. Hope that helps.

**Comment by shenglong209** [comment]
thank you very much ! i get it !

And . . . if someone fake a similar request to change the contents of the database. So what can I do to prevent ?
sorry sir, i just a student and  i just want to learn. please give me some idea !

**Comment by mevdschee** [comment]
You can add some code to protect your api with a username and password as shown in:

https://github.com/mevdschee/php-crud-api/blob/master/examples/auth.php

Or you can use a more sophisticated scheme, like http://jwt.io.

**Comment by shenglong209** [comment]
ohhh thank you very much, I'm stuck in this problem for a few days, and once again thank you for your help ^^

**Comment by mevdschee** [comment]
You are welcome. Good luck!
