### ISSUE TITLE
not all section are using xml file in language 

### ISSUE THREAD

**Issue by artiman** [mevdschee/php-crud-api#320]
hi 

I am just trying to add a language what i am trying to translate
i see most section like "setting_setting" using xml to get the translation into the database 
but i am see also that some section are not on file like : 
"forms_manager_forms_manager"
" banner_manager_banner_manager"
so i tried to add a file and create a directory > 
1. with the name (banner) as a directory in the language directory after
2. add a xml file "manager_banner_manager.xml" into this directory with the codes.

but it will not importing into the data in abanatecart 
how do i add this file to get it into the data abantecart ?

a litle help would be great 
Thanks

**Comment by mevdschee** [comment]
I'm confused. What is the question?

**Comment by artiman** [comment]
sorry for my bad english 

what i am trying to do is to translate abantecart from english to turkish for this i have translate nearly 90 % of the language to turkish but there is 1 section in the menu that still using english and not the other language .
I have all file what is under the TR language directory in xml format already translated 
in the default directory there is no xml file for the folder in the menu / design - banner Manager

so i ad a xml file to the directory manager_banner_manager.xml but it seems not working 
thats the problem i have 
hope you understund what i mean !

thanks

**Comment by mevdschee** [comment]
Okay.. that makes it a bit clearer. But I fail to see how "abantecart" is related to this project. Are you sure you don't want to submit this ticket here:

https://github.com/abantecart/abantecart-src

Kind regards, Maurits

**Comment by artiman** [comment]
oh.....  sorry yes i was try to submit the ticket to abantecart 
sorry again and thank you for the info you provided
