### ISSUE TITLE
404 error on synology nas

### ISSUE THREAD

**Issue by MaccerC** [mevdschee/php-crud-api#321]
Developing on localhost this api works fine.
However, deploying on my Synology Nas it throws a 'page not found' error 404.
I'm very sure I didn't misspell the URL. Doesn't this API work on a NAS?
Any idea how to overcome this error?

**Comment by mevdschee** [comment]
Can you post the version of PHP and the version of Apache that you are running? Can you also check whether or not $_SERVER['PATH_INFO'] is set?

**Comment by MaccerC** [comment]
My Synology NAS is running PHP version 5.6 on Nginx.
Now I've changed this to Apache HTTP Server 2.2 and all is working fine!
Thanks for pointing me into the right direction.

**Comment by mevdschee** [comment]
Great. It should also work on Nginx, but I'm glad you find a workaround!
