### ISSUE TITLE
Problem with relations

### ISSUE THREAD

**Issue by kolchagov** [mevdschee/php-crud-api#323]
When you execute relation from tests: '/posts?include=tags&columns=posts.id,tags.name&filter=id,eq,1&transform=1', PHP API output is:

```
{
  "posts": [
    {
      "id": 1,
      "post_tags": [
        {
          "post_id": 1,			<- 'post_tags.id' is missing here
          "tag_id": 1,
          "tags": [
            {
              "id": 1,
              "name": "funny"
            }
          ]
        },
        {
          "post_id": 1,
          "tag_id": 2,
          "tags": [
            {
              "id": 2,
              "name": "important"
            }
          ]
        }
      ]
    }
  ]
}
```
As you can see, 'post_tags.id' (PK) is missing from your output, which is essential for client-side applications (but PK appears in the other tests with relations)

**Comment by mevdschee** [comment]
This is due to the fact that the "post_tags" table is the intermediate table and therefor automatically added. If you need the PK you should execute:

    '/posts?include=post_tags,tags&columns=posts.id,tags.name&filter=id,eq,1&transform=1'

I hope this helps.
