### ISSUE TITLE
Problem with (wrong) result from one test

### ISSUE THREAD

**Issue by kolchagov** [mevdschee/php-crud-api#324]
the test @line 441: '/categories?include=posts&filter[]=id,ge,1&filter[]=id,le,1&filter[]=posts.id,eq,5&filter[]=posts.id,eq,6&filter[]=posts.id,eq,7&satisfy=all,posts.any' actually returns wrong results, because of the 'record_filter' function: 
```
     'record_filter'=>function ($action, $database, $table) {
              return ($table=='posts')?array('id,neq,13'):false;
      },
```
In this case the API should perform the following queries:
```
SELECT categories.id , categories.name , categories.icon
 FROM categories
 WHERE categories.id >= ? AND categories.id <= ?  with params: [1,1]
SELECT posts.id , posts.user_id , posts.category_id , posts.content
 FROM posts
 WHERE posts.id = ? OR posts.id = ? OR posts.id = ? OR posts.id != ? AND posts.category_id IN ( ? )  with params: [5,6,7,13,1]
```
and they have to return all posts except post.id=13

**Comment by mevdschee** [comment]
This bug should be fixed in v2.
