### ISSUE TITLE
Not found with nginx, but apache OK

### ISSUE THREAD

**Issue by nikakoy131** [mevdschee/php-crud-api#33]
Hello! I try to use api with nginx 1.6.2 with PHP 5.6.14. But default configuration of nginx+php don't like links like `api.php/users ` (nginx can not find file users). With apache all work fine. Maybe I can use another url for access to table "users"? Like this `api.php?table=users`. Or maybe I can do some changes in api.php to solve this problem. 
PS
I tried many configuration for nginx, but they can not solve my problem.

**Comment by mevdschee** [comment]
Can you add the following line on top of "api.php" and post the output here?

    die(var_dump($_SERVER));

I need to see what environment variables are missing.

**Comment by mevdschee** [comment]
Now supports Nginx several ways. For one with a 'path' GET parameter like this ```api.php?path=/users```

see: 3d8c49afc1a6f734d49f7d1136eb2897239aed6f

**Comment by nikakoy131** [comment]
Sorry I have old config file for nginx+php. With fresh config from [nginx official site](https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/#) all work fine. Anyway thank you!

**Comment by gbolo** [comment]
why was this change reverted?

**Comment by mevdschee** [comment]
Because it turned out nginx was not configured as recommended.

**Comment by mevdschee** [comment]
Also to avoid dead code. Why are you asking, do you need that code?

**Comment by mevdschee** [comment]
NB: You can still set `'request'=>$_GET['path']` in the configuration if that is what you want.

**Comment by gbolo** [comment]
mevdschee. Thanks, the recommended config worked.

**Comment by mevdschee** [comment]
You are welcome. Enjoy the software!
