### ISSUE TITLE
Websockets vs. REST-API

### ISSUE THREAD

**Issue by Disane87** [mevdschee/php-crud-api#332]
Hey again! Since my last tries with your excellent REST-API I'm currently building some microcontrollers which use your API to push data to the mysql database. 

Since I want to get the data in the client (angular) in realtime, I want to build on websockets.
But then I have the problem, your API has to call websocket methods to push the changes from the API to the websockets.  

Did you implemented something in this direction? 
At the moment, I'm only interested in the experience of you because I'm not sure if I should build on a websock and rest-api.

**Comment by mevdschee** [comment]
>Did you implemented something in this direction?

Yes, I once implemented something like that. I guess a (table) filter subscription system would make sense, but only for a very specific and real time experience (not for an administrative application).

Are you sure you need both real-time and the ACID compliance of a transactional database?

**Comment by Disane87** [comment]
That makes sense. I only need a realtime communication for the measurement data, not for the entire database. I guess it make sense to define a table where all tables are stored and how they should react (only via rest or emitting an event to a socket). 

Thank you for the tipp with the table filter!
