### ISSUE TITLE
question about auth

### ISSUE THREAD

**Issue by simonplm** [mevdschee/php-crud-api#335]
is it possible to use username and password from a table, let say users table, before acquiring the jwt token? so that i can be able to set the $_SESSION['user'] depends to the user level. if this has been asked before, can you please show me the link? tnx.

**Comment by mikfaina** [comment]
+1

**Comment by mevdschee** [comment]
It is currently not implemented, but adding code for this in the handler that checks the username + password is certainly possible.

**Comment by travscrog** [comment]
@mevdschee Could you give a little more detail about going about this? I don't know much PHP but using this I have a working API that I would like to combine with a simple username & password check that we also have working. I plan on using a separate table that will hold the user's credentials, ID, and access level and I want to pass allow access only after logging in using this method.

**Comment by mevdschee** [comment]
This will be covered in #427
