### ISSUE TITLE
Connecting to AWS MySQL Instance

### ISSUE THREAD

**Issue by greenfm** [mevdschee/php-crud-api#338]
Has anyone had any luck connecting to a MySQL database on AWS?

**Comment by mevdschee** [comment]
You should be able to. Did you run into problems or did you see any errors?

**Comment by greenfm** [comment]
I'm not sure how to retrieve the logs in AWS, but I've set all the credentials with the same values that work in MySQLWorkbench, but the api just times out with a 500 response

the default port in AWS is 3306, would that be a problem?

**Comment by mevdschee** [comment]
>the default port in AWS is 3306, would that be a problem?

not if you configure the port

**Comment by greenfm** [comment]
Looks like all the issues were with my EC2 intsances.  Once I set up the Linux AMI with the proper security groups, connection worked like a charm, ty!
