### ISSUE TITLE
function php_crud_api_transform in api.php vs php_crud_api_transform.php

### ISSUE THREAD

**Issue by kalvick** [mevdschee/php-crud-api#34]
Hi 

Experiencing the following Notices & Warnings on running the** client.php** under the examples folder

------------------
- Notice:

 **Undefined index: relations** in **\path to php_crud_api folder\lib\php_crud_api_transform.php** on line 11

- Warning:

 **Invalid argument** supplied for **foreach()** in **\path to php_crud_api folder\lib\php_crud_api_transform.php** on line 11

------------------------------

On detailed study, It is observed that

Under **lib** folder, the **php_crud_api_transform.php** requires the following 
at line 11
	    `** if (isset($reltable['relations'])) {`**
with the corresponding
`			**}`**
at line 16

to be in match with 

**`function php_crud_api_transform `**

in **`api.php`** at line 1252 and line 1257 respectively

Please confirm / advise.

Best Regards
Krishna
KALViCK Technologies

**Comment by mevdschee** [comment]
Thank you very much, very good analysis. I fixed it!

**Comment by mevdschee** [comment]
Please let me know whether or not it looks good to you and close the issue if it does.

**Comment by kalvick** [comment]
Fine! 

it's Working Well, Now

Best Regards
Krishna
KALViCK Technologies
