### ISSUE TITLE
How to filter on existing corresponding record in included table

### ISSUE THREAD

**Issue by siauderman** [mevdschee/php-crud-api#342]
Dear mevdschee,

How do I filter such that only records which have a corresponding record in 1 of the included tables are returned?

I have tried to filter on the id column of the included table 'nis' null, but it did not seem to work.

**Comment by mevdschee** [comment]
You may try to reverse the order of the primary table and the one you are including.

**Comment by siauderman** [comment]
But I just tried it and now it's returning 0 records...any idea why?

**Comment by siauderman** [comment]
I can cull the list on the client but i don't want to waste bandwidth returning lots of records as 1 table will have lots more records than the other, it's a "subclass" situation.

**Comment by mevdschee** [comment]
You can also retrieve both in separate calls to the list function. The filter supports lists of identifiers using the "in" command.

**Comment by mevdschee** [comment]
closed due to inactivity
