### ISSUE TITLE
Securing API for Plugin

### ISSUE THREAD

**Issue by IFeelYourPain** [mevdschee/php-crud-api#345]
I'm wanting to use this API in a Wordpress plugin, but I don't want anyone just posting info to the servers. Is there a way to only allow submission from Wordpress installations along with verifying the submission isn't created manually?

**Comment by mevdschee** [comment]
>Is there a way to only allow submission from Wordpress installations 
>along with verifying the submission isn't created manually?

Easiest is to use PHP (curl) as a client on Wordpress and write a htaccess on the API only allowing the server IP to post messages. I'm not aware of a secure alternative.

**Comment by pawelpodkowa** [comment]
I did a secure server side future, do lika @mevdschee  sad, its best way to secure api file with htaccess and do request from js to php server and than php do curl to the api file, works great.

**Comment by pawelpodkowa** [comment]
plus token of course betwen PHP cURL <-> Api file,

**Comment by IFeelYourPain** [comment]
Could they not then just write js to write to the php server which would then pass it to curl and essentially the api file?

**Comment by mevdschee** [comment]
@IFeelYourPain depends on the operations you allow to pass through.

**Comment by IFeelYourPain** [comment]
basically it performs a get on the process php file which sanitizes everything, sends it to the api through curl, and from there pushes it into the database. I can deny access to the api.php file through htaccess, and I can santize the input coming to process php file, I just want to make it so that only specific websites can pass information to them. I plan on setting up a token so that only websites with that token are permited, I just want to make sure they can not use that token and post information from anywhere but the website.

**Comment by mevdschee** [comment]
As I said.. I'm not aware of any fully secure alternative (from javascript). But probably your obfuscation scheme will bring you a long way :-)
