### ISSUE TITLE
How to wrap api with a php script to get access to data using only functions defined in the script? 

### ISSUE THREAD

**Issue by Denis-Evseev** [mevdschee/php-crud-api#346]
I am not professional in PHP and wonder if there is a reliable and efficient way to wrap the api with a php script to restrict access to data by using functions defined in the script? The api is awesome but I would like to make interactions between user and server more secure. As if you just call api.php it retrieves all tables and then a user can easily get access to each table and download data

I think the best way to prevent stilling data is to restrict access. The only solution which I managed to create so far:
```
	$request = explode('/', trim($_SERVER['PATH_INFO'],'/'));
	$method = preg_replace('/[^a-z0-9_]+/i','',array_shift($request));	
	$page = array_shift($request)+0;
```
	
$method contains a word specified after `api.php/**method**/query`
Then I just created several conditions like:

```
if($method == "search) {
// implementation of 
}
```

It seems to me it is no the best way of creating methods. 
Could you please advise how can I wrap the api with function but not spawn new conditions?

Many thanks!

**Comment by mevdschee** [comment]
I think I would either use the callbacks to modify the behavior or I would write custom commands in one or more separate PHP files. You can secure user-server interaction using SSL (over HTTPS), I do strongly recommend that. Obscuring functionality by renaming it is pointless IMHO, but I'm not sure that is what you are suggesting.

**Comment by Denis-Evseev** [comment]
Thank you mevdschee for the response, 
Do you have an example of using commands? How can I combine several request into one command?
I used the approach, which is specified in the question

If I use SSL + HTTPS will it hide interaction between client and server? The user won't get access to the data? Sorry, I just have never used it before

**Comment by mycaravam** [comment]
Sorry for late response, maybe i am totally wrong here but aren't the table_authorizers exactly for this issue, i.e. making the table more secure? Like (preventing access to a users table)
```	
'table_authorizer'=>function($cmd,$db,$tab)
	{
		if ($tab == "users"){
			return false;
		} else {
			return true;
		}
	}
```

**Comment by mevdschee** [comment]
>aren't the table_authorizers exactly for this issue, i.e. making the table more secure?

Yes, they are for security, but not to "make interactions between user and server more secure".
