### ISSUE TITLE
columns selecting

### ISSUE THREAD

**Issue by pawelpodkowa** [mevdschee/php-crud-api#348]
Hi!
There is possible to get speciffy columns in GET: api.php/posts/1 in specify target ?
tried like: api.php/posts/1?columns=posts.id,posts.name&transform=1 
but that gives me back still all columns.

**Comment by pawelpodkowa** [comment]
should i use filter ?

**Comment by rapgithub** [comment]
same here! any way to select columns to display?

**Comment by mevdschee** [comment]
The parameter "columns" has been renamed to "include".
