### ISSUE TITLE
Relations FK

### ISSUE THREAD

**Issue by pawelpodkowa** [mevdschee/php-crud-api#349]
Hi, 

got:

```
ALTER TABLE `survey`
  ADD CONSTRAINT `survey_ibfk_1` FOREIGN KEY (`status`) REFERENCES `survey_status_names` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Ograniczenia dla tabeli `survey_users`
--
ALTER TABLE `survey_users`
  ADD CONSTRAINT `survey_users_ibfk_1` FOREIGN KEY (`survey_id`) REFERENCES `survey` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `survey_users_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `survey_users_ibfk_3` FOREIGN KEY (`survey_access_names_id`) REFERENCES `survey_access_names` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Ograniczenia dla tabeli `users`
--
ALTER TABLE `users`
  ADD CONSTRAINT `access_name` FOREIGN KEY (`access_level`) REFERENCES `access_names` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;
```

And i do: 
 /users?include=survey,survey_access_names,survey_status_names&exclude=password&filter=id,eq,'.$id.''

my callback is: 
null

if i do: 
 /users?include=survey,survey_status_names&exclude=password&filter=id,eq,'.$id.''

that works, 
and problem is that when i use survey_access_names i should get an array survey_access_names_id which got object with access_survey_names (string). I understand that the status is inside the survey table so that FK works properly, but why if i link with fk id from survey_access_names_id from survey_users that not contain linked table, like: survey_access_names as array of survey_access_names_id

this is the not supporten multi fk ? sry for my english, please help with this.

**Comment by pawelpodkowa** [comment]
everytime when i use survey_access_names in include, the callback is null

**Comment by pawelpodkowa** [comment]
![obraz](https://user-images.githubusercontent.com/17589316/37060561-f01f0ae0-2190-11e8-94e2-003db0416247.png)

**Comment by mevdschee** [comment]
It does support multiple foreign keys... are there any errors in the log? When your remove "transform=1" do you get the right results?

**Comment by pawelpodkowa** [comment]
no, without &transform=1 i got everytime "data is null". Even when i do simple: users?include=access_names,survey = null
users?include=access_names,survey,survey_status_names,survey_access_names = null

with transform=1 works fine, but not contain survey_access_names, its funny becouse  when i use users?include=access_names,survey,survey_status_names&transform=1 that works fine, but even when i put survey_access_name i got null, even alone, like: 
users?include=access_names,survey,survey_access_names = null
what to do ? did you try do multiple FK ?

**Comment by pawelpodkowa** [comment]
![obraz](https://user-images.githubusercontent.com/17589316/37079640-902ea11a-21e3-11e8-99ec-cc7f51ed1085.png)

**Comment by pawelpodkowa** [comment]
only what i need is array of survey_access_names downthere :P

**Comment by pawelpodkowa** [comment]
any idea how to resolve that?

**Comment by pawelpodkowa** [comment]
and why if i remove transform option i got data is null ?

**Comment by pawelpodkowa** [comment]
@mevdschee any updates? any idea?

**Comment by mevdschee** [comment]
This should be fixed in v2. Can you confirm?
