### ISSUE TITLE
Filtering on tables with relationships

### ISSUE THREAD

**Issue by sutsurikeru1986** [mevdschee/php-crud-api#35]
Is it possible to apply multiple filters when tables are in a relationship?

For example:

http://localhost/api.php/posts,categories?filter[]=post_name,cs,Internet&&filter[]=categories.cat_name,eq,Internet

**Comment by mevdschee** [comment]
No, you will have to do 2 queries and use the "in" operand.

    http://localhost:8000/blog.php/categories?columns=id&filter[]=name,cs,a

resulting in 

    {"categories":{"columns":["id"],"records":[["1"],["2"]]}}

The you have to take that result and use it:

    http://localhost/blog.php/posts?filter[]=category_id,in,1,2

Resulting in the requested posts.

**Comment by sutsurikeru1986** [comment]
Ah that makes sense! Many thanks for the quick response - i know what i need to now
