### ISSUE TITLE
PUT request not working on webhost ipage.com help wanted

### ISSUE THREAD

**Issue by jeffrowsell** [mevdschee/php-crud-api#351]
API works great locally but not on my web host on ipage.com, everything works on the external host (GET,POST,DELETE) but not PUT requests.  For some reason I get back a 404 for PUT requests.  Any idea on what to check or tweak on my web host on ipage.com to fix the issue?  Do I need to tweak the .htaccess or php.ini in some way to allow PUT requests to work?   Thanks in advance.

**Comment by mevdschee** [comment]
It could be that your host does not allow put requests. You may work around this by using post requests and adding: `'method'=>$_GET['method'],` to the config. The you can specify "?method=put" in the url to work around this problem.

**Comment by pawelpodkowa** [comment]
the same was on one of polish hosting, be sure that Hosting company allows this type fo requests.

**Comment by jeffrowsell** [comment]
You are right, unfortunately my host doesn't support PUT requests.  In
regards to your work around, could you elaborate a bit more on where I put
this in the config and how I achieve this? Little confused on where I make
this change.

Thanks,
Jeff

**Comment by mevdschee** [comment]
Sure, put the method in the config as described in the readme and then use the extra get parameter on the url.

**Comment by jeffrowsell** [comment]
Thanks.  I updated the config as described and hopefully I did this change correctly.  Below is a snippet of what I have no with the extra line you mentioned to add:

// uncomment the lines below when running in stand-alone mode (credentials and hostname db etc. edited for this example):

$api = new PHP_CRUD_API(array(
	'dbengine'=>'MySQL',
	'hostname'=>'mywebhost.com',
	'username'=>'username',
	'password'=>'thepassword',
	'database'=>'apitest2',
	'method'=>$_GET['method'],  // added this line as per your previous comment
	'charset'=>'utf8mb4',
));
$api->executeCommand();

I have a simple test table called users that has 3 columns: id, uname, pwd and id is int autoincrement primary key, uname and pwd are varchar 30.  I'm using postman to test api functionality.  You mentioned I should do a POST call with ?method=put in the url to fake a put request.  So, assuming I want to change the uname on id=4 in the table I would generate a POST request with postman and the URL would be http://mywebhost.com/apitest2/api.php/users/4?method=put and then put uname=newusername in the body data?  Not sure if I did the config correctly or and that I'm making the call correctly.

Here's the JSON I get back when I call http://mywebshost.com/apitest2/api.php/users/4

{
"id": 4,
"uname": "hunter",
"pwd": "gecko"
}

Appreciate any help you can provide. Thanks for you help in advance!

Jeff

**Comment by mevdschee** [comment]
try:

    'method'=>strtoupper($_GET['method']),

I hope this helps

**Comment by jeffrowsell** [comment]
Awesome, that did the trick!  Worked great and thank you for your help!

Cheers,
Jeff
