### ISSUE TITLE
Combine columns for output in one single element alias name

### ISSUE THREAD

**Issue by rapgithub** [mevdschee/php-crud-api#353]
is there a way the api can combine columns for output I mean:

the JSON object usually look like this:

{ “table_name”: [ { “ID”: “1”, “CityCode”: “LDY”, “CityName”: “London”... } ] }

but what if I need to do this combine columns in a different output?

{ “table_name”: [ { “name”: “London, LDY” } ] }

thanks...

**Comment by mevdschee** [comment]
Thank you for your question. No, this is not supported, but you surely can do string concatenation in JavaScript. :-)
