### ISSUE TITLE
How to list records in a table using Angular 5?

### ISSUE THREAD

**Issue by leossmith** [mevdschee/php-crud-api#358]
I am trying to list the results of a call to a table using Angular 5, but my list is empty. I tried following the example for angular2 but as I am using a service.ts I can't figure out what to do.

This is my code:

```
import { Injectable } from '@angular/core';
import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import { Product } from './product';

import php_crud_api_transform from './lib/php_crud_api_transform.js';


@Injectable()
 
// Service for products data.


export class ProductService {
    
 
    // We need Http to talk to a remote server.
    constructor(private _http : Http){ }
 
    // Get list of products from remote server.
    readProducts(): Observable<Product[]>{
        return this._http
            .get("http://localhost/shop/v1/products")
            .map(res => php_crud_api_transform(res.json()));
    }
 
}
```

When I try to compile, I get this error:

ERROR in /Development/angular-crud-level-one/src/app/product.service.ts (8,36): Cannot find module './lib/php_crud_api_transform.js'.

Can you help me?

**Comment by mevdschee** [comment]
Apparently you are not able to load the "php_crud_api_transform" function from "./lib/php_crud_api_transform.js".

As a workaround you could remove all references to "php_crud_api_transform" and add "?transform=1" to the url.

**Comment by jledun** [comment]
As there's no "module.exports" in php_crud_api_transform.js, you should import it in your .angular-cli config or in index.html as a regular javascript function.
Then you should be able to use it in your code just like you did.

Not tested

**Comment by leossmith** [comment]
Using the ?transform=1 did the trick :) Thank you

`
readHotels(): Observable<Hotel[]> {
    return this._http
    .get("rest/api.php/hotel?transform=1")
            .map(res => res.json());
  }

`
