### ISSUE TITLE
How to join the same table twice

### ISSUE THREAD

**Issue by raz0r007** [mevdschee/php-crud-api#359]
Hi,
I've the following problem. This is my query:

**SELECT
     U1.Name as User1
     ,U2.Name as User2
     FROM Challenges c
     INNER JOIN Users U1 ON c.User1Id = U1.Id
     INNER JOIN Users U2 ON c.User2Id = U2.Id**
     
I need to join twice the same table because I need print Name of user1 and user2 from Challenges. In Challenges table, the FK is composed. User1Id and User2Id are the FK in Challenges table.
'Id' is PK in Users table.

I have understood that I don't need specify the ON clauses in the **filter[]** because the script deduces it through the information schema.

My question is, in this cases that i've two FKs in the Challenges table, how can I specify the filter columns for the joins? If it's impossible, what alternative I could use for resolve this problem? Or it's impossible?

Thanks

**Comment by mevdschee** [comment]
Thank you for your well written question. You are right and this is currently not possible.

It is one of the things v2 will definitely support. As a work around you can do multiple queries.

I hope this helps you a bit. Kind regards, Maurits

**Comment by raz0r007** [comment]
Thanks ! The v2 has any estimated date for launch?
I read about **php-sp-api** and it would be fantastic integrate the possibility to execute SP's in php-crud-api, something like:

GET http://localhost/api.php/procedure_name?param1=x&param2=y

It will resolves much complex queries and the api will be very powerful.
Please, think in it for the v2 :)
Regards

**Comment by mevdschee** [comment]
This is now supported in v2 (still beta). For the other suggestion I created #422.

**Comment by tafelnl** [comment]
> This is now supported in v2 (still beta). For the other suggestion I created #422.

You are referring to the double join right? Can you explain how this is done, because I don't understand?
