### ISSUE TITLE
Composite primary workaround?

### ISSUE THREAD

**Issue by peterphen** [mevdschee/php-crud-api#36]
Hi Mevdshee,

I'm aware of the limitation of the composite primary (you mentioned them in readme.md).

Is there any workaround to put (update) record with composite primary?

Tq

**Comment by mevdschee** [comment]
Can't you add an auto-increment key to the table and convert the primary key to an unique index?

**Comment by peterphen** [comment]
Backend developed by others, unless I can persuade them to add another id
pk autoincrement field. Other frontend developed in C# for the last few
years. Now I was asked to developed hybrid app to access the backend.

**Comment by mevdschee** [comment]
Well.. I'm not sure how I can help you. Do you have a suggestion?

**Comment by mevdschee** [comment]
Keep an eye out for my (similar) stored procedure project that I'll launch soon, it may help you.

Closing this issue for now.
