### ISSUE TITLE
How to use POST with foreign key?

### ISSUE THREAD

**Issue by mbnoimi** [mevdschee/php-crud-api#363]
Hi,

I've created this tiny db and I want to add a Student while I don't know the id of its School
![screenshot_2018-04-03_13-01-53](https://user-images.githubusercontent.com/284547/38243316-b10a9332-373f-11e8-9fff-b5d80d2e9c83.png)
I tried to use the following call but it keeps add school_id as 0.
```
https://mydomain.com/api.php/Student?include=School&filter=School.name,eq,Londra
```
How can I fix this problem?

![image](https://user-images.githubusercontent.com/284547/38243385-0559a2e8-3740-11e8-92bd-b76acb1e82f3.png)

**Comment by mevdschee** [comment]
Hi. Thank you for asking this question. Try:

    https://mydomain.com/api.php/School?include=Student&filter=School.name,eq,Londra

As filters are applied from the first (primary) table. I hope this helps.

**Comment by mbnoimi** [comment]
Thanks @mevdschee but the following adds a school! I want to add a student.

```
POST https://mydomain.com/api.php/School?include=Student&filter=School.name,eq,Londra
```

**Comment by mbnoimi** [comment]
@mevdschee  You meant using **filter** doen't affect on **POST**?

**Comment by mevdschee** [comment]
>filter doen't affect on POST?

@mbnoimi yeah.. afaik it doesn't

**Comment by mevdschee** [comment]
You want to add a student, so try:

    POST https://mydomain.com/api.php/Student

and post the following body:

    {"name":"student123","birthday":"2001-01-01T12:34:56Z"}

Maybe you did not understand that you need to post the data in the body and not in the filter?

**Comment by mbnoimi** [comment]
> Maybe you did not understand that you need to post the data in the body and not in the filter?

No I understand how to post the data but I want to make post with filter because in some cases I don't know the id of the school but I know its name.

**Comment by mevdschee** [comment]
>in some cases I don't know the id of the school but I know its name.

I understand your thinking, but a filter can - unfortunately - not help you in this case.

A workaround would be to do 2 requests, one to get the school and one to create the student.

**Comment by mbnoimi** [comment]
Thanks a lot @mevdschee

**Comment by mevdschee** [comment]
You are welcome, enjoy the software!
