### ISSUE TITLE
Question: Loading 1 Million Record Attributes

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#364]
I have 2 tables, one is the primary table that has 57578 records and the attributes table has 1296371 records, my attributes table stores the primary table record id to reference back via foreign key. 

**The Issue**
When loading the records from the primary table and including the attributes table via "include=" i run into a PHP fatal exhausted memory error.

I know this is from loading a lot of records at run time without any filters. Is there any way i could maybe work around this? I have to load the attributes via the include parameter.

Is this a bug or just due to the streaming nature of the API?

**Comment by mevdschee** [comment]
Thank you for your report.

>a PHP fatal exhausted memory error. 

Are you using transform=1?

If so, do you also get the memory problem when you don't use transform=1?

>Is this a bug or just due to the streaming nature of the API?

The server side transform negates the streaming nature of the API.

**Comment by mevdschee** [comment]
Does it help when you allow PHP to use more memory? Are you selecting any large columns/records? 
What is the current memory limit? What is the largest record that you have?

>Hi! I am Amy a full stack web developer with 8 years of experince under my belt.

@ubergeekzone you may want to fix that typo in your profile description: experince

**Comment by ubergeekzone** [comment]
@mevdschee so, table A has 57578 records and table B has 1296371 records, api is called "api/A?include=B" table A with all of table B records are loading, If i give it more memory the server just stops responding due to stress and causes slow load times.

btw: typo fixed, thanks for making me aware of it.

**Comment by mevdschee** [comment]
It will collect key values and keep those in memory. These values may use quite some memory on large datasets. Also your database may require quite some time to actually retrieve the data. Does it help to reverse the order and do `api/B?include=A`?

**Comment by kolchagov** [comment]
Just another proposal:
you may try to increase the memory limit into php.ini file:
memory_limit = 256M
or in your api.php:
ini_set('memory_limit', '256M');

**Comment by ubergeekzone** [comment]
@mevdschee it does not matter if I reverse the order and do `api/B?include=A` same error, What I think may need to be done here is query caching.

**Comment by ubergeekzone** [comment]
@mevdschee I have come up with a solution to rectify this issue. But require a little bit of assistance to implement this and I think this would be a quick addition to the API to extend the usage case. 

I have moved my attribute tables into columns within the primary table and named them a_attributes, b_attributes, etc.. the data is serialized using PHP, the issue is getting the unserialized data back via client side to be used. is there a simple way to add a parameter to the callback like ```?unserialize=a_attributes``` this would then return the data back into the json object outputted correctly. 

thanks
