### ISSUE TITLE
Update JSON Put returns 0

### ISSUE THREAD

**Issue by rofsky** [mevdschee/php-crud-api#37]
Hi Maurits, thanks for the great code. I do however have an issue. I have no problem using the script with post create, list, list transform etc. 

However when I attempt to do a PUT update with or without JSON I am not successful. Initially i was getting a 403 permission denied then realized Apache was not allowing PUT requests. I added an override in an .htaccess file and now I get a 200 with a 0 for the response. When I analyze the object it is properly encoded as a json object, and if I use a browser based REST tool, I also return the same result. 

Here is my object and ajax request: 

```
var DataToSend = new Object();
DataToSend = {  
	id : '115',
	year : '2009',
	year_end : '2014',
	make : 'Yamaha',
	model : 'YZF-R1',
	title : '2009-2014 Yamaha YZF-R1'
};

$.ajax({
	type: 'PUT',
	url: 'http://localhost/s/themes/Carbon/api.php/motorcycles/2',
	dataType: "json",
	data: JSON.stringify(DataToSend),
	success: function(data){
		alert(data);
	}
});	
```

Any idea what the problem could be?

Thank you in advance for your reply.

Arthur

**Comment by mevdschee** [comment]
The call returns "rows affected", could that be "0"?

**Comment by rofsky** [comment]
According to your documentation my understanding was that the 0 was rows affected. When I look at my data, it is not updated with the new values per the data object above.

**Comment by mevdschee** [comment]
You seem to post to primary key "2" with id "115". Are you sure this is what you expect/want?

**Comment by rofsky** [comment]
AHHH! very good. that must be my problem. While reading your documentation I was a bit confused in the example you have /2 in the URL, and I was under the impression that 2 is the command for update. I am guessing that is the problem. I will try again right now. Thank you so much!

**Comment by rofsky** [comment]
My guess is also that if I wanted to see the executed query for updateObject I can just return the sql on line 722 of api.php , per my question above. 

Thanks so much for the great code and documentation, prompt reply and kindness. Take care!

**Comment by mevdschee** [comment]
I'm glad I could help. Thank you for your kind words, have fun with the code!

**Comment by mevdschee** [comment]
NB: All three drivers have some commented out code to show the SQL executed in the function "query".
