### ISSUE TITLE
Read multiple doesn't work for me

### ISSUE THREAD

**Issue by jhuesser** [mevdschee/php-crud-api#372]
Hi, big thanks for your great work! I've used this on many of my projects!

The readme says i can read multiple records by calling
`../api.php/comments/1,2`
But when I do this, I only get
`Not found (object)`
But both records `1` and `2`exist in the database...

Can you help me? Thank you very much!

**Comment by mevdschee** [comment]
Well that is supposed to work. Can you read a single record?

**Comment by jhuesser** [comment]
Yes I can. When I try api.php/comments/1 and api.php/comments/2 I get the records.

**Comment by mevdschee** [comment]
Are you running the latest version? Did you run the tests? The test "testReadPosts" is testing that. Does it fail?

**Comment by jhuesser** [comment]
Hi, im really sorry, somehow an old version sneaked in in this project...

Updated it, and workes like a charm! Thank you for your great work, and sorry for this fail^^

**Comment by mevdschee** [comment]
>Thank you for your great work, and sorry ..

Don't be. Thank you for using the software and sharing your experience with it. Enjoy!
