### ISSUE TITLE
How to join tables with fk?

### ISSUE THREAD

**Issue by leossmith** [mevdschee/php-crud-api#374]
I have an issue trying to use the api in Angular 5. 

I am trying to get the values of a table of users which also contains a a foreign key defining the usergroup.

![image](https://user-images.githubusercontent.com/4300876/38984239-d7b54c66-43ce-11e8-84a9-55310eb52713.png)

The current result is:
`
"users": [
        {
            "id": 1,
            "user": "demo",
            "password": "demo",
            "email": "",
            "server": "http://localhost/gateway.php",
            "userGroup": 1,
            "hotel_id": 1
        }]
`

but I would like to have the userGroup title instead of just the fk. Is it possible?

**Comment by mevdschee** [comment]
Thank you for reaching out. You could use the "include=usergroups" get parameter in the URL to tell the script to include that entity.

**Comment by leossmith** [comment]
Thank you for the answer :) although I went with my own rest with phpslim, I will give it a try on feature projects.

**Comment by mevdschee** [comment]
Next version (v2) will be easy to integrate with SlimPHP
