### ISSUE TITLE
Filtering on relations

### ISSUE THREAD

**Issue by ratsey** [mevdschee/php-crud-api#379]
Is it possible to filter on multiple relations?

Using the documented example of blog posts, how would I query posts that include tags of both '1:Funny' *and* '2:Important' in their collection but exclude posts that have only one of those tags.  It should also return posts that have other tags, but those 2 must be present to be returned.

Thanks - love this API's simplicity.

**Comment by mevdschee** [comment]
@ratsey yes, but you would have to query the tags and include the posts (and not the other way around).
