### ISSUE TITLE
Multiple records to insert

### ISSUE THREAD

**Issue by kosvoski** [mevdschee/php-crud-api#38]
It is possible to send multiple records to insert ?
Sample:

    {
        "users": [{
            "columns": ["id", "user", "document", "pass"]
            }, {
            "records": [
                ["1", "leo", "1232465", "pass123"],
                ["2", "kosvoski", "3124576", "pass123"]
            ]
        }]
    }

**Comment by mevdschee** [comment]
No, it is not supported. You must do multiple requests. This may seem like a performance problem, but in most cases it is not. The script is very fast and HTTP1.1 will not make multiple connections.
