### ISSUE TITLE
Disable Cors Headers

### ISSUE THREAD

**Issue by joaodforce** [mevdschee/php-crud-api#383]
Ive been using the api.php for a while now, but recently I ran into a problem, because other services consume my API from other domains, and i have been asked to check about CORS, the issue here is that my server already deals with the CORS for another API that its on this same server.

And whenever a call is made to the API.php the response CORS headers coem doubled as the screenshot bellow shows.

I have looked into the documentation but have not found a way to turn that off unless i edit the API.php directly.

Is there a way to disable that right now? or would it be necessary to make one?

<img width="369" alt="captura de tela 2018-05-18 as 16 39 45" src="https://user-images.githubusercontent.com/9410916/40319955-6f65ddd8-5d00-11e8-96ca-148c1d90bac0.png">

**Comment by mevdschee** [comment]
Thank you for asking this question. I will register this as a feature request as this is currently not possible (using configuration). I'm pretty sure that version 2 (that will be released quite soon) will support this.

**Comment by mevdschee** [comment]
Version 2 now has this. You can test it from it's temporary address:

https://github.com/mevdschee/php-crud-api2

Let me know what you think about it.
