### ISSUE TITLE
SESSION Problem

### ISSUE THREAD

**Issue by raz0r007** [mevdschee/php-crud-api#387]
Hi
I'm having this error :

Notice: Undefined variable: _SESSION in /home/php-crud-api-master/auth.php on line 196
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Mjg0MTk4OTIsImV4cCI6MTUyODQxOTkyMn0.eOV6tbWX-I8Yoo1qrdDQyeO4cboSTp9yLYMf6USrQmk"/>

Why? I'm trying to implement login with token.
Regards

**Comment by mevdschee** [comment]
This is a problem with [php-crud-auth](https://github.com/mevdschee/php-api-auth), please report the issue there.
