### ISSUE TITLE
fetch single data with foreign key all fields structure

### ISSUE THREAD

**Issue by suxiaogang** [mevdschee/php-crud-api#388]
really nice job but confused on the huge README/api description and found nothing of my problem.
I was stucking on a ng1-app and just tried to something like `$state.go(detail) ` from a blog list page, just as your demo database structure.
What I expected to get is some json structure like this : 

`GET http://localhost/api.php/post/1`

```json
{
  "id": "1",
  "catogory" :
    {
      "id": "2",
      "name": "funny"
    },
  "content": "content"
}
```

How can I do this?

**Comment by suxiaogang** [comment]
what I've already done is 
```javascript
var id = $route.current.params.id;
var url = 'api.php/post/'+id;
$http({method: 'GET', url: url}).then(function(response) {
    console.log(response);
}, function errorCallback(response) {
    //
});
```

**Comment by mevdschee** [comment]
Thank you. Try this:

    var url = 'api.php/post/'+id+'?include=categories';

And see whether or not the output is usable to you.

**Comment by suxiaogang** [comment]
tks, your code works.
And parsing the result should be like this way:
```js
var url = 'api.php/post?filter=id,eq,'+id+'&include=category&transform=1';
$http({method: 'GET', url: url}).then(function(response) {
    $scope.model = response.data.post[0];
    console.log($scope.model);
});
```
