### ISSUE TITLE
Update Limitations

### ISSUE THREAD

**Issue by raz0r007** [mevdschee/php-crud-api#389]
Hi,
According to the documentation, I could update a register like this:

> PUT http://localhost/api.php/categories/2
> name=Internet+networking

Where "2" is the Id / PK of Categories table.
My question is, the unique way for edit registers is sending the PK? If I want to edit all registers in Categories, i would like to do something like this:

> PUT http://localhost/api.php/categories
> name=Internet+networking

But it doesn't work. Can I make a query with filters[] and update that? or the unique way is always sending the ID?

If the unique way is always sending the ID I should know always the ID that I want to edit, and if I want to edit 100 registers I should make 100 different httpRequests? Can't I use "IN" clause?

It doesn't work:

> PUT http://localhost/api.php/categories?filter=Id,in,1,2,3,4,5
> name=Internet+networking

The body is always NULL.
Thanks

**Comment by mevdschee** [comment]
Although what you are trying does not work, this does:

    PUT http://localhost/api.php/categories/1,2,3,4,5

With body:

    [{"name":"Internet networking"},{"name":"Internet networking"},{"name":"Internet networking"},{"name":"Internet networking"},{"name":"Internet networking"}]

I could accept the POST parameter format as a feature request as I would also expect that to work.

**Comment by raz0r007** [comment]
It would be good if I could construct a select query, something like when I use get to select information, and update the result of that query. Do you understand me?
For use filters[], in, eq, etc.

**Comment by mevdschee** [comment]
>Do you understand me?

Yes, but I disagree. For one because you shouldn't update the primary key, but also because you should not update what you did not (intend to) update/change. In version 2 filtering on updates is no longer supported.

**Comment by raz0r007** [comment]
I think the objetive of the API should be simulate as much as possible the real querys.
In a real query I can UPDATE registers with WHERE clause. Why in this API I can't do it?

Anyway, I respect your decision
Regards

**Comment by mevdschee** [comment]
Closed due to inactivity

**Comment by raz0r007** [comment]
@mevdschee i'm trying to do as you mentioned before:

`PUT http://localhost/api.php/categories/1,2,3,4,5`

But in my case, it doesn't works fine.
In my case, it updates only the register with id=1.
Are you sure that it's working fine? Can you test it?

My original url is:
`POST http://localhost/api.php/categories/1,2,3,4,5?csrf=XXXXXXX&method=PUT`

The body is: "Viewed=1"
