### ISSUE TITLE
HTTP Service Issue

### ISSUE THREAD

**Issue by Zlecktov** [mevdschee/php-crud-api#39]
The issue is on my end and I know this, but please give me some advice or something.   

The issue is that the way I plan to use the API and connect to it from can only use the GET and POST parameters and I was wondering if you had any way to still be able to modify all of the database in all ways as in by giving my query in my POSTs.   

LUA:
local Array = {
Action="UPDATE"; --Example
}

Which would give the API what it needed to know to set up and respond correctly without having to have full support of the HTTP Service.

**Comment by mevdschee** [comment]
Add config parameter:

    'method'=>$_GET['method'],

And POST the data to the url when you want to edit:

    http://localhost/api.php/posts/1?method=UPDATE

Or for delete use GET:

    http://localhost/api.php/posts/1?method=DELETE

Hope that helps!

**Comment by Zlecktov** [comment]
Worked perfectly thank you so much!

**Comment by mevdschee** [comment]
You are welcome, enjoy the code!
