### ISSUE TITLE
Jwt exp question

### ISSUE THREAD

**Issue by simonplm** [mevdschee/php-crud-api#390]
Hi. Is there a way to change the expiration of the jwt? Like if i want to allow user to have an option to be always logged in? Like a check box on the login form? Also, is it ok to store the jwt on the localstorage? Thanks

**Comment by mevdschee** [comment]
No.. JWT shoud not be used as a session cookie as it is lacking the Secure and HttpOnly flags. It can be used for a limited time to traverse domain limits.

**Comment by mevdschee** [comment]
closed due to inactivity
