### ISSUE TITLE
Question HowTo: use input_sanitizer to edit values

### ISSUE THREAD

**Issue by lennertholvoet** [mevdschee/php-crud-api#391]
I would need to edit how the values of a result look like, when using a GET request. (This could be html_entity_decode, utf_8_decode, add a string to the value... depending on which column gets requested.

I tried (based on the documentation and other issues), but this doesn't seem to work
````
'input_sanitizer'=>function($action,$database,$table,$column,$type,$value) { 
    if ( $column=='content' && $table == 'localeContent'){
        $value =  $value . ' add foo';
            return $value;
         } 
     },
````
Could someone give me a nudge in the right direction? Thanks!

**Comment by mycaravam** [comment]
I'm not sure but i think your code as it is would append " add foo" in the best case if you insert some input via api . You maybe want to manipulate the output not the input.

**Comment by lennertholvoet** [comment]
Thanks! Sounds logical (it's not like INPUT_sanitizer isn't logically named... Silly me.)
But I still have some difficulties getting the output. I tried using 'after' and 'before' , but my output is blank there (even when I try putting the output in a text-file, eg. ``'before'=>function(&$cmd,&$db,&$tab,&$id,&$in) { file_put_contents('before.txt', $in); },``), yet I see the correct output in Postman. So I was wondering which callback function I should use, to edit the output (so it shows up in my results).

**Comment by lennertholvoet** [comment]
I think you're right, reading this comment on one of the issues: 

> Thank you for your request. I understand this need and it is currently not supported. I expect v2 to contain an after handler that allows this kind of modification.
https://github.com/mevdschee/php-crud-api/issues/352#issuecomment-373480929

**Comment by mevdschee** [comment]
>I think you're right

Yes you are.

**Comment by lennertholvoet** [comment]
Thanks for the update @mevdschee 
I will now try and add this modification to php_crud_api_transform

**Comment by mevdschee** [comment]
Version 2 will have a middleware approach for all commands (also list) and will allow modification of any request and response. WIP here: https://github.com/mevdschee/php-crud-api2
