### ISSUE TITLE
Filter invisible chars from Output

### ISSUE THREAD

**Issue by mycaravam** [mevdschee/php-crud-api#392]
Hi,
my client often just pastes text from Word etc in inputfields and leaves me with a database cluttered with \u2028 for example. The thing is, you often only see these invisible chars on Windows Chrome, not on Chrome Linux or OSX.

I already installed an inputfilter for new content in my app but still having trouble removing the chars from old entries.

My question: how can I filter these chars from output?

My idea was to implement
```
$object = preg_replace('/[^\x20-\x7e\xa1-\xff]+/u', ' ', $object);
````
in the php_crud_api_transform function (line 2188) but the regex destroys the output at some point.
I would be grateful for a small hint.

And thanks so much for this great software.

**Comment by mevdschee** [comment]
>My question: how can I filter these chars from output?

You shouldn't. You should fix the data in the database, not the output. Use any tool you like for that.

**Comment by mycaravam** [comment]
That's what i thought, i think this can be closed. Thx.
