### ISSUE TITLE
Not found (entity) (PostgreSQL)

### ISSUE THREAD

**Issue by marcus-at-localhorst** [mevdschee/php-crud-api#394]
I get this error and I boiled it down to this statement: https://github.com/mevdschee/php-crud-api/blob/master/api.php#L260 (I was reading #17 and #2)

If I run the `reflect_table` statement in Adminer I get no records, since I don't have a column `table_schema= public`. If I remove that line the query returns the table_name.

I removed `table_schema= public` from all other queries.

Edit: I got the same Errors like in #149 

`ERROR: relation "attributes" does not exist LINE 1: SELECT * FROM "attributes" WHERE 1=2;`

Apparently, fetchFields needs the db schema (see https://stackoverflow.com/a/11421136/814031) .
either like this:
```php
public function fetchFields($table,$database) {
  $result = $this->query('SELECT * FROM !.! WHERE 1=2;',array($database,$table));
```

or 

```php
public function fetchFields($table,$database) {
  $result = $this->query('SET search_path TO !,public;SELECT * FROM ! WHERE 1=2;',array($database,$table));
```

Extending all `fetchFields` related functions with the $database param, finally gives me results.
I've never worked with PostgreSQL before, so I don't know if I setup something wrong (I'm on windows 10, Xampp, php 5.6)

**Comment by mevdschee** [comment]
Thank you for reaching out. It seems your tables are not in the public schema, could that be? Did you run the tests? Do these work?

**Comment by marcus-at-localhorst** [comment]
They are not in the public schema, that's correct and that's how the former devs, set up the postgres db server.

![chrome_2018-07-08_12-27-37](https://user-images.githubusercontent.com/1337223/42418901-93a55834-82aa-11e8-9066-9d916f4b9df6.png)

**Comment by mevdschee** [comment]
You may although the database or the user and set the default schema, as described here: https://stackoverflow.com/a/4185710

**Comment by marcus-at-localhorst** [comment]
So my issues stem from a suboptimal postgres db setting? (because it seems all other problems with `fetchFields`, described above, are related to the missing schema. I try to find out more about postgres.

Your link explains how to set the search_path with alter the DB.

It should be possible to do it on the fly with `SET search_path TO mmab, public` from the script, right?
But only for each statement and is it possible to do it globally for Postgres?

Sorry, I guess this is not necessarily related to your script anymore.
If you have an idea, I appreciate any hint.

**Comment by mevdschee** [comment]
You could make a new user with a different "search_path" (a.k.a. default schema) and let the script use that user.

**Comment by marcus-at-localhorst** [comment]
Thank you.
