### ISSUE TITLE
Version being misreported?

### ISSUE THREAD

**Issue by bigteejay** [mevdschee/php-crud-api#395]
https://github.com/mevdschee/php-crud-api/blob/2637fd8f92872bde91eea236761a3e786a77160f/api.php#L2358

During an InfoSec review, it was pointed out that the version of the API reported is "1.0.0" in the Swagger UI (though it was updated.)  It seems that this is incorrect (if it is meant to represent the version of the API itself.)  Are we misinterpreting what that value is supposed to represent?

![image](https://user-images.githubusercontent.com/14826513/42536979-78cbb0cc-8448-11e8-8674-512e9ccad9a9.png)

Apologies if this is already reported (I didn't find it searching through issues for the word "version").

**Comment by mevdschee** [comment]
This is fixed in v2. The info block is now configurable in the configuration. Let me know what you think.
