### ISSUE TITLE
Remove table name

### ISSUE THREAD

**Issue by nicdnepr** [mevdschee/php-crud-api#396]
`GET http://localhost/api.php/categories?transform=1`
it returns `{"categories":[{"id":1,"name":"Internet"},{"id":3,"name":"Web development"}]}`
How can I remove "categories" without using angular?

**Comment by mycaravam** [comment]
It is possible, but not sure if it would work as expected. Search for `$tree[$name] = $get_objects($tables,$name);` in api.php and replace it with `$tree = $get_objects($tables,$name);`.
This will modify the transformation function, so it only works with `?transform=1`.
Good luck with the debugging.
