### ISSUE TITLE
Support custom table and column mapper

### ISSUE THREAD

**Issue by nicdnepr** [mevdschee/php-crud-api#397]
Is it possible to write mapper for `api.php` to return changed data?
For example I have database with `table1` with columns `column1, column2`
I create script `my_api.php` and call it like `my_api.php/my_table`
Inside `my_api.php` I need catch param `my_table` or any other passed params like `filter` and then run `api.php/table1` and pass params
Then return changed columns like [{"columnA":1, "columnB":2}]

**Comment by nicdnepr** [comment]
What is not clear?
I need use aliases for database table and column
I have table `users` but I want call `api.php/customers` to get records from table `users`
Table `users` has column `f_name` but I want return data with column `first_name` like `[{"first_name":"Alex"}]`

**Comment by nicdnepr** [comment]
Any idea or example?

**Comment by mevdschee** [comment]
In v1 you can try the "before" and "after" filters to modify all (non-list) requests. In v2 you can write middleware to do this. Note that v2 is work in progress and can be found here (temporary):

https://github.com/mevdschee/php-crud-api2

I don't know when it will be ready for release. It is going slower than I hoped.

**Comment by nicdnepr** [comment]
`before` is not fit because it runs after call `getParameters`
for example if I run `api.php/not_exists_table` callback `before` not runs

**Comment by mevdschee** [comment]
I have registered support for a custom mapper as a feature request for v2.

**Comment by mevdschee** [comment]
See also #313

**Comment by mevdschee** [comment]
There is a mapper branch that may be merged into the next minor release.
