### ISSUE TITLE
API NOT WORKING ONLINE IN SITE

### ISSUE THREAD

**Issue by dksami** [mevdschee/php-crud-api#398]
in https the api is not working its showing me that the page is not found but in http its not working either but with different error and this time it is not showing any errors 
 Your see here https://imgur.com/a/wg3bm2e

Here is the link www.dashboards.tk/api.php

**Comment by mycaravam** [comment]
This maybe not related to the software. You may want to check your server error logs.

**Comment by dksami** [comment]
Well i have fixed the preivious problem through my hosting provider . But i
am not getting any response still if you go to www.dashboards.tk/api.php/

**Comment by mycaravam** [comment]
Its hard to guess from a blank page what did went wrong. You need more feedback from your server. Maybe adding this  
```
    // Error handling
    ini_set('display_errors', 1);
    error_reporting(E_ALL);
```
on top of your api.php can give you more insight what is happening...

**Comment by dksami** [comment]
okay, it's fixed. I didn't uncomment the bottom execute line.

**Comment by mycaravam** [comment]
Maybe you want to close the issue if it's  resolved.
