### ISSUE TITLE
Loopback style filters

### ISSUE THREAD

**Issue by jledun** [mevdschee/php-crud-api#401]
Sometimes I can't use IBM Loopback to build REST api on servers because node.js is not always supported by host providers. That's why I'm interested in your php-crud-api project.

In order to use the same front-end that I use with IBM Loopback, would it be possible to get an alternative filters format as a json objects joined in GET url ?

More details about Loopback filters [here](https://loopback.io/doc/en/lb3/Querying-data.html "IBM Loopback : Querying data").

example of IBM Loopback filter :

```json
{
  "where": {
    "and": [
      {"gt": {"column1": 40}},
      {"column2": "example"}
    ]
  }, "limit": 50,
  "order": "column3 ASC"
}
```

Then the url would be : 

```url
GET https://www.example.com/api?filter={"where":{"and":[{"gt":{"column1":40}},{"column2":"example"}]},"limit":50,"order":"column3 ASC"}
```

Could we build a kind of filter adapter which could transform a defined filter format to php-crud-api filter format ?

Sorry for my bad language,

Regards,

Julien Ledun
IO Systems, France

**Comment by mycaravam** [comment]
First you have to know, that the v1 version of the API don't support multiple filter, so maybe you want to checkout the [v2](https://github.com/mevdschee/php-crud-api2) first. If that isn't a problem you want to take a closer look at the filter mechanics:

1.) Extract Parameter from get with
```
	protected function getParameters($settings) {
		extract($settings);
...
                $filters   = $this->parseGetParameterArray($get, 'filter', false);
...

```
2.) Process filter parameter
```
	protected function processFiltersParameter($tables,$satisfy,$filterStrings) {
		$filters = array();
		$this->addFilters($filters,$tables[0],$satisfy,$filterStrings);
		return $filters;
	}
```
3.) Add Filters 
```
	public function addFilters(&$filters,$table,$satisfy,$filterStrings) {
		if ($filterStrings) {
			...
					$this->addFilter($filters,$t,$and,$f,$comparator,$value);
				}
			}
		}
	}
```
4.) Add Filter 
```
	public function addFilter(&$filters,$table,$and,$field,$comparator,$value) {
..
		$filter = $this->convertFilter($field,$comparator,$value);
		if ($filter) $filters[$table][$and][] = $filter;
	}
```
5.) Translate filter to SQL
```
	protected function convertFilter($field, $comparator, $value) {
		$result = $this->db->convertFilter($field,$comparator,$value);
...
					case 'cs': return array('! LIKE ?',$field,'%'.$this->db->likeEscape($value).'%');
```
This returning string will be added to the SQL query.

So, what you can do is to read your filter object and transform it in a way, that the processFiltersParameter() function can route the single parts to the final query.

**Comment by jledun** [comment]
Ok, thank you very much for your answer, I'll check that when I'll have time.

:+1:
