### ISSUE TITLE
V1 csrf expiration

### ISSUE THREAD

**Issue by simonplm** [mevdschee/php-crud-api#408]
Hey man. I just want to know how can i extend the csrf expiration. Like if i want to make it 8 hours Longer. How can i do that? Thanks. Oh btw, good luck to you on the v2. We stupid people who dont know php appreciate your work big time.

**Comment by mevdschee** [comment]
It is limited by the PHP ini "session.cookie_lifetime" variable and the "session.gc_maxlifetime" variable.

**Comment by simonplm** [comment]
I see it now. Thank you very much.
