### ISSUE TITLE
Support for views

### ISSUE THREAD

**Issue by janezn31** [mevdschee/php-crud-api#409]
Hi,
I’ve tried to use php-crud-api(v2) with views and it seems it’s not supported. Could this be implemented? Any plans for future release? 
Btw: great work, love it!

**Comment by mevdschee** [comment]
Thank you for your kind words. Views are not yet implemented, but will be added to v2.

**Comment by mevdschee** [comment]
Related to #29

**Comment by mevdschee** [comment]
Latest master should now support views.
