### ISSUE TITLE
New comand Limit

### ISSUE THREAD

**Issue by Radigar** [mevdschee/php-crud-api#41]
First of all nice api, congratulations to the coder. One question: Can be possible add the SQL command "LIMIT" to restrict the response?

**Example**: Last 10 products added in my shopping car

**Comment by mevdschee** [comment]
yes.. this is done using a combination of the "page" and "order" parameter (you must use both):

    GET http://localhost/api.php/shopping_cart_products?order=id&page=1,20

Like that, is that clear?

**Comment by Radigar** [comment]
Yes this combination it's ok for limit the query in order descending but if you want order by date and order ascending for example:

`GET http://localhost/api.php/shopping_cart_products?order=created,asc&page=1,20`

This call return the 20 oldest products but no the last 20  products ordered by date, or  I'm wrong with this?

Thanks for your help @mevdschee

**Comment by mevdschee** [comment]
If you want the oldest records you need to sort in descending order. It you want to present these in your front end in ascending order then you should reverse the array after receiving it. Does that help?

**Comment by Radigar** [comment]
Oh ok it's true, i can reverse the array this way. I thought that the API could bring me this already ordered.

Thank for your help!

**Comment by mevdschee** [comment]
It does not because it is not included in SQL and the API is streaming the data, not keeping it in memory for reordering before sending it out. Kind regards, Maurits

**Comment by bhavesh-vyas** [comment]
What!  This api doesn't allow to get desc sorted with pagination?

You mean to achieve this we have to get all data without pagination and
then reverse it in local?

-Bhavesh

**Comment by mevdschee** [comment]
No, that is not true. You can get it with pagination, but have to reverse it local.

**Comment by mevdschee** [comment]
Does this make things clear? Can I close this issue now?
