### ISSUE TITLE
How to get datas with filter using the +

### ISSUE THREAD

**Issue by manucr619** [mevdschee/php-crud-api#411]
I used the filter syntax and filtered a blood group as ab+. It's showing me as empty records . Can anyone help me out ?? 

{"records":[]}

**Comment by mevdschee** [comment]
You should "url encode" the "+" as "%2B". See: https://www.urlencoder.org/

**Comment by manucr619** [comment]
omg its little tough right, every time I need to encode and send?

**Comment by mevdschee** [comment]
Yes, any url variable needs to be url encoded. This is not my idea. This is in the HTTP standard.
