### ISSUE TITLE
display only selected columns? 

### ISSUE THREAD

**Issue by rapgithub** [mevdschee/php-crud-api#418]
I tried to use columns= to display only some columns and it is not working it shows always all columns for the table... 

Is the a way to limit the columns to show to selected columns instead of showing all table columns?

thanks

**Comment by mevdschee** [comment]
Thank you for asking this question. What was not clear from the answers in #417 and #348? the parameter "columns=" is renamed to "include=" and that should do it for you in v2.

**Comment by rapgithub** [comment]
Yes it works include and I see you have exclude also and that is great the only issue I am having right now how do you set well include or exclude when you have joins?

In addresses I need also exclude some columns too... how the API knows which table I need to exclude or include columns? 

records/users/?exclude=is_active&join=addresses ....

thanks

**Comment by rapgithub** [comment]
I think I found how to make it work:

```php
records/users/?exclude=users.is_active, addresses.is_active&join=addresses
```

Big thanks
