### ISSUE TITLE
basicAuth not working for me 

### ISSUE THREAD

**Issue by simonplm** [mevdschee/php-crud-api#420]
i quite don't understand how to make it work. i already configure the htaccess abd htpasswd but it still giving me a "Access denied for 'admin" message. my middlewares parameter btw is like this, 	'middlewares' => 'basicAuth',

**Comment by mevdschee** [comment]
You don't need .htaccess. Just create a htpasswd file with "username:password" entries in plain text. The software will encrypt it.

**Comment by simonplm** [comment]
Oh, I thought it's the same with .htaccess and .htpasswd. Yeah, I get it now. I put the base64 value of my password in the htpasswd file, that's why it's not working with the api. Weird that when using the Restlet Client chrome app it's actually working, but using axios it's giving me 401 error and cross-origin error.
