### ISSUE TITLE
unable to get a response from server with basic auth

### ISSUE THREAD

**Issue by electather** [mevdschee/php-crud-api#421]
Hi, thanks for the great project, it's a lifesaver. But I encountered a problem with it recently.
when I try to send a request using the Android networking libraries, I face the following problem 

- as long as the credentials provided is wrong, I get an error object (which is what I expected) 
- if I enter the **right username password combination**, I get a "null" body with **status 0.** 

The odd thing is it works fine with the postman and my java desktop client, and I wouldn't have even considered posting an issue here if it weren't for #14 and #249. 
I seriously don't understand why the server would send this response and why this happens only in my android client. 
ps. I've tried everything clientside on my android app (changed networking libraries, connection quality and testing other API s) and it's working fine in all of them.

**Comment by mevdschee** [comment]
Thank you for your kind words. Which version are you using? Can you proxy and record the android communication using charles/fiddler/paros proxy? Maybe we can find out why this is happening.

**Comment by electather** [comment]
I think the problem was with the android library I was using, it's fixed now. thanks
