### ISSUE TITLE
Support JWT authentication in v2 of the API

### ISSUE THREAD

**Issue by rapgithub** [mevdschee/php-crud-api#423]
how do you implement the auth for v2 of the API.php ?
I see that the PHP-API-AUTH it is for v1 only implemented...

thanks

**Comment by mevdschee** [comment]
Hi, v2 supports basic auth (to be documented properly) and does not yet support JWT based auth (it will be added before it is out of beta).

**Comment by rapgithub** [comment]
thank you I tried to use it without success and now I know it is time to wait for the official release... for me I need to get it working with JWT... that will be perfect... in the moment I am using this for JWT for generating JWT with php ... [https://tqdev.com/2016-jwt-implementation-in-php](url) 
but it is not perfect I need to validate also any Ajax calls with the API and restrict the type POST for some tables...

I am sending the JWT in my Ajax in the header... and receiving it in the api.php with 

```php
	$headers = apache_request_headers();
   	$jwt = (isset($headers['Authorization'])) ? $headers['Authorization'] : false;
...
```

I hope JWT will be added soon! :) thanks

**Comment by rapgithub** [comment]
I think I will use this library very simple to add and many features maybe it will be a good add for the API too..

https://github.com/lcobucci/jwt [https://github.com/lcobucci/jwt](url)

**Comment by mevdschee** [comment]
Can you verify whether the latest master works for you? It should support JWT through middleware without any dependencies.
