### ISSUE TITLE
Composer integration for V2

### ISSUE THREAD

**Issue by rapgithub** [mevdschee/php-crud-api#424]
Composer integration v2?

Do you know how to add php-crud-api to my composer.json manually because I do not see an installation for to do it? 

I will like to use the library https://github.com/lcobucci/jwt  that it is light and fast to implement JWT and I will like to add the php-crud-api to my composer.json and composer.lock to work together with it...

any tips? thanks

**Comment by mevdschee** [comment]
Why is composer not working for you?

**Comment by rapgithub** [comment]
composer is working when installing any dependencies libraries but it is not working with php-crud-api...  is there a way to have it since vendor folder manually? I do not see any installation method using composer of php-crud-api... thanks

**Comment by mevdschee** [comment]
Can you share the commands you execute and the errors you get while trying to use composer?

**Comment by rapgithub** [comment]
where is the composer installer link to run in the console? 

I installed manually inside the vendor folder and modified the composer.json to include it there and even if I installed manually and it does not work... the namespaces are not found... all the time no matter what you try... :(

**Comment by mevdschee** [comment]
>where is the composer installer link to run in the console?

To retrieve the composer run:

```
wget https://getcomposer.org/composer.phar
```

Then to execute the composer run:

```
php composer.phar
```

To add this tool via composer run:

```
php composer.phar require mevdschee/php-crud-api
```

Let me know how this goes.

**Comment by rapgithub** [comment]
thanks let you know...

**Comment by mevdschee** [comment]
Any update?

**Comment by mevdschee** [comment]
I did some improvements to "`composer.json`". I hope it helps.

**Comment by mevdschee** [comment]
If you need further help, please open another issue.
