### ISSUE TITLE
getPk() must be an instance of ReflectedColumn, null returned

### ISSUE THREAD

**Issue by maxmenGMK** [mevdschee/php-crud-api#425]
Hi!
Have ubuntu 18, nginx/1.14.0 (Ubuntu), PHP 7.2.7
Nginx config i get from the other answer to previous issues and it seems good:

```
server {
    listen 80 default_server;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
        server_name _;
        #return 301 https://$server_name$request_uri;
        root /var/www/html/;
        index index.php index.htm index.html;
    location / {
	try_files $uri $uri/ =404;
    }

#    location /testapi/ {
#	fastcgi_index api.php;
#	rewrite ^/api(.*)$ /testapi/api.php$1 last;
#    }

    location ~ [^/]\.php(/|$) {
	fastcgi_split_path_info ^(.+.php)(/.+)$;
	try_files $fastcgi_script_name =404;
	set $path_info $fastcgi_path_info;
	fastcgi_param PATH_INFO $path_info;
	fastcgi_index index.php;
	include fastcgi.conf;
	fastcgi_pass unix:/run/php/php7.2-fpm.sock;
	
    }
```

run php test:

```
php test.php
mysql: 81 tests ran in 1836 ms, 0 failed
pgsql: skipped, driver not loaded
sqlsrv: skipped, driver not loaded
```

But i cant to use such nice api with my mysql db. I have 2 tables in database - "test" my own and "posts" from example and try to put to and get from the table but there no result.

http://192.168.50.44/testapi/api.php/recodrs/test/ gives:

{"code":1000,"message":"Route '\/recodrs\/test\/' not found"}

http://192.168.50.44/testapi/api.php/test/ gives 

{"code":1000,"message":"Route '\/test\/' not found"}

http://192.168.50.44/testapi/api.php gives 

{"code":1000,"message":"Route '' not found"}
 
http://192.168.50.44/testapi/api.php/records/posts gives

{"code":9999,"message":"Return value of Tqdev\\PhpCrudApi\\ReflectedTable::getPk() must be an instance of Tqdev\\PhpCrudApi\\ReflectedColumn, null returned"}

What is wrong?

**Comment by mevdschee** [comment]
>http://192.168.50.44/testapi/api.php/recodrs/test/

"recodrs" should be "records", seems to be a typo

>http://192.168.50.44/testapi/api.php/records/posts

Seems like there is no primary key in the posts table, could that be?

**Comment by maxmenGMK** [comment]
> Seems like there is no primary key in the posts table, could that be?
id is the primary key
MariaDB [6004]> desc posts;
+---------+------------------+------+-----+---------+----------------+
| Field   | Type             | Null | Key | Default | Extra          |
+---------+------------------+------+-----+---------+----------------+
| id      | int(20) unsigned | NO   | PRI | NULL    | auto_increment |
| title   | text             | NO   |     | NULL    |                |
| content | text             | NO   |     | NULL    |                |
| created | text             | NO   |     | NULL    |                |
+---------+------------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)

**Comment by mevdschee** [comment]
Can you post a create table statement, so that I can reproduce this error locally?

**Comment by maxmenGMK** [comment]
> Can you post a "create table" statement, so that I can reproduce this error locally?
I create my table with phpmyadmin

> Are you sure you are running the latest version?

Yes, i am sure - i just clone it again and the result the same.

**Comment by mevdschee** [comment]
Did you solve the problem already? If not, can you help me reproduce it? What OS and php version are you on?

**Comment by mevdschee** [comment]
I tried to reproduce with MariaDB 10.1.36 and PHP 7.2.10, but with no luck.

**Comment by mevdschee** [comment]
Can you help me reproduce?

**Comment by mevdschee** [comment]
I'm sorry, but I can't reproduce.
