### ISSUE TITLE
Document authentication usage with example

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#427]
There are many tickets of people that need help with the authentication implementation. We need a document and example of how to do this (in v2).

**Comment by EDDYMENS** [comment]
Been going through the issues are you referring to  DB based authentication?

**Comment by mevdschee** [comment]
I think docs about file based auth would already help.

**Comment by mevdschee** [comment]
I'm not sure what you are asking. Any contribution to the documentation would be very welcome and I would love to review and merge it.

**Comment by mevdschee** [comment]
I have added an Auth0 and an "auth.php" example and tested it thoroughly.

The file "auth.php" can be found here: https://github.com/mevdschee/php-api-auth
