### ISSUE TITLE
Feature Request - access next/previous object values on a single returned object

### ISSUE THREAD

**Issue by sutsurikeru1986** [mevdschee/php-crud-api#43]
I've previously switched to using this php-crud-api over WordPress - is it possible to do currently or would it be a feature request for the following:

If you are on a blog post and you get the single returned object (as expected!) - could you access the next / previous object? Or a value from the next / previous object (if one is available of-course!)?

``

**Comment by mevdschee** [comment]
Hey, isn't that a "find" with "post date" bigger or smaller then "current post date" order by "post date" and a "limit" set to "1"?

**Comment by sutsurikeru1986** [comment]
hmm let me see if i can create a custom controller in angular to get the next and previous object in the list

**Comment by mevdschee** [comment]
Please let me know whether or not this worked for you. If not, I'll reopen the issue.
