### ISSUE TITLE
Generate API documentation using OpenAPI tools

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#431]
This is a v1 feature that has not yet been ported.

**Comment by luisrock** [comment]
Would you help me generate documentation with openapi? I don't know how to begin. All I did was visiting "/api.php/openapi", but I got:

{
  "code": 9999,
  "message": "Unsupported type 'year' for driver 'mysql'"
}

By the way, API was successfully created.

**Comment by mevdschee** [comment]
@luisrock I created a new issue for you, see: #499
