### ISSUE TITLE
Issue reflecting SQL Server PK

### ISSUE THREAD

**Issue by etcook** [mevdschee/php-crud-api#435]
`{"code":9999,"message":"Return value of Tqdev\\PhpCrudApi\\ReflectedTable::getPk() must be an instance of Tqdev\\PhpCrudApi\\ReflectedColumn, null returned"}`

The PK does not seem to be resolving properly on many of my tables. I believe this is a result of a composite key, which is not supported.

Is there any way to override the reflection or short circuit it, and only allow filtered GETs?

**Comment by mevdschee** [comment]
Thank you for reporting this. I reproduced, fixed and added a test case for your issue.
