### ISSUE TITLE
Possible typo in api.php at line 1617

### ISSUE THREAD

**Issue by rkondner** [mevdschee/php-crud-api#436]
A complete PHP newbie here but is $opertor a typo at line 1617 in api.php?

The is in the function:
   private function hasSpatialArgument(String $operator): bool

The next line uses $opertor

Would that code even compile? I am too much a newbie to even suggest an issue.

Bob K.

**Comment by mevdschee** [comment]
Thank you Bob K! Great find.

**Comment by rkondner** [comment]
Wow. Proves that even a blind pig can find an acorn!

 

Question: How does something like that simple typo get into a distribution? Not that I have never done such but I have been known to be a lazy good for nothing programmer😊

 

Bob K.

**Comment by mevdschee** [comment]
Hi Bob,

PHP is not a compiled language and this specific function had no test written for it (shame on me). Another factor is that this is a complete rewrite and still in beta, so not many people are using it yet.

I would be very grateful if you would contribute more, preferably by finding more bugs or adding test cases.

Thank you again!

Maurits

**Comment by rkondner** [comment]
Maurits,

 

All I did was open it up in PHPStorm and I saw the red flags. I see one more , see below. Line 3283

 

What does Build.php do? Does it put together the api.php from the src files in the Tqdev directory? Wow that is a pretty cool way of putting together a lib. Maybe it is standard fair in Linux but for a Windows guy it is different. I am really just a hardware guy buy you can see some of my code at www.partsync.com <http://www.partsync.com> .

 

My goal is to put some of that CADish type logic into a format that regular folks can use. Someone should be able to add such functions in anything, even WordPress. So I am looking around at PHP frameworks now.   Any suggestions? Zend or Cake or something else?

 

If I need help do you sell consulting time?

 

Thanks,

Bob

**Comment by mevdschee** [comment]
Hi Bob,

>I see one more , see below. Line 3283

Thank you!

>What does Build.php do? Does it put together the api.php from the src files in the Tqdev directory? Wow that is a pretty cool way of putting together a lib.

Yeah.. it does. It is indeed custom and not really needed (as most people use an autoloader).

Kind regards,

Maurits

**Comment by mevdschee** [comment]
I have applied PHPStorm's static code analysis tools and fixed some more issues :-)

**Comment by rkondner** [comment]
Hi,

 

So I have it running on XAMPP doing data access. Working fine.

 

Thanks,

Bob Kondner

**Comment by rkondner** [comment]
Hi,

 

I have been using api.php under XAMPP and it has been working fine.

 

I just moved it up to a shared server on my ISP Dreamhost. I get a “Server Error 500”

 

I attached a PHP Info dump, they are running PHP Ver 7.0.30

 

Can you possibly point me in the right direction?

 

Thanks,

Bob Kondner

**Comment by mevdschee** [comment]
I did not receive your attachment. Can you post the attached php info dump here?

**Comment by mevdschee** [comment]
Also please open a new issue for a each new problem. That will keep things organized.
