### ISSUE TITLE
Way to execute a raw query

### ISSUE THREAD

**Issue by jsantari** [mevdschee/php-crud-api#44]
Is there any way to execute a query such as select distinct city ...

**Comment by mevdschee** [comment]
Take a look at: https://github.com/mevdschee/php-sp-api

It is made for that purpose.

**Comment by jsantari** [comment]
Well Ok thanks, I was really asking if there was a way to do it with php-crud-api though.

**Comment by mevdschee** [comment]
Raw queries are and will not be supported, because that is hard to keep secure (unless you write a full SQL parser). Keywords like distinct can easily be added to the API functionality, but I'm not sure whether or not we should want that as it is somewhat breaking the REST idea.
