### ISSUE TITLE
getPk() must be an instance of ReflectedColumn

### ISSUE THREAD

**Issue by rhsumner** [mevdschee/php-crud-api#442]
When a table has a composite primary key the following error occurs when try to list records:

> {"code":9999,"message":"Return value of Tqdev\\PhpCrudApi\\ReflectedTable::getPk() must be an instance of Tqdev\\PhpCrudApi\\ReflectedColumn, null returned"}

**Comment by mevdschee** [comment]
You should still be able to do list calls on that table
