### ISSUE TITLE
INNER JOIN query ?

### ISSUE THREAD

**Issue by laboratoirevetoquinol** [mevdschee/php-crud-api#444]
Hello, 

First of all thank you very much for your project. It has been really useful so far.

However, since you introduced "Joins" in V2 I have a question for you : 
Could you please give me an example of how I could get the results of such a SQL query with your API ?
`SELECT * FROM user_data INNER JOIN user ON user.id = user_data.user_id AND user.locked = 1`

Bes regards,

**Comment by mevdschee** [comment]
You can select "users" filter on "locked == 1"  and join on "user_data", like this:

    /api.php/records/users?filter=locked,eq,1&join=user_data

I hope that helps.

**Comment by mevdschee** [comment]
You can also do two queries.. get all users that are locked. Extract the id values and then do an "in" filter:

    /api.php/records/users?filter=locked,eq,1
    /api.php/records/user_data?filter=user_id,in,1,2,3,4,5,6,7,8,9

But I would recommend to try the previous method first.

**Comment by laboratoirevetoquinol** [comment]
Thanks a lot for your answers. That is indeed useful.

Best regards
