### ISSUE TITLE
Can I use curl to get data from api??

### ISSUE THREAD

**Issue by klikpaspor** [mevdschee/php-crud-api#446]
$curl = new MyCurl('localhost/api.php/records/user');
    $curl->setopt(CURLOPT_RETURNTRANSFER, 1);
    $curl->setopt(CURLOPT_CUSTOMREQUEST, 'GET');
    $response = $curl->exec();
    $balance = json_decode($response, true);
    $credits = $balance['records'][0]['balance'];
    $_SESSION['balance'] = $credits;

why no response?

Thank you.

**Comment by mevdschee** [comment]
This should work:

	$curl = curl_init();
	curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'GET');
	curl_setopt($curl, CURLOPT_URL, 'http://localhost/api.php/records/user');
	$response = curl_exec($curl);
        $balance = json_decode($response, true);
        $credits = $balance['records'][0]['balance'];
        $_SESSION['balance'] = $credits;

You're welcome.

**Comment by klikpaspor** [comment]
Still no response man :(

**Comment by mevdschee** [comment]
And the URL works in a browser?

Can you try `var_dump($response);` and see what it prints?

**Comment by klikpaspor** [comment]
this is the response `bool(false)`

what can i do?

**Comment by klikpaspor** [comment]
i think this good reference to fix this sources https://stackoverflow.com/questions/12181197/why-is-this-returning-boolfalse?answertab=votes#tab-top

**Comment by klikpaspor** [comment]
the response is string not json man, so fix them to json response :D

**Comment by mevdschee** [comment]
You are not answering my questions while I'm genuinely trying to help you. I'm closing this issue for now as there is nothing I can do for you.

**Comment by klikpaspor** [comment]
Sorry man :( no problem with my url than is showing the response string, this is works but the output is string

**Comment by klikpaspor** [comment]
oke fixed, i'm remove var_dump . thanks a lot :)

**Comment by mevdschee** [comment]
I'm glad you figured it out. Enjoy the software!
