### ISSUE TITLE
BasicAuth not blocking anonymous access

### ISSUE THREAD

**Issue by cc3a9dric** [mevdschee/php-crud-api#447]
Hello, 

I got an issue with basicAuth I can't get it work, or i missing something.

I tried on an Ubuntu 18.04.1 with apache 2.4.29 / php 7.2 / postgres 10.5
I tried on an Debian 9, apache 2.4.25 / php  7.0 / postgres 10.5

For the moment just simple conf : 

```
$config = new Config([
    'driver' => 'pgsql',
    'username' => 'my_user',
    'password' => 'my_password',
    'database' => 'my_base',
    'middlewares' => 'basicAuth',
        ]);
```

When i call the API without the authorization header or with bad user i do not get an unauthorized status, the api juste give me the info i request instead.

Have someone got the same problem ?
Do i need special conf in apache / php ?

Thanks for your help

**Comment by mevdschee** [comment]
I get this question more often. Apparently you expect basicAuth to do authentication and authorization. I'll add an option to (by default) deny all access to unauthenticated users and request authentication.

**Comment by mevdschee** [comment]
Latest master now has a "mode" config where you can set authentication as "optional" if you want the old (apparently unexpected) behavior.

**Comment by mevdschee** [comment]
Can you test whether or not it does (out-of-the-box) what you expected?

**Comment by cc3a9dric** [comment]
What you add is more like what describe here : 
https://en.wikipedia.org/wiki/Basic_access_authentication
Server side section, and it is exactly what i was looking for, thanks.

But now i always get : 
`curl -X GET -k -H 'Authorization: Basic dGVzdDp0ZXN0' -i 'https://...'`

Response
`{"code":1011,"message":"Authentication required"}`

I think my authorization header isn't read by the api.
So in
`$credentials = $this->getAuthorizationCredentials($request);`

$credentials is always empty.

What do you think i must do ?

**Comment by mevdschee** [comment]
Did you create the file `.htaccess` with the content `test:test`?

**Comment by cc3a9dric** [comment]
Yes file is present with test:test
In readme : "When the passwords are entered in plain text they fill be automatically hashed. "
But my .htpasswd isn't rewritten with the hashed password, i don't know if it's related.

**Comment by mevdschee** [comment]
Can you see whether or not this helps? It does for me. :-)

**Comment by cc3a9dric** [comment]
Problem solved thanks.

May be it was this part that cause the issue : 
```
if (!$this->highPerformance) {
                foreach ($_SERVER as $name => $value) {
                    if (substr($name, 0, 5) == 'HTTP_') {
                        $key = str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))));
                        $headers[$key] = $value;
                    }
                }
            }
```
highPerformance is true so headers were empty.

**Comment by mevdschee** [comment]
No .. highperformance will not "pre" parse all headers.. it still reads them "on demand". The problem was that apache removes the header and sets PHP vars. This code did it:

    private function getAuthorizationCredentials(Request $request): String
    {
        if (isset($_SERVER['PHP_AUTH_USER'])) {
            return $_SERVER['PHP_AUTH_USER'] . ':' . $_SERVER['PHP_AUTH_PW'];
        }
        $parts = explode(' ', trim($request->getHeader('Authorization')), 2);
        ...

Thank you for your help.
