### ISSUE TITLE
filter on joined tables

### ISSUE THREAD

**Issue by ahma0942** [mevdschee/php-crud-api#448]
Hi!

I don't know if it is a bug or it is just me, but i am trying to filter on a joined table, so i have the following tables:

```
Users:
| id | name | email | password |

Messages:
| id | user_id | group_id | message |
```

I request with following params:

```
'page=1,5'
'join=users'
'filter=group_id,eq,1'
'filter=users.name,cs,something'
'filter=message,cs,something'
'include=users.id,users.name,message'
```

The error i get is:

```
<br />
<b>Notice</b>:  Undefined index: users.name in <b>C:\xampp\htdocs\Get2Work\Backend\api\Tqdev\PhpCrudApi\Column\Reflection\ReflectedTable.php</b> on line <b>104</b><br />
{"code":9999,"message":"Return value of Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedTable::get() must be an instance of Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedColumn, null returned"}
```

Is it possible to filter on joined tables or only filter on the current table?
Thanks in advance and i love your plugin!

**Comment by mevdschee** [comment]
You can take messages as the current table.. that will allow you to applu 2 out of 3 filters.

**Comment by ahma0942** [comment]
That is what i am currently doing, tho searching on names is necessary for me. I guess i'll have to do 2 requests, 1 to users and 1 to messages table to search on both and then combine the results in the frontend. Hmm. Thanks for the info tho!

Is this something you will be working on? If so, do you have an ETA on when you will be finished?
Thanks in advance!

**Comment by mevdschee** [comment]
Would you be interested in:

A) filtering the "many" objects in a hasMany or "hasAndBelongsToMany" relationship? Or 

B) are you interested in filtering the original records based on the existence of records in the "belongsTo" or "hasMany" relationship?

I might consider A, but not B. Which one are you after?

**Comment by ahma0942** [comment]
Well actually i would need B to finish my task, though i guess i'll leave it for now then. Thank you very much for the super fast responses!

**Comment by thipages** [comment]
Hi,
this is a need for me also.
