### ISSUE TITLE
Issue with id and foreign key

### ISSUE THREAD

**Issue by Isabellle** [mevdschee/php-crud-api#45]
Cannot retrieve associated item of a user based on this sample request
http://mean-experience.com/api.php/users?include=items,pictures&filter=id,eq,1&transform=1

You can find all users here: http://mean-experience.com/api.php/users
all items here: http://mean-experience.com/api.php/items

Foreign keys has been set on users(id) and items(user_id)

Thanks for your assistance, 

For your convenience, here is my foreign key declaration:
`ALTER TABLE `items`
  ADD CONSTRAINT `items_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;`

**Comment by mevdschee** [comment]
Please update the script to the latest version or use:

    http://mean-experience.com/api.php/users,items,pictures?filter=id,eq,1&transform=1

This caused by a change in the signature, due to the new swagger support.

I hope it does not cause to much inconvenience. Kind regards, Maurits

**Comment by mevdschee** [comment]
Closed due to inactivity.

**Comment by Isabellle** [comment]
Sorry for the late reply. Thanks for the information.

**Comment by mevdschee** [comment]
No problem, enjoy the software.
