### ISSUE TITLE
Integers converted to strings

### ISSUE THREAD

**Issue by maciey** [mevdschee/php-crud-api#456]
I noticed ID (Primary Keys) fields are returned in JSON as strings
I tried to change that in MySQL to different length (eg64), type (eg BIGINT) but still no luck

Im getting this:
{"records":[{"ID":"1","PARAM":"CITIES", .... 

Id like to have:
{"records":[{"ID":1,"PARAM":"CITIES", .... 

I read few posts people complained same, and seems no quick win here.

I still do need all my numeric fields (not only IDs) to be presented as digits (without quotes)
If no easy correction / setting in API is possible - can you please advise best way I can do such conversion on my server end ?

(Id like to avoid to do such on each client device consuming JSONs)

**Comment by mevdschee** [comment]
Did you try the latest v1 or v2? This is fixed in both.

**Comment by maciey** [comment]
I'm using recent master v2

**Comment by mevdschee** [comment]
Can you post your schema and your PHP + mysql version?

**Comment by mevdschee** [comment]
Are you on Windows?

**Comment by maciey** [comment]
Actually my script works with PHP Version 7.2.8
(Only phpmyadmin with 5.6)

OS is Linux

PHP config below

> 
> Configure Command | './configure'  '--disable-dependency-tracking' '--prefix=/usr'  '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin'  '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include'  '--libdir=/usr/lib64' '--libexecdir=/usr/libexec'  '--sharedstatedir=/var/lib' '--mandir=/usr/share/man'  '--infodir=/usr/share/info' '--build=x86_64-redhat-linux-gnu'  '--host=x86_64-redhat-linux-gnu' '--target=x86_64-redhat-linux-gnu'  '--program-prefix=' '--prefix=/opt/alt/php72'  '--exec-prefix=/opt/alt/php72' '--bindir=/opt/alt/php72/usr/bin'  '--sbindir=/opt/alt/php72/usr/sbin' '--sysconfdir=/opt/alt/php72/etc'  '--datadir=/opt/alt/php72/usr/share'  '--includedir=/opt/alt/php72/usr/include'  '--libdir=/opt/alt/php72/usr/lib64'  '--libexecdir=/opt/alt/php72/usr/libexec' '--localstatedir=/var'  '--with-curl=/opt/alt/curlssl/usr' '--sharedstatedir=/usr/com'  '--mandir=/opt/alt/php72/usr/share/man'  '--infodir=/opt/alt/php72/usr/share/info' '--cache-file=../config.cache'  '--with-libdir=lib64' '--with-config-file-path=/opt/alt/php72/etc'  '--with-config-file-scan-dir=/opt/alt/php72/link/conf' '--disable-debug'  '--with-pic' '--without-pear' '--with-bz2' '--with-freetype-dir=/usr'  '--with-png-dir=/usr' '--with-xpm-dir=/usr' '--with-webp-dir=/usr'  '--with-t1lib=/opt/alt/t1lib/usr' '--without-gdbm' '--with-gettext'  '--with-gmp' '--with-iconv' '--with-jpeg-dir=/usr'  '--with-openssl=/opt/alt/openssl' '--with-openssl-dir=/opt/alt/openssl'  '--with-pcre-regex=/opt/alt/pcre/usr' '--with-pcre-jit' '--with-zlib'  '--with-layout=GNU' '--enable-exif' '--enable-ftp' '--with-kerberos'  '--enable-shmop' '--enable-calendar'  '--with-libxml-dir=/opt/alt/libxml2/usr' '--enable-xml'  '--with-readline' '--with-mhash' '--with-zlib-dir=/usr'  '--with-password-argon2=/usr' '--with-litespeed' '--enable-pcntl'  '--without-mysqli' '--disable-mbstring' '--disable-bcmath'  '--disable-dba' '--disable-dom' '--disable-fileinfo' '--disable-json'  '--disable-intl' '--disable-pdo' '--disable-phar' '--disable-posix'  '--disable-soap' '--disable-sockets' '--disable-sysvsem'  '--disable-sysvshm' '--disable-sysvmsg' '--disable-wddx'  '--disable-xmlreader' '--disable-xmlwriter' '--disable-zip'  '--without-gd' '--without-imap' '--without-xmlrpc' '--without-xsl'  '--without-ldap' '--without-pgsql' '--without-snmp' '--without-tidy'  '--without-enchant' '--without-recode' '--without-mssql'  '--without-pspell' '--without-unixODBC'  'build_alias=x86_64-redhat-linux-gnu'  'host_alias=x86_64-redhat-linux-gnu'  'target_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall  -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong  --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -fno-strict-aliasing -Wno-pointer-sign' 'CXXFLAGS=-O2 -g -pipe -Wall  -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong  --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'
> -- | --
> Server API | LiteSpeed V7.1
> Virtual Directory Support | disabled
> Configuration File (php.ini) Path | /opt/alt/php72/etc
> Loaded Configuration File | /opt/alt/php72/etc/php.ini
> Scan this dir for additional .ini files | /opt/alt/php72/link/conf
> Additional .ini files parsed | /opt/alt/php72/link/conf/alt_php.ini
> PHP API | 20170718
> PHP Extension | 20170718
> Zend Extension | 320170718
> Zend Extension Build | API320170718,NTS
> PHP Extension Build | API20170718,NTS
> Debug Build | no
> Thread Safety | disabled
> Zend Signal Handling | enabled
> Zend Memory Manager | enabled
> Zend Multibyte Support | provided by mbstring
> IPv6 Support | enabled
> DTrace Support | disabled
> Registered PHP Streams | https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
> Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
> Registered Stream Filters | zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk
> 
>

**Comment by maciey** [comment]
.Just tested v1 with same db connection/ data and it returns correctly formatted data
Im preffering v2 so Id appreciate if you can advise how to fix that / what part of code is responsible for quoting values (I can even hardcode that all IDs shouldnt be quoted)

`{"CONFIG":[{"ID":1,"PARAM":"CITIES","VALUE":"NY","LAST_CHANGE":"2018-10-24 20:27:00"}]}`

**Comment by mevdschee** [comment]
hmm.. this must be a PDO related issue. A quick fix would be to search for "getRecordValueConversion" and change the condition:

    if ($this->driver == 'sqlsrv' && $column->getType() == 'bigint') {

To:

    if ($column->getType() == 'integer' || $column->getType() == 'bigint') {

That should do it for you.

**Comment by mevdschee** [comment]
It may be related to this SO issue:

https://stackoverflow.com/questions/1197005/how-to-get-numeric-types-from-mysql-using-pdo#1197424

**Comment by maciey** [comment]
WORKS !!! THANKS !

I had **pdo_mysq** extention enabled but following ppl advice Ive disabled it and enable the **nd_pdo_mysq** and now works as a charm !

Many thank for prompt response and help offered.

**Comment by mevdschee** [comment]
Added to known issues: f802f2b873812d48ce06c33678ff2a9dc8bcc24e
