### ISSUE TITLE
Apache rule rewrite: 1000-Route '/' not found ERROR

### ISSUE THREAD

**Issue by maciey** [mevdschee/php-crud-api#457]
Im using Apache on hosting platform 
Im trying to 'hide' .php extensions by adding below to .htaccess

```
RewriteCond %{REQUEST_FILENAME}.php -f
RewriteRule !.*\.php$ %{REQUEST_FILENAME}.php [QSA,L]

```
It does what is expected ( so instead  www.mydomain.com/show.php I can do just www.mydomain.com/show)

But when I tried called similar way your api.php file I have error **1000 - Route '/' not found** 
Same URL ending api.php works well.

Any ideas ?

**Comment by maciey** [comment]
OK Ive found way:

```

# xxx/API/zzzzz  -> xxx/API/api.php/zzzz
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^API/(.*)$ API/api.php/$1 [L,QSA]
```

(Note my API is placed in /API folder)

**Comment by mevdschee** [comment]
Great! This is how I would do that as well..

**Comment by maciey** [comment]
Actually if you are referring to the one mentioned below is not exactly same as mine

`RewriteRule ^(.*)$ api.php/$1 [L,QSA]`

https://github.com/mevdschee/php-crud-api/commit/f84b2552c9a8fff81a56c6deb990a4c3bad1ff3c
