### ISSUE TITLE
Getting response from server

### ISSUE THREAD

**Issue by gmpofficial** [mevdschee/php-crud-api#46]
I am having issues validating a response from API.
I am passing the values from my login form to the url filter[], the server responds with a 200 OK response and returns the json data for that login. However I don't need the json data just a "success" or "error" response. Any help would be amazing. Thank you in advance for any feedback.

```
$(document).ready(function() {
	$("#login-button").click(function() {
        log_email = $("#login_email").val();
        log_password = $("#login_password").val();
        $.ajax({
            type: "GET",
            url: "http://www.website.com/api.php/users?",
			crossDomain: true,
            data: "filter[]=email,eq,email=" + log_email + "&filter[]=password,eq,password=" + log_password,
			dataType: 'json',
			success: function(data) {
				if (data == "null") {
					console.log("Email and Password DIDN'T match");
                    $( "#invalid-login" ).popup( "open" );
				} 
				else if (data == "true") {
					console.log("it's a !!MATCH!!");
					window.location = "content.html";
				}
			}
        });
        return false;
    });
});
```

**Comment by mevdschee** [comment]
Hi, in data add:

    +"&columns=id"

Hope that helps.

**Comment by gmpofficial** [comment]
wow that is exactly what I needed. Thank you so much.
No it's not for a real-life login, I'm learning and trying to pull/push data around but also to validate/verify it using an API. I have heard that OAuth is the way to go in terms of authorization with APIs.
PS: thank also for the quick response

**Comment by mevdschee** [comment]
You are welcome, enjoy the software!
