### ISSUE TITLE
Question: Get ids / records back on create /update?

### ISSUE THREAD

**Issue by gr0g** [mevdschee/php-crud-api#461]
Hi, 
First off: thank you for your amazing work!

Question:
Any way of getting back on create/update the actual records created? (or is this out of scope / non-desired behaviour?)

It seems that it would be very practical it some cases (maybe by hinting using a param) to have the results immediately back - especially that when using customization middleware you would then have the record + primary key in order to act on it since the customization.afterHandler does not have the request nor the primary key.

Thank you for your thoughts!

Cheers,

**Comment by mevdschee** [comment]
Hi @gr0g,

>Any way of getting back on create/update the actual records created?

You get back the primary key and you can follow the "create" or "update" with a "read".

>since the customization.afterHandler does not have the request nor the primary key.

This seems not true. The beforeHandler can store parameters (such as the $request) in the $environment variable so that the afterHandler can access them and the $response of a create call contains the primary key.

Is that clear enough? Please let me know.

**Comment by gr0g** [comment]
@mevdschee thanks for clarifying that.

Yes that works!

Any reason conceptually (e.g. is it a standard / performance related /etc.?) that you prefer juggling data between pre/post handlers in an environment variable vs having the response included the result?

I'm asking mainly to understand your design decisions / priorities.

Thank you!

**Comment by mevdschee** [comment]
I'm glad it worked! 

>Any reason conceptually (e.g. is it a standard / performance related /etc.?) that you prefer juggling data between pre/post handlers in an environment variable vs having the response included the result?

No, I did not realize that the request would be useful in the afterHandler. I'm tempted to add the request as a parameter on the afterHandler now that you bring it up. Do you think I should?

Thank you for clarifying.

**Comment by gr0g** [comment]
Yes - that would be helpful actually, I was tempted to add it myself but figured I'd ask you before so I don't fork / clobber the code :P 

Its primarily useful in the afterHandler because the Response object is ultra thin. (only contains primary key or # of updated records on create / update)

Typically in web apps we build, we expect to have the Response object containing what was returned from the server (since the data could have been manipulated / updated) and it can then be-reused vs placing another get / Read call.

So I would consider the following: 
- a config/option/flag to have Response return the created / updated record(s) (with their primary keys) <-- saves on placing another "Read" call in real-world apps
- passing the $request param to afterHandler in customization middleware
- all of the above :P 

Cheers,

**Comment by mevdschee** [comment]
Hi,

Thank you for helping me understand your reasoning better. Some questions:

>saves on placing another "Read" call in real-world apps

why does this matter?

>passing the $request param to afterHandler in customization middleware

just to be able to return it in the response?

Kind regards,

**Comment by gr0g** [comment]
> Thank you for helping me understand your reasoning better. Some questions:
> 
> since the data could have been manipulated / updated
> 
> Why? You have just sent the manipulated/updated data.
> 
> saves on placing another "Read" call in real-world apps
> 
> Why does this matter? Is it because of latency?

1. the data can be additionally manipulated on its way back so the point is to *trust* the data from server more than the data on the client (e.g. it could be augmented on its way back via customfields so the model on the client side would not be fully representative in its state then)
2. Yes, it reduces having to place another ajax call
3. Granted, the above is really not that critical (one can simply place another call) 

> passing the $request param to afterHandler in customization middleware
> 
> Do you want this just to be able to return it in the response?

I think "passing the $request param to afterHandler in customization middleware" will be useful if you equally see value in that (helps avoid juggling with $environment)

Thanks!
