### ISSUE TITLE
Updating join table information?

### ISSUE THREAD

**Issue by gr0g** [mevdschee/php-crud-api#462]
Does php-crud-api/treeql support updating join table information automatically?

e.g. considering an example of 3 tables: posts, tags, and posts_tags (as a join table) with the fields:
posts.id
posts.name

tags.id
tags.name

posts_tags.id
posts_tags.post_id
posts_tags.tag_id

How would I go about adding a new tag to a post without doing the steps below?
create post (get primary key back)
create tag (get primary key back)
create posts_tags (create new posts_tags with both primary keys from above)

Does php-crud-api handle this automagically? :)

Thanks!!

**Comment by mevdschee** [comment]
>Does php-crud-api handle this automagically?

No it does not and in typical cases (existing post and tag) you just have to insert one record to post_tags for each tag you want to relate to the post.
