### ISSUE TITLE
Extending php-crud-api

### ISSUE THREAD

**Issue by gr0g** [mevdschee/php-crud-api#463]
Hi,

php-crud-api is awesome!

What are the recommended ways to extend its functionality?

The docs presently highlight the customization middleware which is great.

Additionally are these viable/interesting options (any others)?
- controllers (adding your own controller definition in e.g. $config and allowing php-crud-api to instantiate that external controller if the class exists)
- routes (being able to define custom route <-- this would allow php-crud-api to be a drop-in for existing projects maybe too)

Thanks again!

p.s: is there a better place to ask questions that the Issues

**Comment by mevdschee** [comment]
Thank you for reaching out.

>What are the recommended ways to extend its functionality?

You may stick the "api.php" file in the webroot of any other framework and extend it that way.

>The docs presently highlight the customization middleware which is great.

Middleware should be used to extend the functionality (in a reusable way).

>Additionally are these viable/interesting options (controllers, routes). Are there any others?

Please contribute new functionality to the project if (you think) it is not specific to your use case.
