### ISSUE TITLE
Problems to use code

### ISSUE THREAD

**Issue by rsoftw** [mevdschee/php-crud-api#465]
Hi.
thanks for sharing this!
i trying to use code and i changed just following 3 lines 
from:
// file: src/index.php

$config = new Config([
    'username' => 'php-crud-api',
    'password' => 'php-crud-api',
    'database' => 'php-crud-api',

To
// file: src/index.php

$config = new Config([
    'username' => 'myuser',
    'password' => 'mypass',
    'database' => 'mydb',

and i trying to run it via web and i getting following error:

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/xxxx.dk/rest/api02/api.php:1832 Stack trace: #0 /var/www/xxxx.dk/rest/api02/api.php(1832): PDO->__construct('mysql:host=loca...', 'myuser', 'mypass', Array) #1 /var/www/xxxx.dk/rest/api02/api.php(5025): Tqdev\PhpCrudApi\GenericDB->__construct('mysql', 'localhost', '3306', 'mydb', 'myuser', 'mypass') #2 /var/www/xxxx.dk/rest/api02/api.php(5554): Tqdev\PhpCrudApi\Api->__construct(Object(Tqdev\PhpCrudApi\Config)) #3 {main} thrown in /var/www/xxxx.dk/rest/api02/api.php on line 1832

could you please help me?

**Comment by mevdschee** [comment]
This makes total sense: It is trying to connect to your database on address 'localhost' (still default) with the credentials you have given. If you want to override the "address" to point to something else than "locahost" you can do so in that block:

    $config = new Config([
    'address' => 'not-localhost',
    'username' => 'myuser',
    'password' => 'mypass',
    'database' => 'mydb',

I hope that helps.

**Comment by mevdschee** [comment]
Any updates?

**Comment by rsoftw** [comment]
Hi. sorry i was traveling.
i really appreciate your valuable help.
works perfectly! thank you so much!!!
