### ISSUE TITLE
Auth help

### ISSUE THREAD

**Issue by StevenJonSmith** [mevdschee/php-crud-api#468]
Hi,
Trying to add auth to the api, created my .htpasswd file in the same directory add a username:password combination to the first line. I have tried both with and without the password being hashed in this file but my authorisation when I do the call always fails.

Tried webCoreHome:Et5sw42tEWG (plain text) in the file with header 'Authorization: Basic d2ViQ29yZUhvbWU6RXQ1c3c0MnRFV0c=', and also tried the same but with the password Base64 hashed too. I know I'll kick myself when I get an answer but I can't see the wood for the trees at the moment.

**Comment by mevdschee** [comment]
Hi! Thank you for reaching out. Did you add the basicAuth middleware using the "middleware" config parameter?

**Comment by StevenJonSmith** [comment]
Yes added middleware parameter to config, but every time I send a request I get Authentication Required, I believe it's code 1011 (that's from memory of last night so could be wrong).

**Comment by mevdschee** [comment]
Are you on the latest version? Does the test suite (with the basic auth test) run?

**Comment by mevdschee** [comment]
Can you zip a minimal setup (that does not work) and send it to me by email? That can help me debug it.

**Comment by StevenJonSmith** [comment]
Sorry for the delayed reply, it's a personal project and not had chance to sit down and look at it deeper yet. I took the two config lines out for middleware and basicAuth.passwordFile and it is working fine.

I am going to have a little look this evening and see if it's just me being silly and missing something.

**Comment by StevenJonSmith** [comment]
Permissions on the .htpasswd file were bad. Set to "664" and all good now.
