### ISSUE TITLE
PUT - route not found

### ISSUE THREAD

**Issue by thinkpeuro** [mevdschee/php-crud-api#469]
Hi,
I tried to update a value but got error route not found.
I see that I need to send the primary key but its also not working

{"code":1000,"message":"Route '\/records\/test\/4' not found"}

Here is my code:
$url = "api.php/records/test/4";
$fields = array(
	'id' => 4,
	'guid' => "checking"
);
$ch = curl_init();
curl_setopt($ch,CURLOPT_URL, $url);
curl_setopt($ch,CURLOPT_POST, 1);
curl_setopt($ch,CURLOPT_POSTFIELDS, $fields);
$result = curl_exec($ch);
curl_close($ch);

Attached is the table's structure
![capture](https://user-images.githubusercontent.com/22701603/48866618-196d9480-eddc-11e8-8b42-4050ffc39e42.JPG)

Thanks!

**Comment by mevdschee** [comment]
Thank you for reaching out and for your clear question. Update is done with PUT, not with POST, and you need to encode the data, so do:

    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
    curl_setopt($ch, CURLOPT_POSTFIELDS,json_encode($data));

Hope that helps/works!

**Comment by mevdschee** [comment]
Did this work?
