### ISSUE TITLE
How to have Basic authentication mandatory ?

### ISSUE THREAD

**Issue by GODDET** [mevdschee/php-crud-api#470]
Hi,

I try to use the basic authentication. 

I put this in my config

`$config = new Config([
    'address' => '127.0.0.1',
    'username' => 'xxxx',
    'password' => '',
    'database' => 'xxxx',
    'middlewares' => 'cors,basicAuth', 
    'basicAuth.mode' => 'optional',
    'basicAuth.passwordFile' => __DIR__ . DIRECTORY_SEPARATOR . '.htpasswd',
   
]);`

On my localhost, if I add a header with **Authorization** it works well. If the hash is not good, the result of the url call is blocked.

But if I open my GET url in my browser or if I miss the header, the API returns the result of my GET. 

- How can set the basic authentication to mandatory ? 
- Which value of **basicAuth.mode** I need to use to have a mandatory authentication ?
- Is-it due to my localhost ?

Thanks by advance,

**Comment by mevdschee** [comment]
Thank you for your question. The "basicAuth.mode" can be either "optional" or "required" and it will default to "required".

**Comment by GODDET** [comment]
Thank you it works now.
