### ISSUE TITLE
Can you send null data?

### ISSUE THREAD

**Issue by didinkha** [mevdschee/php-crud-api#473]
Hello! I just began using this amazing script. Thank you for providing this. I just want to ask if it is possible to send PUT request with null value. I tried sending this data:
`data: {
                                                    "id_sch":null
                                                }`

Then i received this message:
`{"code":9999,"message":"SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'id_sch' at row 1"}`

id_sch is a foreign key so I need to be able to set the value to null. Is it possible?

**Comment by mevdschee** [comment]
Thank you for reaching out. Is `id_sch` a datetime?

**Comment by didinkha** [comment]
no it's not datetime, it is an integer, I also tried these: `"id_sch":null` `"id_sch":"null"` `"id_sch":""` but none of it worked.

**Comment by mevdschee** [comment]
Can you reproduce this in a test case?

**Comment by didinkha** [comment]
Actually it worked, I used ajax to send the data. So, the problem was the null value itself, I should've set it to undefined. Anyways, Thank you for your responses.
