### ISSUE TITLE
use of JWT tokens with v2

### ISSUE THREAD

**Issue by laboratoirevetoquinol** [mevdschee/php-crud-api#477]
Hi Mauritz

things move here : our v2 use is now working

we are starting to us this for security
https://bshaffer.github.io/oauth2-server-php-docs/overview/jwt-access-tokens/
as JWT provider

have you some recommendations of other JWT servers or you already know this one ?

thanks

antoine

**Comment by mevdschee** [comment]
Hi Antoine, Thank you for your message. I have no experience with JWT token servers. I have tried Auth0 and it worked (https://auth0.com/). I hope this helps a bit. Kind regards, Maurits

**Comment by mevdschee** [comment]
I hope you get JWT auth working. FYI, here is the auth0 example code: https://github.com/mevdschee/php-crud-api/blob/master/examples/clients/auth0/vanilla.html

**Comment by laboratoirevetoquinol** [comment]
hi ! thanks for answer ! i'll try next week and post results here asap
