### ISSUE TITLE
javascript 404 error with non valid ids

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#478]
Hi,
this library is just great congrat!

I have an issue when I try to retrieve a non existing record (ie querying an  non existent id of a table)
here is a simple javascript fetch, working fine with existing _id_ in _table_ 
```
fetch([baseUrl,"records",table,id].join("/"), {method:'GET'})
    .then(response=>response.json())
    .then (data=>console.log(data));
```
The issue : 

When id is not existing I get the right error code in _data_ as (fine) : 
`{code: 1003, message: "Record '1000' not found"}`

but  I get also an additional message , a javascript error : 
`GET http://localhost/php/api.php/records/note/1000 404 (Not Found)`

Here is a screenshot
<img width="422" alt="2018-12-21_04-36-49" src="https://user-images.githubusercontent.com/130309/50323657-e7367c00-04da-11e9-96c6-f5a4a0982581.png">

How can I catch this error (in red)?
Thank you

**Comment by mevdschee** [comment]
Thank you for reaching out and for your kind words. It is intended that you get a 404 when you request an item that is not found. Maybe you are experiencing this:

https://bugs.chromium.org/p/chromium/issues/detail?id=124534

Kind regards, Maurits

**Comment by thipages** [comment]
Hi,
first thanks for the link.
You wrote "It is intended...". My question is more why the API return 404 **and** json containing code 1003. Is that not redundant?

**Comment by mevdschee** [comment]
>Is that not redundant?

Yes it is :-)

**Comment by thipages** [comment]
.. but satisfies some specification I guess. Thanks.

**Comment by thipages** [comment]
Finaly, it seems not to be redundant. The two information
- status code (eg 404)
- error object (code, message)

are necessary to identity an error
The error object only could be a query response.
