### ISSUE TITLE
v2 - silent authentication

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#479]
Hi,
I tried basic authentication but I am not happy with it and would like to get an authentication mechanism without the _WWW-Authenticate_ header popup.
Is it possible/in the scope of this API?
Thank you

**Comment by mevdschee** [comment]
Thank you for reaching out. This is supported. Change the "basicAuth.mode" from "required" to "optional", as you can see here: https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Middleware/BasicAuthMiddleware.php#L98

**Comment by thipages** [comment]
Hi,
ok, I think I get it somehow. However I have an issue
Here is how I manage silent basic authentication **restricting to registered users only (no anonymous)**

1. .htaccess file filled in  with username:password
2. Config as  
```
$config = new Config([
    'username' => 'username',
    'password' => 'password',
    'database' => 'database',
    'middlewares' => 'basicAuth,authorization',
    'basicAuth.mode' => 'optional',
    'authorization.tableHandler' => function ($operation, $tableName) {
        return isset ($_SESSION['username']) && $_SESSION['username'];
    }
]);

```
3. Javascript as (where xxxxx is username:password base64 encoded)
```
        fetch(
              [baseUrl, "records", myTable, id].join("/"),
              {method: 'GET', headers: {Authorization:'Basic xxxx'}}
            )
            .then(response => response.json())
            .then(data => console.log(data));
```
This works fine
- if xxxx is valid, I got the correct output
- if xxxx is not valid I got` {code: 1001, message: "Table 'myTable' not found"}`, fine
- Then if I remove the Authorization header or if [part[0] ](https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Middleware/BasicAuthMiddleware.php#L70) is not "Basic" string, it acts as valid case, which it is not what I would like.

[Seems that an else is missing here](https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Middleware/BasicAuthMiddleware.php#L82) reseting $_SESSION['username']

What do you think? Thank you.

**Comment by thipages** [comment]
I just edited my previous post and get my issue finally working as I wanted.

**Comment by mevdschee** [comment]
I'm glad you got it working. Thank you for sharing!

**Comment by thipages** [comment]
minor update : PHP-CRUD-API uses `username` as SESSION key. `pca_username` may be more appropriate avoiding some collisions with existting code.
