### ISSUE TITLE
v2 - Differences between multiTenancy.handler and authorization.recordHandler

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#480]
Hi,
`'multiTenancy.handler'` and `'authorization.recordHandler' `seem to provide the same functionality, ie adding a filter to the query.
Can you elaborate on this? Thank you.

**Comment by mevdschee** [comment]
The multiTenancy handler does not return a condition. It returns a key value pair that is enforced as a filter on read and list, delete and update, but also used as input on create and update.

**Comment by thipages** [comment]
ok, I think I got it.
I did not know about multi-tenancy concept . Have you a link for newbie?
Thank you

**Comment by mevdschee** [comment]
It is for storing multiple customers in a single database by adding a customer_id column to all/most tables. This is some talk about it:

https://softwareengineering.stackexchange.com/questions/298057/multi-tenant-database-design

**Comment by thipages** [comment]
Thank you
