### ISSUE TITLE
Does openapi request contains table relationships

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#481]
Hi,
I query "openapi" in order to extract some database information taking avantage of the php-crud-api reflection work. So far, I could get parsing the result (javascript)
- the list of tables as `["tags"]["name"]`
- the list of a `table` properties as `["components"]["schemas"]["list-"+table]["properties"]["records"]["items"]["properties"]`

I would like to get tables relationships, but I could  not find them. 
Any help? Thank you

**Comment by mevdschee** [comment]
You could consider enabling the "columns" controller and access the "columns" endpoint. You will find all data there (for read and write). Be careful that you apply proper (security) restrictions to this endpoint.

**Comment by thipages** [comment]
ok, works fine , see below.

The `reflect` operation seems clear to me and [is a result of GET + columns endpoint](https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Record/RequestUtils.php#L25) (btw get is lowercase in the code)

question  : I could not find `remodel` operation usage in code/documentation. Can you show me where it stands? Thank you.


**Code example for retrieving database structure + disabling database structure changes**

```
    $config = new Config([
        'controllers'=>'records,openapi,columns','
        'middlewares' => 'authorization',
        'authorization.tableHandler' => function ($operation, $tableName) {
            return $operation!=="remodel";
        }
    ]);
```
javascript
```
fetch(
    [baseUrl, "columns", aTable, aColumn].join("/"),
    {method: 'GET'}
)
.then(response => response.json())
.then(data => console.log(data));  
```   
Note : if aColumn or aTable is omitted, then  all tables and columns are listed

**Comment by mevdschee** [comment]
>question : I could not find remodel operation usage in code/documentation. Can you show me where it stands?

https://github.com/mevdschee/php-crud-api/blob/fb18a551a9be074d380902f5947faedb0fd4642d/src/Tqdev/PhpCrudApi/Record/RequestUtils.php#L25

**Comment by thipages** [comment]
I will. Thank you.
