### ISSUE TITLE
Non defined foreign keys constraints

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#482]
Hi,
In the limitation, it states

> Database must support and define foreign key constraints

For some projets (quite a lot) , related databases do not define them.
Is it planned to include those databases in the API?
Thanks

**Comment by mevdschee** [comment]
Thank you for your question. First of all I feel that it's bad practice to not have FK constraints. But since you don't, do you at least follow a naming convention? Or let me ask that question different: How should the software "detect" the foreign key relationship? Kind regards, Maurits

**Comment by mevdschee** [comment]
Duplicate of #101
