### ISSUE TITLE
erro code:9999,help

### ISSUE THREAD

**Issue by spritecn** [mevdschee/php-crud-api#486]
when i create a record ,get a error like:
`
{
    "code": 9999,
    "message": "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\"qCom\" (\"shId\") VALUES (?)' at line 1"
}
`
my server info:
api url:http://spritecn.gz01.bdysite.com/crud-api-test.php/records/qCom

qCom table create sql:
```
CREATE TABLE IF NOT EXISTS `qCom` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `shId` varchar(100) DEFAULT '',
  `uId` varchar(50) DEFAULT '',
  `city` varchar(20) DEFAULT '',
  `name` varchar(50) DEFAULT '',
  `account` int(10) unsigned DEFAULT '0',
  `url` varchar(255) DEFAULT '',
  `sso` varchar(255) DEFAULT '',
  `aera` varchar(20) DEFAULT '',
  `saler` varchar(20) DEFAULT '',
  `upTm` varchar(30) DEFAULT '2000-01-01 00:00:00',
  `createTm` bigint(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
```

test create json:
```
{ "shId": "sh9945"}
```

how can i do?

**Comment by mevdschee** [comment]
![image](https://user-images.githubusercontent.com/1288217/51189788-08736800-18e1-11e9-8274-b7786814a99d.png)

works for me

**Comment by spritecn** [comment]
> I do:
> 
> ```
> $ curl -X POST -d '{ "shId": "sh9945"}' http://localhost:8000/api.php/records/qCom
> ```
> Result:
> 
> ![image](https://user-images.githubusercontent.com/1288217/51189788-08736800-18e1-11e9-8274-b7786814a99d.png)
> 
> So, it works for me

thinks a lot,
i guess the ression is mysql version  is  5.5.3
i try localserver on 5.7,it works
is any solution on 5.5? 
the server on the idc,cant modify  version

**Comment by mevdschee** [comment]
Which (Linux) operating system are you running? I'm looking for a distribution where 5.5 is still used so that I can add a docker build for it.

**Comment by spritecn** [comment]
u can lookup at [http://spritecn.gz01.bdysite.com/phpinfo.php](url),
5.5 is mysql version  not  linux...

**Comment by mevdschee** [comment]
You are running Ubuntu Precise (12.04) which is not (no longer) supported.

**Comment by spritecn** [comment]
thanks,u nice man
i guess ression is mysql syntax not suppered..
maybe use compatibility  sql will works...
i want fix it,but,i'm not a phper,just know a little python.
but the server just can use  php,any  5.5 version mysql

anyway  thanks..
