### ISSUE TITLE
Performance of the API vs 'normal' SQL-queries

### ISSUE THREAD

**Issue by tafelnl** [mevdschee/php-crud-api#490]
Sorry for opening yet another issue 😳 

If I do a GET on the following endpoint for example:
`records/users/:id/?join=users_statuses` it will take about ~4 seconds.

I guess this API-call corresponds to about the following SQL query:

```
SELECT *
FROM users
	LEFT JOIN users_statuses
		ON users_statuses.user_id = users.user_id
WHERE users.user_id= :id
```

This query takes only about ~16 **milli**seconds

Am I doing something wrong/is something wrong with my configuration, or is this expected behavior?

**Comment by mevdschee** [comment]
The query takes 16 milliseconds, the API call 4 seconds. You can't compare these numbers (these are two different things). Also the query does a join, while the API does an "IN" query.

I think that if you have millions of users then it might make sense that the API call takes 4 seconds. Unfortunately I know nothing about your environment (or hardware).

**Comment by tafelnl** [comment]
Ah okay, that makes sense.

I am currently testing on localhost on my PC. And the database is hosted on a t2.micro instance on AWS. So that shouldn't be the bottleneck I guess.

I only have about a 1000 users right now, so that is not that many.

So I guess normally it would go a bit faster than 4 seconds right?

**Comment by tafelnl** [comment]
What do you mean by 'B/W'?

I think the database is only used for querying the tables first and after that the PC does all the work? So you are suggesting the PC isn't fast enough?

**Comment by mevdschee** [comment]
B/W=bandwidth

Maybe the bandwidth is the bottleneck.

**Comment by tafelnl** [comment]
I upgraded to db.r4.8xlarge on AWS and still got the same performance.

It is maybe good to know that when I select only one table (calling `api/records/tablename`) it is fast (under half a second).

So the bottleneck is not in the database.

I'm going to try and call some endpoints from a different server tomorrow. I'll keep you posted

**Comment by mevdschee** [comment]
>when I select only one table (calling api/records/tablename) it is fast (under half a second).

When I request 11 records from a table on localhost the full request takes about 2 milliseconds

**Comment by mevdschee** [comment]
I have posted the timings of the tests in the README. Maybe those can help you to have a baseline for your performance research.

**Comment by tafelnl** [comment]
Ohh, hmm, that's strange. But you can agree that db.r4.8xlarge should be quite enough right? So I don't think the bottleneck is in the Database server

**Comment by tafelnl** [comment]
> I have posted the timings of the tests in the README. Maybe those can help you to have a baseline for your performance research.

Thank you very much :). I will take a look at it first thing in the morning

**Comment by mevdschee** [comment]
Are you running the PHP script on your local machine and the database in the cloud?

**Comment by tafelnl** [comment]
Yes, that it correct. The cloud being a `db.r4.8xlarge` instance from Amazon

**Comment by mevdschee** [comment]
Can you try running the PHP script and the Database on the same machine (or at least in the same network)?

**Comment by tafelnl** [comment]
I made a copy of the database on my localhost and now when I request a table with 19 records it only takes about 4 milliseconds.

When I do a simple join it takes about 460-740 milliseconds. The same request from cache takes about 20 milliseconds.

So that is definitely an improvement.

I will try and find a way to put my server and Amazon RDS instance on the same network and do some tests. I'll keep you posted

**Comment by tafelnl** [comment]
@mevdschee you're a hero man! You were correct, I deployed a little EC2 instance and now I can retrieve a single table (consisting of ~600 records) in only ~3 milliseconds 😮 

The complex join I was talking about:
>And I just figured out a much more complex API-call with about 9 joins takes about ~4 seconds as well. 

is now only taking about 260 milliseconds and ~20 milliseconds from cache

So let's migrate from hosting then haha.
Thanks again 👍

**Comment by mevdschee** [comment]
>is now only taking about 260 milliseconds and ~20 milliseconds from cache

Thats sounds about right!
