### ISSUE TITLE
Unicode not correctly stored

### ISSUE THREAD

**Issue by spritecn** [mevdschee/php-crud-api#491]
post string like
`"city": "\\u798f\\u5dde"`
the unicode just only store..  
it sould be encode to utf8 then store

**Comment by mevdschee** [comment]
Thank you for reporting this issue. It seems that you are double escaping. Replace the double backslash with a single one before the "u" character as specified here: https://json.org/

**Comment by spritecn** [comment]
it's python json.dumps's result;
`
>>> json.dumps(a)
'{"city": "\\u676d\\u5dde"}'
`

**Comment by mevdschee** [comment]
This is expected behavior and in line with the JSON standard on https://json.org/

**Comment by spritecn** [comment]
got it
think you

**Comment by spritecn** [comment]
but another thing： when i get a utf8 string. it not to encode uncode
the response like
,"city":"杭州",

**Comment by spritecn** [comment]
private function parseBody($body)
    {
        if ($body === '') {
            $this->body = '';
        } else {
            $data = json_encode($body, JSON_UNESCAPED_UNICODE);
            $this->addHeader('Content-Type', 'application/json');
            $this->addHeader('Content-Length', strlen($data));
            $this->body = $data;
        }
    }
i look the  code...if i need will  let 
`$data = json_encode($body);`
thanks

**Comment by spritecn** [comment]
my english  read   https://json.org/     hard...hard  hard

**Comment by mevdschee** [comment]
No problem, feel free to adjust the code to your needs. I don't see a bug in the code, let me know if you do.
