### ISSUE TITLE
help.the join not working

### ISSUE THREAD

**Issue by spritecn** [mevdschee/php-crud-api#494]
i have to table
```
 CREATE TABLE `test` (
     `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
     `name` varchar(255) DEFAULT NULL,
     `age` int(11) NOT NULL,
     PRIMARY KEY (`id`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
```
CREATE TABLE `todo` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `test_id` int(11) unsigned NOT NULL,
  `todo` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
i run sql:
```
select t.id,t.name,t.age,d.id as did,d.test_id,d.todo from test as t LEFT JOIN todo as d on  t.id = d.test_id
```
result like this
```
2	base	   33	  1	2	do some thing
1	jon	   3			
```
but i try to  join on api it doesnt works,
```
GET  /records/test/2?join=todo
```
it's only out the result in test
{
    "id": 2,
    "name": "base",
    "age": 33
}

help  why?

**Comment by mevdschee** [comment]
The join depends on a defined foreign key constraint, see this one between comment and post:

https://github.com/mevdschee/php-crud-api/blob/master/tests/fixtures/blog_mysql.sql#L27

If you did not define such constraint it cannot find the foreign key relationship.

**Comment by spritecn** [comment]
thanks ..it's  not  write in readme yet...   i' m so fooo

**Comment by mevdschee** [comment]
I added it: 4dc8cf6bd76cdbca30f46f9ec20aeb4265346174
