### ISSUE TITLE
Does POST require you to send all rows in order to post to table?

### ISSUE THREAD

**Issue by tonyduanesmith** [mevdschee/php-crud-api#496]
example:
I have the following table -

posts  
=======
id     
title  
content
created

I send a post request with the raw data of:
{
     "title": "this is the title"
}

I expected this to post to the table only adding to the title column but in fact I get a response of:
{
    "code": 1010,
    "message": "Data integrity violation"
}

If I post with all fields filled in then the request is successful and the response is the created ID.

Thanks for the great work and apologies if this question has already been asked but I was unable to find a similar issue.

Thanks,

**Comment by mevdschee** [comment]
Thank you for reaching out. Quick question: are the other fields (content and created) nullable or do they have a default value set?

**Comment by mevdschee** [comment]
You are welcome, enjoy the software!
