### ISSUE TITLE
How to use handlers?

### ISSUE THREAD

**Issue by jonmbennett** [mevdschee/php-crud-api#498]
Hello, thanks for your great work. I found it easy to get up and running. I'm not sure how to use the handlers though. I'm sorry if this is a dumb question or I overlooked something in the documentation.

For example, this customization handler was given in the docs:
```
'customization.afterHandler' => function ($operation, $tableName, $response, $environment) {
    $response->addHeader('X-Time-Taken', microtime(true) - $environment->start);
},
```
But where in the api.php file would I insert this code in order to use it?

**Comment by thipages** [comment]
Hi,
you can declare handlers at the end of file api.php in the Config object.
Do not forget to update `middlewares` field as well
[See here for an example with an other handler](https://github.com/mevdschee/php-crud-api/issues/479#issuecomment-449880531)

**Comment by jonmbennett** [comment]
Ah, that works. My mistake was trying to put it at the end of the file **outside** the Config object. 😂

Thank you!
