### ISSUE TITLE
Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by emond07** [mevdschee/php-crud-api#500]
Hi, im using the V2 but im having an issues running local xampp server

GET http://127.0.0.1/votermasterlist/api/v2/api.php/records/vlist/

![github](https://user-images.githubusercontent.com/17446488/53148759-ae07ae80-35e6-11e9-9cb2-fb7eafa0fb33.png)

error:
Fatal error: Default value for parameters with a class type hint can only be NULL in C:\xampp\htdocs\votermasterlist\API\v2\api.php on line 14

**Comment by mevdschee** [comment]
Are you running a PHP version lower than (the minimum version) 7?

**Comment by emond07** [comment]
yes im running 5.6.28

**Comment by mevdschee** [comment]
Okay, please run v1 or upgrade.

**Comment by emond07** [comment]
im running version 1 now, i have 11k rows can i fetch this?

**Comment by mevdschee** [comment]
Sure, why not? :-)
