### ISSUE TITLE
CORS is blocking, preflight does not contain CORS header

### ISSUE THREAD

**Issue by Disane87** [mevdschee/php-crud-api#501]
Hey, I'm just practising with your V2 of this great API!
Actually I have some strange problems with it. At the moment I'm developing an internal banking overview for me and my gf for internal use. So I get all my transactions and accounts from my bank over a frequently running python script and push them into the database (this is really ok). Now comes the strange part:

I configured the api with JWT to require an auth with JWT (in addition with Auth0), but if I want to connect my Angular-Frontend with it, CORS is always blocking, every f* time. 

Here is my config of the api:
```php

$config = new Config([
    'username' => '',
    'password' => '',
    'database' => '',
    'address' => '',
    'middlewares' => 'basicAuth,authorization,jwtAuth,cors,authorization,customization',
    'basicAuth.mode' => 'optional',
    'jwtAuth.mode' => 'required',
    'cors.allowedOrigins' => '[my-projectname].stackblitz.io,localhost'
]);
```
If I open the api in the browser, its failing (just as it should be):
```json
{
"code": 1011,
"message": "Authentication required"
}
```

Error in chrome:

> Access to fetch at 'https://[API-URL]/api/api.php/records/Accounts/' from origin 'https://[stackblitz project] has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

For privacy reasons, I don't want to disclose the API and Stackblitz data, as they are already sensitive data.

**Comment by mevdschee** [comment]
Can you check whether or not the pre-flight request has the "Access-Control-Allow-Origin" header? The error says it does not. It is likely to be an "OPTIONS" request (or is your webserver blocking those?).

**Comment by Disane87** [comment]
Good point! Totally forgot to check that. This is the preflight:
![image](https://user-images.githubusercontent.com/956158/53162821-22355880-35cd-11e9-8f41-457952734a45.png)

It seems it needs to authenticate, but (for testing purposes) I turned the JWT to optional. In browser now I got the full data, in stackblitz not.

**Comment by mevdschee** [comment]
The problem may be this: https://stackoverflow.com/questions/41760128/cookies-not-sent-on-options-requests

JWT authorization does not exclude the OPTIONS request.

**Comment by mevdschee** [comment]
I have verified with a test case that the order of the middleware matters, please update it.
