### ISSUE TITLE
"public static function fromString(ReflectedTable $table, String $value): Condition" 

### ISSUE THREAD

**Issue by uniho** [mevdschee/php-crud-api#502]
Please remove ": Condition" from
"public static function fromString(ReflectedTable $table, String $value): Condition".
Because you are using "return null;" in this function.

**Comment by mevdschee** [comment]
Thank you for reporting this. Good catch. I'll change the code as soon as possible.

**Comment by mevdschee** [comment]
This should be resolved in the latest version/master. Feedback is appreciated. Thank you, Maurits.
