### ISSUE TITLE
openapi

### ISSUE THREAD

**Issue by emond07** [mevdschee/php-crud-api#503]
im trying to access the /openapi documentation but it give me this error.

using apache 
![sc1](https://user-images.githubusercontent.com/17446488/53247931-7c2e3f00-36ef-11e9-87c4-63942411792d.png)
xampp with PHP7

**Comment by mevdschee** [comment]
Thank you for reporting this. I'll look into this as soon as possible.

**Comment by mevdschee** [comment]
This should be resolved in the latest version/master. Feedback is appreciated. Thank you, Maurits.
