### ISSUE TITLE
Force paging

### ISSUE THREAD

**Issue by painos** [mevdschee/php-crud-api#504]
Is there an option to force paging on every request? I want to open public API with only read and I would like to limit the results to 1000 or 2000 records per request on the server side to prevent anyone getting results of millions of records at once.

**Comment by mevdschee** [comment]
You can start the script with setting the get parameter 'page' to '1,1000' like this:

    $_GET['page'] = '1,1000';

Hope that helps.

**Comment by mevdschee** [comment]
Instead of forcing paging I added a 'pageLimits' middleware that you can use. Let me know whether or not it does what you want/need.

**Comment by mevdschee** [comment]
Check out the latest release and let me know what you think.

**Comment by painos** [comment]
Yes, thank you! This does exactly what I need.

**Comment by painos** [comment]
Oh, actually I think if pageLimits is enabled JSON should include number of results by default to know how many pages exist.

**Comment by mevdschee** [comment]
>if pageLimits is enabled JSON should include number of results by default to know how many pages exist.

Such logic would make every request much more expensive, so I would not recommend that.
