### ISSUE TITLE
basicAuth and curl

### ISSUE THREAD

**Issue by devoldski** [mevdschee/php-crud-api#505]
hi,

when enabling basicAuth and including username and pass in curl headers I receive access denied.

curl_setopt($process, CURLOPT_USERPWD, $username . ":" . $password);  

also connecting to api endpoint with uname pass in url like https//user:pass@server.tld... does also throw an error. 

Can you please advice.

**Comment by mevdschee** [comment]
Thank you for reporting this. The curl command is correct, so there must be something else that is going wrong.

**Comment by mevdschee** [comment]
Can you shar e some more information about your setup and the problem you encounter? Maybe I can reproduce it.

**Comment by devoldski** [comment]
Thank you for aiding. 

I did a bit more testing and found out that there was an issue with my .htpasswd file causing my error. 

I gather opening the issue made me solve it :-) 

Thank you for the support and the making of this script.

**Comment by mevdschee** [comment]
Thank you for reporting your success!
