### ISSUE TITLE
Update value of primary key

### ISSUE THREAD

**Issue by juanludukeboss** [mevdschee/php-crud-api#506]
Hi, I'am using your API 1 year ago and its amazing, I like it. But, now I have a problem. I need update the value of primary key of a table, but is not working. 
I explain the problem: I have a table 'users' with the field primary key 'id_user' and othe field 'name_user'. So, I need update the values of records but the API not updated the value of primary key.

Method and URL from request:
PUT  => https://{myserver}/api.php/records/users/100
Fields request:
{
 id_user.     : 150,
name_user : 'Sam Lee'
}

Response : 1

The response is like correct, the value 'name_user' is updated perfectly, but the value 'id_user' not change to new value 150 and the other fields of table are updated perfect. The field primary key is the unique field that not update. 

NOTE: If I execute the update action directly about MySQL working correctly, only fail with the API.

What is happening?, Why 'name_user' updated but not change the value of primary key 'id_user'?

**Comment by mevdschee** [comment]
Thank you for reporting this issue. I think you should not (read: never, because it is wrong to do so) update the primary key value. So I do not see this as a problem. Can you explain why you want to update the primary key value?

see: https://stackoverflow.com/questions/3838414/can-we-update-primary-key-values-of-a-table

**Comment by juanludukeboss** [comment]
The field "id_user" is foreign key (Update cascade and delete restrictions) in other tables "booking" and "transactions". So, I want change the primary key, because the primary key "id_user" is the e-mail of user, and if the user cancel his account, I don't want delete the records de "booking" and "transactions", I want override his "id_user" (e-mail) with a hash in this primary key. The object of this, is not delete records.
I can't update this value with the API, this value not change never, but the other fields from table "users" are change without problem. It's possible that the problem is that "id_user" is foreign key in other tables?.
In MySQL directly no has a problem, the problem is with the API.

**Comment by mevdschee** [comment]
@juanludukeboss Thank you for your explanation. The fact that MySQL supports something does not make it a good idea to do it. You should not use fields with meaning as primary keys. Again, this is about good data management. If you have foreign keys pointing to the record then it would be a bad idea to update the primary key value as it would cause data inconsistencies or orphaned records.

I would add an autoincrementing primary key named 'id' to the table and convert the current primary key to an index with an unique constraint. Also adjust your foreign keys, to reflect the new type and values.

I know it is a lot of work, but this is how it should be done.

>It's possible that the problem is that "id_user" is foreign key in other tables?

Yes, I am not aware of a restriction in the software, although if there is one, I am not going to remove it.

**Comment by juanludukeboss** [comment]
Ok, So I will change the primary_key in the "users" table. I will create a new field 'email_user' and the problem will be solved.

Thanks for your help.
