### ISSUE TITLE
PUT, DELETE, POST not working for some reason.

### ISSUE THREAD

**Issue by kimeeo** [mevdschee/php-crud-api#51]
Hi thanks for writing wounder full API. this is super work.

I am facing issues with PUT, DELETE, POST none of the method works. in my case.

GET works well.

**Comment by kimeeo** [comment]
Try this with 

PUT http://kimeeo.com/restDemo/api.php/categories/2
name=my_name

POST
http://kimeeo.com/restDemo/api.php/categories
name=my_name

DELETE
http://kimeeo.com/restDemo/api.php/categories/2

all it does is return null.

**Comment by mevdschee** [comment]
I would love to help, but I need more information. Which database engine do you use? Which SQL file did you load? What platform are you on? Which client do you use (like PostMan or curl)? Please provide more information.

**Comment by mevdschee** [comment]
Went to "http://editor.swagger.io/" and clicked "File" - "Import URL" and entered "http://kimeeo.com/restDemo/api.php". There I tested your API and it works fine!

**Comment by kimeeo** [comment]
Which database engine do you use.
-> MySQL

 Which SQL file did you load
->blog_mysql.sql

What platform are you on?
-> PHP 5.6

Which client do you use
-> PostMan

As I said,  GET is working

but if PUT, DELETE, POST it reutnr's null

**Comment by kimeeo** [comment]
My Bad, Something was wrong at my end.

**Comment by mevdschee** [comment]
No problem, enjoy the software!

**Comment by clh021** [comment]
Hey! @kimeeo  What wrong? Me too.

@mevdschee  Maybe this tool should write some log or debug.
return null. And no more .I 'm cray......

**Comment by mevdschee** [comment]
I don't know, probably returning an header with the error message would make most sense.. but only in the case some debug flag is true.. for security reasons.. or yes.. logging.. that could also work..

**Comment by xouaib** [comment]
@mevdschee hi dear,
pl i create CRUD system API using PHP and MySQL, then the POST not working :

<?php
include 'config/database.php';
if ($_POST) {

    try {

        $query = "INSERT INTO products SET p_name=:name, p_description=:description, p_price=:price";

        $stmt = $con->prepare($query);

        $name = $_POST['name'];
        $description = $_POST['description'];
        $price = $_POST['price'];

        $stmt->bindParam(':name', $name);
        $stmt->bindParam(':description', $description);
        $stmt->bindParam(':price', $price);

        if ($stmt->execute()) {
            echo json_encode(array('result' => 'success'));
        } else {
            echo json_encode(array('result' => 'fail'));
        }
    } catch (PDOException $exception) {
        die('ERROR: ' . $exception->getMessage());
    }
}


the database file contains already all header that we need , i check the CREATE with POST method using POSTMAN but not working 

![image](https://user-images.githubusercontent.com/41961680/58215620-40087b80-7cea-11e9-8365-b8f28a9f1e52.png)

CORDIALLY
CORD

**Comment by mevdschee** [comment]
@xouaib it is probably another exception, please replace "PDOException" with "Exception" or "Throwable" depending on your PHP version.

**Comment by xouaib** [comment]
i still strive with it without ay advance Mr @mevdschee 
![1](https://user-images.githubusercontent.com/41961680/58295847-98aa4800-7dc0-11e9-88c4-b78f148703d5.PNG)
![2](https://user-images.githubusercontent.com/41961680/58295848-9942de80-7dc0-11e9-9465-062b47a4e4e1.PNG)

**Comment by mevdschee** [comment]
You are now sending post parameters and expect it to be a JSON document, that's not correct.

**Comment by xouaib** [comment]
@mevdschee thank you so much it's working perfectly
