### ISSUE TITLE
RDS Connection

### ISSUE THREAD

**Issue by emond07** [mevdschee/php-crud-api#511]
Im want to connect to AWS RDS ,
hostname: xxxxl.us-east-1.rds.amazonaws.com
username: xxx
password: xxx

im looking for Hostname where i can put it?in config I have only  seeing this:

$config = new Config([
    'username' => 'xxx',
    'password' => 'xxx',
    'database' => 'xyz_db',
]);

THanks

**Comment by mevdschee** [comment]
Add 'hostame' above 'username' and set it, like this:

    $config = new Config([
        'hostname' => 'xxx.amazonaws.com',
        'username' => 'xxx',
        'password' => 'xxx',
        'database' => 'xyz_db',
    ]);

Hope that helps. Kind regards,

**Comment by mevdschee** [comment]
Thank you for reporting this issue. Can you please respond to your other open issue?

You can use:

    $config = new Config([
    'hostname' => 'xxx',
    'username' => 'xxx',
    'password' => 'xxx',
    'database' => 'xyz_db',
    ]);

Thanks,

**Comment by emond07** [comment]
thanks for the quick reply.. im getting this error when putting the hostname in my config

![sc1](https://user-images.githubusercontent.com/17446488/54251092-22e45d80-4581-11e9-8e7d-c832b5341fc0.png)

**Comment by emond07** [comment]
btw im using v2

**Comment by Disane87** [comment]
Then your hostname is not a valid hostname and contains i.e. special chars. whitespaces or some control chars like „cr“ and/or „lf“.

You should check that.

**Comment by Disane87** [comment]
The hostname shouldn‘t contain the port.

**Comment by mevdschee** [comment]
You don't have to change the 'getDefaultAddress' implementation.

**Comment by mevdschee** [comment]
I'm glad you got it working and the ticket now also describes how it should be done. Thank you @Disane87 for your help. I'm closing the ticket now.
