### ISSUE TITLE
v2 generated OAS without parameters

### ISSUE THREAD

**Issue by dun74fr** [mevdschee/php-crud-api#512]
Dear developer,
I just switch from v1 to v2.
when I open the generated api /openapi with swagger as before I can see that the routes do not work. The base URL is not set and there are no parameters in the methods.
Adding a server : parameter I can access the basic functions, but no filters, includes etc...
Is there something I missed?
Kindly
Julien

**Comment by mevdschee** [comment]
Hi Julien, Thank you for your feedback. v2 is a complete rewrite (it also uses openapi instead of swagger). You seem to have stumbled upon a regression. I will try to (re)add 'base URL' and 'parameters' as you have asked. Kind regards, Maurits

**Comment by mevdschee** [comment]
I have added a 'base URL' alternative: cbd63d57dc91e96bcb56c830dfeb8e8514165453

I will add the parameters in another commit.

**Comment by mevdschee** [comment]
I have added 'parameters' in commit: 229b08990cfb06d9d9671e06b9374ed351d27100

I have tested using: http://editor.swagger.io/

**Comment by mevdschee** [comment]
I have released v2.0.19 that contains this functionality.

**Comment by dun74fr** [comment]
Thanks a lot for your work.
It is working.
I just found one little enhancement to make. The array[string] parameters like "join" should have an attribute "explode: true" if you do not put it the client joins them in one string like one path.

**Comment by mevdschee** [comment]
@dun74fr Like this?

**Comment by dun74fr** [comment]
Great!
One more feedback.. this one is more tricky I think.
If you have a model like this :
Client
------
id
name
state_id
company_id

Company
---------
id
name
state_id

State
-----
id
name

(the model is not a real one, just to illustrate the case)

If I GET the Clients, and I want to join the State (client level), the Company and the State of the Company: join=State&join=Company,State
The resulting JSON contain the State at the client level, but the Company is replaced by the State.
The same occurs if I query join=State&join=Company : the Company is replaced by the State because both levels contain the same Entity.

I hope it is clear enough.
Thanks for the great work.
Julien
