### ISSUE TITLE
join replaces entity (wrongly detects habtm)

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#513]
One more feedback.. this one is more tricky I think.
If you have a model like this:

```
Client
------
id
name
state_id
company_id

Company
---------
id
name
state_id

State
-----
id
name
```

(the model is not a real one, just to illustrate the case)

If I GET the Clients, and I want to join the State (client level), the Company and the State of the Company: join=State&join=Company,State
The resulting JSON contain the State at the client level, but the Company is replaced by the State.
The same occurs if I query join=State&join=Company : the Company is replaced by the State because both levels contain the same Entity.

I hope it is clear enough.
Thanks for the great work.
Julien

_Originally posted by @dun74fr in https://github.com/mevdschee/php-crud-api/issues/512#issuecomment-473391513_

**Comment by mevdschee** [comment]
@dun74fr This used to be the case in v1, but should not be the case in v2. Are you sure this is what you see?

**Comment by dun74fr** [comment]
A real example
```
records/Territory?join=Location

{
  "records": [
    {
      "id": "17d002aa-11a0-d0ff-463c-b3800d8f6f19",
      "name": "CBBA-ARQUE-COCAMARCA",
      "code": "CBBA-ARQUE-01",
      "type": "COLD",
      "municipality_id": "60ff91aa-b651-490b-8e10-16a0e0ff7244",
      "for_4x2": 1,
      "for_4x4": 1,
      "for_moto": 0,
      "Location": [
        {
          "id": "068b74f3-919e-4284-ab32-793aed8c4acf",
          "hub_id": "004726",
          "name": "PATACALLANI (Arque)",
          "municipality_id": "60ff91aa-b651-490b-8e10-16a0e0ff7244",
          "latitude": -17.6917,
          "longitude": -66.4992,
          "population": 184,
          "comment": "",
          "congregation_id": null,
          "territory_id": "17d002aa-11a0-d0ff-463c-b3800d8f6f19",
          "language": "",
          "last_visit": "0000-00-00"
        },...
```
Territory -> Location (OK)

```
records/Territory?join=Location&join=Municipality
"records": [
    {
      "id": "17d002aa-11a0-d0ff-463c-b3800d8f6f19",
      "name": "CBBA-ARQUE-COCAMARCA",
      "code": "CBBA-ARQUE-01",
      "type": "COLD",
      "municipality_id": {
        "id": "60ff91aa-b651-490b-8e10-16a0e0ff7244",
        "state_id": "e1692b8e-2a69-49c9-9ff5-7e1ee11a91b0",
        "name": "Arque - Arque"
      },
      "for_4x2": 1,
      "for_4x4": 1,
      "for_moto": 0,
      "Location": [
        {
          "id": "60ff91aa-b651-490b-8e10-16a0e0ff7244",
          "state_id": "e1692b8e-2a69-49c9-9ff5-7e1ee11a91b0",
          "name": "Arque - Arque"
        },
```
The content of Location is now changed..

**Comment by mevdschee** [comment]
Can you test the latest version and see whether or not your issue is resolved?

**Comment by dun74fr** [comment]
Bravo!
it works as expected now.
Thank you so much

**Comment by mevdschee** [comment]
Can you retest with the latest? It only tries a habtm relation when there is no belongsTo or hasMany relation found.

**Comment by mevdschee** [comment]
I covered this issue in a test case, see: https://github.com/mevdschee/php-crud-api/blob/master/tests/functional/001_records/079_read_post_with_categories.log

**Comment by mevdschee** [comment]
I really appreciate the time and effort you took to report and explain this complicated issue. Thank you very much.
