### ISSUE TITLE
exmple for upload image ??

### ISSUE THREAD

**Issue by yaasoof** [mevdschee/php-crud-api#514]
i want an exmple to upolad image to mysql >> thx

**Comment by mevdschee** [comment]
![image](https://user-images.githubusercontent.com/1288217/54561180-5893a700-49c4-11e9-8fb6-81a8c782691c.png)

**Comment by yaasoof** [comment]
in this case we are save image as base64 in db ?? that will be more size and less performance for db

**Comment by mevdschee** [comment]
The exchange of binary data in the API is in base64 format. In the database the image is stored in a binary field. The api is smart enough to "detect/reflect" this binary field and convert the data to and from base64.

**Comment by yaasoof** [comment]
so what type of filed in mysql ??

**Comment by mevdschee** [comment]
blob

**Comment by yaasoof** [comment]
![التقاط](https://user-images.githubusercontent.com/25013814/54778025-b6262e80-4c24-11e9-8469-1493f57af99d.PNG)

is it best practices to save image in db ??
 that will increase size of db ??
 save image in folder and save name of image in db is it better ??

**Comment by Disane87** [comment]
It depends heavily on the data size imho. If you have much small files it’s okay. But if you have large files like db backups, large logs, cad/cam files, videos or music projects, I would recommend to save a reference and meta data in the db with a relation to the physical folder in the file system.

**Comment by mevdschee** [comment]
@Disane87 I completely agree, I would recommend object storage (such as s3 or swift) to upload the file and then store the object url in the database.

**Comment by yaasoof** [comment]
how stander is large or small file .. file less than 2 mb its small or large ??
and in case of large file iwill send two request one for storge file and return the path of file and request info to mysql ??

**Comment by mevdschee** [comment]
> .. file less than 2 mb is small otherwise it is large?

That sounds reasonable to me.

> ... in case of a large file will I send two request? One to store the file (that returns the path of the file) and one to store that info into MySQL?

Yes indeed.

**Comment by yaasoof** [comment]
thx for your help and your patience ?? 
yes iam not native English speaker ...

**Comment by mevdschee** [comment]
You are welcome. I'm glad I could help! Enjoy the software.
