### ISSUE TITLE
Batch Update not working

### ISSUE THREAD

**Issue by emond07** [mevdschee/php-crud-api#515]
I can update using PUT /1 but when try to make batch update like: PUT /1,2,3 im facing an error. please see screen shots

![sc122](https://user-images.githubusercontent.com/17446488/54525550-6be84780-49af-11e9-8230-d747a738104e.png)
![sc123](https://user-images.githubusercontent.com/17446488/54525600-8c180680-49af-11e9-946e-c380f1c43c7f.png)

**Comment by mevdschee** [comment]
You should set the content per record, so an update for "PUT /records/vlist/12,13,14" should send content:

    [{"Status":"xxx"},{"Status":"xxx"},{"Status":"xxx"}]

I hope that helps.

**Comment by mevdschee** [comment]
Please also read this section of the README: 

https://github.com/mevdschee/php-crud-api/blob/master/README.md#batch-operations

**Comment by emond07** [comment]
thanks for this. more power
