### ISSUE TITLE
Filter with clausule similar to OR

### ISSUE THREAD

**Issue by juanludukeboss** [mevdschee/php-crud-api#516]
Hi,
it's possible filter in the API similar to clausule OR in SQL?. So, I have a value for search and I need to filter by fields "name" or "town". Now the API only accept concatenate filters, similar to AND, but not similar to OR.

Example API now: https://{server}/api.php/records/bookings?filter=name,eq,{PARAM_SEARCH}&filter=town,eq,{PARAM_SEARCH}
This is similar to AND in SQL

But, I need to search similar to OR. It's possible to do it? How should I do it?

**Comment by mevdschee** [comment]
You can use filter1= and filter2=, see:

https://github.com/mevdschee/php-crud-api/blob/master/README.md#multiple-filters

**Comment by juanludukeboss** [comment]
this is only valid with numbers, but I need it with strings

**Comment by mevdschee** [comment]
This is AND:

    https://{server}/api.php/records/bookings?filter=name,eq,{PARAM_SEARCH}&filter=town,eq,{PARAM_SEARCH}

This is OR:

    https://{server}/api.php/records/bookings?filter1=name,eq,{PARAM_SEARCH}&filter2=town,eq,{PARAM_SEARCH}

Please read and compare carefully :-)

**Comment by juanludukeboss** [comment]
Sorry, I don't to read "filter1" and "filter2".
Thank you very much!! :)

**Comment by mevdschee** [comment]
Thank you for asking the question. Enjoy the software!
