### ISSUE TITLE
Error when trying to use specific row

### ISSUE THREAD

**Issue by nobobo1234** [mevdschee/php-crud-api#517]
Hey! I just installed your api on my server and everything works. But everytime I try something specific like `/api.php/records/projects/1` I get an error: 
```json
{
    "code": 9999,
    "message": "Argument 1 passed to Tqdev\\PhpCrudApi\\ColumnCondition::__construct() must be an instance of Tqdev\\PhpCrudApi\\ReflectedColumn, null given, called in /blah/blah/blah/api.php on line 1988"
}
```
I get this for all requests methods. I am using PHP 7.2 on my webserver with cPanel.

**Comment by mevdschee** [comment]
In order to get a specific row by primary key, you need to specify the primary key (set a column to be the primary key).

See: https://www.youtube.com/watch?v=VKBindYG--8
