### ISSUE TITLE
How to save client IP address to MySQL?

### ISSUE THREAD

**Issue by shelovemee** [mevdschee/php-crud-api#519]
Hi,

I have three columns in MySQL database,

id
stuff
ip address

I post json from client side, the server is running php-crud-api.

{id:1, stuff:"test"}

How can i insert client ip address into "ip address" field via php-crud-api? Thanks

**Comment by mevdschee** [comment]
Hi. Thank you for reporting this issue. This is currently not supported. I registered it this as a feature request. Kind regards, Maurits

**Comment by shelovemee** [comment]
Hi mevdschee,

Thanks for your reply

**Comment by shelovemee** [comment]
Hi mevdschee,

Can i use middlewares or controllers to to achieve this goal? Logging client ip address is a must-have feature in our system. Thanks

**Comment by mevdschee** [comment]
You can use the sanitation handler for this:

    'sanitation.handler' => function ($operation, $tableName, $column, $value) {
        return $column=='ip_address' ? $_SERVER['REMOTE_ADDR'] : $value;
    },

Make sure you also enable the 'sanitation' middleware.

**Comment by mevdschee** [comment]
See if this works for you

**Comment by mevdschee** [comment]
I added some extra middleware for this named 'ipAddress'. See if it does what you want.

**Comment by mevdschee** [comment]
Please share your feedback.

**Comment by mevdschee** [comment]
Source is here:

https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Middleware/IpAddressMiddleware.php

**Comment by mevdschee** [comment]
I added a test case:

https://github.com/mevdschee/php-crud-api/blob/master/tests/functional/001_records/080_add_barcode_with_ip_address.log

**Comment by shelovemee** [comment]
Hi mevdschee,

Thanks for your fast reply. I am really new in PHP. Do i need to upload the whole php-crud-api/src/Tqdev folder to my server? Cause i see "namespace Tqdev\PhpCrudApi\Middleware; use Tqdev\PhpCrudApi\Column\ReflectionService;" in IpAddressMiddleware.php.

Then i should put IpAddressMiddleware.php in the same folder of api.php, and add "'middlewares' => 'pAddressMiddleware.php' in api.php.  Am i right? By the way. Do middlewares have any performance hit? Sorry i have too much questions.:)

**Comment by mevdschee** [comment]
Just download the latest version. It has the middleware included. Then add the word 'ipAddress' to the 'middlewares' config parameter to enable it. Also add the 'ipAddress.columns' config parameter to specify the column you want to have filled.

**Comment by mevdschee** [comment]
Please report usage questions in a new issue.

**Comment by shelovemee** [comment]
Hi mevdschee,

It works now. Thanks for your great work!
