### ISSUE TITLE
Return the SQL error on DATA_INTEGRITY_VIOLATION

### ISSUE THREAD

**Issue by palmtop** [mevdschee/php-crud-api#520]
Finding out the actual problem is quite difficult, when you are getting the data integrity violation message (I typically had misspelled field names or field without default value). To help debugging I would recommend to add the SQL result to the returned error json.
For example in the src/Tqdev/PhpCrudApi/Api.php file in the handle method: 

```
if (strpos(strtolower($e->getMessage()), 'default value') !== false) {
                    return $this->responder->error(ErrorCode::DATA_INTEGRITY_VIOLATION, '',**$e->getMessage()**);
```
I simply added the $e->getMessage() to the error function parameters, but if for security reasons this is not recommended, it can be done only if the debug flag is set.

**Comment by mevdschee** [comment]
>if for security reasons this is not recommended

Yes, indeed, this is a problem.

> it can be done only if the debug flag is set.

This is a good implementation suggestion.

**Comment by mevdschee** [comment]
How about this?

**Comment by palmtop** [comment]
That is also excellent.

**Comment by palmtop** [comment]
I am testing it now (looking at the request in Chrome DevTools and EDGE), but it seems that I get the 409 error response but I get only an empty body and only the content-type application/json and no other headers.

**Comment by palmtop** [comment]
I found the problem, in the handle member, when a specific error code is selected, the response is immediately returned, and the debug part is not running. I made a change in the code and now it works:

```
  public function handle(Request $request): Response
    {
        $response = null;
        try {
            $response = $this->router->route($request);
        } catch (\Throwable $e) {
			
			$response = $this->responder->error(ErrorCode::ERROR_NOT_FOUND, $e->getMessage());
			
            if ($e instanceof \PDOException) {
                if (strpos(strtolower($e->getMessage()), 'duplicate') !== false) {
                    $response = $this->responder->error(ErrorCode::DUPLICATE_KEY_EXCEPTION, '');
                }
                if (strpos(strtolower($e->getMessage()), 'default value') !== false) {
                    $response = $this->responder->error(ErrorCode::DATA_INTEGRITY_VIOLATION, '');
                }
                if (strpos(strtolower($e->getMessage()), 'allow nulls') !== false) {
                    $response = $this->responder->error(ErrorCode::DATA_INTEGRITY_VIOLATION, '');
                }
                if (strpos(strtolower($e->getMessage()), 'constraint') !== false) {
                    $response =$this->responder->error(ErrorCode::DATA_INTEGRITY_VIOLATION, '');
                }
            }
            
			if ($this->debug) {
                $response->addHeader('X-Exception-Message', $e->getMessage());
                $response->addHeader('X-Exception-File', $e->getFile() . ':' . $e->getLine());
            }
        }
        return $response;
    }
```

However the response body is still empty and Chrome Dev-Tool is not showing the headers, but EDGE do show them:

```
   Connection: Keep-Alive
   Content-Length: 50
   Content-Type: application/json
   Date: Fri, 29 Mar 2019 19:02:42 GMT
   Keep-Alive: timeout=5, max=100
   Server: Apache/2.4.18 (Ubuntu)
   X-Exception-File: /home/laco/sambapublic/web/mysql/api.php:2016
   X-Exception-Message: SQLSTATE[HY000]: General error: 1364 Field 'Info' doesn't have a default value
```

**Comment by mevdschee** [comment]
How about this?

**Comment by palmtop** [comment]
I have just tested it, and it works now, but there is still one problem:

If  I am using it from a different server, the CORS middleware is not inserting the headers for error messages. I could patch it, by always adding an Access_Control-Allow-Origin: * in the Respone constructor, but this is not nice at all.

**Comment by mevdschee** [comment]
Okay, I can't reproduce (yet). Is the 'cors' middleware listed as the first middleware?

**Comment by mevdschee** [comment]
My test:

    $ curl -i http://localhost:8000/api.php/records/posts/222 -H 'Origin:localhost'
    HTTP/1.1 404 Not Found
    Host: localhost:8000
    Date: Tue, 02 Apr 2019 20:12:19 +0200
    Connection: close
    X-Powered-By: PHP/7.2.15-0ubuntu0.18.04.2
    Content-Type: application/json
    Content-Length: 48
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Origin: localhost

    {"code":1003,"message":"Record '222' not found"}

It shows a "Access-Control-Allow-Origin" header.

**Comment by mevdschee** [comment]
I opened a new ticket for the missing CORS header.

**Comment by Mlayeh** [comment]
hii, i have the same problem and i can't solve it

**Comment by mevdschee** [comment]
> hii, i have the same problem and i can't solve it

Please open a new issue
