### ISSUE TITLE
Code 9999 - Reflected Column Error

### ISSUE THREAD

**Issue by maztam** [mevdschee/php-crud-api#521]
I use v2, and want to POST ... 

i receive this error 

Tqdev\PhpCrudApi\ColumnsBuilder::quoteColumnName() must be an instance of Tqdev\PhpCrudApi\ReflectedColumn, null given, called in

and then, i try to ... /api.php/records/post/3, and get this error :  

"code":9999,"message":"Argument 1 passed to Tqdev\\PhpCrudApi\\ColumnCondition::__construct() must be an instance of Tqdev\\PhpCrudApi\\ReflectedColumn, null given, called in

please help

**Comment by mevdschee** [comment]
Do you have a primary key defined on the table?

**Comment by maztam** [comment]
in my case, i have two different primary key
<img width="717" alt="Screen Shot 2019-03-29 at 22 34 43" src="https://user-images.githubusercontent.com/5019045/55244270-76d68e00-5273-11e9-9b44-50263ad4e05b.png">

**Comment by mevdschee** [comment]
I'm sorry, but composite primary keys are not supported, as stated in the readme.

**Comment by maztam** [comment]
Ok, sorry ... and thanks for information.. maybe i must read again the readme

**Comment by mevdschee** [comment]
No problem, thank you for reporting this issue.
