### ISSUE TITLE
Error 500 on insert

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#522]
Hi,
I have an issue while trying to insert a record with the following code

```javascript
const insert=(table,body) => {
    fetch([baseUrl,"records",table].join("/"),
        {
            method: "POST",
            body:JSON.stringify(body)
        }
    )
    .then(response =>response.json())
    .then(data => console.log(data))
    .catch ((err)=> console.log(err));
};

insert("client",{name:"New name"});
/*
create table client(
    id   int auto_increment primary key,
    name varchar(50) not null
);
*/
```
In php logs:
Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'Tqdev\PhpCrudApi\RecordController' does not have a method 'insert' in C:\....\api.php on line 2905

Any help? I am stuck
Thank you

Note : similar select (GET), update (PUT) and delete (DELETE) similar functions are working well.

**Comment by mevdschee** [comment]
Thank you for reporting this issue. Can you post line 2905 of api.php?

**Comment by thipages** [comment]
Hi,
[this one](https://github.com/mevdschee/php-crud-api/blob/master/api.php#L2905)

**Comment by mevdschee** [comment]
Did you search and replace "create" with "insert" ? Can you try with a clean download? Can you post the URL?

**Comment by thipages** [comment]
wahoo, so sorry.
api.php has been modified (create->insert) during a refactoring
Everything fine now.
Thanks!!!!!

**Comment by mevdschee** [comment]
No probs.. Enjoy the software!
