### ISSUE TITLE
CORS middleware is not inserting the headers for error messages

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#523]
I have just tested it, and it works now, but there is still one problem:

If  I am using it from a different server, the CORS middleware is not inserting the headers for error messages. I could patch it, by always adding an Access_Control-Allow-Origin: * in the Respone constructor, but this is not nice at all.

_Originally posted by @palmtop in https://github.com/mevdschee/php-crud-api/issues/520#issuecomment-479093871_

**Comment by mevdschee** [comment]
Okay, I can't reproduce (yet). Is the 'cors' middleware listed as the first middleware?

My test:

    $ curl -i http://localhost:8000/api.php/records/posts/222 -H 'Origin:localhost'
    HTTP/1.1 404 Not Found
    Host: localhost:8000
    Date: Tue, 02 Apr 2019 20:12:19 +0200
    Connection: close
    X-Powered-By: PHP/7.2.15-0ubuntu0.18.04.2
    Content-Type: application/json
    Content-Length: 48
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Origin: localhost

    {"code":1003,"message":"Record '222' not found"}

It shows a "Access-Control-Allow-Origin" header.

**Comment by mevdschee** [comment]
@palmtop Do you have some more input?

**Comment by palmtop** [comment]
I have done some tests, and here are the results. I have a database, where none of the fields have default value, so the insert fails unless I specify correctly all field names.

Here is a successful insert (POST):
```
curl -i "http://boss.laco.hu/mysql/api.php/records/maches" --data "Name=haha^&Position=^&Ping=^&Ping_type=^&Network=^&wakeURL=^&offURL=^&infoURL=^&info2URL=^&Info=^&Info2=^&setupURL=^&menuURL=" -H "Origin: http://vu1804s-nodejs.laco.hu:3000"
HTTP/1.1 200 OK
Date: Thu, 04 Apr 2019 04:46:49 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Length: 2
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://vu1804s-nodejs.laco.hu:3000
Content-Type: application/json

20
```

If I change the field name to Name1:

```
curl -i "http://boss.laco.hu/mysql/api.php/records/maches" --data "Name1=haha^&Position=^&Ping=^&Ping_type=^&Network=^&wakeURL=^&offURL=^&infoURL=^&info2URL=^&Info=^&Info2=^&setupURL=^&menuURL=" -H "Origin: http://vu1804s-nodejs.laco.hu:3000"
HTTP/1.1 409 Conflict
Date: Thu, 04 Apr 2019 04:51:37 GMT
Server: Apache/2.4.18 (Ubuntu)
Content-Length: 50
X-Exception-Message: SQLSTATE[HY000]: General error: 1364 Field 'Name' doesn't have a default value
X-Exception-File: /home/laco/sambapublic/web/mysql/api.php:2015
Content-Type: application/json

{"code":1010,"message":"Data integrity violation"}
```
Here the CORS headers are missing. As the documentations states, CORS is enabled by default, so I have no any specific middleware settings, beside the database name, username and password I have only debug=true in my config.

**Comment by mevdschee** [comment]
Thank you! I was able to reproduce the problem and I will try to propose a fix for this problem. Please hold on.

**Comment by palmtop** [comment]
Thank you, no hurry, at the moment I can live with my not-so-nice workarround.

**Comment by mevdschee** [comment]
This is not an easy to fix problem. Please have some patience.

**Comment by palmtop** [comment]
Thank you for working on it, I spent some time on trying to find the problem and concluded the same, that the error should be catched earlier. But no any concrete ideas...

**Comment by mevdschee** [comment]
I think I solved it. Can you verify?

**Comment by mevdschee** [comment]
Released a new version with the fix. Let me know how you like it :-)

**Comment by palmtop** [comment]
Thank you, now it is working :-), it solves my initial problem.

**Comment by mevdschee** [comment]
Thank you for your feedback.
