### ISSUE TITLE
customization.beforeHandler transform POST in PUT

### ISSUE THREAD

**Issue by duskovit** [mevdschee/php-crud-api#525]
Hi,
Is possible if two columns already exist in table, transform the current api POST call in a PUT call with the same data?

For example:
POST DATA:
```
{
"sku": "123456",
"model": "bla123",
"price": "10"
}
```
PUT DATA: 
```
{
"price": "10"
}
```

**Comment by mevdschee** [comment]
Do you mean support for insert or update (upsert)? See #334
