### ISSUE TITLE
commenting the last lines of api.php

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#529]
Hi,
is it possible to comment the last lines of api.php?

The reason is that it allows to sync and use the repository and get the file without changes.

I think that this change will not break the 'single file php script' principle since these last lines are changed anyway for setting the right db access. Also php-crud-ui is build by commenting the last lines ;-)

for info, my use case is that I wrote a class for managing the different handlers I need.

**Comment by mevdschee** [comment]
Thank you for reaching out. If you are changing the functionality, then I recommend to adjust the source code in the `src` tree and re-run the `build.php` script. Would this workflow work for you?

**Comment by thipages** [comment]
Hi,
Seems that I am the only supporter for such change.
No problem for me to change index.php
