### ISSUE TITLE
Suggestion:delete use filter

### ISSUE THREAD

**Issue by chaofml** [mevdschee/php-crud-api#531]
I am happy to use this library  in my work. It's very powerful  with short code.   Howerver ,when I use this to delete the record which has many to many relation  without primary key,  I find it's very inconvenient. can add new features  like delete can use  filter? Besides, can  insert or update record be customized  with param ,  just like json {success:true,affect:1}?

**Comment by mevdschee** [comment]
>many to many relation without primary key

This scenario is not supported. Every table should have a primary key.

>add new features like delete can use filter?

This scenario is not supported as it would be too easy to accidentally wipe the database.

>Besides, can insert or update record be customized with param , just like json {success:true,affect:1}?

Currently, success is reported as a status 200 and the result not being a 'null' json value.

**Comment by chaofml** [comment]
Thank you for your answer. Now, I am using the Extjs (a js framework ) in my work ,when success  the form need to  be reponsed with json ,although,the problem can be solved in anther way .I just hope the crud library  more powerful and flexible  with configs or middlewares or AOP.

**Comment by mevdschee** [comment]
Thank you. Maybe #119 can be of use to you.

Also you can use/write your own middleware if you want.

Kind regards, Maurits

**Comment by chaofml** [comment]
Thank you.
