### ISSUE TITLE
Route not Found

### ISSUE THREAD

**Issue by david2dia** [mevdschee/php-crud-api#532]
Hello,

Locally I am no problem to use the API which is great by the way 
I take this opportunity to say thank you :)

On the other hand when I want to upload it to my server 1&1 all routes respond not found with error 1000, it seems that the router can't save the routes, or rather that the route bind is not correct, no matter how much I try all the Htaccess configurations nothing does there so I ask for help.

Best Regards

**Comment by botnyx** [comment]
fyi: 
im running it on apache, and i can get the routes without problems. ( https://myhost/records/posts )

this is what i use in my htaccess.
<pre>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [L]
</pre>

i hope it helps.

**Comment by mevdschee** [comment]
Can you see whether or not the `$_SERVER['PATH_INFO']` variable is set?

Add the following line to the API script:

    die(var_dump($_SERVER['PATH_INFO']));

Let me know what it prints.

**Comment by david2dia** [comment]
Lucky Dip
$_SERVER['PATH_INFO'] is null

so I added at the beginning of API script, 

```
if(!isset($_SERVER['PATH_INFO'])) ){
    $_SERVER['PATH_INFO'] = str_replace('api/', '', $_SERVER['SCRIPT_URL']) ;
}
```

And the problem is solved.
If you have something more elegant, I'm listening.

**Comment by mevdschee** [comment]
Sounds good and if it works for you I'm happy. :-)

**Comment by david2dia** [comment]
I completely agree with you. 
unfortunately on this server I have no control over the installation of php.

Thanks again for the solution and your reactivity, the issue is closed
