### ISSUE TITLE
v2 - multiTenancy.handler not working

### ISSUE THREAD

**Issue by resident0** [mevdschee/php-crud-api#536]
I've configured the handler as described in the documentation.

I dug around a little and found that when a table is initially reflected in the ReflectedTable class the tenant column is present however, when the hasColumn method is called it is not.

**Comment by mevdschee** [comment]
Thank you for your report. It is not entirely clear to me what is happening. Can you elaborate or provide a test case?

**Comment by mevdschee** [comment]
NB: This test should ensure that the handler is working:  

https://github.com/mevdschee/php-crud-api/blob/master/tests/functional/001_records/063_list_kunsth%C3%A5ndv%C3%A6rk.log

**Comment by resident0** [comment]
I didn't describe that very well. The handler is working, per your test. After closer examination it turns out that my authorization.columnHandler callback was interfering with multiTenancy.handler. I appreciate your prompt response and I'm sorry to have taken your time for a non issue.

**Comment by mevdschee** [comment]
Hey, no problem.. I'm glad you got it fixed! Enjoy the software.
