### ISSUE TITLE
Error when adding 'authorization.tableHandler' 

### ISSUE THREAD

**Issue by ano** [mevdschee/php-crud-api#538]
I get the following 2 errors

- Fatal error: Uncaught Exception: Config has invalid value 'authorization.tableHandler' 
- Exception: Config has invalid value 'authorization.tableHandler'

when I add

```php
'authorization.tableHandler' => function ($operation, $tableName) {
        return ($operation == "list" || $operation == "read");
    }
```

to my **$config** variable 

```php

$config = new Config([
    'address' => 'localhost',
    'username' => 'root',
    'password' => '',
    'database' => 'datamart',
    'driver' => 'mysql',
    'port' => 3306,
    "controllers" => 'records,openapi,authorization',
    "openApiBase" => '{"info":{"title":"Datamart API","version":"1.0.0"}}',
    'authorization.tableHandler' => function ($operation, $tableName) {
        return ($operation == "list" || $operation == "read");
    }
]);
$request = RequestFactory::fromGlobals();
$api = new Api($config);
$response = $api->handle($request);
ResponseUtils::output($response);
```
What am I doing wrong?

**Comment by ano** [comment]
Ok figured it out after carefully reading the docs. 
- ***authorization*** needs to go into the ***middleware*** section NOT into the ***controllers*** section. 

So the **$config** variable should actually be:

```php
$config = new Config([
    'address' => 'localhost',
    'username' => 'root',
    'password' => '',
    'database' => 'datamart',
    'driver' => 'mysql',
    'port' => 3306,
    "controllers" => 'records,openapi',
    'middlewares' => 'authorization',
    "openApiBase" => '{"info":{"title":"Datamart API","version":"1.0.0"}}',
    'authorization.tableHandler' => function ($operation, $tableName) {
        return ($operation == "list" || $operation == "read");
    }
]);
```

**Comment by ano** [comment]
Now I'm stuck on how to only allow ***list*** and **_read_** permissions on database tables. The following:

```php
'authorization.tableHandler' => function ($operation, $tableName) {
        return ($operation == "list" || $operation == "read");
}
```
doesn't seem to work. Am I missing something here?

**Comment by mevdschee** [comment]
Can you add a "die($operation);" in the handler and ensure that it is called (and the value is set)?

**Comment by ano** [comment]
Hi @mevdschee , thanks for the tip. Is this what you meant

```php
    'authorization.tableHandler' => function ($operation, $tableName) {
        print_r($operation); die($operation); 
        return ($operation == "list" || $operation == "read");        
    }
```
When I do this and print the **$operation** variable, it outputs

```
documentdocument
```

**Comment by ano** [comment]
I'm looking to allow only **read** and **list** access to the tables in the database. Not sure what to write in the **'authorization.tableHandler'** to enable that so any hints would be much appreciated.

**Comment by mevdschee** [comment]
When you call the url you are getting the document operation, so I guess you want that one allowed as well, e.g:

    return in_array($operation, array('list','read','document'));

I hope that helps!

**Comment by ano** [comment]
Ah, perfect...thanks for that. That's the answer I was looking for.

**Comment by mevdschee** [comment]
You are welcome, enjoy the software.
