### ISSUE TITLE
Api does not detect the relationship?

### ISSUE THREAD

**Issue by freddiefish** [mevdschee/php-crud-api#54]
Thanks for this great API code! Just can't figure out how to get related data from a many to one relation. It seems the api code does not detect the relationship. 

When I call 
http://openantwerpen.be/openstadsbestuur/api/documents?include=groups&filter=id,eq,1
I expect a document to return only one group (now it returns all groups)

How can I do this?
Thanks!

**Comment by mevdschee** [comment]
Are there foreign keys between these entities?

**Comment by freddiefish** [comment]
@mevdschee great, just discovered you can setup foreign key constraints in mysql! Now, the api gives only the related group. Thanks. Maybe good to mention this requirement in the readme? Thanks again

**Comment by mevdschee** [comment]
Good idea! Thank you. See: e95d0d1
