### ISSUE TITLE
Mutliple public keys for JWT signature checking

### ISSUE THREAD

**Issue by sebj54** [mevdschee/php-crud-api#540]
Hi there!

I faced a new problem with JWT today. It can be solved easily I guess but I wanted to have your feedback before making any PR :)

So the problem is that there are multiple certificates used by Firebase to sign the JWT. These certificates can be found at this address: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com.
The object contains several certificates (2 in my case, don't know if it's the same for everyone). Each certificate has a `kid` as its key.

Sometimes (I don't know why) Firebase issued a token with a different certificate and that is a problem because php-crud-api does not support the use of several `secret`s to check the JWT.

So, I propose to support multiple keys by allowing to pass an array or a string as the `secret` configuration option.
This will support the actual behavior (having the public key as a string) and allow the system to choose the right public key in an array. For that, we will simply have an array with `kid`s as keys and public certificates as values. Like that, it will be easy to get the public key before we have access to the JWT headers (including `kid`) before checking the JWT signature.

What do you think about it @mevdschee? I can totally do the PR as I will need it in my project.

**Comment by mevdschee** [comment]
>What do you think about it @mevdschee? I can totally do the PR as I will need it in my project.

Yes, please! I'm not sure about the string vs. array thing, but we will figure the exact syntax out later.. once you got it working. :-)

**Comment by mevdschee** [comment]
This is now merged into master. Can you confirm that it is working?

**Comment by sebj54** [comment]
Thanks for the update! Sorry, I've been very busy these last months.

I'm actually testing the master branch to test both features, I'll let you know once I'm done.

**Comment by mevdschee** [comment]
Thank you. You need to set 'jwtAuth.secrets' (note the extra s) and use a "key1:value1,key2:value2" scheme.

**Comment by sebj54** [comment]
I tested it, I don't see any problem with this feature! 👌

**Comment by mevdschee** [comment]
This is now in v2.5.0
