### ISSUE TITLE
Tried lots, but can't get it to work.

### ISSUE THREAD

**Issue by gfmoore** [mevdschee/php-crud-api#541]
So I've used the previous version in many projects and had no issues.

I've dropped in the new version and changed the config at the bottom.

So if I try http://127.0.0.1/Territory/api.php/map
I get 
![image](https://user-images.githubusercontent.com/22768967/58273157-fe2e1280-7d87-11e9-827c-aa4ade56b041.png)
i.e. route /map not found.

The old version works fine.

Clearly? it's not finding a way to access the database.

I've tried too many things to mention, but I'm using xampp on win 10 which I've just updated to the latest version with PHP 7.3.5

I'm at a loss. I can manage with the old version so it's not critical, but would like to keep up. :)

Thanks
Gordon

**Comment by mevdschee** [comment]
Hi there! Please try "api.php/records/map" instead of "api.php/map".. that is the new syntax! Read the readme for more explanation about new features!

**Comment by gfmoore** [comment]
Oh what an idiot I am. Just never saw the implications of that. I didn't get the sense of it. It's so obvious. Thanks.

:)

**Comment by mevdschee** [comment]
I'm glad you got it working again. Enjoy the software!
