### ISSUE TITLE
sqlite database and need of sys/* to work

### ISSUE THREAD

**Issue by andreamoro** [mevdschee/php-crud-api#548]
Have been working on a brand new database created for an MVP, using a PHP script put together a while ago from a third party.
Also I'm using an old version of your CRUD API. 

In comparing the database structure with a previous database file, I noticed the absence of a bunch of sys/* tables from my file which where in fact impeding be to query the database successfully. 

Can you please shed a lite on the needs of these tables and how I can eventually drop off their need?

Thanks

**Comment by mevdschee** [comment]
Thank you for this issue. The sys tables were created for SQLite which is no longer supported in v2. Can you explain what you were using the sys tables for? You can now use the "/columns" endpoint to read the structure of your database. This should serve as an alternative.

**Comment by andreamoro** [comment]
HI @mevdschee 
I am actually not sure for what specific purpose these tables were queried for. I have this script from a third party that is remotely inserting/updating data in the database via an API mechanism.

As far as I could see, the database was in first instance queried to find whether two specific columns were existing and be sure that to be a valid database for the given platform.
I have been not able to dig deeper than that, but I suspect that simply updating the script will not work out of the box. 

Would the new API you put together work without the need of these tables at all?

**Comment by andreamoro** [comment]
Actually ... reading again, you message you say that SQLLite is no longer supported? How come?

**Comment by mevdschee** [comment]
>Would the new API you put together work without the need of these tables at all?

Yes, it does not require those tables.

>Actually ... reading again, you message you say that SQLLite is no longer supported? How come?

Well, because the meta-information scanning took a lot of time and thus any large(r) scale usage of this method would fail due to bad performance. I want to avoid people being disappointed with (the performance of) the software.

>I have this script from a third party that is remotely inserting/updating data in the database via an API mechanism.

Sounds like you are in need of some consultancy support from that integrating party.

**Comment by andreamoro** [comment]
Well, if the new version doesn't support sqllite, I guess I need to first locate a new CRUD

**Comment by mevdschee** [comment]
Duplicate of  #405
