### ISSUE TITLE
Running againts CORS with new api

### ISSUE THREAD

**Issue by freddiefish** [mevdschee/php-crud-api#55]
Hi there
Developing an Angular 2 App from localhost. I had no CORS with my former api. My server allows calls from other domains. 

Implementing the php-crud-api, I get a "Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin." warning. 

Any ideas? Thank you!
Fred

**Comment by mevdschee** [comment]
I don't know, it does call: 

    header('Access-Control-Allow-Origin: *');

in line 1822, can you try to be more specific? What call is failing? Is there a pre-flight request failing?

**Comment by mevdschee** [comment]
Did you see the angular2 client example in the "examples" folder?

**Comment by freddiefish** [comment]
Good idea to first check how CORS behave with the angular2 example. When I run the api with sqlite, I get:
EXCEPTION: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by mevdschee** [comment]
Use a full like postman to check the output of the API. Maybe you are missing a dependency and is it showing an error.

**Comment by freddiefish** [comment]
The CORS issue is resolved when I comment out line 1822
`header('Access-Control-Allow-Origin: *');`
Uncommenting returns the CORS warning.

**Comment by mevdschee** [comment]
Can you provide more details as this is opposite to what I expect (and experience). How can I reproduce the CORS warning?

For the SQLite problem I created another issue.

**Comment by mevdschee** [comment]
I need to know more things, like:
- operating system
- php version
- mysql version
- url requested
- response headers
- response body

**Comment by mevdschee** [comment]
Closed due to inactivity.

**Comment by freddiefish** [comment]
Maurits

Ik heb geen tijd gehad om dit te bekijken voor jou. Wat ik vermoed: mijn domein aanvaardt via htaccess (tijdelijk ;) ) * hosts. Misschien dat de extra header call vanuit het crud php script conflicteert?

Groeten
Frederik

**Comment by mevdschee** [comment]
Hi Frederik,

That could very well be the problem. Maybe you can try disabling that in the htaccess and see what happens? It is possibly an environment issue.

Kind regards,

Maurits

**Comment by freddiefish** [comment]
Maurits, commenting out the `Header add Access-Control-Allow-Origin "*"` line in htaccess solved it!

**Comment by mevdschee** [comment]
Great.. thank you, can you also retry #57?

**Comment by pottertech** [comment]
About the new CORS feature..., I am assuming the "*" means ALL origins are allowed?  Also would like to know the format for supporting multiple origins... do we place with in a list separated by commas?  example:  http://website-one.com, https://website-two.com

**Comment by mevdschee** [comment]
@pottertech Yes that should work.
