### ISSUE TITLE
Multiple users CRUD - best approach

### ISSUE THREAD

**Issue by lnjuanj** [mevdschee/php-crud-api#550]
Hi @mevdschee , all,
I would like to have a CRUD API for multiple "users". In a typical CRUD API for different users, you would have objects that depend on the user. So, if a mysql table has rows for different users, each user that called the API would only get their own rows. AFAIK, by what I have read, this is not available on the library _per se_. Is there any library or approach that you recommend?
I have seen one way to achieve this is having a column for the user in the table (which I already have) and filter by user. Where should I introduce those filters?

**Comment by mevdschee** [comment]
Great question. This is what the multi-tenancy handler is for. Simply add a user_id to all tables and compare with the user_if from the users table. If you want to allow multi-user (per tenant), then you should add a tenant_id column to the users table (and all other tables) and compare with that.

**Comment by lnjuanj** [comment]
Thank you very much. 
I will add some info to the documentation and do a PR when I finish the project, in case you'd like to have a more detailed info on topics such as middleware definitions and multi-tenancy. I could add some sample usage instead. Both would reduce the number of questions to you, I hope :)

**Comment by mevdschee** [comment]
>I will add some info to the documentation and do a PR when I finish the project, in case you'd like to have a more detailed info on topics such as middleware definitions and multi-tenancy. 

That would be great!

**Comment by adnoh** [comment]
> Thank you very much.
> I will add some info to the documentation and do a PR when I finish the project, in case you'd like to have a more detailed info on topics such as middleware definitions and multi-tenancy. I could add some sample usage instead. Both would reduce the number of questions to you, I hope :)

Did this pr ever happen? Have the same question and a more complex example would be nice.
