### ISSUE TITLE
authorization.columnHandler not filtering out columns

### ISSUE THREAD

**Issue by Mrgove10** [mevdschee/php-crud-api#553]
I can't seem to make the columnHadler work properly 
```php
$config = new Config([
    'address' => 'XXXX',
    'username' => 'XXXX',
    'password' => 'XXXX',
    'database' => 'users',
    'middlewares' => 'cors,authorization',
    'authorization.columnHandler' => function ($operation, $tableName, $columnName) {
        return !($columnName == 'mail');
    }
]);
```
whit this config it still returns me the "mail" column
![image](https://user-images.githubusercontent.com/25491408/60384226-8a181600-9a7b-11e9-8f28-dee45edcb000.png)

i have tried authorization.tableHandler on the whole users table and that works.

**Comment by mevdschee** [comment]
Hi, thank you for reaching out. The "columnHandler" requires a "tableHandler" that returns true in all cases.

**Comment by Mrgove10** [comment]
Thanks alot for the UBERFAST reply !

Worked first time !

Config if anyone has the issue :
```php
$config = new Config([
    'address' => 'XXXX',
    'username' => 'XXXX',
    'password' => 'XXXX',
    'database' => 'users',
    'middlewares' => 'cors,authorization','authorization.tableHandler' => function ($operation, $tableName) {
        return $tableName != 'random_table';
    },
    'authorization.columnHandler' => function ($operation, $tableName, $columnName) {
        return !($columnName == 'mail');
    }
]);
```

**Comment by mevdschee** [comment]
I agree that this is confusing. I'll make a change to the code so that this is no longer required.

**Comment by mevdschee** [comment]
Version v2.3.4 has been released for you :-)
