### ISSUE TITLE
Username + password authentication

### ISSUE THREAD

**Issue by lnjuanj** [mevdschee/php-crud-api#556]
Hi,
I would like to do the following: a user fills a form and a POST call is sent to the API. I would like to check that the username and password are correct in the database and send the user a cookie and set the username: $_SESSION['username'] with a custom field in the database.
What I currently do is:

```
$config = new Config([
...
'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
    $body = $request->getParsedBody();
    $cloudUser = $body->username;
    $cloudPass = $body->password;
    $access_mysqli = new \mysqli('localhost', 'dbuser', 'dbpass', 'dbname');
    $sql    = "SELECT  'id', 'password' FROM 'user' WHERE 'user'='$cloudUser'";
    $result = $access_mysqli->query($sql);
    if ($result->num_rows==0) {
      header('HTTP/1.0 401 Unauthorized');
      exit(0);
    }
    $row    = $result->fetch_assoc();
    if (password_verify($cloudPass,$row['password'])==1) {
      // go on
    }
    else {
      header('HTTP/1.0 401 Unauthorized');
      exit(0);
    }
```

This does not return a session cookie. It returns correctly in case the user+pass is valid, and a 401 in case it is not a valid user+pass.
So, I have a double question:
* How could I return a session cookie?
* How could I set the $_SESSION['username']? It would be the 'id' field returned in the query.

Thanks in advance!

**Comment by mevdschee** [comment]
I had to update the password of user2 to '$2y$10$cg7/nswxVZ0cmVIsMB/pVOh1OfcHScBJGq7Xu4KF9dFEQgRZ8HWe.' and then I used the following config:

    $config = new Config([
        'username' => 'php-crud-api',
        'password' => 'php-crud-api',
        'database' => 'php-crud-api',
        'middlewares' => 'customization',
        'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
            session_start();
            if (!isset($_SESSION['username'])) {
                $body = $request->getParsedBody();
                $username = $body->username;
                $password = $body->password;
                $db = new \mysqli('localhost', 'php-crud-api', 'php-crud-api', 'php-crud-api');
                $username = $db->escape_string($username);
                $sql = "SELECT `username`, `password` FROM `users` WHERE `username`='$username'";
                $result = $db->query($sql);
                if ($result->num_rows==0) {
                    header('HTTP/1.0 401 Unauthorized');
                    exit(0);
                }
                $row = $result->fetch_assoc();
                if (password_verify($password,$row['password'])==1) {
                    $_SESSION['username'] = $row['username'];
                    header('HTTP/1.0 200 OK');
                    exit(0);
                } else {
                    header('HTTP/1.0 401 Unauthorized');
                    exit(0);
                }
            }
        }
    ]);

I tested it and it does what you want.

NB: Be careful about SQL injection when writing SQL (see: https://en.wikipedia.org/wiki/SQL_injection)

**Comment by mevdschee** [comment]
And here is a full example with login and logout endpoints:

    $config = new Config([
        'username' => 'php-crud-api',
        'password' => 'php-crud-api',
        'database' => 'php-crud-api',
        'middlewares' => 'customization',
        'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
            session_start();
            $path = RequestUtils::getPathSegment($request, 1);
            if ($path == 'login') {
                $body = $request->getParsedBody();
                $username = isset($body->username)?$body->username:'';
                $password = isset($body->password)?$body->password:'';
                $db = new \mysqli('localhost', 'php-crud-api', 'php-crud-api', 'php-crud-api');
                $username = $db->escape_string($username);
                $sql = "SELECT `username`, `password` FROM `users` WHERE `username`='$username'";
                $result = $db->query($sql);
                while ($row = $result->fetch_assoc()) {
                    if (password_verify($password,$row['password'])==1) {
                        session_regenerate_id(true);
                        $_SESSION['username'] = $row['username'];
                        header('HTTP/1.0 200 OK');
                        exit(0);
                    }
                }
                unset($_SESSION['username']);
                header('HTTP/1.0 401 Unauthorized');
                exit(0);
            } else if ($path == 'logout') {
                if (isset($_SESSION['username'])) {
                    session_destroy();
                    unset($_SESSION['username']);
                    header('HTTP/1.0 200 OK');
                    exit(0);
                }
                header('HTTP/1.0 401 Unauthorized');
                exit(0);
            } else {
                if (!isset($_SESSION['username'])) {
                    header('HTTP/1.0 401 Unauthorized');
                    exit(0);
                }
            }
        }
    ]);

I'm sure that helps :-)

**Comment by mevdschee** [comment]
I'm considering porting this into an officially supported middleware.

**Comment by lnjuanj** [comment]
Hi,
This is working nicely. Thanks for the help and also the login and logout endpoints: very useful indeed!!
I'm going to experiment with the _SESSION['username']) and see how I would filter the rows by the user column but this looks really promising.

**Comment by mevdschee** [comment]
>how I would filter the rows by the user column

Make sure to take a look at the multi-tenant implementation, see: https://github.com/mevdschee/php-crud-api#multi-tenancy-support

**Comment by billiemead** [comment]
Hi, I am LOVING the software, I have it installed in Laravel. You did an amazing job with the implementation (and your support is great too!). Could I use this to build a login screen for mobile or do you recommend a different authorization method? Cheers.

**Comment by mevdschee** [comment]
Thank you for your kind words. If you use Laravel, then I think it is better to use the preferred way of creating a login page. See: https://laravel.com/docs/7.x/authentication

**Comment by pottertech** [comment]
I would like to see an examples/dbAuth folder added that contains a working version for using dbAuth rather than have to dig around the issues comments to try to get a working version.  It should also contain a "crud_users.sql" file to help users with a working version of the database table.  A few examples to also show how it works for adding a users, deleting a user, updating the password as well as a login and logout example.
