### ISSUE TITLE
Simple put request "code": 1002

### ISSUE THREAD

**Issue by simsol180** [mevdschee/php-crud-api#557]
POST, DELETE, and GET are working correctly in my environment.  PUT looks like it has a null value for `$body = file_get_contents('php://input');` in fromGlobals.  Confirmed this in both my Angular app and using a rest editor browser plugin.  Any idea what I'm doing wrong?  

below is the error response:

    {
        "code": 1002,
        "message": "Argument count mismatch in '1'"
    }

Running: MySQL - 5.6.41-84.1-log / PHP 7

/api.php/records/classes/1

    {
        "id":1,
        "title": "test class 1wwwww",
        "description": "Here is some text for test class 1.",
        "training_id": 0
    }

/api.php/openapi

    `update-classes":{
        "type": "object",
        "properties":{
            "id":{"type": "integer", "format": "int32", "x-primary-key": true, "x-referenced":["training.class_id"…},
            "title":{"type": "string"},
            "description":{"type": "string"},
            "training_id":{"type": "integer", "format": "int32"}
        }
    },

**Comment by mevdschee** [comment]
Hi, thank you for your question. Could it be because you are using a training_id of "0" (zero)? Primary keys / auto-increments should start at 1.

**Comment by mevdschee** [comment]
Can you help me reproduce this issue on the test database?

**Comment by simsol180** [comment]
Thanks for the help! I am using a json object.  The same one from the GET request, altered and sent back using PUT.  Those settings are set, still the issue persists.  

The strange thing is that the POST request works to create an item in the table.  That should use file_get_contents too right?  to test it, I put `echo file_get_contents('php://input');` at the top of the file, under the namespace and did a create post and an update put,  results are below.  null on put, not null on post.

The code for the test:
![test code](https://user-images.githubusercontent.com/34282063/61185957-4dc4e800-a62d-11e9-9505-2aeff7362530.PNG)

The POST request to create an item that works:
![post-create item](https://user-images.githubusercontent.com/34282063/61185936-02aad500-a62d-11e9-9e47-62f5645b9e5c.PNG)

The PUT request to update  an item that doesn't work:
![put- update item](https://user-images.githubusercontent.com/34282063/61185937-02aad500-a62d-11e9-8885-bfefa514bd71.PNG)

**Comment by simsol180** [comment]
I had a similar issue on the last version except it was a silent error, it returned empty.

**Comment by simsol180** [comment]
Why would it fail for the PUT request and not the POST?

**Comment by mevdschee** [comment]
Tell me more about your hosting setup. Are you using cloudflare? Is there a reverse proxy in use? Nginx with fastcgi? Apache with mod_php? If 'php://input' is empty then that has nothing to do with the script, but with a broken PHP setup. I'm glad to help, but I can't do much without information.

**Comment by mevdschee** [comment]
I can offer you a workaround. In the config put the following: 

    $_SERVER['REQUEST_METHOD'] = $_GET['method']; // add this
    $request = RequestFactory::fromGlobals();

By adding the above line you can override the method, by specifying an extra get parameter 'method'.

**Comment by simsol180** [comment]
The work around worked like a charm.  I totally would have guessed the server variables would be read only.  Thank you so much for your help!  This has been eating me forever.  You are my hero!

**Comment by mevdschee** [comment]
I'm glad I could help. Thank you for your kind words. Enjoy the software!
