### ISSUE TITLE
Getting Data integrity violation Error in Post API.

### ISSUE THREAD

**Issue by vaibhavisojitra25** [mevdschee/php-crud-api#558]
Hello,
I want to create api dynamically in laravael framework.
I have create database table and field name is username.
I have run post api with passing arguments in raw json like this,
`{
	"username" : "test test"
}`
But its return response is,
`{
    "code": 1010,
    "message": "Data integrity violation",
    "details": "SQLSTATE[HY000]: General error: 1364 Field 'username' doesn't have a default value"
}`
I have applied existing solution(issue #520) but still getting error.
Please, Can anyone  give me other solution??

**Comment by mevdschee** [comment]
It seems like the post body is not received properly by the script.

**Comment by vaibhavisojitra25** [comment]
I have tried two ways to post body data(x-www-form-urlencoded and raw json data). you can see in below image ink
https://ibb.co/gdKmLT2
https://ibb.co/R3dk70B
But still getting same error.
And GET API Working properly. In below link is GET API response. please check
https://ibb.co/zsjTjb1

**Comment by mevdschee** [comment]
I tried to reproduce, but without success, maybe you can help me reproduce, by answering:

- Which PHP version are you using?
- What database do you use? MySQL? Which version?
- What is the CREATE TABLE statement for the table you try to operate on?

Kind regards, Maurits

**Comment by mevdschee** [comment]
I was able to reproduce this bug.

**Comment by mevdschee** [comment]
I fixed this bug in v2.3.11, please update.

**Comment by vaibhavisojitra25** [comment]
> I fixed this bug in v2.3.13, please update.

Thanks, Now its working fine.

**Comment by vaibhavisojitra25** [comment]
> I fixed this bug in v2.3.13, please update.

How Can I customize Post API Response ??
Currently its return only id. But I want to Response Like,
{
id : 1
}
Can you please help me??
