### ISSUE TITLE
Getting Data integrity violation Error in Post API with Symfony 4

### ISSUE THREAD

**Issue by Mlayeh** [mevdschee/php-crud-api#559]
I have run post api with passing arguments in raw json like this,
{ "designation" : "pppp" }
But its return response is,
{ "code": 1010, "message": "Data integrity violation"}
and  GET API Working properly.
Please, Can anyone give me solution??

**Comment by mevdschee** [comment]
Thank you. Can you tell me a bit about your environment so I can try to reproduce?

- Which PHP version are you using?
- What database do you use? MySQL? Which version?
- What is the CREATE TABLE statement for the table you try to operate on?
- What is the exact URL + data you are sending to the request?

Kind regards, Maurits

**Comment by mevdschee** [comment]
I was able to reproduce this bug.

**Comment by mevdschee** [comment]
I fixed this bug in v2.3.11, please update.
