### ISSUE TITLE
Feature: add mysql functions to columns

### ISSUE THREAD

**Issue by skirmis** [mevdschee/php-crud-api#56]
For example.  

?column=INET_NTOA(ip_addr)

and same to filter

?filter[]=INET_NTON(ip_addr),eq,'1.1.1.1'

because I have a database which stores IP addresses as long number

Thank you

**Comment by mevdschee** [comment]
Why don't you want to do this at the client? Why are you requesting this feature?

**Comment by skirmis** [comment]
Use case: I have an IP database maintaining by other software. But it lack of good API. So I decided to give a try for your solution. Field IPaddr is containing an IP address in number format ( long ). This would be not a problem, because I can convert ip2long on client side. But some clients is missing ip2long function(different daemon, program languages and so on), because I'm integrating IP database with many micro-services.

**Comment by mevdschee** [comment]
I think this use-case fits better for the stored procedure API, see:

https://github.com/mevdschee/php-sp-api

Check it out!
