### ISSUE TITLE
Need to Customize Post API Response

### ISSUE THREAD

**Issue by vaibhavisojitra25** [mevdschee/php-crud-api#560]
How Can I Customize Post API Response ??
Currently its return only id (like 1). Which is not manage by APP Developer. So I want to Response Like,
{
data : {
"id" : 1
}
}
Can you please help me??

**Comment by mevdschee** [comment]
As the readme states:

>You may use the "customization" middleware to modify request and response and implement any other functionality.

See: https://github.com/mevdschee/php-crud-api#customization-handlers

Read up on this link about "Message Bodies":

See: https://mwop.net/blog/2015-01-26-psr-7-by-example.html

**Comment by vaibhavisojitra25** [comment]
return $response->withBody($stream);
Where should I need to write this. because i have not make any routes or function for call post api.

**Comment by mevdschee** [comment]
>Where should I need to write this

In a 'customization.afterHandler' as described in the readme.

NB: you need to enable the 'customization' middleware.

**Comment by vaibhavisojitra25** [comment]
> > Where should I need to write this
> 
> In a 'customization.afterHandler' as described in the readme.
> 
> NB: you need to enable the 'customization' middleware.

Okay I have enabled in config
```
Route::any('/{any}', function (ServerRequestInterface $request) {
    $config = new Config([
        'username' => 'root',
        'password' => '',
        'database' => 'laravel_api',
        'basePath' => '/api',
        'middlewares' => 'customization',
        'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
            $environment->start = microtime(true);
        },
        'customization.afterHandler' => function ($operation, $tableName, $response, $environment) {
            return $response->withHeader('X-Time-Taken', microtime(true) - $environment->start);
        },
    ]);
    $api = new Api($config);
    $response = $api->handle($request);
    // $stream =  'data';
    // $response->withBody($stream);
    return $response;
})->where('any', '.*');
```
But can you please explain how its works ??
What parameter should be pass into `$stream` for this type of response ??
```
{
data : {
"id" : 1
}
}
```

**Comment by mevdschee** [comment]
If you use laravel, then you dont need the customization handler.

The new Response could come from a ResponseFactory, so replace:

    // $stream =  'data';
    // $response->withBody($stream);

with:

    $json = json_decode($reponse->getBody()->getContents());
    $response = ResponseFactory::fromObject(200, $json);

See: https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/ResponseFactory.php#L23

**Comment by vaibhavisojitra25** [comment]
> If you use laravel, then you dont need the customization handler.
> 
> The new Response could come from a ResponseFactory, so replace:
> 
> ```
> // $stream =  'data';
> // $response->withBody($stream);
> ```
> 
> with:
> 
> ```
> $json = json_decode($response->getBody()->getContents());
> $json = (object) array('data'=>$json);
> $response = ResponseFactory::fromObject(200, $json);
> ```
> 
> See: https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/ResponseFactory.php#L23

Thanks, 
Its working but didn't get exact reponse. 
its returning below
 ```{
    "data": [
        10,
        11
    ]
}
```
can i get response in array with key id just like.
```
{
data : [{
"id" : 1
},{
"id" : 2
}]
}
```

**Comment by mevdschee** [comment]
Something like this should do it:

    $json = json_decode($response->getBody()->getContents());
    $json = array_map(function($e){return (object)['id'=>$e];},$json); //added
    $json = (object) array('data'=>$json);
    $response = ResponseFactory::fromObject(200, $json);

Kind regards, Maurits
