### ISSUE TITLE
How to run iis? 

### ISSUE THREAD

**Issue by kookle** [mevdschee/php-crud-api#561]
Hi,

thank you for sharing...

we use iis, how to install or run ?

**Comment by mevdschee** [comment]
>we use iis, how to install or run ?

Like any other PHP script on IIS.

**Comment by kookle** [comment]
i solved, just added api.php file on iis :)

thank you, have a nice day

**Comment by mevdschee** [comment]
You are welcome, enjoy the software! 

NB: Feel free to ask a more questions when you are running into problems.
