### ISSUE TITLE
Parse error: syntax error, unexpected '}', 

### ISSUE THREAD

**Issue by kerkenit** [mevdschee/php-crud-api#563]
I've updated the code by copy the new release folder  of 8e6d7cbfa6abd69ae8cea5469f3eb23b40b3524c to the server. Right now I'm getting an error.

Parse error: syntax error, unexpected '}', expecting end of file in /var/www/html/tmp_api.php on line 10333

What to do?
I can't remember which release I've had. Probably v2.3.6 or v2.3.7 but I'm not sure.

**Comment by mevdschee** [comment]
Thank you for reaching out. Has this issue been resolved by upgrading to the latest release? What is it that you are asking in the issue? Can you share the file (tmp_api.php) with me (for private sharing use email). Kind regards, Maurits

**Comment by mevdschee** [comment]
I released v2.3.20 for you. It should fix your problem.
