### ISSUE TITLE
How to change json data format of api output

### ISSUE THREAD

**Issue by DearPureone** [mevdschee/php-crud-api#564]
Hello Mr.Maurits
first of all your project is work perfectly fine
i just use it with simple api call with axios and work with no problem
with output look like this.
> {
    "records":[
        {
            "id": 1,
            "title": "Hello world!",
            "content": "Welcome to the first post.",
            "created": "2018-03-05T20:12:56Z"
         },
        {
            "id": 2,
            "title": "Black is the new red",
            "content": "This is the second post.",
            "created": "2018-03-06T21:34:01Z"
        }
    ]
}
 ##
**but is it possible to have out put like this, like Batch operations output**
> [
        {
            "id": 1,
            "title": "Hello world!",
            "content": "Welcome to the first post.",
            "created": "2018-03-05T20:12:56Z"
        },
        {
            "id": 2,
            "title": "Black is the new red",
            "content": "This is the second post.",
            "created": "2018-03-06T21:34:01Z"
        }
]

Thank for your advice.

**Comment by mevdschee** [comment]
> but is it possible to have output like Batch operations output (without the "records" key)?

Yes, using an afterhandler (add this to your config in 'index.php'):

    'middlewares' => 'customization',
    'customization.afterHandler' => function ($operation, $tableName, $response, $environment) {
        $json = json_decode($response->getBody()->getContents());
        return ResponseFactory::fromObject(200, (object) $json->records);
    },

But couldn't you just resolve that "records" key in the data received by axios?

**Comment by DearPureone** [comment]
Thank for your fast reply

i have try with your solution and got output like this.
> 

{
"0": {
     "id": 1,
      "title": "Hello world!",
      "content": "Welcome to the first post.",
      "created": "2018-03-05T20:12:56Z"
},
"1":  {
      "id": 2,
       "title": "Black is the new red",
       "content": "This is the second post.",
       "created": "2018-03-06T21:34:01Z"
}
}

what i want is output look like  [jsonplaceholder](https://jsonplaceholder.typicode.com/comments)
can i find usage of customization.afterHandler anywhere. don't want to bother you too much.

new to this kind of stuff, did't know that i can resolve that with axios.
i'll looking into it.
many thanks for your advice.

**Comment by mevdschee** [comment]
I made a mistake. Can you try again?

**Comment by mevdschee** [comment]
Do you have an update? Did it work for you?

**Comment by DearPureone** [comment]
Sorry for my late reply.
The output is now working as expected.



I really want to thank you for your help.

**Comment by DearPureone** [comment]
I apologize for reopen this issue
just want your advice, 
what the different between your customization code and the Batch operations output.
the output look like the same.
with the output from Batch operations and [jsonplaceholder](https://jsonplaceholder.typicode.com/comments) it working fine when i get it with axios and use it to v-for in my work
but with customization code output it's not working.
or problem is CORS ? but i thought it enabled by default

I really appreciate the help.

**Comment by mevdschee** [comment]
>what the different between your customization code output and the Batch operations output.

None AFAIK

> the output look like the same.

It should be

> but with customization code output it's not working.

What is not working? This sounds like a bug in your Vue code.

**Comment by DearPureone** [comment]
> What is not working? This sounds like a bug in your Vue code.


in same api.php file 

-with Batch operations  it working 

-with 'customization.afterHandler' i've  got "has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource"

**Comment by mevdschee** [comment]
Ah.. you should add the "cors" middleware, change:

    'middlewares' => 'customization',

to:

    'middlewares' => 'cors,customization',

I'm sure that helps.

**Comment by DearPureone** [comment]
> 'middlewares' => 'cors,customization',

with this,it working as expected.


That’s very kind of you.
Many thanks for your advice.
