### ISSUE TITLE
update operation blocked by multi tenancy handler returns success

### ISSUE THREAD

**Issue by koltai75** [mevdschee/php-crud-api#565]
I defined a multi tenancy handler that restricts the updating of records based on a column value. When I try to make an invalid update (for example update a row which belongs to another tenant) the update operation is not carried out (which is good), but the request returns  200 OK. The only way to find out what happened is to check the results count in the response result set. If it is 0, the update failed.

Wouldn't it be better the return an error in this case?

**Comment by mevdschee** [comment]
Hi, thank you for reaching out. I understand your reasoning, but let me explain what happens: It adds a "where" condition to the update statement resulting in 0 affected rows. This is why it behaves like it does. I'm not entirely sure whether or not we could (or should) return an error instead. Kind regards, Maurits

**Comment by koltai75** [comment]
Hi, thank for your quick answer. In your opinion the proper way is to check the response JSON, and if it is 0, than the update was not carried out? And the same goes for delete operations also, I guess.

My problem is that I cannot distinguish the different scenarios. Deleting a record can result in 0 affected rows for "normal" reasons (the record was deleted by someone else) and other reasons, for example someone is maliciously trying to delete a record that belongs to another tenant. The two situations are different and might require different handling.

The same goes for rules defined in the column handler. If I disallow the updating of a specific column in a table, but the user tries to change that field on the client UI, the operation reports success, although the column will not be updated. In this case I can also check the result count, but again, I will not know why the update failed (affected 0 rows).

The table handler returns an error when someone is trying to access a table that is not available. I don't know whether an error is a good idea in the above mentioned cases, but somehow it would be nice the have more information regarding why an operation resulted in 0 affected rows, especially when it is caused by the handler functions, which implement important authorization rules. (In my opinion a delete operation that targets the deleting of a record, and the delete is not executed because the record is not available to the client, is not a success, but a failure. Bottom line is, the record remains in the database, so the operation did not succeed. One could also argue that the operation itself is success by means it did not encounter any errors, but did not affect any records. It's somehow a philosophical question.)

Kind regards and thank you, Peter

**Comment by mevdschee** [comment]
Hi Peter,

Thank you for your elaborate reply.

>The table handler returns an error when someone is trying to access a table that is not available.

Specifically, it gives a 404, which means that it does not exist.

>Deleting a record can result in 0 affected rows for "normal" reasons and other reasons.

Your front-end should not allow doing operations that are not allowed (by the tenancy or column handler).

>I cannot distinguish the different scenarios

A pragmatic approach would be to set a response header in the handler and check for that on the client. You can use PHP's "header()" function.

>It's somehow a philosophical question.

Indeed. And of application design. Users should not be aware of the existance of your multitenancy column.

Kind regards,

Maurits

**Comment by koltai75** [comment]
Hi Maurits,

I will try to adjust my front-end to handle 0 affected records returned by your API, or go with the recommended header(), thank you for that.

I totally agree that the front-end should not allow restricted operations and users should not know about multitenancy columns, and my implementation goes by that. The problem is that clients cannot be trusted, anyone with a little knowledge can easily manipulate many things from the client browser, so I always like to assume the worst and prepare for that, since security is very important in my application.

Thank you for your time, I close this issue now.

Bests,

Peter
