### ISSUE TITLE
I want to do multi-table joint survey. How can I achieve it?I want to do multi-table joint survey. How can I achieve it?

### ISSUE THREAD

**Issue by lxge** [mevdschee/php-crud-api#566]
I want to do multi-table joint survey. How can I achieve it?

**Comment by mevdschee** [comment]
Thank you for filing an issue. Please describe your question in more detail. What did you try? What did you run into? What do your tables look like? What query do you try to execute (in SQL maybe)? I'm sorry to inform you that I need to close this ticket to avoid broken window effect. Kind regards, Maurits
