### ISSUE TITLE
mysql session setting

### ISSUE THREAD

**Issue by kdoe13** [mevdschee/php-crud-api#568]
Hi,

The "TRADITIONAL" setting here https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Database/GenericDB.php#L44, makes it so passing in true for a boolean value is not read correctly. 

{"data" : true}  .... where the Column "Data" is set in my db as a boolean. The DB throws an error if TRADITIONAL mode is set and I try to send "true"...anyhow, this is not the behavior I'd like. I'm wondering if there is a setting on my side of things that I can override this mode?

**Comment by mevdschee** [comment]
Thank you for filing this issue. 

The setting "traditional" will make MySQL "give an error instead of a warning” when inserting an incorrect value into a column.

You write:

>makes it so passing in true for a boolean value is not read correctly

and you also write:

>the DB throws an error if TRADITIONAL mode is set and I try to send "true"

My guess is that you are sending "true" as:

    {"data":"true"}

while you should be sending:

    {"data":true}

But I may be mistaken, can you verify this?

Kind regards, Maurits

**Comment by mevdschee** [comment]
There is a test that tests boolean fields:

    tests/functional/001_records/030_list_example_from_readme_tags_only.log

Can you see whether or not that test runs correctly on your machine?

**Comment by mevdschee** [comment]
I'm able to reproduce this bug. I'm adding a test case. Please hold on.

**Comment by mevdschee** [comment]
Okay, so I think I fixed it now. I've squashed all commits into this one:

22b282ab5bbf0cfbdbe40ced8e8a13d5d3974d3f

I hope this works for you.

**Comment by kdoe13** [comment]
@mevdschee Yes this is checking out for me on tests as well as in my application. Thank you for the quick action.

**Comment by mevdschee** [comment]
I'm glad it worked. Thank you for your quick reply.

**Comment by kdoe13** [comment]
@mevdschee So I lied when I thought it was working. I've been multi-tasking all day on little sleep and didn't do as good a job of testing as I should have. I've done a more thorough check now, and will hopefully communicate better now. I really appreciate the time you've taken on this and I'm sorry for not communicating as fully as I should have.

So...first off I misspoke when I said my issue was with {"data":true} being the issue, my actual issue was {"data":false} not working. I see how your solution would solve this, though, but the problem with MySql is that it won't set a column as Boolean.  In your case you are setting bit(1), which throws the error on true..but since I use [Phinx](http://docs.phinx.org/en/latest/) to handle my migrations when I set it as boolean the MySql column is set as tinyint(1), and in this case it fails on false.  And since the column is now set an integer, the solution you set is not going to work.

I added the following for my setup and it would work, although it does cause your /GET test will throw an error but the PUT tests work.

    private function convertInputValue($conversion, $value)
    {
        switch ($conversion) {

            case 'integer':
                if (is_bool($value)) {
                    return $value ? 1 : 0;
                } else {
                    return $value;
                }

            case 'boolean':
                return $value ? 1 : 0;
            case 'base64url_to_base64':
                return str_pad(strtr($value, '-_', '+/'), ceil(strlen($value) / 4) * 4, '=', STR_PAD_RIGHT);
        }
        return $value;
    }

    private function getInputValueConversion(ReflectedColumn $column): string
    {

        if ($column->isInteger()) {
            return 'integer';
        }

        if ($column->isBoolean()) {
            return 'boolean';
        }
        if ($column->isBinary()) {
            return 'base64url_to_base64';
        }
        return 'none';
    }

Sorry again for not being more thorough in my original write-up.

Thank you again for your hard work on this.

**Comment by mevdschee** [comment]
I released v2.4.2 with a fix.

**Comment by kdoe13** [comment]
Yep its working. Glad we were able to work together on this today and get it all sorted so quickly.

**Comment by mevdschee** [comment]
Yeah, great collaboration. Thank you for your contribution!
