### ISSUE TITLE
Support 'Set' datatype in MySQL

### ISSUE THREAD

**Issue by graziano1955** [mevdschee/php-crud-api#570]
My DB: MariaDB 10.3.11

This worked fine in V1:

struttura?include=struttura_tipi&columns=struttura.nome,struttura.indirizzo,struttura_tipi.descrizione

In V2

records/struttura?join=struttura_tipi&include=struttura.nome,struttura.indirizzo,struttura_tipi.descrizione

give error:

'Unsupported type ''set'' for driver ''mysql'' in /volume1/web/apinew.php:6436'

This

records/struttura?join=struttura_tipi

works fine.

-------------------------------------------------------------
This works fine in V1:

prenotazioni?include=clienti&filter=prenotazioni.codice_camera,eq,1

In V2

records/prenotazioni?join=clienti&filter=prenotazioni.codice_camera,eq,1

give error:

'Return value of Tqdev\PhpCrudApi\Column\Reflection\ReflectedTable::getColumn() must be an instance of Tqdev\PhpCrudApi\Column\Reflection\ReflectedColumn, null returned  in /volume1/web/apinew.php:3927'

This

records/prenotazioni?join=clienti&filter=codice_camera,eq,1

give error:

'Unsupported type ''set'' for driver ''mysql'' in /volume1/web/apinew.php:6436'

**Comment by mevdschee** [comment]
I have added support for the 'set' datatype in d3d596129030d184d7bb79a49ec5a7aa9b6bd893

I have released v2.4.7 with this support.

**Comment by mevdschee** [comment]
Any update?

**Comment by graziano1955** [comment]
First of all: Thank you for your wonderful work!
The support for the 'set' datatype is working fine.

I have still this error:

This works fine in V1:

prenotazioni?include=clienti&filter=prenotazioni.codice_camera,eq,1

In V2

records/prenotazioni?join=clienti&filter=prenotazioni.codice_camera,eq,1

give error:

'Return value of Tqdev\PhpCrudApi\Column\Reflection\ReflectedTable::getColumn() must be an instance of Tqdev\PhpCrudApi\Column\Reflection\ReflectedColumn, null returned in /volume1/web/apinew.php:3927'

This

records/prenotazioni?join=clienti&filter=codice_camera,eq,1

is working fine.
(codice_camera is a column in prenotazioni table)

**Comment by mevdschee** [comment]
Could it be that you have a table without a (single) primary key?

**Comment by graziano1955** [comment]
no, my table definition is:

CREATE TABLE `prenotazioni` (
  `codice` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `codice_cliente` int(10) unsigned NOT NULL,
  `codice_canale` smallint(5) unsigned NOT NULL,
  `data_arrivo` date NOT NULL,
  `ora_arrivo` time DEFAULT NULL COMMENT 'ora indicativa di arrivo',
  `data_partenza` date NOT NULL,
  `stato` enum('R','O','C','P','N') NOT NULL COMMENT 'Richiesta cOnfermata Cancellata Presenza Non_presenza',
  `codice_camera` smallint(5) unsigned DEFAULT NULL,
  `adulti` tinyint(4) NOT NULL DEFAULT 1,
  `bambini` tinyint(4) NOT NULL DEFAULT 0,
  `animali` tinyint(4) NOT NULL DEFAULT 0,
  `caparra` smallint(6) DEFAULT NULL,
  `note` varchar(100) DEFAULT NULL,
  `colazione` tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`codice`),
  KEY `FK_prenotazioni_canali` (`codice_canale`),
  KEY `FK_prenotazioni_camere` (`codice_camera`),
  KEY `FK_prenotazioni_clienti` (`codice_cliente`),
  CONSTRAINT `FK_prenotazioni_camere` FOREIGN KEY (`codice_camera`) REFERENCES `camere` (`codice`),
  CONSTRAINT `FK_prenotazioni_canali` FOREIGN KEY (`codice_canale`) REFERENCES `canali` (`codice`),
  CONSTRAINT `FK_prenotazioni_clienti` FOREIGN KEY (`codice_cliente`) REFERENCES `clienti` (`codice`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=154 DEFAULT CHARSET=utf8 COMMENT='Elenco delle prenotazioni';

**Comment by mevdschee** [comment]
Ah.. now I see what the problem is. You cannot filter on other tables than the primary one, so I dropped support for the tablename.fieldname syntax in the filter.

**Comment by graziano1955** [comment]
OK for the filter but there is still a problem with include syntax.

My request 

    'records/prenotazioni?join=clienti&include=clienti.nome,clienti.cognome,' +
    'prenotazioni.codice, prenotazioni.data_arrivo, prenotazioni.data_partenza,' +
    'prenotazioni.adulti, prenotazioni.bambini, prenotazioni.animali, prenotazioni.note,' +
    'prenotazioni.caparra, prenotazioni.colazione' +
    '&filter=codice_camera,eq,' + codiceCamera +
    '&filter=data_arrivo,ge,' + startDate +
    '&filter=data_partenza,le,' + endDate;

give me a result like this

'{"records":[{"codice":92,"codice_cliente":{"codice":39,"nome":"antonio","cognome":"verdi"},"adulti":1,"caparra":null},{"codice":106,"codice_cliente":{"codice":38,"nome":"alfonso","cognome":"rossi"},"adulti":1,"caparra":null}]}'

I cannot see all columns requested in table prenotazioni, just a few

**Comment by graziano1955** [comment]
This request (without table name prefix in include)
    'records/prenotazioni?join=clienti&include=clienti.nome,clienti.cognome,' +
    'codice, data_arrivo, data_partenza,' +
    'adulti, bambini, animali, note,' +
    'caparra, colazione' +
    '&filter=codice_camera,eq,' + codiceCamera +
    '&filter=data_arrivo,ge,' + startDate +
    '&filter=data_partenza,le,' + endDate;
give me same result as above.

In V1

the request

    'prenotazioni?include=clienti&columns=clienti.nome,clienti.cognome,' +
    'prenotazioni.codice, prenotazioni.data_arrivo, prenotazioni.data_partenza,' +
    'prenotazioni.adulti, prenotazioni.bambini, prenotazioni.animali, prenotazioni.note,' +
    'prenotazioni.caparra, prenotazioni.colazione' +
    '&filter[]=prenotazioni.codice_camera,eq,' + codiceCamera +
    '&filter[]=prenotazioni.data_arrivo,ge,' + startDate +
    '&filter[]=prenotazioni.data_partenza,le,' + endDate + '&transform=1';

give me something like

'{"prenotazioni":[{"codice":98,"codice_cliente":43,"clienti":[{"codice":43,"nome":"asdfj","cognome":"popo"}],"data_arrivo":"2019-07-10","data_partenza":"2019-07-12","adulti":1,"bambini":0,"animali":0,"caparra":null,"note":null,"colazione":0},{"codice":106,"codice_cliente":38,"clienti":[{"codice":38,"nome":"alfonso","cognome":"rossi"}],"data_arrivo":"2019-07-06","data_partenza":"2019-07-07","adulti":1,"bambini":0,"animali":0,"caparra":null,"note":null,"colazione":0}]}'

**Comment by mevdschee** [comment]
Is this due to the spaces behind the comma?

**Comment by graziano1955** [comment]
YES!
Now it works.

Thank you so much.

**Comment by mevdschee** [comment]
Thank you very much for your patience and my apologies for the regression. I guess I implemented v2 a little stricter than v1. Let me know when you run into anything else.
