### ISSUE TITLE
Adding Swagger

### ISSUE THREAD

**Issue by webteambel** [mevdschee/php-crud-api#572]
Hello,

Thanks for your great Api Crud, I just want a little help , is it possible to integrate **swagger** with it ? I tried but to do it but I had some problems.

I think that the V1 branch in api.php was supporting swagger v2.

Thanks in advance for your reply.

**Comment by mevdschee** [comment]
Thank you for reaching out and for your kind words. Did you check out the `/api/openapi` endpoint?

**Comment by webteambel** [comment]
Thank you very much, that was very helpful.

**Comment by mevdschee** [comment]
You are welcome. Enjoy the software!
