### ISSUE TITLE
How to use dbAuth from database

### ISSUE THREAD

**Issue by DearPureone** [mevdschee/php-crud-api#575]
Hello again Mr.Maurits
I still using and learning from your software it very useful
come to ask for your advice again.
I  have already  make part to call API and it work perfectly.

what if i want to implement the Authentication from my database  (MS SQL Server)

Looking into [PHP-API-AUTH](https://github.com/mevdschee/php-api-auth) and [dbAuth](https://github.com/mevdschee/php-crud-api#database-authentication)
>  main([
        'default' => [
            'api.php' => [
                'secret' => 'someVeryLongPassPhraseChangeMe',
                'redirects' => 'http://localhost/vanilla.html',
                'validate' => function ($username, $password) {
                    **return $username == 'admin' && $password == 'admin';**
                },
            ],
        ],
    ]);

But how can i check for **$username**  **$password** from my database
Can you show me some Example 
or if i misunderstood something.

Thank for your advice.

**Comment by mevdschee** [comment]
You can either use dbAuth (more simple) or PHP-API-AUTH in combination with jwtAuth. I recommend you to explore the dbAuth route first. Configure the middleware and everything should work. You may read #556 for some background information.

**Comment by mevdschee** [comment]
Please open a new issue (or reopen this one) when you have new/further questions.

**Comment by DearPureone** [comment]
Sorry for my late reply, I've follow your suggestion with dbAuth
and change from \mysqli  to \pdo for my MS SQL Server 
> ```
> $config = new Config([
>     'username' => 'php-crud-api',
>     'password' => 'php-crud-api',
>     'database' => 'php-crud-api',
>     'middlewares' => 'customization',
>     'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
>         session_start();
>         $path = RequestUtils::getPathSegment($request, 1);
>         if ($path == 'login') {
>             $body = $request->getParsedBody();
>             $username = isset($body->username)?$body->username:'';
>             $password = isset($body->password)?$body->password:'';
>             $db = new \PDO("sqlsrv:server=sqlserver; Database=mydatabase", "mydatabaseuser", "mydatapasepassword");
>             $username = $db->escape_string($username);
>             $sql = "SELECT `username`, `password` FROM `users` WHERE `username`='$username'";
>             $result = $db->query($sql);
>             while ($row = $result->fetch_assoc()) {
>                 if (password_verify($password,$row['password'])==1) {
>                     session_regenerate_id(true);
>                     $_SESSION['username'] = $row['username'];
>                     header('HTTP/1.0 200 OK');
>                     exit(0);
>                 }
>             }
>             unset($_SESSION['username']);
>             header('HTTP/1.0 401 Unauthorized');
>             exit(0);
>         } else if ($path == 'logout') {
>             if (isset($_SESSION['username'])) {
>                 session_destroy();
>                 unset($_SESSION['username']);
>                 header('HTTP/1.0 200 OK');
>                 exit(0);
>             }
>             header('HTTP/1.0 401 Unauthorized');
>             exit(0);
>         } else {
>             if (!isset($_SESSION['username'])) {
>                 header('HTTP/1.0 401 Unauthorized');
>                 exit(0);
>             }
>         }
>     }
> ]);
> ```
> 

I've try to send post request from Postman
> ```
> {
> "username" : "username",
> "password" : "password"
> }
> ```
and got error code 
> ```
> {
> "code": 9999,
> "message": "Call to undefined method PDO::escape_string()"
> }
> ```
try to replace escape_string() with PDO::quote() still not work

Did I do something wrong?

**Comment by mevdschee** [comment]
Yes you are doing something wrong: you are not using the dbAuth middleware. Please enable and configure it and then create a login.html with a form that posts username and password to `/login`.

**Comment by DearPureone** [comment]
I'll find another way .
Much appreciated your help.

**Comment by mevdschee** [comment]
No problem, please feel free to open a new issue when you run into any problems.
