### ISSUE TITLE
Move configuration to separate file

### ISSUE THREAD

**Issue by pmeszaros** [mevdschee/php-crud-api#576]
Like one file solution, but for maintenance perspective is better keep configuration separately. Each time when I like update script from this repo, there is necessity edit configuration part of script.

**Comment by mevdschee** [comment]
Thank you for reaching out. Most people use composer to update dependencies. Does this work for you?

**Comment by pmeszaros** [comment]
Thank You for reaction. What I'm looking for is have content of $conf variable from api.php file somehow out of the script. So, take separately DB credentials and other setting related to usage with my DB.

**Comment by lcuis** [comment]
Hello @pmeszaros ,

We had the same need for a shared project. We wanted the configuration to be outside the api.php file. We ended up using the following lines to include the configuration file from a safe place (cannot be reached as easily as the api.php script):
```php
...
    if ((include '../safe/config.php') != true) {
        echo("<h3>Cannot include php-crud-api config, aborting.</h3>");
        exit;
    }

    $request = RequestFactory::fromGlobals();
...
```
The config.php file then contains the following for example:
```php
<?php
    $configArray = [
        'username' => 'example',
        'password' => 'example',
        'database' => 'example',
        'tables' => 'user',
        'debug' => 'true',
        'middlewares' => 'dbAuth,sanitation,validation',
        'validation.types' => 'all',
        'dbAuth.mode' => 'required',
        'dbAuth.usersTable' => 'user',
        'dbAuth.usernameColumn' => 'username',
        'dbAuth.passwordColumn' => 'pwhash',
        'dbAuth.returnedColumns' => 'id,timestamp,email,username,datacollection',
        'sanitation.handler' => function ($operation, $tableName, $column, $value) {
            return is_string($value) ? strip_tags($value) : $value;
        }
    ];
?>
```
In addition, we added a password protected configuration edition file `editconfig.php` (simple textarea) in the same folder as the configuration file which sends the old and new configurations by email at each edition:
```php
<?php
if(!array_key_exists("password",$_POST)||$_POST['password']!='youShouldChangeThisPassword'){
echo("<form action='editconfig.php' method='POST'>");
echo("Password: <input type='password' value='".(array_key_exists("password",$_POST)?$_POST['password']:"")."' name='password'><br>");
echo("<input type='submit'>");
echo("</form>");
exit;
}
$filename="config.php";
$content=file_get_contents($filename);
if($content===false){ 
echo("<h3>Cannot read file ".$filename."</h3>");
exit;
}
if(array_key_exists('autocrudconfig',$_POST)){
if($content==$_POST['autocrudconfig']){
echo("<h3 style='color:orange;'>Warning: no changes, not saved</h3>");
}
else{
$result=file_put_contents($filename,$_POST['autocrudconfig']);
if($result===false){
echo("<h3 style='color:red;'>Error writing to file</h3>");
}
else{
echo("<h3 style='color:green;'>Successfully wrote new content to file</h3>");
    $actual_link = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
    $emailbody="updated from ".$actual_link." by ip ".$_SERVER['REMOTE_ADDR']." on ".date("Y-m-d H:i:s")."\r\n";
    $emailbody.="---------->old config:---------->\r\n";
    $emailbody.=$content;
    $emailbody.="\r\n<----------old config:<----------\r\n";
    $emailbody.="---------->new config:---------->\r\n\r\n";
    $emailbody.=$_POST['autocrudconfig'];
    $emailbody.="\r\n\r\n<----------new config:<----------\r\n";
    $emailresult = mail("configchanged@example.com", "Update of php-crud-api config", $emailbody, "From: no-reply@example.com");
    if ($emailresult==false) {
        echo("<h3 style='color:red;'>Update email cannot be sent</h3>");
    }
}
$content=$_POST['autocrudconfig'];
}
}
echo("<form action='editconfig.php' method='POST'>");
echo("<textarea name='autocrudconfig' style='width:100%;' rows='50'>");
echo(htmlspecialchars($content));
echo("</textarea><br>");
echo("Password: <input type='password' value='".$_POST['password']."' name='password'><br>");
echo("<input type='submit'>");
echo("</form>");
?>
```
If you intend to use the configuration edition file, I recommend doubling the security by using  `.htaccess` and `.htpasswd` files to protect the folder access through authentication for example.

The edition script has proven to be quite useful to us really. I would like to improve it by sending in the email body the diff between the old and the new configurations and by attaching the 2 versions to the email instead of having them directly in the body. But since this is a more cosmetic than essential change, it will probably not happen soon.

**Comment by mevdschee** [comment]
You can adjust `src/index.php` and then rebuild the script using:

    php build.php

If you want to read the config from, for instance, the environment, then you can use `getenv()` in `index.php`.

**Comment by mevdschee** [comment]
Sorry @lcuis that I had to delete your comment, it had too many security considerations. I do appreciate all your effort to help people out. Please keep it up!

**Comment by lcuis** [comment]
> Sorry @lcuis that I had to delete your comment: it had too many security considerations. I do appreciate all your effort to help people out. Please keep it up!

No worries, I understand, thanks for the explanation and the good vibes!
