### ISSUE TITLE
Error 400: Bad request and error 405: Method not allowed on large batch

### ISSUE THREAD

**Issue by MaccerC** [mevdschee/php-crud-api#579]
Hi,
On updating database with http.put I get these errors with large batch (+150 records):
Error 400: Bad Request
Error: 405: Method not allowed

When I update less than say 150 records, all is working fine.
So I wonder, is there any limit in batch update (i.e. http.put requests)?

**Comment by mevdschee** [comment]
> So I wonder, is there any limit in batch update (i.e. http.put requests)?

Yes, there are limits although they are defined by the underlying system(s). Depending on your setup Nginx, Apache and PHP may be limiting your URL length and POST size.

**Comment by mevdschee** [comment]
Please share some details about your setup and the request that you are doing and maybe together we can find the configuration parameters that limit your URL length or POST size.

**Comment by MaccerC** [comment]
I use an Apache server with PHP (Apache/2.4.34 (Unix) PHP/7.1.23)
I want to do a batch update with http.put request. The request contains more than 150 id's and the body contains an array with an equal number of objects.
This is the full request:
`http.put<any>('api.php/records/agenda_items/' + id, body)`

where id is an array with the id's of the records to be updated and body is an array with the objects. The number of id's  is equal to the number of objects.

**Comment by mevdschee** [comment]
Is your url longer than 2kb or your message body larger than 10Mb?

See: https://stackoverflow.com/questions/2364840/what-is-the-size-limit-of-a-post-request

**Comment by MaccerC** [comment]
I don't know how to calculate the body size. All I can tell:
I'm posting more than 150 id's (each id is a number of 5 digits) and a body with an equal number of objects. The body consists of an array with objects. Each object has just one key/value pair like this: {keykey: "Valuevalue"} When I put about 2000 such objects in a separate file the file size is round 60KB. Does this add up to the size of the URL?

**Comment by mevdschee** [comment]
hmm.. it seems you are nowhere near any of the default limits :-/ Let me try to reproduce your scenario.

**Comment by mevdschee** [comment]
I have tested (using a test case) to add 1405 posts of 46 bytes (see fixture) and also to update those 1405 posts in a batch transaction (5977 byte URL) and there seem to be no limits in the software. This test uses >64Kb (66084 bytes) POST/PUT data in the message body. You can see the tests in:

    tests/functional/001_records/086_add_and_update_posts_in_large_batch.log

I hope this helps.
