### ISSUE TITLE
Not sure what I am doing wrong...

### ISSUE THREAD

**Issue by kriskhoury** [mevdschee/php-crud-api#58]
Hey!!!

Wondering what I am doing wrong. My Server:
http://dashlinks.kriskhoury.com/php.php

Data Table:
Backups - (id,email,password,json,created,revision)

I get the following result:
http://dashlinks.kriskhoury.com/api.php/backups

Am I missing an important part or is this a server configuration issue?

Thanks again for the help and this gem!

Kris

**Comment by mevdschee** [comment]
Can you uncomment the first line of the script and post the output?

**Comment by kriskhoury** [comment]
That worked!!!

Thank you sir. Cheers.

**Comment by mevdschee** [comment]
You are welcome
