### ISSUE TITLE
Error 502 Bad Gateway when I try to query table in SQL Server and server nginx

### ISSUE THREAD

**Issue by juanludukeboss** [mevdschee/php-crud-api#580]
Hi,
When I try to query table in SQL Server with the API, always I'm getting error 502 Bad Gateway. The server is ok, because a sample file with PDO connection PHP is working correctly, but the API is not working. 
For analyze the problem, I have doing profiling and I'm looking that the server is very slow in the method that get the structure information table and finally return 502 Bad Gateway. I attach capture of profiling.

![imagen](https://user-images.githubusercontent.com/42599905/66056040-ce152e00-e536-11e9-81ed-7564d6fc7a2c.png)

**Comment by mevdschee** [comment]
Thank you for filing this issue. It seems the request takes longer than 30 seconds, is that correct?

**Comment by mevdschee** [comment]
Can you tell me how many tables and how many columns you have in your database? The method you see that are slow are analyzing the database structure.

**Comment by juanludukeboss** [comment]
Yes, the problem is that database has about 3.000 tables, ¿it is possible that this is the problem?

**Comment by mevdschee** [comment]
Yes it is.. I'm analyzing all the tables and I'm storing the structure in the cache for quick retrieval.

**Comment by juanludukeboss** [comment]
It's possible modify anything in the API for just analyze the structure of tables that we are going to work, because for this project only needs 10 tables of this database. But the database complete is about 3.000 tables.

**Comment by mevdschee** [comment]
Currently this is not configurable, but I can make it so that you can.

**Comment by juanludukeboss** [comment]
I would appreciate it very much, because I only need to work with 10 tables for this project and I want to use this API, because this API is wonderful and very easy to use

**Comment by mevdschee** [comment]
I've released a new version (v2.6.0).

You can specify the "tables" now in the configuration.

Let me know whether or not it works for you.

**Comment by juanludukeboss** [comment]
The new parameter 'tables' in the configuration, Is a array of tables??

**Comment by mevdschee** [comment]
Yes, as the README states it is a "Comma separated list of tables", see:

https://github.com/mevdschee/php-crud-api/blob/master/README.md

**Comment by juanludukeboss** [comment]
No, the response return error 500, but the json response is "code" : 9999m, very curious.

I Attach capture.
![Captura de pantalla 2019-10-02 a las 19 09 02](https://user-images.githubusercontent.com/42599905/66065806-813a5300-e548-11e9-984f-2717209b56a1.png)

**Comment by mevdschee** [comment]
Please enable "debug"  in the configuration, that may give you some extra information (in the headers).

**Comment by juanludukeboss** [comment]
The error is in the line 5526. I attach the capture.

![Captura de pantalla 2019-10-02 a las 19 15 53](https://user-images.githubusercontent.com/42599905/66066113-2ead6680-e549-11e9-93cb-d34ddf01099b.png)

**Comment by mevdschee** [comment]
What request do you do? Are you comparing with a text ntext or image?

**Comment by mevdschee** [comment]
You could try to use "field,sw,value" instead of "field,eq,value" when you are comparing.

**Comment by juanludukeboss** [comment]
No, the query is very simple. The filter is in a the column numeric. I Attach the capture with the request.

![Captura de pantalla 2019-10-02 a las 19 28 26](https://user-images.githubusercontent.com/42599905/66067079-20f8e080-e54b-11e9-9d77-675c1a990e46.png)

**Comment by juanludukeboss** [comment]
no, the query is very simple. The filter is in a numeric field. I attach the capture

![Captura de pantalla 2019-10-02 a las 19 28 26](https://user-images.githubusercontent.com/42599905/66067271-88169500-e54b-11e9-86b2-709bc6a00ca5.png)

**Comment by mevdschee** [comment]
Is the primary key a text, ntext or image?

**Comment by mevdschee** [comment]
Comment out 10585 (Content-Length) and uncomment line 5525. You should see the failing query. This should help you find the cause.

**Comment by juanludukeboss** [comment]
Yes, the primary key is varchar type field. I has commented this line and effectively the problem is this. Attach the capture.
What solution can I make here??, because the database is not mine, is a database the my customer and it is in production with other program. :(
![Captura de pantalla 2019-10-02 a las 19 44 10](https://user-images.githubusercontent.com/42599905/66068200-7504c480-e54d-11e9-8407-0d06eb2205e6.png)

**Comment by mevdschee** [comment]
Did you find the failing SQL query?

**Comment by juanludukeboss** [comment]
I think that for this project I will design a simpler API, because there are very few tables and actions that must be performed on this SQL Server database. 

Thank you very much for your help.

**Comment by mevdschee** [comment]
>Thank you very much for your help.

You are welcome. Good luck with the project and thank you for your feedback!
