### ISSUE TITLE
Clarification of authorization middleware

### ISSUE THREAD

**Issue by hatsumatsu** [mevdschee/php-crud-api#582]
Hi, thank you for building this really handy piece of software. 

I was wondering whether the authorization handlers ( `authorization.tableHandler`, `authorization.columnHandler` , `authorization.recordHandler` ) can be combined and if there is a specific order of execution.

Let's say I want to generally block access to the `users` table but want to let users change their own password.

Could I combine

`````

'authorization.tableHandler' => function ($operation, $tableName) {
    return $tableName != 'users';
}
`````
with something like this?

`````
'authorization.recordHandler' => function ($operation, $tableName) {
    return ($tableName == 'users') ? 'filter=username,eq,' . $_SESSION['user'] : '';
}
`````

**Comment by mevdschee** [comment]
This seems both easy to try and easy to deduct from reading the source code. But let me try to answer as good as I can:

>Let's say I want to generally block access to the users table but want to let users change their own password.

Leave out the tableHandler, the recordHandler seems enough for this case. I hope this helps.

**Comment by hatsumatsu** [comment]
Thank you and good point about checking source!

**Comment by mevdschee** [comment]
Thank you for your question. Enjoy the software!
