### ISSUE TITLE
Joins are not working

### ISSUE THREAD

**Issue by DariuszPowroznik** [mevdschee/php-crud-api#583]
Hi,
I'm trying to GET posts with joined tables - like in example in documentation (https://github.com/mevdschee/php-crud-api#joins). But as response I have list without joined elements. Should I do something more to run joins?

**Comment by Disane87** [comment]
to do this. you need a clean PK -> FK relation. If you haven't this, you can't join tables together.

**Comment by mevdschee** [comment]
Indeed, as @Disane87 says: You need to define a foreign key constraint for joins to work.

**Comment by DariuszPowroznik** [comment]
Thanks! Its working now.

**Comment by Disane87** [comment]
> Indeed, as @Disane87 says: You need to define a foreign key constraint for joins to work.
> 
> (@Disane87 thank you for your super quick reply)

No problem @mevdschee, just saw that and couldn't get around :)
