### ISSUE TITLE
Create Dockerfile for official image

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#585]
In order to use the project using a docker image we need a Dockerfile that can be pointed to a database instance, similar to how phpMyAdmin and Adminer work.

- https://github.com/phpmyadmin/docker/blob/master/fpm-alpine/Dockerfile
- https://github.com/TimWolla/docker-adminer/blob/master/4/Dockerfile

Note that the config should be ~somehow editable~ (provided) using environment variables ~or an external config file~.

**Comment by ibonkonesa** [comment]
I don't undestand the meaning of editable config. A docker image must be stateless, so config is supposed to be provided via environment variables. I want to solve this issue but I need to know exactly what is the target

**Comment by mevdschee** [comment]
>A docker image must be stateless, so config is supposed to be provided via environment variables.

Great, that is exactly what I meant.

**Comment by ibonkonesa** [comment]
I think there would be nice to use dot-env (.env files), but this is not related with docker image. 
Dockerfile is fine, but code must implement an environment oriented database configuration in order to get this values from the context (docker, operative system, VPS, etc)

**Comment by mevdschee** [comment]
I agree

**Comment by mevdschee** [comment]
This is now implemented and available on Dockerhub:

https://hub.docker.com/r/mevdschee/php-crud-api

The repo also has a `docker-compose.yml` file now.
