### ISSUE TITLE
Forbid update of primary key - behavior confirmation

### ISSUE THREAD

**Issue by lcuis** [mevdschee/php-crud-api#588]
I noticed that if I forbid the update of my primary key through the `'authorization.columnHandler'`, I cannot update the record because the primary key cannot be used to match the record based on the primary key.
Therefore, I tried to allow the update of the primary key through the `'authorization.columnHandler'` and tried to update the primary key and nothing happened - which is great.

With this question, I would just like to make sure the intention is to not allow update of primary key columns through php-crud-api even if allowed in `'authorization.columnHandler'`.

This, way, I don't need to add such a trigger to forbid primary key update in MySQL/MariaDB:
```
delimiter $$
CREATE TRIGGER tg_tablename_protect_pk
BEFORE UPDATE
   ON tablename FOR EACH ROW
BEGIN
	SET NEW.id = OLD.id;
END$$
delimiter ;
```

Is my understanding correct?

**Comment by mevdschee** [comment]
>the intention is to not allow update of primary key columns through php-crud-api

Indeed.. primary keys should be technical and non-composite and thus updating is not allowed.

**Comment by lcuis** [comment]
Excellent, thank you very much for your confirmation!
