### ISSUE TITLE
Data integrity violation by postman

### ISSUE THREAD

**Issue by TransporterCL** [mevdschee/php-crud-api#589]
Hi, 
My name is Luis and having troubles ti post data in a simple table (InnoDB - MariaDB 10.141) by postman, i have no problems with GET, PUT, DELETE, etc.

![Captura de Pantalla 2019-11-04 a la(s) 09 50 24](https://user-images.githubusercontent.com/50333638/68122213-978d5300-fee8-11e9-86fc-b4f0b3344a19.png)
![Captura de Pantalla 2019-11-04 a la(s) 09 30 49](https://user-images.githubusercontent.com/50333638/68122214-9825e980-fee8-11e9-8943-a0827b176fd3.png)
![Captura de Pantalla 2019-11-04 a la(s) 09 23 49](https://user-images.githubusercontent.com/50333638/68122215-9825e980-fee8-11e9-99d4-5dccdcc62a1e.png)

Any suggestion please

greetings from Chile

**Comment by lcuis** [comment]
Hello @TransporterCL Luis,
My name is Louis.
Can you try to POST with raw such as the following?
```
{
  "text":"text2"
}
```
I get the same error message as you when I try to POST as form instead of raw.

**Comment by mevdschee** [comment]
You cannot post "null" values using form-urlencoded like that. You need to suffix the field name with "__is_null" to post "null" values, as implemented here:

https://github.com/mevdschee/php-crud-api/blob/master/api.php#L10149

I suggest that you use JSON raw body instead as @lcuis suggested.

**Comment by TransporterCL** [comment]
Thank you guys, I will try with raw
And thank for the quick answer too

**Comment by mevdschee** [comment]
Please let us know if there are any further questions.
