### ISSUE TITLE
DELETE with filter/multi-field PK

### ISSUE THREAD

**Issue by Shivol** [mevdschee/php-crud-api#59]
I have a reference table for many-to-many relationship. Its primary key is two foreign keys. Is there a way to remove rows without surrogate ID.?

**Comment by mevdschee** [comment]
No, at the moment there is not. As the readme states:

>- Composite primary or foreign keys are not supported

If you want to support custom queries you may want to look in a "stored procedure" API, something like this:

https://github.com/mevdschee/php-sp-api

NB: I've just started this project and it is less mature.

**Comment by Shivol** [comment]
Ok, thank you.
That procedure API looks promising!

**Comment by mevdschee** [comment]
Thank you :)
