### ISSUE TITLE
Error 500: due to localhost on live server?

### ISSUE THREAD

**Issue by MaccerC** [mevdschee/php-crud-api#594]
Hi,
Using successfully your api in local development I tested my app on a live testserver (a Synology NAS webserver). No problems so far.
Now I want to deploy it on a real, remote live server but I get a 500 internal server error.
I have tested the connection successfully with this separate PHP script:

```
    <?php
	$dsn = "mysql:host=<hostname>;dbname=<dbname>;charset=utf8";
	$username = "<username>";
	$pass = "<password>";

	try {
		$db = new PDO($dsn, $username, $pass);
		echo "Connected!";
	}
	catch(PDOException $e)
	{
	    echo "Connection Failed" . $e->getMessage();
	}
    ?>
```

Now I'm wondering: should I replace  'address' in the Config values (which is default 'localhost' ) to the hostname in the  above php script? Or do I leave it unchanged (i.e. localhost)?
The testserver (Synology) is a http server with php 7.2.13. The real live server is a https server, working with php 7.3.6 version. Does it make a difference http or https?

I don't have a clue to solve this problem. I hope you have...

gr, 
MaccerC

**Comment by mevdschee** [comment]
> should I replace 'address' in the Config values (which is default 'localhost' ) to the hostname in the above php script?

Yes

>Does it make a difference http or https?

No

**Comment by MaccerC** [comment]
So I did replace the 'address' to the mentioned hostname, but the error persists. I don't know how to check the error.log on this remote server. The browser console gives me this:
![Schermafbeelding 2019-11-20 om 07 08 01](https://user-images.githubusercontent.com/12985787/69213508-96a12600-0b64-11ea-8fc4-68bc4531c4e0.png)

**Comment by MaccerC** [comment]
Hij Maurits, I found the solution: I replaced all occurrences of 'localhost' with the hostname.
I'm glad it's working now.

gr., MaccerC
