### ISSUE TITLE
Laravel PUT and POST

### ISSUE THREAD

**Issue by fcontrerasz** [mevdschee/php-crud-api#595]
hi, im working with laravel....

when I try to send a request of both of methods... has a error and the field isn't changed. 

example:

`axios('/form/19/', {
                  method: 'PUT',
                  data: {"text": "test text"}
              }).then(function (response) {
                 alert("done")
              }).catch((error) => { 
                 alert("fail")
              });`

get error: {code: 9999, message: "Undefined offset: 0"}  (the request delete the last slash)

in postman, when try to send... I have the same problem.

![image](https://user-images.githubusercontent.com/6060664/69283410-2679bb00-0bcb-11ea-92c3-e86f869e779b.png)

**Comment by mevdschee** [comment]
Hi, thank you for your issue.

>the request delete the last slash

What do you mean? Can you explain better what happens? The last slash shoudn't be there.

What version of PHP and Laravel are you running?

**Comment by fcontrerasz** [comment]
look this..in red...

![image](https://user-images.githubusercontent.com/6060664/69283998-51184380-0bcc-11ea-84db-feaa1f11d5e2.png)

the browser send....

![image](https://user-images.githubusercontent.com/6060664/69284083-84f36900-0bcc-11ea-8a6c-29cf12a17724.png)

**Comment by mevdschee** [comment]
Okay, I doubt that is the cause of the problem, as that is a valid url (without the slash).

**Comment by fcontrerasz** [comment]
yes.... but in postman send correct the request.... but not update the field.

![image](https://user-images.githubusercontent.com/6060664/69284285-02b77480-0bcd-11ea-91e5-d19f4fff0f3b.png)

**Comment by fcontrerasz** [comment]
sorry I close for errror !

**Comment by fcontrerasz** [comment]
> Okay, I doubt that is the cause of the problem, as that is a valid url (without the slash).
> 
> Can you enable debug mode ('debug' => true in the config) and tell me the content of the debug headers?

![image](https://user-images.githubusercontent.com/6060664/69284513-8ffac900-0bcd-11ea-87c5-a72eba5f21a5.png)

**Comment by mevdschee** [comment]
Okay what version of Laravel are you running?

**Comment by fcontrerasz** [comment]
Laravel 5.8

**Comment by mevdschee** [comment]
Me too :-)

**Comment by mevdschee** [comment]
Do you have other middleware loaded?

**Comment by fcontrerasz** [comment]
Ok.

But, how in postman dont update the row in database? The request return the row complete with information.

Any more to do?

**Comment by mevdschee** [comment]
> The request return the row complete with information.

Yes, that is odd.. seems as if the PUT is not sent (but a GET is sent).

It would help if I could reproduce or if you could and that code was on Github. Is that possible?

**Comment by fcontrerasz** [comment]
Sendme a email to send a link

**Comment by fcontrerasz** [comment]
I send you an email!!

**Comment by mevdschee** [comment]
You are using Zend/Diactoros and I added support for it in 2.6.3 (you are on ^2.5). Please update composer.json and install the latest version.

**Comment by mevdschee** [comment]
Also, make sure you send 'Content-Type: application/json' as a request header.

**Comment by fcontrerasz** [comment]
thks !

**Comment by fcontrerasz** [comment]
Hi, look this new error....



![image](https://user-images.githubusercontent.com/6060664/69301554-6e153c80-0bf5-11ea-8944-d80c977896d6.png)

**Comment by mevdschee** [comment]
You can't store nested documents, see #587

**Comment by mevdschee** [comment]
Please open a new ticket for new issues.
