### ISSUE TITLE
LARAVEL PUT POST retrive GET

### ISSUE THREAD

**Issue by fcontrerasz** [mevdschee/php-crud-api#596]
Hi again,

I trying to save info to a test table, but the result is a GET info about the row and dont save anything.

this dont update and store rows....

![image](https://user-images.githubusercontent.com/6060664/69332469-85741a00-0c35-11ea-860d-fc4357e616c3.png)

look this:

![image](https://user-images.githubusercontent.com/6060664/69332580-c1a77a80-0c35-11ea-8f7a-a6877eff2638.png)

PD: im sending context type: json.

**Comment by mevdschee** [comment]
>PD: im sending context type: json.

Are you sending exactly this?

    Content-Type: application/json

Because that is needed.

**Comment by mevdschee** [comment]
>I trying to save info to a test table, but the result is a GET info about the row and dont save anything.

Is this problem only happening in Postman?

POST is for inserting and should not have the '/1' suffix so:

    POST /records/test

and:

    PUT /records/test/1

Maybe that helps?

**Comment by mevdschee** [comment]
Any update?

**Comment by fcontrerasz** [comment]
Hi, I found the problem.

Its about how I send the data, I tried to send a "Object" data many times, finally convert the data with JSON.stringify.

now works fine !

thks a lot.
