### ISSUE TITLE
Authorise problem (localhost:3000 and localhost/api)

### ISSUE THREAD

**Issue by DariuszPowroznik** [mevdschee/php-crud-api#597]
I'm writing app in ReactJS.
I wrote before (https://github.com/mevdschee/php-crud-api/issues/591) and that problem was solved.
Now I have new one. 
My front-end app is executed on http://localhost:3000 but my back-end api is on http://localhost/api/api.php.
I resolved issue with CROSS origin. But now, despite logging in, I still don't have access to api when I try to do call. 
In network I see that I send cookie that I got after logging (look on screenshots).

Should I add some extra config?
On Postman all works fine.

After login:
![cookie](https://user-images.githubusercontent.com/23011586/69334188-7c497400-0c5a-11ea-98a2-cf803f4b293b.png)

When I want to go to some page and send request to api:
![res_tab2](https://user-images.githubusercontent.com/23011586/69334190-7ce20a80-0c5a-11ea-8121-ca44af197b8b.png)
![res_tab1](https://user-images.githubusercontent.com/23011586/69334189-7c497400-0c5a-11ea-954b-e6d13461164c.png)

**Comment by mevdschee** [comment]
I'm guessing it is using fetch and credentials are not enabled, see:

https://developers.google.com/web/updates/2015/03/introduction-to-fetch

**Comment by DariuszPowroznik** [comment]
It was my problem before (I'm using axios). But I resolve it adding `{ withCredentials: true, }` (https://codewithhugo.com/pass-cookies-axios-fetch-requests/)

As you can see on second screenshot cookie is being sent with request but it still throw 401 unauthorised.

**Comment by mevdschee** [comment]
> On Postman all works fine.

Than it is most likely a problem in your React configuration

> In network I see that I send cookie 

Sending a cookie is no guarantee that the authentication succeeds.

Can you do the calls with Postman and with React and compare the differences?

**Comment by DariuszPowroznik** [comment]
This are screens from postman. I see that when I send cookie by React app - domain, path etc are N/A. On Postman it looks ok. 
Could it be a reason?

![postman](https://user-images.githubusercontent.com/23011586/69615088-9a391f00-1034-11ea-828c-6f445f1051bb.png)
![postman-cookie](https://user-images.githubusercontent.com/23011586/69615089-9a391f00-1034-11ea-82cd-ca35a5149184.png)

**Comment by DariuszPowroznik** [comment]
Oh. It's working.
The reason was that I tried to add withCredentialst like that:
`  .get(
    '/cookie-auth-protected-route',
    { withCredentials: true }
  )`

If someone in future will have similar problem - just add this as default for axios:
`axios.defaults.withCredentials = true;`

It's working only with that... I don't know why... JS... ;)
