### ISSUE TITLE
Empty response when columnHandler prevents update.

### ISSUE THREAD

**Issue by resident0** [mevdschee/php-crud-api#598]
I'm using v2.6.5. When I try to update a column that has been filtered by ``` authorization.columnHandler ``` or a group of columns that includes one that is filtered an empty response is returned with no indication that a conflict has occurred. Would it be possible for this situation to issue a 403 response code so a message like "Resource $columnName restricted" can be sent so filtered columns can be removed from the request?

**Comment by mevdschee** [comment]
>When I try to update a column that has been filtered by authorization.columnHandler or a group of columns that includes one that is filtered an empty response is returned with no indication that a conflict has occurred.

Hi, I added a test to show that this should not happen :-)

**Comment by resident0** [comment]
It turns out that I am week testing the result for truthy-ness and pulling any error from curl. The string '0' result fails but there is no curl error. The failure of the group update was the result of not noting a change in the columnHandler method.

After looking closely at how the columnHandler is implemented I can see that a 403 response doesn't make sense.

Thanks for helping me out.
