### ISSUE TITLE
What would be a good way to add custom validation of query params?

### ISSUE THREAD

**Issue by perqa** [mevdschee/php-crud-api#6]
What would be a good way to add custom validation of query params?

**Comment by mevdschee** [comment]
How about if I add a callback system to register extension functions, would that be useful? What should the signature be?

Function extension_callback($operation,$database,$table,$id,$object,$parameters)

Operation could be a crud operation, like "list" or "insert"
Database is the name of the database
Table is the name of the table
Id is the primary key value for the operation (or null)
Object are the values that are stored in the insert or update (or null)
Parameters are the filter and sort options for list (or null)

Would something like this be a good start for an extension system?

**Comment by perqa** [comment]
I had something simpler in mind, and something that would intercept the flow at an earlier stage - actually at the earliest possible - before even involving the database. My thought was to use key - value pairs consisting of query param - function:
'queryparam1': 'func1',
'queryparam2': 'func2',
'queryparam3': 'func1',
etc
where one has to write one's own validation functions. Each function returns the new checked and processed value of each query parameter, or false if invalid. Then you can choose to terminate further execution before even invoking the db in case any doubtful query params are encountered.

**Comment by mevdschee** [comment]
I updated the code. ```$api->executeCommand();``` now accepts an array of callbacks with ```$parameters``` as arguments. These are functions that look like ```function callback($parameters)``` and within that function you need to check the values for ```$parameters['input']```.

**Comment by mevdschee** [comment]
You can now specify an ```input_validator``` callback in the config. This callback is a function with the following signature:

```function validate($action,$database,$table,$column,$value)```

It may return false or an error message (string) when the input is not valid. 

see: 596c503a3c174f35c00308e56b8c24db67582798

**Comment by mevdschee** [comment]
@perqa Can I close the issue?
