### ISSUE TITLE
BasicAuth session name

### ISSUE THREAD

**Issue by sookoll** [mevdschee/php-crud-api#600]
I have quite unic situation. I have a site, where users can log in. Site make some ajax requests to api, which is secured by BasicAuth. And I ran into session conflict, as site send PHPSESSID and API send PHPSESSID and after that broser change it for site and SESSION got lost for user.

I know it is not ideal solution, but simplest for now. I fix it by setting session name for site. But it should be configurable in api.

"basicAuth.sessionName" option for example, defaults to PHPSESSID.
And before You do session_start(), do session_name() with that option value.

**Comment by mevdschee** [comment]
Good feature request. Should not take long to implement.

**Comment by mevdschee** [comment]
See: v2.6.6 Support sessionName

**Comment by sookoll** [comment]
It works! Awsome job! Thanks.
