### ISSUE TITLE
Views in MySQL work on localhost but not on server 

### ISSUE THREAD

**Issue by marcelkrassenburg** [mevdschee/php-crud-api#603]
Hi,
I want to use MySQL views to serve datasets (read-only). This works fine on localhost but not on the server MySQL database, returns {"code":9999}. 

Requests on tables work fine on server. 

on table:  ..../records/cc_event   OK
on view: ..../records/cv_event   not OK code 9999

Simple table: cc_event with e_id int(11) primary key, AI and e_name varchar(250)
Simple view: create or replace view cv_event as select e_id, e_name from cc_event;

On server, phpMyAdmin reports PHP-versie: 5.5.38
In php-application phpversion(); returns 7.0.24
(I do not understand the difference)

Any idea what goes wrong?

--------- Specifications

LOCAL
   Windows, 
**Databaseserver**
    Server: 127.0.0.1 via TCP/IP
    Servertype: MariaDB
    Serverversie: 10.1.28-MariaDB - mariadb.org binary distribution
    Protocolversie: 10
    Gebruiker: root@localhost
    Karakterset van server: UTF-8 Unicode (utf8)
**Webserver**
     Apache/2.4.28 (Win32) OpenSSL/1.0.2l PHP/7.0.24
    Clientversie van database: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
    PHP-uitbreiding: mysqliDocumentatie curlDocumentatie mbstringDocumentatie
    PHP-versie: 7.0.24

SERVER on Versio
**Databaserver**
    Server: Localhost via UNIX socket
    Servertype: MariaDB
    Serververbinding: SSL wordt niet gebruikt Documentatie
    Serverversie: 10.1.23-MariaDB - MariaDB Server
    Protocolversie: 10
    Gebruiker: ******<user>******@localhost
    Karakterset van server: cp1252 West European (latin1)
**Webserver**
     Apache/2
    Cliëntversie van database: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 15d5c781cfcad91193dceae1d2cdd127674ddb3e $
    PHP-uitbreiding: mysqliDocumentatie curlDocumentatie mbstringDocumentatie
    PHP-versie: 5.5.38

**Comment by mevdschee** [comment]
>On server, phpMyAdmin reports PHP-versie: 5.5.38

You need PHP 7 or higher, see: https://github.com/mevdschee/php-crud-api/blob/master/README.md#requirements

>PHP 5.6 End of Life happened on December 31, 2018.

source: https://endoflife.software/programming-languages/server-side-scripting/php

It is not okay to run this version, https://www.versio.nl/ should upgrade ASAP!
