### ISSUE TITLE
Google Firebase JWT authorization to CRUD API fails

### ISSUE THREAD

**Issue by NorthFred** [mevdschee/php-crud-api#606]
I tried following the instructions in the README.md to use authorization with JWT on the php-crud-api, but I must be doing something incorrectly, as all my requests are returning a 403 status with a 1012 error code.

My mobile (Android) app created with Ionic framework uses Google Firebase for signing up and logging in new users. Authorization is handled by Firebase, where I have successfully created a project and completed the integration with my app. New users are able to sign up via email and log in to the app.

Via the AngularFireAuth library `'angularfire2/auth'` , I can retrieve a token for the signed-in user account.

`	getToken() {
		return this.afAuth.auth.currentUser.getIdToken();
	}`

In the php-file, I have following configuration:

```
    $config = new Config([
        'username' => 'username_for_database',
        'password' => 'password',
        'database' => 'xx_database',
        'address' => 'mysqlxx5.domain.xx',
        'cacheType' => 'NoCache',
        'middlewares' => 'authorization, jwtAuth',
        'jwtAuth.secret' => '-----BEGIN CERTIFICATE-----\nMII**secret-stuff-here--2C\n-----END CERTIFICATE-----\n'
    ]);
```

I got the 'jwtAuth.secret' from the link in the documentation:

https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com](https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com)

What is unclear to me though, is how the service account is linked to the user's token?

These are the service accounts currently defined in my project. The last one in the list was created for the API access.

![service](https://user-images.githubusercontent.com/26854315/71544216-e6091c00-2984-11ea-96d5-e3076079de7d.jpg)

How can start making successful API requests via the retrieved user token? Or do I need to handle this differently?

Many thanks!

**Comment by mevdschee** [comment]
I think you need a different order of middlewares:

        'middlewares' => 'authorization, jwtAuth',

should be:

        'middlewares' => 'jwtAuth,authorization',

Does that help you any further?

**Comment by NorthFred** [comment]
I wish it was that simple, but that didn't help. Any other ideas?

**Comment by NorthFred** [comment]
Also, I checked that I had the correct "kid" from the public certificate , matching with the decoded token:

![jwt](https://user-images.githubusercontent.com/26854315/71548142-b244eb00-29b2-11ea-98c3-29625d4d08a4.jpg)

**Comment by mevdschee** [comment]
The setting "jwtAuth.secret" is now called "jwtAuth.secrets". It should contain "kid:key" pairs. Did you notice?

**Comment by NorthFred** [comment]
Seems I overlooked that completely...

Perhaps still a silly question, but what is the correct format for the pairs?

E.g. this does not work and returns 500 status:

```
'jwtAuth.secrets' => {
  "d7635ab646e07fd199f74b016a9543922a0cff9a": "-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIILQz84oV/Q7wwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTkx\nMjE0MjEyMTA2WhcNMTkxMjMxMDkzNjA2WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAKsM2Azr5FMn8U35o3+o26CJ13Zn3jkJRs4Tfdcgq2YL/9sx\nm9/EJ8Z6DuCSw6t12+7v0xEyjs/VloQd5lR4nWYhe/bR5Ko5AOZfip5Z+noRD9FE\nDl3ZkQdvjDcaiqaj9CuO4fRdKCi7mT2yeNFeFo7wckI3ZH9nDtQRQ+oD/ELa9Ox0\n2UqXk28QZfed3awz47/OHQ2TGd6XNFyDZ8BhNC3pA30gMVdEdmLnVcq/LFedn8d7\nTkIyklVlfyjzdPF5JbCkspX9HnkB4pg37U0hLYSvGkrOa1DT9A4+AjkLrP1aS9WV\nrPxpMtQyrlVxUjmhb5J6EW/70oQlBvzyuce25rUCAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBABCDhmu26cpOSEj+BH6tYDdJsNacceJ2BIUYV8lnLEOy\n72FoGWtLCchMWHsbh51HedaDdiH4A7dtmBmd8NRV0rIUSiZrfMAyocNP9uOCizRi\nCl3aPZqBlQ1ZUxsSelqrfbSFgep8pyLd7HQ64Kfs2FjnMU+3DAIiKa4BTVxuhfhp\n9f1j4duGmHph4aC1FpdIDqK8DswBIMSPMtErbwF9rbcajr/LdVtGXhhSD9pdoQZs\n0UOYt1k9VmJiteg5BmHwX7Pi19Oxc4DMiUMmLXX3Bn6uuDWTjwcHgyAKUAOipEdB\ngzhfQ5WxWJWKcwrkxfpzYstTpUqsJwT7z8V8gggVJB8=\n-----END CERTIFICATE-----\n",
  "ce5ced6e40dcd1eff407048867b1ed1e706686a0": "-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIExun9bJSK1wwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTkx\nMjIyMjEyMTA3WhcNMjAwMTA4MDkzNjA3WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAKsvVDUwXeYQtySNvyI1/tZAk0sj7Zx4/1+YLUomwlK6vmEd\nyl2IXOYOj3VR7FBA24A9//nnrp+mV8YOYEOdaWX7PQo0PIPFPqdA0r7CqBUWHPfQ\n1WVHVRQY3G0c7upM97UfMes9xOrMqyvecMRk1e5S6eT12Zh2og7yiVs8gP83M1EB\nGqseUaltaadjyT35w5B0Ny0/7NdLYiv2G6Z0S821SxvSo1/wfmilnBBKYYluP0PA\n9NPznWFP6uXnX7gKxyJT9//cYVxTO6+b1TT13Yvrpm1a4EuCOhLrZH6ErHQTccAM\nhAx8mdNtbROsp0dlPKrSfqO82uFz45RXZYmSeP0CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBACNsJ5m00gdTvD6j6ahURsGrNZ0VJ0YREVQ5U2Jtubr8\nn2fuhMxkB8147ISzfi6wZR+yNwPGjlr8JkAHAC0i+Nam9SqRyfZLqsm+tHdgFT8h\npa+R/FoGrrLzxJNRiv0Trip8hZjgz3PClz6KxBQzqL+rfGV2MbwTXuBoEvLU1mYA\no3/UboJT7cNGjZ8nHXeoKMsec1/H55lUdconbTm5iMU1sTDf+3StGYzTwC+H6yc2\nY3zIq3/cQUCrETkALrqzyCnLjRrLYZu36ITOaKUbtmZhwrP99i2f+H4Ab2i8jeMu\nk61HD29mROYjl95Mko2BxL+76To7+pmn73U9auT+xfA=\n-----END CERTIFICATE-----\n"
}
```

**Comment by mevdschee** [comment]
It should be "kid1:key1,kid2:key2".. I hope that helps.

**Comment by NorthFred** [comment]
```
    $config = new Config([
        'username' => 'xxxxxxxx',
        'password' => 'xxxxxxxx',
        'database' => 'xxxxxxxx',
        'address' => 'mysql05.xxxxxx.xxx',
        'cacheType' => 'NoCache',
        'middlewares' => 'cors, jwtAuth, authorization',
        'jwtAuth.secrets' => 'ce5ced6e40dcd1eff407048867b1ed1e706686a0:-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIExun9bJSK1wwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTkx\nMjIyMjEyMTA3WhcNMjAwMTA4MDkzNjA3WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAKsvVDUwXeYQtySNvyI1/tZAk0sj7Zx4/1+YLUomwlK6vmEd\nyl2IXOYOj3VR7FBA24A9//nnrp+mV8YOYEOdaWX7PQo0PIPFPqdA0r7CqBUWHPfQ\n1WVHVRQY3G0c7upM97UfMes9xOrMqyvecMRk1e5S6eT12Zh2og7yiVs8gP83M1EB\nGqseUaltaadjyT35w5B0Ny0/7NdLYiv2G6Z0S821SxvSo1/wfmilnBBKYYluP0PA\n9NPznWFP6uXnX7gKxyJT9//cYVxTO6+b1TT13Yvrpm1a4EuCOhLrZH6ErHQTccAM\nhAx8mdNtbROsp0dlPKrSfqO82uFz45RXZYmSeP0CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBACNsJ5m00gdTvD6j6ahURsGrNZ0VJ0YREVQ5U2Jtubr8\nn2fuhMxkB8147ISzfi6wZR+yNwPGjlr8JkAHAC0i+Nam9SqRyfZLqsm+tHdgFT8h\npa+R/FoGrrLzxJNRiv0Trip8hZjgz3PClz6KxBQzqL+rfGV2MbwTXuBoEvLU1mYA\no3/UboJT7cNGjZ8nHXeoKMsec1/H55lUdconbTm5iMU1sTDf+3StGYzTwC+H6yc2\nY3zIq3/cQUCrETkALrqzyCnLjRrLYZu36ITOaKUbtmZhwrP99i2f+H4Ab2i8jeMu\nk61HD29mROYjl95Mko2BxL+76To7+pmn73U9auT+xfA=\n-----END CERTIFICATE-----\n',
        'cors.allowedOrigins' => '*',
        'cors.allowHeaders' => 'X-Authorization'
    ]);
```

Still no luck :( I tried several combinations with string formats, but all of them return the same 403 / 1012 error.

**Comment by mevdschee** [comment]
The error code means it cannot decode the claims:

        if (empty($claims)) {
                    return $this->responder->error(ErrorCode::AUTHENTICATION_FAILED, 'JWT');

see: https://github.com/mevdschee/php-crud-api/blob/341fe344d095928c5e6bf40042a5014c65b24a23/src/Tqdev/PhpCrudApi/Middleware/JwtAuthMiddleware.php#L142

I would try a debugger and go step-by-step through the code.

**Comment by NorthFred** [comment]
It seems that the token is not found, as inside this function the claims are empty:

```
        public function process(ServerRequestInterface $request, RequestHandlerInterface $next): ResponseInterface
        {
            if (session_status() == PHP_SESSION_NONE) {
                if (!headers_sent()) {
                    session_start();
                }
            }
            if ($token) {
                $claims = $this->getClaims($token);
                $_SESSION['claims'] = $claims;
                if (empty($claims)) {
                    error_log('Claims is empty!');
                    return $this->responder->error(ErrorCode::AUTHENTICATION_FAILED, 'JWT');
                }
                if (!headers_sent()) {
                    session_regenerate_id();
                }
            }
            if (empty($_SESSION['claims'])) {
                $authenticationMode = $this->getProperty('mode', 'required');
                if ($authenticationMode == 'required') {
                    return $this->responder->error(ErrorCode::AUTHENTICATION_REQUIRED, '');
                }
            }
            return $next->handle($request);
        }
```

I double-checked my front-end code, and it correctly retrieves the token from the logged in user. The token is then passed on in the 'X-Authorization' header of the request, which contains the string as e.g. `Bearer eyJhb....etc....`

Somehow the token is not properly detected via PHP, but I seem to lack the skills to properly pinpoint the problem on that end :/

**Comment by mevdschee** [comment]
>but I seem to lack the skills to properly pinpoint the problem on that end :/

Is there any way I can help you with that?

**Comment by NorthFred** [comment]
I am more of a front-end person... :) How can I trace whether the php.api is reading the token? What is the best place to add e.g. some 'error_logs()' statements to read the info that is being passed on inside the php?

**Comment by mevdschee** [comment]
It is probably one of the empty array returns here:

https://github.com/mevdschee/php-crud-api/blob/341fe344d095928c5e6bf40042a5014c65b24a23/src/Tqdev/PhpCrudApi/Middleware/JwtAuthMiddleware.php#L14

Maybe you can do a `die('test_case_1')` before the return... this should output 'test_case_1' and end the script.

**Comment by NorthFred** [comment]
It seems that none of the private functions inside `class JwtAuthMiddleware` are reached.
Only the public function `process()` is gone through, and there it fails with the authentication error.

Btw, thanks for you effort and quick replies, I appreciate the help!

**Comment by mevdschee** [comment]
Is the token (header) read? Can you look into this method?

https://github.com/mevdschee/php-crud-api/blob/341fe344d095928c5e6bf40042a5014c65b24a23/src/Tqdev/PhpCrudApi/Middleware/JwtAuthMiddleware.php#L112

Kind regards, Maurits

**Comment by NorthFred** [comment]
No, it is not :( No header, no value. The function/method is not even called...

**Comment by mevdschee** [comment]
but the process method is called? Is `session_start` failing with an error in the Apache log?

**Comment by NorthFred** [comment]
First part of the problem found.... Somewhere along the editing, I must have accidently deleted this line from the` process() `method (ooops):

[$token = $this->getAuthorizationToken($request);](url)

Adding it back in already takes me much further... So the next issue:

```
        private function getAuthorizationToken(ServerRequestInterface $request): string
        {
            $headerName = $this->getProperty('header', 'X-Authorization');
            $headerValue = RequestUtils::getHeader($request, $headerName);
            $parts = explode(' ', trim($headerValue), 2);
            if (count($parts) != 2) {
                return '';
            }
            if ($parts[0] != 'Bearer') {
                return '';
            }
            return $parts[1];
        }
```

The token part is returned as [undefined](url).

**Comment by mevdschee** [comment]
Can you paste the content (first 20 chars) of the headerValue variable?

**Comment by NorthFred** [comment]
Had another issue in my UI code, occasionally the token would be sent as undefined. After resolving this, the code ends up on the back-end, so I did some more logging and here are the print-outs:

```
[30-Dec-2019 13:28:24 Europe/Helsinki] X-Authorization
[30-Dec-2019 13:28:24 Europe/Helsinki] header value:
[30-Dec-2019 13:28:24 Europe/Helsinki] Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImN********************REMOVED
[30-Dec-2019 13:28:24 Europe/Helsinki] Bearer
[30-Dec-2019 13:28:24 Europe/Helsinki] eyJhbGciOiJSUzI1NiIsImtpZCI6ImN********************REMOVED
[30-Dec-2019 13:28:24 Europe/Helsinki] getClaims()
[30-Dec-2019 13:28:24 Europe/Helsinki] getVerifiedClaims()
[30-Dec-2019 13:28:24 Europe/Helsinki] Public key:
[30-Dec-2019 13:28:24 Europe/Helsinki] -----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIExun9bJSK1wwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTkx\nMjIyMjEyMTA3WhcNMjAwMTA4MDkzNjA3WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAKsvVDUwXeYQtySNvyI1/tZAk0sj7Zx4/1+YLUomwlK6vmEd\nyl2IXOYOj3VR7FBA24A9//nnrp+mV8YOYEOdaWX7PQo0PIPFPqdA0r7CqBUWHPfQ\n1WVHVRQY3G0c7upM97UfMes9xOrMqyvecMRk1e5S6eT12Zh2og7yiVs8gP83M1EB\nGqseUaltaadjyT35w5B0Ny0/7NdLYiv2G6Z0S821SxvSo1/wfmilnBBKYYluP0PA\n9NPznWFP6uXnX7gKxyJT9//cYVxTO6+b1TT13Yvrpm1a4EuCOhLrZH6ErHQTccAM\nhAx8mdNtbROsp0dlPKrSfqO82uFz45RXZYmSeP0CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBACNsJ5m00gdTvD6j6ahURsGrNZ0VJ0YREVQ5U2Jtubr8\nn2fuhMxkB8147ISzfi6wZR+yNwPGjlr8JkAHAC0i+Nam9SqRyfZLqsm+tHdgFT8h\npa+R/FoGrrLzxJNRiv0Trip8hZjgz3PClz6KxBQzqL+rfGV2MbwTXuBoEvLU1mYA\no3/UboJT7cNGjZ8nHXeoKMsec1/H55lUdconbTm5iMU1sTDf+3StGYzTwC+H6yc2\nY3zIq3/cQUCrETkALrqzyCnLjRrLYZu36ITOaKUbtmZhwrP99i2f+H4Ab2i8jeMu\nk61HD29mROYjl95Mko2BxL+76To7+pmn73U9auT+xfA=\n-----END CERTIFICATE-----\n
[30-Dec-2019 13:28:24 Europe/Helsinki] PHP Warning:  openssl_verify(): supplied key param cannot be coerced into a public key in /*****/*******/public_html/********/api/api.php on line 7664
[30-Dec-2019 13:28:24 Europe/Helsinki] Claims is empty!
```

**Comment by mevdschee** [comment]
It is clear that `$claims` will be empty when `openssl_verify` fails to decode the key.

Is this reproducible?

**Comment by NorthFred** [comment]
Yes, I keep on getting this error now:

`PHP Warning:  openssl_verify(): supplied key param cannot be coerced into a public key`

I wonder if there still is something wrong with the public key formatting?
      `  'jwtAuth.secrets' => 'ce5ced6e40dcd1eff407048867b1ed1e706686a0:-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIExun9bJSK1wwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTkx\nMjIyMjEyMTA3WhcNMjAwMTA4MDkzNjA3WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAKsvVDUwXeYQtySNvyI1/tZAk0sj7Zx4/1+YLUomwlK6vmEd\nyl2IXOYOj3VR7FBA24A9//nnrp+mV8YOYEOdaWX7PQo0PIPFPqdA0r7CqBUWHPfQ\n1WVHVRQY3G0c7upM97UfMes9xOrMqyvecMRk1e5S6eT12Zh2og7yiVs8gP83M1EB\nGqseUaltaadjyT35w5B0Ny0/7NdLYiv2G6Z0S821SxvSo1/wfmilnBBKYYluP0PA\n9NPznWFP6uXnX7gKxyJT9//cYVxTO6+b1TT13Yvrpm1a4EuCOhLrZH6ErHQTccAM\nhAx8mdNtbROsp0dlPKrSfqO82uFz45RXZYmSeP0CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBACNsJ5m00gdTvD6j6ahURsGrNZ0VJ0YREVQ5U2Jtubr8\nn2fuhMxkB8147ISzfi6wZR+yNwPGjlr8JkAHAC0i+Nam9SqRyfZLqsm+tHdgFT8h\npa+R/FoGrrLzxJNRiv0Trip8hZjgz3PClz6KxBQzqL+rfGV2MbwTXuBoEvLU1mYA\no3/UboJT7cNGjZ8nHXeoKMsec1/H55lUdconbTm5iMU1sTDf+3StGYzTwC+H6yc2\nY3zIq3/cQUCrETkALrqzyCnLjRrLYZu36ITOaKUbtmZhwrP99i2f+H4Ab2i8jeMu\nk61HD29mROYjl95Mko2BxL+76To7+pmn73U9auT+xfA=\n-----END CERTIFICATE-----\n'
`

**Comment by NorthFred** [comment]
I got it working :)  It seems important to use **double quotes** in the secrets string definition.
Also, the string may not contain any spaces before or after the ':' sign in the string.
This is what my public key looks like in the config:

`        'jwtAuth.secrets' => "ce5ced6e40dcd1eff407048867b1ed1e706686a0:-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIExun9bJSK1wwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTkx\nMjIyMjEyMTA3WhcNMjAwMTA4MDkzNjA3WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAKsvVDUwXeYQtySNvyI1/tZAk0sj7Zx4/1+YLUomwlK6vmEd\nyl2IXOYOj3VR7FBA24A9//nnrp+mV8YOYEOdaWX7PQo0PIPFPqdA0r7CqBUWHPfQ\n1WVHVRQY3G0c7upM97UfMes9xOrMqyvecMRk1e5S6eT12Zh2og7yiVs8gP83M1EB\nGqseUaltaadjyT35w5B0Ny0/7NdLYiv2G6Z0S821SxvSo1/wfmilnBBKYYluP0PA\n9NPznWFP6uXnX7gKxyJT9//cYVxTO6+b1TT13Yvrpm1a4EuCOhLrZH6ErHQTccAM\nhAx8mdNtbROsp0dlPKrSfqO82uFz45RXZYmSeP0CAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBACNsJ5m00gdTvD6j6ahURsGrNZ0VJ0YREVQ5U2Jtubr8\nn2fuhMxkB8147ISzfi6wZR+yNwPGjlr8JkAHAC0i+Nam9SqRyfZLqsm+tHdgFT8h\npa+R/FoGrrLzxJNRiv0Trip8hZjgz3PClz6KxBQzqL+rfGV2MbwTXuBoEvLU1mYA\no3/UboJT7cNGjZ8nHXeoKMsec1/H55lUdconbTm5iMU1sTDf+3StGYzTwC+H6yc2\nY3zIq3/cQUCrETkALrqzyCnLjRrLYZu36ITOaKUbtmZhwrP99i2f+H4Ab2i8jeMu\nk61HD29mROYjl95Mko2BxL+76To7+pmn73U9auT+xfA=\n-----END CERTIFICATE-----\n",`

**Comment by mevdschee** [comment]
Great! Well done. I'm glad you worked it out. Do you feel the documentation needs an improvement? If so, can you propose it (in a PR)?

**Comment by NorthFred** [comment]
Happy New Year!
I created a PR with some additions to the README.md. Please see https://github.com/mevdschee/php-crud-api/pull/607

**Comment by mevdschee** [comment]
Awesome.. thank you very much and the best wishes for 2020!

**Comment by leossmith** [comment]
I think I have the same issue. I try to set this app locally but get an error:

`{
    "code": 1011,
    "message": "Authentication required"
}`

This is my config:

`$config = new Config([
        'username' => 'root',
        'password' => '',
        'database' => 'mydb',
        'cacheType' => 'NoCache',
        'middlewares' => 'cors, jwtAuth, authorization',
        'jwtAuth.secrets' => "51402b3d042b2976943f05fe2ed429b73643f651:-----BEGIN CERTIFICATE-----\nMIIDHDCCAgSgAwIBAgIIU9uuogvqiBMwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE\nAxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMjAw\nMTA3MjEyMTA3WhcNMjAwMTI0MDkzNjA3WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl\nbi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBAMXwx/2WuLZ19vGpO+Wga9LMv+/8uUv/kQEs1hILIAo519dU\ncOUix/LTzulwyKlUVeCpnhe3FugU/RYKaf0u3H3yhqjqlYtR62EEJSeEYsF/B63c\njr3Zx7Nas8NK6bpLJ03ChhbS2NfJ41cM/JpJCuk7jhwWPTfCS33xtCUyi5EWY61K\nBC/wMbmg3gyiobkUxRSQlHWPsOYIiS0JyzFrgv8y65Sz2rBz0wJubiMjcnG3sXOt\nJuTVBCIoqtGgJK7gzVTbT9OiOKYq6iyn/5bHlzZLOgtN+hnOyB12kwvzO88qNWGf\ny6DfuZ74nQPENAyvuU4G6z0ejusQ2k0gApu1ktsCAwEAAaM4MDYwDAYDVR0TAQH/\nBAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ\nKoZIhvcNAQEFBQADggEBAH3vaupHPOpbWXfiHryCQn62M6rejNcM9epH3llB5fps\n2PERX/tKeOX6H5cfmVTcaX5wfOtOOlC0GpI4gG/LlGjfcH/oWfKAmPxxqFoPta0a\nZBXch7NO8BhmbqhctXMUnondmo2fY/5wv+Z45jn6y53XiNfccREd97POxlHv9S8R\nbfCjN6oI5k1pdop7SsTD9CP2mK1YvdPBlF27r8gmEAT90dlfnKpMlbV6GXKvfVq4\nrwHyECVi5A+a3/bnhdrW9hW8ArjSCKH/npyeIoBprcvZ/g7k8+kNbllbKAElITLU\nn1HxqQFxlfYzPdtJTDPdBp5Epl1QaTb/5nITie7cjLc=\n-----END CERTIFICATE-----\n",
        'cors.allowedOrigins' => '*',
        'cors.allowHeaders' => 'X-Authorization'
    ]);`


I am testing using Postman, login with a user using rest api, then use the idToken for Authorization of the api,php (bearer token).

Not sure what is wrong with my process. Can you help me? Thanks.

**Comment by NorthFred** [comment]
@leossmith Your config part is correctly formatted, couldn't find any issues in that. One thing to double-check is whether you are using the correct 'kid' key?

Btw, I improved my own code to automatically fetch the kids from the secrets URL, so you don't have to maintain it in the `api.php` file (the keys change regularly). This is how I did it:

First fetch the public keys and format them to string:
```
$rawPublicKeys = file_get_contents('https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com');
    $keys = json_decode($rawPublicKeys, true);
    $keyKidsArray= array_keys($keys);
    $pKeysArray = array_values($keys);
    $secrets = $keyKidsArray[0] . ':' . $pKeysArray[0] . ',' . $keyKidsArray[1] . ':' . $pKeysArray[1];
```
and then use them here:
```
'jwtAuth.secrets' => $secrets,
```

**Comment by NorthFred** [comment]
One more note: your error code points at a "1011 - Authentication required", whereis the original problem I faced was a "1012 - Authentication failed".

So it seems the back-end functions ok, but there are issues with the login / headers in the request?

**Comment by leossmith** [comment]
I think there is something wrong in the jwt. When I try the token in jwt.io, although i get the correct info, it says Signature invalid. 

Concerning the 'kid' key, I get 2 keys. One has the same kid as seen in jwt.io and the other is random.

Can you suggest a way to check the login / headers to see if there is an issue?

**Comment by NorthFred** [comment]
Could you verify that the token you use is not truncated (cut off)? How did you get the token? (e.g. console may print out only x characters).

**Comment by leossmith** [comment]
Ok, so it looks like it works in the vanilla.html and vanilla-success.html, but it didn't work for postman.

After some research, I removed the Authentication and changed it to X-Authorization and it looks like it works now. I think a postman guide would also be useful.

**Comment by ndee85** [comment]
> $rawPublicKeys = file_get_contents('https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com');
> $keys = json_decode($rawPublicKeys, true);
> $keyKidsArray= array_keys($keys);
> $pKeysArray = array_values($keys);
> $secrets = $keyKidsArray[0] . ':' . $pKeysArray[0] . ',' . $keyKidsArray[1] . ':' . $pKeysArray[1];

Hi @NorthFred 
I am interested in your solution to dynamically fetch the kid keys. Where did you put your custom code? I noticed that too, that the kid changes on a regular basis, corrupting the login.

**Comment by leossmith** [comment]
This one is in my api.php, at the bottom:

![image](https://user-images.githubusercontent.com/4300876/101823704-d9e58280-3b33-11eb-8f0e-54e993c62133.png)

**Comment by niyonx** [comment]
Hey @leossmith , does getting the public keys every time poses some issue? The public key refreshes very often so the jwt becomes invalid every minute

**Comment by leossmith** [comment]
I have been using the above method for 2 years now without any issues, so it should be ok to use.
