### ISSUE TITLE
VueJS / Axios: basicAuth runs into Access-Control-Allow-Origin problem

### ISSUE THREAD

**Issue by Rasenkantenstein** [mevdschee/php-crud-api#608]
I have set up a basic authentication. I used the "Advanced REST Client" to test the authorization header. It worked fine. However, when trying to connect with axios, I get the following error:

> Access to XMLHttpRequest at 'http://url.com/api/getsomething' from origin 'http://192.168.1.100:8080' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

But when I completely remove the basicAuth middleware, the record object is passed through.

I use the following middlewares with default values: `'middlewares' => 'cors,basicAuth'`

The axios call works like this:
```
const api = axios.create({
  headers: {
     Authorization: "Basic base64encodedusernameandpassword"
  }
}
)

//something else

mounted() {
    api
      .get(
        "http://url.com/api/getsomething"
      )
      .then(response => console.log(response.data))
      .catch(error => console.log(error));
  }

```

**Comment by NorthFred** [comment]
I had a similar issue when authenticating via Google Firebase, and it helped by adding these lines to the configuration (just replace your header with 'Authorization'):

```
        'cors.allowedOrigins' => '*',
        'cors.allowHeaders' => 'X-Authorization'
```

**Comment by mevdschee** [comment]
or:

        'cors.allowHeaders' => 'Authorization'

as it seems that is what it complains about.

**Comment by Rasenkantenstein** [comment]
Now, that was easy. Thank you guys!
