### ISSUE TITLE
Question: Extend query with custom condition

### ISSUE THREAD

**Issue by nthiebes** [mevdschee/php-crud-api#61]
First of all: Thank you for providing this wonderful api file! It is really useful :).

I'm looking for a way to extend every query by a custom condition, for example:
`AND user = '$userId'`

I don't want to expose the userID to the dev/user, so I want to avoid using a filter for this:
`GET http://localhost/api.php/categories?filter=user,eq,1234`

Is there a nice way to do this? Right now I'm using the "tenancy_function" (btw. it's called tenant_function in the readme) to add a userId to my user column.

**Comment by mevdschee** [comment]
Thank you for reporting the documentation problem, I fixed it. 

You are using the "tenancy_function" the way it was meant to be used.

If you have further questions, please let me know.

**Comment by nthiebes** [comment]
Okay, thanks, good to know. The thing is that I don't want to have the userId in the response. "column_authorizer" will prevent this but the response then includes the categories of all users and the "tenancy_function" function doesn't have an effect anymore.

**Comment by mevdschee** [comment]
Did this help you?

**Comment by nthiebes** [comment]
It did! Thanks for updating it.
