### ISSUE TITLE
dbAuth not working

### ISSUE THREAD

**Issue by escoffie** [mevdschee/php-crud-api#610]
Hello Maurits,

I'm trying to make use of dbAuth, but I'm getting a 1012 code in the response, no matter what I do.

So far, this is what I got:

In api.php:

```
    $config = new Config([
        'username' => 'root',
        'password' => '',
        'database' => 'somedb',
        'middlewares' => 'dbAuth',
    ]);
```

My DB structure implies a 'users' table with a 'username' and a 'password' fields, both as varchars.
I also have a user 'test' with password '$2y$10$PYebk9v7i5lgxHDMZzuEveYAYkPnZaU6/MkJryMjgoA/tjfabRrSC' and I'm using Postman to send a POST request to /login with the following body:

```
{
	"username": "test",
	"password": "$2y$10$PYebk9v7i5lgxHDMZzuEveYAYkPnZaU6/MkJryMjgoA/tjfabRrSC"
}
```

I created the user by sending a POST request with the exact same body to /records/users

Can you help me find out what's wrong?

Thank you in advance.

**Comment by lcuis** [comment]
Hello @escoffie ,

It looks like you used the password hash to authenticate in Postman. I believe you should use the password that was used to generate the hash in clear instead. Something like this:
```
{
	"username": "test",
	"password": "password"
}
```

**Comment by escoffie** [comment]
Hello @lcuis 
Thank you very much. That is correct, and it worked.
I was sure I tried that, but obviously, I didn't.
Case closed!

**Comment by mevdschee** [comment]
@lcuis: Thank you for helping @escoffie, appreciated!

**Comment by lcuis** [comment]
I'm glad it worked and helped. Thanks @mevdschee .
