### ISSUE TITLE
General error: 1615 Prepared statement needs to be re-prepared

### ISSUE THREAD

**Issue by fcontrerasz** [mevdschee/php-crud-api#611]
Hi, 

Im Laravel 5.8 and when I call a view I get error: 9999

Example: 

![image](https://user-images.githubusercontent.com/6060664/72156988-9ae40580-3395-11ea-9b11-ce88acd16fe2.png)

Inside the Log about request... it show:

![image](https://user-images.githubusercontent.com/6060664/72156868-4fc9f280-3395-11ea-91b1-c404f30c691c.png)

**Comment by mevdschee** [comment]
This is a possibility: [MySQL bug #42041][1]

They suggest upping the value of [`table_definition_cache`][3].

You can read about re-preparation [in the MySQL docs][2].


  [1]: https://bugs.mysql.com/bug.php?id=42041
  [2]: https://dev.mysql.com/doc/refman/5.5/en/statement-repreparation.html
  [3]: https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_table_definition_cache

from: https://stackoverflow.com/questions/4380813/how-to-get-rid-of-mysql-error-prepared-statement-needs-to-be-re-prepared/4381155#4381155

**Comment by mevdschee** [comment]
Suggestion of forgotten deallocation here:

https://stackoverflow.com/questions/29480915/mysql-view-prepared-statement-and-prepared-statement-needs-to-be-re-prepar

**Comment by mevdschee** [comment]
It seems that either:

    SET GLOBAL table_definition_cache = 1024 

or:

    \PDO::ATTR_EMULATE_PREPARES => true

would help. Did it?

**Comment by mevdschee** [comment]
any updates?

**Comment by fcontrerasz** [comment]
Sorry for late reply .. finally was about table_definition_cache.. I increase and fixed. Thks for all , regards.

**Comment by mevdschee** [comment]
Heads up that this is now the default in v2.10.1 onwards, so no need to change anything anymore, see also #759
