### ISSUE TITLE
sanitation handler & password_hash

### ISSUE THREAD

**Issue by haroldyangyao** [mevdschee/php-crud-api#612]
Hi, my purpose is to leverage the sanitation handler to have 'password' column in 'users' table  hashed, so I put following callback into config, but this callback hashed all the columns in users table when I insert an user through API, so, what should I supposed to do?, thanks
 
 'sanitation.handler'=>function($operation,$tableName,$column,$value)
{ return ($tableName == 'users' && $column == 'password')?null:password_hash($value,PASSWORD_DEFAULT); },

**Comment by lcuis** [comment]
Hello @haroldyangyao ,
I didn't try this yet but playing with your lines around, I believe that the following should work:
```
'sanitation.handler' => function ($operation, $tableName, $column, $value) {
                return ($tableName == 'users' && $column == 'password')?password_hash($value,PASSWORD_DEFAULT):$value;
            },
```
Is there a way to prevent a user from updating the password of another user?
Do you think that the following untested recordHandler would do the job?
```
'authorization.recordHandler' => function ($operation, $tableName) {
                if($tableName == 'users' && $operation == 'update'){
                                return('filter=id,eq,'.$_SESSION['user']['id'].);
                }
                return('');
},
```
This is assuming that your users table has an id column named `id`.
Or maybe something more radical like this could be even better?
```
'authorization.recordHandler' => function ($operation, $tableName) {
                if($tableName == 'users' && $operation != 'create')
                    return('filter=id,eq,'.$_SESSION['user']['id']);
                return('');
},
```

**Comment by haroldyangyao** [comment]
thanks, but unfortunately, the new sanitation callback will leave all columns unhashed, seems that "$column" doesn't work at all, weird

**Comment by lcuis** [comment]
Hello @haroldyangyao ,

Thanks for testing this.

Indeed, the `$column` is in fact an array with more information thank just the name.
The column name can be reached as `$column['name']`.
So, for you, this should be working:
```
'sanitation.handler' => function ($operation, $tableName, $column, $value) {
                return ($tableName == 'users' && $column['name'] == 'password')?password_hash($value,PASSWORD_DEFAULT):$value;
            },
```

I tried your approach on a test implementation and I found one drawback that I could not overcome for now, how to invalidate the session after a password or username update to force the user to log in again?

Here is my table:
```
CREATE TABLE users (
  id int(10) UNSIGNED NOT NULL,
  created timestamp NOT NULL DEFAULT current_timestamp(),
  username varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  password varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE users
  ADD PRIMARY KEY (id),
  ADD UNIQUE KEY username (username);

ALTER TABLE users
  MODIFY id int(10) UNSIGNED NOT NULL AUTO_INCREMENT;
```

Here is my configuration that prevents the update of a password by another user:
```
    function testlog($message){
        $error=false;
        $message=date('Y-m-d H:i:s')."[T]: ".$message."\n";
        $handle = fopen("/tmp/php-crud-api-logs.txt", 'a') or $error=true;
        if($error){
            echo("cannot write logs: ".$message);
            return(false);
        }
        fwrite($handle, $message);
        fclose($handle);
    }
   
    $config = new Config([
        'username' => 'phpcrudapitests',
        'password' => 'hehehe :0',
        'database' => 'phpcrudapitests',
        'tables' => 'users',
        'debug' => 'true',
        'middlewares' => 'dbAuth,authorization,sanitation',
        'authorization.tableHandler' => function ($operation, $tableName) {
            $tablesPermissions=array(
                "users" => "lcrudi",
            );
            if(!array_key_exists($tableName,$tablesPermissions)){
                return(false);
            }
            $op=$operation[0];
            $ret=strpos($tablesPermissions[$tableName],$op)!==false;
            if(!$ret)testlog("failed permission for operation: ".$operation." table: ".$tableName);
            return($ret);
        },
            'authorization.columnHandler' => function ($operation, $tableName, $columnName) {
                $colsPermissions=array(
                    "users" => array(
                        "id" => "lcru",
                        "created" => "lru",
                        "username" => "lcru",
                        "password" => "cu",
                    ),
                );
                if(!array_key_exists($tableName,$colsPermissions)){
                    testlog("!array_key_exists(tableName,colsPermissions): ".$operation." table: ".$tableName." column: ".$columnName);
                    return(false);
                }
                if(!array_key_exists($columnName,$colsPermissions[$tableName])){
                    testlog("!array_key_exists(columnName,colsPermissions[tableName]): ".$operation." table: ".$tableName." column: ".$columnName);
                    return(false);
                }
                $op=$operation[0];
                $ret=strpos($colsPermissions[$tableName][$columnName],$op)!==false;
                if(!$ret)testlog("failed permission for operation: ".$operation." table: ".$tableName." column: ".$columnName);
                return($ret);
            },
            'authorization.recordHandler' => function ($operation, $tableName) {
                if(array_key_exists('user',$_SESSION)&&array_key_exists('id',$_SESSION['user']))
                    $userid=$_SESSION['user']['id'];
                else{
                    $userid=null;
                    testlog("anonymous");
                }
                if($tableName == 'users'){
                    if(is_null($userid)&&$operation!='create'){
                        testlog("anonymous user can only create in the users table");
                        return('filter=id,eq,-1');
                    }
                    switch($operation){
                        case 'create':
                            return('');
                            break;
                        case 'list':
                            return('filter=id,eq,'.$userid);
                            break;
                        case 'read':
                            return('filter=id,eq,'.$userid);
                            break;
                        case 'update':
                            return('filter=id,eq,'.$userid);
                            break;
                        case 'delete':
                            return('filter=id,eq,'.$userid);
                            break;
                        default:
                            testlog("unexpected operation requested on ".$tableName.", operation: ".$operation.", user id:".$userid);
                            return('filter=id,eq,-1');
                            break;
                    }
                }
                testlog("unexpected table in authorization.recordHandler: ".$tableName.", operation: ".$operation.", user id:".$userid);
                return('');
            },
            'dbAuth.mode' => 'anonymous',
            'dbAuth.usersTable' => 'users',
            'dbAuth.usernameColumn' => 'username',
            'dbAuth.passwordColumn' => 'password',
            'dbAuth.returnedColumns' => 'id,created,username',
            'sanitation.handler' => function ($operation, $tableName, $column, $value) {
                if($tableName == 'users' && $column['name'] == 'password')
                    return(password_hash($value,PASSWORD_DEFAULT));
                return is_string($value) ? strip_tags($value) : $value;
            },
    ]);
    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    ResponseUtils::output($response);
```
Hello @mevdschee , do you think there could be an easy way to force the user to log in again after a  username or password update?
Also, do you see any security concerns with this approach? For example, is the `$_SESSION['user']['id']` reliable or can it be faked somehow?

**Comment by haroldyangyao** [comment]
yes! password_hash works, awesome, I should have known that after $column->serialize(), the $column will be returned as ['name' => $this->name, 'type' => $this->type, 'length' => $this->length,'precision' => $this->precision, 'scale' => $this->scale, 'nullable' => $this->nullable,'pk' => $this->pk, 'fk' => $this->fk,], so have to use $column['name'] in callback, thanks
as to the drawback part, very like to wait for @mevdschee's comments

**Comment by lcuis** [comment]
I'm glad it worked for you @haroldyangyao !
Thanks for the feedback!

**Comment by lcuis** [comment]
My tests are working with the following configuration:
```
// file: src/index.php
namespace Tqdev\PhpCrudApi {

    use Tqdev\PhpCrudApi\Api;
    use Tqdev\PhpCrudApi\Config;
    use Tqdev\PhpCrudApi\RequestFactory;
    use Tqdev\PhpCrudApi\ResponseUtils;

    function testlog($message){
        $error=false;
        $message=date('Y-m-d H:i:s')."[T]: ".$message."\n";
        $handle = fopen("/tmp/php-crud-api-logs.txt", 'a') or $error=true;
        if($error){
            echo("cannot write logs: ".$message);
            return(false);
        }
        fwrite($handle, $message);
        fclose($handle);
    }
    $sessionToReset=false;
    $config = new Config([
        'username' => 'autocrudtests',
        'password' => 'd3csF2R9cnW4',
        'database' => 'autocrudtests',
        'tables' => 'users',
        'debug' => 'true',
        'middlewares' => 'dbAuth,authorization,sanitation,validation',
        'authorization.tableHandler' => function ($operation, $tableName) {
            // GET    /records/{table}      - list      - lists records
            // POST   /records/{table}      - create    - creates records
            // GET    /records/{table}/{id} - read      - reads a record by primary key
            // PUT    /records/{table}/{id} - update    - updates columns of a record by primary key
            // DELETE /records/{table}/{id} - delete    - deletes a record by primary key
            // PATCH  /records/{table}/{id} - increment - increments columns of a record by primary key
            $tablesPermissions=array(
                "users" => "lcrudi",
            );
            if(!array_key_exists($tableName,$tablesPermissions)){
                return(false);
            }
            $op=$operation[0];
            $ret=strpos($tablesPermissions[$tableName],$op)!==false;
            if(!$ret)testlog("failed permission for operation: ".$operation." table: ".$tableName);
            return($ret);
        },
            'authorization.columnHandler' => function ($operation, $tableName, $columnName) {
                global $sessionToReset;
                $colsPermissions=array(
                    "users" => array(
                        "id" => "lcru",
                        "created" => "lru",
                        "username" => "lcru",
                        "password" => "cu",
                    ),
                );
                if(!array_key_exists($tableName,$colsPermissions)){
                    testlog("!array_key_exists(tableName,colsPermissions): ".$operation." table: ".$tableName." column: ".$columnName);
                    return(false);
                }
                if(!array_key_exists($columnName,$colsPermissions[$tableName])){
                    testlog("!array_key_exists(columnName,colsPermissions[tableName]): ".$operation." table: ".$tableName." column: ".$columnName);
                    return(false);
                }
                $op=$operation[0];
                $ret=strpos($colsPermissions[$tableName][$columnName],$op)!==false;
                if(!$ret)testlog("failed permission for operation: ".$operation." table: ".$tableName." column: ".$columnName);
                if($ret&&$tableName=="users"&&$operation=="update"&&($columnName=="username"||$columnName=="password")){
                    $sessionToReset=true;
                }
                return($ret);
            },
            'authorization.recordHandler' => function ($operation, $tableName) {
                if(array_key_exists('user',$_SESSION)&&array_key_exists('id',$_SESSION['user']))
                    $userid=$_SESSION['user']['id'];
                else{
                    $userid=null;
                    testlog("anonymous");
                }
                if($tableName == 'users'){
                    if(is_null($userid)&&$operation!='create'){
                        testlog("anonymous user can only create in the users table");
                        return('filter=id,eq,-1');
                    }
                    switch($operation){
                        case 'create':
                            return('');
                            break;
                        case 'list':
                            return('filter=id,eq,'.$userid);
                            break;
                        case 'read':
                            return('filter=id,eq,'.$userid);
                            break;
                        case 'update':
                            return('filter=id,eq,'.$userid);
                            break;
                        case 'delete':
                            return('filter=id,eq,'.$userid);
                            break;
                        default:
                            testlog("unexpected operation requested on ".$tableName.", operation: ".$operation.", user id:".$userid);
                            return('filter=id,eq,-1');
                            break;
                    }
                }
                testlog("unexpected table in authorization.recordHandler: ".$tableName.", operation: ".$operation.", user id:".$userid);
                return('');
            },
            'validation.handler' => function ($operation, $tableName, $column, $value, $context) {
                switch($column['type']){
                    case 'integer':
                        if(!is_numeric($value))
                            return('must be numeric');
                        if(strlen($value)>20)
                            return('exceeds range');
                    break;
                    case 'bigint':
                        if(!is_numeric($value))
                            return('must be numeric');
                        if(strlen($value)>20)
                            return('exceeds range');
                    break;
                    case 'varchar':
                        if(strlen($value)>$column['length'])
                            return('too long');
                        if(!mb_check_encoding($value))
                            return('wrong encoding');
                    break;
                    case 'decimal':
                        if(!is_float($value)&&!is_numeric($value))
                            return('not a float');
                    break;
                    case 'float':
                        if(!is_float($value)&&!is_numeric($value))
                            return('not a float');
                    break;
                    case 'double':
                        if(!is_float($value)&&!is_numeric($value))
                            return('not a float');
                    break;
                    case 'boolean':
                        if($value!=0&&$value!=1)
                            return('not a valid boolean');
                    break;
                    case 'date':
                        $date_array=explode('-',$value);
                        if(count($date_array)!=3)
                            return('invalid date format use yyyy-mm-dd');
                        if(!checkdate($date_array[1], $date_array[2], $date_array[0]))
                            return('not a valid date');
                    break;
                    case 'time':
                        $time_array=explode(':',$value);
                        if(count($time_array)!=3)
                            return('invalid time format use hh:mm:ss');
                        foreach($time_array as $t)
                            if(!is_numeric($t))
                                return('non-numeric time value');
                        if($time_array[1]<0||$time_array[2]<0||$time_array[0]<-838||$time_array[1]>59||$time_array[2]>59||$time_array[0]>838)
                            return('not a valid time');
                    break;
                    case 'timestamp':
                        $split_timestamp=explode(' ',$value);
                        if(count($split_timestamp)!=2)
                            return('invalid timestamp format user yyyy-mm-dd hh:mm:ss');
                        $date_array=explode('-',$split_timestamp[0]);
                        if(count($date_array)!=3)
                            return('invalid date format use yyyy-mm-dd');
                        if(!checkdate($date_array[1], $date_array[2], $date_array[0]))
                            return('not a valid date');
                        $time_array=explode(':',$split_timestamp[1]);
                        if(count($time_array)!=3)
                            return('invalid time format use hh:mm:ss');
                        foreach($time_array as $t)
                            if(!is_numeric($t))
                                return('non-numeric time value');
                        if($time_array[1]<0||$time_array[2]<0||$time_array[0]<0||$time_array[1]>59||$time_array[2]>59||$time_array[0]>23)
                            return('not a valid time');
                    break;
                    case 'clob':
                        if(!mb_check_encoding($value))
                            return('wrong encoding');
                    break;
                    case 'blob':
                        if(!mb_check_encoding($value))
                            return('wrong encoding');
                    break;
                    case 'varbinary':
                        if(((strlen($value) * 3 / 4) - substr_count(substr($value, -2), '='))>$column['length'])
                            return('too long');
                        if(!mb_check_encoding($value))
                            return('wrong encoding');
                    break;
                    case 'geometry':
                        if(!mb_check_encoding($value))
                            return('wrong encoding');
                    break;
                    default:
                        testlog("unknown type: ".$column['type']);
                    break;
                }
                return(true);
            },
            'dbAuth.mode' => 'anonymous',//'required',
            'dbAuth.usersTable' => 'users',
            'dbAuth.usernameColumn' => 'username',
            'dbAuth.passwordColumn' => 'password',
            'dbAuth.returnedColumns' => 'id,created,username',
            'sanitation.handler' => function ($operation, $tableName, $column, $value) {
                if($tableName == 'users' && $column['name'] == 'password')
                    return(password_hash($value,PASSWORD_DEFAULT));
                return is_string($value) ? strip_tags($value) : $value;
            },
    ]);
    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    if($sessionToReset){
        $c=$response->getBody()->getContents();
        if(isset($c)&&ctype_digit($c)&&intval($c)>0){
            testlog("destroying session after update to username or password");
            session_destroy();
        }
        $response->getBody()->rewind();
    }
    ResponseUtils::output($response);
}
```
I make use of `session_destroy()` to invalidate the current session in case of password or username update requested and if at least one row was updated.
I am wondering whether an error message could be sent instead of the -1 filter when an anonymous user tries to do something else than a creation on the `users` table.

**Comment by haroldyangyao** [comment]
pls correct me if I am wrong, I am quite new on this wonderful API also quite new on coding....but when I do the testing today, I found several things:

1. after logged in, I couldn't access other tables through API, it is said "1001 table xxx not found"

2. for record handler, if we suppose there is a user_id column in all the tables(not include 'users' table), then I thought it would be great if we could apply "user_id" filter, thus, when the logged in user call other API, all the records will be automatically under his ID. suppose multi-tenancy could do the same job, but perception wide, multi-tenancy means multi customer_id + multi user_id, so if record handler could do the "multi user" job, it would a "not bad" option

3. so I updated the configuration a little bit, but there is a drawback I couldn't overcome, when the $operation is 'create' (insert a row), user_id in the target table cannot be set to logged in user's $userid automatically

4. I didn't test the $sessionToReset part but it looks right

here is the updated tableHandler, columnHandler & recordHandler's configuration 

`

        'authorization.tableHandler' => function ($operation, $tableName) {
            // GET    /records/{table}      - list      - lists records
            // POST   /records/{table}      - create    - creates records
            // GET    /records/{table}/{id} - read      - reads a record by primary key
            // PUT    /records/{table}/{id} - update    - updates columns of a record by primary key
            // DELETE /records/{table}/{id} - delete    - deletes a record by primary key
            // PATCH  /records/{table}/{id} - increment - increments columns of a record by primary key

            $tablesPermissions=array(
                "users" => "lcrudi",
            );
            if(!array_key_exists($tableName,$tablesPermissions)){
                return(true);
            }
            $op=$operation[0];
            $ret=(strpos($tablesPermissions[$tableName],$op)!==0);
            if(!$ret)testlog("failed permission for operation: ".$operation." table: ".$tableName);
            return($ret);
        },
            'authorization.columnHandler' => function ($operation, $tableName, $columnName) {
                global $sessionToReset;
                $colsPermissions=array(
                    "users" => array(
                        "id" => "lcru",
                        "created" => "lru",
                        "username" => "lcru",
                        "password" => "cu",
                    ),
                );
                if(!array_key_exists($tableName,$colsPermissions)){
                    testlog("!array_key_exists(tableName,colsPermissions): ".$operation." table: ".$tableName." column: ".$columnName);
                    return(true);
                }
                if(!array_key_exists($columnName,$colsPermissions[$tableName])){
                    testlog("!array_key_exists(columnName,colsPermissions[tableName]): ".$operation." table: ".$tableName." column: ".$columnName);
                    return(true);
                }
                $op=$operation[0];
                $ret=(strpos($colsPermissions[$tableName][$columnName],$op)!==0);
                if(!$ret)testlog("failed permission for operation: ".$operation." table: ".$tableName." column: ".$columnName);
                if($ret&&$tableName=="users"&&$operation=="update"&&($columnName=="username"||$columnName=="password")){
                    $sessionToReset=true;
                }
                return($ret);
            },
            'authorization.recordHandler' => function ($operation, $tableName) {
                if(array_key_exists('user',$_SESSION) && array_key_exists('id',$_SESSION['user']))
                    $userid=$_SESSION['user']['id'];
                else{
                    $userid=null;
                    testlog("anonymous");
                }
                if($tableName == 'users'){
                    if(is_null($userid)&&$operation!='create'){
                        testlog("anonymous user can only create in the users table");
                        return('filter=id,eq,-1');
                    }
                    switch($operation){
                        case 'create':
                            return('');
                            break;
                        case 'list':
                            return('filter=id,eq,'.$userid);
                            break;
                        case 'read':
                            return('filter=id,eq,'.$userid);
                            break;
                        case 'update':
                            return('filter=id,eq,'.$userid);
                            break;
                        case 'delete':
                            return('filter=id,eq,'.$userid);
                            break;
                        default:
                            testlog("unexpected operation requested on ".$tableName.", operation: ".$operation.", user id:".$userid);
                            return('filter=id,eq,-1');
                            break;
                    }
                } else {
                    if(is_null($userid)) {return '';}
                    switch($operation){ //if a table other than 'users' could have user_id column, then records under $userid will be filted automatically
                        case 'create':
                            return(''); //couldn't figure out how to set user_id = $userid automatically
                            break;
                        case 'list':
                            return('filter=user_id,eq,'.$userid);
                            break;
                        case 'read':
                            return('filter=user_id,eq,'.$userid);
                            break;
                        case 'update':
                            return('filter=user_id,eq,'.$userid);
                            break;
                        case 'delete':
                            return('filter=user_id,eq,'.$userid);
                            break;
                        default:
                            testlog("unexpected operation requested on ".$tableName.", operation: ".$operation.", user id:".$userid);
                            return('filter=id,eq,-1');
                            break;
                    }
                }
                testlog("unexpected table in authorization.recordHandler: ".$tableName.", operation: ".$operation.", user id:".$userid);
                return('');
            },
`

**Comment by lcuis** [comment]
Hello @haroldyangyao ,

Thanks for the conversation.

1. With this example configuration, if you'd like to add a table named "newtable" with for example columns "id", "name" and "user_id", you would have to either remove the constraints from the configuration (but this would be less secure: no more `'tables' => 'users',` and return true when the table is not found in the tableHandler, columnHandler and recordHandler) or you could add the following newtable configuration elements:
```
//...
        $tablesPermissions=array(
            "users" => "lcrudi",
            "newtable" => "lcrudi",//adds newtable for "list", "create", "read", "update", "delete", "increment"
        );
//...
$colsPermissions=array(
                "users" => array(
                    "id" => "lcru",
                    "created" => "lru",
                    "username" => "lcru",
                    "password" => "cu",
                ),
                "newtable" => array(//adds all permissions for 3 columns of newtable
                    "id" => "lcrudi",
                    "name" => "lcrudi",
                    "user_id" => "lcrudi",
                ),
            );
//...
```

2 I also use the user_id principle in my configuration and tables. The risk for me is in case the `$_SESSION['user']['id']` can be faked.

3. It seems hard for me to automatically log in a user that was just created without modifying non-configuration `php-crud-api` code. Indeed, the POST /login is handled in the DbAuthMiddleware::process method. Maybe we could create a new ServerRequestInterface for this call? I don't know this code enough, sorry.

4. Thanks.

**Comment by haroldyangyao** [comment]
I misunderstood your configuration previously, now I get it, the philosophy is: by default,  no table & columns could be accessed, unless you put them into $tablePermission & $colsPermission with explicit permissions assigned, also permissions for every table and every column could be down to "lcrudi" level by this configuration, which is awesome, thanks

**Comment by lcuis** [comment]
Yes, you got it indeed, thank you very much @haroldyangyao !
