### ISSUE TITLE
Advice Needed - Restricting READ by username matched to field in every table - best way to do this?

### ISSUE THREAD

**Issue by Fever905** [mevdschee/php-crud-api#617]
Hey this isn't an issue but I'm looking for customization advice - or maybe there is a way to do this without modifying the base code?

I'm looking to base the GET/READ requests on all tables based on a column in that matches the authenticated user's username.

For example we have a field called LAB_CODE which contains the user's ID. When a GET is performed we want to only return results that match the user ID of the system making the request. Basically it's like a preset hidden filter.

Is this possible to implement and can you give me a high level idea of where I should start to implement this? I am an experienced programmer so I just need some basic advice on how you would do something like this.

What I'm looking at now is modifying selectSingle and selectMultiple and adding "AND LAB_CODE LIKE $_SESSION['username']"

Would you think this is the best way to achieve this or is there another way to accomplish this?

Thank you so much in advance.

Michael DeMutis / Fever905

**Comment by lcuis** [comment]
Hello @Fever905 ,

There are examples of configurations in #612 that filter records based on user id without core code modification. However, from a security standpoint, I cannot affirm with full confidence whether or not the session user id is reliable or not. Can a user somehow pretend to hold another user id than his? So, far, I didn't see how.

**Comment by Fever905** [comment]
Thank you - we are just exchanging oil analysis result data between our labs.  Oil analysis results from industrial machines, truck fleets stuff like that. Nothing exciting that any hacker would want so it's really not a huge deal from a security standpoint.  We just wanted to make it easy for our member labs to pull the data that pertains to them.  

I will take a look at #612 now.  Thank you for pointing me in the right direction.  :) :+1:
