### ISSUE TITLE
Add support for "route" as a querystring parameter.

### ISSUE THREAD

**Issue by adrianvoica** [mevdschee/php-crud-api#619]
Could we have the "route" as a (temporary) query string parameter?
Maybe, add a config option "RouteAsQueryStringParameter" or something like that (defaults to false).
When it is set to true, we can specify the route in a "route" query parameter together with any other parameters. 
That parameter will then be used as the REQUEST_URI and be removed from further processing of the query string parameters.

Scenario: I don't want to (or can't) use RewriteRules in .htaccess, but still need that routing functionality. 
I can have a call like: 
    api.php?route=recrods/posts&filter=id,gt,100

Internally, it should be treated the same way as:
    api.php/records/posts?filter=id,gt,100.

Would this require a significant amount of effort to implement?

**Comment by mevdschee** [comment]
> I don't want to (or can't) use RewriteRules in .htaccess, but still need that routing functionality.

You don't need RewriteRules. The default configuration of PHP without .htaccess modification will use everything after ".php" as the "PATH_INFO" variable and this is read by the script. What is not working?

**Comment by adrianvoica** [comment]
Well, the scenario is a bit more complex than that. It's something like this:
- I have a directory that holds 2 files (or more, but for now, let's say there only 2): index.php and api.php;
- I have some .htaccess RewriteRules, because I need to hide the actual calls to the api.php behind some nice URLs, like: myapidomain.com/getActiveUsers or myapidomain.com/logmein (to perform the actual api.php/login), but also, I need to do some other stuff that is not related to api.php, and should not pass through that file;
- The main idea is that I need to hide everything behind a "router" (via .htaccess) and having a route parameter at hand would be a tremendous win for me. Maybe I will try to implement that, but I haven't really touched PHP in a while, only the small stuff like config options and maybe some array manipulation, and I'm fine with that - but if somebody else - that is more connected to the php world -  could do it, that'd be great. 
Otherwise, if you think there's no real value in this (for TreeQL), feel free to close this.
Thanks! Keep up the good work!

**Comment by mevdschee** [comment]
I see what you are trying to do. You want to add some logic around the script. Why don't you give slimphp a try? It allows for a lot of customization and is light weight, see: https://tqdev.com/2019-automatic-api-slimphp-4

**Comment by mevdschee** [comment]
What you want can be achieved by adding this line on top of the file:

    $_SERVER['PATH_INFO'] = $_GET['route'];

I don't recommend such an approach, but it may help you.

**Comment by adrianvoica** [comment]
I think that is exactly what I need, it solves my scenario. Thanks a lot!

**Comment by mevdschee** [comment]
You are welcome, enjoy the software!
