### ISSUE TITLE
error when adding tablehandler

### ISSUE THREAD

**Issue by leembb** [mevdschee/php-crud-api#623]
Hello, ive added the following to my config

            'middlewares' => 'cors,basicAuth,authorization',
            'controllers' => 'records,geojson,openapi',
            'customControllers' => '',
            'customOpenApiBuilders' => '',
            'cacheType' => 'TempFile',
            'cachePath' => '',
            'cacheTime' => 10,
            'debug' => true,
            'basePath' => '',
            'openApiBase' => '{"info":{"title":"PHP-CRUD-API","version":"1.0.0"}}',
	    'authorization.tableHandler' => function ($operation, $tableName) {
				return ($operation == "list" || $operation == "read");
	    },

im getting the a 500 server error, error in the log is:
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Constant expression contains invalid operations

running php 7.4

If i remove the 'authorization.tableHandler' all works fine.

**Comment by leembb** [comment]
solved, user error

**Comment by mevdschee** [comment]
no problem, enjoy the software!
