### ISSUE TITLE
Support multi-database

### ISSUE THREAD

**Issue by hanrobin123** [mevdschee/php-crud-api#624]
Hi Maurits,

Is there a way to use api.h to query data from multi-database.
For example, I have database a, b and c. I want to query data from them. what should I set for "database" as below config?
    $config = new Config([
        'username' => 'root',
        'password' => '1234',
        **'database' => ''**
    ]);

**Comment by mevdschee** [comment]
Simplest way is to install the script multiple times.

**Comment by hanrobin123** [comment]
Hi Maurits,
Thank you for the quick reply.
For the URL scheme, it could looks like http://localhost/api.php/records/schemaName/user/1
Is there a way to configure seetings in api.phh to support this feature?


Thank you,
Robin

**Comment by mevdschee** [comment]
This is not supported, but it is achievable with an Apache "rewriterule" and a get parameter in the config.

**Comment by phillipwilhelm** [comment]
I too am also interested in this. 

Any example would be much appreciated.

**Comment by mevdschee** [comment]
Create a folder for your api using:

    mkdir api

Now go to the folder:

    cd api

Download the api code

    wget https://raw.githubusercontent.com/mevdschee/php-crud-api/master/api.php

Edit the file using:

    nano api.php

Add the following line to the top of the file:

    if (isset($_GET['path'])) $_SERVER['PATH_INFO'] = $_GET['path'];

In your configuration (at the end of the file) set the credentials:

        'username' => 'YourUsername',
        'password' => 'YourPassword',
        'database' => $_GET['db'],

Start your favorite editor to create a file named ".htaccess":

    nano .htaccess

Past the following content:

    <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^([^/]*)(/.*)\??$ api.php?db=$1&path=$2& [QSA,L]
    </IfModule>

If Apache does not have "mod_rewrite" enabled, then enable it using:

    sudo a2enmod rewrite
    sudo apachectl -k graceful

Try it out!

**Comment by mevdschee** [comment]
Another approach (avoiding mod_rewrite) is to add the following to the top of the file:

    if (!preg_match('|^/([^/]*)/([^/]*)/?(.*)|', $_SERVER['PATH_INFO'], $matches)) die('not found');
    $database = $matches[2];
    $_SERVER['PATH_INFO'] = '/'.$matches[1].'/'.$matches[3];

And in the config at the bottom of the file use:

    'username' => 'YourUsername',
    'password' => 'YourPassword',
    'database' => $database,

This achieves exactly what you want:

    http://localhost/api.php/records/schemaName/user/1

Enjoy!

**Comment by phillipwilhelm** [comment]
Thank you!

**Comment by 3257** [comment]
Hey, guys, @phillipwilhelm and @mevdschee, I am a bit late to the party. 
I came across the same issue, so I extended and updated what @mevdschee recommended for multiple databases.

This is what I came up with (I am using the `api.include.php ` file and I have a separate `api.php` file that you see below):


```php
<?php

// Sometimes session has not started yet
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

include './php-crud-api/api.include.php';

use Tqdev\PhpCrudApi\Api;
use Tqdev\PhpCrudApi\Config;
use Tqdev\PhpCrudApi\RequestFactory;
use Tqdev\PhpCrudApi\RequestUtils;
use Tqdev\PhpCrudApi\ResponseUtils;

// Get Request first
$request = RequestFactory::fromGlobals();
// Extract the /api.php part
$apiPathSegment = RequestUtils::getPathSegment($request, 1);
// Extract the path segment declaring the database to use
$databasePathSegment = RequestUtils::getPathSegment($request, 2);

// Set $database for later use in if check below and Config class
$databaseName = $databasePathSegment;

$fullPathForRequest = $request->getUri()->getPath();

// If the full path of the request contains a valid database path segment,
// remove it so that api.include.php handles the request as if it was missing
if ($databaseName != NULL && str_contains($fullPathForRequest, $databasePathSegment)) {
    $newPath = str_replace("/$apiPathSegment/$databasePathSegment", "/$apiPathSegment", $fullPathForRequest);
    $newUri = $request->getUri()->withPath($newPath);
    $request = $request->withUri($newUri, false);
}

$config = new Config([
    'driver' => 'mysql',
    'address' => 'database',
    'port' => '3306',
    'middlewares' => 'cors, authorization, apiKeyAuth',
    'username' => 'root',
    'password' => 'password',
    'database' => $databaseName ?? '',
    'apiKeyAuth.keys' => '02c042aa-c3c2-4d11-9dae-1a6e230ea95e',
    'authorization.tableHandler' => function ($operation, $tableName) {
        // Basic set-up to block all users' access the admin_users table
        return $tableName != 'users';
    },
    'debug' => true
]);

$api = new Api($config);
$response = $api->handle($request);
ResponseUtils::output($response);

```

I hope this helps anyone else that may need it.

**Comment by 3257** [comment]
Still, looks like the `.htaccess` solution is better.
