### ISSUE TITLE
关联查询中支持筛选吗？/ Is filtering supported in correlated queries?

### ISSUE THREAD

**Issue by zhaocaijuan** [mevdschee/php-crud-api#625]
比如 /  such as 

```
posts    comments  users     post_tags  tags
=======  ========  =======   =========  ======= 
id       id        id        id         id
title    post_id   username  post_id    name
content  user_id   phone     tag_id
created  message
```

/records/posts?join=comments,users&join=tags

如何在users中增加条件？/ How to add conditions in users?

**Comment by mevdschee** [comment]
您应该要求相反：带有他们的帖子，标签和评论的用户。/ You should ask for the reverse: users with their posts, tags and comments.

**Comment by zhaocaijuan** [comment]
Thank you.
I have a question, such as:

posts    comments  users     post_tags  tags
=======  ========  =======   =========  ======= 
id       id        id        id         id
title    post_id   username  post_id    name
content  user_id   phone     tag_id
created  message

/records/posts?join=comments,users&join=tags

how to find comments where "message" contains "greet" from posts
（从post开始，如何查询到 message 包含“greet”的comments）

eg:/records/posts?join=comments(filter=message,contains,greet)

**Comment by mevdschee** [comment]
This is not supported as you can only filter on the primary entity. You can search for the reverse structure:

    /records/comments?join=posts&filter=message,cs,greet

I hope this properly explains what is and what is not possible.
