### ISSUE TITLE
 Hello, I am having an error when placing in laravel.

### ISSUE THREAD

**Issue by vitorhugosg** [mevdschee/php-crud-api#626]
Hello all well? first of all thank you for the project, i've been looking for something like this for a long time, i'm starting a project now with laravel, however i tried to put it here in my project, but i was not successful. Can you tell me if I'm going the right way?

```
Route::any('/{any}', function (ServerRequestInterface $request) {
    //configuração da API REST
    $config = new Config([
        'username' => env('DB_USERNAME', 'forge'),
        'password' => env('DB_PASSWORD', ''),
        'database' =>  env('DB_DATABASE', 'forge'),
        'address' => env('DB_HOST', '127.0.0.1'),
        'basePath' => '/api',
    ]);
    $api = new Api($config);
    
    $response = $api->handle($request);
    return $response;
})->where('any', '.*');
```

Here is the answer in the postman:

![image](https://user-images.githubusercontent.com/17458174/77449823-38fe3e00-6dd1-11ea-9c12-32d2377d54ba.png)

Meu banco de dados:

![image](https://user-images.githubusercontent.com/17458174/77449903-529f8580-6dd1-11ea-99e8-0590b9d3e6d1.png)

Thanks very much <3

**Comment by vitorhugosg** [comment]
![image](https://user-images.githubusercontent.com/17458174/77451161-110fda00-6dd3-11ea-9cf6-33247bf12c6f.png)

The mistake was mine, I don't know why, when I put the adress it didn't work. When I want to connect to a bank that is not on localhost, how will I proceed? Thanks in advance.

**Comment by mevdschee** [comment]
Hi, thank you for opening this issue. Replace '127.0.0.1' with the IP address or hostname of your database server. Kind regards, Maurits

**Comment by vitorhugosg** [comment]
thank you very much, resolved I will close here, congratulations on the work, great tool.
