### ISSUE TITLE
[help-resolved] error php crud api cache.

### ISSUE THREAD

**Issue by vitorhugosg** [mevdschee/php-crud-api#628]
Hello, how are you?

I'm using your lib and I'm
finding it simply spectacular.

However, I went up for approval, went up to the server, installed the project on the server, but returned an error

![image](https://user-images.githubusercontent.com/17458174/77836518-91b53a00-7135-11ea-9093-fc77ef057fab.png)

I would like to know how to proceed, I tried to find some things here I didn't find, thanks in advance.

**Comment by mevdschee** [comment]
Hi Vitor,

I think you did not specify the 'cachePath' in the config and now it defaults to the system path to which writing is not allowed by an open basedir restriction. To resolve this problem create a folder in which you can write and set the 'cachePath' variable in the config.

Kind regards, 

Maurits

**Comment by vitorhugosg** [comment]
very thanks for info, i solved with:

![image](https://user-images.githubusercontent.com/17458174/77836912-6cc2c600-7139-11ea-814f-0dcf28218f81.png)



but I will do that, that you said it will be better

**Comment by mevdschee** [comment]
Glad you solved it. Be sure to tune the cache parameters for production use. Enjoy the software!
