### ISSUE TITLE
Change json output

### ISSUE THREAD

**Issue by seljo-ch** [mevdschee/php-crud-api#629]
Hi there 

First of all many thanks for the brilliant project! How is it possible to rename the json object "records"? In cooperation with jQuery DataTables, json data cannot be read from objects named "records".

Is there a way to adjust the json output so that it no longer displays "records" but an individual name?

Or is there a possibility to omit the entry "records"? I already tried it with "transform=1" (from another entry) but without success.

Thanks and Regards

seljo-ch

**Comment by mevdschee** [comment]
Thank you for filing this issue. Try:

    $('#example').dataTable( {
    "ajax": {
        "url": "api.php",
        "dataSrc": "records"
    }
    } );

see: https://datatables.net/reference/option/ajax.dataSrc#Examples

**Comment by seljo-ch** [comment]
Unfortunately, that is exactly what does not work. With every other keyword it works, only with "records" there are problems. I have tried everything.

**Comment by mevdschee** [comment]
>I have tried everything

Okay.. did you try this?

    "dataSrc": function(json) { console.log(json); return json.records; },

Do you see the contents in the javascript console? Is it a string/object/array?

**Comment by seljo-ch** [comment]
Many thanks for your support. I haven't tried that yet. However, I have come to the same conclusion.

An array output is displayed in the console. The same happens if I take one of the examples from DataTables and adjust the json element to "records". 

It will show the total of the existing elements, but not the single elements. As soon as the json element has a different name, for example DATA or, Example, everything works fine. 

Here for better understanding, my Json output from my API, as an example:

`{"records":[{"id":8,"ean":"dfasdfasdfasdf","year":2020,"month":3,"day":20,"qrdata":"555555","qrurl":"http:\/\/api?data=HelloWorld!&size=100x100","DateTime":"2020-03-24 20:59:24"},{"id":9,"ean":"dfasdfasdfasdf","year":2020,"month":3,"day":20,"qrdata":"5648789978978979887","qrurl":"http:\/\/api?data=HelloWorld!&size=100x100","DateTime":"2020-03-24 20:59:46"},{"id":10,"ean":"7879879877989","year":2020,"month":3,"day":20,"qrdata":"5648789978978979887","qrurl":"http:\/\/api?data=HelloWorld!&size=100x100","DateTime":"2020-03-24 20:59:55"},{"id":11,"ean":"7879879877989","year":2020,"month":3,"day":20,"qrdata":"5648789978978979887","qrurl":"http:\/\/api?data=HelloWorld!&size=100x100","DateTime":"2020-03-24 21:00:11"},{"id":12,"ean":"7879879877989","year":2020,"month":3,"day":20,"qrdata":"5648789978978979887","qrurl":"http:\/\/api?data=HelloWorld!&size=100x100","DateTime":"2020-03-24 21:00:23"},{"id":14,"ean":"7879879877989","year":2020,"month":12,"day":31,"qrdata":"5648789978978979887","qrurl":"http:\/\/api?data=Hesize=100x100","DateTime":"2020-03-24 21:01:29"},{"id":15,"ean":"7879879877989","year":2022,"month":12,"day":31,"qrdata":"5648789978978979887","qrurl":"http:\/\/api?data=Hesize=100x100","DateTime":"2020-03-24 21:01:39"}]}`

Here my Example DataTables code with your additions and my try of the "colums" addition mentioned on the DataTables website:

`    $(document).ready(function() {
        $('#example').DataTable( {
            "ajax": {
                "url": "http://192.168.1.208/objects.txt",
                "dataSrc": function(json) { console.log(json); return json.records; },
				},
				 "columns": [
            { "records": "name" }
           
        ]
            
        } );
    } );`

And here the Output from the Console:

`{records: Array(7)}records: Array(7)0: id: 8ean: "dfasdfasdfasdf"year: 2020month: 3day: 20qrdata: "555555"qrurl: "http://api?data=HelloWorld!&size=100x100"DateTime: "2020-03-24 20:59:24"__proto__: Object1: {id: 9, ean: "dfasdfasdfasdf", year: 2020, month: 3, day: 20, …}2: {id: 10, ean: "7879879877989", year: 2020, month: 3, day: 20, …}3: {id: 11, ean: "7879879877989", year: 2020, month: 3, day: 20, …}4: {id: 12, ean: "7879879877989", year: 2020, month: 3, day: 20, …}5: {id: 14, ean: "7879879877989", year: 2020, month: 12, day: 31, …}6: {id: 15, ean: "7879879877989", year: 2022, month: 12, day: 31, …}length: 7__proto__: Array(0)__proto__: Object`

**Comment by mevdschee** [comment]
That output is seriously mixed up.. maybe try

    return json.records.records;

Not sure, but it seems that it is double nested, is it?

**Comment by seljo-ch** [comment]
Thanks, but with this code, I don't get anything. Ether on the console. 

Yeah for me it looks as well double nested. But is the default output from  your script double nested? But what I can't understand, when I change the main json naming from "records" to someting else it works very well.

This was my intention to look at this side for a solution and not at the DataTables for a solution. Maybe there is a way to change the API Output, that it doesn't come with records?

**Comment by mevdschee** [comment]
What does this do?

    "columns": [{ "records": "name" }]

What if you leave that out?

**Comment by seljo-ch** [comment]
If tried it with and with out this lines. In the Documentation is mentioned that it's needed: [https://datatables.net/manual/ajax#Column-data-points](https://datatables.net/manual/ajax#Column-data-points)

**Comment by mevdschee** [comment]
AFAIK it should not say "records", but "data".. nevertheless it should work. Can you share a link to the project or a minimal example that fails? I'm willing to help debug it, but I can't. You may also email me a link to a screen-sharing session to debug together.

**Comment by mevdschee** [comment]
Please see the example above for usage of nested objects.

**Comment by seljo-ch** [comment]
Thank you very Much, with the Example it works!

Great job and very fast Support!
