### ISSUE TITLE
Struggling filtering  a many-to-many relationschip on foreign key

### ISSUE THREAD

**Issue by freddiefish** [mevdschee/php-crud-api#63]
Hi @mevdschee !

I have an entity (poi) that holds two foreign keys. From this, I want to filter on a foreign entity (places) id. From the result set, I want to also display data form the other entity (documents).

I get a PARSE ERROR when I run this: 
mydomain/api/api.php/documents?include=poi,places&transform=true&columns=documents.meetitem_title_pop,poi.draggable,places.lat,places.lng&filter[]=placed,ne,1

Can you point me in the right direction? 
Thanks
Fred

**Comment by mevdschee** [comment]
Hi Fred, I'd love to help. Can you post the exact error message you get? If possible, can you also provide some sample data that exposes the problem? This way I can try to reproduce the problem. Kind regards, Maurits

**Comment by mevdschee** [comment]
There is no string "PARSE ERROR" in the code, so this must come from another source:

see: https://github.com/mevdschee/php-crud-api/search?q=PARSE+ERROR

**Comment by freddiefish** [comment]
as sql-dump, what do you exactly need?

I get this error:
Invalid argument supplied for foreach() in <b>/home/pzbg263630/domains/openantwerpen.be/public_html/openstadsbestuur/api/api.php</b> on line <b>1530</b><br />
{"documents":[]}

**Comment by mevdschee** [comment]
Ok, is this what you need?

    api.php/places?include=poi,documents&columns=documents.meetitem_title_pop,poi.draggable,places.lat,places.lng&filter[]=id,ne,1&transform=1

The problem: The filter does not support other tables than the primary one.

**Comment by mevdschee** [comment]
I added a line of code to avoid duplicate table names, see: 4322850726205038f7441d13114df2f42026d540

**Comment by freddiefish** [comment]
Works like a charm!! Seems I do not have to put the connecting table in the include= parameter . In my case 'poi', that holds the 2 foreign keys for the 'many' sides documents,places. Am I correct with that?

**Comment by mevdschee** [comment]
Thank you for your feedback. 

>Seems I do not have to put the connecting table in the include= parameter
Indeed, you don't have to, but after my commit, you may.

If there is anything else I can help you with, please don't hesitate to open another issue!
