### ISSUE TITLE
Error due to lack of complex transactions?

### ISSUE THREAD

**Issue by qoubo** [mevdschee/php-crud-api#630]
Hey there!

Why are complex Transactions not supported?
I would like to use this API to pass data to my database, but the data seems to be too big...
`Object of class stdClass could not be converted to string` is the error.

I also recognized that there is no text/longtext type, I think that's because he throws this error.
But why isn't there this type?

**Comment by mevdschee** [comment]
Thank you for reporting this issue. I think the issue you run into is likely caused by something else than lack of transaction support. Also tex/longtext is supported. Maybe you can tell us exactly which request you are doing (and what you are sending) and then we can try to help you resolve the error you run into.

**Comment by qoubo** [comment]
TableName : vertretung
columns: id(primary), standIn
Im using Postman to send the request.

`Url: https://***********-**********.de/api.php/records/vertretung`

`Headers: the standard headers postman sets`
`Cache-Control: no-cache`
`Postman-Token: <calculated when request is sent>`
`Content-Type: application/json`
`Content-Length: <calculated>`
`Host: <calculated>`
`User-Agent: PostmanRuntime/7.24.0`
`Accept: */*`
`Connection: keep-alive`

and Im sending this in the body:

`{
    "standIn": {
        "standIns": [
            {
                "date": "16.01.2020",
                "class": "5,1",
                "standIn": [
                    {
                        "lesson": "**",
                        "time": "**********",
                        "subject": "***",
                        "teacher": "************",
                        "newSubject": "***",
                        "room": "*******",
                        "addition": "*******"
                    }
                ]
            }
        ]
    }
}`

**Comment by mevdschee** [comment]
Hi, nested writes are not supported. This is why the POST(?) is failing. You need to multiple simple writes (one table per request).

**Comment by qoubo** [comment]
solved the problem by replacing double quotes with single one's and wrapping it up in double quotes

`{
	"id": 3,
    "standIn": "{ 'standIn': { 'standIns': [ { 'date': '16.01.2020', 'class': '5,1', 'standIn': [ { 'lesson': '**', 'time': '**********', 'subject': '***', 'teacher': '************', 'newSubject': '***', 'room': '*******', 'addition': '*******' } ] } ] } }"
}`

**Comment by mevdschee** [comment]
Ah.. you wanted to store JSON in a text field! Now I understand your question. I'm glad you figured out how to do that. You may also use backslash to escape the quote character. JSON technically doesn't like those single quotes.

**Comment by qoubo** [comment]
encodeURI() should do the job
