### ISSUE TITLE
Latest version with SQLITE support

### ISSUE THREAD

**Issue by focussing** [mevdschee/php-crud-api#631]
I came to this repo via this: [https://tqdev.com/2016-php-crud-api-now-supports-sqlite](https://tqdev.com/2016-php-crud-api-now-supports-sqlite). Now I understand that the current V2 version does not longer support SQlite. One of the reasons being possibe performance degradation. For me is performance far less of importance than functionality.

Until now I have been using this api: https://github.com/alixaxel/ArrestDB.
However I need a kind of search or "select.. like" functionality which this one does not provide.

@mevdschee could you tell me please what the latest version is that does support SQLITE?

**Comment by mevdschee** [comment]
Thank you for asking this question. I believe all v1 versions support sqlite. I would be technically able to port the sqlite functionality to v2, but until now I have not. Please use #405 to express your interest in it and further discuss.

**Comment by focussing** [comment]
Thank you @mevdschee for this follow-up.

**Comment by focussing** [comment]
Could you provide the blog.db file mentioned [overhere](https://tqdev.com/2016-php-crud-api-now-supports-sqlite)?

**Comment by mevdschee** [comment]
> Could you provide the blog.db file mentioned [overhere](https://tqdev.com/2016-php-crud-api-now-supports-sqlite)? The link is broken.

You can create a new database (blog.db) and run this sql to recreate it:

https://github.com/mevdschee/php-crud-api/blob/v1/tests/data/blog_sqlite.sql

**Comment by focussing** [comment]
Beautiful! Thank you.
