### ISSUE TITLE
multiTenancy.handler location

### ISSUE THREAD

**Issue by millhoff** [mevdschee/php-crud-api#632]
Hi , I really like this API, but not being a PHP developer, I am trying to follow the documentation and add the handler mentioned, however, I am not sure where to place it. Could you share the location where it should go as I wonder if this was valid in v1 but code has changed for v2 ?

'multiTenancy.handler' => function ($operation, $tableName) {
    return ['customer_id' => 12];
},

**Comment by mevdschee** [comment]
It works the same, just add it to the configuration:

    'multiTenancy.handler' => function ($operation, $tableName) {
        return ($tableName == 'kunsthåndværk') ? ['user_id' => 1] : [];
    },

You can see an example in the tests. See: https://github.com/mevdschee/php-crud-api/blob/master/tests/config/base.php

**Comment by millhoff** [comment]
Many thanks for the quick reply , got it, and works like a charm
