### ISSUE TITLE
Request permissions / auth

### ISSUE THREAD

**Issue by pwFoo** [mevdschee/php-crud-api#633]
Hi,
I searched for a headless cms like [Directus](https://docs.directus.io/getting-started/introduction.html) and found your php-crud-api. 
Directus is a nice headless cms which extend a (custom) mysql database with authentication, permissions and some other parts with a nice admin interface.

But I think I haven't understood the usage of php-crud-api yet.
I can use it as a rest api with backend support for mysql, postgres, mssql, (sqlite?), but there is no permission handling to limit data by user / group?

Is it possible to hook or build could around php-crud-api to handle permissions? 

I think directus is to much for my needs and php-crud-api not have all the needed parts?

**Comment by mevdschee** [comment]
>Is it possible to hook or build could around php-crud-api to handle permissions?

You can setup multi-tenancy (one database for multiple customers) using the multi-tenancy handler or you can implement an authorization handler (to set what read/writes are permitted) based on the authenticated user and their role(s). 

>I think directus is to much for my needs and php-crud-api not have all the needed parts?

Could very well be, you did not explain your use case (needs) and I'm not familiar with Directus.

**Comment by pwFoo** [comment]
I try to separate frontend from backend. Backend is database, some server side (php) code like maybe push notifications (webpush-api). But I need some content access control (view, edit, create, delete) by users / groups.
It's easy with a cms and even better with a headless cms. Directus looks awesome as database administration tool and feature rich rest api, but I can't integrate it with my other server side code...

So I searching for a database management, access control / user or group permissions tool with a rest api and without an integrated template system.

**Comment by mevdschee** [comment]
Well.. Why dont you give php-crud-api a try? It can be integrated indeed and you can implement any custom authorization system that you need. Did I mention it is MIT licensed and not GPL? Enjoy the software!

**Comment by pwFoo** [comment]
Yes, I will do.

Are there some more examples and documentation for middleware multiTenancy, sanitation and authorization / server side permission check?

**Comment by pwFoo** [comment]
Moved to #620 and close here. Thanks!
