### ISSUE TITLE
Views in MYSQL return error 9999

### ISSUE THREAD

**Issue by millhoff** [mevdschee/php-crud-api#634]
I am using MySql and 5 and Php 7. Whenever I try to access a view, I get Error 9999.  Is that a problem with that version of MySql  ? I have no trouble using the view from my own php statement. Any hint's are welcome.

**Comment by mevdschee** [comment]
>Is that a problem with that version of MySql?

MySQL 5.6 and PHP 7.0 and higher are supported.

> I get Error 9999

Please enable debug by setting in the config:

    'debug' => true,

And check the response headers for a more descriptive error message.

**Comment by millhoff** [comment]
Enabled debug, no change:
{"code":9999}

**Comment by mevdschee** [comment]
Great this is probably due to the definition cache being to low, see:

https://stackoverflow.com/questions/4380813/how-to-get-rid-of-mysql-error-prepared-statement-needs-to-be-re-prepared

**Comment by mevdschee** [comment]
From #593:

>This helped:
>In this method: GenericDb::getOptions()
>set the option: 
>    \PDO::ATTR_EMULATE_PREPARES => true, // was false before

**Comment by millhoff** [comment]
Great, yes that worked! May be worth adding something at the end of the documentation that covers these rare cases , so people know what to set. Anyway thanks again

**Comment by mevdschee** [comment]
> set the option: PDO::ATTR_EMULATE_PREPARES => true

Heads up that this is now the default in v2.10.1 onwards, so no need to change anything anymore, see also #759
