### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by pwFoo** [mevdschee/php-crud-api#635]
I looked into related projects. I think some Projects integrated into php-crud-api (single file api script?) and admin is an extension to it?

Both contain php-crud-api code? How to remove duplicated code?

**Comment by mevdschee** [comment]
There is a package manager in place to avoid duplicate code. When the code is compiled into a single file then the code is duplicated (obviously). You don't have to use the single file, you can also use the 'src' folder and the composer package.
