### ISSUE TITLE
authorization.tableHandler not working as expected

### ISSUE THREAD

**Issue by kdoe13** [mevdschee/php-crud-api#636]
I'm having a little trouble with the authorization.tableHandler. 

Imagine I have the following DB structure:
Business
  --People

I want "People" to be completely shut-down (only internal use, which I can look at the DB directly) but "Business" to be public. I'd assume in tableHandler, I can just put:
return $tableName != "People";

This works for a direct GET /People request, but it does not work for GET /Business?join=People.  I'm not sure why this is not the case, and also in the code in [Authorization Middleware](https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Middleware/AuthorizationMiddleware.php#L40-L55), the table is removed from the reflection variable, which leads me to think this might be a bug.. ?

Anyhow, wondering if this is something that can be changed. I do realize I could write the following to accomplish my goal but it isn't ideal: 

`authorization.recordHandler => function ($operation, $tableName) {`
`return ($tableName == 'People') ? 'filter=id,eq,null' : '';`
`}`

**Comment by mevdschee** [comment]
Thank you for reporting this issue. I did a bugfix and tried to fix this in master. Is it working as expected with that version?

**Comment by mevdschee** [comment]
I covered this issue in a test to avoid regression.

**Comment by mevdschee** [comment]
Please let me know if this solved your issue. I'm assuming it did. Closing the bug for now.

**Comment by kdoe13** [comment]
@mevdschee Hey there, sorry had to work on another project for a few days, but got everything checked out now and confirm that this is now working as expected for me. Sorry for the delay and thank you for your quick response.
