### ISSUE TITLE
auth0 problems with vanilla.html

### ISSUE THREAD

**Issue by mrcnee93** [mevdschee/php-crud-api#639]
Hi, 
i've followed your docs for auth0 but still i'm not able to access my endpoint.
I've already looked at the other similar issues without luck.

here's my PHP
`
// file: src/index.php
namespace Tqdev\PhpCrudApi {

    use Tqdev\PhpCrudApi\Api;
    use Tqdev\PhpCrudApi\Config;
    use Tqdev\PhpCrudApi\RequestFactory;
    use Tqdev\PhpCrudApi\ResponseUtils;

    $config = new Config([
        'username' => '[my user]',
        'password' => '[my pwd]',
        'database' => '[my db]',
        'middlewares' => 'cors, jwtAuth, authorization',
        'jwtAuth.secret' =>"-----BEGIN CERTIFICATE---- my app certificate -----END CERTIFICATE-----"
    ]);

    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    ResponseUtils::output($response);
}`

This is the response:
<img width="413" alt="Schermata 2020-04-10 alle 16 07 34" src="https://user-images.githubusercontent.com/63459992/78996701-7559ca00-7b45-11ea-85f1-6c36f56a156b.png">

the auth0 signIn/login/logout works.

am i missing something? 

Thanks

**Comment by mevdschee** [comment]
Please read:

https://github.com/mevdschee/php-crud-api/issues?q=is%3Aissue+auth0

And especially issue #554

**Comment by mevdschee** [comment]
Did you resolve the issue? Is there any way I can help you?

**Comment by mrcnee93** [comment]
I, i'm working on it today, i'll let you know if it works. thanks, i really appreciate the support.

**Comment by mrcnee93** [comment]
> Please read:
> 
> https://github.com/mevdschee/php-crud-api/issues?q=is%3Aissue+auth0
> 
> And especially issue #554 and #604

Hi, for the #554 issue i've already replied there, for the #604 i'm replying here (because i've seen the "closed" tag).

My sign algorithm is RS256.
<img width="679" alt="Schermata 2020-04-14 alle 12 22 24" src="https://user-images.githubusercontent.com/63459992/79214162-9e7ea100-7e4a-11ea-8660-0488adbf14ad.png">

I've seen an array in the api.php file containing some algorithms, it's the only place it appears to me the RS256 string.

<img width="646" alt="Schermata 2020-04-14 alle 12 24 40" src="https://user-images.githubusercontent.com/63459992/79214320-ee5d6800-7e4a-11ea-820e-41eb2e429ae8.png">

**Comment by mevdschee** [comment]
@kevinstory wrote:

>Once I changed that in the algorithm array, it appears to be working now.

Do you understand what to change? I don't. If so, can you (or @kevinstory) do a PR?

**Comment by mrcnee93** [comment]
I don't understand what need to be changed here

**Comment by marionee** [comment]
Hi there,
after reading the latest answers with @mrcnee93, we tried to convert Certificate to public key using this command

[openssl x509 -in key.pem -pubkey -noout]

We have also tried to debug and have finally discover where the auth fails, see the screen attached. 
<img width="849" alt="Schermata 2020-04-19 alle 23 54 22" src="https://user-images.githubusercontent.com/25976529/79701012-01809580-829a-11ea-904e-c30206a593c7.png">

The variable kid contains a text, probably the problem is related to $secrets array?

**Comment by mevdschee** [comment]
>The variable kid contains a text

This is the problem. If you specify a 'kid' in the claims, then you should use 'jwtAuth.secrets' instead of 'jwtAuth.secret' and the format should be '{kid}:{key}'.

**Comment by mevdschee** [comment]
Also note this from the readme:

>Then you have to configure the jwtAuth.secrets configuration in your api.php file. Don't fill it with the secret you will find in your Auth0 application settings but with a public certificate. To find it, go to the settings of your application, then in "Extra settings". You will now find a "Certificates" tab where you will find your Public Key in the Signing Certificate field.

([source](https://github.com/mevdschee/php-crud-api))

**Comment by marionee** [comment]
It works! Thank you.
After this 2 changes everything works now:
- fixed the key jwtAuth.secret to jwtAuth.secrets
- fixed the syntax to ‘jwtAuth.secrets’ => “kid:public_key”

The extraction of public key from public cert is not necessary, following the above changes the validation works!

**Comment by mevdschee** [comment]
If you feel the documentation can be improved, then please do a PR of the README with your adjustments in it. That would be highly appreciated. Enjoy the software!
