### ISSUE TITLE
PUT issues with axios

### ISSUE THREAD

**Issue by albmunmu** [mevdschee/php-crud-api#640]
I am using axios to make a PUT request to Update data:
` 
axios
      .put(
        '/api/api.php/records/customer/' + 
          this.props.match.params.id,
        {
          data,
        }
      )
      .then((res) => {
        console.log(res);
        console.log(res.data);
      });
`
**_data_** object contains the correct variable names changed. Yet in my response I am getting the old data, and no changes are being reflected on the DB.  No errors being thrown too.

What could be my issue ?

**Comment by mevdschee** [comment]
>no changes are being reflected on the DB. No errors being thrown too.

So you are getting a 200 response?

Can you open the web developer tools and show/copy the information from the network tab for that request?

**Comment by albmunmu** [comment]
Not an api issue, .htacess configuration was the issue! Thank you for fast response

**Comment by mevdschee** [comment]
You are welcome. If any new issue arises, feel free to open a new issue. Enjoy the software!
