### ISSUE TITLE
PHP Fatal error:  Cannot declare interface

### ISSUE THREAD

**Issue by sinky** [mevdschee/php-crud-api#643]
Hi,
just downloaded api.php and changed credentials on the bottom, but i get the following error:
```
Got error 'PHP message: PHP Fatal error:  Cannot declare interface Psr\\Http\\Message\\RequestFactoryInterface, because the name is already in use in /var/www/api/api.php on line 17'
```

What's wrong?

**Comment by mevdschee** [comment]
Did you try to run it standalone? If you run it as part of another framework, then you should use composer to install, see: 

- [Automatic REST API for Laravel](https://tqdev.com/2019-automatic-rest-api-laravel)
- [Automatic REST API for Symfony 4](https://tqdev.com/2019-automatic-rest-api-symfony)
- [Automatic REST API for SlimPHP 4](https://tqdev.com/2019-automatic-api-slimphp-4)

Kind regards, Maurits

**Comment by sinky** [comment]
Yes, api.php standalone, from current git. PHP Version 7.4.
Already tried it with file from Release v2.7.3

**Comment by mevdschee** [comment]
Did you do any includes?

**Comment by mevdschee** [comment]
I can reproduce the error by including "api.php" in the file "api.php" (create a loop).

**Comment by mevdschee** [comment]
I cannot reproduce the error in any PHP version, see: https://3v4l.org/PHgit

**Comment by mevdschee** [comment]
What operating system are you running on?

**Comment by sinky** [comment]
no include. just the api.php with changed credentials.
CentOS Linux 7 @ https://uberspace.de a shared hosting with cli access

It seem a php7.4 issue
$ php73 api.php
{"code":1000,"message":"Route '' not found"}

$ php74 api.php
PHP Fatal error:  Cannot declare interface Psr\Http\Message\RequestFactoryInterface, because the name is already in use in /var/www/virtual/mk/html/crud/api.php on line 17

**Comment by mevdschee** [comment]
Can you send the (cli) output of phpinfo();?

    echo 'phpinfo();' | php -a

I'd love to find out what is causing this.

**Comment by mevdschee** [comment]
I have added CentOS 8 docker with PHP 7.4.4 and all tests run fine:

    [root@2fe06043c898 php-crud-api]# php -v
    PHP 7.4.4 (cli) (built: Mar 17 2020 10:40:21) ( NTS )
    Copyright (c) The PHP Group
    Zend Engine v3.4.0, Copyright (c) Zend Technologies
    [root@2fe06043c898 php-crud-api]# php api.php 
    {"code":1000,"message":"Route '' not found"}
    [root@2fe06043c898 php-crud-api]# 

I think the host is misconfigured somehow.

**Comment by mevdschee** [comment]
With the extra CentOS and PHP 7.4 tests I think it is proven well enough that the problem is not in this software. Thus the label 'invalid'. Did you try other software under PHP 7.4 on that host?

**Comment by mevdschee** [comment]
Thank you Marco for your PM with phpinfo contents. It seems extension "psr" is loaded in your CentOS installation with "dnf -y install php-psr". This is a problem for the compiled (single-file) version of the script. I'll see what I can do about this.

**Comment by mevdschee** [comment]
Okay.. messy commits, but it is fixed.

Rebuilding using "php build.php" when the "psr" extension is loaded should now create an "api.php" that does not contain the PSR interfaces.

I hope this solution works for you.

**Comment by sinky** [comment]
yes it works perfectly
