### ISSUE TITLE
9999 error

### ISSUE THREAD

**Issue by hannovermeulen** [mevdschee/php-crud-api#647]
Hi,
Thanks for an awesome product.  I am very very new to this and need some help.
I used the single file internally on our dev server running IIS, PHP 7.3. I connect to another internal MS Sql Server.  All works perfectly when testing with Postmaster.

I then proceeded to copy the api.php file to our web server and tried the same GET and POST that worked perfectly before.  Now I get a 500 internal error (9999).

The servers are identical.  Where can I look? Probably something realy easy that I might have overlooked.

Content-Type: application/json
Server: Microsoft-IIS/10.0
X-Powered-By: PHP/7.3.1
X-Exception-Name: PDOException
X-Exception-Message: SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: The wait operation timed out.
X-Exception-File: C:\inetpub\BearesWeb\api\api.php:6271

Regards
H

**Comment by mevdschee** [comment]
>Probably something really easy that I might have overlooked.

It seems that the server is not responding fast enough to the reflection queries. Are the databases of equal size? You may want to reduce the number of tables exposed using the "tables" config parameter.

**Comment by gaegaelab** [comment]
I tried the Laravel tutorial below on AWS EC2 as is, but I am getting the same problem.
https://tqdev.com/2019-automatic-rest-api-laravel
Below is the response. No message is attached.
```
{"code": 9999}
```
The response status in the browser was 500.
Nothing is displayed on the console, so I don't know the cause and there is no use for the action.

**Comment by gaegaelab** [comment]
> I tried the Laravel tutorial below on AWS EC2 as is, but I am getting the same problem.
> https://tqdev.com/2019-automatic-rest-api-laravel
> Below is the response. No message is attached.
> 
> ```
> {"code": 9999}
> ```
> 
> The response status in the browser was 500.
> Nothing is displayed on the console, so I don't know the cause and there is no use for the action.

I was using AWS so I only had to address it. 💦
Connected below.
`` `
    $ config = new Config ([
        'address' => env ('DB_HOST'),
        'username' => env ('DB_USERNAME'),
        'password' => env ('DB_PASSWORD'),
        'database' => env ('DB_DATABASE'),
        'basePath' => '/ api',
    ]);
`` `

**Comment by mevdschee** [comment]
Thank you for reporting this issue. Try enable debug, with the config:

    'debug' => true,

And post the output (and the response headers).

**Comment by hannovermeulen** [comment]
Hi mevdschee,
I restricted the tables and the Table depth, works perfect. Like a BOSS, tx so much.

**Comment by mevdschee** [comment]
Great, thank you for reporting back!
