### ISSUE TITLE
Laravel on AWS EC2, but I am getting error 9999

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#650]
> I tried the Laravel tutorial below on AWS EC2 as is, but I am getting the same problem.
> https://tqdev.com/2019-automatic-rest-api-laravel
> Below is the response. No message is attached.
> 
> ```
> {"code": 9999}
> ```
> 
> The response status in the browser was 500.
> Nothing is displayed on the console, so I don't know the cause and there is no use for the action.

I was using AWS so I only had to add the address. 💦
Connected below.
```
    $ config = new Config ([
        'address' => env ('DB_HOST'),
        'username' => env ('DB_USERNAME'),
        'password' => env ('DB_PASSWORD'),
        'database' => env ('DB_DATABASE'),
        'basePath' => '/ api',
    ]);
```

_Originally posted by @gaegaelab in https://github.com/mevdschee/php-crud-api/issues/647#issuecomment-618150760_

**Comment by mevdschee** [comment]
Thank you for reporting this issue. Try enable debug, with the config:

    'debug' => true,

And post the output (and the response headers).

**Comment by gaegaelab** [comment]
As mentioned above, adding the address now returns records instead of 9999.

I also tried debug.
```
    $ config = new Config ((
        'debug' => true,
        'username' => env ('DB_USERNAME'),
        'password' => env ('DB_PASSWORD'),
        'database' => env ('DB_DATABASE'),
        'basePath' => '/ api',
    ]);
```
Is this all right? It seems that the debug log is not output.
`{" code ": 9999}` will be returned. No errors or logs are displayed on the AWS console.

**Comment by mevdschee** [comment]
>Is this all right?

Yes.

>It seems that the debug log is not output.

I cannot explain that.

**Comment by mevdschee** [comment]
>As mentioned above, adding the address now returns records instead of 9999.

So, does this mean that your issue is resolved? If so, you may close it.

**Comment by gaegaelab** [comment]
I want to close this issue, but I can't close it because it's not an issue I created 💦

**Comment by mevdschee** [comment]
No problem, thank you for reporting back.
