### ISSUE TITLE
Multiple filters with the same name are not valid in Laravel.

### ISSUE THREAD

**Issue by gaegaelab** [mevdschee/php-crud-api#651]
I made a URL like this.
`/api/records/user?filter=email,eq,address@gmail.com&filter=password,eq,12345678`
I was expecting a record with the specified email address and password to be returned.
However, a record with a matching email address or password was returned.
What's wrong?

**Comment by gaegaelab** [comment]
I tried to output SQL log.
It seems that only the filter behind is valid. It wasn't "OR".
```
SELECT "id","email","password","thumb_name","part","family_name","given_name","is_delete","created_at","updated_at" FROM "user" WHERE "password" IN ('12345678') ORDER BY "id" ASC
```

**Comment by gaegaelab** [comment]
It was because I was running it in Laravel.
When I ran it only in api.php, both filters were in the query.

**Comment by mevdschee** [comment]
You can try the official syntax for PHP, so instead of:

    /api/records/user?filter=email,eq,address@gmail.com&filter=password,eq,12345678

make it:

    /api/records/user?filter[]=email,eq,address@gmail.com&filter[]=password,eq,12345678

It seems Laravel does not play nice with two get parameters with the same name.

**Comment by gaegaelab** [comment]
> make it (looks a bit ugly):
> 
> ```
> /api/records/user?filter[]=email,eq,address@gmail.com&filter[]=password,eq,12345678
> ```
It worked!
I don't care what the URL looks like!
Thank you!

**Comment by gaegaelab** [comment]
Some people may be in trouble, but I'm okay with this, so I close the issue.
