### ISSUE TITLE
Error occurs when Create.

### ISSUE THREAD

**Issue by gaegaelab** [mevdschee/php-crud-api#652]
I tried to insert into a table with Laravel.
I got the following error.
```
{
"code": 9999,
"message": "Argument 1 passed to Tqdev\\PhpCrudApi\\Database\\ColumnsBuilder::quoteColumnName() must be an instance of Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedColumn, null given, called in /home/ec2-user/MYPROJECT/vendor/mevdschee/php-crud-api/src/Tqdev/PhpCrudApi/Database/ColumnsBuilder.php on line 80"
}
```
I get the same error when I use a standalone api.php without Laravel.
```
{
"code": 9999,
"message": "Argument 1 passed to Tqdev\\PhpCrudApi\\Database\\ColumnsBuilder::quoteColumnName() must be an instance of Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedColumn, null given, called in /home/ec2-user/MYPROJECT/api.php on line 4896"
}
```

DB : MariaDB 10.3.20
Path : /api/records/post
Method: Post
Body: 
```
{"group_id":1,"user_id":1,"parent_id":0,"text":"sdfsdfsdf","photo_name":"","video_name":"","is_delete":false}
```
How do I get rid of the error?

**Comment by mevdschee** [comment]
Thank you for reporting this issue. Does the table and the named columns exist? Can you post the SQL TABLE CREATE statement?

**Comment by gaegaelab** [comment]
I set the primary key to two columns.
After reducing the primary key to one, this error no longer occurs.

Another error has occurred.
I got the following error because is_delete was TINYINT but set it to false.
```
{
"code": 9999
}
```
When I set it to 0 instead of false, the record was successfully added.

I didn't need two primary keys.
I'm fine with this.

**Comment by mevdschee** [comment]
>I didn't need two primary keys.

That is also not supported by this software.

> I got the following error because is_delete was TINYINT but set it to false.

The "TINYINT(1)" type is most often used to represent the (missing) boolean type in mysql.

> I'm fine with this.

Sounds good, so your issue is resolved? Feel free to close it if it is.
