### ISSUE TITLE
Auth Method for creating native Mobile login

### ISSUE THREAD

**Issue by billiemead** [mevdschee/php-crud-api#653]
I have setup the API in Laravel 5.8 and its been running great. Laravel is being using for the backend and also the web frontend.  I configured php-crud-api using the database auth method. The API will primarily be for native ecommerce Android and IOS apps.

Is this the best method to use for creating a LOGIN page for native mobile use? I believe it is after the research I have done online but figured I would ask first.

Also, just a quick note that whenever I run composer update or a new install, I get the message that the package zendframework/zend-diactoros is abandoned and a suggestion to use laminas/laminas-diactoros instead. Would this have any consequences? 

Thank you for such a great resource!

**Comment by mevdschee** [comment]
>Is this the best method to use for creating a LOGIN page for native mobile use?

I'm not sure I would call it "the best method", but I guess it will work.

>I get the message that the package zendframework/zend-diactoros is abandoned and a suggestion to use laminas/laminas-diactoros instead. Would this have any consequences?

I don't think so. Who is requiring that package? This library is not..

**Comment by billiemead** [comment]
> I'm not sure I would call it "the best method", but I guess it will work.

Great, I'll give it a go...

> I don't think so. Who is requiring that package? This library is not..

Well, I used the install instructions from [here](https://tqdev.com/2019-automatic-rest-api-laravel), and about three paragraphs down:

> **Install PHP-CRUD-API**
In order to add the automatic API library you need to run:
`php composer.phar require symfony/psr-http-message-bridge`
`php composer.phar require zendframework/zend-diactoros`
`php composer.phar require mevdschee/php-crud-api`

**Comment by mevdschee** [comment]
>Well, I used the install instructions from here, and about three paragraphs down:

Ah.. I get it.. it is the PSR-7 bridge and implementation for Laravel. It is not in the composer JSON as a direct dependency, that's why I was confused.

Yeah.. if Laravel is now using another PSR7 implementation, then it is fine to use that one.

**Comment by mevdschee** [comment]
>Great, I'll give it a go...

You'll run into some missing features (brute force attack detection). Feel free to request them here and/or try to contribute them in a PR.

**Comment by billiemead** [comment]
> > Great, I'll give it a go...
> 
> You'll run into some missing features (brute force attack detection for instance). Feel free to request them here and/or try to contribute them in a PR.

I absolutely will contribute them as I work on this! Thank you again for everything... its those like **you** that help those like **me** learn and progress on our journey!

**Comment by mevdschee** [comment]
>Thank you again for everything

You are welcome, your gratefulness is appreciated. Enjoy the software and stay safe!

**Comment by mevdschee** [comment]
>Well, I used the install instructions from here,

FYI, I updated the blog post. Thank you reporting this issue.

**Comment by billiemead** [comment]
Super, I am going to update Laravel this afternoon with the new dependency!
