### ISSUE TITLE
connect to a SQL SERVER 2017, but error 9999 occurs

### ISSUE THREAD

**Issue by gyancarlodasilva** [mevdschee/php-crud-api#654]
I'm trying to connect to a SQL SERVER 2017, but error 9999 occurs, see the image below:
![image](https://user-images.githubusercontent.com/6933051/80227467-08a1fd80-8624-11ea-99ce-0ddc8322ea5f.png)

I put debug with value true, but there is no return.

I built a php code to check the sql connection and it works.
![image](https://user-images.githubusercontent.com/6933051/80227674-5c144b80-8624-11ea-8d6b-f473f8b9a95b.png)

Can you help me?

**Comment by mevdschee** [comment]
Thank you for creating this issue. Let me try to help you.

>I put debug with value true, but there is no return.

That is unexpected, can you post your configuration?

**Comment by gyancarlodasilva** [comment]
Hello, follows requested items.
![image](https://user-images.githubusercontent.com/6933051/80370306-3d04fc00-8866-11ea-94e8-4cb313442990.png)

![image](https://user-images.githubusercontent.com/6933051/80372599-2c568500-886a-11ea-91ce-492426cab79a.png)

```
HTTP/1.1 500 Internal Server Error
Host: localhost:8000
Date: Mon, 27 Apr 2020 12:18:50 GMT
Connection: close
X-Powered-By: PHP/7.4.3
Content-Type: application/json
Content-Length: 13
X-Exception-Name: PDOException
X-Exception-Message: SQLSTATE[08001]: [Microsoft][ODBC Driver 17 for SQL Server]Provedor TCP: No connection could be made because the target machine actively refused it.
X-Exception-File: D:\Outsourcing\web\htdocs\api\index.php:6283
```

The debug still not working.

About this message on the response hearder "[Microsoft][ODBC Driver 17 for SQL Server]Provedor TCP: No connection could be made because the target machine actively refused it.", but this not happend with my connection test code.
![image](https://user-images.githubusercontent.com/6933051/80372483-f913f600-8869-11ea-9959-6500f98be3f6.png)

Thanks for your help.

**Comment by mevdschee** [comment]
I think the firewall prevents a connection or your server listens to an alternative port.

**Comment by mevdschee** [comment]
Okay, I see that the address you use is: SCVNAPPA7452\POWERBI_ATE_2K17

Can you try to use a double backslash? 

    SCVNAPPA7452\\POWERBI_ATE_2K17

Also try this:

    $conn = new PDO("sqlsrv:Server=$address,$port;Database=$database", $username, $password);

You can try a PHP file with the above to connect with your credentials set. Port defaults to 1433.

    

You

**Comment by mevdschee** [comment]
Are you trying to use the PHP PDO Connection to SQL Server with integrated security?

see: https://stackoverflow.com/questions/857194/php-pdo-connection-to-sql-server-with-integrated-security

**Comment by DearPureone** [comment]
Try this query to check which port number SQL Server is working
> 
> ```
>SELECT DISTINCT 
 >local_tcp_port 
>FROM sys.dm_exec_connections 
>WHERE local_tcp_port IS NOT NULL 
> ```
> 
 It work in my case, hope this helps.

**Comment by mevdschee** [comment]
@gyancarlodasilva any update?

**Comment by gyancarlodasilva** [comment]
> Okay, I see that the address you use is: SCVNAPPA7452\POWERBI_ATE_2K17
> 
> Can you try to use a double backslash?
> 
> ```
> SCVNAPPA7452\\POWERBI_ATE_2K17
> ```
> 
> Also try this (this is what the script does):
> 
> ```
> $dsn = "sqlsrv:Server=$address,$port;Database=$database";
> var_dump($dsn);
> $conn = new PDO($dsn, $username, $password);
> var_dump($conn);
> ```
> 
> You can try a PHP file with the above to connect with your credentials set for address, database, username and password. Port defaults to (TCP port) 1433.
> 
> I hope this helps.

I tried this, but doesn't work.
![image](https://user-images.githubusercontent.com/6933051/81092028-652fd300-8ed6-11ea-9b68-36a4afbf4294.png)

**Comment by gyancarlodasilva** [comment]
> Are you trying to use the PHP PDO Connection to SQL Server with integrated security?
> 
> see: https://stackoverflow.com/questions/857194/php-pdo-connection-to-sql-server-with-integrated-security

I tried this, with my code, look the results.
![image](https://user-images.githubusercontent.com/6933051/81092239-b50e9a00-8ed6-11ea-93fd-798388581cd2.png)

This is my code

> > Okay, I see that the address you use is: SCVNAPPA7452\POWERBI_ATE_2K17
> > Can you try to use a double backslash?
> > ```
> > SCVNAPPA7452\\POWERBI_ATE_2K17
> > ```
> > 
> > 
> > Also try this (this is what the script does):
> > ```
> > $dsn = "sqlsrv:Server=$address,$port;Database=$database";
> > var_dump($dsn);
> > $conn = new PDO($dsn, $username, $password);
> > var_dump($conn);
> > ```
> > 
> > 
> > You can try a PHP file with the above to connect with your credentials set for address, database, username and password. Port defaults to (TCP port) 1433.
> > I hope this helps.
> 
> I tried this, but doesn't work.
> ![image](https://user-images.githubusercontent.com/6933051/81092028-652fd300-8ed6-11ea-9b68-36a4afbf4294.png)

I found the error, the port number is different.
I used this script on SSMS (SQL SERVER) to find the correct port.
```
USE MASTER
GO
xp_readerrorlog 0, 1, N'Server is listening on'
GO
```

I changed the port on the config and the access worked.

**Comment by mevdschee** [comment]
I'm glad you've found the solution! Thank you for reporting back.
