### ISSUE TITLE
Get view by id issue

### ISSUE THREAD

**Issue by Killea** [mevdschee/php-crud-api#655]
Currently, I use 
**http://localhost/api.php/records/pig** this is working
But
http://localhost/api.php/records/pig/1 this returns:
{
"code": 1015,
"message": "Operation 'read' not supported"
}
How can I get a specific id for in a view select? Thank you.

**Comment by mevdschee** [comment]
There is no proper primary key reflection for views, so you need to specify a filter:

    http://localhost/api.php/records/pig?filter=id,eq,1

I hope this helps.

**Comment by Killea** [comment]
Thank you for your quick reply.
