### ISSUE TITLE
Need to Customize Post API Request Body

### ISSUE THREAD

**Issue by mjza** [mevdschee/php-crud-api#656]
Assume I have the following data in the body of my POST request:

```
{ 
    "a": "1",
    "c": "3"
}
```

I want to modify the body of my post request before inserting in DB like this:

```
'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
	$request->body['b'] = 2;
},
```
I know this code is wrong but I couldn't find any documentation of how to do it?

**Comment by mevdschee** [comment]
Thank you for creating this issue. It is a good question. This shows how to do it:

    $body = $request->getParsedBody();
    $body['b'] = 2;
    return $request->withParsedBody($body);

I hope this helps.

**Comment by mjza** [comment]
I tried it, and what I get is 500 error,

> code: 9999
> message: "Cannot use object of type stdClass as array"

**Comment by mjza** [comment]
for me this works:

```
$body = $request->getParsedBody();
$body->b = 2;
return $request->withParsedBody($body);
```
