### ISSUE TITLE
PostreSQL 12 Supported

### ISSUE THREAD

**Issue by emond07** [mevdschee/php-crud-api#657]
Hi,

Im using Mysql before and it working properly . May I know what is the settings for PostgreSQL, version 12 compatible? Thanks for the hard work.
![sc1](https://user-images.githubusercontent.com/17446488/80851012-9e0b4600-8c51-11ea-9a2a-2ae4479a880d.png)

**Comment by emond07** [comment]
> Hi,
> 
> Im using Mysql before and it working properly . May I know what is the settings for PostgreSQL, version 12 compatible? Thanks for the hard work.
> ![sc1](https://user-images.githubusercontent.com/17446488/80851012-9e0b4600-8c51-11ea-9a2a-2ae4479a880d.png)

Nevermind this. Got the solution. thanks

**Comment by mevdschee** [comment]
Yes, I guess you had to add:

    'driver' => 'pgsql',

In case anyone else finds this ticket.

**Comment by emond07** [comment]
thanks a lot.
