### ISSUE TITLE
OpenApi

### ISSUE THREAD

**Issue by PatrickV82** [mevdschee/php-crud-api#659]
Does the OpenApi swagger generate the api documents for the creation, updating commands.
With my database it only gives documentation for the get functions.

**Comment by mevdschee** [comment]
It does when you have only read permissions, is that the case?

**Comment by PatrickV82** [comment]
that is probably the problem then, as I did not setup any authentication.
Will try to do it, and see how it works.

**Comment by mevdschee** [comment]
>I did not setup any authentication.

That is not what I meant. Has the user, that you connect with, write permissions to the database?

**Comment by PatrickV82** [comment]
yes the user has write permissions to the database, at least it should as it is the root user for the database

**Comment by mevdschee** [comment]
Hmm... can you post your configuration?

**Comment by PatrickV82** [comment]
I use the latest posed api.php with just the following edits. 
---
` 
// file: src/index.php
namespace Tqdev\PhpCrudApi {

    use Tqdev\PhpCrudApi\Api;
    use Tqdev\PhpCrudApi\Config;
    use Tqdev\PhpCrudApi\RequestFactory;
    use Tqdev\PhpCrudApi\ResponseUtils;

    $config = new Config([
        // 'driver' => 'mysql',
        // 'address' => 'localhost',
        'username' => 'root',
        'password' => 'iUCh2IC0OmTV',
        'database' => 'shootinginfo',
        // d'debug' => false
    ]);
    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    ResponseUtils::output($response);
}
`

**Comment by mevdschee** [comment]
Ah.. you may not have any primary keys defined, could that be the case?

**Comment by PatrickV82** [comment]
It looks like that might be the case, did not make the database. 
Will alter the database and will let you know

**Comment by mevdschee** [comment]
Yeah.. I'm pretty sure that that is the problem. Feel free to open a new issue when you run into something else.
