### ISSUE TITLE
dbAuth error -> {code:1012, message:Authentication failed for 'username'}

### ISSUE THREAD

**Issue by ndee85** [mevdschee/php-crud-api#660]
Hi,
I am trying to access the database via the dbAuth. Without authentification everything worked perfectly. Now I want to secure the database and only give certain users access.

I hope I did understand everything correctly. But somehow I cannot get proper access. Always getting the error message:
{code:1012, message:Authentication failed for 'username'}

Here is my config so far:
$config = new Config([
        'username' => 'root',
        'password' => 'DBPassword',
        'database' => 'database_name',
'middlewares' => 'cors, dbAuth',
'dbAuth.mode' => 'required',
'dbAuth.usersTable' => 'users',
'dbAuth.usernameColumn' => 'username',
'dbAuth.passwordColumn' => 'password'
    ]);

As said, general access to database is working. So I asume that the database is setup correctly. For dbAuth access I created a new table, called users. The table users has follwing columns:
username varchar(15),
password varchar(8), <- for testing purposes a varchar with size 8
first_name varchar(30),
last_name varchar(30)

The table contains one user.
username -> username
password -> 12345678
first_name -> User
last_name -> Name

I am doing a Post request with following stringified json data and this url:
localhost/restAPI/api.php/login
{"username":"username", "password":12345678}

Getting a response code 403 with the above mentioned error.
I wanted to ask if I am doing something completely wrong, or should it work that way?

**Comment by mevdschee** [comment]
>The table contains one user.

Is the password stored as:

    $2y$10$pn2h4FgTfeudLZf0r2LxHe/H9qncaTjNtVmvESJREa1ND4aUtfOdy

This is the output of the command:

    php -r 'echo password_hash("12345678", PASSWORD_DEFAULT)."\n";'

As described in the manual here:

https://github.com/mevdschee/php-crud-api#database-authentication

**Comment by ndee85** [comment]
Yes, that was my error. I stored the password in a human readable text and not hashed. Thank you very much for your quick support! Really appreciate it!!!

Now the authentication process works perfectly. Thanks for this great api. Learning a lot about databases lately! :-)

**Comment by mevdschee** [comment]
Thank you Andreas, appreciated. I have seen your work on YouTube and I'm in awe (Brave Bran looks amazing)! Keep it up.

**Comment by ndee85** [comment]
Wow.. thanks a bunch. Currently not working actively on the game though :-(

Sorry, may I have a follow up question. I am using godot(game engine) to to access the database via your module. 
Authentication works now when sending an http_request. But as it seems, each request godot sends, it doesn't know anything about the request before.
So making a post to the login endpoint works fine. I get a successfull response. But when then sending an http get request I have no permission again. Is there a way to pass permission in the header somehow?
Maybe this is a dump question, databases and rest access is a pretty new world for me :-)

**Comment by mevdschee** [comment]
This is because the request logs you in and gets a cookie returned that has to be set in subsequent requests. 

See: https://github.com/godotengine/godot/issues/17711

**Comment by ndee85** [comment]
Great, thanks for the detailed explanation and the link.
I was able to retrieve the phpsessid cookie from the header and pass it to the new request header. Did work as it should!
Thank you for your great support.

**Comment by mevdschee** [comment]
Feel free to reopen or file a new issue in case you have further questions. Kind regards, Maurits
