### ISSUE TITLE
Javascript error auth0/vanilla.html 

### ISSUE THREAD

**Issue by billiemead** [mevdschee/php-crud-api#662]
Good day,

My Laravel API integration with Auth0 should be setup and working, but I created and new route for an HTML page, copied auth0/vanilla.html to a new file login.html and am getting a Javascript error:

' Uncaught ReferenceError: requestAPI is not defined
    at window.onload (login.html:36)'

The file is live and is at https://highheelheaven.shoes/login.html but I have a duplicate environment here on localhost.

Without giving it all way, could I get a pointer in the right direction to troubleshoot this? I am almost certain it doesn't have to do with my AUTH0 settings. And I see where requestAPI is defined as a function previous to being called by window.onload.... do I need to load Jquery library here?

Kind regards, Billie

**Comment by mevdschee** [comment]
Hi Billie,

I think it is case sensitivity in the function name 'requestApi' is not 'requestAPI' .. 

I hope this helps. Kind regards, Maurits

**Comment by billiemead** [comment]
That did it my Maurits. Thank you. Not the first time I have been tripped up by case differences.

Just an FYI, I grabbed the login form form here and it looks like there is a case difference on line [10](https://github.com/mevdschee/php-crud-api/blob/cfc7cf8bc5e55c76f4dd230461118c62cf3ea735/examples/clients/auth0/vanilla.html#L10)

So following these [instructions](https://github.com/mevdschee/php-crud-api#configure-and-test-jwt-authentication-with-auth0):  **Configure and test JWT authentication with Auth0**

I set up the **auth0** app and API and these are a few of my variable strings:

```
authUrl domain: https://highheelheaven.auth0.com/authorize
client ID: ***********************************
callback URL: https://highheelheaven.shoes/login.html
API audience: https://highheelheaven.shoes/api
allowed web origins: https://highheelheaven.auth0.com
```
Also I configured the jwtAuth.secrets with **public certificate** using the \n line breaks.

Here is the **php-crud-api** config I am using for testing: 

```
        'driver' => 'mysql',
        'address' => 'localhost',
        'port' => '3306',
	'username' => 'root',
        'password' => '************************',
        'database' => 'hhhproddb',
        'basePath' => '/api',
        'debug' => true,
	'middlewares' => 'cors,jwtAuth',
	'cors.allowedOrigins' => '*',
        'cors.allowHeaders' => 'X-Authorization,Content-Type',
	'cors.allowMethods' => 'OPTIONS, GET, PUT, POST, DELETE, PATCH',
	'jwtAuth.secrets' => "-----BEGIN CERTIFICATE-----\n************************"
```
[highheelheaven.shoes/login.html](https://highheelheaven.shoes/login.html)

Results are that I am getting this error in the console, which I will research with auth0 

```
GET https://highheelheaven.auth0.com/user/ssodata 404

There was an error fetching the SSO data.
This is expected - and not a problem - if the tenant has Seamless SSO enabled. If the tenant
doesn't have Seamless SSO enabled, this could simply mean that there was a problem with the
network. But, if a "Origin" error has been logged before this warning, please add
"https://highheelheaven.auth0.com" to the "Allowed Web Origins" list in the Auth0 dashboard.
```
But before I go too much further, I wanted to ask if going this route with auth0 will query and authorize against the users in the Laravel MySQL user table? I dont want to have to force customers to create new login credentials for the mobile app so I assume the plan with going this way is that auth0 will be the login provider regardless if the user originates from the website, PWA or native mobile app?

I have been reading a tutorial that covers adding JWT tokens to Laravel with the tymon/jwt-auth package and creating/updating controllers with new functions for login, registration, authorization etc. It does not include the use of auth0 so what do you think of going this route and would the integration be done using **php-crud-api** middleware?

There is a stunning amount of information out there regarding login/registration/authorization and while it can be overwhelming and am really getting a good primary education on the subject.

Thank you again Maurits. The USA is starting to slowly come back to life and I hope you and yours are staying healthy and safe!

Cheers, Billie

**Comment by mevdschee** [comment]
>Just an FYI, I grabbed the login form form here and it looks like there is a case difference on line 10

Thank you, you have found a bug! I've fixed it in master.

>auth0 will query and authorize against the users in the Laravel MySQL user table?

No it will not. If that is what you want then you need protect the API with Laravel and let Laravel authenticate and authorize using the PHP-CRUD-API authorization middleware, reading the Laravel set identity.

>There is a stunning amount of information out there regarding login/registration/authorization

It is a difficult topic and I'm also not aware of all best practices, always learning!

>I hope you and yours are staying healthy and safe!

Thank you. The Netherlands are also slowly starting up again. I hope you and your family are also staying safe and healthy.

Kindest regards, Maurits

**Comment by billiemead** [comment]
Thank you Maurits!
