### ISSUE TITLE
Missing case in validateType

### ISSUE THREAD

**Issue by resident0** [mevdschee/php-crud-api#663]
Version 2.9.2

In the test of non-string values in the validateType function the type 'decimal' is not accounted for causing decimal values to always fail validation.

On a side note, I don't receive the message with a 422 response only the code. I don't know if that's a problem with my server or the way the code is sent.

**Comment by mevdschee** [comment]
>causing decimal values to always fail validation.

Causing floats to fail the decimal validation, right? Well.. technically they should, shouldn't they? Maybe that is too strict? What do you think?

>I don't receive the message with a 422 response only the code

What status code do you get instead of 422?

**Comment by resident0** [comment]
The column type is decimal, which is not tested for in the function, the value is either float or int.

The response I get is simply "The requested URL returned error: 422". Nothing further.

**Comment by mevdschee** [comment]
>The response I get is simply "The requested URL returned error: 422". Nothing further.

Is that what the browser shows you or is that the raw response (in postman or curl)?

**Comment by mevdschee** [comment]
>The column type is decimal, (...) , the value is either float or int.

And in your opinion a float or int is a valid decimal? I can see why you feel it should be accepted.

**Comment by resident0** [comment]
> Is that what the browser shows you or is that the raw response (in postman or curl)?

It is the result of ` curl_error() ` after ` curl_exec() ` returns false.

**Comment by mevdschee** [comment]
If you want an `curl_error` for a non 200 response, you may have to set:

    curl_setopt($ch,CURLOPT_FAILONERROR,true);

As per the documentation: https://www.php.net/manual/en/function.curl-error.php

**Comment by resident0** [comment]
> And in your opinion a float or int is a valid decimal? I can see why you feel it should be accepted.

I do value validation prior to submitting data. In situations where I'm not using the api mariadb accepts both floats and ints as valid decimal and dose a conversion behind the scenes.

> If you want an curl_error for a non 200 response, you may have to set:...

I have that option turned on, yes.

**Comment by resident0** [comment]
In the validation middleware there is this:
`php
  case 'float':

  case 'double':

      if (!is_float($value) && !is_int($value)) {

         return 'invalid float';
      
       }

     break; `

I think that a decimal falls into the same category.

**Comment by mevdschee** [comment]
>mariadb accepts both floats and ints as valid decimal

Many databases are quite relaxed in converting anything you throw at them silently. The added value of this middleware is that it is actually more strict than the underlying database(s) and gives an error related to the field.

>I think that a decimal falls into the same category.

I am not sure about that as a float is not a decimal. I added a feature request for this.

**Comment by resident0** [comment]
> I am not sure about that as a float is not a decimal. I added a feature request for this.

I see what you mean. In the sanitation middleware there is strict testing on the decimal values based on the column settings. Perhaps the same test could apply for validation as well?

**Comment by mevdschee** [comment]
>In the sanitation middleware there is strict testing on the decimal values based on the column settings.

The sanitation middleware is designed to be more relaxed and explicitly accept a wide range of values. It in fact does solve your problem, but only if you load it *before* the validation middleware.

**Comment by resident0** [comment]
Sorry to take so long in responding, I was called away from the office.

I've double checked and I am indeed loading sanitation before validation however, when I call a logging function in both sanitation.handler and validation.handler only validation.handler is called. If I disable validation then sanitation executes.

Regardless of how the 'decimal' type is validated the fact that there is not currently a validation test for the type in the "check non-string types" section of the function means that the default ` 'invalid ' . $column->getType(); ` is always returned and no data targeted at 'decimal' type fields can be entered.

**Comment by resident0** [comment]
>  If I disable validation then sanitation executes.

That isn't quite right. If no data fails validation then sanitation executes.

**Comment by mevdschee** [comment]
Are you sure the order is correct? Can you compare the middlewares config string?

    'middlewares' => 'xml,cors,reconnect,dbAuth,jwtAuth,basicAuth,authorization,sanitation,validation,ipAddress,multiTenancy,pageLimits,joinLimits,customization',

That is mine from here:

https://github.com/mevdschee/php-crud-api/blob/master/tests/config/base.php#L7

**Comment by resident0** [comment]
You are correct, I was looking at the order in which I defined the function rather than the order of the property. No both callbacks are executed, unfortunately that did not change the failure of validation.

**Comment by mevdschee** [comment]
I would love to reproduce the behavior you are seeing, but I'm afraid I have too little information to do so. What are your settings for the validation and sanitation middlewares? Can you see the difference between your situation and the test case with the float that I linked?

**Comment by mevdschee** [comment]
>Now both callbacks are executed

Can you step through them? The sanitation should change the float value into a decimal string and then the validation should accept it.

**Comment by resident0** [comment]
The decimal type is indeed converted to a string by sanitizer and is passing validation. All other values I'm submitting also pass validation however I'm still getting a 422 response when posting data. This leads me to believe that the problem must be in my validation.handler even though there was no problem there in previous versions. I will update when I've tracked down the issue. Thank you for all your help today.

**Comment by mevdschee** [comment]
>I'm still getting a 422 response when posting data

Did you read the body/content of the response? It should contain some extra information.

> Thank you for all your help today.

Thank you for using the software and sharing your experience. Kind regards, Maurits

**Comment by resident0** [comment]
Just to verify, there was indeed a problem with my validation handler. A tinyint field was being tested as numeric rather than boolean. Having fixed that the latest version is working very well. Thank you for all the work you do here.
