### ISSUE TITLE
Check if user is logged in via Javascript (Vue.js)

### ISSUE THREAD

**Issue by ndee85** [mevdschee/php-crud-api#665]
Hi,
I am running authentication via dbAuth. Everything works fine. When sending credentials to the login endpoint I get a 200 response. Sending get requests works then too.

But is there a way to check from javascript if I have a valid connection and the session is still healthy? Based on that information I would like display some further information. Or when reloading the page I need to know if the connection is still valid. 

As far as I understand it, the session is stored as cookie. But I am not able to access the cookie. Reloading the page also makes the cookie not present anymore. When trying to read PHPSESSID I always get undefined.

Or do I need to send a request and see if I get a response 200 to know?

Would be great if you could give some advice what the best practice would be here.

**Comment by ndee85** [comment]
Small update. I got it working, but I am really not sure if this is a hacked way or not.

When I am logging in the first time, I store the database userID in a cookie. I then have a method checkIfLoggedIn. Which takes the userID and tries to get the userdata via the given ID. If the server sends back that I have still access, I know that the connection is still valid. Otherwise I know I need to reconnect via the login form.

Would appreciate to hear your thoughts. I this is a way I solved the problem dirty/hacky, maybe I have missed something in the api which makes this process cleaner?

**Comment by billiemead** [comment]
> When I am logging in the first time, I store the database userID in a cookie. I then have a method checkIfLoggedIn. Which takes the userID and tries to get the userdata via the given ID.

Hello... while you waiting to hear back from Maurits, did you see these topics? I just went through this myself last week.

[Authentication](https://github.com/mevdschee/php-crud-api#authentication)

[Database Authentication](https://github.com/mevdschee/php-crud-api#database-authentication)

Specifically:
> A user can be logged in by sending it's username and password to the login endpoint (in JSON format). The authenticated user (with all it's properties) will be stored in the $_SESSION['user'] variable.

**Comment by mevdschee** [comment]
>But is there a way to check from javascript if I have a valid connection and the session is still healthy? 

Well, if you get back a 403 instead of a 200 then your session is no longer healthy.

>Which takes the userID and tries to get the userdata via the given ID

Sounds like a good idea.

>Would appreciate to hear your thoughts.

I think you should (always) redirect to the login page on a 403 (forbidden).

There is not much more to it.

**Comment by ndee85** [comment]
Great. Thanks for the input.
Good to know I was on the right track. Everything now works as it should. So, pretty happy that the first hurdle is taken!

Really appreciate you and billimead took the time to answer!
