### ISSUE TITLE
Data Integrity Violation

### ISSUE THREAD

**Issue by mingsai** [mevdschee/php-crud-api#666]
> Note: This example contains Chinese text and a payload of nested JSON. The payload had to be encoded as a string before being passed on to the API. I found that using the flutter http package one has to use a workaround to decode the characters properly (https://github.com/dart-lang/http/issues/243). The alternative is to use the dio package which encodes everything as utf-8 properly. When decoding the get request, one has to remember to also decode the nested json separately.

Fix for others having this issue:

Flutter has a new network profiler in the Dart tools. Using this I was able to see that an error returned that Field payload does not have a default value. 

**Solution:**
Add a default NULL value to the payload field and with that inserts are now working.
My payload is a json field so I had to jsonEncode(payload) before adding it to the post (in my toJson method)
Also found that I could simply wrap the entire jsonEncode(post) with single quotes 
'$jsonString' without escaping the quotes in the use case below (code)

```
CREATE TABLE `posts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `payload` json DEFAULT NULL,
  `donorid` char(36) DEFAULT NULL,
  `categories` varchar(25) DEFAULT NULL,
  `srclang` int(11) DEFAULT NULL,
  `votes` int(11) DEFAULT NULL,
  `datecreated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `datemodified` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;
```

Current Error
flutter: '{"payload":{"normal":"王先生","phonetic":"Wáng xiān shēng","translation":"Mister Wong"},"categories":"testing"}'
**flutter: {"code":1010,"message":"Data integrity violation"}**

**UPDATES**
Adjusting the post to enforce a single quote surrounding the json encoded string delivers the following error message:

code change >>> `body: '\'$jsonString\'')`
produces:
flutter: {"code":1010,"message":"Data integrity violation"}
btw:
Same thing if I place double quotes here...

??? Does API correctly forward a JSON object to a JSON field?

Original Error
Object of class stdClass could not be converted to string in ... on line 5580
**API Error - <b>Catchable fatal error</b>:  Object of class stdClass could not be converted to string in <b>/data/.../api/index.php</b> on line <b>5580</b><br />**

Environment:
Hosting the API script at a website and connect to a Google MySQL instance. 
Attempting the post from a Flutter application (iOS Sim & Device)
Noteworthy - This version of MySQL (57.x) supports JSON column type and I've confirmed that I can insert the JSON payload using the Sequel Pro tool.

Table Structure
CREATE TABLE `posts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `payload` json NOT NULL,
  `donorid` char(36) DEFAULT NULL,
  `categories` varchar(25) DEFAULT NULL,
  `srclang` int(11) DEFAULT NULL,
  `votes` int(11) DEFAULT NULL,
  `datecreated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `datemodified` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

The Dart code:
import 'dart:convert';

import 'package:http/http.dart' as http;

createPost(Map<String, dynamic> content) {
    var jsonString = jsonEncode(content);
    print('encoded json string $jsonString');
    http
        .post(
            'http://.../api.php/records/posts',
            headers: <String, String>{
              'Content-Type': 'application/json; charset=UTF-8', //;
            },
            body: jsonString)
        .then((value) {
      print(value.body);
    }).catchError(handlePostingError);
  }

  handlePostingError(dynamic response) {
    print('httpErrorHandled- $response');
  }

The following are the current test results:

All feedback welcome

Test of php-crud-api file: Attempt to identify correct method of posting to GCP/MySQL instance.

URL: http://.../api.php/records/posts

Verified that behavior is same if the file is renamed: http://.../index.php/records/posts

Confirmed that direct posting of an encoded JSON String works using Sequel Pro (SP) from (outside of the API): e.g. from Flutter produced a json encoded string and verified that I can stick it into the table using SP. 

Note - Double quotes were not a problem in the SP UI

{"id":null,"payload":{"normal":"郭先生","phonetic":"Guō xiān shēng","translation":"Mister Guo"},"donorid":null,"categories":"testing","srclang":8,"votes":null,"datecreated":"2020-05-15T19:20:31.782268","datemodified":"2020-05-15T19:20:31.782265"}

Confirmed that direct posting of unencoded JSON String FAILS when using SP.

 {normal: 郭先生, phonetic: Guō xiān shēng, translation: Mister Guo}, donorid: null, categories: testing, srclang: 8, votes: null, datecreated: 2020-05-15T19:20:31.782268, datemodified: 2020-05-15T19:20:31.782265}
 
 Confirmed the IP address of the source website hosting the API: ccc.xy.xxz.xab
 
 Confirm the source website address is on list of authorized access to connect to the GCP/MySQL instance. 
 
 
 Note - Future.catchError argument must be dynamic or one gets the following error: 
 The following ArgumentError was thrown while handling a gesture:
 Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a a valid result: Closure: (Response) => dynamic from Function 'handlePostingError':.
 
 API Error - <b>Catchable fatal error</b>:  Object of class stdClass could not be converted to string in <b>/data/.../api/index.php</b> on line <b>5580</b><br />
 
 Note - Similar error observed on this reported issue - https://github.com/mevdschee/php-crud-api/issues/630
 
 Headers monitored in Flutter Dev Tools seem correct - 200 received
 
 Connection to SQL monitored from different IP address and updated.
 
 SQL Log shows connection but no evidence of submission.

SHOW PROCESSLIST on MySQL client shows the connection from the api host when I initiate a test from the app

**Comment by mingsai** [comment]
I was able to solve the issue by giving my JSON column a default NULL value. See the note for complete details.

**Comment by mevdschee** [comment]
Reopened for investigation.

**Comment by mevdschee** [comment]
Thank you for reporting this issue. You have done some excellent research on this topic.

> This example contains Chinese text and a payload of nested JSON. 

I don't think Chinese characters are relevant here, only nested JSON is.

>The payload had to be encoded as a string before being passed on to the API. 

Yes, just as data of any other database type that has no mapping on a JSON type, such as a date.

>I found that using the flutter http package one has to use a workaround to decode the characters properly (dart-lang/http#243).

I added the charset to the content-type reponse header. This will solve the bug. Thank you.

>When decoding the get request, one has to remember to also decode the nested json separately.

This will still be needed, as (in v2 of the code) JSON types are represented on in- and output as strings and not as objects. I added a feature request for the expected (old) behavior, see: #667

Kind regards, Maurits

**Comment by mingsai** [comment]
Maurits,

Thanks for the fast reply. Just want to share that the bug for the problematic Chinese text did not occur in browsers only when I tried to pull from within the flutter code. I will test this at some point today and update the post with results.

**Comment by mevdschee** [comment]
>It could very well be something related to the dart library rather than the API.

Yes, I think it has to do with flutter falling back to latin1 unless the character set is defined. JSON has by definition a UTF-8 character set, but I didn't specify this in the 'Content-Type' header in the response. Now in stead of returning:

    Content-Type: application/json

I return:

    Content-Type: application/json; charset=utf-8

Which is more correct. I released "v2.9.3 Better Content-Type" with this improved behavior.

**Comment by mevdschee** [comment]
With the bug fixed and the feature request present I will now close this issue. Thank you for your contribution and helping make this software better!

**Comment by mingsai** [comment]
@mevdschee - Just tested this again with the new feature in place and I am getting a server error 500. With all other things being equal - it looks like the change has broken the flow of data on the application side. Browser output remains the same. When I revert to the pre-updated file everything works fine.

**Comment by mevdschee** [comment]
Oh, my.. I may have created a buggy version. Can you help me by enabling the "debug" parameter and post the 500 response headers?

**Comment by mevdschee** [comment]
>it looks like the change has broken the flow of data on the application

Well the application should now receive utf-8 encoded characters, so treating them as latin1 would be wrong, is that the case?

**Comment by mingsai** [comment]
No, its not you its me... Thanks for mentioning the debug config settings. I have now reset the config for my setup and I am receiving data. User error... smh...

**Comment by mevdschee** [comment]
No problem, I'm glad we both do thorough testing. This way we prevent bugs from slipping through.
