### ISSUE TITLE
Support database JSON types in v2

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#667]
In v1 of PHP-CRUD-API JSON database types where represented as objects, not as strings. In v2 they are represented as strings (containing JSON). This is a feature request to bring the old behavior back.

See #176 and #723

**Comment by mevdschee** [comment]
SQL Server has no metadata on JSON content in columns, see: https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-ver15

**Comment by cooperdk** [comment]
In MySQL/MariaDB, you can query the column type by:

SELECT DATA_TYPE from INFORMATION_SCHEMA.COLUMNS where table_schema = '<db>' and table_name = '<table>' and column_name = '<column>'

and then determine that if it is JSON, then output unquoted/unescaped.

I don't know how many PHP users actually use MSSQL.
But for db types where you cannot query a column type, as you mention, you could add an identifier, but you might also add a config value to specify any JSON tables/fields?

**Comment by mevdschee** [comment]
>but you might also add a config value to specify any JSON tables/fields?

That is indeed another good option.

**Comment by mevdschee** [comment]
Another option would be to write middleware to do the conversion for specific (configured) fields.

**Comment by cooperdk** [comment]
Nice to know that I can think of something useful. Unfortunately, I have no knowledge of Laravel and my php is getting rusty so I probably wouldn't be the right one to do this...

**Comment by mevdschee** [comment]
Minimum versions for JSON support:

PostgreSQL: 9.3 (2013-09-09) (using JSONB)
SQL Server: 2012 (2012-04-02) (only XML storage)
MySQL: 5.7.9 (2015-10-21)
MariaDB: 10.2 (2017-05-23)

In Ubuntu the following are provided:

20.04: MySQL 8.0 & MariaDB 10.3 & PostgreSQL 12.2
18.04: MySQL 5.7 & MariaDB 10.1 & PostgreSQL 10.4
16.04: MySQL 5.7 & MariaDB 10.0 & PostgreSQL 9.5

In Debian the following are provided:

Debian 10 ("jessie"): MariaDB 10.3 & PostgreSQL 11.4
Debian 9 ("jessie"): MariaDB 10.1 & PostgreSQL 9.6

These are available through docker setups.

**Comment by cooperdk** [comment]
The Debian information is based on the fact that you cannot install newer versions of MariaDB on those versions unless you do so manually. I have MariaDB 10.5 on Debian 9 and the JSON field type is there and working.

**Comment by mevdschee** [comment]
>The Debian information is based on the fact that you cannot install newer versions of MariaDB on those versions unless you do so manually.

Indeed, good observation.

**Comment by mevdschee** [comment]
Maybe we can support JSON in SQL server with an "alias data type or a user-defined type" as described in the "CREATE TYPE (Transact-SQL)" documentation here:

https://docs.microsoft.com/en-us/sql/t-sql/statements/create-type-transact-sql?view=sql-server-ver15

In a way the other implementations do nothing more than store the JSON in a large string anyway (no filter support).

**Comment by mevdschee** [comment]
I have experimented a bit with SQL Server.

To create the alias data type we can run:

    IF TYPE_ID('json') IS NULL CREATE TYPE [json] FROM [ntext];

To remove the alias data type:

    DROP TYPE IF EXISTS [json];

This could be part of the test fixture.

**Comment by cooperdk** [comment]
> > The Debian information is based on the fact that you cannot install newer versions of MariaDB on those versions unless you do so manually.
> 
> Indeed, good observation.

Yup, could actually provide a Docker image with the required versions. I don't use Docker myself;  I know how to build the images. I'm sure someone would find it useful.

**Comment by mevdschee** [comment]
> Yup, could actually provide a Docker image with the required versions.

It is there: https://hub.docker.com/repository/docker/mevdschee/php-crud-api

**Comment by cooperdk** [comment]
> It is there: https://hub.docker.com/repository/docker/mevdschee/php-crud-api

Great, I knew that you offered a Docker version, but what OS is that based on, and what if you require a specific OS/version/web server?

I know that is usually not necessary when you consider what the Docker team says; Docker is OS independent and doesn't rely on an OS to function; in my opinion that is not entirely correct, since a base OS image is installed for each app container if it's not already in the pool of local images. When I test my Python based system and have a clean Docker directory, a number of images and containers are installed, one of them being the base OS.

I have two OS images, a Debian 9 and a Windows one, in my Docker data dir. The Debian one comes from the Dockerfile line:

FROM python:3.7.7-slim which installs an image with Debian Buster.

This is not a necessity and not according to the Docker mentality. But some people rely on very specific software.

**Comment by mevdschee** [comment]
>This is not a necessity and not according to the Docker mentality. But some people rely on very specific software.

I also use docker to quickly test the different OS configurations, as you can see here:

https://github.com/mevdschee/php-crud-api/tree/master/docker

**Comment by mevdschee** [comment]
I see another problem with the JSON datatype and support in MariaDB: In MariaDB the JSON data type is an alias for the LONGTEXT data type. I've not found a way (yet) to detect the specified (JSON) type from the INFORMATION_SCHEMA.

**Comment by mevdschee** [comment]
The "json" middleware is added in v2.11.0

**Comment by cooperdk** [comment]
This is great! Thanks and I can verify it works on my version of MariaDB (10.5.8)
