### ISSUE TITLE
Auth using an application API Key rather than user/login

### ISSUE THREAD

**Issue by mingsai** [mevdschee/php-crud-api#668]
Would it be possible to simply authorize access by posting an application key? The purpose would be to allow limited operations (not delete) in a secure way without setting up a users table. I guess I could also do a dbAuth here as well but an app token of some kind might be better. Am I missing something obvious? BTW - Could you give a brief description of the authentication flow assuming I enable a users  table? I have questions on whether I need to make two calls to validate the user before any other calls and what that table structure ought to look like. Is there additional change to the api.php required, etc? I have read the two paragraphs on dbAuth but I'd like to be sure.

**Comment by mevdschee** [comment]
>Am I missing something obvious?

You can use 'basicAuth' for a applicatio key. You may have to implement the user/password check in a handler. You can fix the username to "apikey" or something.

Or you can use 'jwtAuth' for token based access, which is better explained at: https://jwt.io/

>Could you give a brief description of the authentication flow assuming I enable a users table?

- Post a username password to the "/login" endpoint, receive a "set-cookie" header.
- Do your requests with the relevant cookie header added (browsers do this automatically).
- Post to the "/logout" endpoint when done.

Does that help?

**Comment by mingsai** [comment]
I think that perhaps the best path forward is:

1) Lookup an app apikey for an initial validation
2) Assuming 1 is true then Lookup a user/pass to further validate a user

I am reading through the documentation again on how to further constrain user authorization and access to specific tables. I'd like to ensure that I can place data limits on the calls made.

I am guessing that I can simply post to the user table using an (admin or app/apikey) account to create new user logins using the TreeQL methods I have used to create posts? I think this two step method might be best if I do not want outside parties to make frivolous calls to the db or to make their own logins if they are not within the domain of the application.

Would I, submit the un-hashed password/username during a create operation on the logins table? The API would hash the password at that point?

BTW - Thanks for the help and the API.

**Comment by mevdschee** [comment]
> I'd like to ensure that I can place data limits on the calls made.

You can use and combine (or even adjust) the various middlewares.

>I think this two step method might be best if I do not want outside parties to make frivolous c

A single apikey, token or username/password seems enough to me.

> Would I, submit the un-hashed password/username during a create operation on the logins table?

No the password should be hashed.

>Thanks for the help and the API.

You are welcome, enjoy the software!

**Comment by mingsai** [comment]
Just had a quick follow-up after observing the following:

Inside my Config, I've added:

```
'middlewares' => 'dbAuth,authorization',
'authorization.tableHandler' => function ($operation, $tableName) {
    return $tableName != 'secret-table-name';
},'dbAuth.usersTable' => 'secret-table-name','dbAuth.mode' => 'required',

```   
I also setup my secret-table-name for users pre your reference link
I have been able to confirm that I can post an encrypted username/password to my database.
I was not anticipating seeing my encrypted password appear in the users table without being further hashed by the API. I thought it would use some PHP hash command but the password is using my hash formula when the data is at rest on the table.

Is this normal behavior?

I then attempt to post my uname/pwd to the login endpoint and I see two things:
In my Response Header:
I can see that I get a PHPSESSID and a cookie
I also get 401 Unauthorized

Right now I am testing using two pages (one with the dbAuth configured and the other without). I am about to look into how that cookie/session id ought to be used but I thought I ought to share where I am in case my configuration is missing anything.

Cheers and thanks again.

**Comment by mevdschee** [comment]
> Is this normal behavior?

You can use a columnHandler to deny read access to the column.

> I also get 401 Unauthorized

The endpoint is at "/login", are you sure you use the correct path?

>in case my configuration is missing anything.

I don't see any obvious omissions

**Comment by mingsai** [comment]
@mevdschee 

I have implemented a few of the handlers to test and find your instructions quite useful (after my deep dive into the codebase). 

I have a scenario where I am allowing only my admin user to programmatically create other user accounts. I am testing with a set of forms to ensure that I remove issues related to my app.
So far, I login to the admin account and then attempt to post to the users table. 

Results:
test1 : abc.. (pwd) are created on the database

Expected Results:
test1 : $2y... password

The password is not being hashed before it is inserted into the database. I took a look at the readPasswords function and apparently no php hash is being applied to the password. I want to hash it with the PHP code so that it can be verified later.

Can I intercept the passwords and hash them using one of the handlers? If so, any tips would be appreciated.

BTW:

Have been successful at getting the correct cookie behavior using the flutter package (https://pub.dev/packages/requests).

**Comment by mevdschee** [comment]
>Can I intercept the passwords and hash them using one of the handlers

Yes, you can. Use the customization middleware and the beforeHandler.

**Comment by mingsai** [comment]
I was able to do this using the sanitation handler. On the beforeHandler I couldn't figure out where to place the hashed value so that it would change the password before data entry. A lifecycle of the API flow might be helpful. I found this answer over in #612 - I will be mining the other issues for more information on how-to topics. The tips from the issues might be a great fit for the wiki. You are doing tremendous work, please let me know if you need any help updating the wiki.

```
'sanitation.handler' => function ($operation, $tableName, $column, $value) {
          return ($tableName == 'users' && $column['name'] == 'password')?password_hash($value,PASSWORD_DEFAULT):$value;
       },
```

**Comment by mevdschee** [comment]
>You are doing tremendous work, please let me know if you need any help updating the wiki.

Thank you for your kind words. I would be thankful for any howto's and/or wiki articles.
