### ISSUE TITLE
Stopped working after changing database

### ISSUE THREAD

**Issue by j2l** [mevdschee/php-crud-api#669]
First of all, thank you very much! Great project!

I get a weird behavior, using MariaDB and PHP 7.2
At first, I got code:1000, then I created a `pippo` table in a `records` database, following another past issue on this project, and it worked, I got the JSON object by viisting http://0.0.0.0/api.php/records/pippo/
Then I changed api.php database (same user) to another existing  database and it failed.
Then I got back to records, and it failed. First it threw 9999, with debug true, I could see the error code was 2002 But I didn't noted it.
And now, I get code:1000
This container is running another php stuff (tikiwiki test). I wonder if it's related.
I only changed api.php credentials and added your code from another issue:
```
if (!preg_match('|^/([^/]*)(/.*)|', $_SERVER['PATH_INFO'], $matches)) {
  die('database not found');
}
$database = $matches[1];
$_SERVER['PATH_INFO'] = $matches[2];
```
I restarted the container without luck.
pippo table is present. Adminer is on it (I have issue with your other admin script, so adminer to the rescue):
![adminer](https://user-images.githubusercontent.com/65325/82200458-521df980-98ff-11ea-9c73-b513f43087cc.png)
I'm not php saavy. Please bear with me :) Thank you!

**Comment by mevdschee** [comment]
> I added your code from another issue:

When you apply that change, you need to adjust the url accordingly:

    /api.php/db/records/pippo/

Otherwise you get a 1000 error.

**Comment by j2l** [comment]
Thank you Maurits. You're fast!
I set the PC on sleep, changed to `http://localhost/api.php/db/records/pippo/` and now I get 9999 again, with the 2002 error (no such file or directory):
![crudapi](https://user-images.githubusercontent.com/65325/82212420-d463e900-9912-11ea-967d-1347b821ecdf.png)

**Comment by j2l** [comment]
I removed your code to get closer to when it was working and I tried within the container:
```
root@d622e0261ba1:/var/www/html# wget http://localhost/api.php/records/pippo/ -O /tmp/pippo
--2020-05-18 12:31:51--  http://localhost/api.php/records/pippo/
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-05-18 12:31:51 ERROR 500: Internal Server Error.

root@d622e0261ba1:/var/www/html# wget http://localhost/api.php/db/records/pippo/ -O /tmp/pippo
--2020-05-18 12:32:15--  http://localhost/api.php/db/records/pippo/
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-18 12:32:15 ERROR 404: Not Found.
```

**Comment by mevdschee** [comment]
It is because you need to change the address from 'localhost' to '127.0.0.1' to force a TCP connection instead of a socket file.

see: https://stackoverflow.com/questions/29695450/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

**Comment by j2l** [comment]
Ok:
```
root@d622e0261ba1:/var/www/html# wget http://127.0.0.1/api.php/records/pippo/ -O /tmp/pippo
--2020-05-18 12:42:16--  http://127.0.0.1/api.php/records/pippo/
Connecting to 127.0.0.1:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-05-18 12:42:16 ERROR 500: Internal Server Error.
```

**Comment by mevdschee** [comment]
can you do a "curl -i" instead of a wget?

**Comment by j2l** [comment]
From the apache log:
```
{"log":"[Mon May 18 12:43:09.793764 2020] [authz_core:error] [pid 32] [client 127.0.0.1:43452] AH01630: client denied by server configuration: /var/www/html/db/records\n","stream":"stderr","time":"2020-05-18T12:43:09.793817934Z"}
{"log":"127.0.0.1 - - [18/May/2020:12:43:09 +0000] \"GET /api.php/db/records/pippo/ HTTP/1.1\" 404 310 \"-\" \"Wget/1.20.1 (linux-gnu)\"\n","stream":"stdout","time":"2020-05-18T12:43:09.814195642Z"}

```

**Comment by j2l** [comment]
Sure! Thank you for helping me
```
curl -i http://127.0.0.1/api.php/db/records/pippo/ -O /tmp/pippo
curl: Remote file name has no length!
curl: try 'curl --help' or 'curl --manual' for more information
curl: (3) URL using bad/illegal format or missing URL
```

**Comment by j2l** [comment]
AH01630: client denied by server configuration
I guess it's the .htaccess of the wiki

**Comment by j2l** [comment]
Found a temporary fix.
When I change to `         'address' => '172.26.0.2',` in api.php config (the MariaDB container), it works on the wiki container:
![workingdb](https://user-images.githubusercontent.com/65325/82216321-18f28300-9919-11ea-85f6-6efa40e1822b.png)

It makes sense. But it worked for a brief time without this setting. And Adminer finds its way between containers to connect dynamically to the MariaDB container.
What could be done to help api.php to resolve the container ip based on the port?

**Comment by mevdschee** [comment]
> What could be done to help api.php to resolve the container ip based on the port?

If you send the word "localhost" it will connect via a unix socket, don't do that. It is not api.php that has this behavior, but the underlying PDO driver.

see: https://serverfault.com/questions/337818/how-to-force-mysql-to-connect-by-tcp-instead-of-a-unix-socket

**Comment by j2l** [comment]
Thank you for the link. Though, I don't get all the subtleties here.
Does it mean, I must tweak the MariaDB container settings for api.php?
It worked for a brief period with localhost or 0.0.0.0 (I don't remember). Now it must be the real IP on docker network. 
What should I do to make it work and keep the right settings for the wiki?
I wonder how adminer and the wiki seam to work as is.

**Comment by j2l** [comment]
Ok, let's leave the IP thing on the side for now.

I change the database and get code 1000:
`http://0.0.0.0/api.php/tikiwiki21/users_users`
{"code":1000,"message":"Route '\/tikiwiki21\/users_users' not found"}
with
         'address' => '172.26.0.2',
            'database' => 'tikiwiki21',
Apache log:
172.26.0.1 - - [18/May/2020:13:34:11 +0000] "GET /api.php/tikiwiki21/users_users HTTP/1.1" 404 313 "-" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Mobile Safari/537.36"

while it's available for my user on Adminer:
![adminer](https://user-images.githubusercontent.com/65325/82219601-cf586700-991d-11ea-97d6-ae4a73c62575.png)

**Comment by mevdschee** [comment]
you need "records" in the path..

**Comment by j2l** [comment]
{"code":1000,"message":"Route '\/tikiwiki21\/records\/users_users' not found"}

**Comment by mevdschee** [comment]
Did you apply the patch for the variable database names? If you didn't, use:

    http://0.0.0.0/api.php/records/users_users

I hope this helps.

**Comment by j2l** [comment]
Sorry, I don't understand why `records` should be in the path.
As you can see above, I changed  'database' => 'tikiwiki21',

**Comment by mevdschee** [comment]
Did you also remove this?

    if (!preg_match('|^/([^/]*)(/.*)|', $_SERVER['PATH_INFO'], $matches)) {
      die('database not found');
    }
    $database = $matches[1];
    $_SERVER['PATH_INFO'] = $matches[2];

**Comment by j2l** [comment]
Yes

**Comment by j2l** [comment]
Should I put it back and use $database?

**Comment by mevdschee** [comment]
Does it work with records in the path?

**Comment by j2l** [comment]
Ah!
I was confused. I thought it was dynamic and the records database was for testing purpose. I understand.
So using your code and replacing records with

**Comment by mevdschee** [comment]
The word 'records' maps to the 'RecordController' and there are also other controllers that can be enabled.

**Comment by j2l** [comment]
Sorry, posted too fast.
It makes sense to keep the database within the php, not exposing it through GET.
I'll stay with static and use records.

Thank you so much for your help.

**Comment by j2l** [comment]
Now I'll post to the wiki project and will propose your way to get a restful API within tikiwiki :)

**Comment by j2l** [comment]
If you're ok with that.

**Comment by mevdschee** [comment]
>If you're ok with that.

Yes, please.

**Comment by j2l** [comment]
Great!
Now, the IP thing might hit php-crud-admin too, see https://github.com/mevdschee/php-crud-admin/issues/2
And closing this one for now.
