### ISSUE TITLE
Authentication failed for 'JWT'

### ISSUE THREAD

**Issue by mafen** [mevdschee/php-crud-api#670]
"code": 1012,
    "message": "Authentication failed for 'JWT'"

I am getting this problem and i dont know why , I have looked at the different other issues that both closed and open 

vanilla.html
var authUrl = 'https://dev--q.eu.auth0.com/authorize'; // url of auth0 '/authorize' end-point
var clientId = '***************************'; // client id as defined in auth0
var audience = 'https://xxxxxx.no/api.php/'; // api audience as defined in auth0
var url = '/api.php/records/log/';

my config
// file: src/index.php

    $config = new Config([
    
        'driver' => 'mysql',
	'port' => '3306',
        'address' => 'localhost',
        'username' => 'log',
        'password' => '',
        'middlewares' => 'cors, jwtAuth',
        'jwtAuth.secrets' => '-----BEGIN CERTIFICATE-----
MIIDDTCCAfWgAwIBAgIJdaUDcCutHanwMA0GCSqGSIb3DQEBCwUAMCQxIjAgBgNV
BAMTGWRldi0tcS0zOWIwai5ldS5hdXRoMC5jb20wHhcNMjAwNTE2MTYyMTUzWhcN
MzQwMTIzMTYyMTUzWjAkMSIwIAYDVQQDExlkZXYtLXEtMzliMGouZXUuYXV0aDAu
-----END CERTIFICATE-----',
        'database' => 'log',
        'debug' => 'true'
 
Any help is appreciated

**Comment by mafen** [comment]
It records them as successful logins on the auth.0 logs

**Comment by mevdschee** [comment]
'jwtAuth.secrets' should contain '{kid1}:{key1},{kid2}:{key2}' pairs.

**Comment by mafen** [comment]
Do i just put kid 1 or what do i put there?

'jwtAuth.secrets' => '{kid1'}:{-----BEGIN CERTIFICATE-----}

Like ^^?

**Comment by mafen** [comment]
Or do i have to make a string variable with my public key? and put that there like kid : public key like i saw on some other issue posts

**Comment by mevdschee** [comment]
Replace '{kid1}' and '{key1}' with the key id and certificate, so without the accolades.

**Comment by mafen** [comment]
so could you point me to where on auth.0 site i can find key id 

or is it the name of the certificate when you download it

**Comment by mafen** [comment]
I found my key id but it does still not work, so is this the right way to use it 

        'jwtAuth.secrets' => '{xOZhU6jcqPH}:{
MIIDDTCCAfWgAwIBAgIJdaUDcCutHanwMA0GCSqGSIb3DQEBCwUAMCQxIjAgBgNV
7AE+Eb98D29ngdb8ugd0F4n5I9FfP5xELGBzOT4ufQRGUa2wdUk4w9yxrJWM2xvQ
/xgPrYjkC+BSuK40qpY3LQ0=
}',

**Comment by mafen** [comment]
I looked in to using the method https://github.com/mevdschee/php-crud-api/issues/639 but it did nothing

**Comment by mevdschee** [comment]
Try it without accolades, so 'xOZhU6jcqPH' instead of '{xOZhU6jcqPH}'.

**Comment by mafen** [comment]
Yes it worked and I now know another word for brackets, thank you

**Comment by mevdschee** [comment]
Sorry.. it indeed is a bracket.. I'm not native English. A "curly bracket" is what it is called apparently. I'm glad you understood it nevertheless.  I'm glad you figured it out!
