### ISSUE TITLE
Query api sometimes show getString error! 

### ISSUE THREAD

**Issue by Wimjiang** [mevdschee/php-crud-api#677]
Java try to read json response:

at [Source: (String)"<br />
<b>Notice</b>:  Undefined offset: 1 in <b>C:\Tools\Apache24\htdocs\scorpioDatahub.php</b> on line <b>3483</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: Return value of Tqdev\PhpCrudApi\Cache\TempFileCache::getString() must be of the type string, null returned in C:\Tools\Apache24\htdocs\scorpioDatahub.php:3487
Stack trace:
#0 C:\Tools\Apache24\htdocs\scorpioDatahub.php(3516): Tqdev\PhpCrudApi\Cache\TempFileCache-&gt;getString('C:\\Windows\\TEMP...')
#1 C:\Tools\Apache24\htdocs"[truncated 610 chars]; line: 1, column: 2]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: (String)"<br />
<b>Notice</b>:  Undefined offset: 1 in <b>C:\Tools\Apache24\htdocs\scorpioDatahub.php</b> on line <b>3483</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: Return value of Tqdev\PhpCrudApi\Cache\TempFileCache::getString() must be of the type string, null returned in C:\Tools\Apache24\htdocs\scorpioDatahub.php:3487
Stack trace:
#0 C:\Tools\Apache24\htdocs\scorpioDatahub.php(3516): Tqdev\PhpCrudApi\Cache\TempFileCache-&gt;getString('C:\\Windows\\TEMP...'

Apache error log:
PHP Fatal error:  Uncaught TypeError: Return value of Tqdev\\PhpCrudApi\\Cache\\TempFileCache::getString() must be of the type string, null returned in C:\\Tools\\Apache24\\htdocs\\scorpioDatahub.php:3487\nStack trace:\n#0 C:\\Tools\\Apache24\\htdocs\\scorpioDatahub.php(3516): Tqdev\\PhpCrudApi\\Cache\\TempFileCache->getString('C:\\\\Windows\\\\TEMP...')\n#1 C:\\Tools\\Apache24\\htdocs\\scorpioDatahub.php(3421): Tqdev\\PhpCrudApi\\Cache\\TempFileCache->clean('C:\\\\Windows\\\\TEMP...', Array, 32, false)\n#2 C:\\Tools\\Apache24\\htdocs\\scorpioDatahub.php(3249): Tqdev\\PhpCrudApi\\Cache\\TempFileCache->__construct('phpcrudapi-e396...', '')\n#3 C:\\Tools\\Apache24\\htdocs\\scorpioDatahub.php(10069): Tqdev\\PhpCrudApi\\Cache\\CacheFactory::create('TempFile', 'phpcrudapi-e396...', '')\n#4 C:\\Tools\\Apache24\\htdocs\\scorpioDatahub.php(10696): Tqdev\\PhpCrudApi\\Api->__construct(Object(Tqdev\\PhpCrudApi\\Config))\n#5 {main}\n  thrown in C:\\Tools\\Apache24\\htdocs\\scorpioDatahub.php on line 3487

**Comment by mevdschee** [comment]
Good find! I think it is a bug. I can fix this.. please give me a few hours :-)

**Comment by mevdschee** [comment]
It seems that the file contains unexpected content (xml), can you post the contents of the temp file used as cache? It seems it is not json.

**Comment by Wimjiang** [comment]
> Java try to read json response:
> 
> at [Source: (String)"
> 
> Notice: Undefined offset: 1 in C:\Tools\Apache24\htdocs\scorpioDatahub.php on line 3483
> 
> 
> 
> Fatal error: Uncaught TypeError: Return value of Tqdev\PhpCrudApi\Cache\TempFileCache::getString() must be of the type string, null returned in C:\Tools\Apache24\htdocs\scorpioDatahub.php:3487
> Stack trace:
> #0 C:\Tools\Apache24\htdocs\scorpioDatahub.php(3516): Tqdev\PhpCrudApi\Cache\TempFileCache->getString('C:\Windows\TEMP...')
> #1 C:\Tools\Apache24\htdocs"[truncated 610 chars]; line: 1, column: 2]
> com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
> at [Source: (String)"
> 
> Notice: Undefined offset: 1 in C:\Tools\Apache24\htdocs\scorpioDatahub.php on line 3483
> 
> 
> 
> Fatal error: Uncaught TypeError: Return value of Tqdev\PhpCrudApi\Cache\TempFileCache::getString() must be of the type string, null returned in C:\Tools\Apache24\htdocs\scorpioDatahub.php:3487
> Stack trace:
> #0 C:\Tools\Apache24\htdocs\scorpioDatahub.php(3516): Tqdev\PhpCrudApi\Cache\TempFileCache->getString('C:\Windows\TEMP...'
> 
> Apache error log:
> PHP Fatal error: Uncaught TypeError: Return value of Tqdev\PhpCrudApi\Cache\TempFileCache::getString() must be of the type string, null returned in C:\Tools\Apache24\htdocs\scorpioDatahub.php:3487\nStack trace:\n#0 C:\Tools\Apache24\htdocs\scorpioDatahub.php(3516): Tqdev\PhpCrudApi\Cache\TempFileCache->getString('C:\\Windows\\TEMP...')\n#1 C:\Tools\Apache24\htdocs\scorpioDatahub.php(3421): Tqdev\PhpCrudApi\Cache\TempFileCache->clean('C:\\Windows\\TEMP...', Array, 32, false)\n#2 C:\Tools\Apache24\htdocs\scorpioDatahub.php(3249): Tqdev\PhpCrudApi\Cache\TempFileCache->__construct('phpcrudapi-e396...', '')\n#3 C:\Tools\Apache24\htdocs\scorpioDatahub.php(10069): Tqdev\PhpCrudApi\Cache\CacheFactory::create('TempFile', 'phpcrudapi-e396...', '')\n#4 C:\Tools\Apache24\htdocs\scorpioDatahub.php(10696): Tqdev\PhpCrudApi\Api->__construct(Object(Tqdev\PhpCrudApi\Config))\n#5 {main}\n thrown in C:\Tools\Apache24\htdocs\scorpioDatahub.php on line 3487

**Comment by mevdschee** [comment]
I assume you found the cause. I will leave it at that.

**Comment by Wimjiang** [comment]
sorry ~ I closed it by mistakle

I cannot find xml? Could you tell me where to find this file?

**Comment by mevdschee** [comment]
apparently there is a file in "C:\Windows\TEMP" that is used as a cache. Can you share the contents of that file.

**Comment by mevdschee** [comment]
Are you using java for something? It seems that jackson is a java library. How does that error end up in a PHP project?

**Comment by mevdschee** [comment]
I have made a fix ignoring the cache file when it has wrong content. I'm not sure that is going work around the symptoms or fix the problem though..

**Comment by mevdschee** [comment]
What happens when you switch the cache engine to memcache?

**Comment by Wimjiang** [comment]
Hi, I have get code laste version , found error as following log.
And I used java to fetch api.

LOG: 

Java log
Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: (String)"<br />
<b>Warning</b>:  fopen(C:/Tools/phpCache\3685b8b17a33aa0c375c10f9a4f51887): failed to open stream: No such file or directory in <b>C:\Tools\Apache24\htdocs\custom.php</b> on line <b>3459</b><br />
<br />
<b>Warning</b>:  unlink(C:/Tools/phpCache\3685b8b17a33aa0c375c10f9a4f51887): No such file or directory in <b>C:\Tools\Apache24\htdocs\custom.php</b> on line <b>3522</b><br />
{"records":[{"ID":1,"Currency":"**","name":"**","BuyingRate":null,"CashBuyin"[truncated 7222 chars]; line: 1, column: 2]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: (String)"<br />
<b>Warning</b>:  fopen(C:/Tools/phpCache\3685b8b17a33aa0c375c10f9a4f51887): failed to open stream: No such file or directory in <b>C:\Tools\Apache24\htdocs\custom.php</b> on line <b>3459</b><br />
<br />
<b>Warning</b>:  unlink(C:/Tools/phpCache\3685b8b17a33aa0c375c10f9a4f51887): No such file or directory in <b>C:\Tools\Apache24\htdocs\custom.php</b> on line <b>3522</b><br />
{"records":[{"ID":1,"Currency":"**","name":"**","BuyingRate":null,"CashBuyin"[truncated 7222 chars]; line: 1, column: 2]

Apache log:

PHP Warning:  fopen(C:/Tools/phpCache\\3685b8b17a33aa0c375c10f9a4f51887): failed to open stream: No such file or directory in C:\\Tools\\Apache24\\htdocs\\custom.php on line 3459

**Comment by Wimjiang** [comment]
And I have changed the cache path as `C:/Tools/phpCache`

**Comment by mevdschee** [comment]
I think the folder "C:/Tools/phpCache" might not exist.

Also I think there is no '<' in the response, so I don't understand the error message.

**Comment by Wimjiang** [comment]
HI

Our service call api.php by httpClient and got the following response, why it add <br>..</br> before response?

<br />
<b>Warning</b>:  unlink(C:/Tools/phpCache\6ce966980fc830c61e3c2a41924f2610): No such file or directory in <b>C:\Tools\Apache24\htdocs\api.php</b> on line <b>3522</b><br />
{"records":[{"ID":1,"Currency":"**","name":"**","BuyingRate":null,"CashBuyingRate":"18111.320000","SellingRate":null,"CashSellingRate":"223.230000","MiddleRate":"143.150000","ID":null,"CreateDate":"2020-05-25","UpdateDate":"2020-05-25 00:00:05"}]}

**Comment by mevdschee** [comment]
@Wimjiang maybe that is on top of the api.php file, before the '<?php' start tag? Or it is something added by the webserver or a reverse proxy?

**Comment by Wimjiang** [comment]
Hi 
Log is:
`<br />
<b>Warning</b>:  unlink(C:/Tools/phpCache\6ce966980fc830c61e3c2a41924f2610): No such file or directory in <b>C:\Tools\Apache24\htdocs\api.php</b> on line <b>3522</b><br />
{"records":[{"ID":55,"Currency":"**","name":"**","BuyingRate":null,"CashBuyingRate":"18111.320000","SellingRate":null,"CashSellingRate":"223.230000","MiddleRate":"143.150000","ID":null,"CreateDate":"2020-05-25","UpdateDate":"2020-05-25 00:00:05"}]}
`

**Comment by Wimjiang** [comment]
This is the apache response from the php server .

**Comment by mevdschee** [comment]
The "unlink" warning and the line number helped me find the problem, thank you. Can test the latest version (v2.9.5) and see whether or not the issue is resolved?

**Comment by Wimjiang** [comment]
Hi
updated V2.95, 
Log: 
`res:<br />
<b>Parse error</b>:  syntax error, unexpected '$request' (T_VARIABLE), expecting ']' in <b>C:\Tools\Apache24\htdocs\scorpioDatahub.php</b> on line <b>11247</b><br /> `

**Comment by mevdschee** [comment]
There are no syntax errors in the release:

    maurits@maurits-desktop:~/projects/php-crud-api$ php -l api.php 
    No syntax errors detected in api.php

Can you copy/paste that line?

**Comment by Wimjiang** [comment]
Hi 
This is my fault. The latest version(v2.9.5) is fix the bug.
Thank you for your help !

**Comment by Wimjiang** [comment]
Hi mevdschee

this issue reproduced with the latest version(v2.9.5), Could you help me fix this issue~~ thanks!
warrning message as following :

`
at [Source: (String)"<br />
<b>Warning</b>:  fopen(C:\Windows\TEMP\phpcrudapi-e3963778-cache\623ac493259199b598bb537b64af5693): failed to open stream: Permission denied in <b>C:\Tools\Apache24\htdocs\hub.php</b> on line <b>3459</b><br />
{"records":[{"ID":1,"Currency":"AED","CurrencyChineseName":"**","BuyingRate":null,"CashBuyingRate":"**","SellingRate":null,"CashSellingRate":"**","MiddleRate":"**","CreateUserID":null,"CreateDate":"**","UpdateDate":"**""[truncated 3 chars]; line: 1, column: 2]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<br />
<b>Warning</b>:  fopen(C:\Windows\TEMP\phpcrudapi-e3963778-cache\623ac493259199b598bb537b64af5693): failed to open stream: Permission denied in <b>C:\Tools\Apache24\htdocs\hub.php</b> on line <b>3459</b><br />
{"records":[{"ID":1,"Currency":"AED","CurrencyChineseName":"**","BuyingRate":null,"CashBuyingRate":"**","SellingRate":null,"CashSellingRate":"**","MiddleRate":"**","CreateUserID":null,"CreateDate":"**","UpdateDate":"**""[truncated 3 chars]; line: 1, column: 2] 
`

**Comment by mevdschee** [comment]
> fopen(C:\Windows\TEMP\phpcrudapi-e3963778-cache\623ac493259199b598bb537b64af5693): failed to open stream: Permission denied

This means that the folder "C:\Windows\TEMP" does not exist or the file cannot be created due to lack of write permissions.

Does this help you in any way? I'm pretty sure this is related to your environment and the writing to disk.

>What happens when you switch the cache engine to memcache or specify a specific cache path?

This question is still relevant, try this:

>"cacheType": TempFile, Redis, Memcache, Memcached or NoCache (TempFile)

    "cacheType" => 'NoCache',

And see whether or not that solves your problem.

**Comment by mevdschee** [comment]
Do you have any update?

**Comment by Wimjiang** [comment]
So sorry~~, I forgot to close this issues~
Set `"cacheType" => "NoCache",` can fix this issues,
thank you~
