### ISSUE TITLE
TableHandler and POST operation on given tableName is failing

### ISSUE THREAD

**Issue by NorthFred** [mevdschee/php-crud-api#679]
I'm trying to implement a tableHandler with following simplified code:

```
        'authorization.tableHandler' => function ($operation, $tableName) {
			if ($operation == 'create' && $tableName == 'youCanPostHere') {
				return $tableName;
			}
        }
```

Any other operations that I use ('read', 'list', 'update', 'delete') are properly handled on the given table, but whenever I use 'create', I bump into a 500 Internal Server error.  What is happening here?

**Comment by NorthFred** [comment]
Facepalm.... Missing privileges.

**Comment by mevdschee** [comment]
Recognizable :-) Glad you resolved the issue. Enjoy the software!
