### ISSUE TITLE
generated API empty

### ISSUE THREAD

**Issue by lukemt** [mevdschee/php-crud-api#68]
The connection to database works. But the api is empty.

Output api.php:
`{"swagger":"2.0","info":{"title":"cRM_Solution_ITproject","description":"API generated with [PHP_CRUD_API](https://github.com/mevdschee/php-crud-api)","version":"1.0.0"},"host":"localhost","basePath":"/data/php-crud-api-master/api.php","schemes":["http"],"consumes":["application/json"],"produces":["application/json"],"tags":[],"paths":{}}`

Configuration:
```php
// For Microsoft SQL Server 2012 use:

 $api = new PHP_CRUD_API(array(
	 'dbengine'=>'SQLServer',
	 'hostname'=>'Sam\SQLdb',
	 'username'=>'xx',
	 'password'=>'xxx',
	 'database'=>'xxxt',
	 'charset'=>'UTF-8
 ));
 $api->executeCommand();
```
Any idea?

**Comment by mevdschee** [comment]
Are your tables in the default schema? Do you have enough permissions to view them?

**Comment by lukemt** [comment]
Thank you for repliing. Unfortunately, I'll not be at work until mid next week. I'll give more info then.

**Comment by mevdschee** [comment]
Any feedback?

**Comment by lukemt** [comment]
Yes.
I printed out the query of api.php, which was something like that:
```sql
USE cRM_Solution_ITproject
SELECT "TABLE_NAME" FROM "INFORMATION_SCHEMA"."TABLES" 
    WHERE "TABLE_CATALOG" = 'cRM_Solution_ITproject';
```
when i query this with the Microsoft DBMS i do get results.
however i do not know if api.php receives them.
I am not sure about the privileges, my colleague said i got admin-privileges.
I can't answer the question about the default schema because i don't have any experience with the information_schema table and don't know how to differentiate. 
I hope this info helps a bit.

**Comment by lukemt** [comment]
what would you do or try next?

**Comment by mevdschee** [comment]
Try to save this file as "test.php" and execute it:

    <?php
    $connectionInfo = array();
    $connectionInfo['UID']='xx'; // fill username here
    $connectionInfo['PWD']='xxx'; // fill password here
    $connectionInfo['Database']='cRM_Solution_ITproject';
    $connectionInfo['CharacterSet']='UTF-8';
    $conn = sqlsrv_connect( 'Sam\SQLdb', $connectionInfo);
    if (!$conn) {
        die("Connect failed: ".print_r( sqlsrv_errors(), true));
    }
    $stmt = sqlsrv_query($conn, 'SELECT "TABLE_NAME" FROM "INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_CATALOG" = 'cRM_Solution_ITproject';');
    if( $stmt === false ) {
       die( print_r( sqlsrv_errors(), true));
    }
    echo "OK\n";
    sqlsrv_close($conn);

Do not forget to replace username (xx) and password (xxx). Let me know what the output is.

**Comment by lukemt** [comment]
The output is `OK`

**Comment by mevdschee** [comment]
Okay, so no errors. Now replace:

    echo "OK\n";

with:

    while($row = sqlsrv_fetch_array($stmt)) echo implode(',',$row)."\n";

And run the script again. It should show a list of tables.

**Comment by lukemt** [comment]
This works too.

So I just had another look at the sql.txt and the exact query is 
```sql
SELECT
					"TABLE_NAME","TABLE_COMMENT"
				FROM
					"INFORMATION_SCHEMA"."TABLES"
				WHERE
					"TABLE_CATALOG" = ?
```
```array (
  0 => 'cRM_Solution_ITproject',
)```

which means the column TABLE_COMMENT doesn't exist in my schema.
I now commented all the comment stuff in api.php out, and now it works!

**Comment by mevdschee** [comment]
Ah.. you don't have a comment in SQL server? Very good find!

**Comment by mevdschee** [comment]
I fixed it.
