### ISSUE TITLE
Create record does not return primary key if it is a UUID and the table has (another) autoincrement column

### ISSUE THREAD

**Issue by sugu1** [mevdschee/php-crud-api#680]
I have a table that has an UUID as primary key and another column that keeps a key for the sort order with an ordinary index with autoincrement. Instead of returning the primary key, the latest value of the auto increment is returned.
The documentation says:
` it will return the value of the primary key of the newly created record`
So I guess, this is a bug.

**Comment by mevdschee** [comment]
Thank you for reporting this issue. It is very interesting! I don't have a test case yet for the scenario you describe. One question: do you specify the UUID on record creation or is it generated server side with a trigger?

**Comment by mevdschee** [comment]
Can you share the table create statement for the table with the issue? Or a simplified table create statement in which the issue occurs?

**Comment by mevdschee** [comment]
I'm assuming you are on MySQL, is that true? What version?

**Comment by mevdschee** [comment]
I'm failing to even reproduce table creation:

    Loading '/home/maurits/projects/php-crud-api/tests/fixtures/blog_mysql.sql' failed on statemement #38:
    'CREATE TABLE `kunsthåndværk` (
      `id` varchar(36) NOT NULL,
      `Umlauts ä_ö_ü-COUNT` int(11) NOT NULL,
      `user_id` int(11) NOT NULL,
      `invisible` varchar(36),
      `invisible_id` varchar(36),
      `sort_order` int(11) NOT NULL AUTO_INCREMENT,
      PRIMARY KEY (`id`),
      CONSTRAINT `kunsthåndværk_Umlauts ä_ö_ü-COUNT_fkey` UNIQUE (`Umlauts ä_ö_ü-COUNT`),
      CONSTRAINT `kunsthåndværk_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
      CONSTRAINT `kunsthåndværk_invisible_id_fkey` FOREIGN KEY (`invisible_id`) REFERENCES `invisibles` (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;'
    with error:
    Array
    (
        [0] => 42000
        [1] => 1075
        [2] => Incorrect table definition; there can be only one auto column and it must be defined as a key
    )

Please help me :-)

**Comment by mevdschee** [comment]
I'm using:

    CREATE TABLE `kunsthåndværk` (
      `id` varchar(36) NOT NULL,
      `Umlauts ä_ö_ü-COUNT` int(11) NOT NULL,
      `user_id` int(11) NOT NULL,
      `invisible` varchar(36),
      `invisible_id` varchar(36),
      `sort_order` int(11) NOT NULL AUTO_INCREMENT,
      PRIMARY KEY (`id`),
      CONSTRAINT `kunsthåndværk_Umlauts ä_ö_ü-COUNT_fkey` UNIQUE (`Umlauts ä_ö_ü-COUNT`),
      CONSTRAINT `kunsthåndværk_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
      CONSTRAINT `kunsthåndværk_invisible_id_fkey` FOREIGN KEY (`invisible_id`) REFERENCES `invisibles` (`id`),
      UNIQUE (`sort_order`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

Is that what your table looks like?

**Comment by mevdschee** [comment]
The test case still succeeds:

    maurits@maurits-desktop:~/projects/php-crud-api$ mysql --version
    mysql  Ver 14.14 Distrib 5.7.30, for Linux (x86_64) using  EditLine wrapper
    maurits@maurits-desktop:~/projects/php-crud-api$ php test.php mysql 001 064
    mysql: 1 tests ran in 43 ms, 0 skipped, 0 failed

What are you seeing?

**Comment by sugu1** [comment]
Thanks for replying so fast. Actually yes, I am adding the UUID via trigger (custom format), so I guess this is causing the issue.

**Comment by mevdschee** [comment]
Indeed, so it is not a bug, still it is an interesting scenario.

I was thinking: If you use MySQL and you can map your non-deterministic part (random? value) of the UUID to a bigint, then you may call `LAST_INSERT_ID` with that value: `LAST_INSERT_ID(value)` as that is the value that will be returned. You can then generate your UUID primary key value on the client using this value.

see: https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_last-insert-id

**Comment by sugu1** [comment]
Great idea. Thanks!

**Comment by mevdschee** [comment]
Note that you can also use an "customization.afterHandler" to adjust the returned value to do the above trick!

Enjoy the software! Kind regards, Maurits
