### ISSUE TITLE
Updating int-/date-/time-columns to null causes internal server error (500)

### ISSUE THREAD

**Issue by escamillo** [mevdschee/php-crud-api#681]
Updating int-/date-/time-columns (and probably also columns with other numeric types) to _null_ results in an internal server error (500).

jQuery-Code:
```
$.ajax({
	url: 'api.php/records/testtable/47',
	type: 'PUT',
	data: {intcolumn: null},
	success: function(data) {
		console.log(data);
	},
	error: function(data) {
		console.log(data);
	}
});
```

Relevant elements from response object:
```
responseJSON: Object { code: 9999 }, 
status: 500, 
statusText: "Internal Server Error"
```

The columns I tested this with, were all nullable. Setting char-/varchar-columns to null does work.

database: mysql
php-crud-api-Version: v2.9.5

**Comment by mevdschee** [comment]
Thank you for reporting this issue. Can you enable debug in the config parameters and paste the response headers of the 500?

**Comment by escamillo** [comment]
```
HTTP/1.1 500 Internal Server Error
Date: Sun, 07 Jun 2020 15:47:41 GMT
Server: Apache/2.2.15 (Red Hat)
X-Exception-Name: PDOException
X-Exception-Message: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'intcolumn' at row 1
X-Exception-File: /u/www/[removed]/[removed]/api.php:5583
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://[removed]
Content-Length: 13
Connection: close
Content-Type: application/json; charset=utf-8
Vary: Accept-Encoding
```

**Comment by mevdschee** [comment]
Can you post the request, the loaded middlewares (with their config) and the table structure, so I can try to reproduce your scenario?

**Comment by mevdschee** [comment]
Let me know whether or not the above works for you.

**Comment by escamillo** [comment]
It work's! Thanks a lot for your help!

**Comment by mevdschee** [comment]
NB: You may use the web debugger and look in the network tab at the difference between the request bodies to fully understand the difference between sending 'x-www-form-urlencoded' and JSON data.

Feel free to open a new issue or reply to this one in case you have either a new or a follow-up question. Enjoy the software!
