### ISSUE TITLE
When I use join how to set page ?

### ISSUE THREAD

**Issue by FadelSultan** [mevdschee/php-crud-api#682]
Hello
Thank you for this really strong and beautiful work that every application programmer needs as I hope to develop it more and more :)
I have a problem which is as follows:
If more than one table is linked by joining, how can I limit each number of pages?

{
  "records": [
    {
      "id": 6,
      "username": " ",
      "title": "‏ ",
      "description": " ",
      "imageProfile": " ",
      "lenses": 31,
      "Following": 123456,
      "Followers": 12345678,
      "email": "srqa3h.com@gmail.com",
      "idFirebase": "JgVfVFLMxVVHWmLV6CXRfdllrVm2",
      "lens": [
        {
          "id": 761,
          "idProfile": 6,
          "title": " ",
          "snapLink": " ",
          "imagePath": " ",
          "usedToday": 3,
          "filterUsed": 4773,
          "filterShared": 154,
          "sction": 25,
          "snapDate": "0000-00-00 00:00:00",
          "snapIsActive": 1,
          "snapIsPinned": 0,
          "snapPlay": 0,
          "isNew": 0,
          "uuid": "96f4eb9019a542d581451e757cebdea0"
        },
        {
          "id": 762,
          "idProfile": 6,
          "title": " ",
          "snapLink": " ",
          "imagePath": " ",
          "usedToday": 0,
          "filterUsed": 1137,
          "filterShared": 36,
          "sction": 25,
          "snapDate": "0000-00-00 00:00:00",
          "snapIsActive": 1,
          "snapIsPinned": 0,
          "snapPlay": 0,
          "isNew": 0,
          "uuid": "2adf34804e6f459ea05940a373226c6a"
        },
        {
          "id": 763,
          "idProfile": 6,
          "title": " ",
          "snapLink": " ",
          "imagePath": " ",
          "usedToday": 0,
          "filterUsed": 3496,
          "filterShared": 48,
          "sction": 22,
          "snapDate": "0000-00-00 00:00:00",
          "snapIsActive": 1,
          "snapIsPinned": 0,
          "snapPlay": 0,
          "isNew": 0,
          "uuid": "be06970c68c5453e8d0c3cae74208ac1"
        }
      ]
    }
  ]
}

Thank's

**Comment by mevdschee** [comment]
Hi, Thank you for creating this issue and for your kind words. You can join the other way around, so list the "lenses" and join the "profile". This way you can paginate the "hasMany" relation and have the relation as a "hasOne".

**Comment by FadelSultan** [comment]
Hi,

Thank you for quick replay :)

I try your issue but I don't see data to a user

{
      "id": 1956,
      "idProfile": 6,
      "title": "",
      "snapLink": " ",
      "imagePath": " ",
      "usedToday": 0,
      "filterUsed": 0,
      "filterShared": 0,
      "sction": 0,
      "snapDate": "2020-06-10 14:20:01",
      "snapIsActive": 1,
      "snapIsPinned": 0,
      "snapPlay": 0,
      "isNew": 1,
      "uuid": "1d72ca8c82174df38878f49381282e28",
      "Users": [
        
      ]
    },

**Comment by FadelSultan** [comment]
Thank you Too much.
I have some wrong in relation now I correct it.

**Comment by mevdschee** [comment]
I'm glad you resolved the issue. Feel free to open a new issue if you have other questions. Enjoy the software!
