### ISSUE TITLE
existing table returns 9999 error

### ISSUE THREAD

**Issue by charlikindly** [mevdschee/php-crud-api#683]
Hello!

First of all, like lots of other people here, I want to thank you for doing this awesome project. It's so simple yet powerful - saves us, especially newbies like me, lots of time. Hope you and your family are all well in this strange time.
Get to the my issue here - I've been working on this for the past two weeks and went through (almost) all the posts here that could possibly give me an idea on how to fix my site. I am building my site on UNA.IO, which is a social media platform sort of framework (so they have some basics already set up, like user system and posts). I can use your most API functions without any problems but the only thing that's giving me nightmares is the AUTH (which is also something I can't do without and I'm using the most basic DB mode here). Today I created a new 'users' table just to test it. **Well, it actually worked!** 
Now my question is --> why is it not working with my existing users table (sys_accounts)? I already know they use a much fancier hash + SALT algorithm, which I temporarily bypassed by typing in the PHP hash from terminal for the same password. Is there anything I should pay attention to? There's only one PK on the table - which is the main cause for this error code in most cases, as far as I know? Does any column setting (?) of the sys_accounts look odd to you?

Please help!
Thank you so much! And also to some other people that've been answering questions here!

C
 
![Screen Shot 2020-06-12 at 7 26 24 PM](https://user-images.githubusercontent.com/46832397/84553655-a475ee80-ace2-11ea-9550-253487827fa7.png)
![Screen Shot 2020-06-12 at 7 27 07 PM](https://user-images.githubusercontent.com/46832397/84553679-c1122680-ace2-11ea-83f2-6e782c679f55.png)

**Comment by charlikindly** [comment]
Hi, 

So I managed to get my own oauth2 server set up and it is doing the authorization via user password credentials. Now I am even more confused...
What do I do now to hook it up with your API script? Which direction shall I look at? Shall I modify the JWT token part?

Many thanks!

C

**Comment by mevdschee** [comment]
>Does any column setting (?) of the sys_accounts look odd to you?

How about password with length 40?

    maurits@maurits-desktop:~/Downloads$ php -a
    Interactive mode enabled
    
    php > echo strlen(password_hash('test', PASSWORD_DEFAULT));
    60
    php > 

Now for the JWT part:

>What do I do now to hook it up with your API script?
>Which direction shall I look at? Shall I modify the JWT token part?

Load and configure the JWT middleware to begin with. Let me know what errors you encounter.

**Comment by mevdschee** [comment]
Any update?

**Comment by charlikindly** [comment]
> Any update?

hey thanks for the reply! was busy finishing the other parts of the app. will try to figure this one out now and report back!
many thanks!! =)

**Comment by charlikindly** [comment]
Hey Maurits,
I am back - trying to use the auth middleware but this password thing is still a problem.
For "Test123456" the result after hash is b2ffe3032ec81d9a5f302978ce703b2be308f4cf
I looked up in the code too.
function encryptUserPwd($sPwd, $sSalt)
{
	$sAlgo = defined('BX_PWD_ALGO') ? BX_PWD_ALGO : '';

    switch ($sAlgo) {

        case 'custom':
            return bx_custom_pwd_encrypt($sPwd, $sSalt);

    	case 'crypt':
            return crypt($sPwd, BX_PWD_ALGO_SALT);

        case 'sha1_crypt_salt':
            return sha1(crypt($sPwd, BX_PWD_ALGO_SALT) . $sSalt);

        case 'sha1_md5_salt':
        default:
            return sha1(md5($sPwd) . $sSalt);
    }
}

I even tried sh1(md5(password))... no luck there
contacting the script vendor but haven't heard back

**Comment by charlikindly** [comment]
Hi Maurits,

On top of the post above, I have another issue - so I used the hash in DB as a placeholder (don't want to get stuck while waiting for a solution) but I get 403 error now.
I suspect that it has something to do with my server setup. Do you spot anything wrong in the response?


![Screen Shot 2020-07-11 at 11 24 49 AM](https://user-images.githubusercontent.com/46832397/87227468-281a0e00-c369-11ea-8a04-5b535a13bba5.png)
cannot get anything more basic than this:
function interactiveSignIn (email,password) {
  console.warn('login started',email+password);
      let data = {
        username:email,
        password:password
      }
      const options ={
        method:'POST',
        headers: {
          'Content-Type':'application/json'
        },
        body: JSON.stringify(data)
      }
      fetch('https://www.heymofas.com/api.php/login',options)
      .then(res=> {
        if(res.ok){
          console.log(res);
          return res.json();
        }}
      ).then(res=>{
        console.log('logging',res);
      }).catch(err=> console.log(err.message));
    }

in your file cinfig:

  'middlewares' => 'dbAuth',
        'dbAuth.mode' => 'required',
        'dbAuth.usersTable' => 'sys_accounts',
        'dbAuth.usernameColumn' => 'email',
        "dbAuth.passwordColumn" => 'password',

**Comment by charlikindly** [comment]
forgot to add -  without authentication, the rest of the api can work

**Comment by mevdschee** [comment]
I think the 403 is caused by a failed authentication, but you may enable the 'debug' setting to get more details. Take a look at both the response body and the response headers (after enabling debug).

**Comment by charlikindly** [comment]
Thanks for the reply, @Maurits.
Unfortunately, I still can't figure it out after spending days on the auth api call trouble. Everything was working well in the local development environment until deployment.
I had an oAuth2 server set up too for auth and that token endpoint call is also giving me 403 via js code. Postman and curl can work.
The rest of your endpoints are working correctly.

I had always had debug enabled but I just went to disable that just to see the difference.

this is after debug:
`HTTP/1.1 403 Forbidden
Date: Wed, 15 Jul 2020 10:49:10 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
**Set-Cookie: PHPSESSID=41c47af906a3cb35adcecbaeceb84193; path=/**
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: CONNECT, DEBUG, DELETE, DONE, GET, HEAD, HTTP, HTTP/0.9, HTTP/1.0, HTTP/1.1, HTTP/2, OPTIONS, ORIGIN, ORIGINS, PATCH, POST, PUT, QUIC, REST, SESSION, SHOULD, SPDY, TRACE, TRACK
Access-Control-Max-Age: 1000
Access-Control-Allow-Headers: Accept, Accept-CH, Accept-Charset, Accept-Datetime, Accept-Encoding, Accept-Ext, Accept-Features, Accept-Language, Accept-Params, Accept-Ranges, Access-Control-Allow-Credentials, Access-Control-Allow-Headers, Access-Control-Allow-Methods, Access-Control-Allow-Origin, Access-Control-Expose-Headers, Access-Control-Max-Age, Access-Control-Request-Headers, Access-Control-Request-Method, Age, Allow, Alternates, Authentication-Info, Authorization, C-Ext, C-Man, C-Opt, C-PEP, C-PEP-Info, CONNECT, Cache-Control, Compliance, Connection, Content-Base, Content-Disposition, Content-Encoding, Content-ID, Content-Language, Content-Length, Content-Location, Content-MD5, Content-Range, Content-Script-Type, Content-Security-Policy, Content-Style-Type, Content-Transfer-Encoding, Content-Type, Content-Version, Cookie, Cost, DAV, DELETE, DNT, DPR, Date, Default-Style, Delta-Base, Depth, Derived-From, Destination, Differential-ID, Digest, ETag, Expect, Expires, Ext, From, GET, GetProfile, HEAD, HTTP-date, Host, IM, If, If-Match, If-Modified-Since, If-None-Match, If-Range, If-Unmodified-Since, Keep-Alive, Label, Last-Event-ID, Last-Modified, Link, Location, Lock-Token, MIME-Version, Man, Max-Forwards, Media-Range, Message-ID, Meter, Negotiate, Non-Compliance, OPTION, OPTIONS, OWS, Opt, Optional, Ordering-Type, Origin, Overwrite, P3P, PEP, PICS-Label, POST, PUT, Pep-Info, Permanent, Position, Pragma, ProfileObject, Protocol, Protocol-Query, Protocol-Request, Proxy-Authenticate, Proxy-Authentication-Info, Proxy-Authorization, Proxy-Features, Proxy-Instruction, Public, RWS, Range, Referer, Refresh, Resolution-Hint, Resolver-Location, Retry-After, Safe, Sec-Websocket-Extensions, Sec-Websocket-Key, Sec-Websocket-Origin, Sec-Websocket-Protocol, Sec-Websocket-Version, Security-Scheme, Server, Set-Cookie, Set-Cookie2, SetProfile, SoapAction, Status, Status-URI, Strict-Transport-Security, SubOK, Subst, Surrogate-Capability, Surrogate-Control, TCN, TE, TRACE, Timeout, Title, Trailer, Transfer-Encoding, UA-Color, UA-Media, UA-Pixels, UA-Resolution, UA-Windowpixels, URI, Upgrade, User-Agent, Variant-Vary, Vary, Version, Via, Viewport-Width, WWW-Authenticate, Want-Digest, Warning, Width, X-Content-Duration, X-Content-Security-Policy, X-Content-Type-Options, X-CustomHeader, X-DNSPrefetch-Control, X-Forwarded-For, X-Forwarded-Port, X-Forwarded-Proto, X-Frame-Options, X-Modified, X-OTHER, X-PING, X-PINGOTHER, X-Powered-By, X-Requested-With
Access-Control-Allow-Credentials: true
Upgrade: h2
Connection: Upgrade, Keep-Alive
Content-Length: 71
Vary: User-Agent
Keep-Alive: timeout=2, max=100
Content-Type: application/json; charset=utf-8`

I had this crazy _cors-fighting_ headers setup after (obviously) so many failed attempts at auth.
After comparing with the debug-off version, the difference is the _set-cookie._
It should be something related to cookies? I just don't know how to fix that.

Thank you so much.

**Comment by charlikindly** [comment]
and the code i got is -

> {"code":1011,"message":"Authentication required"}

Many thanks.

**Comment by mevdschee** [comment]
Do tot have a cookie jar mechanism? Ie: do you store the set-cookie response and send it again on the next request using a cookie header?

**Comment by mevdschee** [comment]
You should be either using dbauth and the /login endpoint or a JWT and oAuth. Are you trying to combine these options?

**Comment by charlikindly** [comment]
> You should be either using dbauth and the /login endpoint or a JWT and oAuth. Are you trying to combine these options?

Hi @mevdschee I finally fixed the bug... It's actually _not an advanced bug_ at all...haha but I really was stuck on it for two weeks...
Regarding the password myth if you are curious - it is sha1(md5($sPwd) . $sSalt);
My problem is kind of silly though - I have an oAuth2 server on my own server which gives out token and stuff. It has some api endpoints I can use but my app heavily relies on your script - which means I need to integrate your php file into this oauth2 server setup.

**Comment by charlikindly** [comment]
Is there anyway to just auth the user with what comes from the oauth2 authentication process? Access token or cookies?

**Comment by mevdschee** [comment]
Yes, the README explains how this is done for auth0.

**Comment by charlikindly** [comment]
except that it's not auth0 and didn't have a pubkey to validate the token with T.T
how am i gonna verify that? with algorithm???

**Comment by mevdschee** [comment]
>except that it's not auth0

So what is it then?

> didn't have a pubkey to validate the token with 

What do you have to validate the token with?

**Comment by charlikindly** [comment]
> > except that it's not auth0
> 
> So what is it then?
> 
> > didn't have a pubkey to validate the token with
> 
> What do you have to validate the token with?

Hi Maurits,

Thanks for keeping me company! Well, the auth server is on my own server. It is based off this: https://github.com/bshaffer/oauth2-server-php
While I am asking the script vendor to point me in the right direction (to the public key), I am thinking about some other solutions -
Since it is on my server and I have my access token just sitting in the DB, isn't it easier just to verify token itself?? Could this have any security risk? It does sound a bit dangerous? I am not an expert at this, as you can see already...

Thank you so much for bearing with me!!!

**Comment by mevdschee** [comment]
>Since it is on my server and I have my access token just sitting in the DB, isn't it easier just to verify token itself??

It indeed sounds easy enough and I don't see an immediate problem with that scheme. On the other hand...

>Could this have any security risk?

I do recommend to follow standards, because in security a bug can have large consequences. That's why I would recommend against such a "home-grown" solution.

>Thank you so much for bearing with me!!!

I'm happy to help.

**Comment by charlikindly** [comment]
> > Since it is on my server and I have my access token just sitting in the DB, isn't it easier just to verify token itself??
> 
> It indeed sounds easy enough and I don't see an immediate problem with that scheme. On the other hand...
> 
> > Could this have any security risk?
> 
> I do recommend to follow standards, because in security a bug can have large consequences. That's why I would recommend against such a "home-grown" solution.
> 
> > Thank you so much for bearing with me!!!
> 
> I'm happy to help.

I definitely want to follow the instructions you put out there but I really cannot find the public key. I think maybe they use some algorithm to sub that? I don't know auth server that well. I also asked the script vendor but I don't think they understand me.
English is probably just not enough in some situations...

**Comment by charlikindly** [comment]
Hi Maurits,

I am using database query to directly check user's token against the one in the DB. It works, of course, but I' really concerned about the security aspect.
I do have 230 tables. What's your best recommendation to keep my DB safe?

Thank you so much as always!

**Comment by mevdschee** [comment]
>What's your best recommendation to keep my DB safe?

I recommend that when you write sensitive/critical/important software (with complex information security issues) to get an computer security (infosec) professional to audit/review/hacktest your setup.

**Comment by mevdschee** [comment]
I'll close this issue for now as your questions seem answered. If you have further questions about this ticket, feel free to reply. Otherwise, please open a new issue. Good luck!
