### ISSUE TITLE
Basic Auth - Avoid repeating Authorization:Basic xxxx

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#686]
Hi,

Using Basic Authentification, 'Authorization:Basic xxxx' headers has to be present in every api call.

Is it possible to register it once avoiding referencing it in subsequent api calls, the time of the session duration?

Thank you.

**Comment by mevdschee** [comment]
Thank you for asking this question.

>Is it possible to register it once avoiding referencing it in subsequent api calls, the time of the session duration?

Yes, if you enable the cookie storage (and sending) on the API client. In the first request you send the credentials using the "Authorization" header (and get a "Set-Cookie" header in return). In the subsequent requests you send the "Cookie" header containing the session identifier.

I hope this helps.

**Comment by thipages** [comment]
Hi,
thanks, it works now for what I want to do (on remote server) ... without changing a line of code ;-) oops
Questions : for how long the cookie is living? Can I destroy it?

**For sharing**
The following js code works on remote server but not on localhost.
```javascript
const baseUrl='api.php';
let table='aTable';
let keyBase64='xxxxxx';
let id=1;
let calledTwice=false;
const call=(keyBase64)=>(table,id)=> {
    const auth=!keyBase64?{}:{headers: {Authorization:'Basic '+keyBase64}};
    fetch(
        [baseUrl, "records", table, id].join("/"),
        Object.assign(auth,{method: 'GET'})
    )
        .then(response => response.json())
        .then(data => {
            // document.cookie keys
            // localhost : _ga, _ga_xxxx, username, PHPSESSID
            // remote server  : only PHPSESSID
            console.log(data, document.cookie);
           // SECOND CALL
            if (!calledTwice) call()(table,id); // 403 for localhost, ok for remote server
            calledTwice=true;
        });
};
// FIRST CALL
call(keyBase64)(table, 1); 
```
the api.php config
```
    'middlewares' => 'basicAuth',
    'basicAuth.mode' => 'optional', // or required  (same behaviours)
```
**What it does** : call twice api.php seeking for record id 1 of aTable.
- the first call is with 'username:pass' based64 
- the second without

**Results** 
- first call works on both environments
- the second call works on remote server, not on localhost
- the document.cookies keys are different on local and remote (perhaps due to the different tests I have done with several middlewares)

Any explanations or links to?
Is it possible to get the same behaviour on localhost?

I have missed something somewhere anyway

**Comment by mevdschee** [comment]
> Questions : for how long the cookie is living? 

The cookie lives for as long as the session lives in the browser or when the session cleanup on the server happens.

>Can I destroy it?

You should not destroy it.

>the second call works on remote server, not on localhost

This could be due to cross domain issues, or are you running a PHP web server locally?

>the document.cookie keys are different on local and remote

They should be, as the cookie only contains a random session id that refers to a file on the server containing the session storage.

>I have missed something somewhere anyway

I'm happy to help you master this (quite difficult) topic.

**Comment by thipages** [comment]
yes, I am running a php web server locally.
I have to work more on this topic to better understand it!!
Thank you.

**Comment by mevdschee** [comment]
>yes, I am running a php web server locally.

That's great!

> I have to work more on this topic to better understand it!!

Sure, but feel free to reopen and ask follow-up questions. I'm happy to help you.
