### ISSUE TITLE
Filtering on Foreign table

### ISSUE THREAD

**Issue by olejerx** [mevdschee/php-crud-api#689]
Hello.

Apologizing if there was already similar questions.
I am trying to filter records on foreign table.
Here is a request example:
/api.php/records/wp_posts?join=wp_term_relationships&filter=ID,eq,1

Which retrieves following JSON.

```
{
    "records": [
        {
            "ID": 1,
            "post_author": 1,
            "post_date": "2019-06-04 15:30:16",
            "post_date_gmt": "2019-06-04 15:30:16",
            "post_content": "
            "post_title": "",
            "post_excerpt": "",
            "post_status": "publish",
            "comment_status": "open",
            "ping_status": "open",
            "post_password": "",
            "post_name": "1593076643705",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2020-06-25 09:17:22",
            "post_modified_gmt": "2020-06-25 09:17:22",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "",
            "menu_order": 0,
            "post_type": "post",
            "post_mime_type": "",
            "comment_count": 0,
            "link": "",
            "image": null,
            "wp_term_relationships": [
                {
                    "object_id": 1,
                    "term_taxonomy_id": 4,
                    "term_order": 0
                },
                {
                    "object_id": 1,
                    "term_taxonomy_id": 12,
                    "term_order": 0
                }
            ]
        }
    ]
}
```

I would like to filter to apply filter on wp_term_relationships.term_taxonomy_id columng.

I've tried to use following requests:
1) /api.php/records/wp_posts,wp_term_relationships
Response: 

```
{
    "code": 1001,
    "message": "Table 'wp_posts,wp_term_relationships' not found"
}
```

2) /api.php/records/wp_posts?join=wp_term_relationships&filter=wp_term_relationships.term_taxonomy_id,eq,4
Response:

```
{
    "code": 9999,
    "message": "Return value of Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedTable::getColumn() must be an instance of Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedColumn, null returned"
}
```

Could you please provide a correct syntax?

Kind regards,
Oleg.

**Comment by i2pacg** [comment]
Hello Oleg, no i don't think you can directly filter a joined table atm , you might have to look at views for that.
the first error you're getting is because of the syntax, the first parameter after records should be the table name only . followed by a ? then other parameters  .
the second error is because you can't use columns from joined tables for filtering

**Comment by mevdschee** [comment]
Hi, thank you for reporting this issue. You are right:

Filtering can only be done on the primary table and not on the join tables.

There is a common workaround:

    /api.php/records/wp_term_relationships?join=wp_posts&filter=term_taxonomy_id,eq,4

This gives you a single taxonomy with all related posts.

**Comment by mevdschee** [comment]
Does this work for you? Shall I close the ticket?

**Comment by olejerx** [comment]
Yes please.
