### ISSUE TITLE
dbAuth integration

### ISSUE THREAD

**Issue by skg9h** [mevdschee/php-crud-api#694]
Have updated the config to be able to validate a user and returns the user table record.

However, further subsequent calls are giving  error {"code":1011,"message":"Authentication required"}

Tried checking session_id, used cookies for curl.

Could not find anyway to pass session_id and send it again for subsequent  post / get calls.

**Comment by mevdschee** [comment]
Thank you for reporting this issue.

Did you enable the curl cookie jar mechanism?

See: https://stackoverflow.com/questions/20896893/cookiejar-in-php-curl

Kind regards, Maurits

**Comment by skg9h** [comment]
Yes.

Did.that. tried tweeking many parameters including passing session_id() as key value pair in the Cookie.

Tried by setting CURLOPT_HTTPHEADER value and pass the session_id
Tried setting CURLOPT_HEADER as true.

Have put echo and print_r  statement in api.php. it is simply not picking up the session id. In one scenario api.php even created it's own session.

I am using cpanel hosting both for app and api.php

**Comment by mevdschee** [comment]
>Did.that. tried tweeking many parameters including passing session_id() as key value pair in the Cookie.

That should not be needed with a cookiejar.

>In one scenario api.php even created it's own session.

It should

>I am using cpanel hosting for both app and api.php

I don't think that that is relevant.

**Comment by skg9h** [comment]
Here is the piece of code that I used. Not working as expected.

**For Login:**
    $url = "http://bestbn.asiaus.systems/api.php/login";
    $options = array('username' => $_POST['username'], 'password' => $_POST['password'] );
    $query = http_build_query($options);
    $ch    = curl_init();
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
    curl_setopt($ch, CURLOPT_COOKIEJAR, 'bestbn_'.session_id());
    curl_setopt($ch, CURLOPT_COOKIEFILE, 'bestbn_'.session_id());
    $response = curl_exec($ch);
    curl_close($ch);
    print_r($response);
    
**For Fetching record**
    $url = "http://bestbn.asiaus.systems/api.php/records/member_personal";        
    $ch    = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HEADER, false);
    curl_setopt($ch, CURLOPT_COOKIEJAR, 'bestbn_'.session_id());
    curl_setopt($ch, CURLOPT_COOKIEFILE, 'bestbn_'.session_id());
    $response = curl_exec($ch);
    curl_close($ch);
    print_r($response);

**Please see on http://bestbn.asiaus.systems/login_api.php**

username: test61
password: sharad123

**Comment by mevdschee** [comment]
Hi,

When you start echo-ing data then the "set cookie" headers cannot be set anymore (headers are already sent). I understand that this is for debug purposes, but you need to avoid doing that.

Kind regards, Maurits

**Comment by skg9h** [comment]
yes. it solved the problem
