### ISSUE TITLE
Only get in tables?

### ISSUE THREAD

**Issue by gstrainovic** [mevdschee/php-crud-api#695]
Hello

Thanks for this great API. Why are there tables which I can only read (GET) and others where I can do everything? (GET,PUT,POST) I don't understand where the API gets this from and why? I would like to POST, but only GET works on tables *_category_descriptions and *_product_categories.

![grafik](https://user-images.githubusercontent.com/8936333/89452695-5cad9980-d75e-11ea-8904-a5d743f46429.png)

**Comment by mevdschee** [comment]
Hi, thank you for reporting this issue. 

>Why are there tables which I can only read (GET) and others where I can do everything? 

Could these these read-only tables be views?

Kind regards, Maurits

**Comment by gstrainovic** [comment]
I'm not sure, I haven't found anything that makes them read-only. Also, I can describe these tables with e.g. https://github.com/ThingEngineer/PHP-MySQLi-Database-Class, so it's more likely that it has two PrimaryKeys?


![grafik](https://user-images.githubusercontent.com/8936333/89706411-a7e5c900-d965-11ea-8443-978e6ce28223.png)

**Comment by mevdschee** [comment]
>so it's more likely that it has two PrimaryKeys?

Yes. Good find! Composite primary keys are not supported.

KInd regards, Maurits

**Comment by gstrainovic** [comment]
Ok. I understand. 
I probably can't do this because there are many tables which are like this and then probably the shop to this database doesn't work. 
As it looks like the database must be designed to work with this API and in my case it is better to use a DB ORM.
Thank you, now I know what the problem is.
