### ISSUE TITLE
index based response

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#696]
Hi,
this is not a bug but a question.

the response is based on json (or xml) and named field.
Will it possible to get a response on an indexed based in order to **save some bandwidth**?

1. This may be based on the database field order or if specified on the include ordering.
2. Not sure that all api select/read responses cases can be covered (joins?)
3. This could be implemented through `customization `middleware, I guess
4. Performance may be impacted
5. Have you some advices for such implementation ?

Thank you.

**Comment by thipages** [comment]
as complement, the response could be an array
```
[
  index based response, 
  associated fields names (tree)
]
```

**Comment by mevdschee** [comment]
If your goal is to save some bandwidth, then I would gzip/deflate the output using a webserver.

You can also implement middleware to transform the output to your needs.

**Comment by thipages** [comment]
thank you
