### ISSUE TITLE
Match results of included table

### ISSUE THREAD

**Issue by lfaltran** [mevdschee/php-crud-api#697]
There is any way to limit included table results based on main table?

/api.php/oc_order?include=oc_order_product&order=date_modified&page=1,10

On this example I want only the "oc_order_product" of "oc_order" listed

**Comment by mevdschee** [comment]
Any update?

**Comment by lfaltran** [comment]
sorry for delay on answer @mevdschee 

I`ve change the way that I used to search for multiple data, instead of using "joinLimits" I combined "include" with "filter[]", the result was something like:

`/api.php/oc_order?include=oc_order_product&filter[]=order_id,eq,12&filter[]=oc_order_product.order_id,eq,12`

On this example I'll get the "oc_order_product" of "oc_order" listed, both filtered by ORDER_ID attribute.

About your suggest... I don't have access to API running side server, so, I'm not sure how `joinLimits` are configured and also if tables are using FK correctly.

**Comment by mevdschee** [comment]
Are you satisfied with your current solution or do you need any further help in any way?

**Comment by lfaltran** [comment]
yeah, all ok for now
