### ISSUE TITLE
Invalid argument supplied for foreach(). POST fails with '9999' error.

### ISSUE THREAD

**Issue by NorthFred** [mevdschee/php-crud-api#699]
Since yesterday, I started receiving a PHP warning in the PHP error logs.  The errors starts to appear when I make a 'create' request on the table 'Streams'.  I tried removing the 'multiTenancy.handler' and the 'authorization.tableHandler', but the error persists. The POST request keeps on failing with <500> error and gives code "9999".
For the same table, I can fetch data with GET and filters etc.
Since removing the handlers below doesn't resolve it, and other requests are working, I believe my config should be fine (?).

Any ideas?  The line hints towards the function `getPairs` in the api.php file...

```
    $config = new Config([
        'username' => '************',
        'password' => *************',
        'database' => '*************',
        'address' => 'mysql**.domain.fi',
        'cacheType' => 'NoCache',
        'middlewares' => 'cors, jwtAuth, authorization, multiTenancy',
        'jwtAuth.secrets' => $secrets,
        'jwtAuth.algorithms' => 'RS256',
        'jwtAuth.issuers' => 'https://securetoken.google.com/******',
        'jwtAuth.audiences' => '**************',
        'cors.allowedOrigins' => '*',
        'cors.allowHeaders' => 'X-Authorization, content-type',
        'multiTenancy.handler' => function($operation, $tableName) {
		    if ($tableName === 'Users') {
		      if (in_array($operation, ['read', 'create', 'update'])) {
		          return ['userId' => $_SESSION['claims']['user_id']];
		      }
		    }
		    if ($tableName === 'UserFavorites') {
		        return ['userId' => $_SESSION['claims']['user_id']];
		    }
		    if ($tableName === 'Launches') {
		        return ['userId' => $_SESSION['claims']['user_id']];
		    }
		},
		'authorization.tableHandler' => function ($operation, $tableName) {
			if (in_array($operation, ['read', 'create', 'delete', 'list']) && $tableName == 'UserFavorites') {
			    return $tableName;
			}
			if (in_array($operation, ['delete']) && (in_array($tableName, ['Users', 'Streams']))) {
			    return false;
			}
			if ($tableName === 'Launches') {
			    if ($operation == 'create') {
			        return $tableName;
			    }
			    return false;
			}
			// PUT ==> block Streams from being updated by Users...
			return $tableName;
        }
    ]);

```

Error output:
`[24-Aug-2020 22:46:02 Europe/Helsinki] PHP Warning:  Invalid argument supplied for foreach() in /home3/******/public_html/********/api/api.php on line 7818`

**Comment by mevdschee** [comment]
Hi, thank you for reporting this issue. Can you post the line 7818? Kind regards, Maurits

**Comment by NorthFred** [comment]
Here are the affected lines in my version of the api.php:

```
        private function getPairs($handler, string $operation, string $tableName): array
        {
            $result = array();
            $pairs = call_user_func($handler, $operation, $tableName);
            $table = $this->reflection->getTable($tableName);
            foreach ($pairs as $k => $v) {               <----------------- 7818
                if ($table->hasColumn($k)) {
                    $result[$k] = $v;
                }
            }
            return $result;
        }
```

Met vriendelijke groet,
Fred

**Comment by mevdschee** [comment]
Okay, thank you! It seems to related to the return value of the multi-tenancy handler, can you paste your handler?

**Comment by NorthFred** [comment]
The modified part of the multiTenancy handler is in the opening post. Is that what you need?

**Comment by mevdschee** [comment]
Can you add a default case at the end of the handler?

    return [];

May work, dunno..

**Comment by mevdschee** [comment]
Version v2.9.19 released. I hope it fixes your problem.

**Comment by NorthFred** [comment]
> 
> 
> Can you add a default case at the end of the handler?
> 
> ```
> return [];
> ```
> 
> May work, I'm not sure..

This did not help, still <500> error with code '9999'.  
One change though was that the error_log of the php server is no longer logging any errors...

Either way, I will try the latest release and report back in a moment!

**Comment by mevdschee** [comment]
Please enable debug mode, so that you see what error 9999 is about (check the response headers).

**Comment by NorthFred** [comment]
Thanks! That got me to finding out what the issue was. 

The exception message from the debugger stated: `SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'type' at row 1`

My POST payload contained a value for 'type' which was outside of the allowed amount of characters.

Hopefully this info will help you to make further improvements to the already awesome api. It would be great if the code could catch this kind of exception and send a meaningful error code back to the developers!

Thank you once again!!

**Comment by mevdschee** [comment]
Thank you for reporting back. I'm afraid there is no easy improvement here. Sometimes the database errors contain sensitive information and therefor (for security reasons) error reporting defaults to "9999", without explanation. You need to enable debug mode to find the errors that the database reports.
