### ISSUE TITLE
How can I see relationships?

### ISSUE THREAD

**Issue by BoldijarPaul** [mevdschee/php-crud-api#7]
I don't really understand what it says in the documentation, because that classes are not there anymore  .

So I have this structure

Person 
     -id (PK)
     -name
     -classId (FK)

Class
     -id (PK)
      - name

And Person.classId is in relation ship with class.id.

But in my json output I only see classId, and can't see class object.

I don't have almost no php knowledge.

Thanks.

**Comment by mevdschee** [comment]
Can you try to call ```api.php/Person,Class?transform=1``` and see what happens?

**Comment by mevdschee** [comment]
Also, defining a foreign key constraint is required for the feature to work. Something you can do with SQL with the following command (for MySQL innoDB):

```ADD FOREIGN KEY (`classId`) REFERENCES `Class` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT```

**Comment by BoldijarPaul** [comment]
http://localhost/api/index.php/person?transform=1 will give me

{
person: [
{
id: "1",
name: "Alex",
classId: "2"
},
{
id: "2",
name: "Dan",
classId: "2"
},
{
id: "3",
name: "Ion",
classId: "1"
},
{
id: "4",
name: "Boldij",
classId: "2"
}
]
}

And if transform is 0
http://localhost/api/index.php/person?transform=0

{
person: {
columns: [
"id",
"name",
"classId"
],
records: [
[
"1",
"Alex",
"2"
],
[
"2",
"Dan",
"2"
],
[
"3",
"Ion",
"1"
],
[
"4",
"Boldij",
"2"
]
]
}
}

I made the relation with phpmyadmin.

![capture](https://cloud.githubusercontent.com/assets/7826299/10902509/8e88b270-8207-11e5-8f1e-f2d1f7c342a1.PNG)

**Comment by mevdschee** [comment]
Good, now try: ```http://localhost/api/index.php/person,class?transform=1```

**Comment by BoldijarPaul** [comment]
Thank you! Works

**Comment by mevdschee** [comment]
Great, enjoy the software! Feedback is always welcome.

**Comment by BoldijarPaul** [comment]
Also, if I go to
http://localhost/api/index.php/person,class?transform=1
As you said

I get a list of

person: [
{
id: "1",
name: "Alex",
classId: "2",
class: [
{
id: "2",
name: "Sport"
}
]
}

Why a person has a list of classes?
It is not a many to many relationship, a person only has one classId field.
Am I wrong?

**Comment by mevdschee** [comment]
>Why a person has a list of classes?
This way the relationship is represented the same way for belongsTo, hasMany and HABTM relationships. One may argue whether or not this is an advantage.

**Comment by BoldijarPaul** [comment]
So there is no way to only have a class object instead of a list of classes there?

**Comment by mevdschee** [comment]
At the moment you cannot, as the transformation does not know which field contains the primary key. On the other hand you probably do and you can easily add "[0]" to the class to get the object, right?

**Comment by BoldijarPaul** [comment]
Yes, i can.
