### ISSUE TITLE
authorization with JWT

### ISSUE THREAD

**Issue by 55chevypickup** [mevdschee/php-crud-api#700]
I'm trying to get the API to work so reads you don't need to be logged in but when logged in with a JWT token changes are able to be made. JWT is working when not using authorization.tableHandler. I have tried the following like what is in tests/config/base.php but the $_SESSION var always seems to be NULL. Not sure if it is something that I'm doing? Thanks for any help and this API has been great.

     $config = new Config([
        'username' => 'xxx',
        'password' => 'xxx',
        'database' => 'xxx',
		'address' => 'xxxx',
		'driver' => 'mysql',
        'port' => '3306',
        'middlewares' => 'authorization,jwtAuth',
        'jwtAuth.secrets' => "xxxx",
        'jwtAuth.mode' => 'optional',    
        'jwtAuth.algorithms' => 'RS256', 
            'jwtAuth.leeway' => '60',
            'jwtAuth.header' => 'X-Authorization',
            'authorization.tableHandler' => function ($operation, $tableName) {
                 return (($operation == "list" || $operation == "read") || (isset($_SESSION['claims']['name'])));  
            }
    ]);

**Comment by mevdschee** [comment]
Hi, thank you for reporting this issue. Do you have cookies enabled? As the session mechanism requires a session cookie to function. You need to accept the Set-Cookie header and send the Cookie header with the appropriate value in subsequent requests. This requires some CORS headers and sometimes other settings to enable session cookies. Let me know whether or not you see these headers being passed back and forth. Kind regards, Maurits

**Comment by 55chevypickup** [comment]
It is passing the headers from what I can tell. I put a var_dump($_SESSION); in the JwtAuthMiddleware after the session_start(); and it shows the JWT claims in the $_SESSION.

**Comment by mevdschee** [comment]
Is the $_SESSION null on the same request? Or on the next request? Or does every request have a JWT?

**Comment by 55chevypickup** [comment]
In the same request the $_SESSION in JwtAuthMiddleware will show the claims but if you var_dump the same $_SESSION in the $config it will be NULL.

**Comment by mevdschee** [comment]
I think you need to change the order of the middlewares in the 'middlewares' config parameter.

**Comment by 55chevypickup** [comment]
are you saying from this 'middlewares' => 'authorization,jwtAuth' to  'middlewares' => 'jwtAuth,authorization'? if so  the $_SESSION is still NULL

also changed 'authorization.tableHandler' to before the 'jwtAuth.secrets' and $_SESSION is still returning NULL

**Comment by mevdschee** [comment]
>are you saying from this 'middlewares' => 'authorization,jwtAuth' to 'middlewares' => 'jwtAuth,authorization'?

Yes

> if so the $_SESSION is still NULL

Ah..

>also changed 'authorization.tableHandler' to before the 'jwtAuth.secrets' and $_SESSION is still returning NULL

That is not needed.

**Comment by 55chevypickup** [comment]
Changing it to 'middlewares' => 'jwtAuth,authorization' worked. I made the change in the wrong file. It is working now. Thanks for the help!!
