### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by Spy-Shifty** [mevdschee/php-crud-api#702]
Hi I can't get it to work.

I've downloaded the latest version (or any older doesn't matter). 

I changed the config in the api.php:

   $config = new Config([
		'driver' => "mysql",
		'address' => "My-MySQL-URL",
		'port' => "3306",
		'username' => "USERNAME",
		'password' => "*******",
		'database' => "DB Instance",
		'debug' => false
    ]);

I've uploaded the api.php to the server. 

Then I access the db with 
http://www.myurl.com/api.php/records/products/

I just get:
{"code":1000,"message":"Route '\/api.php\/records\/products' not found"}

What am I doing wrong?

**Comment by NorthFred** [comment]
Few things that come to mind first:

- Did you configure your server for using the PHP file (with e.g. MultiPHP INI Editor, add the PHP directives to the `php.ini` file) ?
- Is your Table name written with capital letter? The path is case sensitive. If you have it named "Products", you should access it also with `api.php/records/Products`

**Comment by Spy-Shifty** [comment]
Hi thx for your help.

I solved my problem by adding a 
.htaccess to the root folder

The one, provided by the project failed for some reason 

.htaccess content:
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ /api.php/$1 [QSA,L]


With this in mind, I can now access my data via 
http://www.myurl.com/records/products/

so I got rid of api.php in the url

**Comment by NorthFred** [comment]
Glad you managed to resolve it!
