### ISSUE TITLE
Server error: no such file or directory....

### ISSUE THREAD

**Issue by MaccerC** [mevdschee/php-crud-api#704]
Hi,

I get this error from the server: 
Warning: fopen(/tmp/phpcrudapi-5ff80ecc-cache/623ac493259199b598bb537b64af5693): failed to open stream: No such file or directory in /...../..../api.php on line 3459
It happens after a few http requests. So when I reload the webpage, some 2 or 3 requests are passing without error and the next request is giving this error.
What can I do about it? Is it a bug or a defect in my code. However, the code runs without any errors on my local machine with localhost.

**Comment by MaccerC** [comment]
Just forget my issue...
I updated the api, refreshed the browser and voila, no errors.
Sorry for bothering.

**Comment by mevdschee** [comment]
No problem, thank you for reporting this issue. Feel free to open a new issue if you need any assistance in the future.

**Comment by clysss** [comment]
Hello,
[Fri Oct 18 10:15:52.807449 2024] [php:warn] [pid 2780:tid 1952] [client ::1:58320] PHP Warning:  fopen(C:\\Users\\xxx\\AppData\\Local\\Temp\\phpcrudapi-9d98f9bd-cache\\e42cf949b95c1a6569da6d7afec9f3ba): Failed to open stream: No such file or directory in C:\\xampp\\htdocs\\go\\api.include.php on line 3857, referer: http://localhost:8800/
[Fri Oct 18 13:42:33.153643 2024] [php:warn] [pid 2780:tid 1960] [client ::1:49684] PHP Warning:  fopen(C:\\Users\\xxx\\AppData\\Local\\Temp\\phpcrudapi-9d98f9bd-cache\\fdb94ff9d53e2dc9b3be1d99928b63e2): Failed to open stream: No such file or directory in C:\\xampp\\htdocs\\go\\api.include.php on line 3857, referer: http://localhost:8800/

after around 30 minutes of inactivities, Ive go a cache error
but the session seems ok.. and the file seems to be accessible few time after, and after a refresh, everything is back (file exist in directroy)

**Comment by clysss** [comment]
- i imagine that their is a cache expire ?
-  the API return the good data, but as their is a warning, the warning is send just before the data and of course my client don't like... => how should I remove warnings? Thx
