### ISSUE TITLE
dbAuth, but allow the /openapi endpoint to work without authentication.

### ISSUE THREAD

**Issue by adrianvoica** [mevdschee/php-crud-api#706]
Hello Maurits,
The title kinda describes my scenario.
So, the question is: is there a quick way to configure api.php to use dbAuth on the API endpoints, but allow the /openapi endpoint to work without authentication? 
Thanks for the great API! Keep up the (superhuman) work!

**Comment by mevdschee** [comment]
Thank you for your kind words. I guess you can add some middleware (or on top of the PHP file) to set `$_SESSION['user']` to something when you hit that specific URL (and unset that value when you hit another URL). Do you think you can manage to implement that?

**Comment by adrianvoica** [comment]
Thank you! I will definitely try this approach. I'm not into writing much php (and backend code in general) these days, that's why I need something that works out of the box and just gets the job done (like TreeQL / php-crud-api).

**Comment by mevdschee** [comment]
Ok.. I'll try.. add this to the top of the PHP file:

    <?php
    $user = $_SESSION['user']??false;
    if ($_SERVER['REQUEST_URI']=='/openapi') {
        if (!$user) {
            $_SESSION['user'] = 'anonymous';
        }
    } else {
        if ($user == 'anonymous') {
            unset($_SESSION['user']);
        }
    }

Not tested..

**Comment by mevdschee** [comment]
Note that the /openapi endpoint is designed to reflect the actual permissions that the user has. So if a table is not accessible for a specific user, then it is not listed either. This is why authentication for that endpoint is required.

**Comment by mevdschee** [comment]
You may also use ""dbAuth.mode" set to "optional" to achieve this.

    "dbAuth.mode": Set to "optional" if you want to allow anonymous access ("required")

If you authenticate then you get more permissions than just the /openapi endpoint. Implement an authorization handler to reflect this configuration.

**Comment by adrianvoica** [comment]
Ok. It makes perfect sense now - the /openapi reflecting the user permissions. Thanks a lot! I have enough examples to fiddle with now. dbAuth.mode sound a bit more idiomatic, so I will try that as well. Cheers!

**Comment by mevdschee** [comment]
Great! Try it out and let me know whether or not you succeed.

**Comment by mevdschee** [comment]
I'll close this ticket now. If you have further questions, feel free to open a new issue or reply if it is closely related this topic. Enjoy the software!
