### ISSUE TITLE
Combining Handlers

### ISSUE THREAD

**Issue by NorthFred** [mevdschee/php-crud-api#707]
Given the following situation:

- TableName = "DataRecords"
- The "DataRecords" table contains 'private' and 'public' records, indicated by a column name "private" which holds a boolean value
- 'Private' dataRecords should not be accessible if owned by the signed-in user
- 'Public' dataRecords are accessible to any signed-in user
- Only GET (single) and LIST operations are allowed on the table
- A column is available for 'private' records which contains the 'userId' of the owner.

I would like to be able to:
- with GET /DataRecords, any authorized person can  **only** see the Public Records.
but
- when a specific filter is used as parameter, user's Private records can be retrieved as well.

Is this achievable, if so what kind of handler combination?  This is an existing (old) database, so I cannot modify the structure directly :(

**Comment by mevdschee** [comment]
Hi. Thank you for opening this issue. You can use the multitenancy middleware for this. Can you try that and see what you run into?

**Comment by mevdschee** [comment]
In the authorization middleware you can restrict write actions to specific tables and in the multitenancy middleware you can limit access to specific records to specific users.

**Comment by NorthFred** [comment]
Thanks for getting back so quickly.

The problem with using the multiTenancy handler, is that on the one hand, the user should be able to get  access to all Public data from the same table, as where the Private data is located. But there doesn't seem to be that possibility to return the data based on a 'private' filter (column filter) in combination with the unique 'userId' column value?

Then again,when looking into the authorization recordhandler, there doesn't seem to be the option to use the 'userId' for specific record access.

What I am looking after is basically a multiTenancy handler, which can use the same behavior / filters of the authorization recordhandler.

**Comment by NorthFred** [comment]
I am trying to visualize here what I am after:

		'multiTenancy.handler' => function($operation, $tableName) {
		    if ($tableName === 'DataRecords') {
		      if (in_array($operation, ['read', 'list'])) 
		      {
		          return ['userId' => $_SESSION['claims']['user_id']];
				  
	                           * And here add a condition to only check for 'userId' if the column 'private' is set to 1.
                                   * If the column 'private' contains value 0, then we don't check for the userId (there is none for public records)
		      }
		    }
	    },

**Comment by mevdschee** [comment]
Ah.. I see... you would want a "`userId = ? or userId IS NULL`" kind of condition, right?

**Comment by NorthFred** [comment]
> 
> 
> Ah.. I see... you would want a `userId = ? or userId IS NULL` kind of condition, right?

Correct, something along those lines. Not sure whether it is possible to achieve at the moment?

**Comment by mevdschee** [comment]
>Not sure whether it is possible to achieve at the moment?

It should be possible, as you can implement arbitrary difficult row based access control using the 'authorization.recordHandler'.

See: https://github.com/mevdschee/php-crud-api/blob/master/tests/config/base.php#L31

Please try it out and report any problems you may run into.

**Comment by NorthFred** [comment]
Thanks, I got a little further and managed to apply an Update operation which is limited to only user's own dataRecords.
But the read/list operation is still giving me a headache, as I can't seem to apply the correct condition for allowing reading/list of owner's private records and also allow public to all...

```

        'authorization.recordHandler' => function ($operation, $tableName) {
            if ($tableName == 'DataRecords') {
                // Only allow update of User's Own Private Records  (<------- This works fine!)
                if ($operation == 'update') {
                    return ($tableName == 'DataRecords') ? "filter=private,eq,1&&filter=active,eq,1&filter=userId,eq,{$_SESSION['claims']['user_id']}" : '';
                }
                // When reading Private Records, only return the User's Own Records - but allow reading the Public ones
                if (in_array($operation, ['list', 'read'])) {
                    return ($tableName == 'DataRecords') ? "filter=private,eq,1&&filter=active,eq,1&filter=userId,eq,{$_SESSION['claims']['user_id']}" : '';
                }
            }
        },
```

How could I translate this to:

        'authorization.recordHandler' => function ($operation, $tableName) {
            if ($tableName == 'DataRecords') {
                // When reading Private Records, only return the User's Own Records - but allow reading the Public ones
                if (in_array($operation, ['list', 'read'])) {
                    if (the user applies a private filter in the request) {
                        return 'DataRecords' if the userId equals the claims
                    }
                    if (the user does not apply any filter) {
                       return 'DataRecords' which are public.
                }
            }
        },

It seems trivial to do, but I am having problems making the condition to work :(

**Comment by NorthFred** [comment]
OOoww.... It seems writing out my question above, made me realize something...  It's possible to combine AND and OR statements in filters by **repeating the filter with the number**...  So this lead to this:

```
                if (in_array($operation, ['list', 'read'])) {
                    return ($tableName == 'DataRecords') ? "filter1=private,eq,1&filter1=active,eq,1&filter1=userId,eq,{$_SESSION['claims']['user_id']}&filter2=private,eq,0&filter2=active,eq,1" : '';
                }
```

I will do some more testing, but so far it looks like this is what I was after.  Thanks for all the help, once again!

**Comment by mevdschee** [comment]
> It's possible to combine AND and OR statements in filters by repeating the filter with the number

Or by appending a letter.. 

See: https://github.com/mevdschee/php-crud-api#multiple-filters

**Comment by NorthFred** [comment]
Issue can be closed 👍
