### ISSUE TITLE
Authentication failed for 'JWT'

### ISSUE THREAD

**Issue by xelenttechnologies** [mevdschee/php-crud-api#708]
Hello Maurits,

Hope you are doing well and staying safe! Thank you for this great piece of work.

I am implementing this in one of our new projects and everything works great, though I am facing an intermittent issue with JWT authentication. The issue is persistent whether its tested using Postman or Angular integration. Everything will keep working fine for days but suddenly will start getting below response -

```
{
    "code": 1012,
    "message": "Authentication failed for 'JWT'"
}
```

This response will continue for few requests and then the correct response from table will come. Below is the configuration and code for JWT Authentication -

```
        //code to fetch jwt key and secret
	$rawPublicKeys = file_get_contents('https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com');
	$keys = json_decode($rawPublicKeys, true);
	$keyKidsArray= array_keys($keys);
	$pKeysArray = array_values($keys);
	$secrets = $keyKidsArray[0] . ':' . $pKeysArray[0] . ',' . $keyKidsArray[1] . ':' . $pKeysArray[1];
```

```
        $config = new Config([
			'driver' => 'mysql',
                        'address' => $MYSQL_HOST,
			'username' => $MYSQL_USER,
			'password' => $MYSQL_PASS,
			'database' => $MYSQL_DB,
			'debug' => $DEBUG,
			'controllers' => 'records,openapi',
			'middlewares' => 'cors,jwtAuth,authorization,multiTenancy,customization',
			'cors.allowedOrigins' => '*',
			'cors.allowHeaders' => 'X-Authorization,Accept,Content-Type,Referer,User-Agent',
                        'cors.allowMethods' => 'GET,POST,PUT,OPTIONS',
                        'jwtAuth.secrets' => $secrets
                     ]);
```

I am so far unable to figure out what's causing this. Any help or direction on this will be appreciated.

Regards,  
A J

**Comment by mevdschee** [comment]
Could it be that the server on "https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com" is not responding? Can't you cache that result in case the response comes in empty?

**Comment by xelenttechnologies** [comment]
Hello Maurits,

Thank you for your reply. Though the similar URL of google apis works perfectly fine if tried with Angular. I will give cache a try and revert.

Regards,
 A J

**Comment by mevdschee** [comment]
>Though the similar URL of google apis works perfectly fine if tried with Angular.

because front-end technology might use cached contents

**Comment by mevdschee** [comment]
Any update?

**Comment by xelenttechnologies** [comment]
Hello Maurita,

Apologies for a late response. This issue is not coming now after Angular developer has done some changes as his end for caching.

Thank you for suggestion and response.

**Comment by mevdschee** [comment]
You are welcome. I'm closing the issue for now. Feel free to re-open if the issue appears again.

**Comment by xelenttechnologies** [comment]
Sure, thank you...and once again thank you for this great piece of software :).
