### ISSUE TITLE
Error when requesting tables with relationship

### ISSUE THREAD

**Issue by cooperdk** [mevdschee/php-crud-api#709]
I am calling /records/tags/1?join=aliases

where aliases rows refer to a row in tags. One "tags" to many "aliases".

For me, the above request yields this error:

{"code":9999,"message":"Call to a member function getName() on null"} 

IF I call it like /records/tags?join=aliases I get the following error:

{"code":9999,"message":"Argument 1 passed to Tqdev\\PhpCrudApi\\Record\\Condition\\ColumnCondition::__construct() must be an instance of Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedColumn, null given, called in (...)\/api.php on line 5509"}

Any idea what's wrong? I am running PHP 7.4.

**Comment by mevdschee** [comment]
Do both tables have primary keys?

**Comment by cooperdk** [comment]
I changed the table structure a bit so there is no error now BUT the join doesn't happen.
I have in tags table, fx a tag id 82 name tag1
and in the aliases three rows with tag_id 82 and their names.

(It doesn't matter if the column is named "tag_id" or "tags_id", the script doesn't pick up on the relation)

The tags table has this structure:
id int auto pk
tag str
thumb str

And the aliases table has this structure:
id int auto pk
tag_id int 
alias str

I appreciate your interest in my debugging :-)

**Comment by cooperdk** [comment]
Sorry, I got it to work.

It seems that your script depends on foreign key constraints (I hadn't read that) and that only works on INNODB tables, so after altering the tables and creating the foreign key constraint, it now works. Thanks :-)

**Comment by mevdschee** [comment]
> I got it to work.

Great! It indeed requires foreign key constraints to detect the relationship. It may fall back to naming convention for views. I'm happy for you that it works now. Enjoy the sofware!

Kind regards, Maurits
