### ISSUE TITLE
Authentication using an API key

### ISSUE THREAD

**Issue by cooperdk** [mevdschee/php-crud-api#715]
Hey,

I have a user table (in the db connected with php-crud-api).
In this table, I have an API key generated with a hash based on user id and username (actually the table is API_Editor_Users and the field is called api_key). It is a web based editor based on PHPrunner, which has it's own REST API but I don't like it (too simple).

Is it possible to make your system recognize this field value as an auth token,  like below? I couldn't really determine it based on your readme.

curl -H "X-Auth-Token: $2y$10$nbtC/UY05wzN9hjTYAGf8Om.k28f3MnI1VqWe4zx1Z3sU.zHNSE9W" "site/records/tags/..."

**Comment by mevdschee** [comment]
Hi,

Thank you for your question. I'm certain that you can write a middleware to do this. If you do and it would be generic enough then I would consider to support it as it is quite a common scheme. Look at the following lines where the credentials are read (you should read your header) and the `$_SESSION` variable is set:

https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Middleware/BasicAuthMiddleware.php#L91-L99

Same happens here, but this middleware looks data up in a database table:

https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Middleware/DbAuthMiddleware.php#L46-L71

I hope this inspires you to contribute a `DbApiKeyMiddleware.php` file as it is merely a mix of those two approaches.

Kind regards,

Maurits

**Comment by cooperdk** [comment]
I will consider the middleware suggestion and check out the code you posted. Thanks for your reply :-)

**Comment by mevdschee** [comment]
This is implemented in v2.12.0. Feel free to open an new issue when you encounter problems with it.
