### ISSUE TITLE
Support JSON options (such as pretty printing)

### ISSUE THREAD

**Issue by cooperdk** [mevdschee/php-crud-api#716]
Thanks for your previous replies. 

I have one more question, and it has to do with reading a lot of JSON, especially during testing.

Is there a way to indent-format the output code within the API, aka "prettify"? At least so that it isn't output in one long go, but at least so each record is separated.
I have looked at the code and it is pretty confusing to determine what happens where. I would rather not tunnel it thru something else in order to do so. :-)

In fact, I wanted to do something along the lines of:

$output = json_encode($data, JSON_PRETTY_PRINT);

This also follows the JSON "best practice".

Best regards, cooperdk

**Comment by cooperdk** [comment]
I just found [this old reply](https://github.com/mevdschee/php-crud-api/issues/564#issuecomment-519438132)

But it's not working for me.

**Comment by mevdschee** [comment]
Thank you for opening this issue. I understand you want to pretty print the output.

>This also follows the JSON "best practice".

No it does not. Also, your browser has pretty print functionality built in. So, why do you need it in the output?

>But it's not working for me. 

It should look like this:

    'customization.afterHandler' => function ($operation, $tableName, $response, $environment) {
        $json = json_decode($response->getBody()->getContents());
        return ResponseFactory::from(200, 'application/json', json_encode($json, JSON_PRETTY_PRINT));
    },

To do the pretty format trick. Also do load the customization middleware using:

    'middlewares' => 'cors,customization',

In the config. Please let me know whether or not this works and if you have any further questions.

**Comment by cooperdk** [comment]
> Thank you for opening this issue. I understand you want to pretty print the output.
> 
> > This also follows the JSON "best practice".
> 
> No it does not. The best practice for an API is to send the data without pretty print. Your browser has pretty print functionality built in. So it is not clear to me why you need it in the output, but nevertheless I'll try to help you achieve it.

I don't understand why examples on json.org are pretty printed, if that's not the intended format. Nowadays, we don't have to consider the few extra bytes required to format so that the data is also human readable, at least until the frontend stuff is done.

https://json.org/example.html

> > But it's not working for me.
> 
> The afterHandler should look like this to do the pretty format trick:
>...
> In the config. Please let me know whether or not this works and if you have any further questions.

Inserting his snippet worked. The code is a bit different from the older config lines I found in another thread.
As a suggestion, this could be configurable, fx as a parameter "pp" so one could pretty print during development. Or, it could be mentioned in the readme?

Thanks for your reply.

**Comment by mevdschee** [comment]
> fx as a parameter "pp" so one could pretty print during development. 

Or we could automatically pretty print when debug is enabled.

**Comment by cooperdk** [comment]
Whichever works for you. I am just not familiar with Laravel, so I would be happy with something in the readme.
You solved my "problem", so thanks for your time :-)

**Comment by mevdschee** [comment]
We may support json encoding options, such as:

- unescaped utf8
- unescaped json
- pretty printing

see flags here: https://www.php.net/manual/en/function.json-encode.php

**Comment by mevdschee** [comment]
Implemented in #877

**Comment by mevdschee** [comment]
Released in v2.14.2
