### ISSUE TITLE
Sending a POST batch insert using javascript

### ISSUE THREAD

**Issue by innerskyone** [mevdschee/php-crud-api#718]
How can I do a batch create using javascript? If I understand it correctly, I have to send in URL format as JSON isn't supported. Is this actually possible?

I tried sending something like this in the body, but it inserts only a single record in the table.

id=745&userid=1&name=testA&url=""&parentId=1&col=3&ord=1&color=black&open=0&shw=1,id=746&userid=1&name=testB&url=""&parentId=1&col=3&ord=1&color=black&open=0&shw=1

PS This is such an awesome project.

--
Thanks,
Bart

**Comment by Zhangirkhan** [comment]
to add any lines, you need to use a POST request. It seems to me that you are using the GET method. Or send a piece of code where you wrote, I'll try to figure it out.
Try using POSTMAN (Json format)

```
POST /records/posts
{
    "title": "Black is the new red",
    "content": "This is the second post.",
    "created": "2018-03-06T21:34:01Z"
}
```

**Comment by mevdschee** [comment]
Thank you for reporting this issue. You should send a json body instead:

    id=745&userid=1&name=testA&url=""&parentId=1&col=3&ord=1&color=black&open=0&shw=1,id=746&userid=1&name=testB&url=""&parentId=1&col=3&ord=1&color=black&open=0&shw=1

It shouls be:

    [
        {
            "id": 745,
            "userid": 1,
            "name":"testA",
            "url": "",
            "parentId": 1,
            "col": 3,
            "ord": 1,
            "color":"black",
            "open": 0,
            "shw": 1
        },
        {
            "id": 746,
            "userid": 1,
            "name":"testB",
            "url": "",
            "parentId": 1,
            "col": 3,
            "ord": 1,
            "color":"black",
            "open": 0,
            "shw": 1
        }
    ]

I hope that helps! Kind regards, Maurits

**Comment by innerskyone** [comment]
Yes this works perfectly. I had tried this before but got eacht time a 409 error. (I forgot to replace the = by :)

Thank you!
