### ISSUE TITLE
Postgresql database integration with slim4 php using php-crud-api query

### ISSUE THREAD

**Issue by haider0324** [mevdschee/php-crud-api#719]
Hi Experts,

Need to build an app server application using slim4 php and postgresql database. Could you please help me out generate api's from postgresql database using _php-crud-api_. 
I follow this post https://tqdev.com/2019-automatic-api-slimphp-4 but from this point _Install PHP-CRUD-API_, i am not able to get what i need to do 
Where should i provide postgresql database connection details etc
Generate api from postgresql database
Not able to understand _app/routes.php_ code

Thanks in advance

**Comment by mevdschee** [comment]
Thank you for creating this issue. What exactly did you execute? What are the error messages? The post assumes the postgresql server is on localhost, but you can specify other config parameters (driver, address, port) next to the existing (username, password, database) to solve your problem.

I hope this helps.

**Comment by haider0324** [comment]
Thanks for your quick response

Basically i am stuck in _Installation_ section of _php-crud-api_ . I am not able to overcome this line
 `PHP 7.0 or higher with PDO drivers for MySQL, PgSQL, SqlSrv or SQLite enabled`

I am confused how to use _php-crud-api_  with my postgresql local database. How to install _php-crud-api_ and use with slim4 php.

Thanks

**Comment by mevdschee** [comment]
Did you download or install composer (see: https://getcomposer.org/)? Did you manage to run the composer command?

    curl https://getcomposer.org/composer-stable.phar -o composer.phar
    php composer.phar require mevdschee/php-crud-api

Does that help you?

**Comment by haider0324** [comment]
I apologize for taking your time. Great Thanks for looking into this query

Please have a look what i have done so far. Currently i am using MAC OS Catalina

**Composer SetUp and Install Command**
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'c31c1e292ad7be5f49291169c0ac8f683499edddcfd4e42232982d0fd193004208a58ff6f353fde0012d35fdd72bc394') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

**Install Slim SlimPHP 4 for Automatic REST API Commands**
php composer.phar create-project slim/slim-skeleton slimrestpgapi
cd slimrestpgapi
mv ../composer.phar .
php composer.phar start

**Install PHP-CRUD-API but it doesn't work**
php composer.phar require mevdschee/php-crud-api
and done changes in app/routes.php file as well

but in project folder config directory not found and when i put following details in

**Comment by mevdschee** [comment]
Change:

    $config = new Config([
      'username' => 'php-crud-api',
      'password' => 'php-crud-api',
      'database' => 'php-crud-api',
      'basePath' => '/api',
    ]);

Into:

    $config = new Config([
      'driver' => 'pgsql',
      'username' => 'php-crud-api',
      'password' => 'php-crud-api',
      'database' => 'php-crud-api',
      'basePath' => '/api',
    ]);

To make a PostgreSQL instead of a MySQL connection.

**Comment by mevdschee** [comment]
Also try to connect to your slim application on the "/api" path. What is the result? Are there errors in the error log?

**Comment by haider0324** [comment]
I got this following error while including driver
<img width="1440" alt="Screenshot 2020-10-22 at 11 23 11 AM" src="https://user-images.githubusercontent.com/3973130/96830453-1e6c7000-1459-11eb-9847-176beb8722f2.png">

I know i am doing mistake config folder is not present in my directory. Even i run the command php composer.phar require mevdschee/php-crud-api

**Comment by mevdschee** [comment]
Can you check the following path?

    vendor/mevdschee/php-crud-api/src/Tqdev/PhpCrudApi/Config.php

Can you ensure `composer.json` has the following (in the require section)?

      "mevdschee/php-crud-api": "*",

I hope this clears things up.

**Comment by haider0324** [comment]
No this path and file not exits in my source code folder.
<img width="298" alt="Screenshot 2020-10-22 at 1 44 40 PM" src="https://user-images.githubusercontent.com/3973130/96844317-fd157f00-146c-11eb-89b6-a266ecac3c1b.png">

and also it didn't find in composer.json as well
<img width="268" alt="Screenshot 2020-10-22 at 1 45 10 PM" src="https://user-images.githubusercontent.com/3973130/96844365-0c94c800-146d-11eb-8541-911b25a7f2a6.png">

**Comment by haider0324** [comment]
Thank You @mevdschee , It's working now
<img width="760" alt="Screenshot 2020-10-22 at 1 55 43 PM" src="https://user-images.githubusercontent.com/3973130/96845478-621da480-146e-11eb-975a-b1d2a653a369.png">

I just want to know how we generate api classes in our code. Suppose i have existing database and based on that they will generate crud api services for each table. Create models, services etc based on database tables in postgresql database.

**Comment by mevdschee** [comment]
>I just want to know how we generate api classes in our code.

You don't have to, the code uses reflection.

>Create models, services etc based on database tables in postgresql database.

If that is what you want, maybe uninstall this library and try:

https://github.com/slimphp-api/slim-api

**Comment by haider0324** [comment]
Great Thanks @mevdschee for helping and guiding me

**Comment by mevdschee** [comment]
You are welcome, I'm happy to help you with any further issues you encounter!
