### ISSUE TITLE
Transform on empty Resultset shows Notice and Warning

### ISSUE THREAD

**Issue by LukasGrebe** [mevdschee/php-crud-api#72]
using transform=1 and filters that return 0 records, results in:

> <b>Notice</b>:  Undefined index: records in <b>/api.php</b> on line <b>1538</b><br />
> <br />
> <b>Warning</b>:  Invalid argument supplied for foreach() in <b>/api.php</b> on line <b>1538</b><br />
> 

Fixed by setting `error_reporting(E_ERROR | E_PARSE);` Notice and warning were on by default on my setup…

**Comment by mevdschee** [comment]
Thank you for your contribution. Another excellent find! 

See: 2b30959bc2d2e887810bc565c08cabc676a029c2

Please keep reporting these high quality issues! :+1:
