### ISSUE TITLE
Error 500 on POST: Incorrect string value

### ISSUE THREAD

**Issue by nilopaim** [mevdschee/php-crud-api#721]
Maurits, congratulations for this wonderful piece of software.

But I'm facing a problem...

My Mysql database contains the table:

```
create table users (
	id int primary key autoincrement,
	name varchar(40) not null,
	email varchar(40) not null,
	passwd varchar(10) not null,
	corporate tinyint default 0,
	blocked tinyint default 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) engine=innodb;
```

My Vue application sends the following snippet:

```
        axios
          .post("http:/myurl.com/api.php/records/users", {
            name: this.currentUser.name,
            email: this.currentUser.email,
            passwd: this.currentUser.passwd,
            corporate: this.currentUser.corporate ? true : false,
            blocked: this.currentUser.blocked ? true : false,
          })
          .then(function (response) {
            console.log("Normal response: ", response);
          })
          .catch(function (error) {
            console.log("Error response: ", error);
          });
```

Problem: It returns error 500 when the string vaariable this.currentUser.name contains accentuated characters.

When I have "Rogério" on name variable the error is **SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC3\xA9rio ... for column 'name' at row 1**

Any workaround or I just missed something?

**Comment by mevdschee** [comment]
Hi Nilo, thank you for your kind words and for opening this issue. What is the character set of the target table and what is the collation of the column 'name'? Since JSON is by definition UTF8 I do recommend you to use character set `utf8mb4` and collation `utf8mb4_general_ci`. You can find these settings in the table create statement or in the MySQL server defaults.

**Comment by mevdschee** [comment]
A good test case is this character, as it is a 4 byte utf8 emoji: 👋

**Comment by nilopaim** [comment]
Maurits,

Changed my table definition to 

`create table users (
	id int AUTO_INCREMENT primary key,
	code varchar(15) not null, 
	name varchar(40) not null,
	email varchar(40) not null,
	passwd varchar(10) not null,
	corporate tinyint default 0,
	blocked tinyint default 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) engine=innodb CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;`

Works like a charm!

Thanks for your prompt answer and again, congrats for your fantastic work.

**Comment by mevdschee** [comment]
Thank you, your kind words mean a lot to me.
