### ISSUE TITLE
Default filter

### ISSUE THREAD

**Issue by jonguerre** [mevdschee/php-crud-api#722]
Hello,

I have three little questions:

1. It is possible to set a “default” table filter for the “list” operations ? This default filter will be overwritten if a filter query parameter is set in the URL. Perhaps with the customization.beforeHandler controller ?
2. How can i set this where clause with the filter parameter ?:
where ((field1=value1 and field2=value3) or field3=value4)
4. It is possible to authorize only the “list” and “read” operations ? something like a read-only mode.

Many thanks in advance for your help.

Regards,

Jonathan

**Comment by mevdschee** [comment]
Hi Jonathan,

Thank you for opening this issue.

>It is possible to set a “default” table filter for the “list” operations ? This default filter will be overwritten if a filter query parameter is set in the URL. Perhaps with the customization.beforeHandler controller ?

Yes, this is possible, you could do this in a middleware or just with a line like this (on top of the file):

    if (!$_SERVER["QUERY_STRING"]) {
      $_SERVER["QUERY_STRING"] = 'filter=some,eq,thing';
    }

>How can i set this where clause with the filter parameter ?:

    filter1=field1,eq,value&filter1=field2,eq,value3&filter2=field3,eq,value4

>It is possible to authorize only the “list” and “read” operations ? something like a read-only mode.

You can do this by returning "false" in the "authorizationHandler" for other "action" values than "list" and "read".

I hope this gets you started. Let me know what you run into.

**Comment by jonguerre** [comment]
Hi Maurits,

many thanks for your quick feedback and your help.

It is possible to set a filter with the "customization.beforeHandler" controller? something like this:

`'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
$param = $request->getQueryParams();
$param["filter"] = "field1,eq,value1";
$request->withQueryParams($param);            
}`

Many thanks.

Kind regards, Jonathan

**Comment by mevdschee** [comment]
Yes, I think you can :-)

**Comment by jonguerre** [comment]
Hi Maurits,

i tried this but the filter ist not set:

`'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
  $param = $request->getQueryParams();
  $param["filter"] = "field1,eq,value1";
  return $request->withQueryParams($param);            
}`

Thanks

Jonathan

**Comment by mevdschee** [comment]
Try this:

    'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
        return $request->withUri($request->getUri()->withQuery("filter=field1,eq,value1"));
    },

It should work.

**Comment by jonguerre** [comment]
Perfect it works fine :-)

Many thanks for your help
