### ISSUE TITLE
Recommandation needed: Disable possibility to POST unauthorized data

### ISSUE THREAD

**Issue by odcey** [mevdschee/php-crud-api#726]
Hi,
First, thank you for this great project.

So i'm playing with the database & given examples.
Concerning "Posts" table, it has foreign key `user_id`.

I'm trying to prevent the connected User (lets say id 3) to insert a `post` with `user_id` = 4 (Basically trying to prevent user to post data not associated to its id)

What is the best method to do this ?

Right now i'm using beforeHandler, but not sure if it is the best way to do this
```php
'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
        if ($tableName == 'posts' && $operation == 'create') {
            $userId = $_SESSION['user']['id'];
            $postUserId = $request->getParsedBody()->user_id;
            if ($userId != $postUserId) {
                return $request->withParsedBody(null);
            }
        }
    },
```
By the way, returning a body with null data works but seems hacky,it returns:
```json
{
    "code": 1008,
    "message": "Cannot read HTTP message"
}
```
Is there a way to throw an error "Unauthorized" from there, with the right HTTP status maybe ?

Thank you !

**Comment by mevdschee** [comment]
Hi, Thank you for creating this issue. Maybe the 'multiTenancy' middleware fits your need. It allows you to add an owner column to your tables and filter on that on list, read, update and delete, while setting it to a value on creation of the record.

**Comment by odcey** [comment]
Hi, Thank you for your quick reply.
So i tried to do it with multiTenancy middleware like this:
```php
'multiTenancy.handler' => function ($operation, $tableName) {
        if($tableName == 'posts' && $operation == 'create'){
            return ['user_id' => $_SESSION['user']['id']];
        } else {
            return [];
        }
    },
```

The post was 
```json
{
    "user_id": 1,
    "category_id": 2,
    "content": "Trying forbidden insert"
}
```

And the connected user's id was `2`.
So i espected it to fail. But the insert was successful.
Am i doing this wrong ?

Thank you

**Comment by odcey** [comment]
Okay,
I didn't have a look at the created row in the database (was just expecting it to fail)
I understand now that returning `['user_id' => $_SESSION['user']['id']];`is overriding this value in the body of payload
This kind of fits my need. 

But maybe later i'll need the query to fail if some of the custom value from the post/put request isn't allowed, how do i do that ?
Thank you

**Comment by mevdschee** [comment]
>But maybe later i'll need the query to fail if some of the custom value from the post/put request isn't allowed, how do i do that ?

This value that you set on create is also used as a filter on read, list, update and delete. Try removing the `&& $operation == 'create'` from your handler.

**Comment by odcey** [comment]
Alright thank you for your responses ! And for this great project
