### ISSUE TITLE
dbAuth and xsrf

### ISSUE THREAD

**Issue by caltabid** [mevdschee/php-crud-api#730]
Hi, congratulation for the great library and work!
I'm trying to setup a simple backend with dbAuth and xsrf middlewares.
I found the following problems:

1. login calls fail when there is no xsrf and there should not be xsrf in login since it is generally the first call to the backend. xsrf cannot be excluded, you could "excludeMethods" all "post", but then the middleware would be useless.
I hard-coded an exception in the xsrf middleware if "($method == 'POST' && $path == 'login')".
It does not seem a clean solution, any other option?
2. xsrf token is only sent in the cookie, should it be returned by login in the json?
I hard-coded a patch in both middlewares: saving the token in "$_SESSION['token']" in xsrf middleware and returning "$result = (object) array('token' => $_SESSION['token'], 'user' => $user)" instead of just the "user" in dbAuth middleware.
It does not seem a clean solution, any other option?
3. "customization" callbacks "beforeHandler" and "afterHandler" are not called on login, therefore I did not find a simpler solution to points 1 and 2.
4. how can I implement a simple signup? It should be a post in the user without xsrf? another exception to hard-code in the xsrf middleware?
5. After Signing-up I should send an email with a confirmation link, here I should be able to use the afterHandler, but when the user confirm in the front-end I would again need to do a put on the user table without xsrf to unlock the user?
6. What about forgot-password: I should send a verification email, how? 
7. I did not find any test/examples using both dbAuth and xsrf middlewares, did I miss them?

Can you help?

**Comment by mevdschee** [comment]
Hi, thank you for opening this issue. I'll try to answer all your questions.

> 1. login calls fail when there is no xsrf

You could sent a GET request to receive a cookie before sending the login request (which is indeed protected by xsrf). A good way would be to send a GET to the new '/me' endpoint to see whether or not login is required.

> 2. xsrf token is only sent in the cookie, should it be returned by login in the json?

No, this called the double submit method. You submit the same value in a cookie as in the xsrf request header.

> 3. "customization" callbacks "beforeHandler" and "afterHandler" are not called on login, therefore I did not find a simpler solution to points 1 and 2.

And this should not be needed (hopefully).

> 4. how can I implement a simple signup? It should be a post in the user without xsrf? another exception to hard-code in the xsrf middleware?

There is nothing about xsrf that complicates implementing a signup, which in itself can be challenging.

> 5. After Signing-up I should send an email with a confirmation link, here I should be able to use the afterHandler, but when the user confirm in the front-end I would again need to do a put on the user table without xsrf to unlock the user?

If you want to bypass the xsrf in beforeHandler, then you should set a xsrf requestheader and a xsrf cookie with the same values. Note that you need to load the customization middleware before the xsrf middleware by ordering them appropriate in the 'middlewares' config parameter.

> 6. What about forgot-password: I should send a verification email, how?

You may use the beforeHandler and call the PHP's 'mail' function.

> 7. I did not find any test/examples using both dbAuth and xsrf middlewares, did I miss them?

No, but feel free to contribute them. I'm happy to add examples or link to them.

**Comment by mevdschee** [comment]
Note that in the latest release I added a "/register" endpoint that needs to be enabled using the "dbAuth.regsiterUser" config parameter.

**Comment by mevdschee** [comment]
I'm assuming your questions are answered. I'm closing this ticket now. Feel free to open a new one.
