### ISSUE TITLE
Get records given starting latitude and starting longitude and distance

### ISSUE THREAD

**Issue by lupohirp** [mevdschee/php-crud-api#731]
Hi,

impressive work. I have a question : how i can get records given starting latitude and longitude and distance? 
For example : i have two columns for my records , ie latitude and longitude, and i want to filter given starting latitude and longitude  and maximum distance from input latitude and longitude. 

It' s possible to do that?

**Comment by mevdschee** [comment]
>It' s possible to do that?

No, it currently is not supported.

**Comment by mevdschee** [comment]
If you precalculate the circle-like polygon around the point, then you can do a spatial 'within' or  filter. Using:

    api.php?filter=geo,swi,polygon(...)

I hope this helps.

**Comment by mevdschee** [comment]
Related to #98

**Comment by lupohirp** [comment]
have resolved using sp_api, i have write a stored proceudre and called the sp_api.php. These data can be exposed on internet without authorization. I have opened another issue regarding registration/ signup with dbAuth security. Can you check please?

Thanks

**Comment by mevdschee** [comment]
I think the workaround I proposed (and the one you've chosen) fit most use cases, so I hope you don't mind me closing the ticket.

NB: I commented on the other issue.
