### ISSUE TITLE
standalone config file

### ISSUE THREAD

**Issue by adrianvoica** [mevdschee/php-crud-api#734]
Hello Maurits,
Please consider adding a check for the existence of a standalone config file in the same directory as the **api.php** file - maybe **api.config.php** is a good fit - that would contain the configuration data, instead of having to modify api.php. 

This way, if api.php finds a file called api.config.php, it uses its contents as the configuration data (the $config object as declared in api.php), so that when a new version of the api.php is released, we can just upload the file without worrying about (accidentally?) overwriting the config (unless we add config options for new and shiny features!).

Thanks!

**Comment by mevdschee** [comment]
The file is build in the same step as the "api.php" and is called "api.include.php". You should name your config "api.php" and include the "api.include.php" from there. Does that work for you?

**Comment by adrianvoica** [comment]
Sorry - not willing to undermine your work in any way - but I don't think that this is a good direction, both semantically and architecturally. 
I think api.config.php would have been a better fit (at least, that's my humble opinion) since it would reflect just what it does (contains). 
My idea for this enhancement was somehow, quite in the opposite relation (api.php **uses/has** the api.config.php). 
The generic vision was that api.php keeps defining the $config object inside it (for not breaking legacy code at all), and that object, if found inside api.php has priority over the external config. but if an external config is found, it is used, unless otherwise specified. 
Again, sorry for this misdirection/confusion. Please don't rush thing into releases just to keep everyone happy. Everything can wait. 
And, I must emphasize, again, you work is stellar and super-helpful. Because of your work, I got back into using php-based backend services. You seem to always give 100%. Keep up the energy!

**Comment by mevdschee** [comment]
Thank you for your kind words. I understood you expected the opposite relationship. I thought that using api.include.php as a library, but loading the config from an external file was more in line with how people use PHP (generally). Can you elaborate on why this does not work for you? I understood your vision and your expectation, but I need a use-case and reasons.

>You seem to always give 100%. Keep up the energy!

I try to treat others like I would like to be treated when opening issues on open source repos. I'm glad you like it!

**Comment by adrianvoica** [comment]
Well, here are 2 of my use-cases:
1) I have a (cheap) php hosting with cpanel, everything just works. I have a few domains and some subdomains hosted there. As I work on stuff, I copy/move stuff around and between subdomains. At some point (actually, more than once), I copied some api.php file from one subdomain to another, and nothing seemed to work correctly afterwards... until I realised what I had done... was linking to the wrong DB, of course, because of the config... so, having a separate config that I could fine-tune individually would help in these situations. 
2) Another time, I just uploaded the latest version of api.php, and, boom! lost the config (sadly, no backup for DB credentials, so I had to reset the DB user credentials, but I don't have access to the cPanel all the time - sometimes I just upload via FTP so I had to wait a few hours until I got home to reset it).
I hope this adds some stamina to this enhancement's vision. :) 
Cheers!

P.S.: by rushing, I mean not letting it (the idea) settle down, digest it thoroughly, maybe it doesn't align with your philosophy, since this project is your "baby". At least, today things moved quite fast from opening the issue until going to production. I have no doubt about the code quality. Godspeed!

**Comment by mevdschee** [comment]
Thank you for your elaborate reply and I can fully understand how a file containing code and configuration is problematic for your use case. But a question that is still unanswered for me is how it matters which way around the include is done (config-to-code vs code-to-config)?

**Comment by adrianvoica** [comment]
I think going from code to config is the standard semantic way. The code should know about the config, about its structure, about how to use it, but the config has no "power" without the code. We can say that config files are just satellites orbiting around code. Besides, it's nice to not touch external code at all. 
Usually, it's the old saying "convention over configuration". Here, we are talking about convention FOR configuration. :)

**Comment by mevdschee** [comment]
Okay, I'm still not convinced, so I'll leave the functionality as it is now.

**Comment by adrianvoica** [comment]
Hi Maurits, 
Actually, I kept thinking about this. All the great tools of our time (especially the CLI tools) have default configuration files. If no file is specified upon execution, those tools look for their specific config (external, but unique/specific) file. 
I see api.php as a CLI tool (conceptually). That's why having a specific external config seems like the "natural" choice. 
E.g.: composer has composer.json, npm has package.json, webpack has webpack.config.js, gulp has gulpfile.js and so on. 
So, I would consider modifying the internal config (inside api.php) analogous to setting a specific config file for a CLI tool instead of going for the default config file. That was my reasoing behind all this. Just for the sake of clarifying things. Cheers!

**Comment by adrianvoica** [comment]
Well, hello again! ... after a break from hobby projects, here I am. Tried to use api.include.php, but, (please forgive me), how the heck are you supposed to use it? Create the $config object then include the api.include.php? or the other way around? I'm confused. I still think that making api.php look for a specific file (named "api.config.php" for instance) would have been a safer bet. Just my 2cents. Nothing to change, nothing extra to include, just... run. :) Cheers! I'll figure it out, eventually.

**Comment by mevdschee** [comment]
A bit late, but this is how I use it in a file `index.php`:

    <?php

    namespace Tqdev\PhpCrudApi;

    use Tqdev\PhpCrudApi\Api;
    use Tqdev\PhpCrudApi\Config;
    use Tqdev\PhpCrudApi\RequestFactory;
    use Tqdev\PhpCrudApi\ResponseUtils;

    require_once 'api.include.php';
    include 'secrets.php';

    $config = new Config($secrets+[
        'basePath' => '/api/',
        'driver' => 'sqlsrv',
        'controllers' => 'records,openapi,status'
    ]);
    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    ResponseUtils::output($response);

I hope this helps.

**Comment by adrianvoica** [comment]
Yesss! Thank you a million times, Maurits! Cheers!
