### ISSUE TITLE
Fediverse SNS

### ISSUE THREAD

**Issue by BenitoJedai** [mevdschee/php-crud-api#735]
@medvsche hi sir i decide to use this lib to acelerate build of my fediverse microblogging sns but i have a question...
How i can add custom endpoints? 
I personally prefer the v1 versión of this lib and custom output models
For example inteads clasic table json
```
Id:55
Name: Ben 
```
Change to
```
UserID:Tablename.id
User:Tablename.user
```

**Comment by mevdschee** [comment]
Hi, thank you for opening this issue. I'll try to help you.

> How i can add custom endpoints?

This is not yet supported (see #729).

> I personally prefer the v1 versión of this lib and custom output models

This version is no longer supported.

> For example inteads clasic table json, Change to

I'm not sure what the translation is that you have in mind. Can you explain this with more/better examples?

**Comment by mevdschee** [comment]
Any update?

**Comment by BenitoJedai** [comment]
@mevdschee for the moment i change the my database schema and some changes i add in javascript level in the frontend but when i released the first versión of this **SNS**  in github you can view how i use you **API PHP** lib and help me to add the mentioned features in the core lib..

**Comment by BenitoJedai** [comment]
Your lib provide for me a ultra fast way to mount a complete Solid API Backend without tears

**Comment by BenitoJedai** [comment]
@mevdschee also you consider in future add realtime features to your lib in the core or like extension module..

**Comment by mevdschee** [comment]
I see. Would you mind re-opening or filing a new issue when you can further specify/demonstrate your question with a working example?
