### ISSUE TITLE
Working / Not working after refresh... "code":1000 - not found

### ISSUE THREAD

**Issue by kubajjz** [mevdschee/php-crud-api#737]
Hi, I put the file on server and it is working SOMETIMES...
Usually it works for 1. operation, but for next operation I got error. Or If I refresh the link:
- http://my-rest-api.pavlovec.net/api.php/records/posts

So, sometimes I got proper answer, but mostly I got this:
- {"code":1000,"message":"Route '\/records\/posts' not found"}

If I am communicating through "http://postman.com/" app, it is same. Sometimes it is working, sometimes getting error...

Do you have any ideas, what is going on?
Thanks, Kubajjz

**Comment by mevdschee** [comment]
Thank you for reporting this issue. I've got no idea. It could be shared hosting with a load balancer and some misconfigured nodes, but that is a very wild guess.

**Comment by kubajjz** [comment]
But it is not shared hosting. It is quite powerful VPS. It is possible to debug it somehow?

**Comment by mevdschee** [comment]
ah.. it most likely is the caching mechanism. Try the "NoCache" caching engine.

**Comment by kubajjz** [comment]
I have solved it with VPS support. Problem was with the connection limit to DB. We have increased the limit a it is working fine now. 

Thanks for help,
Kubajjz
