### ISSUE TITLE
Customization, db and response access

### ISSUE THREAD

**Issue by caltabid** [mevdschee/php-crud-api#738]
Hi, I'm trying to delete a file on my backend connected to a db record whenever the record is deleted.
I added "reflection and db" in the customization callbacks.
I'm reading the file name in the beforeHandler (using reflection to access table from tableName) and deleting the file in the afterHandler.
How can I read whether the record has been deleted?
I could check again in the database for the same record id but the answer is already available for the frontend in the response variable.
I tried reading $response->getBody()->getContents() but this consumes the stream which is then not sent to the frontend.
Any suggestion?
Moreover can you add "reflection and db" in the customization callbacks or suggest another way to do the same?

**Comment by gabrielmachts** [comment]
I'd also be interested to read the response data in the customization.afterHandler!

**Comment by gabrielmachts** [comment]
@caltabid The following code in the afterHandler seems to work for me (got the idea from issue #564):

```
'customization.afterHandler' => function ($operation, $tableName, $response, $environment) {
 	$responseData = json_decode($response->getBody()->getContents());
 	if(isset($responseData->id)) {
 		...
 	}
 	return ResponseFactory::fromObject($response->getStatusCode(), $responseData);
}
```
Of course you don't have to use the middle bit, just first and last line should suffice.

Maybe @mevdschee , you can confirm if this works correctly? Thanks, btw, for your great work!

**Comment by mevdschee** [comment]
>Maybe @mevdschee , you can confirm if this works correctly? Thanks, btw, for your great work!

I think it should. Thank you for your contribution here on this repository!

**Comment by caltabid** [comment]
It works perfectly!
Thanks @gabrielmachts for your help and @mevdschee for this great project.
