### ISSUE TITLE
/records/tablename/0 returns all rows of table 'tablename' but $operation in afterHandler is 'read'

### ISSUE THREAD

**Issue by gabrielmachts** [mevdschee/php-crud-api#740]
Hi!

I came across this peculiarity which is quite serious for me because I use uuids as primary (and only) keys in this table and I  grant guest access to guest users (without login), but only if they know their own uuid.
So this behavior turns into a security issue for me, because anybody can access the whole table.
I'm blocking "list" access, but here the value in $operation is "read", although it returns all rows.
I know that I could make a workaround in some way or the other but maybe this can be addressed.

Here some more details:
My table has the column 'id' which is the primary key and is of type varchar(64).
The keys are uuids v1 of the type 80da025a-5803-11eb-ae93-0242ac130002, so normally a request would look like this:
GET /records/tablename/80da025a-5803-11eb-ae93-0242ac130002

I have implemented in the afterHandler (this is simplified to show only the relevant parts):

```
if($tableName === 'tablename' && $operation === 'read') {
 	$statusCode = $response->getStatusCode();
	// START Guest Session:
 	if($statusCode === 200) {
 		$responseData = json_decode($response->getBody()->getContents());
 		if(isset($responseData->id)) {
		     $_SESSION['guest_id'] = $responseData->id;
		     session_regenerate_id();
	         }	
 		return ResponseFactory::fromObject($response->getStatusCode(), $responseData);
	}
}
```

Do you have any idea, why the API returns all rows, yet $operation is still "read" and not "list"?

`GET /records/tablename/0`

returns

```
{
  "records": [
    {
      "id": "07f14630-4dc9-11eb-...",
      "mitgliednr": 1,
      "aktiv": true,
      ...
    },
    {
      "id": "b9d0add0-58e8-11eb-...",
      "mitgliednr": 2,
      "aktiv": false,
       ...
    }
  ]
}
```

**Comment by mevdschee** [comment]
Hi, thank you very much for reporting this issue. This looks like a bug to me. I believe that the operation should be either 'read' or 'list' depending on whether or not the URL has a primary key specified. I think I fixed it. Can you check that? Kind regards, Maurits

**Comment by mevdschee** [comment]
A new version (v2.9.32 Wrong operation for 0 pk) has been released that includes this fix. Thank you for your contribution!

**Comment by mevdschee** [comment]
I will close this issue now. Please re-open this issue if it does not solve your problem.

**Comment by mevdschee** [comment]
related from Fred Koschara:

>Ah, yes, booleans - bit values that are either set (TRUE) or not set (FALSE).  Now that we have 64 bit compilers using an int variable for booleans, there is *one* value which is FALSE (zero) and 2**64-1 values that are TRUE (everything else).  It appears there's a lot more truth in this universe, but false can trump anything that's true...

>PHP's handling of strings as booleans is *almost* correct - an empty string is FALSE, and a non-empty string is TRUE - with one exception:  A string containing a single zero is considered FALSE.  Why?  If *any* non-empty strings are going to be considered FALSE, why *only* a single zero?  Why not "FALSE" (preferably case insensitive), or "0.0" (with how many decimal places), or "NO" (again, case insensitive), or ... ?

>The *correct* design would have been that *any* non-empty string is TRUE - period, end of story.  Instead, there's another GOTCHA for the less-than-completely-experienced programmer to watch out for, and fixing the language's design error at this late date would undoubtedly break so many things that the correction is completely out of the question.

source: https://www.php.net/manual/en/language.types.boolean.php

**Comment by gabrielmachts** [comment]
Hi Maurits!

Yes, that fixed my issue! Thanks for your quick fix!

And kudos again for your great work on this project!

Greetings from Austria!

**Comment by mevdschee** [comment]
Thank you for your kind words. Greetings from Amsterdam.
