### ISSUE TITLE
Exclude specific field type (such as files) 

### ISSUE THREAD

**Issue by khalid-o** [mevdschee/php-crud-api#741]
Thank you for the great work done here.
I have a question, is there some way to exclude a specific field type from response such as Files without define each one separately in request query?

Thank you

**Comment by mevdschee** [comment]
Thank you for opening this issue. You can prevent access to certain field using the "authorization.columnHandler". This does not prevent access to a specific type of column, but it may help you. Kind regards, Maurits

**Comment by khalid-o** [comment]
I'll check it out, Thank you for your help.
But in my case, I'm assuming I'm not aware of the database structure.

**Comment by mevdschee** [comment]
Good. You could also use reflection (information_schema) in the beforeHandler (or in custom middleware) to implement such functionality. If you have further questions, please let me know.

**Comment by khalid-o** [comment]
This is very helpful for me.
Thank you very much <3

**Comment by mevdschee** [comment]
No problem. I'm closing the issue for now. Feel free to follow up and I'll re-open.
