### ISSUE TITLE
Record created twice

### ISSUE THREAD

**Issue by khalid-o** [mevdschee/php-crud-api#742]
Hi there, I'm thankful to found this work. 

But I have an issue when creating a resource with POST request, whether it is one or more, it's seems like the route called twice, as shown in screens below.

Thank you.

![Insomnia – dbApi 1_20_2021 12_23_53 AM](https://user-images.githubusercontent.com/13126152/105101056-f8398900-5ab6-11eb-9088-2a5b864281e1.png)
![Insomnia – dbApi 1_20_2021 12_24_26 AM](https://user-images.githubusercontent.com/13126152/105101061-f8d21f80-5ab6-11eb-908d-3cff358813c5.png)

**Comment by mevdschee** [comment]
Hi, this looks like a database issue to me. I think you have a primary or unique key on one of the field. Kind regards, Maurits

**Comment by khalid-o** [comment]
Yes I have an unique key, but create method inside RecordController called twice as you see I printed "Request" dump work, to debug the process of request.
Thank you.

**Comment by mevdschee** [comment]
I think you may have accidentally executed the code twice, maybe through an "include"?

**Comment by mevdschee** [comment]
Are you sure you clean/delete the database (records) in between requests?

**Comment by khalid-o** [comment]
Yes, first record created by first request, but of course second one get me duplicated key, and I didn't use any other filters or request queries.

**Comment by khalid-o** [comment]
Thank you so much for your help.
I solved the problem, I have duplicate $api-> handle($request)!
Very sorry for the inconvenience! :(

Thank you again!

**Comment by mevdschee** [comment]
No problem, I'm glad you figured it out!

**Comment by mevdschee** [comment]
Feel free to open a new issue when you run into something else. I'm happy to help out.

**Comment by khalid-o** [comment]
Thank you <3
