### ISSUE TITLE
PHP 8 bug: Declaration of Tqdev\PhpCrudApi\Database\LazyPdo

### ISSUE THREAD

**Issue by AmelleEK** [mevdschee/php-crud-api#743]
Hello, 

Can't make the solution work, I have the below error :

**Fatal error: Declaration of Tqdev\PhpCrudApi\Database\LazyPdo::query(string $statement): PDOStatement must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in C:\Server\data\htdocs\crud\api.php on line 6390**

Any suggestions ? 
Thank you.

**Comment by mevdschee** [comment]
Hi. Thank you for creating this issue. I would love to help you, but how did you get this error? Can you help me to reproduce it? Really any information would be helpful: operating system, version, what you did, etc, etc.. Kind regards, Maurits

**Comment by mevdschee** [comment]
I just re-ran all the tests on CentOS 8, and Ubuntu 16.04, 18.04 and 20.04 and I have not seen that error. How did you get it? What system are you on?

**Comment by mevdschee** [comment]
It seems you are on PHP 8.0.1 (released two weeks ago) and I don't have a system to test that version on (yet).

**Comment by mevdschee** [comment]
I tested with `docker-compose` and was able to reproduce the problem in PHP 8. It is fixed now. I will release a new version ASAP. Thank you for your contribution! Kind regards, Maurits

**Comment by mevdschee** [comment]
FYI, by now v2.9.33 & v2.9.34 have been released that are both working well on PHP 8.

**Comment by mevdschee** [comment]
$ bash run.sh 
    1) centos8
    2) debian10
    3) debian9
    4) ubuntu16
    5) ubuntu18
    6) ubuntu20
    > 1
    ================================================
    CentOS 8 (PHP 8.0)
    ================================================
    [1/4] Starting MariaDB 10.5 ..... done
    [2/4] Starting PostgreSQL 12.5 .. done
    [3/4] Starting SQLServer 2017 ... skipped
    [4/4] Cloning PHP-CRUD-API v2 ... skipped
    ------------------------------------------------
    mysql: 110 tests ran in 958 ms, 1 skipped, 0 failed
    pgsql: 110 tests ran in 830 ms, 1 skipped, 0 failed
    sqlsrv: skipped, driver not loaded
    sqlite: 110 tests ran in 673 ms, 12 skipped, 0 failed
    [root@e73128eeb392 php-crud-api]# php -v
    PHP 8.0.1 (cli) (built: Jan  5 2021 13:54:54) ( NTS gcc x86_64 )
    Copyright (c) The PHP Group
    Zend Engine v4.0.1, Copyright (c) Zend Technologies
    [root@e73128eeb392 php-crud-api]#
