### ISSUE TITLE
Cache type "TempFile"

### ISSUE THREAD

**Issue by maettyhawk** [mevdschee/php-crud-api#746]
Almost every second request of my api fails because an error 500:
` "statusCode": 500,
    "error": {
        "type": "SERVER_ERROR",
        "description": "ERROR: unlink(\/home\/www\/46\/03\/dkdakde169\/generator\/app\/..\/var\/cache\/\/623ac493259199b598bb537b64af5693): No such `
Also very weird that the error message suddenly stops. 
Had the problem both on a local environment but also on my shared hosting webspace.

**Comment by mevdschee** [comment]
Hi, thank you for reporting this issue. Can you change the 'cacheType' in the config to 'NoCache' and see whether or not the problem persists? Kind regards, Maurits

**Comment by maettyhawk** [comment]
Solved the problem - thanks a lot.

**Comment by mevdschee** [comment]
Thank you for letting me know. Enjoy the software. Kind regards, Maurits
