### ISSUE TITLE
Commercial Usages 

### ISSUE THREAD

**Issue by khalid-o** [mevdschee/php-crud-api#747]
Hello, and thanks for effort done here.

Can I use this package for commercial use?

Thank you

**Comment by mevdschee** [comment]
>Can I use this package for commercial use?

Yes, it is MIT licensed, for an explanation what that means, see:

https://tldrlegal.com/license/mit-license

**Comment by mevdschee** [comment]
NB: If you would need commercial support (for instance a support contract) please contact me by email.

**Comment by khalid-o** [comment]
Thank you so much <3
