### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by maettyhawk** [mevdschee/php-crud-api#748]
Hi there,
I try to store German umlauts, but they get oddly converted. (äüöß => Ã¤Ã¼Ã¶ÃŸ)
The database and also the server seem to be configured using UTF-8 encoding. Is there some conversion going on the api itself?
Kind regards

**Comment by mevdschee** [comment]
Only UTF-8 is supported. Make sure all tables and field collations are set to utf8 (utf8mb4). I'm glad you solved the issue. Kind regards, Maurits
