### ISSUE TITLE
cors.allowedOrigins fails when allowedOrigins contains forward slashes

### ISSUE THREAD

**Issue by garrettcam** [mevdschee/php-crud-api#749]
The cors middleware fails when the `$allowedOrigins` contains `//`

eg `'cors.allowedOrigins' => 'https://randomurl.com',`

it produces `preg_match(): Unknown modifier '/'` and and results in a cors forbidden when it should accept the origin

problem is in function isOriginAllowed();
https://github.com/mevdschee/php-crud-api/blob/d8833c5e33ce7afb58e8dde63795401e51e618fc/api.php#L7467

**Comment by mevdschee** [comment]
Hi, Thank you very much for reporting this issue. Good find! It has been fixed and a new version is released. Enjoy the software. Kind regards, Maurits
