### ISSUE TITLE
New Entity returns non JSON Integer/String value

### ISSUE THREAD

**Issue by knex-xx** [mevdschee/php-crud-api#75]
Dear Developer,

i´ve tested you´re code which is great but, in one case it´s not round up JSON / REST technology.
If you create a new entity with post you will get as return an integer with the new id.
But this id is in non JSON format.
Better format would be {result:+id+}

Thanks!

**Comment by mevdschee** [comment]
AFAIK this is valid JSON, and JSON lint agrees, see: http://jsonlint.com/

**Comment by mevdschee** [comment]
Ok, I've read RFC 4627 (siee: http://www.ietf.org/rfc/rfc4627.txt) and indeed it is a JSON-value and not JSON-text.

**Comment by mevdschee** [comment]
Hmm.. according to JSON validator (see: https://jsonformatter.curiousconcept.com/) it is valid in RFC 7159 (http://www.ietf.org/rfc/rfc7159.txt).

So it is a valid JSON-text according to RFC 7159 and not according to RFC 4627. I think in practice all parsers accept this as valid JSON.

I think this is a non-issue. Can you tell me which JSON parsers reject this JSON string?
