### ISSUE TITLE
Cancelling request in customization.beforeHandler

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#750]
Hi,
I need to cancel a request in customization.beforeHandler, ie return an error code
I thought I could manage it from the validation middleware, but my cancelling depends on response object which seems not present in the validation handler.

Is it possible, how?
Thank you

**Comment by thipages** [comment]
see [this example](https://github.com/mevdschee/php-crud-api/issues/703#issuecomment-778784261) for a use case

**Comment by mevdschee** [comment]
Hi, Thank you for this question. What do you mean with "cancelling"? Simply giving an error response or "undoing" the previous (executed) transaction?

**Comment by thipages** [comment]
Hi,
thank you for clarifying my ambiguous question.
I meant
- preventing the execution of the current request in customization.beforeHandler
- and sending back a custom error message

**Comment by mevdschee** [comment]
>preventing the execution of the current request in customization.beforeHandler

Do you mean (for instance) not inserting a record in an insert request? Reverting the transaction is not possible in the after handler.

>and sending back a custom error message

This is not problem in the after handler.

**Comment by thipages** [comment]
> Reverting the transaction is not possible in the after handler as the transaction is already executed.

How do we revert in the before handler?

> This is not problem in the after handler.

how do I sendback in the after handler?

Thank you

**Comment by mevdschee** [comment]
You may produce an invalid request in the before handler:

    'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) {
        $in = "GET /unknown_url";
        return RequestFactory::fromString($in);
    },

Or in the after handler:

    'customization.afterHandler' => function ($operation, $tableName, $response, $environment) {
        $json = array();
        return ResponseFactory::fromObject(404, $json->records);
    },

I hope this helps!

**Comment by thipages** [comment]
Yes!
Thank you

**Comment by mevdschee** [comment]
There are way more sophisticated things you can do, but this is some quick and dirty code to get the job done. I'm glad this works for you. Feel free to open another issue if you have further questions. Enjoy the software!

**Comment by thipages** [comment]
It is what I have done.
This is a nice way for information transmission between 'modules'
Thank you.
