### ISSUE TITLE
get db informations in customization.beforeHandler

### ISSUE THREAD

**Issue by pat123456** [mevdschee/php-crud-api#751]
Hello,
How can we get information about the table corresponding to the "$table" from the request/url ?

```
'customization.beforeHandler'=>function($operation,$table,$request,$env){
  // check here if a column exist in the table "$table" of the DB 
} 
```
sorry my bad English, hope this understandable

**Comment by mevdschee** [comment]
Hi, thank you for opening this issue.

> How can we get information about the table corresponding to the "$table" from the request/url ?

What is it you want to know? What is it you don't know?

**Comment by pat123456** [comment]
Hi, 
Firstly, thank you very much for your work, your framework is very interesting 

You means to do it with simple php/mysql request, there nothing available in the framework for that ?

**Comment by pat123456** [comment]
thank you ! it's clearer now

**Comment by mevdschee** [comment]
If you have the config object you can do the same as the code does here:

https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Api.php

        $db = new GenericDB(
            $config->getDriver(),
            $config->getAddress(),
            $config->getPort(),
            $config->getDatabase(),
            $config->getTables(),
            $config->getUsername(),
            $config->getPassword()
        );
        $prefix = sprintf('phpcrudapi-%s-', substr(md5(__FILE__), 0, 8));
        $cache = CacheFactory::create($config->getCacheType(), $prefix, $config->getCachePath());
        $reflection = new ReflectionService($db, $cache, $config->getCacheTime());

And use the $reflection to query the database structure.

**Comment by mevdschee** [comment]
Feel free to open a new issue if you have any further questions.

**Comment by pat123456** [comment]
thank again !

> If you have the $config object

just a little precision if possible, as the "customization.beforeHandler" is setup in the Config initialization, how can I access to the $config object there ?

**Comment by mevdschee** [comment]
Something like this:

    'customization.beforeHandler' => function ($operation, $tableName, $request, $environment) use ($config) {
        $environment->start = 0.003/*microtime(true)*/;
    },

see: https://www.php.net/manual/en/functions.anonymous.php

**Comment by mevdschee** [comment]
Note that I didn't test this, so I'm not sure it works.

**Comment by mevdschee** [comment]
You may use the static global VariableStore::set and VariableStore::get to store and retrieve the config.

In the api.php file modify:

    $config = new Config([
        // 'driver' => 'mysql',
        // 'address' => 'localhost',
        // 'port' => '3306',
        'username' => 'php-crud-api',
        'password' => 'php-crud-api',
        'database' => 'php-crud-api',
        // 'debug' => false
    ]);
    VariableStore::set('config', $config); // add this line
    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    ResponseUtils::output($response);

and in the handler use:

    $config = VariableStore::get('config');

**Comment by pat123456** [comment]
ok thank will try... 
that good if you'll work on this !

**Comment by pat123456** [comment]
I've tried the VariableStore "bus" and it work fine

Just an idea, may not make sense, may the handlers should not be defined is the config but outside and after the api initialization, so that $config will already be initialized
something like that :
```
$api = new Api($config);
$api->customization.beforeHandler = etc...
```
