### ISSUE TITLE
unable to delete row with joins

### ISSUE THREAD

**Issue by leembb** [mevdschee/php-crud-api#752]
Hi, am i missing anything obvious, is there no way to delete row that has foreign key/joins?

Thanks

**Comment by mevdschee** [comment]
Hi, this is a good question, thank you for asking it. It has little to do with the software, as the answer is: This depends on your foreign key constraint behavior. In the default case (restrict) you need to remove the referring record before removing the referred to record. You may read more about this:

https://dba.stackexchange.com/questions/14155/how-to-use-restrict-for-foreign-key-in-mysql

**Comment by leembb** [comment]
You're a gentleman, thankyou. Having a read now

**Comment by mevdschee** [comment]
Feel free to open another issue if you have further questions. Enjoy the software!
