### ISSUE TITLE
automate $_SESSION['user']['id'] insertion in DB user_id field

### ISSUE THREAD

**Issue by pat123456** [mevdschee/php-crud-api#754]
Hi,
When an user is logged in and post a new entry, I would like to automate the insertion of his "user id" in the corresponding table/user_id field. And this for any request if there is a "user_id" field in the corresponding table.

I did that but I wonder if it's the good way to do it and if it could be insecure ?

```
'customization.beforeHandler'=>function($operation,$table,$request,$env){
               
    if( $operation == 'create' ){

        // check if there is an user_id column in the table
        $conn = mysqli_connect("localhost", "root", "", "php-crud-api");
        $stmt = $conn->prepare("SELECT * FROM information_schema.COLUMNS WHERE TABLE_NAME = ? AND COLUMN_NAME = 'user_id'");
        $stmt->bind_param("s", $table);
        $stmt->execute();
        $userIdColumn = $stmt->get_result()->num_rows;
        $stmt->close();
        $conn->close();

        if($userIdColumn){
            // insert the id of the logged user
            $body = $request->getParsedBody();
            $body->user_id = $_SESSION['user']['id'];
            return $request->withParsedBody($body);
        }
    }

    return $request;
}
```

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue. This is exactly what the multiTenancy middleware tries to achieve. Read more here:

https://github.com/mevdschee/php-crud-api#multi-tenancy-support

I hope this helps! Kind regards, Maurits

**Comment by mevdschee** [comment]
Also, are you sure you even need to know whether or not that table has that column? Can't you just add that parameter anyway?

**Comment by pat123456** [comment]
> Also, are you sure you even need to know whether or not that table has that column? Can't you just add that parameter to the body anyway?

Yes would be better, I complicated for nothing. What ever I will not have to use that now

>  This is exactly what the multiTenancy middleware tries to achieve

Wonderful ! even easier than I though !
```
'multiTenancy.handler' => function ($operation, $tableName) {
    return ['user_id' => $_SESSION['user']['id']];
},
```
that's all need to be done, no more security setup ?

**Comment by mevdschee** [comment]
>that's all need to be done, no more security setup ?

That's the idea. Be sure to test it properly to see whether or not it fits your purpose.

**Comment by pat123456** [comment]
ok ! thank again and sorry for my newbie's questions, even if the documentation has the advantage of being short, it covers certain aspects a little quickly

**Comment by mevdschee** [comment]
Documentation is a point that certainly can be improved and short is not always better. ;-) Feel free to propose some paragraphs to add to the documentation to make things clearer. I hope you enjoy the software! Thank you for giving it a chance and filling this issue. Kind regards, Maurits

**Comment by pat123456** [comment]
ok I'll think about documentation

**Comment by mevdschee** [comment]
>ok I'll think about documentation

No pressure, but if you have something useful, please share it!

Thank you, Maurits
