### ISSUE TITLE
Proposal: /status endpoint

### ISSUE THREAD

**Issue by adrianvoica** [mevdschee/php-crud-api#755]
Hello Maurits,

I have a proposal/enhancement request: /status endpoint (that will ALWAYS be PUBLIC), that will output something like:
{
   "apiStatus": "up", // this is implicit, there isn't a case for other values - if it's here, it works;
   "dbStatus": "up" // or "down",
   "apiVersion": "20200222" // or any other identifier;  
}

First field will tell us that the API is up (if the field is there, it's obvious that it works).
Second field tells us that the DB connection is ok. A connection attempt should be made to reflect this in realtime.
Maybe other info, like "apiVersion" (application-specific API version) could be specified.

Any thoughts on this?
Cheers!

**Comment by mevdschee** [comment]
Hi Adrian, I like this! Great idea. I'm not sure about the API version and what that should do: Show the software version or reflect database structure changes? I could implement this. Kind regards, Maurits

**Comment by adrianvoica** [comment]
API version should be something that the developer could set in the config to reflect some specific version identifier. Almost like 'openApiBase'. 
For instance, I am working on 2 projects, each with their own API endpoint. When I hit /status on one of them, the result would say something like 'apiVersion': '2021.02.22' (I prefer semantic YMD version formats lately). 
Actually, even better, as I have it now, it says:
{
    "api": {
        "name": "MY-API1",
        "status": "up",
        "version": "2022.02.22",
        "database": "up"
    },
    "timestamp": "1613994676"
}

But this is just optional stuff, for now. The endpoint per-se is more important. We can add stuff later. 

Cheers!

**Comment by mevdschee** [comment]
>But this is just optional stuff, for now. The endpoint per-se is more important. We can add stuff later.

First version is implemented in v2.9.41

**Comment by mevdschee** [comment]
Thank you for your contribution. Your input is very valuable to me. Kind regards, Maurits

**Comment by adrianvoica** [comment]
That was fast! Thank you! 
P.S.: don't forget to update the documentation.

**Comment by mevdschee** [comment]
For docs, see: https://github.com/mevdschee/php-crud-api#status

Feel free to improve.. :-)

**Comment by adrianvoica** [comment]
Wow! Very nice! Great work! 
Cheers!

**Comment by mevdschee** [comment]
Try v2.9.42, some small bugfixes

**Comment by adrianvoica** [comment]
It seems that the endpoint is not public. If the DB is down, how cand I log in? :)) v2.9.42.

**Comment by mevdschee** [comment]
It needs to be excluded from DbAuth in your usecase :-) I will add that. I just added it to the OpenApi config.

**Comment by mevdschee** [comment]
I might add functionality to configure dbAuth exclusions, but when "dbAuth.mode" is set to "optional" it should let you configure which URL's need authentication. Can you use that?

**Comment by mevdschee** [comment]
>If the DB is down, how can I log in?

If the DB is down the call will not succeed.

**Comment by adrianvoica** [comment]
It might become too tightly coupled with dbAuth, and it shouldn't since they are unrelated. By default, /status endpoints should pe publicly accessible (unless otherwise specified).

**Comment by mevdschee** [comment]
>It might become too tightly coupled with dbAuth

Agree, excluding things from dbAuth is strange, it should be solved with granular access control (a permissions handler of some kind).

**Comment by adrianvoica** [comment]
Also, the DB being slow, I don't think it is really of concern for the /status endpoint. It should, at its most basic feature, just display if the subsystems are or aren't operational. The /ping is really nice as a feature, though. But /up should just say that the DB connection is working. But don't take my word for it! Godspeed.

**Comment by mevdschee** [comment]
Since the roundtrip to the database and back should be around 1 ms over a LAN when all systems are operating normally I think you can't say the database is "slow" or "laggy" at 1000ms. Even if you connect it from Europe to Australia over the WAN, the connection should still be well under 1 second. Also nothing fails, it will still give a 200 "OK" for your monitoring system. Only when your PDO timeout is reached you will receive a 500 error (and no upStatus response, but an errorDocument). I think this will be good enough for most uses.

**Comment by mevdschee** [comment]
>just display if the subsystems are or aren't operational. 

I think that the status code of the ping can also be used for that. I might remove the up endpoint altogether, or do you think it is valuable?

**Comment by adrianvoica** [comment]
Yep. Ping is more than enough.

**Comment by mevdschee** [comment]
>Yep. Ping is more than enough.

I made it so, see: v2.9.43.

**Comment by adrianvoica** [comment]
Tried it. Works like a charm. God bless.
