### ISSUE TITLE
"dbAuth.returnedColumns" is set to "username", but also returns "id".

### ISSUE THREAD

**Issue by adrianvoica** [mevdschee/php-crud-api#756]
I have specified only "userename" for "dbAuth.returnedColumns", but the "id" also shows up in the output. 
Am I doing something wrong? 
Or is this intentional?

Using: api.php v2.9.39

**Comment by mevdschee** [comment]
Hi Adrian, Thank you for asking this question. I looked it up in the code and it seems this is intentional: to provide you with at least the id after a login. Why would you like to hide the id? Kind regards, Maurits

**Comment by adrianvoica** [comment]
Well, just for bad actors, the "id" should always be hidden (maybe it's just obsolete knowledge now, but as I recall, I was told about this on numerous occasions), or at least it should be encrypted/hashed somehow. I would use "email" as a unique identifier if I want to narrow down the query to a specific user, as this should also be unique... but for the question at hand, I think "id" should not be visible because of security reasons, unless specified intentionally. 
No other strong(er) opinion on this. Cheers.

**Comment by mevdschee** [comment]
> the "id" should always be hidden (maybe it's just obsolete knowledge now, but as I recall, I was told about this on numerous occasions), or at least it should be encrypted/hashed somehow

Yeah I see how this fits the "obfuscation as an extra layer of defense" argument.

**Comment by mevdschee** [comment]
Thank you for your contribution! It is included in v2.9.40
