### ISSUE TITLE
Lower filter

### ISSUE THREAD

**Issue by BenitoJedai** [mevdschee/php-crud-api#758]
Hi please urgent helpme because your lib is the base of my main software system i need filter:

In rows
Ruben 
ruben

&filter=user,cs,ruben

Return only ruben but i need return  Ruben and ruben please help me how i can add the lower function in filter cs
Thanks sir

**Comment by mevdschee** [comment]
This is not due to the filter, but due to the collation on the column. A "case insensitive" collation has a "_ci" extension and should be set per column (or as a table or database default).

See: https://www.mysqltutorial.org/mysql-collation/

**Comment by BenitoJedai** [comment]
Thanks @mevdschee you are the master sir save my work :grinning: but also how i can add my custom filter operation.
Thanks for your time master..

**Comment by mevdschee** [comment]
>but also how i can add my custom filter operation.

You can add it to the Condition and ConditionsBuilder classes, see:

src/Tqdev/PhpCrudApi/Database/ConditionsBuilder.php

I hope this helps. Kind regards, Maurits
