### ISSUE TITLE
Set lower level limit on joined tables?

### ISSUE THREAD

**Issue by NorthFred** [mevdschee/php-crud-api#759]
I have following case:

a) Table with `productOrders` entries for different `products`
b) Table with the `products` details

The `productOrders` table has a relation to the `products` details via the `productId` field. 

What I wish to achieve is getting a **list of the last order of each product**.  Is this possible to achieve by combining a "join", "size" and e.g. "descending order" query?  The `productOrders` are stored in the table by incremental numeric id.

Example of what I am after:

`/productOrders?order=id,desc&join=products&limit=1`

But it seems the "limit" parameter is a limit set to the top level. Is it possible to apply this limit for each of the products?

**Comment by mevdschee** [comment]
I'm afraid not. In SQL I would write:

    SELECT * FROM `products`, `productOrders` WHERE `products`.`id` = `productOrders`.`productId` AND `productOrders`.`id` IN (SELECT MAX(`id`) FROM `productOrders` GROUP BY `productId`);

This is too expressive for the REST query language that is supported. You could create a view and query that.

**Comment by NorthFred** [comment]
Thanks, I got a bit further now and created a view in the database, the view returns the correct results.

I'm however stuck on querying the created view with the php api.

Debugging gave this message:  `SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared`

**Comment by mevdschee** [comment]
Yeah.. that is most probably due to emulate prepared statements being false (and a bug mysql).

**Comment by NorthFred** [comment]
That seems all very helpful information, but I am on shared hosting server and I am not allowed to touch the cache options :/
I will contact the provider and ask if they can do anything, but given how helpful they have been in the past, I may be stuck with this problem.

One alternative solution I came across was enabling the emulation. Is that possible with the current php code?

`PDO::ATTR_EMULATE_PREPARES => true,`  in mysql connection options.

**Comment by mevdschee** [comment]
Can you try the latest? v2.10.0

**Comment by NorthFred** [comment]
I will give this a try as soon as I have a free moment from my work obligations :)  Sounds promising already!

**Comment by NorthFred** [comment]
Confirmed, the latest version makes querying my table view possible!
In the reference, there are some arguments against setting it to `true`, but unless my web hosting provider resolves the issue by increasing the mentioned caching values, this would be the best solution I can resort to.

Bedankt Maurits, you're saving lives! :)

**Comment by mevdschee** [comment]
>Bedankt Maurits, you're saving lives! :)

Thank you! I'm not, but I'm glad you like it.

> there are some arguments against setting it to true

Yes, but your case does not stand on it's own, this is an annoying bug in MySQL/MariaDB. I have covered the biggest downside by doing the appropriate type conversions in PHP. Other that it is mostly a performance vs. ease of use trade off. Let's see whether or not other people run into issues with these new PDO settings (fingers crossed).

**Comment by mevdschee** [comment]
For a reference, this is the change: https://github.com/mevdschee/php-crud-api/commit/5602e574080743503d8ea543759cf3c5fd332364#diff-2cb15aff70b395d9122685e6a143b080d9f93432064c42770e71a952c9fb0f00
