### ISSUE TITLE
Not found (1pk)

### ISSUE THREAD

**Issue by Wakie87** [mevdschee/php-crud-api#76]
Recently updated api.php, now when loading api.php I am getting the following result:

`Not found (1pk)`

when visiting api.php/table everything works alright. I have narrowed it down to some tables not having Primary keys. Going back to a commit before adding in PK referencing solves the issue. 

Do you have any suggestions for a fix?

**Comment by mevdschee** [comment]
Thank you for using the software and reporting back.
 
- Are you using the swagger output? Are you not interested in the identifying property?
- Is adding a non-composite primary key to all exposed tables is not an option?

I might add a fallback for primary key resolution or disable the extended fields through a configuration setting.

**Comment by Wakie87** [comment]
Hi,

Yes using the swagger output. Some tables in the database are just data backup of another table, one of the applications using the database just copies the data to a "backup" table without copying across the schema.

Modifying existing tables may cause problems later on down the track or within other applications using the database, so if possible without altering the database.

Thanks

**Comment by mevdschee** [comment]
I will investigate how I can make the script less strict on the primary key configuration. Because the script currently prevents listing without primary key, while there is no (real) reason it does that.

Creating, reading, updating and deleting (not unimportant either) on the other hand do need a primary key. Without a primary key these operations are not possible.

**Comment by mevdschee** [comment]
NB: Using the "table_authorizer" you can disallow access to the tables that do not have a primary key and everything should work. Although I'm not sure that work-around works for you.

**Comment by mevdschee** [comment]
Did this fix help you?

**Comment by Wakie87** [comment]
Will give this a try tomorrow, (almost midnight in Australia) also do you have an example of how to use the table and Column authoriser?

**Comment by Wakie87** [comment]
Ok, so the update works, (it outputs the swagger json) but when using the swagger-ui to validate, the swagger badge bottom right comes up as an error. (Also tried on a table that has primary keys - same result)

Also now when using the table_authorizer 
`'table_authorizer'=>function($cmd,$db,$tab) { return (($cmd=='list'||$cmd=='read') && $tab=='table'); }`
The response returned has the list response but not the read response in the json output.
But when using the following
`'table_authorizer'=>function($cmd,$db,$tab) { return (($cmd!='delete') && $tab=='table'); }`
Everything is displayed but the swagger badge bottom right comes up as an error.

**Comment by mevdschee** [comment]
>the swagger badge bottom right comes up as an error

I have no idea what tool you are using, can you be more specific?
I tried to reproduce any problem, but I need more information.
What error is shown by the swagger tools? Do you see any PHP errors or warnings?

**Comment by Wakie87** [comment]
![error](https://cloud.githubusercontent.com/assets/975165/15530124/0ba177ec-2285-11e6-83de-62bd3c13fee0.jpg)

see attached.

**Comment by mevdschee** [comment]
Is that red thing clickable? Is there any error message you can report?

**Comment by mevdschee** [comment]
What does the swagger editor say about the json?

See: http://swagger.io/swagger-editor/

Any error message there?

**Comment by Wakie87** [comment]
So using the latest commit at the following address http://dev.npclinics.com.au/api.php with the following  `'table_authorizer'=>function($cmd,$db,$tab) { return (($cmd=='list'||$cmd=='read') && $tab=='npca_sv_apptpro3_resources'); }`

Using commit from a few days ago (10c9094) at the following address http://dev.npclinics.com.au/api2.php with the following  `'table_authorizer'=>function($cmd,$db,$tab) { return (($cmd=='list'||$cmd=='read') && $tab=='npca_sv_apptpro3_resources'); }`

Both urls show are fin in swagger-editor. 

but in swagger-ui http://petstore.swagger.io/ the latest commit shows an error. The (10c9094) doesnt have any errors.

**Comment by mevdschee** [comment]
This error is caused by the UI tool not accepting the "vendor extensions" as defined in:

http://swagger.io/specification/#schemaObject

I added a "no_extensions" option to allow you to disable these vendor extensions.

**Comment by Wakie87** [comment]
Fantastic, Commit 7094013 fixes the validation issue.
