### ISSUE TITLE
Documentation lack about middlewares

### ISSUE THREAD

**Issue by lascimmia** [mevdschee/php-crud-api#761]
I'm sure It is about me because  I'm a total noob on using this great piece of software: I can't understand WHERE I must configure i.e. the functions to configure Authorization middleware.
Is somewhere some example about this?

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue. You can find an example of the usage of most middlewares in the `tests` folder, see:

https://github.com/mevdschee/php-crud-api/blob/master/tests/config/base.php

I hope this helps you to get started. If you have any further questions, please let me know. Kind regards, Maurits

**Comment by lascimmia** [comment]
Got it, it's fantastic!
Maybe it's a good idea to put the link into middlewares documentation section. 
Anyway, thanks a lot for your great work
