### ISSUE TITLE
Additional parameters and values in successful POST response?

### ISSUE THREAD

**Issue by NorthFred** [mevdschee/php-crud-api#763]
Hello again :) 

The fact that I ask a lot of questions, is because this great library has been providing a lot of help already and the support response is amazing!

I'd like to ask if it is possible at the moment to return certain parameters in the response of a successful POST request?
At the moment, it returns the primary key from the table, but my code would benefit from also receiving some other values from the post request. For instance: I have one column with the primary key, which is a guid string. But I would also like to know the (incremented) number of the database entry in the table.

**Comment by mevdschee** [comment]
Hi again! Thank you for your kind words. If you want to read other fields, then you could request them by primary key. I would not try to save one roundtrip. If you still want to optimize, then you may need to write a customization "after" handler that retrieves the information for you. The library does not support this in a meaningful way.  I hope this helps. Kind regards, Maurits

**Comment by NorthFred** [comment]
Thanks for getting back so fast 👍 I went with the easy round-trip way, since the data amount is negligibly small after all. I was more curious about the technical feasibility. If I have more time, I will look into the "after" handler.  Now I understand what it can be used for :)

**Comment by mevdschee** [comment]
I'm closing this for now. Feel free to open a new issue for follow-up questions.
