### ISSUE TITLE
automatic mapping between logged user id and corresponding FK user_id of another table

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#764]
Hi,

I have a database (SQLite) with two tables user and note with the following structure, a note belonging to a user
```sql
CREATE TABLE user (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   login TEXT,
   pass TEXT
);
CREATE TABLE note (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   note TEXT,
   user_id INTEGER NOT NULL,
   FOREIGN KEY(user_id) REFERENCES user(id)
);
CREATE INDEX note_user_id_idx ON note (user_id);
```
I use the DBAuth middleware.
Is there a way (other than using customization middleware) to assign automatically user_id of note table to the id of the logged user when inserting a note record?
Thank you.

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue. 

>Is there a way (other than using customization middleware) to assign automatically user_id of note table to the id of the logged user when inserting a note record?

Yes, you should look into the multiTenancy middleware and the handler:

    'multiTenancy.handler' => function ($operation, $tableName) {
        return ['user_id' => $_SESSION['user']['id'];
    },

I hope this helps. Please let me know whether or not you have further questions. Kind regards, Maurits

**Comment by thipages** [comment]
Yep, this is working fine. Thank you.

Note : 
`$_SESSION['user']['id']` can not be retrieved if `returnedColumns `does not contain `id `
eg `"dbAuth.returnedColumns"=>"login"`

**Comment by thipages** [comment]
this is may be "in conflict" with #756

**Comment by mevdschee** [comment]
Yeah.. it may be, but by default returnedColumns is set to all columns of the user table, so that may be an edge case.
