### ISSUE TITLE
Filter nsw is missunderstood as spatial

### ISSUE THREAD

**Issue by akuehnis** [mevdschee/php-crud-api#765]
The filter 'nsw' (not starts with) is ignored completely.

Suggestion:

https://github.com/mevdschee/php-crud-api/blob/master/src/Tqdev/PhpCrudApi/Record/Condition/Condition.php

Line 49 

There should be 'elseif, not 'if' because variable $command is modified in line 47.

**Comment by mevdschee** [comment]
Good find! Thank you.

**Comment by mevdschee** [comment]
This has been fixed in v2.11.1
