### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by BenitoJedai** [mevdschee/php-crud-api#767]
Hi sir iam again hahha sorry for my question but you can show me an exampke how can paginate results with fetch from your api or a lib that you know that show data like card list and paginate  like next back or 1,2,3...,8,9,10 thanks please help me sir

**Comment by mevdschee** [comment]
Hi there, Thank you for asking this question. Did you see the documentation on pagination? It is here: https://github.com/mevdschee/php-crud-api#pagination Is there something specific that you tried and isn't working? I'm happy to help you when you run into a problem. Kind regards, Maurits

**Comment by mevdschee** [comment]
As for the lib, did you see PHP-CRUD-UI?

See: https://github.com/mevdschee/php-crud-ui

**Comment by BenitoJedai** [comment]
what I need is to paginate the api with fetch and return the results when changing pages with lit-html or something like that but I can't find any library to generate the page buttons

**Comment by mevdschee** [comment]
> I can't find any library to generate the page buttons

I fail to see how this is relevant for this PHP library. Closing for now.
