### ISSUE TITLE
SQLite "CASE" view

### ISSUE THREAD

**Issue by lascimmia** [mevdschee/php-crud-api#769]
I have a VIEW in SQLite built as:

```
SELECT
    *,
    CAST((CASE
        WHEN nome IS NOT NULL THEN 'danger'
        ELSE NULL
    END) AS text) AS _rowVariant FROM agenda
```
    
If I try to use it on a ROW where `nome` is `NULL` (using the URL `/api.php/records/agenda_bs`, where `agenda_bs` is the VIEW) the response is correct:

```
{"records":[{
	"slot":"2021-03-10 10:05:00",
	"nome":null,
	"telefono":null,
	"_rowVariant":null
}]}
```

otherwise I get a result like

```
{"records":[{
	"slot":"2021-03-10 10:00:00",
	"nome":"John",
	"telefono":null,
	"_rowVariant":0
}]}
```

A `0` instead of `danger`.

**Comment by lascimmia** [comment]
If I see it in SQLStudio everything is right:

![SQLiteStudio screenshot](https://user-images.githubusercontent.com/71778736/111272267-a898b900-8632-11eb-8944-c5f20769f42d.png)

I also tried without `CAST` operator in SQL statement.

**Comment by mevdschee** [comment]
Can you post the original table and an example record? The CREATE TABLE and an INSERT statement? That makes it easier for me to reproduce.

**Comment by lascimmia** [comment]
Creation schema for `agenda` TABLE and `agenda_bs` VIEW.
I did INSERT via SQLiteStudio.

```
CREATE TABLE agenda (
    slot     DATETIME,
    nome_    TEXT,
    telefono TEXT
);

---

CREATE VIEW agenda_bs AS
    SELECT *,
           CASE WHEN nome_ IS NOT NULL THEN CAST ('danger' AS TEXT) ELSE NULL END AS _rowVariant
      FROM agenda;
```

**Comment by lascimmia** [comment]
Meanwhile I tried to `CAST` 'danger' directly, with no luck.

**Comment by lascimmia** [comment]
Trying inserting 

```
INSERT INTO agenda (
                       slot,
                       nome,
                       telefono
                   )
                   VALUES (
                       '2021-01-01',
                       'Jim',
                       '123456789'
                   );
```

still no luck
```
{"records":[{
	"slot":"2021-01-01",
	"nome":"Jim",
	"telefono":"123456789",
	"_rowVariant":0
}]}
```

**Comment by mevdschee** [comment]
I had defaulted all view types to "integer", which was a mistake as "text" is the default type for SQLite.

**Comment by mevdschee** [comment]
v2.11.2 is released with a fix for this issue.

**Comment by lascimmia** [comment]
You're great and really fast ❤

**Comment by mevdschee** [comment]
I made a mistake and you've found it. Thank you for your contribution, much appreciated!
