### ISSUE TITLE
Simplest authorization

### ISSUE THREAD

**Issue by dkonopka** [mevdschee/php-crud-api#77]
Hey,

Maybe someone made a feature where I can easy block access to API for everyone? I want to block people typing www.api.example.com/table/, and give them 403, because they can read all data or trying to read via ajax.

I'm thinking about generating token with private key and then multiply it with timestamp or etc.

There is any way to do it?

**Comment by mevdschee** [comment]
Please read my answer on #74 and tell me what questions you have about this approach.

**Comment by dkonopka** [comment]
@mevdschee  Ye, I saw that question, but i've no idea how to implement that. I'm understand that code, but how to block access to api via [that ](http://tqdev.com/2016-jwt-implementation-in-php) script...

**Comment by mevdschee** [comment]
No, you need a login api call that returns you the token and then send that token to the api on every request. The api should check the claims and determine whether or not the user has access based on these claims.

Maybe I should add an example for this.

**Comment by dkonopka** [comment]
"Maybe I should add an example for this."

i will appreciate it

**Comment by quetool** [comment]
Please, add en example how to implement security! and thanks for the work! your script is awesome!

**Comment by LuisRodriguezLD** [comment]
+1 on the example. thank you very much!

**Comment by mevdschee** [comment]
Example added, in "login.html" and "login_token.html". Will add/update documentation soon.

**Comment by mevdschee** [comment]
Any feedback so far?

**Comment by nenas04** [comment]
I like very much your single file crud api and I want to implement it in one project that I have been working. But, I'm having a trouble with the authentication with token+session or form+session. I'm getting this error after uncomment the lines that you suggest in api.php: "Fatal error: Call to undefined function PHP_API_AUTH()", even after I followed your instructions with the files login_token.html and login_token.php or login.html. I appreciate if you can help me with that issue!

**Comment by mevdschee** [comment]
ok, I missed the word "new", see: ef8945d117c1dfd85d9215e332cf394ba6c00693

**Comment by nenas04** [comment]
Sorry I didn't saw that bugfix. Still don't working, after that in login_token.php it supposed to be a input tag with a token inside right? Instead of that, is showing the code of api and didn't show the input tag... What's wrong? Sorry I'm a little bit newbie in api matter :)

**Comment by mevdschee** [comment]
>Instead of that, is showing the code of api

Well that is certainly wrong, but I'm not sure what is causing it. Probably a server configuration as PHP code should never be served.

**Comment by quetool** [comment]
@nenas04 did you uncomment the lines inside api.php?

```
// uncomment the lines below for token+session based authentication (see "login_token.html" + "login_token.php"):

$auth = new PHP_API_AUTH(array(
	'secret'=>'someVeryLongPassPhraseChangeMe',
));
$auth->executeCommand();
if (empty($_SESSION['user'])) exit(403);
```

**Comment by nenas04** [comment]
@mevdschee Basically I see the code of the api after the html instead of the token:
<form method="post" action="api.php">
	<input name="token" value=
{"swagger":"2.0","info":{
(...)

**Comment by nenas04** [comment]
@quetool yes, I uncommented that lines. Only that lines right?

**Comment by oblivian** [comment]
I also had a lot of trouble getting it to work, before I realized that the login_token.php, etc. in the php-crud-api ZIP file wasn't the same as mevdschee/php-api-auth... Maybe you should leave out those files to mitigate future misunderstandings...

Anyways, so I have created a token, but how on earth do I use it in e.g curl or wget?

**Comment by dkonopka** [comment]
But what about creating unique tokens every ~10 seconds? Creating it in api.php is simple, md5&secret key. But how to make it work with ajax call? Generating there token with also md5 with php sometimes makes a difference in server side time...

**Comment by mevdschee** [comment]
@oblivian hank you for your feedback.I will update the repository and remove those files. It is indeed wrong and confusing.

@dkonopka You typically don't want to double the amount of requests. It is heavy and it does not add security (or does it?).

**Comment by mevdschee** [comment]
@oblivian You can use the token by adding it as a POST parameter with the name "token" together with the other data you are sending to the call. In curl this is called POSTFIELDS I believe. In wget it is the "--post-data" option and in curl on the command line it is the "--data" option. Send something like: 

```
token=<generated token here>
```

Hope this helps.

**Comment by dkonopka** [comment]
@mevdschee Yes, almost i get it. 

(WWW) send ajax call to API with token (but how to generate it via php/ajax?) and send it to (API.php)
and also i have to generate that token in API.php to check if is correct, right?

**Comment by mevdschee** [comment]
Create the token like this:

https://github.com/mevdschee/php-api-auth/blob/master/login_token.php

Send the token in the POST body (variable name 'token') to the API where you also have to include 'auth.php' and set the same shared secret.

I hope this helps you. Please try it out and report your findings!

**Comment by mevdschee** [comment]
See: https://github.com/mevdschee/php-api-auth
