### ISSUE TITLE
POST PUT DELETE not working

### ISSUE THREAD

**Issue by okobsamoht** [mevdschee/php-crud-api#771]
Hi.
first of all thanks for the great work. it saves my life several times.

then, im actually trying to deploy an app based on api.php but only select is working.
im using pgsql. here are my env setting:

- system linux / debian 8
- PHP Version 7.4.16
- PDO drivers | mysql, pgsql, sqlite
- PDO Driver for PostgreSQL PostgreSQL(libpq) Version | 9.2.24

the db is up and running i have record and i can list them.

when a do a post i dot code:9999
when i do a put or a delete i dot 403 forbiddent

here is my config:

`
$config = new Config([
         'driver' => 'pgsql',
         'address' => '127.0.0.1',
         'port' => '5432',
        'username' => 'xxxxxxx',
        'password' => 'xxxxxxx',
        'database' => 'xxxxxxx',
        'debug' => TRUE,
        'middlewares' => 'cors,errors,sanitation',
        'cors.allowedOrigins' => '*',
        'cors.allowHeaders'=>'*',
        'cors.allowMethods'=>'*',
        'sanitation.handler' => function ($operation, $tableName, $column, $value) {
            return is_string($value) ? strip_tags($value) : $value;
        }
    ]);
`

so i need help to fix issue.
thanks

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue. Can you enable debug with `"debug"=>true`? Then tell me what the headers of the responses are. It will help me analyze what is going on.

**Comment by mevdschee** [comment]
I think I found it. Remove "cors.allowMethods" and "cors.allowHeaders" as "*"  is not a valid value for those fields.

**Comment by okobsamoht** [comment]
> Can you enable debug with `"debug"=>true`?

debug=>TRUE  is already set.
then in the headers i got `SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for sequence Registre_id_seq` i think its my DB privledge issue. i will handle that.

**Comment by okobsamoht** [comment]
> I think I found it. Remove "cors.allowMethods" and "cors.allowHeaders" as "*" is not a valid value for those fields.

done but still having 403 on PUT and DELETE

**Comment by okobsamoht** [comment]
> > Can you enable debug with `"debug"=>true`?
> 
> debug=>TRUE is already set.
> then in the headers i got `SQLSTATE[42501]: Insufficient privilege: 7 ERROR: permission denied for sequence Registre_id_seq` i think its my DB privledge issue. i will handle that.

**Comment by okobsamoht** [comment]
the issue with the post is fixed.
it was my DB privileges issue. i fixed it with: `GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {$user};`

**Comment by mevdschee** [comment]
That is great news! Enjoy the software.
