### ISSUE TITLE
Result of Pagination request does not include `results` property on empty result set

### ISSUE THREAD

**Issue by nkappler** [mevdschee/php-crud-api#772]
#### Expected behaviour
`results` should be 0
```json
{
"records": [],
"results": 0
}
```

#### Actual behaviour
`results` property is missing entirely
```json
{
"records": [],
}
```

This problem always occurs if the result set contains no records, for example if the table is empty or if the filter does not include any records

**Comment by mevdschee** [comment]
v2.11.3 has been released with this fix
