### ISSUE TITLE
session id shared between two applications

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#774]
Hi,
I am browsing (in Chrome) two different applications (eg located at `localhost/app1/api.php` and `localhost/app2/api.php`)
Both configurations implement dbAuth with the same
- `dbAuth.sessionName` ('user_id')
- `dbAuth.mode` ('required')

I am logged in the app1
I havent logged in the app2 (and there is no user yet in the database)

BUT I am able to access the records in the app2 with ` localhost/app2/api.php/records/aTable `

Should I have different (unique) sessionName for each application on the same server?
Should the lib manage unique session names based on the `dbAuth.sessionName`?

Thank you for your lights.

**Comment by mevdschee** [comment]
Hi, thank you for your question!

>Should I have different (unique) sessionName for each application on the same server?

Yes, nothing more than that. :-) (it is typically the name of the application).

**Comment by thipages** [comment]
ok. Thanks!
