### ISSUE TITLE
how to grant access to the database with 'dbAuth' middleware ?

### ISSUE THREAD

**Issue by NedjZa8** [mevdschee/php-crud-api#775]
Hi,

I need help, I have trouble testing the dbAuth of api.php.
I want to grant access to the database to users of the "compte_entreprise" table

here is my configuration:

   ```
$config = new Config([
        'driver' => 'mysql',
        'address' => 'localhost',
        'port' => '3308',
        'username' => 'root',
        'password' => '',
        'database' => 'mydb',
        'debug' => false,
        'middlewares' => 'dbAuth',
        'dbAuth.usersTable' => 'compte_entreprise',
        'dbAuth.usernameColumn' => 'email',
        'dbAuth.passwordColumn' => 'password_entreprise'
        
    ]);
```

here is the error it displays:

```
{
    "code": 1012,
    "message": "Authentication failed for ''"
}
```

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue. Passwords are not stored in plain text. Maybe your password encoding is not compatible? Kind regards, Maurits

**Comment by mevdschee** [comment]
For password encoding information, see:  https://www.php.net/manual/en/function.password-hash.php (default algorithm)

**Comment by NedjZa8** [comment]
Ok, thanks for the answer,
I have already hashed the password.
Now this is what it displays:

```
{
    "code": 1011,
    "message": "Authentication required"
}
```

**Comment by mevdschee** [comment]
Okay, I'm glad you got a little further. Did you hit the '/login' endpoint first?

**Comment by NedjZa8** [comment]
I am using postman to test.
![postman](https://user-images.githubusercontent.com/67421570/112821158-ddb2fb80-9075-11eb-8c4d-3051c02c4efb.PNG)


`here is the url : http://localhost/projetapi/api.php/login?email=za@gmail.com&password_particulier=$2y$10$G0EJn7bRbbUkuHRRx2ApCOyJRY1mU50lV`

```
username = email
password= passeword_particulier
```
here is the password : `123`
here is the password hash : ` $2y$10$G0EJn7bRbbUkuHRRx2ApCOyJRY1mU50lV `

here is the structure of the database : 

![db](https://user-images.githubusercontent.com/67421570/112821099-cf64df80-9075-11eb-9d2a-eba196a538a5.PNG)

here is my configuration: 

![config](https://user-images.githubusercontent.com/67421570/112821497-4d28eb00-9076-11eb-9fec-885a41697eac.png)

**Comment by mevdschee** [comment]
Don't send the password as a hashed string. Use the plain-text. The database should have the hash stored.

**Comment by NedjZa8** [comment]
I use the plain-text but it always the same result.

![post](https://user-images.githubusercontent.com/67421570/112875076-3f458b00-90b3-11eb-9779-e7537bf83114.PNG)

**Comment by mevdschee** [comment]
Ok, you should still use 'username' and 'password' as post parameters, even when mapped to different fields.

**Comment by NedjZa8** [comment]
I used 'username' and 'password' but it's always the same result it returns.
![DB](https://user-images.githubusercontent.com/67421570/113006743-285f7100-9165-11eb-8d57-8da158366893.PNG)

**Comment by mevdschee** [comment]
You should send the parameters in the body and not as query parameters. Can you try that for me?

**Comment by NedjZa8** [comment]
here is the result .
![body](https://user-images.githubusercontent.com/67421570/113128446-55655f80-9209-11eb-895d-d30398da834d.PNG)

**Comment by mevdschee** [comment]
In your config the field is named 'password_entreprise' while the database has a field "password_particulier".. could that be the reason? Did you try x-www-form-urlencode or form-data as well? Or sending the required 'Content-Type: application/json' header?

**Comment by NedjZa8** [comment]
concerning the fields, I checked it is correct.

![header](https://user-images.githubusercontent.com/67421570/113167323-2663e380-9233-11eb-9381-19dff8eaac7f.PNG)

![xwww](https://user-images.githubusercontent.com/67421570/113167460-45fb0c00-9233-11eb-959d-416e3f6ba8d1.PNG)

**Comment by mevdschee** [comment]
I'm really out of options now. Can you send me the database create script (create table + inserts), the config and the files you are using, preferably all together in a zip to my email address? Try to send a minimal setup that replicates the problem. I'll debug it for you if you do.

**Comment by mevdschee** [comment]
Please also send me the operating system, PHP and MySQL versions you are using. That may help debugging/replicating.

**Comment by NedjZa8** [comment]
okay.

**Comment by NedjZa8** [comment]
Hi. sorry for the silence, can I have your email address to send you what you asked for?

**Comment by mevdschee** [comment]
You can find that on my github profile.

**Comment by NedjZa8** [comment]
I already sent.

**Comment by mevdschee** [comment]
Okay.. I did not see it before, thank you.

**Comment by NedjZa8** [comment]
okay...

**Comment by mevdschee** [comment]
Okay, so you did several things wrong:

- your username field was 'mail' not 'email'
- your password field was 'password' not 'password_particulier'
- your password field was too short: 40 instead of 255 characters
- you did not enable "dbAuth.registerUser" disallowing creating users
- there were no default values on the user table 'compte_particulier' causing insert for register to fail

I guess you tried, but some of these may be due to not checking the actual names of things and/or reading the documentation.

I hope you get it to work now.
