### ISSUE TITLE
table_authorizer

### ISSUE THREAD

**Issue by Wakie87** [mevdschee/php-crud-api#78]
I am only wanting to allow "list" and "read". The following code outputs the list option only. Not list and read:
`'table_authorizer'=>function($cmd,$db,$tab) {  return (($cmd=='list' || $cmd=='read') && $tab=='npca_sv_apptpro3_resources');  },`

Using the read command only outputs empty swagger output:
`'table_authorizer'=>function($cmd,$db,$tab) {  return (($cmd=='read') && $tab=='npca_sv_apptpro3_resources');  },`

I have tried all combinations but can't get it to work?

`'table_authorizer'=>function($cmd,$db,$tab) {  return (($cmd=='list' || $cmd=='read' || $cmd=='create') && $tab=='npca_sv_apptpro3_resources');  },`

`'table_authorizer'=>function($cmd,$db,$tab) {  return (($cmd=='create' || $cmd=='read') && $tab=='npca_sv_apptpro3_resources');  },`

`'table_authorizer'=>function($cmd,$db,$tab) {  return (($cmd!='delete' && $cmd!='create') && $tab=='npca_sv_apptpro3_resources');  },`

`'table_authorizer'=>function($cmd,$db,$tab) {  return (($cmd=='list' || $cmd=='read') && $tab=='npca_sv_apptpro3_resources');  },`

`'table_authorizer'=>function($cmd,$db,$tab) {  return (($cmd=='read') && $tab=='npca_sv_apptpro3_resources');  },`

**Comment by mevdschee** [comment]
Let me know whether this fix worked for you.

**Comment by Wakie87** [comment]
Fixed...I thought I was going crazy. Thanks

**Comment by mevdschee** [comment]
Sorry about that.. I'm glad you reported it :-) Thank you very much!
