### ISSUE TITLE
Virtual field: Error 1001 Table not found 

### ISSUE THREAD

**Issue by Grilloparlante** [mevdschee/php-crud-api#780]
Hi! 
I'm a happy user of php-crud-api, thank you for your work.

I added a virtual field to my table and I got the error: Error 1001 Table not found.
If I remove the virtual field the script run correctly

Server version: 10.1.45-MariaDB-0+deb9u1 - Debian 9.12

Can you help me please?
Thank you.

**Comment by mevdschee** [comment]
Can you show me (a minimal) create table/view statement for which the problem exists?

**Comment by mevdschee** [comment]
I tried with a field like this:

      `name!` varchar(255) AS (concat(`name`,'!')),

and it still worked as expected.

**Comment by Grilloparlante** [comment]
Hi Maurits,
below the dump of the table with the virtual field for which the problem exists:

CREATE TABLE `users` (
  `id_user` int(11) NOT NULL,
  `name` varchar(25) NOT NULL,
  `birth` date NOT NULL,
  `birth_f` varchar(10) AS (date_format(birth, "%d-%m-%Y")) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Thank you, Maurizio.

**Comment by mevdschee** [comment]
I have used:

    Server version: 10.3.25-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

And I cannot reproduce the problem. I have tested on other versions of MariaDB and MySQL and I cannot reproduce the problem. Can you help me reproduce the problem?

**Comment by mevdschee** [comment]
Hi Maurizio,

Can you change:

    `birth_f` varchar(10) AS (date_format(birth, "%d-%m-%Y")) VIRTUAL

into:

    `birth_f` varchar(10) AS (date_format(birth, '%d-%m-%Y')) VIRTUAL

to fix the problem? I think it should fix it.

**Comment by Grilloparlante** [comment]
Hi Maurits,
the hint fixed the problem!

Thank you for your support.

Best regards,
Maurizio.
