### ISSUE TITLE
Get all values from an request

### ISSUE THREAD

**Issue by aouniradouan** [mevdschee/php-crud-api#781]
Hi,
This file is great thank you!
I want to ask you about how i can send data as JSON Format in correct way
when i try to do that it return me this code :` {"code":1010,"message":"Data integrity violation"}`
and also how can i limit or hide access to table and allow others for exemple i want to hide this `/records/wilayas`.
Thank You again!

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue. I would love to help! Please show me what request you are doing that leads to this response, please also include the create table statement for the table that you are trying to insert into (or modify in). Kind regards, Maurits

**Comment by aouniradouan** [comment]
Thank you very much for the response Maurits,
I successfully addressed the problem. 
Another question please.
Is it safe for the user to know about the names of the tables and Column in the my database because they will be present in the link?

**Comment by mevdschee** [comment]
>Is it safe for the user to know about the names of the tables and Column in the my database because they will be present in the link?

Yes, I would say it is safe to share the layout of your database. Although it may be used in advantage of an attacker in case of a SQL injection vulnerability. I guess that in the end people will argue that "it depends", but that's not my style.

**Comment by mevdschee** [comment]
Thank you for you questions. Please open a new issue for new questions, so people can address them and find answers easily later.

**Comment by aouniradouan** [comment]
Thank you sir for your help :)
