### ISSUE TITLE
How to block access to a table or column And API Key?

### ISSUE THREAD

**Issue by aouniradouan** [mevdschee/php-crud-api#782]
Hello sir,
How can I block access to a table or column please?
And how can I include an API key from the users table and not allow them to see the content of one of the tables unless the key is present?

Thank You!

**Comment by mevdschee** [comment]
Hi, thank you for your question (v2.12.0). I just added this feature for you, please read:

https://github.com/mevdschee/php-crud-api#api-key-database-authentication

If you have any questions, please let me know.

Kind regards, Maurits

**Comment by mevdschee** [comment]
I think you probably need a combination of the new 'apiKeyDbAuth' and 'authorization' middleware. From the authorization middleware you may want to use the 'authorization.tableHandler' and 'authorization.columnHandler' and the from the 'apiKeyDbAuth' you may want to alter the 'mode'.

**Comment by mevdschee** [comment]
Do you have an update for me?

**Comment by aouniradouan** [comment]
> Do you have an update for me?

Hi @mevdschee, thank you very much, you really helped me, currently I have no problems thank you

**Comment by mevdschee** [comment]
Okay, if you run into new issues, feel free to open a new issue here. Take care and enjoy the software!
