### ISSUE TITLE
Suggestion: Pagination documentation

### ISSUE THREAD

**Issue by 27maximilian** [mevdschee/php-crud-api#783]
Hi,

thanks for this project and all the work you are putting in.

I am currently implementing pagination for one of my projects and stumbled on one thing in the documentation, which I would suggest to include. It is basically one sentence on "results"-element in the response. It could be something like this:

_The element "results" holds to total number of records in the table, which would be returned if no pagination would be used._

The total number of records is obviously important to implement the pagination in the UI. Therefore, I started to implement something myself with a view on the table, only realizing later that the information is already there.

Best,
Max

**Comment by mevdschee** [comment]
Thank you, I added the sentence you suggested.
