### ISSUE TITLE
apiKeyAuth help

### ISSUE THREAD

**Issue by dmcconnell68** [mevdschee/php-crud-api#785]
Hi, I'm trying to setup apiKeyAuth, but it doesn't seem to be working.  After adding the apiKeyAuth parameters below, I'm still able to get data back from the endpoint.  Am I missing something?

Here is an excerpt from the config:
'middlewares' => 'authorization,json,firewall,apiKeyAuth',
'authorization.tableHandler' => function ($operation, $tableName) {
			return $tableName != 'sys_servicekeys'
			&& $tableName != 'sys_credentials'
			&& $tableName != 'sys_globalcredentials'
			&& $tableName != 'sys_securitygroups'
			&& $tableName != 'sys_securitygroups_audit'
			&& $tableName != 'sys_usersettings'
			&& $tableName != 'sys_usersettings_audit'
			&& $tableName != 'users'
			&& $tableName != 'user_data';
		},
'firewall.allowedIpAddresses' => '10.216.1.41,10.20.65.15,10.20.65.17',
'apiKeyAuth.mode' => 'required',
'apiKeyAuth.header' => 'X-API-Key',
'apiKeyAuth.keys' => '8405d1af-f626-416e-a3dc-496956e41df4',
'debug' => true

Thanks,
David

**Comment by mevdschee** [comment]
Hi David,

Thank you for creating this issue. I am not able to reproduce your problem with the latest version, can you verify that you are running the latest release?

Maybe that config is not effective? Are you using `api.php` or `api.include.php`? Or are you loading the library through composer?

Kind regards,

Maurits

**Comment by mevdschee** [comment]
Great! I'm happy you able to fix the problem. Enjoy the software. Kind regards, Maurits
