### ISSUE TITLE
Multi table update?

### ISSUE THREAD

**Issue by binaryfire** [mevdschee/php-crud-api#786]
Hi guys

Just discovered this project. Very nice!

I couldn't find any info on multi table operations (like this: https://riptutorial.com/mysql/example/23211/multiple-table-update). Is that kind of thing possible with php-crud-api?

Cheers

**Comment by mevdschee** [comment]
Hi, thanks for creating this issue. I was not aware of this syntax in MySQL, so thank you for learning me something. Also this kind of query cannot be created using this project. So the answer is: no, this is not supported: in php-crud-api this requires multiple http requests. On the other hand there is a PR in the making that can support custom SQL, so maybe you could help finish that. Kind regards, Maurits

**Comment by binaryfire** [comment]
@mevdschee Custom SQL would be great! Would love to help but unfortunately my coding skills are pretty limited.

**Comment by mevdschee** [comment]
Thank you for your feedback. Let me know if you have further questions.
