### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 near "(": syntax error

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#788]
Hi,
I switch a working code from windows server to Debian and I got the following error on this request : `api.php/records/event` using sqlite

`"SQLSTATE[HY000]: General error: 1 near "(": syntax error"`

Apache logs : `FastCGI: server "/home/.../.fpm/php5.external" stderr: PHP message: PHP Fatal error:  Declaration of Tqdev\\PhpCrudApi\\Database\\LazyPdo::query(string $statement): PDOStatement must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /home/.../php-crud-api/api.php on line 6390`

Any ideas on whats going on?
Thank you

**here is the configuration used**

php version 7.2.34
system Linux Debian 4.9.210
PDO/sqlite enabled
sqlite 3.8.7.1
php-crud-api : 2.12.2

**Comment by mevdschee** [comment]
Thank you for creating this issue. SQLite needs to be "SQLite 3.16 or higher (spatial features NOT supported)" as per the requirements in the README. I hope this helps! Kind regards, Maurits

**Comment by thipages** [comment]
Ji, 
sorry about that.
Lots of time, when I read x.yz for version I understand x.y.z
I need to slow down when reading such version numbers.

Thank you and good day!!

**Comment by mevdschee** [comment]
> Lots of time, when I read x.yz for version I understand x.y.z

It is easy to overlook. I agree. 

NB: The reflection in that version has improved a lot, so I couldn't support the older versions.

>Thank you and good day!!

Same to you, enjoy the software.

**Comment by thipages** [comment]
Would it be difficult to support sqlite 3.11?
I can try to manage it if you think it is possible and in line with your library

The reason is
- that php 7.x ships default sql version from 3.11 (php 7.4) to 3.28 (php 7.3) (erratic and had difficulties to get a mapping betwwen php and sqlite version)
-  when using shared hosting, it uses default php version, where sqlite version can not be changed

**Comment by thipages** [comment]
Note : support sqlite 3.11 or lower DOES NOT MEAN using it as default
3.16 should be the default

**Comment by mevdschee** [comment]
>Would it be difficult to support sqlite 3.11?

Yes it would, because of the reflection support.

**Comment by thipages** [comment]
clear. Jammer
