### ISSUE TITLE
Data integrity violation 1010

### ISSUE THREAD

**Issue by GoJoe2** [mevdschee/php-crud-api#789]
Hello,

I have a question. I use a MySQL database and everything works just fine. Now, I started to include creation date and modification date columns in my tables with CURRENT_TIMESTAMP and ON UPDATE CURRENT_TIMESTAMP. Now, if I do a POST request with some information in postman, I get a the 1010 error.

Here is my table structure:

![grafik](https://user-images.githubusercontent.com/68908804/117493729-a9373700-af73-11eb-9ee5-4dbcc9002559.png)

An here is my request:

![grafik](https://user-images.githubusercontent.com/68908804/117493912-e7ccf180-af73-11eb-9838-70ef24735b7f.png)

If I try to set the dates explicitly, it doesn't work either:

![grafik](https://user-images.githubusercontent.com/68908804/117494017-092ddd80-af74-11eb-9cea-6e95e15bb1a1.png)

But, when I use the form-data structure in the POST request, everything works fine??

![grafik](https://user-images.githubusercontent.com/68908804/117494210-4e520f80-af74-11eb-8270-8bfc8fab0e7e.png)

I would be very thankful for any advice as to what is going on. I would like to use the raw format to post data.

Thank you very much!

Best

**Comment by mevdschee** [comment]
The field "mod_date" cannot be null on insert, you should set either a default value or allow a null value.

**Comment by mevdschee** [comment]
Also, you should not send formatted JSON, try leaving out all space characters and newlines.

**Comment by GoJoe2** [comment]
OK, now I'm kind of embarrassed!  It was the leading tab-space (only the leading one)! (Tab spaces in the middle are no problem.)

![grafik](https://user-images.githubusercontent.com/68908804/117529535-5cd21280-afd8-11eb-862b-6be2dbaace2e.png)


So thank you so so much! I will follow your advice send the correct header information and leave ot formating :)

I don't know if it is a bug or a feature, if the latter, if you haven't documented it somewhere, maybe that's a good idea.

And I got another question.

Is it possible to block, restrict, or hide one, or two tables from the script, as I do not want them to be exposed via the API?

Btw. if there is a way to donate something for all this great piece of software, please hint me at it.

Thanks again, best

**Comment by mevdschee** [comment]
Thank you for your kind words. You are not the first to encounter this problem, so I could do a bugfix for this. Kind regards, Maurits

**Comment by mevdschee** [comment]
I released v2.12.3 with this fix in it.

**Comment by GoJoe2** [comment]
Installed the update, and it works -> not that it is good practice, as I know now

**Comment by mevdschee** [comment]
>Installed the update, and it works -> not that it is good practice, as I know now

Thank you for your feedback.

I feel it should have been supported as the script tries to be not too strict on the the input. 

Thank you for reporting the issue and making the software better! 

Kind regards, Maurits
