### ISSUE TITLE
DBLIB Integration?

### ISSUE THREAD

**Issue by lquessenberry** [mevdschee/php-crud-api#79]
I am not in a position to use SQLSRV but I do have DBLIB available to me. My web server is on an Ubuntu box, but unfortunately I am not able to add any PHP to my SQL box running Windows Server 2012 and SQL 2012. I would LOVE to be able to use DBLIB in this as a solution or alternative to SQLSRV since I can't install that driver on my Linux machine.

**Comment by mevdschee** [comment]
Why are you using that? In my experience that driver has and had several long running problems (proper UTF8 support, date time formats, transaction support). I hope you are not using it in a production environment?

IMHO you should add an extra Windows server with IIS an PHP and use the better (Microsoft supported) driver.

I see no point in supporting this.

**Comment by lquessenberry** [comment]
As I said above I am not in a position to use IIS server because we are long invested in our *nix based web server with Drupal and it is being used to connect to a SQLserver box. I would totally use SQLSRV if I could, but I am not a in a position to. 

That being said, I realize that PDO is what is preferred in PHP7 and mssql_ functions are no longer supported. If I could get PDO based drivers to work, I would love to see this plugin supported in some fashion that allows me to use a *nix based web server that connects to a Windows based SQLserver.

**Comment by lquessenberry** [comment]
Thanks for at least looking. I am open to any kind of help that is relative and productive.

http://php.net/manual/en/ref.pdo-odbc.php

**Comment by mevdschee** [comment]
PDO does not change that all databases need to be fed different SQL variants, it merely standardizes the calls that you need to do to execute these SQL queries and get their results.

**Comment by lquessenberry** [comment]
Thanks for taking time to explain. Hopefully one day Microsoft will release the proper driver for Linux users and you can support a Linux installed API that queries SQL Server. Thanks again for looking into this.

**Comment by mevdschee** [comment]
You are welcome. Thank you very much for giving feedback.
