### ISSUE TITLE
Restrict, or hide one, or two tables from the script

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#790]
@GoJoe2 wrote:

> Is it possible to block, restrict, or hide one, or two tables from the script, as I do not want them to be exposed via the API?

Yes, use the 'authorization.tableHandler' from the 'authorization' middleware with a to achieve this or set the 'tables' config parameter.

_Originally posted by @mevdschee in https://github.com/mevdschee/php-crud-api/issues/789#issuecomment-835163753_

**Comment by mevdschee** [comment]
Please let me know whether or not you succeed and whether or not the documentation is sufficient, see:

https://github.com/mevdschee/php-crud-api#authorizing-tables-columns-and-records

**Comment by GoJoe2** [comment]
OK. Got it working. Upon reflection I would like to restrict some operations on some tables. So for instance a POST request for one specific table and a get request for another. Unfortunately, I wasn't sure how it works, as I couldn't find any examples in the code. Here is what I tried:

`'authorization.tableHandler' => function ($operation, $tableName) {return !($operation == 'GET' && $tableName == 'USERANSWER');`

But, that doesn't to the trick.

Thanks for your input.

**Comment by mevdschee** [comment]
The `$operation` could be 'list', 'read', 'create', 'update' or 'delete', try a `die($operation)` and you'll find the values :-)

**Comment by GoJoe2** [comment]
Got it. I focused (while looking at this table) always on the words GET, POST etc. and overlooked the coresponding phrases for the operation variable.

I got everything working, how do I combine my two usecases, that is, how do I disable access to some tables completely and for some only some operations. 

Should this be the way?

```
		'authorization.tableHandler' => function ($operation, $tableName) {
 			return !($operation == 'create' && $tableName == 'PREMISE'); 
			return !($operation == 'update' && $tableName == 'PREMISE'); 			
			return !($operation == 'create' && $tableName == 'COUNTERFACTUAL');
			return !($operation == 'update' && $tableName == 'COUNTERFACTUAL'); 		
			return !($operation == 'list' && $tableName == 'RESULT'); 			
			return !($operation == 'read' && $tableName == 'RESULT');
			return $tableName != 'AI';			
			},
```
Strangly, bevore I included the last line disabeling access to the table AI, everything works as intended. Now, the respective operations are blocked for PREMISE and COUNTERFACTUAL, but are working again for the table RESULT and AI can still be accessed.

Maybe you know what's going on.

Thank you!

**Comment by mevdschee** [comment]
>Could there be somehow a buffer or memory thing involved?

Yes, there is a cache involved. You can set 'cacheType' to 'NoCache' to avoid caching of the reflected model.

I hope this helps. Kind regards, Maurits

**Comment by i2pacg** [comment]
Hello , can i suggest 2 things hopefully it helps
1: When setting up and doing configuration its better to have cacheType set to NoCache

2:change your authentication handler to this

	`	'authorization.tableHandler' => function ($operation, $tableName) {
```
if ($tableName == 'AI')
return false;

Switch($operation){
case 

}
```
 			
return !($operation == 'create' && $tableName == 'PREMISE'); 
			return !($operation == 'update' && $tableName == 'PREMISE'); 			
			return !($operation == 'create' && $tableName == 'COUNTERFACTUAL');
			return !($operation == 'update' && $tableName == 'COUNTERFACTUAL'); 		
			return !($operation == 'list' && $tableName == 'RESULT'); 			
			return !($operation == 'read' && $tableName == 'RESULT');
			return $tableName != 'AI';			
			},`

**Comment by mevdschee** [comment]
Did you make any progress? Do you have an update?

**Comment by GoJoe2** [comment]
Thx for your question. Haven't had to chance to work on it again. Will go at it tomorrow.

**Comment by mevdschee** [comment]
>Will go at it tomorrow.

No rush, I just wondered. Take your time.

**Comment by GoJoe2** [comment]
Hi there,
I finally got it working ... my PHP is a bit rusty ... how can 20 years be gone that fast?! Never mind.
Got it working, and runs just fine.

If you have any comments, feel free to go at it! I'm happy about any hints and tips.

One thing I noticed: You can't couple several conditions in on return call, is that correct?

To visualize it, here is how I got it working:
`'authorization.tableHandler' => function ($operation, $tableName)
{
if ($operation == 'list' && $tableName == 'TABLEA'){return !($operation == 'list' && $tableName == 'TABLEA');}
elseif ($operation == 'read' && $tableName == 'TABLEA'){return !($operation == 'read' && $tableName == 'TABLEA');}				
elseif ($operation == 'delete' && $tableName == 'TABLEA'){return !($operation == 'delete' && $tableName == 'TABLEA');}	
elseif ($operation == 'increment' && $tableName == 'TABLEA'){return !($operation == 'increment' && $tableName == 'TABLEA');}	
elseif ($operation == 'create' && $tableName == 'TABLEB'){return !($operation == 'create' && $tableName == 'TABLEB');}	
elseif ($operation == 'update' && $tableName == 'TABLEB'){return !($operation == 'update' && $tableName == 'TABLEB');}	
elseif ($operation == 'increment' && $tableName == 'TABLEB'){return !($operation == 'increment' && $tableName == 'TABLEB');}	
elseif ($operation == 'delete' && $tableName == 'TABLEB'){return !($operation == 'delete' && $tableName == 'TABLEB');}	
elseif ($tableName == 'TABLEC') {return $tableName != 'TABLEC';}
elseif ($tableName == 'TABLED') {return $tableName != 'TABLED';}		
else
{return $tableName != 'TABLEE';}
},`

What was not working is do the same as above but putting all complete table denials in one last return statement:
`'authorization.tableHandler' => function ($operation, $tableName)
{
if ($operation == 'list' && $tableName == 'TABLEA'){return !($operation == 'list' && $tableName == 'TABLEA');}
elseif ($operation == 'read' && $tableName == 'TABLEA'){return !($operation == 'read' && $tableName == 'TABLEA');}				
...
else
{return $tableName != 'TABLEC' || $tableName != 'TABLED';}
},`
And so on.

Did I write it incorrectly?

Thanks again

Best

**Comment by mevdschee** [comment]
Hi,

In most (if not all) of the cases `return false` would do I suppose.

I would end with a `return true`, also I would not use any `else`.

I guess that makes the code more readable.

Anyway, good job! I'm glad you got it working.

Take care,

Maurits

**Comment by GoJoe2** [comment]
Thanks. I cleaned it up a bit according to your suggestions.

Wish you all the best.
