### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by becangular** [mevdschee/php-crud-api#792]
Hi, thanks for this great script!
it is possible not to have the public API, but to use, for example, a simple string to add to the body of the call?
Or what do you suggest to me?
thanks
joseph

**Comment by mevdschee** [comment]
Thank you for your kind words.

> it is possible not to have the public API, but to use, for example, a simple string to add to the body of the call?

I'm not sure what you mean, but maybe you want to explore the 'apiKey' middleware. The simple string should not be added to the body, but to the request header named 'X-API-Key', see:

https://github.com/mevdschee/php-crud-api#api-key-authentication

Kind regards, Maurits

**Comment by becangular** [comment]
Hi Maurits, thanks for the reply!
Can you write me an example of how to set up middleware in api.php?

'middlewares' => 'apiKeyAuth.header', and then?

Thanks again

BR
joseph

**Comment by mevdschee** [comment]
Something like this:

    $config = new Config([
        // 'driver' => 'mysql',
        // 'address' => 'localhost',
        // 'port' => '3306',
        'username' => 'php-crud-api',
        'password' => 'php-crud-api',
        'database' => 'php-crud-api',
        'middlewares' => 'cors,apiKeyAuth',
        'apiKeyAuth.keys' => '123456789abc',
        // 'debug' => false
    ]);
    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    ResponseUtils::output($response);

See also: https://github.com/mevdschee/php-crud-api/blob/main/tests/config/base.php

**Comment by becangular** [comment]
Many thanks, but why if I type the url in my browser it works even without the apiKeyAuth?

Shouldn't the url be blocked without the key in the header?

**Comment by mevdschee** [comment]
>Shouldn't the url be blocked without the key in the header?

Yes, when `apiKeyAuth.mode` is set to `required` (default) it should.

**Comment by becangular** [comment]
Yes, I have this code setup:

   $config = new Config([
         //'driver' => 'mysql',
         //'address' => 'localhost',
         //'port' => '3306',
         'username' => 'user',
         'password' => 'password',
         'database' => 'mydb',
         'tables'=> 'myteable',
         'apiKeyAuth.mode'=> 'required',
         'middlewares' => 'cors, apiKeyAuth',
         'apiKeyAuth.keys' => '123456789abc',
          // 'debug' => false
    ]);

but the url works the same! Why?

**Comment by mevdschee** [comment]
>but the url works the same! Why?

It could be a bug. I'll investigate and let you know.

**Comment by becangular** [comment]
I downloaded the latest version of the api.php file and now it works.
Thanks so much

joseph

**Comment by mevdschee** [comment]
> Thanks so much

I'm glad you got it working. Enjoy the software! Kind regards, Maurits
