### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by gerald-b** [mevdschee/php-crud-api#794]
I'm playing with your great piece of SW an got an reproduceable warning.
I got an warning "A non-numeric value encountered"

# How to reproduce
* get an managed webspace
* create a subdomain
* create a mysql database and some example tables
* upload the api.php
* set in the config section: 
```php
        'username' => 'username',
        'password' => 'secretPassWord',
        'database' => 'dbname',
        // 'debug' => false
        'controllers' => 'records,status,columns,openapi'
```
* call `https://sub.example.com/api.php/openapi`
* admire the problem ;-)
* remove the "columns" from then config section
* warning is gone

# Technical Notes
* PHP 7.3
* MySQL 5.7.28

# Tested Version
* https://github.com/mevdschee/php-crud-api/tree/v2.12.3
* https://github.com/mevdschee/php-crud-api/tree/fa97f863162cd4f44b1ff8b920194c260dea67c5

I hope this is usefull.
btw. is the an other way to get an table stucture?

If you need more information feel free to ask.

Kind regards 
Gerald

**Comment by gerald-b** [comment]
I added the tested Versions. Hope this helps.

**Comment by mevdschee** [comment]
Hi Gerald, thank you for your report! I will fix this ASAP and let you know when the fix has been released. Kind regards, Maurits

**Comment by mevdschee** [comment]
New release:

https://github.com/mevdschee/php-crud-api/releases/tag/v2.12.4

**Comment by gerald-b** [comment]
Thanks for the fast response.

I'm proud. This is my first bug report which result in an fix and an new release.

**Comment by mevdschee** [comment]
>I'm proud. This is my first bug report which result in an fix and an new release.

Rightly so, thank you for your contribution!
