### ISSUE TITLE
Create record with uuid as primary key always returns "0"

### ISSUE THREAD

**Issue by garrettcam** [mevdschee/php-crud-api#795]
If a table has a Primary Key `id` that uses `uuid()` either a `CHAR(36)` or `BINARY(16)`  the create process returns `0` instead of the uuid as `SELECT LAST_INSERT_ID()` only works on `AUTO_INCREMENT` fields.

**Comment by mevdschee** [comment]
Hi, Thank you for creating this issue. I understand the problem you are describing. Do you have a proposal to improve the behavior? You seem to have a default `uuid()` on the primary key column set. Instead I would generate the uuid client-side to work around this. Kind regards, Maurits

**Comment by mevdschee** [comment]
Note that:

>assigning UUID() as DEFAULT value won't work, because It does not guarantee that the same value will be generated on your replica. That is why using TRIGGER is good option for new records (insertions).

source: https://stackoverflow.com/questions/64003814/uuid-as-default-for-mysql-id-column

**Comment by garrettcam** [comment]
Hi, thanks for the suggestion. I did indeed have `uuid() `as default. I've shifted to generating UUIDv4 client side.
