### ISSUE TITLE
Firebase JWT help

### ISSUE THREAD

**Issue by sam-claire** [mevdschee/php-crud-api#797]
/Hi,

Thanks for the marvelous job. Btw I have successfully integrated my first Firebase Auth to sample vanilla.html. I'm quite confused that do I need to call  'function initApp() '  everytime I need to fetch data from my remote server ? Or I just need it to call only once at load ? Thanks so much

**Comment by mevdschee** [comment]
> Or I just need it to call only once at load ? Thanks so much

Once at load is what I expect (given that you create a single page application).

Kind regards, Maurits

**Comment by sam-claire** [comment]
i will be using vue/axiso so the best practice is to call function 'initApp()'  in Mounted() or Created(), then when I need to call request I just need to use axios.get, post and so on? 

thanks

**Comment by mevdschee** [comment]
>then when I need to call request I just need to use axios.get, post and so on?

I'm not familiar with vue/axios, but I guess you are right about this. I once build this that may help you: 

https://github.com/mevdschee/vue-crud-ui

Kind regards, Maurits

**Comment by thipages** [comment]
Hi,
btw, you may be interested in using a tiny [dedicated JS API for PHP-CRUD-API](https://github.com/thipages/js-crud-api).
This may be easier to use and will work with Vue the same way I guess.
If you want to give a try...
