### ISSUE TITLE
Updating table - column name as value

### ISSUE THREAD

**Issue by mayestik1** [mevdschee/php-crud-api#798]
Hello,
I am getting an error while trying to update records with column names.
Example request
`PUT /records/table_name/record_ID`
`
{
    "title": "other_column_name"
}`

Response headers
`X-Exception-Name: PDOException`
`X-Exception-Message: SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server] Error converting data type nvarchar to numeric.`

I would like to run query like this:
`UPDATE table_name SET title = other_column_name WHERE id = record_ID`

**Comment by mevdschee** [comment]
Hi, thank you for opening this issue. It seems like you want to update one column with the value of another column. This is not supported. Kind regards, Maurits
