### ISSUE TITLE
How to add block multiple column ?

### ISSUE THREAD

**Issue by aouniradouan** [mevdschee/php-crud-api#799]
Hi sir i hope you're doing well, i want to block multiple column from access please how i can do that with tables and columns

`        'authorization.columnHandler' => function ($operation, $tableName, $columnName) {
            return !($tableName == 'users' && $columnName == 'password');
        }`

**Comment by mevdschee** [comment]
Something like this?

    'authorization.columnHandler' => function ($operation, $tableName, $columnName) { return !(in_array("$tableName/$columnName",['users/password','table2/field2'])); }

**Comment by aouniradouan** [comment]
This what i need, Thank You

**Comment by mevdschee** [comment]
Good.. enjoy the software!
