### ISSUE TITLE
Not supporting fields of type 'Text'

### ISSUE THREAD

**Issue by BoldijarPaul** [mevdschee/php-crud-api#8]
When I create a field in my table with the type TEXT (from phpmyadmin) the api will return something like 

{
id: "660",
imageFull: "http://s15.postimg.org/ddbe3s9q3/images_154.jpg",
imageMedium: null,
category: "Fara",
date: "1420423665425",
details: "TW9yIDopKQ=="
},

Here  the details field is as type 'TEXT', if i change it back to varchar(100) everything will be ok
{
id: "660",
imageFull: "http://s15.postimg.org/ddbe3s9q3/images_154.jpg",
imageMedium: null,
category: "Fara",
date: "1420423665425",
details: "Mor :))"
},

Anyways, the filtering seems to work with fields with the type 'TEXT'.

**Comment by mevdschee** [comment]
The field is identified as type "binary" and thus the output is in base64. What collation did you choose on the column?
