### ISSUE TITLE
help needed using authorization.columnHandler

### ISSUE THREAD

**Issue by garrettcam** [mevdschee/php-crud-api#802]
I am trying to hide multiple columns, on different tables, depending on operation

I want to hide the `modified` column when ` $operation ==  'update'` so react-admin doesn't clobber `on update current_timestamp()` in MySQL

I have been able to get this working with the following

```
'authorization.columnHandler' => function ($operation, $tableName, $columnName) {
  return !($operation == 'update' && $columnName == 'modified');
},
```

When I attempt to do more than one set of conditions I get errors. I tried to use if statements, but get `code: 9999`
`message: "Return value of Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedTable::getColumn() must be an instance of Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedColumn, null returned"`

I'm obviously missing something. I've got more tables that need to one or two columns hidden but I can't figure out how to get it working.

```
'authorization.columnHandler' => function ($operation, $tableName, $columnName) {
  if ($tableName == 'persons') {
    return !($columnName == 'phone_home' OR $columnName == 'phone_mobile' OR $columnName == 'email_home');
  }
  if ($operation == 'update') {
    return !($columnName == 'modified');
  }
},
```

**Comment by mevdschee** [comment]
Hi, thank your for creating this issue. It can be many things. Can you post your table structure and the HTTP request that you are doing that causes the 9999 error? I'll try to reproduce and debug the issue. Kind regards, Maurits

**Comment by garrettcam** [comment]
Sorry to waste your time. So dumb, I forgot to `return true` after the final `if`.
