### ISSUE TITLE
DELETE and PUT commands send socket hang up

### ISSUE THREAD

**Issue by kitarolivier** [mevdschee/php-crud-api#803]
Hello,

Thank you for this nice API.

I'm stuck with the DELETE and PUT commands which return an "socket hang up" error in postman or in my app :

![image](https://user-images.githubusercontent.com/37141868/130368224-d3de0690-5b97-444d-aaa3-f9d4fa675f98.png)

I have no user rights and I'm logged as database admin, and php version is 7.2.31

I use an API key, which, in postman, is defined at workgroup and inherited on this command.

I don't know if I must specify something in the htaccess or configure something on the hosting website.

the GET function works, and you can see that ID 1 exists :
![image](https://user-images.githubusercontent.com/37141868/130368024-959e92a4-611b-49d3-a95e-43097b7d4458.png)

I'm a beginner with php APIs

Can you help me ?

**Comment by mevdschee** [comment]
This may have to do with the SSL handling. Did you try another host?

**Comment by kitarolivier** [comment]
Thank you for taking time to help me.

I don't have a proxy. Just my computer, wifi box to internet.

I will try to host the database to another provider.

I will udate when checked.

**Comment by kitarolivier** [comment]
I have checked the web hosting forums, and it seems that the DELETE command is allowed only for paid accounts.
 
 I'll try another host and keep you informed.

Thank you for your quick reaction ;)

**Comment by mevdschee** [comment]
>Thank you for your quick reaction ;)

You are welcome. I'm glad you found the cause.

**Comment by mevdschee** [comment]
I can offer you a workaround. In the config put the following: 

    // add these lines:
    if (isset($_GET['method'])) {
        $_SERVER['REQUEST_METHOD'] = $_GET['method'];
    }
    // before this line:
    $request = RequestFactory::fromGlobals();

By adding the above lines you can override the method, by specifying an extra get parameter 'method'. This allows you to POST for update, as long as you add `?method=PUT` to the URL.

**Comment by kitarolivier** [comment]
Thank you again for your reactivity. As I'm working now, I will try this that evenenig and will keep you informed. 

Fortunately, you provided a work around so quickly that I had no time to delete my site and accournt at 000webhost ;)

**Comment by kitarolivier** [comment]
Thank you for your help. Your workaround works fine for me :) . I can now delete and update records with the GET command and the method parameter with PUT or DELETE.

Are you supporting this in future versions, or will I need to "patch" file when updates will come ?

Regards,
Olivier.

**Comment by mevdschee** [comment]
>Are you supporting this in future versions, or will I need to "patch" file when updates will come ?

This will not be part of the release, but you can make it part of the config and include the config-less version `
api.include.php`. Does that work for you?

Kind regards, Maurits

**Comment by kitarolivier** [comment]
It is OK for me.

I will check the doc for the api.include.php and use it if you recommand it.

Again, thank you for your useful help -and API ;) -

Kind regards,
Olivier.
