### ISSUE TITLE
Route '' not found with WampServer

### ISSUE THREAD

**Issue by adri1b** [mevdschee/php-crud-api#805]
Hello,
Are there many specific settings for Wamp please?
I have this issue:

`code | 1000
message | "Route '' not found"`
Idem when I try with a table name
Thanks a lot,

**Comment by mevdschee** [comment]
Do you have an update?

**Comment by adri1b** [comment]
Sorry for my absence (thanks to Covid...)
Is to possible to re-open the ticket please?

`PHP -S` returns nothing

**Comment by mevdschee** [comment]
>PHP -S returns nothing

Run:

    php -S localhost:8000

Now go to:

    http://localhost:8000/api.php

You will see: 

    {"code":1000,"message":"Route '' not found"}

This is normal. If the database you connect to has a table you need to use the name of that table, say "posts" and go to:

    http://localhost:8000/api.php/records/posts

You should now see the contents of that table in JSON.

I hope this helps. 

Kind regards,

Maurits

**Comment by adri1b** [comment]
I try all that tomorrow.
I hope it will work.
Thanks a lot 😉

**Comment by adri1b** [comment]
I have dropped the "api.php" file in "C:\Wamp64\www"
When I try to access it, I have a 404 issue message :-/

**Comment by mevdschee** [comment]
> When I try to access it, I have a 404 issue message :-/

How do you try to access it, what is the URL? Did you read my reply? Did you read the manual?

**Comment by adri1b** [comment]
Hello @mevdschee 
Here is the URL I try to access: "http://localhost:8000/api.php/records/categories"
I have set the configuration part:

`$config = new Config([
    'driver' => 'mysql',
    'address' => 'localhost',
    'port' => '3306',
    'username' => 'rooti',
    'password' => '',
    'database' => 'common',
    'debug' => false
]);`

I ran PHP with this command, as you asked: `php -S localhost:8000`
Here is the log:

`PS C:\Users\Adrien> php -S localhost:8000
[Mon Dec  6 11:55:15 2021] PHP 7.4.26 Development Server (http://localhost:8000) started
[Mon Dec  6 11:56:04 2021] [::1]:61206 Accepted
[Mon Dec  6 11:56:04 2021] [::1]:61206 [404]: (null) /api.php/records/categories - No such file or directory
[Mon Dec  6 11:56:04 2021] [::1]:61206 Closing
[Mon Dec  6 11:56:04 2021] [::1]:61207 Accepted
[Mon Dec  6 11:56:04 2021] [::1]:61207 Closed without sending a request; it was probably just an unused speculative preconnection
[Mon Dec  6 11:56:04 2021] [::1]:61207 Closing`

I'm sorry to ennoy you with that :-/

**Comment by mevdschee** [comment]
>I'm sorry to ennoy you with that :-/

**Comment by adri1b** [comment]
Thanks a lot @mevdschee 😉

**Comment by mevdschee** [comment]
Can you assure that the `pdo_mysql` and `mysqli` extensions are loaded?

**Comment by mevdschee** [comment]
By the way, I downloaded Mysql 8, PHP 7.4 on Windows 10 and everything works fine (after enabling those extensions).

**Comment by adri1b** [comment]
I replaced the default php.ini file like you, by the one of production.
And now, it works good 👍👍👍

I have the php.ini files (and restarted Wamp of cours), and it works now.
I don't really understand why, but you found a solution 😉

Thank you to have a look on it 😉
A really big thank !!!!
