### ISSUE TITLE
Configuration value tables: Empty string should mean 'none', not 'all'

### ISSUE THREAD

**Issue by akuehnis** [mevdschee/php-crud-api#806]
The documentation says that configuration value 'tables' defaults to 'all'. That is ok if I do not pass the configuration value at all.

However, if the value is set to '' (empty string), in my brain's logic this means 'No tables', not 'all the tables'. 

Regards
Adrian

**Comment by mevdschee** [comment]
Hi Adrian, empty strings are considered as "no configuration" and thus fallback to the default setting of "all tables".

**Comment by zemian** [comment]
Actually, I found that if you set `tables => ''` in Config, it returns all tables. but if you set `tables => 'all'` it actually does not return anything! Maybe there is something to fix here.

**Comment by mevdschee** [comment]
Released in v2.14.6
