### ISSUE TITLE
Change response json/string. How do?

### ISSUE THREAD

**Issue by APMU** [mevdschee/php-crud-api#809]
The default json response is:

> {
>     "records":[
>         {
>             "id": 1,
>             "title": "Hello world!",
>             "content": "Welcome to the first post.",
>             "created": "2018-03-05T20:12:56Z"
>         }
>     ]
> }

I need to change for:

> {
>     "contents":[
>         {
>             "id": 1,
>             "title": "Hello world!",
>             "content": "Welcome to the first post.",
>             "created": "2018-03-05T20:12:56Z"
>         }
>     ]
> }

OR

> [
>         {
>             "id": 1,
>             "title": "Hello world!",
>             "content": "Welcome to the first post.",
>             "created": "2018-03-05T20:12:56Z"
>         },
>         {
>             "id": 2,
>             "title": "Hello world!",
>             "content": "Welcome to the first post.",
>             "created": "2018-03-05T20:12:56Z"
>         }
> ]

How do it?

**Comment by mevdschee** [comment]
See #564
