### ISSUE TITLE
EmberJs

### ISSUE THREAD

**Issue by BlackBlackou** [mevdschee/php-crud-api#81]
Hey,

i want use the api for EmberJs but in emberJs for a post or a put the framework send: "{**oeuvre:**{"id":"5","oeuvre_nom":"Fountin"}}"

What i can change in api for it accept my request "post" or "put" with the name of database after.

Thank you, and sorry for my bad english.

**Comment by mevdschee** [comment]
EmberJS has some requirements on the way the JSON data is structured (both sending and receiving). You may want to write a custom adapter to connect to PHP-CRUD-API. Here is the documentation for that: https://guides.emberjs.com/v1.10.0/models/customizing-adapters/

**Comment by mevdschee** [comment]
Closed due to inactivity
