### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by becangular** [mevdschee/php-crud-api#811]
Hi, I am using Angular to authenticate, this is my code:

'middlewares' => 'dbAuth, xsrf, authorization,cors, ajaxOnly, apiKeyAuth, json',

and call this route: /login

Everything works, and I also have my username in the localstorage!

The problem arises when I have to make a get call, for example: records/mytable, I've this error:

{
    "code": 1011,
    "message": "Authentication required"
}

I also used authentication via X-API-Key, but don't work.

If I delete 'dbAuth' from the middleware, call get work, nut don't work login page! I'm a little confused!

What route do you recommend?

Thanks

Peppe

**Comment by mevdschee** [comment]
Hi, I don't recommend using dbAuth and apiKeyAuth together, nor xsrf and ajaxOnly. Maybe you should try to get it to work by adding one middleware at a time and investigate the behavior that each middleware adds. For instance 'dbAuth' requires cookie storage if I recall correctly, while apiKeyAuth is simpler and works without cookies.

**Comment by becangular** [comment]
Thanks for the reply. If I only use JWT authentication can I also manage users for the login page? (as usually happens in SPAs)
