### ISSUE TITLE
Use of APIKEYAUTH inside Docker Container

### ISSUE THREAD

**Issue by marionee** [mevdschee/php-crud-api#817]
Hi there,
i tried to set these variables:
PHP_CRUD_API_MIDDLEWARES=["apiKeyAuth"]
PHP_CRUD_API_APIKEYAUTH_KEYS=mysuperpassword

The errore that i received is "Return value must be of type array, string returned in /var/www/html/api.php:11663"

Hoping you can help me, thank you.

**Comment by mevdschee** [comment]
v2.13.3 released, that contains this fix.

**Comment by marionee** [comment]
Perfect! Thank you.

**Comment by marionee** [comment]
Now PHP_CRUD_API_MIDDLEWARES is working, but PHP_CRUD_API_APIKEYAUTH_KEYS seems to be not working.
If i use this test conf:
**PHP_CRUD_API_MIDDLEWARES: "apiKeyAuth"
PHP_CRUD_API_API_KEY_AUTH_KEYS: "mysuperpassword"**

and then i call with header **X-API-Key: mysuperpassword** i get
{
  "code": 1012,
  "message": "Authentication failed for 'mysuperpassword'"
}

**Comment by mevdschee** [comment]
@marionee as this issue is already closed I'm opening a new one for the bug you've found.
