### ISSUE TITLE
Search on equal strings is broken when character '+' is used

### ISSUE THREAD

**Issue by MaccerC** [mevdschee/php-crud-api#819]
Hello Maurits,
I'm using this code to get similar records:
/api.php/records/table?filter=item,eq,"some value"

When 'some value' contains the character '+' I'm only getting one record instead of all the other similar records.

I wonder if I'm doing something wrong or is this the way it works and I should not use the plus sign in a column?

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue.

Instead of using quotes:

    /api.php/records/table?filter=item,eq,"some value"

You need to apply urlencoding, like this:

    /api.php/records/table?filter=item,eq,some%20value

A "space" is encoded as "%20", you can play with urlencoding here: https://www.urlencoder.io/

Kind regards, Maurits

**Comment by MaccerC** [comment]
Great tip! Thank you!
