### ISSUE TITLE
Probleme with PATH_INFO 

### ISSUE THREAD

**Issue by albu77** [mevdschee/php-crud-api#820]
I've installed api.php on my wamp under `www/MyCave/back/api.php`.
I've defined the virtual host and it's working I've checked it with an `index.php` .
If I comment the first line testing the `PATH_INFO`  it's working but only in this case without commenting it is dying .
Is there an explaination....?

**Comment by mevdschee** [comment]
Hi, thank you for reporting this issue. What does the error.log say? Kind regards, Maurits

**Comment by albu77** [comment]
Sorry, I don't  understand when I downloaded your apia.php I got this code with an imperative die I didn't pay attention to. I could not find this in your repository now. So in fact the code I got had a hard breakpoint.....
![image](https://user-images.githubusercontent.com/624802/139855136-5e51b80b-8656-46ee-915e-85cfd4d0bb2e.png)

**Comment by mevdschee** [comment]
ah.. you must have been unlucky to have downloaded a broken version. I'm very sorry this happened.

**Comment by mevdschee** [comment]
Note that the code is tested by over 100 test and official releases (see releases) are not very likely to be broken.

**Comment by mevdschee** [comment]
Thank you for your kind words, please let me know whether or not you got it working.
