### ISSUE TITLE
Update view in SQL Server fails with error 405

### ISSUE THREAD

**Issue by andreas-sakellariou** [mevdschee/php-crud-api#823]
As per the title, although retrieving data from an SQL Server view works as expected, updating the same view fails with Error 405 'Method not allowed'

The api.php response is:
`{"code":1015,"message":"Operation 'update' not supported"}`

It has been verified that the view is updatable via SSMS.

Is that the expected behavior (ie view updates are not supported) or a problem specific to my implementation?

Is there an easy way to bypass it by changing code in api.php?

**Comment by mevdschee** [comment]
>Is that the expected behavior (ie view updates are not supported) or a problem specific to my implementation?

While some views can be updated (updatable) the code only supports updating tables, not views, see: 

https://github.com/mevdschee/php-crud-api/blob/1000fb1ea0c710b2aa1bd74182ae53066b47dd8a/src/Tqdev/PhpCrudApi/Controller/RecordController.php#L171

This is due to lack of the primary key reflection on views.

>Is there an easy way to bypass it by changing code in api.php?

Not that I'm aware of, but I'm open to suggestions.

**Comment by andreas-sakellariou** [comment]
Hi thanks for the fast response.

Why not letting the update query pass-through and get the result from the server?

Or make the assumption  that the field "id" (or "ID") or the the first field is the key?

**Comment by mevdschee** [comment]
>Or make the assumption that the field "id" (or "ID") or the first field is the key?

That assumption is already made (field name 'id' is chosen in case of a view), see:

https://github.com/mevdschee/php-crud-api/blob/1000fb1ea0c710b2aa1bd74182ae53066b47dd8a/src/Tqdev/PhpCrudApi/Column/Reflection/ReflectedTable.php#L53

I guess you are right and by commenting out the suggested line (171 in RecordController.php) may work for you.

**Comment by andreas-sakellariou** [comment]
Hi Maurits,

Good news! I had to comment out the following lines (although I have no idea of PHP):

https://github.com/mevdschee/php-crud-api/blob/1000fb1ea0c710b2aa1bd74182ae53066b47dd8a/api.php#L4754
https://github.com/mevdschee/php-crud-api/blob/1000fb1ea0c710b2aa1bd74182ae53066b47dd8a/api.php#L4787
https://github.com/mevdschee/php-crud-api/blob/1000fb1ea0c710b2aa1bd74182ae53066b47dd8a/api.php#L4729
https://github.com/mevdschee/php-crud-api/blob/1000fb1ea0c710b2aa1bd74182ae53066b47dd8a/api.php#L4810

I have tested successfully the 'update' and 'delete' operations. I did not have the chance to check 'create' and I don't know about the 'increment' functionality that were also commented out

So yes, I can work with updateable views.

Thanks for your responsive feedback.
