### ISSUE TITLE
Quasar App local with dbAuth - 401 unauthorized

### ISSUE THREAD

**Issue by Jakan** [mevdschee/php-crud-api#827]
Hi,

I'm creating a Quasar app (Vuejs). I have a mysql DB on a server and my api.php Configuration is:

 $config = new Config([
        'middlewares' => 'cors,dbAuth,authorization',
        'dbAuth.registerUser' => '1',
        'authorization.tableHandler' => function ($operation, $tableName) {
            return $tableName != 'users';
        },
        'cors.allowCredentials' => 'true',
        'username' => '###',
        'password' => '###',
        'database' => '###',
        'debug' => true,
    ]);

The ### are the right parameters. If i upload my app to the server or Android-Device i can login via "login-url" und then i can get the data from the database.

Only on local-development (localhost:8080) in the browser i can call the login-url successfully (with response), but if i call the url to geht the data from the database it says 401-unauthorized.

In postman on my pc it works correct. Is this a setting in the local Browser (Edge, Chrome, Firefox) on my Computer? Or is a missing parameter in the api Config?

For the API-Calls i use axios.

Thanks for your help!

**Comment by mevdschee** [comment]
Did you see #608?

**Comment by Jakan** [comment]
Hi,

first - thanks for your reply!

Now in my api.php:

$config = new Config([
'middlewares' => 'cors,dbAuth,authorization',
**'cors.allowHeaders' => 'Authorization',**
'dbAuth.registerUser' => '1',
'authorization.tableHandler' => function ($operation, $tableName) {
return $tableName != 'users';
},
'cors.allowCredentials' => 'true',
'username' => '###',
'password' => '###',
'database' => '###',
'debug' => true,
]);

but i get the same error.

On http://localhost:8080/ with login-URL:

![grafik](https://user-images.githubusercontent.com/3148066/145873203-8dd5bc0d-a56e-492a-8d2a-d6014bf3af5d.png)

After successful login i call a get-Call:
[HTTP/1.1 401 Unauthorized 143ms]

Greetings

Jayken

**Comment by Jakan** [comment]
Hi,

now it works with this adjustment:

 **'cors.allowHeaders' => ("Content-Type, X-XSRF-TOKEN, X-Authorization"),**

and before the api-get-call ->
axios.defaults.withCredentials = true;

Thanks for your great API! 

Greetings

**Comment by mevdschee** [comment]
This is due to your server configuration, see: #784

**Comment by mevdschee** [comment]
Did you solve the issue?

**Comment by Jakan** [comment]
Hi,

it works in the Firefox browser now. With the Edge and Chrome browser, the error "401 (Unauthorized)" continues to appear under localhost: 8080 after the successful login.

After i upload all files to a server, Firefox, Edge and Chrome works fine...

Regards

**Comment by Jakan** [comment]
Hi,

with session_set_cookie_params(['samesite' => 'None', 'secure' => true]); before session_start in the api.php it works with edge, firefox and Chrome!

Greetings

Jakan

**Comment by mevdschee** [comment]
I'm glad you figured it out. Since there is an enhancement open for adding this functionality I'll close this issue. Feel free to open a new issue if you have further questions.

**Comment by mevdschee** [comment]
>there is an enhancement open for adding this functionality

It is released in v2.14.15
