### ISSUE TITLE
Filter "eq" not case sensitive

### ISSUE THREAD

**Issue by EnMaster** [mevdschee/php-crud-api#828]
PHP Version
`PHP 7.4.3`
Link example
`https://127.0.0.1:8000/api.php/records/users?filter=user,eq,AdMin`
or
`https://127.0.0.1:8000/api.php/records/users?filter=user,eq,ADMIN`
or
`https://127.0.0.1:8000/api.php/records/users?filter=user,eq,admin`
The response are the same.
`{
    "records": [
        {
            "id": 1,
            "mail": "",
            "prov": "0.00",
            "user": "admin"
        }
    ]
}`

What can i do to make those requests case sensitive?

**Comment by mevdschee** [comment]
@EnMaster , good question, thank you. You should change the collation of the field to a case sensitive one. See: https://stackoverflow.com/questions/4558707/case-sensitive-collation-in-mysql

**Comment by EnMaster** [comment]
Great!
`ALTER TABLE <table-name> CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;`
Now my table and requests are case sensitive!
Thanks!
