### ISSUE TITLE
choose auth method

### ISSUE THREAD

**Issue by nik2208** [mevdschee/php-crud-api#829]
I'm a little confused regarding the use of PHP-API-AUTH and the middleware options available in PHP-REST-API.
I'm interested in:
- API key database authentication
- Database authentication
and
- PHP-API-AUTH
but I don't understand whether to use one of the firsts in combination of the latter, or alternately one of the three.

Can U drive me thru some wider docs to better understand what I'm missing?

**Comment by mevdschee** [comment]
Hi @nik2208 , Thank you for your question.

API key database authentication is most suitable if you have users in your database that you can or already have provided each their own API key.

Database authentication DbAuthMiddleware is most suitable if you have users in your database and you want your Mobile app to display a login form where people have to enter username and password.

PHP-API-AUTH is an authentication provider that can be used as an alternative to Auth0 to produce a JWT token to use with the JwtAuthMiddleware (that consumes a JWT token).

I hope that once you have an idea of what you want this information can help you choose. Or if you want you can share your use-case and we will give you some advice.

Kind regards, Maurits

**Comment by nik2208** [comment]
thank you. Reading your documentation I'm almost sure the most appropriate (but a bit more complex) method is the PHP-API-AUTH, and also needs custom user functions (login logout register). This wheels me to use the database authentication, which sadly returns me a 422 - 1021 - password to short whatever length of the password I send. Does it make sense?

**Comment by nik2208** [comment]
solved. wrong format of the request body. I've been able to register.
