### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Shavron** [mevdschee/php-crud-api#83]
this api does not supports join in two or more table, but without join how we get data. Because data is always scattered in multiple tables. Is it possible any way in this script ??

**Comment by mevdschee** [comment]
Can you please be more specific on what you are trying to accomplish (preferably with sample data or the included blog example SQL)? Have you read the README? What is not clear?

**Comment by Shavron** [comment]
thanks to reply. i already seen it. But i have different scenario. ok let me explain. i have 2 tables like products and product_category. in product table i have category id but i want category name from product_category table which id in product table. now i want join the records but no foreign key is defined. So can you tell me is there any way to get the same..

**Comment by mevdschee** [comment]
You need to define a foreign key.. or do two calls..

**Comment by Shavron** [comment]
my project is too old and cant define foreign key. and if 1 have 100 result for first table so for each row i have to make another call so it takes total 101 calls... if i am misunderstood please feel free to correct me..

**Comment by mevdschee** [comment]
You can do two calls, first one returns the "products", then you make an array of "category id" from that result and use the "in" filter with that array as an argument on the call to "product_category".

**Comment by Shavron** [comment]
thanks a lot for reply. I made foreign key and successfully fetch what i want.

one another thing if you can do a favor ..  my requirement is like this...... if i made a GET request i want output like below. bcoz if status is "failed" and no need to proceed. I did it for POST/PUT/DELETE but when trying to change list or retriveobject function, i am missing something.. dnt know what..
 
 {
status: "success",
count: 10,
data: {...}
}

**Comment by mevdschee** [comment]
I'm sorry, but that is not a very specific question. Please open a new issue if you need further help.
