### ISSUE TITLE
dbauth middleware: "dbAuth.registerUser" & "dbAuth.sessionName" options - clarifications

### ISSUE THREAD

**Issue by nik2208** [mevdschee/php-crud-api#832]
In the docs I read:
```"dbAuth.registerUser": JSON user data (or "1") in case you want the /register endpoint enabled ("")```
meaning that I can specify a JSON obj reflecting the users table fields? Need details to understand this..

then:
```"dbAuth.sessionName": The name of the PHP session that is started ("")```
what I use this option for?

thank u!

**Comment by mevdschee** [comment]
> "dbAuth.registerUser": JSON user data (or "1") in case you want the /register endpoint enabled ("")
> meaning that I can specify a JSON obj reflecting the users table fields? Need details to understand this..

Yes, you can specify the fields other than username and password that need to be set in a new user record.

> "dbAuth.sessionName": The name of the PHP session that is started ("")
> what I use this option for?

For the name of the session, as dbAuth uses PHP sessions, for more information, see:

https://www.php.net/manual/en/function.session-start.php
