### ISSUE TITLE
 middleware?

### ISSUE THREAD

**Issue by a565551313** [mevdschee/php-crud-api#833]
Could you tell me where to configure the parameters of the middleware?

**Comment by mevdschee** [comment]
>Could you tell me where to configure the parameters of the middleware?

At the end of the file "api.php" you will find some configuration parameters (like "password"). You can add your middleware parameters next to them.

I hope this helps. Kind regards, Maurits

**Comment by mevdschee** [comment]
Did you find it? Any update?

**Comment by a565551313** [comment]
Thank you for your reply. I found it. But it doesn't seem to work. I want to solve the problem of CORS. I want it to allow all. What should I do? I am a rookie. I look forward to your reply again.

**Comment by a565551313** [comment]
> 你找到了吗？任何更新？

Thank you for your reply. I found it. But it doesn't seem to work. I want to solve the problem of CORS. I want it to allow all. What should I do? I am a rookie. I look forward to your reply again.

**Comment by a565551313** [comment]
> 感谢你的回复。我找到了。但这似乎不起作用。我想解决CORS的问题。我希望它允许所有人。我该怎么办？我是菜鸟。我期待您的再次回复。

**Comment by a565551313** [comment]
> 你找到了吗？任何更新？
Thank you for your reply. I found it. But it doesn't seem to work. I want to solve the problem of CORS. I want it to allow all. What should I do? I am a rookie. I look forward to your reply again.

**Comment by mevdschee** [comment]
I'm glad you figured it out. Thank you for reporting back.

**Comment by 3257** [comment]
@mevdschee, is it possible to pass middleware through the `docker-compose.yml` files? 

say `PHP_CRUD_API_MIDDLEWARES=xml,cors`

I am trying and I am getting an error.
