### ISSUE TITLE
creation of tabel entry not fully working 

### ISSUE THREAD

**Issue by Kuhlig** [mevdschee/php-crud-api#834]
HI 
Thank you for this great piece of work! I want to create a new entry. Actually I do but there are two things wich are NOT working as expected

1) I get 0 as response - should be someting like 565875858758
2) the column "i18n_website_translation_old_id" is empty

I use this code generated (from postman) code. 
- Is it because I use BIGINT for the key? 
- the trigger "BEFORE INSERT "
Thank you for your help!
rob

docker-compose ... image: mariadb:latest ... & PHP 7.4.25

```
<?php
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://SOMEWHERE/DB-API/V1/records/i18n_website_translation',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS => 'i18n_website_translation_old_id%20=74356745674567456',
  CURLOPT_HTTPHEADER => array(
    'Authorization: Basic aTE4bi13ZWJzaPSSWDDDDDDDDDDDDMDk2NzQzODU2MA==',
    'Content-Type: application/x-www-form-urlencoded'
  ),
));
$response = curl_exec($curl);
curl_close($curl);
echo $response;
```
Table
```

CREATE TABLE `i18n_website_translation` (
  `i18n_website_translation_id` bigint(20) NOT NULL,
  `i18n_website_translation_old_id` text DEFAULT NULL,
  `_TS_CREATE` timestamp NOT NULL DEFAULT current_timestamp(),
  `_TS_UPDATE` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

DELIMITER $$
CREATE TRIGGER `i18n_website_translation_increment_insert` BEFORE INSERT ON `i18n_website_translation` FOR EACH ROW SET NEW.i18n_website_translation_id = (SELECT MAX(`i18n_website_translation_id`) + 61 FROM i18n_website_translation)
$$
DELIMITER ;

ALTER TABLE `i18n_website_translation`
  ADD PRIMARY KEY (`i18n_website_translation_id`),
  ADD UNIQUE KEY `i18n_website_translation_UNIQUE` (`i18n_website_translation_id`);

  ALTER TABLE `i18n_website_translation`
  MODIFY `i18n_website_translation_id` bigint(20) NOT NULL AUTO_INCREMENT;
COMMIT;
```

PS is NOT a connection problem GET is working an POST is also working but not fully

**Comment by Kuhlig** [comment]
the response 0 erros is due to the "BEFORE INSERT " trigger - 
it works when it teh trigger is deleted - any workarround on that?

now I'm focusieing on the insert error ....

**Comment by Kuhlig** [comment]
it works with josn :-)

  CURLOPT_POSTFIELDS =>'{
    "i18n_website_translation_old_id": "Black is the new red"
}',

So just have a look why the "BEFORE INSERT " trigger does not work .... Thanks rob

**Comment by mevdschee** [comment]
Hi Robert,

The code does not work with your custom trigger. I'm fine with that.

>So just have a look why the "BEFORE INSERT " trigger does not work .... Thanks

No, thank you. If you want to do business with me send me a proposal per email.

Kind regards,

Maurits

**Comment by Kuhlig** [comment]
>>So just have a look why the "BEFORE INSERT " trigger does not work .... Thanks
>No, thank you. If you want to do business with me, then you may send me a proposal per email

Sorry - shouldn't sound like a command - I also have a workaround, but if I get deeper into your API I'll definitely need more help and I'm willing to do this the bunisess way ... Have a nice 2022! and thanks again for the fast answer.

**Comment by mevdschee** [comment]
Hi Robert, I understand, no hard feelings. I just need to draw a line somewhere between open source contributions and work :-). Feel free to open a new issue if there is anything that seems to be a bug to you. Kind regards, Maurits

**Comment by Kuhlig** [comment]
top ! 

and it is not a bug ... see

https://stackoverflow.com/questions/15300673/mysql-error-cant-update-table-in-stored-function-trigger-because-it-is-already

"However, the value of an auto-increment field is only available to an "AFTER-INSERT" trigger - it defaults to 0 in the BEFORE-case."
