### ISSUE TITLE
Support SRID for spatial queries

### ISSUE THREAD

**Issue by mwasil** [mevdschee/php-crud-api#837]
Is it possible to add SRID declaration for spatial queries? At the moment query like this one:

    https://server/api.php/geojson/spatial_table?filter=SHAPE,sco,POINT(coordX coordY)

returns:
_SQLSTATE[HY000]: General error: 3033 Binary geometry function st_contains given two geometries of different srids: 1 and 0, which should have been identical._ 

Where my `spatial_table` has declared SRID (1) in related  `spatial_ref_sys` and `geometry_columns` tables according to MariaDB docs [[1](https://mariadb.com/kb/en/information-schema-spatial_ref_sys-table/),[2](https://mariadb.com/kb/en/information-schema-geometry_columns-table/)].

**Comment by mevdschee** [comment]
Should the SRID be made configurable? I guess it now defaults to 0.

**Comment by mwasil** [comment]
Yes, SRID 0 stands for unitless cartesian coordinate system ([see this explanation](https://stackoverflow.com/questions/25188020/what-is-srid-0-for-geometry-columns/25190899#answers)). I think it should be possible to specify SRID in the query otherwise it should be read from the queried table when no SRID-related argument is passed.

**Comment by pottertech** [comment]
If you are only supporting WKT (Well Known Text) format for spatial data, the SRID should be 4326 (WGS 84 or World Geodetic System 1984) geodetic datum. This is defined as part of the standards for WKT by OGC in this documentation https://en.wikipedia.org/wiki/Well-known_text_representation_of_coordinate_reference_systems.

**Comment by mevdschee** [comment]
@pottertech good point. PostGIS supports `SRID=4326;POINT(-44.3 60.1)` as (E)WKT value. Maybe we should support that too?

see: https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

**Comment by pottertech** [comment]
@mevdschee If you have a good idea on how to support SRID in PostGIS and any other of the databases such as MySQL then I think we should.

**Comment by mevdschee** [comment]
@pottertech Thank you for your great response. It seems support for SRID in the WKT definition is not yet there in MySQL and SQL Server. I'll change the default from 0 to 4326 as per the specification you referenced and make that value configurable.

**Comment by mevdschee** [comment]
Released in v2.14.7

**Comment by nik2208** [comment]
@pottertech don't know why u put a thumb here #910 but in the meanwhile I added something relevant here #926 maybe u can find it useful
