### ISSUE TITLE
dbauth - verify authentication status - renew authentication

### ISSUE THREAD

**Issue by nik2208** [mevdschee/php-crud-api#838]
is there a way to undestand the status of the connection/renew the authenticantion without sending a new login request?

**Comment by mevdschee** [comment]
Yes, you can call the "/me" endpoint every so many minutes.

**Comment by nik2208** [comment]
ok: does it renew the cookie validity? or in case of expired session there's need to login again in the background?

btw: how long does it last the cookie validity?

**Comment by mevdschee** [comment]
>does it renew the cookie validity?

Yes

>how long does it last the cookie validity?

It has a session validity, the timout is set in your php.ini, not by the script.
