### ISSUE TITLE
geojson from table

### ISSUE THREAD

**Issue by qwertz1958** [mevdschee/php-crud-api#839]
Hello,

in my database is a table. In this table are 2 columns 'lat' and 'lon'.
Is there a way to generate a geojoson file from this table.

| id | lat | lon | status |
| --- | --- | --- | --- |
| 614 | 12.614707946777344 | 50.638084890970575 | 3 |

For example:

<pre>
  {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {
         "id": "614", // id
          "marker-color": "#edd400",
          "marker-size": "medium",
          "marker-symbol": "industrial",
          "status": 3 // status
        },
        "geometry": {
          "type": "Point",
          "coordinates": [
            12.614707946777344, // lat
            50.638084890970575 // lon
          ]
        }
      }
    ]
  }
</pre>

Who can help ?

Your sincerly

Stephan

**Comment by mevdschee** [comment]
Hi Stephan,

I think you could add a view that has a geometry field (that is constructed from lat and lon) and try to access that using the geojson controller.

Kind regards, Maurits

**Comment by qwertz1958** [comment]
Hi  Maurits,

i have found the solution.
https://stackoverflow.com/questions/5756232/moving-lat-lon-text-columns-into-a-point-type-column

Greetings

Stephan

**Comment by mevdschee** [comment]
If you have a table `waypoints` with fields `lon` and `lat`:

    CREATE VIEW `waypoints_geom` AS SELECT `id`, GeometryFromText(CONCAT('POINT(',lon,' ',lat,')')) AS `point` FROM `waypoints`;

I hope this helps.

**Comment by qwertz1958** [comment]
Thanks for the support

**Comment by mevdschee** [comment]
Note that this kind of construct might be slower when querying than creating a "real" geometry column (because of indexes).
