### ISSUE TITLE
Filter and Sorting in own Controller

### ISSUE THREAD

**Issue by Kuhlig** [mevdschee/php-crud-api#841]
HI 

Do i have to code Filters, Multiple filters, Column selection, Ordering, Limit size, Pagination etc. for my own controlle by myself? Or is there any way i can "use" the allreday existing code ? 

thanks for Help 
rob

PS controller gives me same result (not null) for 

/DB-API/V1/SelectExample
and for 
/DB-API/V1/SelectExample?filter=i18n_website_translation_id,eq,2313

which is kind of logic, but i wonder if i can add the filter service somehow 

```
class MySQLController {

private $responder;

public function __construct(Router $router, Responder $responder, GenericDB $db, ReflectionService $reflection, Cache $cache)
{
    $router->register('GET', '/SelectExample', array($this, 'getSelectExample'));
    $this->responder = $responder;
    $this->db = $db;
}

public function getSelectExample(ServerRequestInterface $request): ResponseInterface
{
    $sql = "SELECT * FROM _TABLE_";
    $pdo_statement = $this->db->pdo()->query($sql);
    $result = $pdo_statement->fetchAll();
    return $this->responder->success(['results' => $result]);
}

```

**Comment by mevdschee** [comment]
closing for now due to lack of content

**Comment by qwertz1958** [comment]
Hello,

I think I have the same problem.
Unfortunately, aggregate features such as 'SUM ()' or 'Count ()' are not possible.
I need that for statistical purposes.
Therefore, I want to write my own controller.

This controller should first call the 'mytable' table.

Is a redirect in my controller possible ?
The original call is /myOwnController?filter=id,lt,20
The redirect is: '/ records / mytable? Filter = id, lt, 20'.

I want the result of the query as an array in my controller.

Second step: 
In my controller, I can make the aggregation of the datasets.

Third step :
The changed result is then returned as JSON.

Sorry for my bad English. :-(

Can someone help ?

Kind regards

Stephan

**Comment by mevdschee** [comment]
You can run (in the constructor):

    $this->recordService = new RecordService($db, $reflection);

And later do (in the action):

    $params = RequestUtils::getParams($request);
    $this->recordService->_list($table, $id, $params);
                    
I hope this helps.

**Comment by Kuhlig** [comment]
Thanks i give it a try and report back ...

**Comment by mevdschee** [comment]
any update?

**Comment by Kuhlig** [comment]
not yet - to bussy the last days - thanks for asking ...

**Comment by mevdschee** [comment]
any update?
