### ISSUE TITLE
Loads of "PHP message: PHP Deprecated:  Return type of ... #[\ReturnTypeWillChange] attribute ..." errors

### ISSUE THREAD

**Issue by GrahamCobb** [mevdschee/php-crud-api#842]
I have a tiny web app which has been running for some years using a very old version of php-crud-api on an old version of PHP.

The time has come to move to a new server, so I want to update to the latest versions (and probably not touch them again for another 5 years!). I am now using php:fpm with PHP 8.1.1. But when I try to use php-crud-api I get a log full of (apparently fatal) errors complaining about return types. An example is:

`NOTICE: PHP message: PHP Deprecated:  Return type of Tqdev\PhpCrudApi\Database\LazyPdo::errorCode(): mixed should either be compatible with PDO::errorCode(): ?string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/site/report-status/php-crud-api/api.php on line 6590`

Is there any way to easily suppress these so I can use php-crud-api?

Even if I get rid of these - will I hit any other issues trying to get php-crud-api to work on this version of PHP?

**Comment by mevdschee** [comment]
>Even if I get rid of these - will I hit any other issues trying to get php-crud-api to work on this version of PHP?

I will update my containerized tests to include 8.1 (currently it is testing from 7.0 to 8.0).

**Comment by GrahamCobb** [comment]
Brief update...

I now have my app working on the new server (PHP 8.1.1) using the old version of php-crud-api. That also produces these Deprecated messages, which go into the log files but do not appear in the output sent to the client.

Next, I plan to try the latest version of php-crud-api and to report back here.

**Comment by mevdschee** [comment]
Running on PHP 8.1:

    [root@476a0a5f05eb php-crud-api]# php test.php 
    mysql: 117 tests ran in 1260 ms, 1 skipped, 0 failed
    pgsql: skipped, driver not loaded
    sqlsrv: skipped, driver not loaded
    sqlite: 117 tests ran in 796 ms, 13 skipped, 0 failed
    [root@476a0a5f05eb php-crud-api]# php -v
    PHP 8.1.2 (cli) (built: Jan 18 2022 23:52:03) (NTS gcc x86_64)
    Copyright (c) The PHP Group
    Zend Engine v4.1.2, Copyright (c) Zend Technologies
        with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
    [root@476a0a5f05eb php-crud-api]#

**Comment by GrahamCobb** [comment]
Unfortunately, the current version of php-crud-api does not work for me. Note - my app code is unchanged, I just swapped the old php-crud-api directory for the current one.

The response back to the client looks like...

`<html><body><br>
<b>Deprecated</b>:  Return type of Tqdev\PhpCrudApi\Database\LazyPdo::errorCode(): mixed should either be compatible with PDO::errorCode(): ?string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/site/report-status/php-crud-api/api.php</b> on line <b>6590</b><br>
<br>
<b>Deprecated</b>:  Return type of Tqdev\PhpCrudApi\Database\LazyPdo::prepare($statement, $options = []) should either be compatible with PDO::prepare(string $query, array $options = []): PDOStatement|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/site/report-status/php-crud-api/api.php</b> on line <b>6605</b><br>
<br>
... lots more of the same ...
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/html/site/report-status/php-crud-api/api.php:10768) in <b>/var/www/html/site/report-status/php-crud-api/api.php</b> on line <b>11967</b><br>
<br>
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /var/www/html/site/report-status/php-crud-api/api.php:10768) in <b>/var/www/html/site/report-status/php-crud-api/api.php</b> on line <b>11967</b><br>
{&quot;code&quot;:1000,&quot;message&quot;:&quot;Route '\/statuslog' not found&quot;}       

<br>
<b>Fatal error</b>:  Uncaught Error: Class &quot;PHP_CRUD_API&quot; not found in /var/www/html/site/report-status/logapi.php:55
Stack trace:
#0 {main}
`

The requested update operation has not happened.

**Comment by mevdschee** [comment]
Thank you for your reports. I can't explain the "Fatal error" messages. The "Deprecated" warnings could indeed exist (and be surpressed) in my Centos 8 with "remi-8.1". I can try to increase the error reporting to show these and maybe fix them.

**Comment by mevdschee** [comment]
I have set "error_reporting" to "-1' and fixed all warnings.

**Comment by mevdschee** [comment]
I had to add some "ReturnTypeWillChange" attributes, as I wanted to maintain PHP 7.0 compatibility.

**Comment by mevdschee** [comment]
Released v2.13.2

**Comment by mevdschee** [comment]
@GrahamCobb Dear Graham, Thank you for your contribution. With this new release the software has become a little better thanks to you. Kind regards, Maurits
