### ISSUE TITLE
Aggregate features such as 'SUM ()' or 'Count ()'

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#843]
Hello,

I think I have the same problem.
Unfortunately, aggregate features such as 'SUM ()' or 'Count ()' are not possible.
I need that for statistical purposes.
Therefore, I want to write my own controller.

This controller should first call the 'mytable' table.

Is a redirect in my controller possible ?
The original call is /myOwnController?filter=id,lt,20
The redirect is: '/ records / mytable? Filter = id, lt, 20'.

I want the result of the query as an array in my controller.

Second step: 
In my controller, I can make the aggregation of the datasets.

Third step :
The changed result is then returned as JSON.

Sorry for my bad English. :-(

Can someone help ?

Kind regards

Stephan

_Originally posted by @qwertz1958 in https://github.com/mevdschee/php-crud-api/issues/841#issuecomment-1015281250_

**Comment by mevdschee** [comment]
>Can someone help ?

If you can specify how aggregate functions should work, then I might be able to add it for everybody.

**Comment by qwertz1958** [comment]
Hi there,

Here I have an older article on statistical functions in MySQL.
https://www.xarg.org/2012/07/statical-functions-in-mysql/
Unfortunately, MySQL has few possibilities for the statistical evaluation.
The basic functions of MySQL are for this purpose.
'Count (x)', 'sum (x)', 'avg (x)', 'min (x)', 'max (x)', 'std (x)'.

I think the 2 steps are desirable.
The first step contains the acquisition of the aggregate functions.

The second step contains the possibility to access a 'normal' request from a custom controller
before the result is converted to a JSON Response. Here the values can be permanently customized.
For example, for a JavaScript chart.

Kind regards

Stephan

**Comment by mevdschee** [comment]
I think we need a parameter saying what column to aggregate on and which function to use. Maybe also the group by directive somehow. Something like:

    /records/sales?aggregate=count(id),sum(price),avg(price),stddev(price)&group=product_category

Not sure though.. what do you think? Also.. this may be expensive..

**Comment by qwertz1958** [comment]
That would be the perfect solution !

**Comment by mevdschee** [comment]
Maybe an "AggregateController" would be better (to avoid application of the pageLimits):

    /aggregates/sales?fields=count(id),sum(price),avg(price),stddev(price)&group=product_category

I'm still not sure.

**Comment by mevdschee** [comment]
>Is a redirect in my controller possible ?

No, but you can let your (Apache) webserver rewrite any URL, achieving the same result.

NB: I'm closing this issue in favor of #60
