### ISSUE TITLE
Access to tables of a database 

### ISSUE THREAD

**Issue by qwertz1958** [mevdschee/php-crud-api#845]
Hi there,

I'm looking for a simple example to restrict access to the tables of a database.

Who can help ?

Kind regards

Stephan

**Comment by mevdschee** [comment]
>a simple example to restrict access to the tables of a database. Who can help ?

This is too vague for anybody to help you. What do you want? Read-only? Access with username/password login? API key requirements? IP whitelisting? Let us know.

**Comment by qwertz1958** [comment]
Hi there,

I have a database. The tables and views of this database cabinets I use the configuration option 'Tables'.
Now I want to realize only a read access to these tables and views. I recognize the parameter 'authorization.tableHandler' in the middleware. Unfortunately, I will not get on here. :-(
I need a simple example of the use of the middleware.

thank you

Stephan

**Comment by mevdschee** [comment]
>Now I want to realize only a read access to these tables and views. 

You should use something like:

    'authorization.tableHandler' => function ($operation, $tableName) {
        return in_array($operation, ['read','list']);
    },

I hope this helps.

**Comment by qwertz1958** [comment]
Thanks for the support 

Stephan
