### ISSUE TITLE
Use authorization.tableHandler depending on the user type

### ISSUE THREAD

**Issue by niyonx** [mevdschee/php-crud-api#846]
Hi, I have some tables I want to restrict access to.

E.g a normal user will be able to do GET only on a specific table, but an admin can do POST as well.

How do I achieve this? Any help is very much appreciated, thanks!

**Comment by mevdschee** [comment]
Hi, thank you for your question. Do you use the DbAuth middleware? Kind regards, Maurits

**Comment by niyonx** [comment]
No I don't, thanks for the reply!

**Comment by mevdschee** [comment]
Ok.. What is your use case? How do you want to use the software?

**Comment by niyonx** [comment]
I have some users which are either users or admin. They are stored in two different tables. Each has a column I want to use as the API key. (So I should probably use DbAuth as you mentioned), the operations allowed are different if it's a user or admin

**Comment by mevdschee** [comment]
Did you consider installing two instances of the script? Sometimes that makes things easier to customize and secure.

**Comment by niyonx** [comment]
That makes sense. On server side I can check what type of user it is, use DbAuth on different tables. Limit the operations differently on each of the script. Thanks @mevdschee !
