### ISSUE TITLE
Pass middleware through `docker-compose.yml` file

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#848]
@mevdschee, is it possible to pass middleware through the `docker-compose.yml` files? 

say `PHP_CRUD_API_MIDDLEWARES=xml,cors`

I am trying and I am getting an error.

_Originally posted by @3257 in https://github.com/mevdschee/php-crud-api/issues/833#issuecomment-1025662598_

**Comment by 3257** [comment]
Hey, @mevdschee , thanks for the adding it as an issue that quick. 
I do have a question before this gets taken care of, you have this as a comment in your `README`:

> All configuration options are also available as environment variables. Write the config option with capitals, a "PHP_CRUD_API_" prefix and underscores for word breakes, so for instance:

It's under [Configuration](https://github.com/mevdschee/php-crud-api#configuration). 

Can you be more specific, and maybe create an issue with Help Wanted for the configs that are actually missing as docker-compose environment variables.

**Comment by mevdschee** [comment]
>Can you be more specific, and maybe create an issue with Help Wanted for the configs that are actually missing as docker-compose environment variables?

Yes good point, I wasn't aware, but it seems not all config can be used as the parameter overrides are handled later (incorrectly?). This may be considered a bug or possible improvement.

**Comment by mevdschee** [comment]
See: #817

**Comment by mevdschee** [comment]
I feel it should be possible to adjust the code in such a manner that the docker overrides do work. I'm closing this as a duplicate.

**Comment by 3257** [comment]
@mevdschee I am new to php, to be honest, so if it is up to me, it'll take me some time 😄. 
Do you plan on taking care of it yourself or you mostly rely on people to help? (Putting aside the huge amount of work you have put into this already, thanks for that)

**Comment by mevdschee** [comment]
Thank you for your kind words.. I'm going to fix this soon.. :-)

**Comment by mevdschee** [comment]
v2.13.3 released, that contains a fix.

**Comment by 3257** [comment]
Yeah, that was indeed soon, thanks 👍

**Comment by mevdschee** [comment]
>Yeah, that was indeed soon, thanks +1

Yeah, fix, test and deploy in 2 hours. This is 100% due to version control, automated testing and automatic deployment (to github and dockerhub). :-)
