### ISSUE TITLE
dbAuth middleware: Username/Password request field

### ISSUE THREAD

**Issue by nik2208** [mevdschee/php-crud-api#849]
Could be useful to add (beside *dbAuth.usernameColumn* and *dbAuth.passwordColumn*) the possibility to configure the request fields (like *dbAuth.usernameRequestField*) to bind a specific request filed to the relative column of the auth table.

If I'm not mistaken the current state imposes *username* and *password* as mandatory fields for the request.

**Comment by mevdschee** [comment]
>If I'm not mistaken the current state imposes username and password as mandatory fields for the request.

Yes, you are correct. I've added this issue as a feature request. Out of curiosity, why is this feature important to you? I'm asking because typically people don't really care what the exact naming of their form fields is.

**Comment by nik2208** [comment]
I'm developing in angular, and happens that authentication libraries have their "own standard field".. so just in case you find yourself in the need to be compliant to different "standards", to avoid to "switch cases"..

hope I've been able to explain myself

**Comment by mevdschee** [comment]
>hope I've been able to explain myself

It is clear. I'll try to implement some configurable field names.

**Comment by nik2208** [comment]
I'm not so skilled in php.. but I can find myself around, if I have to mod code.. so.. if u need/want some help.. I cant try to

**Comment by mevdschee** [comment]
This is the code that needs to be made configurable:

        if ($method == 'POST' && in_array($path, ['login', 'register', 'password'])) {
            $body = $request->getParsedBody();
            $username = isset($body->username) ? $body->username : '';
            $password = isset($body->password) ? $body->password : '';
            $newPassword = isset($body->newPassword) ? $body->newPassword : '';

in `src/Tqdev/PhpCrudApi/Middleware/DbAuthMiddleware.php`

**Comment by nik2208** [comment]
exactly.. sorry for being disappeared.. very very very.. very busy period

**Comment by mevdschee** [comment]
I'll try to implement this when I find some time. :-)

**Comment by mevdschee** [comment]
This is released in [v2.13.4](https://github.com/mevdschee/php-crud-api/releases/tag/v2.13.4), closing the issue
