### ISSUE TITLE
Creating New Table

### ISSUE THREAD

**Issue by abureviewer3** [mevdschee/php-crud-api#85]
Hi, Is there any way to create a new table through api if yes can you guide me how to do this.

**Comment by mevdschee** [comment]
No it is not possible and I currently see no reason to add this.

**Comment by abureviewer3** [comment]
Thank you for you reply and one more thing can I retrieve column data from multiple table same like join in MYSQL.

eg:
Select a.id, a.name, b.parent_id
FROM tableA  AS a
LEFT JOIN tableB AS b ON b.tableA_id = b.tableB_id

Output:
id, name, parent_id

Thank you very much.

**Comment by mevdschee** [comment]
Yes, but it requires a foreign key and use of the "include" get parameter on the "list" command. Please consult the README.
