### ISSUE TITLE
Environment variable PHP_CRUD_API_API_KEY_AUTH_KEYS not working

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#850]
Now PHP_CRUD_API_MIDDLEWARES is working, but PHP_CRUD_API_API_KEY_AUTH_KEYS seems to be not working.
If i use this test conf:
**PHP_CRUD_API_MIDDLEWARES: "apiKeyAuth"
PHP_CRUD_API_API_KEY_AUTH_KEYS: "mysuperpassword"**

and then i call with header **X-API-Key: mysuperpassword** i get
{
  "code": 1012,
  "message": "Authentication failed for 'mysuperpassword'"
}

_Originally posted by @marionee in https://github.com/mevdschee/php-crud-api/issues/817#issuecomment-1031234547_

**Comment by marionee** [comment]
The problem I suppose is inside applyEnvironmentVariables, the variable PHP_CRUD_API_MIDDLEWARES_API_KEY_AUTH is  renamed to PHP_CRUD_API_API_KEY_AUTH, but after that getenv does not work.

**Comment by mevdschee** [comment]
Hi, I can't reproduce this issue. When I try on the command line, I do:

    PHP_CRUD_API_API_KEY_AUTH_KEYS=123 php test.php mysql 002 004

And the test fails (as it should).

**Comment by marionee** [comment]
Hi @mevdschee, i have tried a lot of combinations without luck, also using PHP_CRUD_API_API_KEY_AUTH_KEYS doesn't work. 
Have you tried it on Docker? Have you got a working yml configuration?
Thank you.

**Comment by mevdschee** [comment]
Hi @marionee,

> i have tried a lot of combinations

Such as? Please help me reproduce the issue you encounter step-by-step with some details about your environment.

> Have you tried it on Docker? Have you got a working yml configuration?

Yes, I have verified this in the test setup, did you? It is easy enough to run the command:

    PHP_CRUD_API_API_KEY_AUTH_KEYS=123 php test.php mysql 002 004

expected output is:

    =====[/002 Auth/004 Api Key Auth]=====
    200
    Content-Type: application/json; charset=utf-8
    Content-Length: 45

    {"id":"e42c77c6-06a4-4502-816c-d112c7142e6d"}

    ======================================
    403
    Content-Type: application/json; charset=utf-8
    Content-Length: 66

    {"code":1012,"message":"Authentication failed for '123456789abc'"}

    ======================================
    mysql: 1 tests ran in 5 ms, 0 skipped, 1 failed

Can you verify this in your environment? Kind regards, Maurits

**Comment by marionee** [comment]
I tried your test and the output is the same.
When I run the same test using the correct password the output is: "mysql: 1 tests ran in 174 ms, 0 skipped, 0 failed"

If I try this container I doesn't work and the api says to me "Authentication failed for '123456789abc'".

`docker run --rm --name phpcrudapi-temp \
--env PHP_CRUD_API_ADDRESS=myhostname \
--env PHP_CRUD_API_DATABASE=mydb \
--env PHP_CRUD_API_USERNAME=myuser \
--env PHP_CRUD_API_PASSWORD=mypassword \
--env PHP_CRUD_API_MIDDLEWARES=apiKeyAuth \
--env PHP_CRUD_API_API_KEY_AUTH_KEYS=123456789abc \
-p 8080:80 \
mevdschee/php-crud-api`

When the container is running, if I execute from another terminal "docker exec -it phpcrudapi-temp env"  I can see my PHP_CRUD_API_API_KEY_AUTH_KEYS=123456789abc

**Comment by mevdschee** [comment]
The release on Dockerhub was one month old, I've just updated it to v2.14.4. Does that make a difference?

**Comment by marionee** [comment]
I pulled down the new image and tested again, but the behavior is the same.

**Comment by mevdschee** [comment]
>I tried your test and the output is the same.

That is good.

> When I run the same test using the correct password the output is: "mysql: 1 tests ran in 174 ms, 0 skipped, 0 failed"

As expected.

>If I try this container I doesn't work and the api says to me "Authentication failed for '123456789abc'".

I have found the bug in the software: the middleware values have no default values, requiring you to specify them before you can override them with an environment variable. I will adjust the code to make your scenario work.

**Comment by mevdschee** [comment]
This has been released in v2.14.5

**Comment by mevdschee** [comment]
DockerHub has been updated with this release

**Comment by marionee** [comment]
Thank you @mevdschee, now it works!

**Comment by mevdschee** [comment]
Thank you @marionee for your help reproducing the issue. Enjoy the software!
