### ISSUE TITLE
Update calls (PUT) on tables that have more then one PK

### ISSUE THREAD

**Issue by tkauffman1** [mevdschee/php-crud-api#851]
I didn't see much documentation on how to update records on a table with more then one PK. 

In a specific example I am trying to update a row on a table with the following Primary Keys:
StoreID
SourceID
DMSID

I need to update based on DMSID

/api.php/records/{tableName}/1

got this error:
`{
    "code": 9999,
    "message": "Call to a member function getName() on null"
}`

I've tried filtering the PUT request : 

/api.php/records/{tableName}/1?filter=DMSID,eq,1
/api.php/records/{tableName}?filter=DMSID,eq,1

Same error as above.

I made a modification on line 3994 in api.php to suit our specific needs (We only need to respect DMSID)

`$columnNames = $reflection->getTablePrimaryKeys($name);
                if (count($columnNames) == 1) {
                    $columnName = $columnNames[0];
                } /*else if (in_array('DMSID', $columnNames)) {   
                    $columnName = 'DMSID';
                }*/`
                
Reading through some of the URL params I see 'PK' as an option. It would be nice if we can denote the PK field to use in these calls vs relying primarily on the Schema. Example:

PUT / GET  - `/API/{TableName}/1?pk=DMSID`                

Is this a feature that already exists or should I customize this solution a bit to suit our needs?

**Comment by tkauffman1** [comment]
For our specific requirements I added a quick function so we can pass in a URL Parameter to specify which PK field to use in the select single/ update / delete calls. I'm sure I'll have to expand on it but for now I have it working as needed.

`        public function getPkField(ReflectedTable $table, ?String $pkFieldName)
        {
            $pkColumn;
            if($pkFieldName != NULL){
                $pkColumn = $table->getColumn($pkFieldName);
                if(is_null($pkColumn)){
                    throw new \Exception('pkField parameter supplied is not a valid column on this table.');
                }
            } else {
                $pkColumn = $table->getPk();
                if(is_null($pkColumn)){
                    throw new \Exception('pkField parameter is required to interact with a single record on this table.');
                }
            }
            return $pkColumn;
        }`

**Comment by mevdschee** [comment]
Thank you for creating this issue. Great workaround! I'm happy you got it working (for your use-case). 

>I didn't see much documentation on how to update records on a table with more then one PK.

Tables with composite PK are not supported, see:

> Composite primary and composite foreign keys are not supported

source: https://github.com/mevdschee/php-crud-api/blob/main/README.md#limitations

I expect you will run into more issues and know that I won't support those. But.. feel free to fork, no hard feelings :-)
