### ISSUE TITLE
[DbAuth] Two cookies in response after login with empty headers.

### ISSUE THREAD

**Issue by maheini** [mevdschee/php-crud-api#853]
## Problem
I tried to log in with my App, using DbAuth middleware. I noticed that after first login (with empty headers) api.php is returning following set-cookie header:

> `set-cookie: MYSESSIONNAME=pkca4uass6qtovsdglch8okunm; path=/,MYSESSIONNAME=atp5t1o3qdn0g6mt125tdekifs; path=/,`

This isn't a problem on the browser as they are just using the second (valid) cookie. But on applications which might only fetch the first cookie, the second one is ignored, resulting into failed authentication on the next request.

## Possible solution
As a workaround, I put a fake/invalid cookie inside my login headers. This bypasses this check inside DbAuthMiddleware:

```
check Inside DbAuthMiddleware::process

if (!headers_sent()) {
  session_regenerate_id(true);  
}
```

## Questions
-Why is this check necessary?
-Is it possible to prevent this first cookie? (The second cookie is the valid one after login)

## Environment
I only noticed this behaviour on a Apache server (XAMPP). It's working perfect on Litespeed, and VScode PHP Server.
-Api v.2.13.3
-Apache Server

**Comment by mevdschee** [comment]
As a security measure the session id needs to be regenerated after the security level changes (login/logout). This is common practice and this is what I think you are seeing. It seems to me that this is a feature and not a bug.

**Comment by maheini** [comment]
@mevdschee I didn't got two responses with litespeed and vscode php server, only with apache. And I was requesting within a flutter project, so there might be a problem inside those two (or mis-configuration as you mentioned). Thanks for the hint.
