### ISSUE TITLE
How to use the Reconnect Middleware dynamically. 

### ISSUE THREAD

**Issue by 3257** [mevdschee/php-crud-api#854]
So, this is my case:

- I am seeding a database service, right, but it has multiple databases in it - say database A(table with login credentials are here), database B (tables with data), and database C(tables with data)
- I get that the easiest is to use a separate `api.php` file with each database and get an API running in that way - that looks like not the optimal solution though

- Then I saw the reconnect middleware, and I played with the base case scenario you have in the `README`, but all I can make it do is just have the reconnect middleware execute rightaway when I make a request when I test locally. 

This is my config:

```php
$config = new Config([
    'driver' => 'mysql',
    'address' => 'database',
    'port' => '3306',
    'middlewares' => 'cors, reconnect',
    'username' => 'root',
    'password' => 'password',
    'database' => 'dbA',
    'reconnect.databaseHandler' => function () {
        return 'dbB';
    },
    'debug' => true
]);
```

But all I get is connecting to dbB right away, so, there's no point in declaring `'database' => 'dbA',`, we always end up with `dbB`as the database to be used. 

----

So, the question, what is the best way to have the reconnect middleware get called and executed dynamically at runtime?
I want to use `dbA` to log in, and then I want to switch to `dbB` for all other requests.

**Comment by mevdschee** [comment]
You should detect the user int the session in the databasehandler and return dbB when there is a valid session (logged in):

    'reconnect.databaseHandler' => function () {
        if (isset($_SESSION['user'])) {
          return 'dbB';
        }
        return 'dbA';
    },

returns dbB when there is a user in the session.

**Comment by 3257** [comment]
Thanks. 

That makes sense! I went for it initially but I did not see it set when I was debugging - my debugging set-up is a bit flaky. 


So, to summarise - it is the `$_SESSION` property the we would rely on for any runtime-dependent decisions, right?

Is there any other way to make the `reconnect` middleware handlers get called - using custom controllers for example?

**Comment by mevdschee** [comment]
>Is there any other way to make the reconnect middleware handlers get called - using custom controllers for example? 

No, it is being called before the database connection is made.

**Comment by 3257** [comment]
Got it, thank you!
