### ISSUE TITLE
jwt authentication, for some tables only?

### ISSUE THREAD

**Issue by niyonx** [mevdschee/php-crud-api#859]
I have jwt authentication, can I bypass the authentication for some tables only?

I need some tables to be publicly accessible

**Comment by mevdschee** [comment]
Yes, this is possible: set the 'jwtAuth.mode' to 'optional' and test for the session claims in the 'authorization.tableHandler'.

**Comment by niyonx** [comment]
It seems to work fine! Except when I do a POST on the table I am bypassing, it is behaving like a GET. Do you know how I can resolve it ?

**Comment by mevdschee** [comment]
Look at the value in the $operation parameter of the tableHandler..

**Comment by niyonx** [comment]
Thanks for responding so quickly!

Yes exactly, instead of create it seems to be doing list only.

In the authorization tablehandler, it should return either true (return the data) or false (do not return data) right?

If the operation is create and I return true, is it still supposed to do the create operation?

**Comment by mevdschee** [comment]
>Yes exactly, instead of create it seems to be doing list only.

That is very unexpected, are you sure?

>If the operation is create and I return true, is it still supposed to do the create operation?

Yes indeed.

**Comment by mevdschee** [comment]
any update?

**Comment by niyonx** [comment]
It is good! False alert on my side!
