### ISSUE TITLE
Any thoughts on recaptcha/2fa support?

### ISSUE THREAD

**Issue by mingsai** [mevdschee/php-crud-api#860]
Hi and thank you again for this outstanding work. I want to implement this lib and I’m concerned about the countless bots trying to register and I'd like to further secure the library using either 2fa that uses custom questions or math problems to allow me to verify human authorship of posts and requests. 

SMS authentication and things like Google recaptcha and even Google Authenticator seem to me to be reasonable options. I’m looking to avoid additional costs and tie-ins to external services if possible (for performance reasons and security). 

I’d like to ensure the safety of the register and login endpoints using 2fa, via email, text sms or, q&a. 

Any specific recommendations? Thank your for your time and energy. 

TC

**Comment by mevdschee** [comment]
>I’d like to ensure the safety of the register and login endpoints using 2fa, via email, text sms or, q&a.

That sounds pretty off-topic to me :-) Thank you for closing the ticket.

>Any specific recommendations?

Sure.. I feel it is best to measure the time taken to fill the form and the age of the session (in seconds). I measure this using a "pixel" on the form.

Kind regards, Maurits
