### ISSUE TITLE
PUT with params

### ISSUE THREAD

**Issue by sam-claire** [mevdschee/php-crud-api#861]
Hi,

Is this possible?
let response = await axios.put(this.endpoint + '/members?filter=Role,eq,abc/1', xpayload, config);

Thanks

**Comment by mevdschee** [comment]
>Is this possible?

Did you try the request? What was the response? What you expected? If not.. why not?

Kind regards, Maurits.

**Comment by sam-claire** [comment]
yes, 

1000 | 404 Not found | Route not found

**Comment by mevdschee** [comment]
Your `this.endpoint` should end in '/records', is that the case?

**Comment by mevdschee** [comment]
Also, what did you try to solve the problem? What does the request look like? Also please share your table definition (table create statement).

**Comment by sam-claire** [comment]
yes var this.endpoint  = url +'/records'

**Comment by mevdschee** [comment]
You are not answering the questions. I can't help you.
