### ISSUE TITLE
can you please provide a curl PATCH example to increment a field?

### ISSUE THREAD

**Issue by golemus** [mevdschee/php-crud-api#865]
Hello,
I am struggling with syntax to increment a value
testing something like
```
curl -vv -X PATCH "https://myserver/api.php/records/votes/art01"\
     -H 'Content-Type: application/json'\
     -H 'Accept: application/json'\
     -d '{"field": "votes", "operator": "+", "operand": 1}'

```
gives a http 200 but does not work.
could you please provide an example?

**Comment by mevdschee** [comment]
> could you please provide an example?

https://github.com/mevdschee/php-crud-api/blob/main/tests/functional/001_records/069_increment_event_visitors.log

**Comment by golemus** [comment]
Thanks exactly what I was looking for

**Comment by mevdschee** [comment]
I'm glad it helped you. If you have other questions, please open a new issue. Enjoy the software, kind regards, Maurits
