### ISSUE TITLE
Getting googleapi public keys

### ISSUE THREAD

**Issue by niyonx** [mevdschee/php-crud-api#867]
What is the best practice to get the google apis public keys? (https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com)

I am now dynamically getting the public keys but notice that my request with a jwt will often return invalid since the public keys changed.

Should I append to the $secrets variable? Or get the keys only once a day?

I had hard coded the secrets before but I believe the public keys become valid after some time.

**Comment by mevdschee** [comment]
Try this from @[leossmith](https://github.com/leossmith):

![code](https://user-images.githubusercontent.com/4300876/101823704-d9e58280-3b33-11eb-8f0e-54e993c62133.png)

I hope it helps..

**Comment by niyonx** [comment]
I was using it before but it was causing me some errors. I now have a cron job to retrieve the keys regularly. 

Thanks for the help as always!
