### ISSUE TITLE
REST API for FirebirdSql

### ISSUE THREAD

**Issue by kalvick** [mevdschee/php-crud-api#87]
Hi
Interested in extending php-crud-api's REST Api to support FirebirdSql database 2.5.x & 3.x (http://www.firebirdsql.org)...

Please advise..

Best Regards
Krishna
KALViCK Technologies

**Comment by mevdschee** [comment]
Just convert/stick to postgresql if you have the choice. At this moment I will not support firebird since it is hardly used. Feel free to create a fork that does.
