### ISSUE TITLE
Possible to disable PUT, POST, DELETE?

### ISSUE THREAD

**Issue by verhulstd** [mevdschee/php-crud-api#871]
Hello Maurits,
Is it possible to only allow GET requests?
Greetings
David

**Comment by verhulstd** [comment]
'authorization.tableHandler' => function ($operation, $tableName) {
        return ($operation == "list" || $operation == "read");
    },

**Comment by verhulstd** [comment]
This works but the openapi does not get updated accordingly... Any tips?

**Comment by mevdschee** [comment]
It should be disabled, see:

https://github.com/mevdschee/php-crud-api/blob/1000fb1ea0c710b2aa1bd74182ae53066b47dd8a/src/Tqdev/PhpCrudApi/OpenApi/OpenApiRecordsBuilder.php#L129

Can you help me reproduce the issue?

**Comment by mevdschee** [comment]
You should use:

    'authorization.tableHandler' => function ($operation, $tableName) {
        return ($operation == "list" || $operation == "read" || $operation == "document");
    },

The operation "document" is required for openapi listing.

I hope this helps, enjoy the software! Kind regards, Maurits
