### ISSUE TITLE
API doesn't work after changing filename to index.php

### ISSUE THREAD

**Issue by T3chnoMaciej** [mevdschee/php-crud-api#873]
Hi, 
I've been using this API for a long time and it works great. I wanted to move it to subdomain api.example.com and thus change it's filename to index.php . Even tough my configuration is fine with the new adress, it stopped working. Is this solution even possible?

Thanks in advance,
Maciej

**Comment by mevdschee** [comment]
Hi Maciej,

Thank you for creating this issue.

>Even tough my configuration is fine with the new adress, it stopped working. Is this solution even possible?

Yes it is possible. What is your platform and what is your configuration? Do you use a rewrite (as suggested in #674)?

Kind regards, Maurits

**Comment by T3chnoMaciej** [comment]
Hi!
My configuration is Apache on Debian 10. I didn't use rewrite. I will check it and let you know if it helped. Thanks for the reply.

Maciej

**Comment by T3chnoMaciej** [comment]
HI,
I belive your solution would work, but Apache just gives me "Found , moved to link" insted of a redirect. However this is not related to your api, so I'm closing the thread. Thanks for the solution.

Maciej

**Comment by mevdschee** [comment]
>Apache just gives me "Found , moved to link" instead of a redirect

Rewrites don't give 301/302 redirect results unless you configure them to. You should be able to rewrite without a redirect.

**Comment by mevdschee** [comment]
This is the htaccess you should use:

https://github.com/mevdschee/php-crud-api/blob/main/.htaccess
