### ISSUE TITLE
error code 9999

### ISSUE THREAD

**Issue by niyonx** [mevdschee/php-crud-api#875]
{ "code": 9999, "message": "Tqdev\PhpCrudApi\Record\Condition\AndCondition::fromArray(): Return value must be of type Tqdev\PhpCrudApi\Record\Condition\Condition, Tqdev\PhpCrudApi\Record\Condition\NoCondition returned" }

Nothing had change in the code but now every GET throws this error

**Comment by niyonx** [comment]
I had changed the database too, it does not seem to be database specific issue.

**Comment by mevdschee** [comment]
This is not how you should report an issue.

**Comment by mevdschee** [comment]
You need to show the table create sql and the exact http request you are doing to help other people understand what you are doing.
