### ISSUE TITLE
Feature Request: Wildcard Search

### ISSUE THREAD

**Issue by nkappler** [mevdschee/php-crud-api#881]
Hi there, I am working on the react-admin integration / dataprovider (https://github.com/mevdschee/ra-data-treeql) again, but this issue better fits here I think.

The situation:
When you use a [ReferenceInput](https://marmelab.com/react-admin/ReferenceInput.html) from react-admin (basically an autocomplete combobox which queries the database for valid inputs)
the input will fire a getList API call with a single parameter: `q` (query). this contains the search string.

Currently, ra-data-treeql creates this request out of this: 
`...api.php/records/customers?order=id,DESC&page=1,25&filter=q,eq,Adam Riese`

Obviously, the column `q` doesn't exist on the customers table so the API throws:
```json
{
  "code": 9999,
  "message": "Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedTable::getColumn(): Return value must be of type Tqdev\\PhpCrudApi\\Column\\Reflection\\ReflectedColumn, null returned"
}
```

While I could write some middleware (I will probably have to do it anyway), which searches in the correct columns, this is not a very generic solution and it would be very nice to have the possibility to search in all columns without specifying them. 

The API throwing could be a bug (maybe one the dataprovider needs to handle, but I digress...)

> not very important for this issue, but the customer table has the columns `firstname` and `secondname` which makes this more complicated.

**Comment by mevdschee** [comment]
Hi Nikolaj, I agree that a middleware could be used to implement the translation from `q=abc` to a matching complex filter expression (with all fields and 'or'). I'm looking forward to your "SearchMiddleware". I'm willing to include it if you send me a PR. Kind regards, Maurits

**Comment by nkappler** [comment]
Hi Maurits, I am not an expert on php, are there any examples or resources I could use to get started?

**Comment by mevdschee** [comment]
Released in v2.14.4

**Comment by mevdschee** [comment]
docs: https://github.com/mevdschee/php-crud-api#search-all-text-fields

**Comment by mevdschee** [comment]
test: https://github.com/mevdschee/php-crud-api/blob/main/tests/functional/001_records/094_search_posts.log

**Comment by nkappler** [comment]
Thanks a lot 🥳
Going to try this out right away...
