### ISSUE TITLE
Tqdev\\PhpCrudApi\\Config not found

### ISSUE THREAD

**Issue by niyonx** [mevdschee/php-crud-api#882]
Hi,

I got a very weird error, the API was working well for weeks, but then one time I see the API shows some kind of server error.

I checked the apache logs and find 

```
PHP Fatal error:  Uncaught Error: Class "Tqdev\\PhpCrudApi\\Config" not found in api.php:12140

\nStack trace:\n#0 {main}\n  thrown in api.php on line 12140
```

It's very weird that the error throws on the new Config, would you know the cause of the issue? I just did an apache restart and it was fine then.

Thank you!

**Comment by mevdschee** [comment]
I have no clue, but my guess would be that somehow your opcache got corrupted. I'm glad you fixed it.

**Comment by arladmin** [comment]
Hi @mevdschee ,

I'm seeing the same issue in a fresh Wordpress install:

```
PHP Fatal error: Uncaught Error: Class "Tqdev\\PhpCrudApi\\Config" not found in /public/api/api.php
```

**Comment by mevdschee** [comment]
@arladmin Thank you for reporting this issue. It is good to know that you also experience this. Unfortunately, without reproduction steps and/or more research from your side, there is little I can do. Kind regards, Maurits

**Comment by arladmin** [comment]
@mevdschee Thanks for your prompt response!

I could provide you the required details if you let me know what i should share, to debug this?

**Comment by arladmin** [comment]
Basically, i did a 'single-file' install:
I added the `api.php` and `api.include.php` to the `public/api/` folder of my Wordpress site.
And then i added my database credentials in the `api.php` file.

**Comment by mevdschee** [comment]
Okay, does restarting Apache change anything (as it did for @niyonx)? In that case it has something to do with the JIT/opcache. If not then you could search for the Config class and insert a die in the file to see whether or not it is loaded. You say you experience this in Wordpress, did you do an integration or do you use an extension/plugin? It could be that the Config class has a syntax error and is not loaded at all.

**Comment by mevdschee** [comment]
>I added the api.php and api.include.php

That is not how it is supposed to work. You either use `api.php` and edit the Config class in the bottom of the file. Or you include `api.include.php` and define the config class yourself. You don't need to use both.

**Comment by arladmin** [comment]
- restarting Apache didn't help
- where to search for the Config class?
- have now removed the `api.include.php` file and restarted : no effect
- i do have other plugins installed in the Wordpress site, but would they have any impact on this?

**Comment by arladmin** [comment]
Tried again, with a new setup.
Created a LAMP stack and added only the `api.php` file to the `public` folder.
Still doesn't work.

**Comment by arladmin** [comment]
Does the api.php need to be on a 'writeable' filesystem?

**Comment by mevdschee** [comment]
> Does the api.php need to be on a 'writeable' filesystem?

Sure, that is expected, but you can disable the cache (see readme).

**Comment by arladmin** [comment]
> > Does the api.php need to be on a 'writeable' filesystem?
> 
> Sure, that is expected, but you can disable the cache (see readme).
> 
> If you email me your config, then I'll check it for problems.

By config, do you mean just the modified `api.php` file, or something else as well?

**Comment by mevdschee** [comment]
Only the last "Config" class from the api.php.. the part that you modified.

**Comment by arladmin** [comment]
@mevdschee 
Sure, here's the part:

```

namespace Tqdev\PhpCrudApi {

    use Tqdev\PhpCrudApi\Api;
    use Tqdev\PhpCrudApi\Config;
    use Tqdev\PhpCrudApi\RequestFactory;
    use Tqdev\PhpCrudApi\ResponseUtils;

    $config = new Config([
        'driver' => 'mysql',
        'address' => '172.18.30.1',
        'port' => '3306',
        'username' => '5023f6a54fe42c64',
        'password' => '6b7f11d039f29fb400284fbc610f7ec38b0a6cd2f6cfe043',
        'database' => '5023f6a54fe42c64',
        'debug' => true,
        'middlewares' => 'json'
    ]);

    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    ResponseUtils::output($response);
}
```

**Comment by arladmin** [comment]
> @mevdschee Sure, here's the part:
> 
> ```
> 
> namespace Tqdev\PhpCrudApi {
> 
>     use Tqdev\PhpCrudApi\Api;
>     use Tqdev\PhpCrudApi\Config;
>     use Tqdev\PhpCrudApi\RequestFactory;
>     use Tqdev\PhpCrudApi\ResponseUtils;
> 
>     $config = new Config([
>         'driver' => 'mysql',
>         'address' => '172.18.30.1',
>         'port' => '3306',
>         'username' => '5023f6a54fe42c64',
>         'password' => '6b7f11d039f29fb400284fbc610f7ec38b0a6cd2f6cfe043',
>         'database' => '5023f6a54fe42c64',
>         'debug' => true,
>         'middlewares' => 'json'
>     ]);
> 
>     $request = RequestFactory::fromGlobals();
>     $api = new Api($config);
>     $response = $api->handle($request);
>     ResponseUtils::output($response);
> }
> ```

@mevdschee 
Does this help?

**Comment by mevdschee** [comment]
> Does this help?

I checked that snippet for errors, but  I didn't find any.

**Comment by arladmin** [comment]
> > Does this help?
> 
> I checked that snippet for errors, but I didn't find any.

How to debug this then?

**Comment by arladmin** [comment]
> > Does this help?
> 
> I checked that snippet for errors, but I didn't find any.

There doesn't seem to be any issue on the webserver side. All other files are easily accessible.
It's only the `api.php` file that's not working.

Only this error: 
`PHP Fatal error: Uncaught Error: Class "Tqdev\PhpCrudApi\Config" not found`

**Comment by arladmin** [comment]
@mevdschee 

Confirmed. 
There's indeed something wrong with the code in the latest `api.php` file.

I just used an older copy copy of the `api.php` file that i was using in another server. That worked fine!
Whereas, the latest `api.php` doesn't work.

I've included the file that's working for me, here:
https://www.diffchecker.com/jCkvkPO7/

^ the one on the left is the old version (which is working) while the one on the right is the latest version (which doesn't work).

**Comment by mevdschee** [comment]
This may be related to your PHP version. Can you report which PHP version you use?

**Comment by arladmin** [comment]
> This may be related to your PHP version. Can you report which PHP version you use?

8.2

**Comment by arladmin** [comment]
> This may be related to your PHP version. Can you report which PHP version you use?

Doesn't work for PHP v8.2, v8.1, v7.2 either

**Comment by mevdschee** [comment]
Are you on Windows or on Linux? Did you install the required PHP extensions (such as mbstring)?

**Comment by mevdschee** [comment]
>Doesn't work for PHP v8.2, v8.1, v7.2 either

There are (Docker) test runners for all those versions. All tests pass.

**Comment by mevdschee** [comment]
>i do have other plugins installed in the Wordpress site, but would they have any impact on this?

That does not seem very likely to me.

**Comment by arladmin** [comment]
> Are you on Windows or on Linux? Did you install the required PHP extensions (such as mbstring)?

Linux. Docker based, LAMP stack (in Cloudron).

Didn't find any instructions for installing any 'required' extensions, anywhere. Where are they? And what all are the prerequisites?

**Comment by mevdschee** [comment]
>Linux

Windows is not tested properly, but Linux is, so that rules out a source of error.

>And what all are the prerequisites?

You can check out the docker folder in the repository to see all installation instructions in various docker based environments.

**Comment by mevdschee** [comment]
I would love to help, but I can't reproduce the error. Can you help us reproduce the error? It would really help if you would share a repository in which the error occurs.
