### ISSUE TITLE
Help with config error

### ISSUE THREAD

**Issue by heliang219** [mevdschee/php-crud-api#883]
<img width="523" alt="截屏2022-05-30 17 49 51" src="https://user-images.githubusercontent.com/795426/170967121-512f5ae6-1f6d-4893-8591-85d154f37676.png">
<img width="979" alt="截屏2022-05-30 17 50 34" src="https://user-images.githubusercontent.com/795426/170967181-840d2e6e-3ce9-44e9-8dd8-09c7c633c4c5.png">
<img width="677" alt="截屏2022-05-30 17 50 51" src="https://user-images.githubusercontent.com/795426/170967222-56d118e9-0636-4606-a067-3053ca2a4167.png">
<img width="683" alt="截屏2022-05-30 17 53 10" src="https://user-images.githubusercontent.com/795426/170967411-1f0904e6-7048-4352-b7e3-a341019f9935.png">

**Comment by mevdschee** [comment]
It can't connect. Check the http response headers in the network tab of the web developer tools of your browser for more info.

**Comment by heliang219** [comment]
> It can't connect. Check the http response headers in the network tab of the web developer tools of your browser for more info.

Thanks,I wil check.
Bye the way, the config I wrote in these files are correct?

**Comment by mevdschee** [comment]
>the config I wrote in these files are correct?

I think not. I think you need to redirect one machine to the other in PHP_CRUD_API_ADDRESS env parameter, see:

https://github.com/mevdschee/php-crud-api/blob/main/docker-compose.yml

**Comment by heliang219** [comment]
![截屏2022-05-30 23 34 43](https://user-images.githubusercontent.com/795426/171024631-8db432de-69bb-4d4d-9dcd-b3cab3e47218.png)
![截屏2022-05-30 23 34 57](https://user-images.githubusercontent.com/795426/171024643-c6c821b8-5669-43ef-b3d9-15d235743a54.png)
![截屏2022-05-30 23 34 25](https://user-images.githubusercontent.com/795426/171024654-12d338aa-7997-460e-812a-fb704a9a6d5d.png)

still wrong!
which step  I make  a mistake?

**Comment by mevdschee** [comment]
Is the instance navicat connects to the same as the database container in the docker compose? I'm guessing it is not.

**Comment by heliang219** [comment]
<img width="734" alt="截屏2022-05-31 12 27 07" src="https://user-images.githubusercontent.com/795426/171093154-d66d906b-07d6-48ed-a34d-e277213da3f7.png">
<img width="573" alt="截屏2022-05-31 12 27 23" src="https://user-images.githubusercontent.com/795426/171093180-54fce842-d43e-4334-b71b-a548e24027d0.png">
<img width="556" alt="截屏2022-05-31 12 28 50" src="https://user-images.githubusercontent.com/795426/171093193-36becca2-c326-4074-bace-073f86f7b6b5.png">
<img width="649" alt="截屏2022-05-31 12 29 07" src="https://user-images.githubusercontent.com/795426/171093220-37d28c56-a024-4a15-b7c4-013867ad8f5b.png">
<img width="506" alt="截屏2022-05-31 12 29 58" src="https://user-images.githubusercontent.com/795426/171093235-da0b5622-b54b-4a9d-b15e-53bb02c2b1fe.png">

Thanks for your reminding，it works finally.
Hope these pictures can help the others not make a mistake like me!

**Comment by mevdschee** [comment]
Thank you for sharing your success, this may indeed help others. Enjoy the software!
