### ISSUE TITLE
Could you please add more services to custom middleware?

### ISSUE THREAD

**Issue by hopeter1018** [mevdschee/php-crud-api#886]
Thanks for the great project!

First of all, Sorry for my English.

I heavily use the CustomizationMiddleware and I would like to do some many things in the my middleware, including DB crud and instant response. I suggest to pass following services to beforeHandler and afterHandler:
- reflectionService
- recordService
- GenericDB
- responder

For the DB actions, I used to re-construct another ReflectionService and RecordService in some version before. But those re-constructed service seems stopped working in the recent version. I am not sure is that related to the new "mapping" as I got "Incorrect table name '' in GenericDB.php".

**Comment by mevdschee** [comment]
>I am not sure is that related to the new "mapping" as I got "Incorrect table name '' in GenericDB.php".

That could very well be. Can you share the code to re-construct the ReflectionService and RecordService? And ideally the line that gives the error including the exact error?

Kind regards, 

Maurits

**Comment by hopeter1018** [comment]
Thanks for the Quick Response.

It always return false when I called the recordService with 

`ApiEx::reflection()->hasTable('just_a_table_name');`

`class ApiEx
{
    protected static $db = null;
    protected static $reflection = null;
    protected static $recordService = null;

    public static function instance()
    {
        if (null === static::$db) {
            static::$db = new GenericDB(
                getenv('MYSQL_DRIVER'),
                getenv('MYSQL_ADDRESS'),
                getenv('MYSQL_PORT'),
                getenv('MYSQL_DATABASE'),
                "",
                [],
                [],
                getenv('MYSQL_USERNAME'),
                getenv('MYSQL_PASSWORD')
            );
        }

        return static::$db;
    }

    public static function reflection()
    {
        if (null === static::$reflection) {
            global $config;

            $prefix = sprintf('phpcrudapi-%s-', substr(md5(__DIR__.'/../vendor/mevdschee/php-crud-api/src/Tqdev/PhpCrudApi/Api.php'), 0, 8));
            $cache = CacheFactory::create($config->getCacheType(), $prefix, $config->getCachePath());
            static::$reflection = new ReflectionService(static::instance(), $cache, $config->getCacheTime());
        }

        return static::$reflection;
    }

    public static function recordService()
    {
        if (null === static::$recordService) {
            static::$recordService = new RecordService(static::instance(), static::reflection());
        }

        return static::$recordService;
    }
}`

**Comment by mevdschee** [comment]
static::$db = new GenericDB(
                getenv('MYSQL_DRIVER'),
                getenv('MYSQL_ADDRESS'),
                getenv('MYSQL_PORT'),
                getenv('MYSQL_DATABASE'),
                "all", // <= difference 
                [],
                [],
                getenv('MYSQL_USERNAME'),
                getenv('MYSQL_PASSWORD')
            );

**Comment by hopeter1018** [comment]
Many thanks! Let me test the modification!

**Comment by hopeter1018** [comment]
It's working! Thanks for the prompt reply!
