### ISSUE TITLE
Using "authorization.tableHandler" gives 500 internal server error

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#887]
same here, using "authorization.tableHandler" gives 500 internal server error
<img width="849" alt="Screenshot 2022-07-08 230147" src="https://user-images.githubusercontent.com/23131234/178041948-cece07de-7e9e-4bd4-bcbe-27721af91a37.png">

_Originally posted by @sk679558 in https://github.com/mevdschee/php-crud-api/issues/885#issuecomment-1178955348_

**Comment by mevdschee** [comment]
@sk679558 Can you post that line (11565)?

**Comment by sk679558** [comment]
<img width="938" alt="Screenshot 2022-07-09 133018" src="https://user-images.githubusercontent.com/23131234/178097281-8ced903b-2efc-4c4d-be32-2dd36dcb0cbe.png">
removing 'authorization.tablehandler' line does not throw any error

**Comment by mevdschee** [comment]
You can't make those a private field `$values` and assign default values. Assign values in another statement.

    private $values;
    
    public function __construct() {
        $this->values = [...]; // <= your code here
    }

This has nothing to do with this project AFAIK.

**Comment by mevdschee** [comment]
I guess that solves this issue. Feel free to open another issue if you have any further questions.
