### ISSUE TITLE
Cors middleware not working for cross site requests

### ISSUE THREAD

**Issue by anoteng** [mevdschee/php-crud-api#889]
Hi, thank you for an awesome piece of software!
I'm having problems getting the cors middleware to work. According to documentation leaving it with default settings should work just fine, but I'm nevertheless having issues.
Adding domains to configuration key cors.allowedOrigins seems to have no effect, however I'm unsure about the syntax with multiple domains, i tried with comma separated. Access-control-allow-credentials header is also missing.
I can work around these problems using a broweser extention to add headers, but even with the headers added the preflight fails with "Access to fetch at '<api endpoint>' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status."

To me it looks like the whole cors middleware is not being invoked.

The API works as expected if requests originate from the same site, which is just fine for production purposes, but for development it would be great not having to update and build code on the web server for each change (frontend is Vue.JS)

I sadly don't have access to the apache logs, as the web server used is being run by my university.

Relevant parts of api.php:

        namespace Tqdev\PhpCrudApi {
        
            use Tqdev\PhpCrudApi\Api;
            use Tqdev\PhpCrudApi\Config;
            use Tqdev\PhpCrudApi\RequestFactory;
            use Tqdev\PhpCrudApi\ResponseUtils;
        
            require_once("config.php");
            $config = new Config([
                'driver' => $driver,
                'address' => $address,
                'port' => $port,
                'username' => $username,
                'password' => $password,
                'database' => $database,
                'debug' => $debug,
                'middlewares' => 'cors,apiKeyDbAuth,authorization',
                'apiKeyDbAuth.usersTable' => 'users',
                'apiKeyDbAuth.apiKeyColumn' => 'login_token',
                'cors.allowedOrigins' => 'http://localhost:8080,<webserver>'
            ]);

**Comment by mevdschee** [comment]
>Hi, thank you for an awesome piece of software!

Thank you for your kind words, I appreciate that.

>I sadly don't have access to the apache logs, as the web server used is being run by my university.

The preflight request may be an "options" request that never reaches PHP. 

Can you post a minimal example that doesn't work, so that I can try to reproduce? Please add the SQL create statement and the JS/CSS and HTML and an explanation of how to install/run the code. Kind regards, Maurits

**Comment by anoteng** [comment]
Hi, i only use the single file, but I added the var_dump to the corresponding line, and indeed it looks like origin is empty.

Running the request from the web server, response headers:

    HTTP/1.1 200 OK
    Date: Thu, 21 Jul 2022 06:10:38 GMT
    Server: Apache/2.4.52 (Ubuntu)
    Strict-Transport-Security: max-age=63072000
    Content-Length: 102
    Keep-Alive: timeout=5, max=99
    Connection: Keep-Alive
    Content-Type: application/json; charset=utf-8

Response:

    array(2) {
      [0]=>
      string(0) ""
      [1]=>
      string(21) "http://localhost:8080"
    }
    {"db":257,"cache":15}

Running the request from localhost WITH plugin adding cors header running in browser:
![bilde](https://user-images.githubusercontent.com/1189986/180142913-ed1a6e07-b7be-4eb7-be85-f658365dbb2d.png)

Running the request from localhost WITHOUT cors plugin running in browser:
![bilde](https://user-images.githubusercontent.com/1189986/180143214-ba8869c6-d447-4cd0-b2ce-49cad05ab7a7.png)

Network tab, request from localhost without plugin:
![bilde](https://user-images.githubusercontent.com/1189986/180143512-683fcaae-0654-4cc6-92f5-7933488f7de3.png)

Headers the top one of the two failing requests:
![bilde](https://user-images.githubusercontent.com/1189986/180143884-ca030559-9b48-4b54-8418-e3e0f33296ba.png)

Second request:
![bilde](https://user-images.githubusercontent.com/1189986/180144352-f415eae5-f18d-4b00-a82f-aed15da7e07b.png)

As you can see the requests to my own php-files work just fine. I'm guessing the 401 unauthorized is caused by the X-API-Key header not being inserted due to the missing cors headers in the response?

The JS-code making the request:

    checkApiKey(key) {
    
            fetch(baseURL + 'api.php/status/ping', {
                credentials: "include",
                headers: {
                    'X-API-Key': key,
                }
            })
                .then(response => response.json())
                .then(data => console.log(data))
        },

**Comment by anoteng** [comment]
Minimal working example atttached. Base URL must be filled in. I could send you the URL by email if you'd like to test against my API, but I'd rather not post it publicly.
github won't let me attach HTML, so here's a paste. Copy and save as .html
https://pastebin.com/bgRFE8sY

**Comment by anoteng** [comment]
Switching from Chrome to Firefox i see that is possible to re-send a request and ignore cors errors, doing so I get this response:

    array(2) {
      [0]=>
      string(21) "http://localhost:8080"
      [1]=>
      string(21) "http://localhost:8080"
    }
    {"db":241,"cache":10}

Headers also look good:

    HTTP/1.1 200 OK
    Date: Thu, 21 Jul 2022 09:44:59 GMT
    Server: Apache/2.4.52 (Ubuntu)
    Strict-Transport-Security: max-age=63072000
    Content-Length: 124
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Origin: http://localhost:8080
    Keep-Alive: timeout=5, max=100
    Connection: Keep-Alive
    Content-Type: application/json; charset=utf-8

Looks like it is only the preflights that are failing to add the origin headers, not the actual requests.

I'm starting to suspect the bug is in the apiKeyDbAuth, not in the cors middleware. Looks like the API is rejecting the preflight with a 401 due to missing API key. If i understand cors correctly any extra headers should not be present in the preflight, as the preflight is the browsers way of asking the server for permission to send these headers.

I'm not getting the errors while doing a same site request, as the browser will not do a preflight on same site requests, and thus include all headers in the first request.

**Comment by anoteng** [comment]
There's probably better ways to solve it, but for now the patch is a working workaround for me. I think the cors middleware is handeling the request correctly as it is, but the auth middleware is rejecting the request after cors is done, due to the missing auth header in the preflight request.

**Comment by mevdschee** [comment]
>There's probably better ways to solve it

Yes, the `X-API-Key` header is not allowed by the CorsMiddleware class as that header is not default included in the `Access-Control-Allow-Headers` response header. You can configure the CorsMiddleware class by specifying this in the config:

    'cors.allowHeaders' => 'Content-Type,X-XSRF-TOKEN,X-Authorization,X-API-Key',

I've just tested this and it solves your problem. I hope you understand what is going on here.

**Comment by anoteng** [comment]
I'll test it tomorrow. Should be added to the docs of the auth middleware though.

**Comment by anoteng** [comment]
I'm unable to test tonight, but i don't understand how that would work. The preflight doesn't contain that header, and the preflight is failing with 401 unauthorized. But, I'll give it a shot tomorrow.

**Comment by mevdschee** [comment]
>Should be added to the docs of the auth middleware though.

I feel your pain. CORS headers are a difficult concept to understand and can be frustrating to deal with. 

>The preflight doesn't contain that header, and the preflight is failing with 401 unauthorized. But, I'll give it a shot tomorrow.

I've tested this on Firefox with my localhost and my internet connected Apache server, reproducing your exact setup. The options request is not failing with a 401 unauthorized in my browser. Please test my solution.

I added the API key header to the defaults, so you helped to make the defaults better, thank you for that.

**Comment by mevdschee** [comment]
You may want to test whether or If your server does not answer OPTIONS requests, please do so by making a PHP file `options.php` containing

    <?php
    header('X-Debug-Options: test');

and request that PHP file by doing a CURL request from the command line:

    curl -i -X OPTIONS https://webserver/options.php

And see whether or not you get a result containing the header. My output:

    maurits@j5040:~$ curl -i -X OPTIONS 'https://webserver/options.php'
    HTTP/1.1 200 OK
    Date: Thu, 21 Jul 2022 18:24:18 GMT
    Server: Apache/2.4.38 (Debian)
    X-Debug-Options: test
    Content-Length: 0
    Content-Type: text/html; charset=UTF-8

Let me know what you have...

**Comment by anoteng** [comment]
Your much better fix worked just fine!
