### ISSUE TITLE
Error with include

### ISSUE THREAD

**Issue by khkassem** [mevdschee/php-crud-api#89]
Hi,

I am experiencing a problem trying to run the following url on the attached database :

api.php/sections?include=departments

I am getting the folowing error :

> {"sections":{"columns":["ID","NAME","DEPARTMENT_ID","PHONE_NUMBER","ROOM_NUMBER"],"records":[["1","sect 1","1","658","987"],["2","sect 2","2","657","698"]]},"mail_sent":{"relations":{"SECTION_ID":"sections.ID"},"columns":["DESC","DIRECTORATE_ID","ID","SENDING_DATE","DEPARTMENT_ID","SECTION_ID"],"records":[]},"departments":{"relations":{"ID":"mail_sent.DEPARTMENT_ID"}<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: departments in C:\devz\workspace\edlmsphp\src\main\webapp\php\lib\api.php on line <i>1395</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0038</td><td bgcolor='#eeeeec' align='right'>856704</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\devz\workspace\edlmsphp\src\main\webapp\php\lib\api.php' bgcolor='#eeeeec'>..\api.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0055</td><td bgcolor='#eeeeec' align='right'>872016</td><td bgcolor='#eeeeec'>PHP_CRUD_API->executeCommand(  )</td><td title='C:\devz\workspace\edlmsphp\src\main\webapp\php\lib\api.php' bgcolor='#eeeeec'>..\api.php<b>:</b>1934</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0085</td><td bgcolor='#eeeeec' align='right'>924056</td><td bgcolor='#eeeeec'>PHP_CRUD_API->listCommand(  )</td><td title='C:\devz\workspace\edlmsphp\src\main\webapp\php\lib\api.php' bgcolor='#eeeeec'>..\api.php<b>:</b>1912</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0086</td><td bgcolor='#eeeeec' align='right'>930064</td><td bgcolor='#eeeeec'>PHP_CRUD_API->listCommandInternal(  )</td><td title='C:\devz\workspace\edlmsphp\src\main\webapp\php\lib\api.php' bgcolor='#eeeeec'>..\api.php<b>:</b>1471</td></tr>
</table></font>
,"columns":["ID","NAME","DIRECTORATE_ID","EDL_ID","PHONE_NUMBER","ROOM_NUMBER"],"records":[["1","department 1","1","1","1236","321"],["2","depart 2","2","2","256","6987"]]}}

if I delete the MAIL_TO table, its working correctly?

[test.txt](https://github.com/mevdschee/php-crud-api/files/358922/test.txt)

**Comment by mevdschee** [comment]
Thank you for reporting this. Does the fix help?

**Comment by khkassem** [comment]
Thank you

The NOTICE disappeared but I am not getting what I want.

If I ran api.php/sections?include=departments&filter=id,eq,1 I get
```
{
  "sections": {
    "columns": [
      "ID",
      "NAME",
      "DEPARTMENT_ID",
      "PHONE_NUMBER",
      "ROOM_NUMBER"
    ],
    "records": [
      [
        "1",
        "sect 1",
        "1",
        "658",
        "987"
      ]
    ]
  },
  "mail_sent": {
    "relations": {
      "SECTION_ID": "sections.ID"
    },
    "columns": [
      "DESC",
      "DIRECTORATE_ID",
      "ID",
      "SENDING_DATE",
      "DEPARTMENT_ID",
      "SECTION_ID"
    ],
    "records": []
  },
  "departments": {
    "relations": {
      "ID": "mail_sent.DEPARTMENT_ID"
    },
    "columns": [
      "ID",
      "NAME",
      "DIRECTORATE_ID",
      "EDL_ID",
      "PHONE_NUMBER",
      "ROOM_NUMBER"
    ],
    "records": [
      [
        "1",
        "department 1",
        "1",
        "1",
        "1236",
        "321"
      ],
      [
        "2",
        "depart 2",
        "2",
        "2",
        "256",
        "6987"
      ]
    ]
  }
}
```

the mail_sent table (relation) is returned but I don't want it to be returned, and I am getting the 2 departments that are not related to the section, I am getting all the departments, not only the related one.

and if i do : api.php/sections?include=departments&filter=id,eq,1&transform=1
I get

```
{
  "sections": [
    {
      "ID": "1",
      "mail_sent": [],
      "NAME": "sect 1",
      "DEPARTMENT_ID": "1",
      "PHONE_NUMBER": "658",
      "ROOM_NUMBER": "987"
    }
  ]
}

```
The department is not retruned.

Thank you

**Comment by mevdschee** [comment]
The script determines relations by foreign key constraints and there is none between sections and departments. Also since you have multiple relations to the same table you may set 'auto_include' to false in the options.

**Comment by khkassem** [comment]
setting auto_include option to false solved my problem

Thank you

**Comment by mevdschee** [comment]
You are welcome. Enjoy the software and thank you for your feedback.
