### ISSUE TITLE
beforeHandler and POINT type

### ISSUE THREAD

**Issue by nik2208** [mevdschee/php-crud-api#891]
trying to figure out how to post/update lat/lon values.

It seems I need  mysql `GeomFromText` function to set properly the field, to be inserted into the table.

May I achieve the desired result though the `beforeHandler`?

**Comment by mevdschee** [comment]
I think you should be able to post the content as a WKT string to be inserted or updated in the table. Let me know whether or not that works. Kind regards, Maurits

**Comment by mevdschee** [comment]
For an example see:

https://github.com/mevdschee/php-crud-api/blob/main/tests/functional/001_records/052_edit_user_location.log

**Comment by mevdschee** [comment]
If you have any further questions, feel free to open another issue.
