### ISSUE TITLE
dbAuth authentication for active users

### ISSUE THREAD

**Issue by chattago2002** [mevdschee/php-crud-api#892]
Hello.
I'm working with this repository and I'm proud to use it, it saves me a lot of time.

I need to understand if it's possible to do the following.
I use "dbAuth" in "middlewares" and authentication is working fine, reading username from "email" column and "password" from "hashed_pwd" column of "users" table.
However in this table I have an additional column with the "state" of the user (active or inactive), so I need to allow authentication only for active users.
How can this be made?

**Comment by chattago2002** [comment]
> You could make a view that holds only the active users and use that as the users table.

Thanks you very much. I'm deeply absorbed in the project. A simple solution was in front of me but no able to see it. Thanks again

**Comment by mevdschee** [comment]
Let me know whether or not this works for you. Kind regards, Maurits

**Comment by chattago2002** [comment]
> Great, thank you for your kind words. Let me know whether or not this works for you. Kind regards, Maurits

Yes, it's working fine. Thank you so much

**Comment by dswdcares** [comment]
Is it possible to use views for login and also enable register end-point? I've successfully used views to login active users but the register endpoint is now throwing error.

`<b>Fatal error</b>: Uncaught PDOException: SQLSTATE[HY000]: General error: 1471 The target table active_users of the
INSERT is not insertable-into in ...`
