### ISSUE TITLE
Is there an example of how to setup api.include.php?

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#895]
What if you are using the api.include.php instead? There is no config at the bottom of the file? Is there an example of how to setup api.include.php?

_Originally posted by @awinante in https://github.com/mevdschee/php-crud-api/issues/866#issuecomment-1207287721_

**Comment by mevdschee** [comment]
@awinante You may use index.php and replace `../vendor/autoload.php` with `api.include.php`. I hope that helps.

see: https://github.com/mevdschee/php-crud-api/blob/main/src/index.php

**Comment by awinante** [comment]
Ok great. I will give it a try. And to confirm, would this function with these 2 files only? index.php and api.include.php? Or are there dependencies?

**Comment by awinante** [comment]
Based on your recommendation, I notice there is still dependencies for the file. I think I might be understanding the notion of a single file script here. Can the api.include.php be used as a standalone script?

**Comment by mevdschee** [comment]
> Or are there dependencies?

No dependencies that I'm aware of.

**Comment by awinante** [comment]
Thanks @mevdschee . I am able to use the api.php file on its own. However, I am not able to get a basic custom controller working. I have tried a few of the examples and I only see Route not found. I am not sure what I am missing.

**Comment by mevdschee** [comment]
>I have tried a few of the examples and I only see Route not found. I am not sure what I am missing.

Please be more specific about the files you have, their contents and the exact URLs you request and the error messages you get.

I'm happy to reproduce any error you get, but you need to help me to get there.

Kind regards, Maurits

**Comment by awinante** [comment]
Ok sure! Appreciate it.

----

Ok so I was busy putting together a long detailed description of my issue, which led me to getting it to work. Your thoughtful message helped me solve it myself, so thank you.

**Comment by mevdschee** [comment]
Glad you got it working. Feel free to open another issue if you run into new problems.
