### ISSUE TITLE
OpenAPI definition missing path portion of server URL

### ISSUE THREAD

**Issue by t-schroeder** [mevdschee/php-crud-api#897]
If this API lies in a subfolder of my webserver root, the OpenAPI definition created through the `/openapi` endpoint doesn't contain the subfolder necessary to call the API.

Lets say my API lies in `https://my.server/some-api/`. I'm using swagger-ui to display an interactive documentation of my API. Any requests sent from swagger-ui go to `https://my.server/status/ping` instead of `https://my.server/some-api/api.php/status/ping`.

**Comment by t-schroeder** [comment]
I've linked a simple workaround.

**Comment by mevdschee** [comment]
@t-schroeder can you confirm that this fix works?

**Comment by t-schroeder** [comment]
@mevdschee I've tested your fix and it works. 👍 Closing this issue.

**Comment by mevdschee** [comment]
Released v2.14.8 with this fix
