### ISSUE TITLE
Can't access MyController

### ISSUE THREAD

**Issue by fallenruby** [mevdschee/php-crud-api#902]
Hi, I have installed `php-crud-api` on a webserver with Apache 2.4 and PHP 7.4.3 (Virtualmin).
I'm using api.php with a custom controller called MyController (MyController.php).

```
$config = new Config([
        'address' => '127.0.0.1',
        'port' => '3306',
        'username' => 'username',
        'password' => 'password',
        'database' => 'database',
        'customControllers' => 'MyController',
        'debug' => true
]);
```
I tried with the default .htaccess, but I get **No input file specified.** at every request. So I've changed the .htaccess in:
```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ api.php?/$1 [QSA,L]
</IfModule>
```
note the question mark after api.php:  RewriteRule ^(.*)$ api.php?/$1 [QSA,L]

With this modification everything works as expected since I can easly get results with **api.domain.com/records/table**

The thing that does not work it's MyController, I have this error: **"Route '/products/1' not found"**. I think that is a .htaccess or a apache misconfiguration. Do you have any hint on this? Thank you

**Comment by mevdschee** [comment]
>The thing that does not work it's MyController, I have this error: "Route '/products/1' not found".

How is MyController linked to the path `/products/1`? Can you show the snippet of code that does that?

**Comment by fallenruby** [comment]
Hi @mevdschee, thank you for your reply. 
I forgot to include MyController.php in the api.php file.

```
namespace Tqdev\PhpCrudApi {

    use Tqdev\PhpCrudApi\Api;
    use Tqdev\PhpCrudApi\Config;
    use Tqdev\PhpCrudApi\RequestFactory;
    use Tqdev\PhpCrudApi\ResponseUtils;
    include "MyController.php";
    $config = new Config([
        // 'driver' => 'mysql',
        'address' => '127.0.0.1',
        'port' => '3306',
```

**Comment by mevdschee** [comment]
I'm happy to hear that you solved the issue. Enjoy the software!
