### ISSUE TITLE
Got "Packets out of order" warning

### ISSUE THREAD

**Issue by coolalexhuang** [mevdschee/php-crud-api#903]
I have a cron job to call read API every morning, but it throws "**PHP Warning:  Packets out of order. Expected 1 received 0. Packet size=145 in /Users/shopee-sec/php-crud-api/api.php on line 6652**" error for the 1st call of every day, however the 2nd and on going calls work well, cloud you help take a look why this happen and how to fix it?

**Comment by mevdschee** [comment]
Seems to be a PHP issue, see: https://bugs.php.net/bug.php?id=81335

What versions and os do you run on?

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
From: coolalexhuang ***@***.***>
Sent: Saturday, September 3, 2022 5:12:17 AM
To: mevdschee/php-crud-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mevdschee/php-crud-api] Got "Packets out of order" warning (Issue #903)


I have a cron job to call read API every morning, but it throws "PHP Warning: Packets out of order. Expected 1 received 0. Packet size=145 in /Users/shopee-sec/php-crud-api/api.php on line 6652" error for the 1st call of every day, however the 2nd and on going calls work well, cloud you help take a look why this happen and how to fix it?

**Comment by coolalexhuang** [comment]
> Seems to be a PHP issue, see: https://bugs.php.net/bug.php?id=81335 What versions and OS do you run on?

Mac OS 11.6.8

**Comment by mevdschee** [comment]
What MySQL version?

**Comment by coolalexhuang** [comment]
> What MySQL version?

<img width="608" alt="image" src="https://user-images.githubusercontent.com/2528449/189088523-a6a45692-947c-436a-b2f2-74f179263b29.png">

**Comment by mevdschee** [comment]
I think it has to do with the persistent connections in the pool and your timeouts for those. Suggested fix:

>If you making SQL requests after a long period of time - you can get a same issue.
>Fix of that possible by tune this values in mysql service config:
>- interactive_timeout
>- wait_timeout


See: https://stackoverflow.com/questions/62282427/after-connecting-to-mysql-database-im-getting-error-got-packets-out-of-order

**Comment by coolalexhuang** [comment]
> I think it has to do with the persistent connections in the pool and your timeouts for those. Suggested fix (set to 24+ hours):
> 
> > If you making SQL requests after a long period of time - you can get a same issue.
> > Fix of that possible by tune this values in mysql service config:
> > 
> > * interactive_timeout
> > * wait_timeout
> 
> See: https://stackoverflow.com/questions/62282427/after-connecting-to-mysql-database-im-getting-error-got-packets-out-of-order
> 
> Alternative change the line:
> 
> ```
> \PDO::ATTR_PERSISTENT => true,
> ```
> 
> to:
> 
> ```
> \PDO::ATTR_PERSISTENT => false,
> ```
> 
> in the function `getOptions()` in the file `src/Tqdev/PhpCrudApi/Database/GenericDB.php`.
> 
> Please report back after trying both options.

After change to this "\PDO::ATTR_PERSISTENT => false," and restart the service, it works as expected, thanks a lot.
