### ISSUE TITLE
openapi tags sqlite fist table missing

### ISSUE THREAD

**Issue by pat123456** [mevdschee/php-crud-api#904]
Hello,

With an sqlite db, in the /openapi "tags" entry, the first table (in alphabetical order) is missing.

May I miss something, or this is a bug ?

Thanks !

**Comment by mevdschee** [comment]
I've tested with the test database and there are 13 tables, just as there should be, no matter the driver.

**Comment by pat123456** [comment]
thank for your answer

here the steps :
1/ copy api.php in an empty folder
2/ change the config to : 
$config = new Config([
    'driver' => 'sqlite',
    'address' => 'db.db',
]);
3/ create a new db in DB Browser for SQLite (on Linux)
4/ add table "table1" (schéma = CREATE TABLE "table1" ("id" INTEGER, "content" TEXT, PRIMARY KEY("id" AUTOINCREMENT)) )
5/ go to localhost/folder/api.php/openapi
tags is :
"tags":[{"name":"status","description":"status operations"}]
6/ add a new table  (schéma = CREATE TABLE "table2" ("id" INTEGER, "content" TEXT, PRIMARY KEY("id" AUTOINCREMENT)) )
tags is :
"tags":[{"name":"status","description":"status operations"},{"name":"table2","description":"table2 operations"}]}

**Comment by mevdschee** [comment]
Yeah.. I can reproduce the problem, thank you. I will update this ticket when a fix is available.

**Comment by pat123456** [comment]
here the "openapi/tags" of my previous test, where sqlite_sequence is showed :

"tags":[{"name":"status","description":"status operations"},{"name":"actualite","description":"actualite operations"},{"name":"images","description":"images operations"},{"name":"sqlite_sequence","description":"sqlite_sequence operations"},{"name":"test","description":"test operations"},{"name":"users","description":"users operations"}]}

**Comment by mevdschee** [comment]
Yes, I understand. Showing internal structures was not the intention and I removed it for consistency. If you want to make the ignored table list a configurable option, then that would be a separate feature request.

**Comment by mevdschee** [comment]
Fixed in v2.14.9

**Comment by pat123456** [comment]
Thank a lot ! It work find now, all tables are shown and sqlite_sequence disappear in my fist test. Have actuality no need of an ignored table list option.
