### ISSUE TITLE
dbAuth gives 401 error after logging in and making subsequent API requests

### ISSUE THREAD

**Issue by NorthFred** [mevdschee/php-crud-api#909]
I am trying to implement `dbAuth` in my current project by removing the current Firebase authentication implementation, because this solution may support my role-based multi-tenant solution better. (see old [issue 896](https://github.com/mevdschee/php-crud-api/issues/896)).

Following the instructions in the readme and going through answers in the issues in this repository, I managed to successfully use the single-file php api and make the user(s) register (sign up), log in and log out. The front-end solution under development is currently run from localhost as an Ionic Angular application.

What was done so far:

- A `users` table was set up to contain `username`, `password`, `role` and other user information.
- User registration was enabled.
- Registration and login is successful via the `/register` and `/login` endpoints
- Logout is successful via the `/logout` endpoint

Here is a snapshot of the configuration:

```
    $config = new Config([
        'database' => 'events',
        'address' => 'mysql05.xxxxxxxx.fi',
        'username' => 'db_user,
        'password' => 'db_pass,
	'middlewares' => 'dbAuth,cors,authorization,multiTenancy',
	'cors.allowHeaders' => 'Content',
	'cors.allowCredentials' => true,
	'cors.allowedOrigins' => 'http://localhost:8100',
	'dbAuth.loginTable' => 'users',
	'dbAuth.registerUser' => true,
	'dbAuth.passwordLength' => 6,
	'dbAuth.sessionName' => 'loginSession',
	'multiTenancy.handler' => function($operation, $tableName) { ........... }
```

When the login is successful, I have been trying to make API requests with Angular's `HttpClient` by propagating the Cookie in the request as follows:

```
      let options = {
        method: 'GET',
        headers: {
          'Accept': 'application/json; charset=utf-8'
        },
        withCredentials: true
      };
      this.http.get(`${authUrl}/me`, options).subscribe(.....)
```

However, a request to the `/me` endpoint after logging in gives a 401 error.

Now, this gets interesting.  With the order of middlewares as `'middlewares' => 'cors,dbAuth,authorization,multiTenancy'`, I am getting Internal Server Errors with following error:

```
[11-Sep-2022 14:11:11 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: Header values must be RFC 7230 compatible strings. in /home3/kmzyummy/public_html/rigor/api.php:1740
Stack trace:
#0 /home3/kmzyummy/public_html/rigor/api.php(1633): Nyholm\Psr7\Response->validateAndTrimHeader('Access-Control-...', true)
#1 /home3/kmzyummy/public_html/rigor/api.php(7974): Nyholm\Psr7\Response->withHeader('Access-Control-...', true)
#2 /home3/kmzyummy/public_html/rigor/api.php(7521): Tqdev\PhpCrudApi\Middleware\CorsMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(Tqdev\PhpCrudApi\Middleware\Router\SimpleRouter))
#3 /home3/kmzyummy/public_html/rigor/api.php(7485): Tqdev\PhpCrudApi\Middleware\Router\SimpleRouter->handle(Object(Nyholm\Psr7\ServerRequest))
#4 /home3/kmzyummy/public_html/rigor/api.php(11829): Tqdev\PhpCrudApi\Middleware\Router\SimpleRouter->route(Object(Nyholm\Psr7\ServerRequest))
#5 /home3/kmzyummy/public_html/rigor/api.php(12414): Tqdev\PhpCrudApi\Api->handle(Object(Nyholm\Psr7\ServerRequest))
#6 {main}
```

Now I understood the order of the middleware may be important, I fail to understand why it throws this fatal error.

In addition, the browser is also showing the following CORS error in the DevTools console:
```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://webserver.com/api.php/me’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).```

(Note that the `api.php` file is uploaded to the web server and using a live database. The app under development is served from the local machine.)

What am I missing here?

**Comment by NorthFred** [comment]
This took me longer than expected to figure out, but few things went wrong here:

1) Correct order of the 'middlewares' is FIRST 'cors' and then 'dbAuth'
2) `'cors.allowCredentials' => true,` should have a string value: `'cors.allowCredentials' => 'true',`

Issue can be closed.

**Comment by vip9** [comment]
This took me longer too (even finding it here). Even if cors is enabled default, it does not runs first. Could You @mevdschee  mention it in documentation, to manually put it first when using dbAuth.
