### ISSUE TITLE
transform not working with filter

### ISSUE THREAD

**Issue by abureviewer3** [mevdschee/php-crud-api#91]
CURLOPT_URL => $url.'api.php/oc_orders?filter[]=date_added,gt,2016-07-13 00:00:00&transform=1'

**Comment by mevdschee** [comment]
datetime or timestamp?

**Comment by mevdschee** [comment]
Hi, could it be that you need to call ```urlencode()``` on the string before appending to ```$url```?

**Comment by abureviewer3** [comment]
Hi, thank for your response I adjusted it in my coding its works like charm.
