### ISSUE TITLE
scandir(C:\Windows\Temp\phpcrudapi-01837a59-cache): Access is deni (code: 5)

### ISSUE THREAD

**Issue by firextechnologies** [mevdschee/php-crud-api#913]
Hello, 

how to resolve this issue?

scandir(C:\Windows\Temp\phpcrudapi-01837a59-cache): Access is deni (code: 5)

even though my setup all on D not in C 

be noted i am using the API CRUD through Laravel

**Comment by firextechnologies** [comment]
> That is because you are not allowed to write to the temp folder. Set "cacheType" to "NoCache" in the config to disable caching. Kind regards, Maurits

Thanks 

be noted that I found the function was doing on TEMP as System variable, not the user variable, so after I change the settings for the folder of the TEMP variable for the system to another location it works fine, but thanks for the option you mentioned. 
If its possible to choose the temp folder from the code will be an advance point if possible for the future.

**Comment by mevdschee** [comment]
>be noted that I found the function was doing on TEMP as System variable

AFAIK the function calls 'sys_get_temp_dir' in PHP to store data in, which I believe is correct.

see: https://www.php.net/manual/en/function.sys-get-temp-dir.php
