### ISSUE TITLE
How to allow only read operation to certain table and only certain columns to be showing?

### ISSUE THREAD

**Issue by firextechnologies** [mevdschee/php-crud-api#914]
How to allow only read operation to a certain table and only certain columns to be showing?

for example, I have table 'myorder' and I need to view only part of the columns. and can only read 
and restrict the rest of the tables from being accessed. 

I saw some of the examples about authorization.tableHandler but not sure if there a simple way to hide around 20 tables, and the table i want to access has more than 60 columns so hopefully there is a simple way to implement it

thank you.

**Comment by firextechnologies** [comment]
Ok so i approach to this now

`        'authorization.tableHandler' => function ($operation, $tableName) {
            if($operation == 'list' && $tableName == 'myorder') return $tableName;
            return !$tableName;
        },`

`'authorization.columnHandler' => function ($operation, $tableName, $columnName) {
            if($operation == 'list' && $tableName == 'myorder'){
                return 
                !($columnName == "ID" OR ....);
            }
            return !$tableName;
        },`

my issue now its really hard to list 63 or 62 columns within the line of columnName  with OR 

let me know if there is something to do work around this =(

**Comment by firextechnologies** [comment]
> Ok so i approach to this now
> 
> ` 'authorization.tableHandler' => function ($operation, $tableName) { if($operation == 'list' && $tableName == 'myorder') return $tableName; return !$tableName; },`
> 
> `'authorization.columnHandler' => function ($operation, $tableName, $columnName) { if($operation == 'list' && $tableName == 'myorder'){ return !($columnName == "ID" OR ....); } return !$tableName; },`
> 
> my issue now its really hard to list 63 or 62 columns within the line of columnName with OR
> 
> let me know if there is something to do work around this =(


Ok i make something i thought it was some error from my end but if i hide the first column it give an error 
so i make it in this way 
return ($columnName == "Id1" OR $columnName == "Name")

and work fine for me

**Comment by mevdschee** [comment]
Glad you got it working. Feel free to open new issues when you have further questions. Enjoy the software!
