### ISSUE TITLE
A flag to enable list of tables and fields?

### ISSUE THREAD

**Issue by zemian** [mevdschee/php-crud-api#916]
Hi,

Would it be useful to add a configurable flag that can expose list of tables and fields available (eg: like a /schema endpoint)? I understand this would be a security risk, but it would be very useful for internal project use where it's not a concern. Also have a flag default to off should be safe enough.

**Comment by mevdschee** [comment]
Try adding "columns" to the the "controllers" config parameter. It does what you want.

**Comment by zemian** [comment]
Ahh! Yes it does work for me! Thank you @mevdschee!
