### ISSUE TITLE
Multi database, where every tenant has it's own database (using the "reconnect" middleware).

### ISSUE THREAD

**Issue by Kuhlig** [mevdschee/php-crud-api#917]
hello 

I have a question to the above middlware .  I have 2 DB on the same server with same user and same passwd. Let's say 

* SQMS_ORG1 (default)
* SQMS_ORG2

Can i send an API request to change the DB? from SQMS_ORG1 -> SQMS_ORG2
```

curl --location --request GET 'http://localhost/???' \
--header 'Authorization: Basic PASSWD'
```

or do I have (can) send the DB Name (in the header) with every request? 

sorry for the question but I don't understand how to Trigger the DB Change 

thanks rob

**Comment by mevdschee** [comment]
Hi Rob,

You need to ensure the database name is in the URL or in the header, so that you can set the correct value.

>sorry for the question but I don't understand how to Trigger the DB Change

There is no such thing as a "change", it needs to be set on every request.

I hope this helps you. Kind regards, Maurits

**Comment by pottertech** [comment]
A "change" is an "update" in database terms.

**Comment by mevdschee** [comment]
>A "change" is an "update" in database terms.

I believe that @Kuhlig is talking about a "change" of database connection, not a "change" to a database record.

**Comment by Kuhlig** [comment]
HI Maurits 

" you need to have the database name in the URL"

like this?
```
curl --location --request GET 'http://localhost/records/{table}?database=SQMS_ORG2' \
--header 'Authorization: Basic PASSWD'

curl --location --request GET 'http://localhost/records/{table}' \
--header 'database: SQMS_ORG2' \ --header 'Authorization: Basic PASSWD' 
```

Does not work in my case - ist still get results from SQMS_ORG1. Do I have to load the Reconnect Milldeware in the config?

PHP_CRUD_API_RECONNECT=1

I have it like this but does not work either ... 

any Hints? thanks!

Rob

**Comment by mevdschee** [comment]
Yes @Kuhlig, you're on the right path. Next you need to program a handler:

    'reconnect.databaseHandler' => function () {
        return $_GET['database'];
    },

and add that to the config.

**Comment by Kuhlig** [comment]
I give it a try when i have time - in the meantime it is easier for me to start 2 Docker Container :-) with SWAG 
SQMS_ORG1.domain.tld
SQMS_ORG2.domain.tld
Thanks for your help ROB

**Comment by mevdschee** [comment]
>I give it a try when i have time

Did you give it a try? Did you succeed?

**Comment by Kuhlig** [comment]
sorry no - i just used 

- SQMS_ORG1.domain.tld
- SQMS_ORG2.domain.tld

since i really have no clue to do that . this workarround is fine for me  ...
thanks for your help

**Comment by mevdschee** [comment]
> this workaround is fine for me ...

Practical solutions are often the best ones. Enjoy the software, kind regards, Maurits
