### ISSUE TITLE
Query returns empty records in SQLite

### ISSUE THREAD

**Issue by ninadst** [mevdschee/php-crud-api#92]
I am querying a sqlite database. While the api works with most of the data, for some it returns empty records.

e.g. `http://localhost/analytics/api.php/test`

returns:

`{"test":{"columns":[],"records":[[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""],[""]......`

**Comment by ninadst** [comment]
Looks like "sys/columns' does not finish building.  I am thinking it holds information that is needed to process the query.

**Comment by mevdschee** [comment]
Can you help me debug it? Is there any (failing) test case that you can share, including the SQL to create the database?

**Comment by ninadst** [comment]
Not sure if I can share a test case as it is possibly an issue with size of the sqlite database. My database has 24 tables and 1905 columns in total. I believe the problem came from the php server timing out after 30 seconds while executing `connect ` after schema updates. I was able to get around the problem by adding  `set_time_limit(0);` in `public function connect`. Not a good solution but it worked and it finished executing properly. Now the query executes as expected.

**Comment by mevdschee** [comment]
>Not a good solution.. 
Why not? What would define a good solution?

**Comment by ninadst** [comment]
What if for some reason something locks up in `connect`, php server will not time out and will be locked up (forever?) as well. I think having an option to forcefully "refresh" schema through API with timeout value as one of the parameters might be better option.

**Comment by mevdschee** [comment]
@ninadst you can simply set it to 3600 within the following if:

```if ($version != $this->db->querySingle('SELECT "version" from "sys/version"'))```

This way it will only increase timeout to one hour when it needs to update schema information.

I think the parameter option does not make sense as there is no point in running the script without or with outdated schema information and your concern about locking up still applies.

**Comment by ninadst** [comment]
I am fine with this solution for my specific case. But I would be against it as a general solution. Someone who does not know about internals might be left wondering why a first query was taking this long. By having a call in API for forced update of the schema information (which means that schema information update will happen irrespective of `$version`.) and documenting it, provides enough pointers that such internal mechanism exists. The schema version does not match then the update should happen regardless (so there should be no outdated schema).

I think another problem is that the connect call is not confirming the schema information was successfully extracted before using it. Which meant that in my case it returned empty records.

**Comment by mevdschee** [comment]
It may not be the prettiest solution, but this will do for now.
