### ISSUE TITLE
Decimal point is comma internationalization

### ISSUE THREAD

**Issue by gasalvati** [mevdschee/php-crud-api#920]
Hello
I'm using a MySql database and your Api as back-end, and an Appgyver app as front-end for a simple development (as a hobby).
In my place we use the comma "," as the decimal point "." for numbers.
As far as I understand Appgyver won´t let me change the decimal point (so it expects and treats numbers with comma as the decimal separator). On the other side up to now my DB use the dot as the decimal separator because **@@lc_time_names** is set to **en_US**.
I think that my options to solve this are two:
1-Change MySql to decimal point is comma **es_AR**, but in this case the api should be able to deal with comma numbers, 
OR
2-The api being able to do the translation from the comma numbers front-end to the dot numbers back-end.

**Options**
_OPTION 1-_Change MySql configuration to es_AR (spanish Argentina) that will change the decimal point to comma, and ask you if the api can deal "as is" with "decimal point is comma" numbers, or have to be set in config or with handlers.
The api should be able to read and write to the db with comma numbers, and also deal the requests and responses with comma numbers.
_OPTION 2-_The api be able to translate external requests and responses from comma numbers to dot numbers, and viceversa. By config or with handlers

Can you please lead me to the solution?

Thanks
GS

**Comment by gasalvati** [comment]
OK,
I found out that MySql internationalization will only affect the way it looks for other aspecs and I will have to go on storing the data in the decimal point dot separator for numbers. So only option 2 is alive.

Will the api be able to translate external requests from decimal point is comma number to internal dot, and then the responses translated from dot numbers again to comma numbers?

Can this be achieved by the api?

Thanks

**Comment by gasalvati** [comment]
Forgive me,
I will put this ON HOLD.

I also found out that even though in appgyver if I set the input keyboard to decimal-pad it will be with "," but the internal number do not accpet comma as the decimal separator.

I have to deal all the way with "." as the decimal separator, and now my problem is how to make appgyver let me use a decimal-pad input keyboard with "." (problem for another forum)

Thanks to anyone who spent time in here.

**Comment by mevdschee** [comment]
@gasalvati No problem. Thank you for sharing your story. A lot of these tools (like AppGyver) use "en_US" locales internally (translating only on the front-end). On the other hand if you wanted the API to be internationalized it would be quite a job as you are right that there are many locale settings to consider: request, the PHP application, the underlying server, the database connection and the stored data. Enjoy the software. Feel free to follow up at any point in time. Closing for now.
