### ISSUE TITLE
Docker Hub pipeline

### ISSUE THREAD

**Issue by marionee** [mevdschee/php-crud-api#921]
Hi there

it could be useful to have a pipeline in order to automatically build/publish a docker image after every new git Tag.

At this moment the last image is from 4 months ago.

**Comment by mevdschee** [comment]
>it could be useful to have a pipeline in order to automatically build/publish a docker image after every new git Tag.

There is a script called `publish-docker.sh` that does what you want. I should run it on every release, but sometimes I forget.

>At this moment the last image is from 4 months ago.

Thank you for the heads up.. I ran the script.

**Comment by marionee** [comment]
> > it could be useful to have a pipeline in order to automatically build/publish a docker image after every new git Tag.
> 
> There is a script called `publish-docker.sh` that does what you want. I should run it on every release, but sometimes I forget.
> 
> > At this moment the last image is from 4 months ago.
> 
> Thank you for the heads up.. I ran the script.

Thank you.
