### ISSUE TITLE
Auth with cookie and curl

### ISSUE THREAD

**Issue by becangular** [mevdschee/php-crud-api#924]
Hello,
i'm trying to do a POST request from  external php file, but i always get an error 1011.

This is my code:

	if (file_exists($upload_path . $_FILES['file']['name'])) {
				$_FILES['file']['name'] = $_FILES['file']['name'] . uniqid(rand(10, 200)) . '-' . rand(1000, 1000000);
				move_uploaded_file($_FILES['file']['tmp_name'], $upload_path . str_replace('.', '', $_FILES['file']['name']) . '.' . $ext);
				$object = new stdClass();
				$object->nome = str_replace('.', '', $_FILES['file']['name']) . '.' . $ext;
				$object->url = '/' . $_POST["pratiche_id"] . '/';
				$object->pratiche_id = intval($_POST["pratiche_id"]);
				$curl = curl_init();
				curl_setopt_array($curl, array(
					CURLOPT_URL => $url,  /// myapi/api.php/records/list
					CURLOPT_RETURNTRANSFER => true,
					CURLOPT_ENCODING => '',
					CURLOPT_MAXREDIRS => 10,
					CURLOPT_TIMEOUT => 0,
					CURLOPT_FOLLOWLOCATION => true,
					CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
					CURLOPT_CUSTOMREQUEST => 'POST',
					CURLOPT_POSTFIELDS => json_encode($object),
					CURLOPT_COOKIEJAR  => $_COOKIE['PHPSESSID'],
					CURLOPT_COOKIEFILE => $_COOKIE['PHPSESSID'],
					CURLOPT_RETURNTRANSFER => true,							
					CURLOPT_HTTPHEADER => array(
						'Content-Type: application/json'
					),
				));

				$response = curl_exec($curl);
				curl_close($curl);
				echo json_encode($response);

And this, my configuration:

$config = new Config([
        'middlewares' => 'authorization,cors,dbAuth, json',
        'authorization.tableHandler' => function ($operation, $tableName) {
          return $tableName != 'users';
          },
         'dbAuth.mode' => 'required',
    ]);

Thanks

Best Regards

Joseph

**Comment by mevdschee** [comment]
Hi Joseph,

You are using 'dbAuth' requiring a valid session and I'm pretty sure these are not valid:

    CURLOPT_COOKIEJAR  => $_COOKIE['PHPSESSID'],
    CURLOPT_COOKIEFILE => $_COOKIE['PHPSESSID'],

If you are using a valid cookiejar and you have in fact logged in then you may not get this 'AUTHENTICATION_REQUIRED' error (1011). Look at the contents of your cookiejar file to debug this. The 'CURLOPT_COOKIEJAR' setting should be a full path prefixed with the temp directory of your system e.g. '/tmp/php-crud-api-cookies.txt'.

See: https://stackoverflow.com/questions/28576197/why-is-curlopt-cookiejar-somehow-saving-different-cookie-values-than-the-set-coo

**Comment by mevdschee** [comment]
Closing this issue as it is about Curl automation in PHP and not about the API. Also because server to server authentication with dbAuth is not recommended (use apiKeyAuth instead).
