### ISSUE TITLE
DbAuth function not working?

### ISSUE THREAD

**Issue by Deltas92** [mevdschee/php-crud-api#927]
I have several questions about DBAuth. Does it already work? What table structure do you need for it?

And with what encryption do you have to enter the password into the database?

When I send the requests to /login and /records/records/, I get the following responses:

{"code":1012, "message": "Authentication failed for 'delta'"}
{"code":1011, "message": "Authentication required"}

Are there any instructions for the DBAuth method somewhere? I have now read through almost everything and somehow found nothing. 

Can I get some help here?

**Comment by nik2208** [comment]
in the readme the documentation appears to be extensive.
did u enable the debug? //not sure this can help you at this step but it will for sure in the future
the first message means that somehow user `delta` is not authorized (ur actually sending a post request but delta has no authorization - not existing user, wrong password.. u should find out).
the second message means that ur sending a get request without the proper session cookie (that would have be set during the login process).
hope this helps

**Comment by Deltas92** [comment]
Thanks for the answer, debugging was active. However, I do not get any message or find any log that could indicate an error. 

What the messages mean in detail is also clear to me. The user exists and the corresponding password was sent to /login via POST.

Does the password have to be stored as a hash value in the database? What must the users table look like? 

Is the password for the user simply stored in plain text in the database? This seems rather insecure to me? Hence all my questions. 

On the whole, I think I'm using the API correctly, but I don't understand how I should use DBAuth. 

My test setup is a CURL query similar to the one I saw in another issue here. (As I said, I have already read through a lot here). Here is my example for the login: 

$options = array('username' => 'delta', 'password' =>'test1233' );
$query = http_build_query($options);
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_URL, $api_url);
curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
curl_setopt($ch, CURLOPT_COOKIEJAR, 'test_'.session_id());
curl_setopt($ch, CURLOPT_COOKIEFILE, 'test_'.session_id());
$res = curl_exec($ch);
curl_close($ch);

**Comment by Deltas92** [comment]
And here is the example for get the records from the table: 

$ch = curl_init($api_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_COOKIEJAR, 'test_'.session_id());
curl_setopt($ch, CURLOPT_COOKIEFILE, 'test_'.session_id());
$res = curl_exec($ch);
curl_close($ch);

**Comment by Deltas92** [comment]
I would like to set the API so that you log in there with username and password and then retrieve the data. If I have read this correctly, is DBAuth the right middleware for this ? Or have I misunderstood something in the documentation?

**Comment by nik2208** [comment]
U should register the user as described in the docs, because the password is automatically hashed. Or at least store the password already hashed. 
the dbauth middleware is what u looking for and it simply works.
make sure u have read and understood the relevant part of the docs: it actually mentions the hashing password process.

**Comment by Deltas92** [comment]
What is the relevant part of the documentary? That's what I'm trying to find out here. I don't find much about DBAuth in the documentation and maybe I'm misunderstanding something. Or am I overlooking something. 

If I enter "dbAuth" as middleware, I get the new routes for the API 
/me
/register <<< I would now POST to this command. 
/login
/password
/logout

However, when I do this via the API, I get the message that I do not have permission to do this. Funny. 

I think the API and the whole project are very cool, but unfortunately I don't understand the documentation. For me, this is more of a search and guessing game. I could of course look at the whole API in detail and how the whole process works. But actually I wanted to use this as a viable alternative to developing it myself. 

Maybe also for the project in general it would be cool to split up all the different methods and the documentation about them and divide them into different sections and components.

**Comment by nik2208** [comment]
>Maybe also for the project in general it would be cool to split up all the different methods and the documentation about them and divide them into different sections and components.

Of course u can start doing that, that would be very useful!
Also in the issues sections if u search dbAuth u will find many answers and maybe you can find the relevant for ur case (there are so many possibility and combinations that it is not so easy to give a sole answer to all the questions).

What is your backend database? I had some (not investigated) problems with mariaDB.

**Comment by nik2208** [comment]
>If I enter "dbAuth" as middleware, I get the new routes for the API
/me
/register <<< I would now POST to this command.
/login
/password
/logout
However, when I do this via the API, I get the message that I do not have permission to do this. Funny.

actually this is an auth method, so you cannot actually request /me if ur not logged in, right? who tell the db who is the "me" your looking for if ur not logged in? nor you cannot logout or change password if your not logged in, agree?
at first instance u can register or login.
the easiest is to register first, to be sure that the hashing and dehashing procecess doesnt appear to be corrupted.
Did u try that?

**Comment by Deltas92** [comment]
When I call the /register Route i get this message: 

{"code":1012,"message":"Authentication failed for 'delta'"}

**Comment by Deltas92** [comment]
This is my Register CURL

$options = array('username' => 'delta', 'password' =>'test1233' );
$query = http_build_query($options);
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_URL, $api_url);
curl_setopt($ch, CURLOPT_POSTFIELDS, $query);
$res = curl_exec($ch);
curl_close($ch);

**Comment by nik2208** [comment]
and what's the response?

why using curl and not edit.swagger.io (importing the api.php's openapi
path?, setting dbauth as optional)?

**Comment by Deltas92** [comment]
the $api_url is:  https://MYDOMAIN/register 

I use a mysql database. 

Why using Curl? Why not? It is a simple way to test it. 

How can I register a USER for the DbAuth. Is that so difficult? I do not understand the structure of the Docs.

**Comment by Deltas92** [comment]
Thank you !

did u set this: `dbAuth.registerUser` to 1? <<< That was the point i don´t see. Now i can register.

**Comment by nik2208** [comment]
https://github.com/mevdschee/php-crud-api#middleware

you can't start reading a book at page 574 ;)

**Comment by Deltas92** [comment]
And now the Login and all the rest works too. But a last question. 

How do I secure my /register route?

I found this in the doc: 


'middlewares' => 'dbAuth,authorization',
'authorization.tableHandler' => function ($operation, $tableName) {
    return $tableName != 'users';
},

However, when I add this to the config, nothing works. Is there a special place where this has to be inserted? I would insert it in line 4455 in the array.

**Comment by nik2208** [comment]
what do u mean with securing? if U want someone to register u enable registration, if u dont u disable it.

**Comment by Deltas92** [comment]
I have seen the options for DBAuth, but I overlooked dbAuth.registerUser as an option to set. Maybe it was also because of the time last night that I didn't see it. But something like this suggests that the documentation should perhaps be divided into different segments. Precisely because the API can now do so much and encompasses so much.

**Comment by Deltas92** [comment]
> what do u mean with securing? if U want someone to register u enable registration, if u dont u disable it.

I mean this part of the docs: 

> It is IMPORTANT to restrict access to the users table using the 'authorization' middleware, otherwise all users can freely add, modify or delete any account! The minimal configuration is shown below:
> 
> 'middlewares' => 'dbAuth,authorization',
> 'authorization.tableHandler' => function ($operation, $tableName) {
>     return $tableName != 'users';
> },
> 
> Note that this middleware uses session cookies and stores the logged in state on the server.

**Comment by nik2208** [comment]
>I have seen the options for DBAuth, but I overlooked dbAuth.registerUser as an option to set. Maybe it was also because of the time last night that I didn't see it. But something like this suggests that the documentation should perhaps be divided into different segments. Precisely because the API can now do so much and encompasses so much.

this is a 5 years or so long and 10000 line of code library: even if it makes A LOT OF STUFF simple, it doesn't mean it is simple itself.

Every character in this pages represents someone's time donated to others. U can start donating your's helping us ;)

**Comment by nik2208** [comment]
>I mean this part of the docs:

well it does exactly what it says: it prevents users table (so the table used to grant access to users) to be queried and/or modified. U can access your (the logged in user) data via /me endpoint

**Comment by nik2208** [comment]
I suggest U to search for dhauth here in issues section, all of these questions have already been answered

**Comment by Deltas92** [comment]
> > I have seen the options for DBAuth, but I overlooked dbAuth.registerUser as an option to set. Maybe it was also because of the time last night that I didn't see it. But something like this suggests that the documentation should perhaps be divided into different segments. Precisely because the API can now do so much and encompasses so much.
> 
> this is a 5 years or so long and 10000 line of code library: even if it makes A LOT OF STUFF simple, it doesn't mean it is simple itself.
> 
> Every character in this pages represents someone's time donated to others. U can start donating your's helping us ;)

Of course I realise that and it is also understandable to me. 

What I just want to say is that if you separate and enter the documentation for each middleware, for example, it would bring a lot of clarity. 

Currently, you have to read through all the different authentication options in search of what you actually want. 

I didn't say that things are always easy just because they are supposed to make it easier. However, it would clearly help to understand this project and also help to ask more specific questions. 

I'll be honest, I've read the documentation twice, but I haven't been able to figure out what you have to enter where and for what in order to achieve this or that. Because there are simply many different options, but these options must then also be summarised for the respective middleware somewhere. 

Of course, once you have that and know it, it's no problem and at some point you'll find your way around the documentation. However, it would be much nicer if the documentation already answered 30-60% of the questions. And you can be sure that you haven't missed anything. 

Do you understand what I mean?

**Comment by Deltas92** [comment]
Thank you for your time and your Help  :)

**Comment by nik2208** [comment]
I completely understand what you mean, but somehow, at the end of the day, I find handy this approach of documentation (that is actually a top-down approach).
Many libraries have tons of pages and U easily get lost.
Here you have most of what u need already there.
U have an introduction, then a sort of handbook of out-of-the-box functions, then what we can consider plugins:
at first a list of all of them (u choose what u need), then a list of all of their options (u'll set the relevant), then a brief explanation of the plugins.
What is not extensively explained is quite for sure in the issues section, because all of the features come from ideas from the community.
In any case, here u can always find people helping anybody.
At first glance it may seem confused, but once u undestand how the library works everything starts assuming shape.

**Comment by mevdschee** [comment]
Thank you for your kind words @Deltas92 and your excellent support @nik2208. Feel free to reopen in case of followup questions. Kindest regards, Maurits
