### ISSUE TITLE
API call with 2 unique filters gives incorrect results. 

### ISSUE THREAD

**Issue by Datathecodie** [mevdschee/php-crud-api#929]
Currently using the API to call for filtered user data. 

`
$url = $base_url. '/api.php/records/users?filter1=username,eq,' . $username. '&filter2=password,eq,' . $password;
`

Expected: The equivalent SQL should be 
`"Select * from users where username = $username AND password = $password".`
As filters are uniquely numbered. 

Results: The resultant SQL generates results as 
` "Select * from users where username = $username OR password = $password".`
It returns users even if either of the filters matches.

**Comment by mevdschee** [comment]
Hi, it works as described in the documentation, see:

https://github.com/mevdschee/php-crud-api#multiple-filters

You are looking for:

    $url = $base_url. '/api.php/records/users?filter=username,eq,' . $username. '&filter=password,eq,' . $password;

Kind regards, Maurits

**Comment by Datathecodie** [comment]
Pardon me for not recognising the difference. 

Thanks for the quick resolution. Kudos to you and the project.

**Comment by mevdschee** [comment]
Thank you for your kind words, appreciated!
