### ISSUE TITLE
PUT / UPDATE doesnt work

### ISSUE THREAD

**Issue by niradler** [mevdschee/php-crud-api#93]
hi, strange problem.
POST , GET , DELETE all working, just PUT does not all test performed on client side in postman and server is php 5.6.6 
you can test it yourself : 
http://prototypesart.com/temp/spapi/crudapi/api.php
http://prototypesart.com/temp/spapi/crudui/

**Comment by mevdschee** [comment]
Did you find out what was wrong with your environment? This is most likely not a bug.

**Comment by niradler** [comment]
amm actually not the workaround is to delete and repost it :/

**Comment by isi-dwade** [comment]
Check that the PUT verb is accepted by your server. If you are using IIS, it usually isn't defined and must be added. I had to in this case.

**Comment by mevdschee** [comment]
I agree with @isi-dwade, that is most likely the problem.
