### ISSUE TITLE
allowMethods Question...

### ISSUE THREAD

**Issue by pottertech** [mevdschee/php-crud-api#931]
I want to restrict the API to only the OPTIONS and GET methods,  is my configuration for this correct?

    $config = new Config([                                                                                                                                                                                        
        'driver' => 'mysql',                                                                                                                                                                                      
        'address' => '1.2.3.4',                                                                                                                                                                                
        'port' => '3306',                                                                                                                                                                                         
        'username' => 'username',                                                                                                                                                                                
        'password' => 'password',                                                                                                                                                                           
        'database' => 'dbname',                                                                                                                                                                             
        'debug' => false,                                                                                                                                                                                         
        'middlewares' => 'cors,errors,json,authorization',                                                                                                                                                        
        'cors.allowedOrigins' => '*',                                                                                                                                                                             
        'cors.allowHeaders' => 'X-Authorization,Accept,Content-Type,Referer,User-Agent',                                                                                                                          
        'cors.allowMethods' => 'OPTIONS,GET',                                                                                                                                                                     
    ]);

**Comment by mevdschee** [comment]
No, that only restricts it for cross origin requests. Please take a look at #871

**Comment by pottertech** [comment]
OK Thanks for the link.
