### ISSUE TITLE
Api Key problem

### ISSUE THREAD

**Issue by irnei84** [mevdschee/php-crud-api#933]
Hi !
I have a little problem with the API key authentication.

using this configuration in api.php :

```
'middlewares' => 'apiKeyAuth',
'apiKeyAuth.keys' => '02c042aa-c3c2-4d11-9dae-1a6e230ea95e'

```
but if i make a call with postman i recived a simple errorr 500 without information.
removing the configuration about middlewares and apiKey it works fine.

i'm not understand what i missing...

![image](https://user-images.githubusercontent.com/41480519/200114038-2d473181-be90-4dd8-a8e3-7603d1f50eab.png)

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue. Did you enable debug? Can you post what the response headers are?

**Comment by nik2208** [comment]
This library handles (in my experience) almost any error. Most of the times error 500 is due to syntax error.
Just make sure (before going on in debugging) that the customization function is correct in commas brackets an so on

**Comment by mevdschee** [comment]
Okay, please check the (PHP) error log of the server and post what it says in there.

**Comment by irnei84** [comment]
Ok i've found this thing into the log.
Sorry but i've only this log available, the api is hosted in a aruba wordpress host.

WARNING: [pool www.ostetricadelcuore.it] child 2168 said into stderr: "[10-Nov-2022 20:00:48 Europe/Rome] PHP Parse error: syntax error, unexpected ''middlewares'' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in /web/htdocs/www.ostetricadelcuore.it/home/_api/api.php on line 12378"

**Comment by mevdschee** [comment]
Can you share lines 12377-12379 of the file '/web/htdocs/www.ostetricadelcuore.it/home/_api/api.php' with us?

**Comment by irnei84** [comment]
![image](https://user-images.githubusercontent.com/41480519/201195557-aa8cd73c-8682-44a4-95cb-47e2fdfcf21a.png)


`    $config = new Config([
        'driver' => 'mysql',
        'address' => '89.46.111.15',
        'port' => '3306',
        'username' => 'Sql955622',
        'password' => '437e2t5p0l',
        'database' => 'Sql955622_5',
		'middlewares' => 'apiKeyAuth',
		'apiKeyAuth.keys' => '02c042aa-c3c2-4d11-9dae-1a6e230ea95e'
        'debug' => true
    ]);`

**Comment by irnei84** [comment]
Ok, i've found the problem.
a missing comma before debug...

**Comment by mevdschee** [comment]
I'm glad you found it! Enjoy the software.
