### ISSUE TITLE
Define multiple filters

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#938]
Hallo Maurits

Thanks for your quick reply. I can NOT reproduce it. Although I tested it several times before, I think I ran into a problem with make.com.

If you specify the filter parameter twice for different table columns it sends only the last parameter. Therefore I got all Exam Sets, but since I only waited for 1 Exam Set I considered this as an error. In fact I got only ExamSets of type Sample so the 2nd filter worked.  but the first defined one not. This confused me, sorry that I made you work.

The service offers the following option 

`By default, Make handles multiple values for the same url query string parameter key as arrays (e.g. [www.test.com?foo=bar&foo=bazwill](http://www.test.com/?foo=bar&foo=bazwill) be converted to [www.test.com?foo[0]=bar&foo[1]=baz](http://www.test.com/?foo[0]=bar&foo[1]=baz)). To disable this feature, activate this option.`

As I said when I turned it off only the second parameter comes with. I have it reported there, could be considered a BUG, right?
is there a way to process an array here?

Thanks rob

_Originally posted by @Kuhlig in https://github.com/mevdschee/php-crud-api/issues/937#issuecomment-1334960960_

**Comment by mevdschee** [comment]
>I have it reported there, could be considered a BUG, right?

No, both methods are valid, but PHP-CRUD-API needs the feature disabled.

>As I said when I turned it off only the second parameter comes with. 

This test case shows that both are taken into account:

https://github.com/mevdschee/php-crud-api/blob/main/tests/functional/001_records/057_filter_on_and.log

Can you help me reproduce the bug?

**Comment by Kuhlig** [comment]
HI Maurits I don't think you have a bug . make.com has one ! I can test if it is working the array an get back to you

**Comment by Kuhlig** [comment]
I think your tool is fine (and create!!!) 

I get the same response for both requestst

{{URL_API_DB}}records/exam_sets?filter**[0]**=uuid,eq,54dd6e8c-6d43-48a9-ad3d-a65339394199&filter**[1]**=type,eq,sample

{{URL_API_DB}}records/exam_sets?filter=uuid,eq,54dd6e8c-6d43-48a9-ad3d-a65339394199&filter=type,eq,sample

so i guess no BUG - good night rob

**Comment by mevdschee** [comment]
Hi Rob, That's good. Let me know if you run into new things. I'm happy to help you. Kind regards, Maurits
