### ISSUE TITLE
get result from view 

### ISSUE THREAD

**Issue by Kuhlig** [mevdschee/php-crud-api#939]
Hi 

i created a view

CREATE VIEW “exam_set_sample” AS select `sqms2`.`exam_sets`.`uuid` AS `id`, .... from `sqms2`.`exam_sets` where `sqms2`.`exam_sets`.`type` = 'sample'

but when i try to get the result I get 
{{URL_API_DB}}records/exam_set_sample

```
{
    "code": 1001,
    "message": "Table 'exam_set_sample' not found"
}

```
I renamed uuid to id - what else can i do?

thanks rob

**Comment by mevdschee** [comment]
Hi Rob, Here `tag_usage` is defined as view:

https://github.com/mevdschee/php-crud-api/blob/main/tests/fixtures/blog_mysql.sql

Here it is queried:

https://github.com/mevdschee/php-crud-api/blob/main/tests/functional/001_records/075_list_tag_usage.log

Maybe your configuration does not allow access to the view/table? 

In order for me to reproduce your problem you need to report the following things in a bug report:

- Structure dump in SQL (create statements)
- Sample records that are in the table (insert statements)
- PHP-CRUD-API configuration (all settings and handlers)
- URL that you are requesting (method + url + request body)

That allows me to reproduce the error. But more likely that will actually make you solve it for yourself.

Kindest regards, Maurits

**Comment by Kuhlig** [comment]
my create view was buggy

CREATE VIEW "_vSampleSetsList" AS
better
CREATE VIEW `_vSampleSetsList` AS

the first create created a view named '"_vSampleSetsList"' with " not Only '_vSampleSetsList' - but I was too tired to see it.

**Comment by mevdschee** [comment]
I'm glad you solved it. Enjoy the software! Kind regards, Maurits
