### ISSUE TITLE
json output correct?

### ISSUE THREAD

**Issue by PeterPlanlos** [mevdschee/php-crud-api#94]
hi, first of all thanks for your work!

i have a question/issue:
why my output ever start with the "tablename" ?
can i prevent this api doing this?
example of wrong out (i think wrong, all my applications want the json in other format)
wrong :(
###################
GET http://subdomain.url.com/api.php/posts?transform=1
OUTPUT:
{"posts":[{"userid":"1","id":"1","title":"test","body":"test"}]}
###################

correct :)
###################
GET http://subdomain.url.com/api.php/posts?transform=1
OUTPUT:
[
  {
    "userId": 1,
    "id": 1,
    "title": "test",
    "body": "test"
  }
]
###################

why on the "wrong" output the int values got "" ? <- its okay for me
why the table name is include in the json output? <- can i transform this somehow in the api call? 

thank you all reading this very much!

**Comment by mevdschee** [comment]
Hi Peter, You are not the first to request int to not have quotes, but there is no "one size fits all" solution as there is no match between database types and javascript types. Even an "int" as you call it is in Javascript actually a float.

**Comment by mevdschee** [comment]
As for the structure of the response of the "list" command, you may access that first node in the json in the result handler of the ajax call and essentially getting the same result. You can see this quite clear at the end of line 11 in the angular example here: 

https://github.com/mevdschee/php-crud-api/blob/master/examples/client_angular.html#L11

**Comment by mevdschee** [comment]
For the int issue see also #11

**Comment by mevdschee** [comment]
Closed due to inactivity.
