### ISSUE TITLE
financial support for php-crud-api?

### ISSUE THREAD

**Issue by Kuhlig** [mevdschee/php-crud-api#940]
Hello Maurits

how can I (we) support your project? I would like to donate something. I have enjoyed your excellent support many times. 
 
Please think about how I (we) can support you financially
* Github Sponsors? OR
* Patreon? OR
* ...

Or is there already a possibility that I have overlooked? 
Or do you just want to bill my organization for 5 hours of support? 
Where I can then question you for another 2 h? :-)

Please give me (us) a possibility!
THANKS rob

**Comment by mevdschee** [comment]
That's very kind of you. You may send a purchase order to my email address: maurits@vdschee.nl

**Comment by Kuhlig** [comment]
i will but i still suggest that you do at least Github Sponsors (or something esle) ...

**Comment by mevdschee** [comment]
Hi Rob, I played with that idea, but I'm sure that after the administration costs (book keeping) and taxes there will be (almost) nothing left.

Also, I'm way too busy playing AdventOfCode, see: https://github.com/mevdschee/AdventOfCode2022

Enjoy programming! Kindest regards, Maurits

**Comment by Kuhlig** [comment]
i just did - but i need it for a "verein" and not (yet) for one of my "real" companies ... I just try things out and then the real programmers take over ... so it's a kind of prototyping in my "free" time, which is rare ...

**Comment by Kuhlig** [comment]
**"After administrative costs (accounting) and taxes, there is (almost) nothing left."**

Try it for a year .... the accounting (list of income) should be managed by Github (I don't know, but I would expect that) - taxes Ouch, but they are not 100% :-) - So you may be surprised ...

**Comment by Kuhlig** [comment]
did you gt my mails? from ...@itemo.org?  please have a look in the spam folder - thanks rob
