### ISSUE TITLE
Add custom route

### ISSUE THREAD

**Issue by effe-dev** [mevdschee/php-crud-api#941]
Hello,
First of all i would like to thank for this script, it is really nice and help me a lot.

I need to understand how to create a custom Endpoint. I'm a newbie so it's not clear to me if i can do everything into the api.php 

At the moment the api replies into the url:
http://localhost/{folder-project}/api.php/records/{table-name}

I would like to drop the api.php and records and became 
http://localhost/{folder-project}/{table-name}

Sorry again if my question is so obviously.

**Comment by effe-dev** [comment]
Hi @mevdschee , thank you so much for your answer.
Actually, i've tried to modify the htaccess but nothing has changed.
Iniatially the file was into a folder, now even if i put into the root , it doesn't work. Of course i can modify htaccess.
So the new configuration the url is:
https://mysite.com/api.php/records/{table-name}
And after modify the .htaccess file should be:
https://mysite.com/records/{table-name}

When i try to reach the last url, the webserver reply as:
No input file specified.

The .htaccess content is the same as you've suggested:
`RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_URI} !api\.php [NC]
RewriteRule ^([^/]+)(.*)?$ api.php/$1$2   [L]`

Maybe i'm missing something?

Thank you so much,

**Comment by mevdschee** [comment]
>Maybe i'm missing something?

Are you running Nginx or Apache as webserver?

**Comment by effe-dev** [comment]
Hi Maurits,
It is an Apache webserver.

I've tried this and it seems to work:

```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . api.php
```

I have to test it with filters,etc but in this way api.php has been dropped. These lines have sense for you?

Finally, may i ask you when it could be useful to use the custom controller, the custom controller can be used with the file api.php or need more external settings.

The file is really useful. 
Many thanks.

**Comment by mevdschee** [comment]
>These lines have sense for you?

Yeah.. looks good to me..

>when it could be useful to use the custom controller, the custom controller can be used with the file api.php or need more external settings.

I guess you can start using the custom controller by defining it in the settings (using "customControllers") and when you should get it working without more external settings.

**Comment by nik2208** [comment]
this code 
```
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_URI} !api\.php [NC]
RewriteRule ^([^/]+)(.*)?$ api.php/$1$2   [L]
```
does the following: if the requested root does not contain api.php, it adds api.php at the end of the request uri, before routes and parameters, and sends it to the server.

Now you want not only to mask api.php, but also records, so this:
```
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_URI} !api\.php/records [NC]
RewriteRule ^([^/]+)(.*)?$ api.php/records/$1$2   [L]
```
should do the trick.

**Comment by mevdschee** [comment]
Thank you @nik2208, that is a great example.

**Comment by effe-dev** [comment]
@nik2208 Thank you so much! i gonna try it. :)
