### ISSUE TITLE
PouchDB Replication

### ISSUE THREAD

**Issue by scriptPilot** [mevdschee/php-crud-api#942]
Hello Maurits, thanks for this great API, very helpful!

I am wondering if there is a connector to [PouchDB](https://pouchdb.com), to keep the local document-based database in sync with a MySQL table. 

Details: https://pouchdb.com/guides/replication.html

**Comment by mevdschee** [comment]
>I am wondering if there is a connector to [PouchDB](https://pouchdb.com/)

No, I've never heard of PouchDB, so there are no plans to support it either.

**Comment by scriptPilot** [comment]
Ok, thanks for the response.

**Comment by mevdschee** [comment]
It also seems specific to CouchDB one the server side and JavaScript on the client side, so I also don't see how it would 
"fit-in" with the current code. Or am I missing something?

**Comment by scriptPilot** [comment]
Well, it's more about a JS library to do the sync between both.
I thought if there is such a library maybe you would know it :-)

**Comment by apps-caraga** [comment]
Pouchdb is a NoSQL or non-relational database and it does not have a fixed schema while api.php is designed around relational databases. 

Still, since Pouchdb data are stored as JSON documents and with JSON support from most RDBMS, it may be possible someone (not me 😂) can  create something that bridges the two.

**Comment by mevdschee** [comment]
>Well, it's more about a JS library to do the sync between both.

I read:

> Typical relational databases such as MySQL are CP, which means they are consistent and tolerant to node partitions, at the expense of availability. CouchDB is an AP database, meaning that it's Partition-Tolerant, every node is Available at all times, but it's only eventually Consistent.

If PouchDB is a client side replication of a CouchDB database (AP), then syncing with MySQL (CP) doesn't make sense to me as you get neither AP nor CP, or am I wrong?

> I thought if there is such a library maybe you would know it :-)

Probably would and I don't know about it.

>it may be possible someone (not me) can create something that bridges the two.

True and someone (not me either) might.

**Comment by apps-caraga** [comment]
Couchdb has its own [replication protocol](https://docs.couchdb.org/en/3.2.2-docs/replication/protocol.html) and a [REST API](https://docs.couchdb.org/en/3.2.2-docs/api/index.html#api). It would be better and straightforward to use that API for replication instead of implementing it here in api.php

**Comment by mevdschee** [comment]
>It would be better and straightforward to use that API for replication instead of implementing it here in api.php

Thank you for your advice. I'm closing the issue.

**Comment by scriptPilot** [comment]
If anyone opens this thread ... as a starting point I've created some Vue bindings for this great API:

https://github.com/scriptPilot/vueuse/

**Comment by mevdschee** [comment]
>If anyone opens this thread ... as a starting point I've created some Vue bindings for this great API:

Thank you. I've added a link to the README, so everybody can easily find your attribution.
