### ISSUE TITLE
Transactions, commit and rollback

### ISSUE THREAD

**Issue by nik2208** [mevdschee/php-crud-api#943]
As per the docs "Complex writes (transactions) are not supported".

Is there any way to work around this, handling the start and the end of the transaction client-side?

**Comment by nik2208** [comment]
I mean, placing the transaction logic client-side sending "manually" start commit and rollback

**Comment by mevdschee** [comment]
>Is there any way to work around this,

There shouldn't be a way for users to start a transaction and not immediately committing or rolling back.

>However, if you did BEGIN TRAN then prompted for user input, your legs need breaking...

I wouldn't put it that strong. See: https://stackoverflow.com/questions/6334869/does-a-transaction-block-reduce-performance-in-sql-server

**Comment by nik2208** [comment]
what I actually need is to assign a code to a specific user, being sure that that specific code is still available when, after retrieving it (the first available code in an array of codes), I alter its state from available to assigned (being sure that no user has assigned it to himself in the meanwhile). For this reason a transaction and the possibility to rollback would be the simplest solution (actually no other solutions come to my mind to be 100% sure that the assignment process is started simultaneously by more than one user).
I could add the code another state like "busy" during the whole process but I feel like I would find myself in the same situation.
Any suggestion about that?

**Comment by mevdschee** [comment]
> Any suggestion about that?

Use a lock. A lock can be implemented by an update with a a where condition while checking for affected rows.

    UPDATE `codes` SET `user_id` = ? WHERE `id` = ? AND `user_id` IS NULL;

If the number of affected rows (changed rows) > 0 then you acquired the lock, otherwise you need to retry.

**Comment by nik2208** [comment]
thank u very much I'll give it a try. I imagine it creates a bound with the user session acquiring the lock.. is it?
Will the lock work using your library?

**Comment by mevdschee** [comment]
> thank u very much I'll give it a try. 

I'm happy to help you out if you get stuck.

>I imagine it creates a bound with the user session acquiring the lock.. is it?

No, it has no relation with the session.

> Will the lock work using your library?

Yes, it will work.
