### ISSUE TITLE
How can I join without adapting table and column names?

### ISSUE THREAD

**Issue by scriptPilot** [mevdschee/php-crud-api#946]
Hey, today I have tables and columns which are not named ideally as shown in the **join** example.
How can I for example join:

table: cities (id, name, country_code)
table: countries (id, name)

to:

````
[
  {
    id: 1,
    name: 'City Name',
    country_code: {
      {
        id: 1,
        name: 'Country Name
      }
    }
  }
]
````

**Comment by scriptPilot** [comment]
Ok - I think the mapping must be applied properly before:
https://github.com/mevdschee/php-crud-api#mapping-names-for-legacy-systems

**Comment by scriptPilot** [comment]
Well, even with basic layout I do not get the joins to work ... do you see any mistake?

<img width="474" alt="Bildschirmfoto 2023-01-04 um 15 24 44" src="https://user-images.githubusercontent.com/19615586/210576669-43b5d3f4-d2a9-496e-989a-bb9970639785.png">
<img width="459" alt="Bildschirmfoto 2023-01-04 um 15 25 01" src="https://user-images.githubusercontent.com/19615586/210576673-cd3a7e87-67cc-408b-a8c1-f41b978b13e9.png">
<img width="456" alt="Bildschirmfoto 2023-01-04 um 15 25 23" src="https://user-images.githubusercontent.com/19615586/210576675-09915965-814e-49ff-915b-11c4edd54f1e.png">
<img width="480" alt="Bildschirmfoto 2023-01-04 um 15 25 28" src="https://user-images.githubusercontent.com/19615586/210576678-02eca7e5-d99d-44ca-b014-3b568c4547f4.png">
<img width="505" alt="Bildschirmfoto 2023-01-04 um 15 26 15" src="https://user-images.githubusercontent.com/19615586/210576683-f3c72efb-913c-4589-8b4a-73ab4f1315df.png">

**Comment by mevdschee** [comment]
Glad you got it working. Enjoy the software!

**Comment by scriptPilot** [comment]
Very well designed API 👍

**Comment by mevdschee** [comment]
Thank you, your nice words mean a lot to me.
