### ISSUE TITLE
Strange issue on shared-hosting with PHP 8.0

### ISSUE THREAD

**Issue by hopeter1018** [mevdschee/php-crud-api#947]
Hello and thanks for the great project!

Sorry for my poor english.

I am facing a strange issue, the api sometimes works fine but sometimes it shows the following:

Tqdev\PhpCrudApi\Column\Reflection\ReflectedTable::__construct(): Argument #2 ($realName) must be of type string, null given, called in /home/salesmgt.whhauto.com/public_html/api/api.include.php on line 4085

**Comment by mevdschee** [comment]
Maybe you can exclude that table from the API and thus from the reflection using for instance the "tables" config parameter?
