### ISSUE TITLE
Class "Tqdev\PhpCrudApi\Config" not found

### ISSUE THREAD

**Issue by baberuth22** [mevdschee/php-crud-api#949]
I'm using laravel 9.46.0 on a Mac with PHP 8.0.

I follow the instructions in [the tutorial](https://tqdev.com/2019-automatic-rest-api-laravel).

`php composer.phar require symfony/psr-http-message-bridge
php composer.phar require laminas/laminas-diactoros
php composer.phar require mevdschee/php-crud-api`

Then add this to routes.php

```
<?php

use Psr\Http\Message\ServerRequestInterface;
use Tqdev\PhpCrudApi\Api;
use Tqdev\PhpCrudApi\Config;

Route::any('/{any}', function (ServerRequestInterface $request) {
    $config = new Config([
        'username' => 'php-crud-api',
        'password' => 'php-crud-api',
        'database' => 'php-crud-api',
        'basePath' => '/api',
    ]);
    $api = new Api($config);
    $response = $api->handle($request);
    return $response;
})->where('any', '.*');
```

But I end up with the error:

**Class "Tqdev\PhpCrudApi\Config" not found
~/plugins/bryan/questions/routes.php line 17**

Can anyone point me in the right direction?  Thanks!

**Comment by baberuth22** [comment]
Got it. 2 Configs.

Client is referenced by 

use Tqdev\PhpCrudApi\Config\Config;

**Comment by mevdschee** [comment]
I'm glad you resolved the issue. Feel free to follow-up with questions on this topic or open a new issue for another topic! Enjoy the software! Kind regards, Maurits

**Comment by atifamin** [comment]
> Got it. 2 Configs.
> 
> Config is referenced by
> 
> use Tqdev\PhpCrudApi\Config\Config;

The last line saved my day. Thank you!
