### ISSUE TITLE
str_replace in Authorization Middleware issue with php8.2

### ISSUE THREAD

**Issue by kdoe13** [mevdschee/php-crud-api#951]
I'm using php 8.2 with MAMP, and I'm running into a problem with a line in the Authorization Middleware that seems to have to do with the php version. 

https://github.com/mevdschee/php-crud-api/blob/e07f7e7de6187f571991f83984fe8a63cdabc44e/src/Tqdev/PhpCrudApi/Middleware/AuthorizationMiddleware.php#L69

str_replace throws and error that the 3rd variable..in this case $query can't be empty. On a simple query like records/users...it is blank, and so therefore won't work.

<img width="277" alt="Screenshot 2023-01-22 at 10 00 20 PM" src="https://user-images.githubusercontent.com/1375401/213963753-3c82eaca-a0ca-48d9-8856-17d2ee10617c.png">

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue. Can you share the exact error message? I think it requires a string instead of a null on the third parameter, but maybe you can confirm that? Kind regards, Maurits

**Comment by kdoe13** [comment]
<b>Correct, I fixed it by adding:</b>
if (!$query) $query = '';

<b>Here is the error message:</b>
PHP Deprecated:  str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /Users/karldoege/Sites/dev-crud-api/vendor/mevdschee/php-crud-api/src/Tqdev/PhpCrudApi/Middleware/AuthorizationMiddleware.php on line 70

**Comment by mevdschee** [comment]
Released in v2.14.17
