### ISSUE TITLE
Problems to use custom users table name

### ISSUE THREAD

**Issue by chattago2002** [mevdschee/php-crud-api#952]
Hi.

I love your repository and I'm using it in many different projects.
For the last one I downloaded last version [v2.14.16](https://github.com/mevdschee/php-crud-api/releases/tag/v2.14.16) but I have problems with my custom table name for apiKeyDbAuth.usersTable and dbAuth.usersTable. I want to use my custom table name instead of "users".
In a older version (I think is [v2.14.6](https://github.com/mevdschee/php-crud-api/releases/tag/v2.14.6) ) there is no problem while in the last one I have many problems (i.e. sometimes debug says error 9999) and it seems to work fine when I rename the table in "users".

Am I wrong in something?

**Comment by mevdschee** [comment]
Hi, thank you for creating this issue. I'm not aware of any breaking changes. Can you share your config? Ideally a minimal example with config and request that fails.

**Comment by chattago2002** [comment]
Hi.
Here is my config:
`$config = new Config([
    'driver' => 'mysql',
    'address' => 'localhost',
    'port' => '3306',
    'username' => 'db_user',
    'password' => 'db_pwd',
    'database' => 'db_name',
    'middlewares' => 'cors, dbAuth, apiKeyDbAuth, authorization',
    'debug' => true,
    'apiKeyDbAuth.mode' => 'required',
    'apiKeyDbAuth.header' => 'X-API-Key',
    'apiKeyDbAuth.usersTable' => 'utente',
    'apiKeyDbAuth.apiKeyColumn' => 'api_key',
    'cors.allowedOrigins' => 'http://localhost:3000, https://mydomain.com',
    'dbAuth.mode' => 'optional',
    'dbAuth.usersTable' => 'utenti_attivi',
    'dbAuth.usernameColumn' => 'email',
    'dbAuth.passwordColumn' => 'hashed_pwd',
    'dbAuth.usernameFormField' => 'username',
    'dbAuth.passwordFormField' => 'password',
    'dbAuth.registerUser' => true,
    'dbAuth.passwordLength' => '8',
    'authorization.recordHandler' => function ($operation, $tableName) {
        if ($_SESSION['apiUser']['id_ruolo'] != 1) {
            if ($tableName === 'utente') {
                return ($tableName == 'utente') ? 'filter=id,eq,' . $_SESSION['apiUser']['id'] : '';
            }
            return $tableName;
        } else {
            return $tableName;
        }
    },
    'authorization.tableHandler' => function ($operation, $tableName) {
        if ($_SESSION['apiUser']['id_ruolo'] != 1) {
            return ($tableName == 'utente') ? 'filter=id,eq,' . $_SESSION['apiUser']['id'] : $tableName;
        } else {
            return $tableName;
        }
    },
    'cors.allowHeaders' => 'X-Requested-With, Content-Type, Accept, Authorization, X-Authorization, X-Custom-Header, X-API-Key',
]);
`.

The request fails because the system try to query on 'users' table that not exists.

**Comment by mevdschee** [comment]
I think you should also set the 'loginTable', but I agree that is should have fallen back to 'usersTable'. I'll make a bugfix.

**Comment by mevdschee** [comment]
Released in [v2.14.18](https://github.com/mevdschee/php-crud-api/releases/tag/v2.14.18)

**Comment by chattago2002** [comment]
Thank you very much.
