### ISSUE TITLE
401 Unauthorized after successful login using Vue 3

### ISSUE THREAD

**Issue by nikosfa** [mevdschee/php-crud-api#953]
Dear Maurits, hello! 

I have used php-crud-api on several projects, for a couple of years now, mainly in combination with ios & android native apps, and I'm very thankful for you creating it. It just works like a charm! It saved me a lot of time and effort.

Now, I'm working on a new web app project using the Vue 3 for the first time and using the php-crud-api on the backend. Also, for the first time I'm trying to use the dbAuth middleware in order to have better security.

In that regard I have an issue regarding the session cookie:

After successful login, the consequent call returns response 401 Unauthorized. I have already seen all the mentions of he similar issues on the net and all the respective solutions, but it seems that no one works for me.

1) I have handled **cors** through the api's cors middleware. There is  no **cors** setting on the Apache side. 
2) I have enabled authorization middleware
3) I have enabled dbAuth middleware  

Please check the screenshot bellow:

**api.php:**

![εικόνα](https://user-images.githubusercontent.com/17946863/214662602-64df51e8-5661-4f27-a387-c473548dd1be.png)

**Successful dbAuth Authentication:**

![εικόνα](https://user-images.githubusercontent.com/17946863/214668191-9cb3296f-4819-4447-bf52-6ad00fd7e4f6.png)

Subsequent call failed call:

![εικόνα](https://user-images.githubusercontent.com/17946863/214668001-5ecfc997-b9c2-4d06-9393-78971c065ffb.png)

client's Vue 3 js login routine:

![εικόνα](https://user-images.githubusercontent.com/17946863/214668374-abed49c8-8fc4-4114-9cb6-abdacf7b7632.png)

client's Vue 3 js subsequent get resource routine:

![εικόνα](https://user-images.githubusercontent.com/17946863/214669476-1b97cdca-f20a-4e1e-a366-626f8ef0ab51.png)

My only observation is that **set-cookie** in subsequent call's response **is different** that in the login's.

What I'm doing wrong?

**Comment by nik2208** [comment]
did u set "withCredentials" equal to true in the http request option obj?

**Comment by mevdschee** [comment]
>why "cors->allow-credentials"?

To set the right CORS headers.

>did u set "withCredentials" equal to true in the http request option obj?

With Fetch you need to use "credentials: 'include'" instead, as you did.

I see no immediate problem with your code.

**Comment by nik2208** [comment]
in my case dbAuth has always worked  without specifying cors->allow-credentials..
@nikosfa does it work if u remove dbAuth->required ?

**Comment by mevdschee** [comment]
How about setting the "origin" to the actual url the request is made from (instead of the comma separated list)? Can you try that?

**Comment by nikosfa** [comment]
Guys, 

Thank you very much for your responses.

"Miraculously" it works now, without any change of the above code. After login the consequent call is also succesfull

I can only think about some kind of caching being involved on the server side. It may be that I needed Apache/FPM restart after change in .htacces  (but normally it should not be the case...).

Sorry for bothering you, but for couple of days it was impossible for me to find a solution for the problem.

**Comment by nikosfa** [comment]
The problem persists, sorry from previous now deleted post, I just have remarked 'dbAuth' =>'Required' and just forgot that, so it worked as default 'Optional'...

I will try the above mentioned suggestions and inform you.

**Comment by nikosfa** [comment]
- So we have same behavior when leaving only one origin url client and server side like 'cors.allowedOrigins' => 'http://127.0.0.1:8080'
- For every single call I receive different session id cookie, either with dbAuth required either even with optional
- I observe also that the origin protocol is http while request destination is https. I dont know if this forces new session cookie?
- I observe that in console tab there is an error for every failed call referred by XHR like bellow:
![εικόνα](https://user-images.githubusercontent.com/17946863/214948307-68ab685c-a0f8-40e8-9a87-25cb61274f31.png)
 - Here are the 3 last calls
![εικόνα](https://user-images.githubusercontent.com/17946863/214947867-71743370-9aa6-4a4e-af77-d61dae8af695.png)

**Comment by nikosfa** [comment]
Using http for both sides does not helps...

**Comment by nik2208** [comment]
does it work if u remove authorization.tablehandler implementation?

**Comment by nikosfa** [comment]
> does it work if u remove authorization.tablehandler implementation?

No, it doesn't unfortunately. nothing changes if I remove the Authorization middleware.

**Comment by nikosfa** [comment]
IMHO, the main issue is that server on every hit provides new session id.

**Comment by nik2208** [comment]
it is the most reasonable reason..
have u checked the session duration been set in php?

**Comment by nikosfa** [comment]
Here are the main php settings:

![εικόνα](https://user-images.githubusercontent.com/17946863/215045764-1738cefb-2f86-47d5-821c-d53a31cd9a9f.png)

**Comment by nikosfa** [comment]
Here are the cookie response screenshots:

![εικόνα](https://user-images.githubusercontent.com/17946863/215285637-f4c46924-53d4-4af0-ba3f-b62efcc422a4.png)


![εικόνα](https://user-images.githubusercontent.com/17946863/215285617-c4267917-e319-43da-bcdd-f7b604a1d714.png)

**Comment by nikosfa** [comment]
Here are the cookie responses:

![εικόνα](https://user-images.githubusercontent.com/17946863/215285772-4bb7ee4d-77be-4bdf-b10d-2ecb30f0db22.png)

![εικόνα](https://user-images.githubusercontent.com/17946863/215285845-a10d0613-e554-4e0d-a988-c8ed492b490c.png)

**Comment by mevdschee** [comment]
First request should send a "Set-Cookie" header in the response. The second request should send the Cookie value in the request. Can you verify that this happens?

**Comment by nikosfa** [comment]
I believe that I follow these guidelines
   
**These are the options set by the first (login call):**
![εικόνα](https://user-images.githubusercontent.com/17946863/215287914-4a6c97f6-1e42-4774-b8c1-3b9729de78f7.png)

**And bellow are from the subsequent call:**
![εικόνα](https://user-images.githubusercontent.com/17946863/215287876-fe633733-7489-4660-8771-2e0e2ab21401.png)

**Maybe my issue is similar as the below, only that I have local development machine with http (not proxy) protocol while server works via https (I tried to set on both machines the http protocol, but this didn't solve the problem). I do not know how to overcome mismatching http/https protocol on local/remote machines.** 

![εικόνα](https://user-images.githubusercontent.com/17946863/215288098-b2f5d856-c40c-4f51-9d66-d2b7f98828d2.png)

**Comment by nikosfa** [comment]
Consulting the following link https://stackoverflow.com/questions/45807049/how-to-run-vue-js-dev-serve-with-https I have enabled the https protocol on local host as bellow:

![εικόνα](https://user-images.githubusercontent.com/17946863/215551307-ba332d65-6924-44c4-a3c7-6e3a08e3944e.png)

But now I can't even log in ...

![εικόνα](https://user-images.githubusercontent.com/17946863/215551731-a83e2a4f-dd59-415b-8e61-f16f601611c2.png)

I have changed the **'cors.allowedOrigins' => 'http://localhost:8080'** in the API and on the client as well

**Comment by nikosfa** [comment]
Following this link https://stackoverflow.com/questions/45807049/how-to-run-vue-js-dev-serve-with-https I have managed to run   localhost over https , but result remains the same: I receive the 401 Unauthorized after login

**Comment by nik2208** [comment]
did u try to use a browser cors extension to verify that actually it is a cors problem?

**Comment by nikosfa** [comment]
> did u try to use a browser cors extension to verify that actually it is a cors problem?

Yes I did the CORS Everywhere for Firefox. When enabled the problem remains, with exact same behavior. 

Did you know if there is a way to enable log on the server side, in order to catch some more information.

Especially this part of the code which handles the sessions/cookies

`// file: src/Tqdev/PhpCrudApi/Middleware/DbAuthMiddleware.php
namespace Tqdev\PhpCrudApi\Middleware {

    use Psr\Http\Message\ResponseInterface;
    use Psr\Http\Message\ServerRequestInterface;
    use Psr\Http\Server\RequestHandlerInterface;
    use Tqdev\PhpCrudApi\Column\ReflectionService;
    use Tqdev\PhpCrudApi\Config\Config;
    use Tqdev\PhpCrudApi\Controller\Responder;
    use Tqdev\PhpCrudApi\Database\GenericDB;
    use Tqdev\PhpCrudApi\Middleware\Base\Middleware;
    use Tqdev\PhpCrudApi\Middleware\Router\Router;
    use Tqdev\PhpCrudApi\Record\Condition\ColumnCondition;
    use Tqdev\PhpCrudApi\Record\ErrorCode;
    use Tqdev\PhpCrudApi\Record\OrderingInfo;
    use Tqdev\PhpCrudApi\RequestUtils;

    class DbAuthMiddleware extends Middleware
    {
        private $reflection;
        private $db;
        private $ordering;

        public function __construct(Router $router, Responder $responder, Config $config, string $middleware, ReflectionService $reflection, GenericDB $db)
        {
            parent::__construct($router, $responder, $config, $middleware);
            $this->reflection = $reflection;
            $this->db = $db;
            $this->ordering = new OrderingInfo();
        }

        public function process(ServerRequestInterface $request, RequestHandlerInterface $next): ResponseInterface
        {
            if (session_status() == PHP_SESSION_NONE) {
                if (!headers_sent()) {
                    $sessionName = $this->getProperty('sessionName', '');
                    if ($sessionName) {
                        session_name($sessionName);
                    }
                    if (!ini_get('session.cookie_samesite')) {
                        ini_set('session.cookie_samesite', 'Lax');
                    }
                    if (!ini_get('session.cookie_httponly')) {
                        ini_set('session.cookie_httponly', 1);
                    }
                    if (!ini_get('session.cookie_secure') && isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') {
                        ini_set('session.cookie_secure', 1);
                    }
                    session_start();
                }
            }
            $path = RequestUtils::getPathSegment($request, 1);
            $method = $request->getMethod();
            if ($method == 'POST' && in_array($path, ['login', 'register', 'password'])) {
                $body = $request->getParsedBody();
                $usernameFormFieldName = $this->getProperty('usernameFormField', 'username');
                $passwordFormFieldName = $this->getProperty('passwordFormField', 'password');
                $newPasswordFormFieldName = $this->getProperty('newPasswordFormField', 'newPassword');
                $username = isset($body->$usernameFormFieldName) ? $body->$usernameFormFieldName : '';
                $password = isset($body->$passwordFormFieldName) ? $body->$passwordFormFieldName : '';
                $newPassword = isset($body->$newPasswordFormFieldName) ? $body->$newPasswordFormFieldName : '';
                if ($path === 'login')
                    $tableName = $this->getProperty('loginTable', 'users');    //add separate property for login as this could be a view joining users table to other table such as roles, details etc. At a minimum, the view output should include the $usernameColumn and $passwordColumn
                else
                    $tableName = $this->getProperty('usersTable', 'users');
                $table = $this->reflection->getTable($tableName);
                $usernameColumnName = $this->getProperty('usernameColumn', 'username');
                $usernameColumn = $table->getColumn($usernameColumnName);
                $passwordColumnName = $this->getProperty('passwordColumn', 'password');
                $passwordLength = $this->getProperty('passwordLength', '12');
                $pkName = $table->getPk()->getName();
                $registerUser = $this->getProperty('registerUser', '');
                $loginAfterRegistration = $this->getProperty('loginAfterRegistration', '');
                $condition = new ColumnCondition($usernameColumn, 'eq', $username);
                $returnedColumns = $this->getProperty('returnedColumns', '');
                if (!$returnedColumns) {
                    $columnNames = $table->getColumnNames();
                } else {
                    $columnNames = array_map('trim', explode(',', $returnedColumns));
                    $columnNames[] = $passwordColumnName;
                    $columnNames = array_values(array_unique($columnNames));
                }
                $columnOrdering = $this->ordering->getDefaultColumnOrdering($table);
                if ($path == 'register') {
                    if (!$registerUser) {
                        return $this->responder->error(ErrorCode::AUTHENTICATION_FAILED, $username);
                    }
                    if (strlen(trim($username)) == 0) {
                        return $this->responder->error(ErrorCode::USERNAME_EMPTY, $username);
                    }
                    if (strlen($password) < $passwordLength) {
                        return $this->responder->error(ErrorCode::PASSWORD_TOO_SHORT, $passwordLength);
                    }
                    $users = $this->db->selectAll($table, $columnNames, $condition, $columnOrdering, 0, 1);
                    if (!empty($users)) {
                        return $this->responder->error(ErrorCode::USER_ALREADY_EXIST, $username);
                    }
                    $data = json_decode($registerUser, true);
                    $data = is_array($data) ? $data : [];
                    $data[$usernameColumnName] = $username;
                    $data[$passwordColumnName] = password_hash($password, PASSWORD_DEFAULT);
                    $this->db->createSingle($table, $data);
                    $users = $this->db->selectAll($table, $columnNames, $condition, $columnOrdering, 0, 1);
                    foreach ($users as $user) {
                        if ($loginAfterRegistration) {
                            if (!headers_sent()) {
                                session_regenerate_id(true);
                            }
                            unset($user[$passwordColumnName]);
                            $_SESSION['user'] = $user;
                            return $this->responder->success($user);
                        } else {
                            unset($user[$passwordColumnName]);
                            return $this->responder->success($user);
                        }
                    }
                    return $this->responder->error(ErrorCode::AUTHENTICATION_FAILED, $username);
                }
                if ($path == 'login') {
                    $users = $this->db->selectAll($table, $columnNames, $condition, $columnOrdering, 0, 1);
                    foreach ($users as $user) {
                        if (password_verify($password, $user[$passwordColumnName]) == 1) {
                            if (!headers_sent()) {
                                session_regenerate_id(true);
                            }
                            unset($user[$passwordColumnName]);
                            $_SESSION['user'] = $user;
                            return $this->responder->success($user);
                        }
                    }
                    return $this->responder->error(ErrorCode::AUTHENTICATION_FAILED, $username);
                }
                if ($path == 'password') {
                    if ($username != ($_SESSION['user'][$usernameColumnName] ?? '')) {
                        return $this->responder->error(ErrorCode::AUTHENTICATION_FAILED, $username);
                    }
                    if (strlen($newPassword) < $passwordLength) {
                        return $this->responder->error(ErrorCode::PASSWORD_TOO_SHORT, $passwordLength);
                    }
                    $userColumns = $columnNames;
                    if (!in_array($pkName, $columnNames)) {
                        array_push($userColumns, $pkName);
                    }
                    $users = $this->db->selectAll($table, $userColumns, $condition, $columnOrdering, 0, 1);
                    foreach ($users as $user) {
                        if (password_verify($password, $user[$passwordColumnName]) == 1) {
                            if (!headers_sent()) {
                                session_regenerate_id(true);
                            }
                            $data = [$passwordColumnName => password_hash($newPassword, PASSWORD_DEFAULT)];
                            $this->db->updateSingle($table, $data, $user[$pkName]);
                            unset($user[$passwordColumnName]);
                            if (!in_array($pkName, $columnNames)) {
                                unset($user[$pkName]);
                            }
                            return $this->responder->success($user);
                        }
                    }
                    return $this->responder->error(ErrorCode::AUTHENTICATION_FAILED, $username);
                }
            }
            if ($method == 'POST' && $path == 'logout') {
                if (isset($_SESSION['user'])) {
                    $user = $_SESSION['user'];
                    unset($_SESSION['user']);
                    if (session_status() != PHP_SESSION_NONE) {
                        session_destroy();
                    }
                    return $this->responder->success($user);
                }
                return $this->responder->error(ErrorCode::AUTHENTICATION_REQUIRED, '');
            }
            if ($method == 'GET' && $path == 'me') {
                if (isset($_SESSION['user'])) {
                    return $this->responder->success($_SESSION['user']);
                }
                return $this->responder->error(ErrorCode::AUTHENTICATION_REQUIRED, '');
            }
            if (!isset($_SESSION['user']) || !$_SESSION['user']) {
                $authenticationMode = $this->getProperty('mode', 'required');
                if ($authenticationMode == 'required') {
                    return $this->responder->error(ErrorCode::AUTHENTICATION_REQUIRED, '');
                }
            }
            return $next->handle($request);
        }
    }
}`

**Comment by nikosfa** [comment]
It seems like that the process goes through this piece of code on every client request and validates as PHP_SESSION_NONE, so it sets again all the parameters starting the new session as well:

`                
if (session_status() == PHP_SESSION_NONE) {
            if (!headers_sent()) {
                $sessionName = $this->getProperty('sessionName', '');
                if ($sessionName) {
                    session_name($sessionName);
                }
                if (!ini_get('session.cookie_samesite')) {
                    ini_set('session.cookie_samesite', 'Lax');
                }
                if (!ini_get('session.cookie_httponly')) {
                    ini_set('session.cookie_httponly', 1);
                }
                if (!ini_get('session.cookie_secure') && isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off') {
                    ini_set('session.cookie_secure', 1);
                }
                session_start();
            }
        }
`

**Comment by nik2208** [comment]
could u try with curl?

**Comment by nikosfa** [comment]
What do you mean? To do a client authentication using the curl from the command line instead of js/browser authentication? Maybe you have some working example for php-crud-api?

**Comment by nik2208** [comment]
Here in the issue section u should be able to find something

**Comment by nik2208** [comment]
you should be able to login with a post receiving the cookie in the response, copy the cookie and than
`curl -v --cookie "cookieName=Val" /end/point/url`

**Comment by nikosfa** [comment]
There is some progress....
When using the **session cookie registered upon login** and curl as you described above **it works**!

**Comment by nik2208** [comment]
in the consequent request you make upon login, you should see in the headers the received cookie you are now sending: if there is no cookie, the library will generate a new one and u wont (as it is) be able to make any further authorized call

**Comment by nik2208** [comment]
> in the consequent request you make upon login, you should see in the headers the received cookie you are now sending: if there is no cookie, the library will generate a new one and u wont (as it is) be able to make any further authorized call

in fact **in the third image u sent here there is no session cookie set** in the request header while it should, indeed.

try to add manually the cookie in the cookie tab of broswer and resend the request, U will see it will work.

**Comment by nik2208** [comment]
di u try to remove `localhost:8080` from origin?

**Comment by nikosfa** [comment]
**Well, it finally worked!**

So now, after login every consecutive Fetch is Authenticated.

I did try every possible combination of all parameters server and client side and nothing helped, but what helped me is when I changed the session.cookie_samesite to 'none'. Please check the screenshot bellow:

![εικόνα](https://user-images.githubusercontent.com/17946863/216426424-a551c9fb-0cab-4090-925f-0d0004b1fd20.png)

Now, I'm not sure if this is correct configuration, but changing from Lax -> None, magically helped me.

I followed this post to figure it out: https://stackoverflow.com/a/67001424/13184820

**Could you confirm that this is the correct way to go or maybe it is possible to do something similar without hacking the API code?**

**Comment by nik2208** [comment]
This is actually a development solution, once u get to production (and u will not have cross site issues) u'd better put the config back to lax. The ini parameter session.cookie_samesite if I'm not mistaken should be configurable in the config section (even if - still - not documented)

**Comment by nik2208** [comment]
Anyway I had the same issue but I had the browsers' cors error feedback to help me investigate. What's strange here is that u had no cors errors

**Comment by nik2208** [comment]
> di u try to remove `localhost:8080` from origin?

DD u try this (leave only 127.0.0.1) before setting samesite setting to none?

**Comment by nik2208** [comment]
Have a look here #830

**Comment by nikosfa** [comment]
> > di u try to remove `localhost:8080` from origin?
> 
> DD u try this (leave only 127.0.0.1) before setting samesite setting to none?

Sorry for late reply nik. I was out of the office. Unfortunately no luck. Changing origin to 127.0.0.1 and reverting samesite to Lax, made the site inaccessible (401).

Thank you very much for your help.

I will develop with none flag and after deploy change it to lax. It would be nice if it could be somehow parametrized.

Best regards

**Comment by nik2208** [comment]
sorry for my late responce..now.. 
it is already parametrized, u can see it from the code. the docs haven't been updated but if I'm not mistaken the parameter is already there

**Comment by mevdschee** [comment]
>it is already parametrized, u can see it from the code

Not that I'm aware of.. unless you mean that you can just set it in `php.ini`, which is indeed true.

**Comment by mevdschee** [comment]
I'm closing this issue as I wouldn't know how to detect the 'none' case and the setting is configurable as-is. If you feel detection for the samesite 'none' case should be added, please open a new issue.
