### ISSUE TITLE
How to specify join column in tree ql

### ISSUE THREAD

**Issue by aszenz** [mevdschee/php-crud-api#954]
One table can relate to another table via two different columns. 

Example:
Post - createdByUser, updatedByUser

How would i specify getting the created user only via join, is it supported

**Comment by mevdschee** [comment]
> is it supported

No.. both will be joined by specifying a join with User

**Comment by mevdschee** [comment]
Does that answer your question? Do you have any further questions?

**Comment by aszenz** [comment]
> Does that answer your question? Do you have any further questions?

So joining is always using tables names. 

Is there any difference between
 `join=foo,bar` and
 `join=foo&join=bar`

How nested joins work. Does it join all the columns linked to the tables in the join clause.

**Comment by mevdschee** [comment]
>Is there any difference between join=foo,bar and join=foo&join=bar

Yes, the first joins the table with foo and joins foo with bar and the second joins the table with both foo and bar.

**Comment by aszenz** [comment]
Cool, feel free to close the issue.

**Comment by apps-caraga** [comment]
I know this is already resolved but just a quick question. What's the difference (in performance for example) in joins thru this approach vs joins in a view in the database itself? I tend to use views for fixed joins, i.e., joins that are always needed and don't need to be dynamically built thru the URL. That way, it is possible to simply access the joined data via `api.php/records/{viewName}`

**Comment by mevdschee** [comment]
@apps-caraga the joins the API does are not real joins and only work for result sets up to 5000 rows. A view is more generic and more performant and provides more flexibility for filtering.

**Comment by daniol** [comment]
A note in the documentation (README) would be useful, pointing that for one-to-many relationships (INNER JOIN) an API query over a view might be easier than trying to join tables, also if the column names don't follow the standard conventions.

**Comment by mevdschee** [comment]
>A note in the documentation (README) would be useful, pointing that for one-to-many relationships (INNER JOIN) an API query over a view might be easier than trying to specifying joins

True, it may be good to remind people that views can be used. On the other hand the reflection on the views is less good, so I'm not entirely sure.

> also if the column names don't follow the standard conventions.

You mean foreign key constraints? Because joins don't look at the naming.
