### ISSUE TITLE
mask the api: help wanted

### ISSUE THREAD

**Issue by nik2208** [mevdschee/php-crud-api#956]
I'm in this situation: I need to give external access to my db but I don't want too give to many infos about what's under the hood.

So I rewrited my endpoint at reverse proxy level so that to get access `mysite.com/api.php/records/mytable?filter=uuid,eq,sampleuuid&filter=text,eq,sampletext` they simply do `mysite.com/sampleuuid/sampletext` and the rewrite rule does the trick:
`rewrite ^/([^/]+)/([^/]+)/?$ /api.php/records/mytable?filter=uuid,eq,$1&filter=text,eq,$2&filter=active,eq,1&include=text last;`

I'm wondering: would I be able to achieve the same result using customization handler? if yes, how?

**Comment by mevdschee** [comment]
>but I don't want too give to many infos about what's under the hood.

Why is that? It is not providing security of any kind.

> would I be able to achieve the same result using customization handler? 

Maybe yes, but I don't see why you should. You would be writing an (inconsistent) routing engine if you do. It seems you want to redefine the routes. A rewriterule would work fine for that. But yes, a customizationHandler can redefine the request in any way you want.

**Comment by nik2208** [comment]
> Why is that? It is not providing security of any kind.

the "foreign" team do not know the library and I don't want them to eventually play around with parameters: I want them to use exactly what I want them to use, nothing else. 

> Maybe yes, but I don't see why you should. You would be writing an (inconsistent) routing engine if you do. It seems you want to redefine the routes. A rewriterule would work fine for that. But yes, a customizationHandler can redefine the request in any way you want.

it is just to keep the logic at library level and not to spread it around.

> What did you try? Did you try to create a new Request in the beforeHandler using RequestFactory::fromGlobals()? What problems did you run into? Please study the code and ask questions when you get stuck.

I havent tried that much because I'm not familiar with php requestfactory and before even starting I wanted to know if it could be done.
Just to be more accurate: this instance of api.php is only serving this particular endpoint: no other requests would be sent other than those towards that partucilar table.
So I was wondering, instead of rewriting the request at proxy level, would I be able in the request handler to get the route and prepare the request like I would do in [authorization middleware](https://github.com/mevdschee/php-crud-api#:~:text=%27authorization.recordHandler%27%20%3D%3E%20function%20(%24operation%2C%20%24tableName)%20%7B)?

I would also like to remap the response to send it without the wrapping 'records' object

**Comment by mevdschee** [comment]
>would I be able in the request handler to get the route and prepare the request 

Yes, I believe you can.

>I would also like to remap the response to send it without the wrapping 'records' object

You are not the first, see: https://github.com/mevdschee/php-crud-api/issues/564#issuecomment-519438132

**Comment by nik2208** [comment]
I'm receiving the error `Too few arguments to function Tqdev\\PhpCrudApi\\ResponseFactory::fromObject()` but from the code it seems to expect 2 argoments, not 3

**Comment by mevdschee** [comment]
It can be 0 as it is the flags variable from: https://www.php.net/manual/en/function.json-encode.php

**Comment by mevdschee** [comment]
Any further questions?

**Comment by nik2208** [comment]
not at the moment sorry for the late reply
