### ISSUE TITLE
Unable to clear the $_SESSION['claims'] when using jwtAuth

### ISSUE THREAD

**Issue by apps-caraga** [mevdschee/php-crud-api#960]
I was able to get the JwtAuthMiddleware to work with  [Keycloak](https://github.com/keycloak/keycloak) SSO server thru its javascript adapter.   The `keycloak.js `adapter has a `keycloak.logout()` function  which deletes the session on the Keycloak server but it seems there is no way to clear the session data (`$_SESSION['claims']`) created by api.php. Any suggestion on this?

**Comment by mevdschee** [comment]
If I read the code, then any malformed token will reset the `$_SESSION['claims']`. Did you try that?

**Comment by apps-caraga** [comment]
I just did and it works, although it seems hackish 😁. Anyway, just in case someone else gets this same issue, you have to send a malformed header, i.e.,` 'X-Authorization':'Bearer string-that-is-not-a-valid-token'` because an empty header will not clear the session.

Thanks for the quick help.
