### ISSUE TITLE
Multiple grouped filters

### ISSUE THREAD

**Issue by MarkusKuhfuss** [mevdschee/php-crud-api#961]
Hi,
i need a filter like this:

(field1=value or field2=value) and field3=value

I tried so much variations but nothing work for me. Could you please tell me how ?

Regards
Markus

**Comment by pottertech** [comment]
This should get you close to the query you want:

GET /records/categories?filter1=field1,eq,value&filter2=field2,eq,value&filter=field3,eq,value

Note the "filter1" and "filter2" indicates and OR when you add a number to the term "filter"

**Comment by MarkusKuhfuss** [comment]
@pottertech No this doesn't work.
@thipages Ok, very nice but if the result is correct;
filter=field1,eq,val1&filter=field3,eq,val3&filter1=field2,eq,val2&filter1=field3,eq,val3

i will end up in a very, very big query string :-(

Maybe i need another solution ...

**Comment by thipages** [comment]
just tried with 6 ORs and 1 AND. Lets see
You can right it also in a simpler manner ('A' OR 'B') AND 'C') . Quotes are still required

**Comment by MarkusKuhfuss** [comment]
I will give it a try. Maybe i will wait for the repsonse of the developer.

**Comment by mevdschee** [comment]
I don't know what to say here. Great advice by @pottertech and fabulous work of @thipages ... just wow :-) ... and if you need a very complicated query, then maybe create a view.. or switch to https://www.treeql.org/ 

Good luck!

**Comment by mevdschee** [comment]
@thipages I added a link to your tool to the README, thank you!

**Comment by MarkusKuhfuss** [comment]
Ok, thanks to all!
