### ISSUE TITLE
One to many JOIN is not supported?

### ISSUE THREAD

**Issue by kohki-shikata** [mevdschee/php-crud-api#963]
Hi there.
First of all, I appreciate that you people provide this awesome library.

Today, I want to ask you a question about join. Accoding to README.md, join parameter is implemented like SQL statement JOIN, and response nested table data.

The example shown on README.md, it is an example for many to many relationship. I would like to use one to many or many to one pattern, it was not worked correctly as I expected.

My relationships for tables like below:

```
CREATE TABLE Categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  name TEXT
);

CREATE TABLE Products (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  category_id INTEGER
  name TEXT,
  FOREIGN KEY (category_id) REFERENCES Categories(id)
);
```

This is for SQLite3. Actually, I think this is not particular one. Then, I hit an endpoint `http://localhost:8000/records/Products?join=Categories`, response is like below:

```
{
    "records": [
        {
            "id": 1,
            "name": “Carrot",
            “category_id”: 1
        },
...
```
But, what I expected is
```
{
    "records": [
        {
            "id": 1,
            "name": “Carrot”,
            “Categories”: [
                   {
                          “id”: 1,
                          “name”: “Vegetables"
                   }
            ]
        },
...
```

I tried many pattern of request and table structures, at this time my guess is PHP CRUD API does not support one to one, or one to many relationship join, only support for many to many? Is this correct? Currently, I create mid table Products and Categories, but if I could possible, I want to choose smarter way.

Thanks.

**Comment by johnwanjohi** [comment]
GET /records/posts?join=comments,users&join=tags

**Comment by johnwanjohi** [comment]
Please use the query like this GET /records/posts?join=comments,users&join=tags

**Comment by kohki-shikata** [comment]
Thank you for your reply.
Do you mean it is necessary for a JOIN table to realize this?
I had been tested the query you showed, it worked with JOIN table, but not worked without JOIN table.

**Comment by kohki-shikata** [comment]
I would like to do same equivalent without JOIN table:
```
SELECT Products.name, Categories.name FROM `Products` LEFT OUTER JOIN `Categories` ON Products.category_id = Categories.id;
```

**Comment by kohki-shikata** [comment]
I have been trying to test these few hours, finally succeeded what I expected one to many relationship. Sorry, somthing had been wrong settings.
