### ISSUE TITLE
dbAuth with Safari/Mobile Safari or PWA

### ISSUE THREAD

**Issue by kohki-shikata** [mevdschee/php-crud-api#965]
Hey there!

I'm working on a web app for my company, kind of like an SFA/CRM tool. I'm using Next.js on Vercel for the frontend and PHP CRUD API with SQLite for the backend, and I'm using Fetch API for all the connections.

So, I tried to add user authentication with the dbAuth middleware, but I'm having some issues and I was hoping you could help me out.

First, it works great on Chrome and Firefox on PC/Mac/iOS/Android, but Safari on Mac and iOS doesn't behave like I expected, even when I turn off the Intelligent Tracking Prevention option on the iOS preference app.

Second, I need to make the app work as a PWA, and it works on Android but not on iOS. I think it might be related to ITP, but I have no clue how to work around it.

I love the dbAuth middleware, it's awesome compared to JWT. Do you know of a smarter way to use dbAuth with iOS? Or maybe I'm doing something wrong and there's a better way to do it?

Thanks!

**Comment by kohki-shikata** [comment]
Update:
Sign in on PWA app suceeded. Something I implemented was wrong. Please forget about this.

**Comment by mevdschee** [comment]
> I need to make the app work as a PWA, and it works on Android but not on iOS. I think it might be related to ITP, but I have no clue how to work around it.

Nobody can help you with such a high level description. Please post a code example and/or an error message that is specific to this project on your next issue. Kind regards, Maurits
