### ISSUE TITLE
implement midlewares

### ISSUE THREAD

**Issue by nepriantodeveloper** [mevdschee/php-crud-api#966]
how to implement middleware on config?

**Comment by mevdschee** [comment]
Please rephrase your question and be more detailed. What is it you want to achieve? What is it you want to know? What is the solution to the problem you expected? What did you try? What error messages and/or problems did you run into? With answers to those questions I may be able to help you. Kind regards, Maurits

**Comment by nepriantodeveloper** [comment]
in advance thanks for your reply, I want my api to be limited by api key which is in my users table, every request to api must send api key header

The following is the middleware code that I have created

$config = new Config([
        // 'driver' => 'mysql',
        // 'address' => 'localhost',
        // 'port' => '3306',
        'username' => 'root',
        'password' => '',
        'database' => 'php_crud_api',
        'debug' => true,
        'middlewares' => 'apiKeyDbAuth.mode',
        "apiKeyDbAuth.header"=> "X-API-Key",
        "apiKeyDbAuth.usersTable"=>"users",
        "apiKeyDbAuth.apiKeyColumn"=>"api_key"
    ]);
    $request = RequestFactory::fromGlobals();
    $api = new Api($config);
    $response = $api->handle($request);
    ResponseUtils::output($response);

[https://github.com/nepriantodeveloper/php-crud-api-auto/blob/main/error.png](url)

<br />
<b>Fatal error</b>:  Uncaught Exception: Config has invalid middleware key 'apiKeyDbAuth.header' in C:\laragon\www\php-api-auth\api.php:4559
Stack trace:
#0 C:\laragon\www\php-api-auth\api.php(12422): Tqdev\PhpCrudApi\Config\Config-&gt;__construct(Array)
#1 {main}
  thrown in <b>C:\laragon\www\php-api-auth\api.php</b> on line <b>4559</b><br />

**Comment by nepriantodeveloper** [comment]
I have successfully implemented middlewares, but how do I limit the displayed columns?

**Comment by nepriantodeveloper** [comment]
I have successfully implemented middlewares, but how do I limit the columns that appear, for example the email and mobile password fields

**Comment by mevdschee** [comment]
>could be an array like this

Yes, using `in_array` you can write that:

    return !($tableName == 'users' && in_array($columnName, ['password','api_key']));

I hope that helps. Kind regards, Maurits
