### ISSUE TITLE
Support spatial data types

### ISSUE THREAD

**Issue by tigellus** [mevdschee/php-crud-api#97]
When trying to list all records from a table that contains [spatial data types like GEOMETRY,](https://dev.mysql.com/doc/refman/5.7/en/spatial-datatypes.html) the GET returns no records.

**Comment by mevdschee** [comment]
Which database are you on?

**Comment by tigellus** [comment]
Yeah sure. Database is mysql, here comes the create table script
`CREATE TABLE `reg_hotels` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(50) NOT NULL,
 `address` text NOT NULL,
 `city` varchar(50) NOT NULL,
 `postal_code` varchar(10) NOT NULL,
 `country` varchar(50) NOT NULL,
 `GPS_location` point NOT NULL,
 `contact_name` varchar(50) NOT NULL,
 `contact_phone` varchar(50) NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1
`

**Comment by mevdschee** [comment]
It seems spatial indexing is supported from msyql 5.7.5 on InnoDB (see: https://dev.mysql.com/doc/refman/5.7/en/optimizing-spatial-analysis.html), so people may want to use this indeed. I guess that accepting and returning a WKT representation would be the preferred solution in this case. Using the 'ST_AsText' stored procedure when reading from the database and 'ST_GeomFromText' when writing. Can you confirm this is what you expect?

**Comment by pottertech** [comment]
I have MySQL tables using a field named geom defined as GEOMETRY.  I put data into the geom field using the 'GeomFromText' function.  I am wondering if you could expand the filters to support some of the common spatial queries using WKT which might look like:
api.php/locations?filter[]=geom,intersects,POINT(15, 25)
api.php/locations?filter[]=geom,contains,POLYGON((30 10, 40 40, 20 40, 10 20, 30 10))
these would translate to a query that looks something like:
SELECT * FROM locations where ST_Contains(geom, GeomFromText('POLYGON((30 10, 40 40, 20 40, 10 20, 30 10))')

**Comment by mevdschee** [comment]
Yes, I fully understand what you are trying to achieve and why it cannot be stored in TEXT field. I see that you also need several new operators that are actually functions. That is also a challenge.

**Comment by pottertech** [comment]
I think an edit to "protected function convertFilter($field, $comparator, $value)" might give us what we want by adding a few new cases:

switch (strtolower($comparator)) {
  case 'intersects': 
         $comparator = null; 
         $value = 'ST_Intersects($field, GeomFromText(' . $value . '))'; 
        $field = null; 
        break; 
I think there would have to be a little clean up of the SQL to remove the empty "" after the 'WHERE' from the empty field value, but this should get you close.

**Comment by ubergeekzone** [comment]
This would need to go into the listCommandInternal i would believe. and a
case/if statement would be in order for the SELECT SQL.

Thanks

Amy BridgesCEO & Full Stack Web Developer

(678) 872-3085 | invoate.com <http://www.invoate.com>
<http://www.invoate.com/>

[image: Twitter]  <http://www.twitter.com/invoate> [image: Facebook]
<http://www.facebook.com/invoate> [image: Google +]
<https://plus.google.com/+Invoate> [image: LinkedIn]
<https://www.linkedin.com/in/amy-bridges-ab33b336> [image: Skype]
<https://htmlsig.com/signatures/001C01XJ2/atlantawebco> [image: Github]
<http://www.github.com/ubergeekzone>

**Comment by mevdschee** [comment]
It should also detect the geometry fields when not used in a filter, like it detects and handles binary fields. What type(s) are reported for the geometry fields?

**Comment by ubergeekzone** [comment]
@mevdschee https://dev.mysql.com/doc/refman/5.7/en/spatial-datatypes.html

**Comment by pottertech** [comment]
So MySQL reports the field type as "geometry" but your API reports it out as "string" right now.

**Comment by pottertech** [comment]
The valid spatial data types in MySQL are:
    GEOMETRY, POINT, LINESTRING, POLYGON, MULTIPOINT, MULTILINESTRING, MULTIPOLYGON and GEOMETRYCOLLECTION. 

The GEOMETRY type can store geometry values of any type. The other single-value types (POINT, LINESTRING, and POLYGON) restrict their values to a particular geometry type. The smartest thing to do is to only use GEOMETRY as a type so you can normalize, join, etc across tables and spatial data types without having to worry about conversions of any kind from a spatial aspect.

**Comment by pottertech** [comment]
Just to help people with older MySQL versions say >= 5.5 and <= 5.7 you can still use spatial indexes by ensuring your table is using the MyISAM engine.  I offer a small example from tigellus with minor modifications:

CREATE TABLE `reg_hotels` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(50) NOT NULL,
 `address` text NOT NULL,
 `city` varchar(50) NOT NULL,
 `postal_code` varchar(10) NOT NULL,
 `country` varchar(50) NOT NULL,
 `GPS_location` geometry NOT NULL,
 `contact_name` varchar(50) NOT NULL,
 `contact_phone` varchar(50) NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1

The MyISAM will work with MySQL 5.5, 5.6 & 5.7 and I change GPS_location to geometry type as it is much more versatile.

**Comment by mevdschee** [comment]
Note that MyISAM does not support FK constraints and MyISAM will therefor not work with this project as relations are found based on the reflection of these constraints.

**Comment by mevdschee** [comment]
I've found that the reported type for geometry is 255, see:

http://stackoverflow.com/questions/1691390/php-mysqli-fetch-field-data-type

I think the same approach as with binary can be followed.

**Comment by pottertech** [comment]
Well I think you just document that FK does not work for MyISAM as it is up to the developer which table type they need to use.  For one project that I am working on I am limited to MySQL 5.6 right now but I am not using FKs so I am hoping this will work out.

**Comment by mevdschee** [comment]
@pottertech I created feature req #101 for this, check it out.

**Comment by mevdschee** [comment]
I'm making a list of geometrical filters:

- ST_Contains()	Whether one geometry contains another
- ST_Crosses()	Whether one geometry crosses another
- ST_Disjoint()	Whether one geometry is disjoint from another
- ST_Equals()	Whether one geometry is equal to another
- ST_Intersects()	Whether one geometry intersects another
- ST_IsClosed()	Whether a geometry is closed and simple
- ST_IsSimple()	Whether a geometry is simple
- ST_IsValid()	Whether a geometry is valid
- ST_Overlaps()	Whether one geometry overlaps another
- ST_Touches()	Whether one geometry touches another
- ST_Within()	Whether one geometry is within another

Am I missing something?

**Comment by pottertech** [comment]
I think this is a great addition to the API. The functions you defined are perfect and I do agree that the utility functions ( ST_IsClosed(), ST_IsSimple() and ST_IsValid() )  are not really not valuable as people should validate their data and have its attributes (closed, simple, valid) captured/understood before the INSERT into the DB.

**Comment by mevdschee** [comment]
Agree, these complex parsing and validation checks can better be done client-side.

**Comment by pottertech** [comment]
No pressure, but it would be nice to know if and/or when you would be able to add in these spatial functions? I am ready to support you with any testing help you might need.

**Comment by mevdschee** [comment]
@tigellus: Your issue should be resolved. 

@pottertech: I'm working on the filters now.

**Comment by mevdschee** [comment]
It is ready.. :smile:

**Comment by pottertech** [comment]
Maurits,

My tests from home went very well.  I will test it tomorrow at work where I have a database of with over 4 billion records of various spatial data and I will let you know how well it performs with larger data sets.

Did you also implement a NOT (!)  feature?  If so, I am not sure how to use it with the filter[].  Also, how would I use the IsValid or IsSimple with filter[]?

Sincerely,

—Skip

**Comment by pottertech** [comment]
Maurits,

I got home late, but I will test it tonight and tomorrow to see if I find any issues.  Thanks again for the great work!

Sincerely,

--Skip

**Comment by mevdschee** [comment]
I'll change the filter system to allow for negation as that seems like a very valid need, thank you for helping me to make the software great!

**Comment by pottertech** [comment]
Well you had the great idea for such a wonderful API.  I am just lending my experience with spatial data to repay your great work!

I tested your API at work with MySQL and it is working well.  I have not found any errors at all.  I do not have any of the other databases available so I can only test MySQL.

I do look forward to seeing the next update with negation.  This will make your API the best available that I have seen.  If you want to make more changes after you are done with negation, let me know.  I am a serious user doing real world, very large database work with your API and it is making for a wonderful environment for getting answers from out data.

Thanks again!

Sincerely,

—Skip

**Comment by mevdschee** [comment]
Negation is now supported on all filters (including spatial).

**Comment by pottertech** [comment]
So fast!?!?! You are amazing!  So how do I use it?  Give me 1 quick example please...

Sincerely,

—Skip

**Comment by pottertech** [comment]
Oh never mind!  I see you updated the docs too!  Great job!  Going to install it on my web site for testing and then at work tomorrow. As always, I will report back…

Sincerely,

—Skip

**Comment by pottertech** [comment]
Wow! Just “WOW” !

The negation ability has simply doubled the capability with now you can formulate queries.  Truly a work of art my friend, you have done amazing work.

Thank you so much.  I will report back tomorrow on how it does against the very big database but I am sure it will work just the same.  But now my queries will be much more dynamic and easier to construct.

Sincerely,

—Skip

**Comment by mevdschee** [comment]
Thank you very much for your kind words.

**Comment by pottertech** [comment]
OK, I tested the API at work today and it works very well.  I can not find any decline in speed and the new negation feature helps to make a lot more query combinations possible. Again, thank you so much for the hard work and high level of quality you have in your work.

Sincerely,

—Skip

**Comment by mevdschee** [comment]
Fixed a small bug that caused the spatial filter test to fail and added the 'between' filter for your convenience.

**Comment by pottertech** [comment]
Congratulations on the new and improved version!  I think you can close this thread as you have done a fine job adding support for spatial data.

**Comment by mevdschee** [comment]
@pottertech Thank you for your kind words.
