### ISSUE TITLE
Custom responses for authorization.tableHandler

### ISSUE THREAD

**Issue by jankocian** [mevdschee/php-crud-api#972]
Hi all, 
I'd like to return a custom error message for failed authorization.tableHandler. Now it gets me "table not found" only, but I want to differentiate between several states. 

One of the use cases for me is to check the current date&time to asses whether the submission can be accepted. I found the tableHandler to be the best place for that, cause the validation middleware works only on fields basis...

Thanks a lot in advance,
Jan

**Comment by apps-caraga** [comment]
The authorization handler just returns true or false depending one is authorized to access a table. I don't fully get the use case yet (need sample or further description) but perhaps the validation handler is better fit for your requirement. The idea to to validate the submission date/time vs some pre-identified valid submission date/time (which may be stored in session). You can return custom message from validation hander if the validation rule is not met.

**Comment by apps-caraga** [comment]
Not sure if this is still needed, seeing there's no response yet from @jankocian 

But just a quick sample. Let's say you want to check the submission time vs some pre-determined time. (`$banned_until` in this example) . In the example, $banned_until is hard-coded but you can also put it in a session variable and the name of the table is `sampleTable`. We'll also use unix timestamp so you need to convert the time to that format. This is to simplify the computation of the difference between the dates/time, but you can also use DateTime object, date_dif or whatever way to complicate your life.  😁✌

```
		'validation.handler' => function ($operation, $tableName, $column, $value, $context) {
			$submission_time = time();
			$banned_until = 1686484800;// June 11, 2023 12:20:00 PM GMT+08:00
			$dif  = $banned_until - $submission_time;
			return ($tableName == 'sampleTable' && $dif >= 1) ? "Operation not yet allowed, try again in ". round($dif/60,2) ." minutes": true;
		},
```

Assuming your submission is before the sample date, you'll get the following response:

```
{
    "code": 1013,
    "message": "Input validation failed for 'sampleTable'",
    "details": {
        "data": "Operation not yet allowed, try again in 4.13 minutes"
    }
}
```

**Comment by mevdschee** [comment]
@jankocian any update?

**Comment by jankocian** [comment]
Hey guys, thanks a lot for such a response! 

My point was, that the validation I want to perform does not relate to any of the fields/columns. It technically is not an input validation anyway, right?

And as I process (and show) the input validation on the frontend, I'd much prefer to have a different way of returning such an error back - not associated to any field. Is there a preferred way to do it?

**Comment by mevdschee** [comment]
>I'd like to return a custom error message for failed authorization.tableHandler. Now it gets me "table not found" only

If you don't have access you can also not be sure that the table exists.

>It technically is not an input validation anyway, right?

And as I process (and show) the input validation on the frontend. Why would you even want to show the form on the front-end if you don't meet the conditions to fill it?

>Is there a preferred way to do it?

I think the suggested solutions work on the server side of things. Not being allowed to submit a form should be handled before the form is shown, thus on the front-end and not by the back-end. Why fill a form that you can't submit?

I hope this helps.

Kind regards,

Maurits

**Comment by apps-caraga** [comment]
Admittedly, my proposed solution does not answer the question which is specifically about `authorization.tableHandler`. It is more of a possible solution to the mentioned use case which is to
> check the current date&time to asses whether the submission can be accepted

Anyway, if you don't want to process a user input for some reason, it would seem more sensible to not show the form to the user at all.

> It technically is not an input validation anyway, right?

I assume (and I may be wrong) that the submission date/time can actually be considered as some kind of input ( from the system, not from the user) which you can validate.
