### ISSUE TITLE
501 on register function

### ISSUE THREAD

**Issue by harri00413** [mevdschee/php-crud-api#974]
Goodday and thanks for this api you created. I have a question on using the js-crud-api. 
My experience level is a few years html and css, js mediocre and new (few months) to php.

I have a login / signup page where the jscrudapi is called `const jca = jscrudapi('api.php');`
and then `const b = { username, password }; jca.register(b);` 
the error I get is
[Error] Failed to load resource: the server responded with a status of 501 () (register, line 0)
url: (https://data.zzsites.nl/api.php/register)
Testing on a host with nginx and php8.
my config in api.php: 
```
    $config = new Config([
   
        'username' => '**********',
        'password' => '**********',
        'database' => '************',
        'middlewares' => 'dbAuth,authorization',
        'dbAuth.usernameColumn' => 'e-mail',
        'dbAuth.passwordColumn' => 'Wachtwoord',
        'dbAuth.registerUser' => '1',
        'dbAuth.loginAfterRegistration' => '1',
        'authorization.tableHandler' => function ($operation, $tableName) {
            return $tableName != 'users';
        }
    ]);
```
So, what am I doing wrong? 
Searched through the documentation and Google for some weeks now, but there are no answers there. 

While I'm typing, is there a reason why you can only add username & pw to the users table and not name etc?

**Comment by thipages** [comment]
Hi,

from
```javascript
const b = { username, password }; 
jca.register(b);
```
you should write
```javascript
jca.register(username, password);
```

Note : this question may be better in the [jca repo issues](https://github.com/thipages/js-crud-api/issues)

**Comment by mevdschee** [comment]
ModSecurity says: Request content type is not allowed by policy. Try disabling ModSecurity. :-)

**Comment by mevdschee** [comment]
I'm not supporting ModSecurity, so I'll close this issue. Feel free to open a new one if you run into problems.

**Comment by harri00413** [comment]
Ha Maurits, 

So what you’re saying I will not be able to use PHP-CRUD-API?

Groeten,

Frank Harland

**Comment by mevdschee** [comment]
I don't like your reaction and/or implication at all. Locking and considering a block. Have a nice day.
