### ISSUE TITLE
Multipolygon Support?

### ISSUE THREAD

**Issue by Dherlou** [mevdschee/php-crud-api#977]
Hey there,

we are using this API to save/retrieve geo data, especially multipolygons.

I noticed that the API fails when working with multipolygons:
- GETing results in a blank 200 response
- POSTing/PUTting results in an sql error `SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field`

Upon further debugging I found out that the multipolygon field is not detected as a geometric field, hence the value is treated as a typical scalar value, doesn't undergo the WKT-parsing and then fails the syntax check upon inserting.

When I add `'multipolygon' => 'geometry'` to the `$toJdbc` array 
https://github.com/mevdschee/php-crud-api/blob/9307ae2d75f8e6cd44071199b440b6728588c6db/api.php#L7356, it seems to work fine (at least from my POV - we are using MariaDB).

Almost all database types ([MySQL](https://dev.mysql.com/doc/refman/5.7/en/gis-class-multipolygon.html#:~:text=MultiPolygon%20Assertions&text=A%20MultiPolygon%20is%20a%20regular,Polygon%20values%20in%20the%20MultiPolygon%20.)/[MariaDB](https://mariadb.com/kb/en/multipolygon/), [PostgreSQL](https://postgis.net/workshops/postgis-intro/geometries.html#collections) and [SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/spatial/multipolygon)), probably except SQLite (or at least I couldn't find reliable information) seem to support it and the type support for multipolygons seems to be already implemented in https://github.com/mevdschee/php-crud-api/blob/9307ae2d75f8e6cd44071199b440b6728588c6db/api.php#L7748 and https://github.com/mevdschee/php-crud-api/blob/9307ae2d75f8e6cd44071199b440b6728588c6db/api.php#L10660.

Is there a specific reason why the multipolygon type is 'deactivated'? Are there any concerns in enabling it (at least in our installation)?

**Comment by mevdschee** [comment]
Hi Lucas Kinne,

Thank you for reporting this issue.

>Is there a specific reason why the multipolygon type is 'deactivated'? 

No, I can't think of any. In reality it really is only a type constraint on a 'geometry' column.

>Are there any concerns in enabling it (at least in our installation)?

No, I think it was left out by accident. Feel free to do a PR.

Kind regards,

Maurits van der Schee

**Comment by mevdschee** [comment]
I checked some more and Postgresql could be improved:

https://www.postgresql.org/docs/current/datatype-geometric.html

MariaDB could also be improved:

https://www.postgresql.org/docs/current/datatype-geometric.html

It seems it can be made more complete.

**Comment by Dherlou** [comment]
Ah, you are right. It seems that some other bits might be missing as well. We just use POINT and MULTIPOLYGON, so I didn't notice the rest. :)

While MariaDB supports multipolygons natively, it seems that you need the "[PostGIS](https://postgis.net/)" extension for PostgreSQL, which among others adds [Multipolygon](https://postgis.net/workshops/postgis-intro/geometries.html#collections). The same might be true for [SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index#:~:text=SpatiaLite%20is%20an%20open%20source,implementation%3A%20almost%20complete%20SQL%2D92) for SQLite, but I am only familiar with MySQL/MariaDB and the documentation seems hard to understand.

**Comment by mevdschee** [comment]
I think most databases use an underlying "geometry" column type, which is what I rely on.

I think the following lines:

    'polygon' => 'geometry',
    'point' => 'geometry',

should be:

    'point' => 'geometry',
    'linestring' => 'geometry',
    'polygon' => 'geometry',
    'multipoint' => 'geometry',
    'multilinestring' => 'geomet,ry'
    'multipolygon' => 'geometry',

In the file [TypeConverter.php](https://github.com/mevdschee/php-crud-api/blob/main/src/Tqdev/PhpCrudApi/Database/TypeConverter.php). Agree?

**Comment by Dherlou** [comment]
I think so. At least that is what got us up and running. :)

**Comment by mevdschee** [comment]
I'll create a new release later today. Thank you!

**Comment by mevdschee** [comment]
Released in [v2.14.21](https://github.com/mevdschee/php-crud-api/releases/tag/v2.14.21)
