### ISSUE TITLE
Question: How can I use this with planetscale.com?

### ISSUE THREAD

**Issue by Mashiane** [mevdschee/php-crud-api#978]
Hi

I just discovered this cloud back-end service that uses MySQL.

I am able to connect with a GUI however I cant figure out how to make this work with this rest api.

Can you please advise.

This is the output I get..

{"code":9999,"message":"SQLSTATE[HY000] [1105] unknown error: Code: UNAVAILABLE\nserver does not allow insecure connections, client must use SSL\/TLS\n"}

Thanks a lot.

**Comment by SMN947** [comment]
This is something that is not currently possible. However, it appears to be in the features bucket, as reported in #923 **Specify options for database connection in configuration**.

**Comment by mevdschee** [comment]
My answer in #923:

> You might be able to workaround this limitation using stunnel as client, see: https://www.stunnel.org/
> 
>     * https://serverfault.com/questions/262484/connecting-to-mysql-securely-mysqls-ssl-vs-stunnel-vs-ssh-tunneling
> 
>     * https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ssl-tunnel-using-stunnel-on-ubuntu
> 
>     * https://www.percona.com/blog/mysql-encryption-performance-revisited/
> 
> 
> I have found that somebody was trying to use stunnel in client mode for mysql and failed, see:
> 
>     * https://forums.mysql.com/read.php?30,620633,620633#msg-620633
> 
> 
> If you succeed, please let us know. I hope this helps. Kind regards, Maurits
> 
> NB: Do consider SSH tunnels (that's what I use), as they are more secure and faster.
