### ISSUE TITLE
MS SQL boolean column not updated correctly

### ISSUE THREAD

**Issue by thetechnician94** [mevdschee/php-crud-api#981]
When trying to update a bit column in MS SQL, values evaluate to 'true' which are not expected. Specifically 'false' will update the column to a 1. Only a 0 will actually update the column correctly. 

That is in the function `convertInputValue` the return for boolean should be:

`return filter_var($value, FILTER_VALIDATE_BOOLEAN) ? 1 : 0;` 

so that 'false' converts to 0 instead of 1

**Comment by mevdschee** [comment]
Yes.. good find

**Comment by mevdschee** [comment]
Fixed in v2.14.22: Fix boolean parsing
