### ISSUE TITLE
error in Wordpress authentication middleware

### ISSUE THREAD

**Issue by nkappler** [mevdschee/php-crud-api#984]
relates to: #982

I've just updated to the version where the `user_pass` member is removed from the result, however it isn't working unfortunately.
That was my mistake though, because the code changes I suggested didn't quite work - sorry 😅 
<hr />

Since `WPUser` is an object, not an array, and `user_pass` is part of the `data` member, the three unset calls need to be changed from
```php
unset($user['user_pass']);
```

to
```php
unset($user->data->user_pass);
```

I have tested it and it works 🙂

Also, in the logout path, the order of operations is:
1. call `wp_logout`
2. set `$user` to `wp_get_current_user`

I'm not sure if this works, probably `wp_get_current_user` needs to be called before `wp_logout` otherwise it will return `0` which is probably not intended, is it?

**Comment by mevdschee** [comment]
Fixed in v2.14.24

**Comment by mevdschee** [comment]
>which is probably not intended, is it?

it is.. it shows the current user.. ID=0 if logout succeeded..
