### ISSUE TITLE
unable to update record when key column value = 0

### ISSUE THREAD

**Issue by isi-dwade** [mevdschee/php-crud-api#99]
When the record key value equals "0" (a string of zero), the record doesn't update. this is due to the code in functions parseRequestParameter and processKeyParameter.  the checks coerce a value of "0" to a boolean false before checking.
For parseRequestParameter I changed the first IF to:
`if (strlen($request) == 0) return false;
`
For processKeyParameter I changed the first IF to:
`if ($key === false || strlen($key) == 0) return false;`

**Comment by mevdschee** [comment]
I'm glad that that works for you, but using "0" as a primary key value is not very common. I suggest that you use an auto-incrementing integer, starting at 1 and name it "id".

**Comment by isi-dwade** [comment]
It may be uncommon, but it is a valid value… as could be a negative value.

In my case, it is a common value we use…
I just wanted to help make your library able to handle any condition.

Thanks for writing the library and your attention.

Derek Wade

**Comment by mevdschee** [comment]
Thank you very much for feedback. The code is very limited in what it accepts in the primary key field and this is just one of the many constraints. These limitations are to keep the code simple, secure and fast. The code is very opinionated about what you do with the database and limited in it's capabilities. You should either use an UUID or an auto-incrementing integer starting at 1, other cases are not supported as primary keys. I'll update the documentation to reflect this.

**Comment by mevdschee** [comment]
see: 811f9367196c567accbf3664c46f3af244af2408
